// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {BrowserAudio} from './audio.ts';import {BrowserCaptureTarget} from './browser-capture-target.ts';
async function environment(run:(f:{audio:BrowserAudio;gains:Array<{gain:{value:number};disconnected:boolean}>;nodes:Array<{port:{messages:unknown[];onmessage:((event:{data:{type:string;buffer:ArrayBuffer}})=>void)|null}}> ;gum:MediaStreamConstraints[];sent:ArrayBuffer[];settings:{echoCancellation:boolean;noiseSuppression:boolean;autoGainControl:boolean};tracks:Array<{readyState:string}>;fault:(count:number,permission?:boolean)=>void;defer:()=>{resolve:()=>void}})=>Promise<void>){
 const originals=new Map(['window','navigator','AudioContext','AudioWorkletNode'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)])),gains:Array<{gain:{value:number};disconnected:boolean}>=[],nodes:Array<{port:{messages:unknown[];onmessage:((event:{data:{type:string;buffer:ArrayBuffer}})=>void)|null}}>=[],gum:MediaStreamConstraints[]=[],sent:ArrayBuffer[]=[],tracks:Array<{readyState:string}>=[];let failures=0,permission=false;let wait:Promise<void>|undefined,complete:()=>void=()=>{};const settings={echoCancellation:true,noiseSuppression:true,autoGainControl:true};
 class Node{disconnected=false;connect<T>(next:T):T{return next;}disconnect(){this.disconnected=true;}}
 class Worklet extends Node{port={messages:[] as unknown[],onmessage:null as ((event:{data:{type:string;buffer:ArrayBuffer}})=>void)|null,postMessage:(message:unknown)=>this.port.messages.push(message)};constructor(){super();nodes.push(this);}}
 class Context{sampleRate=48000;destination={};audioWorklet={addModule:async()=>{}};async resume(){}async close(){}createGain(){const node=new Node(),value={number:1};Object.defineProperty(node,'gain',{value:{get value(){return value.number;},set value(n:number){value.number=Math.fround(n);}}});const typed=node as Node&{gain:{value:number}};gains.push(typed);return typed;}createMediaStreamSource(){return new Node();}}
 const navigator={mediaDevices:{async getUserMedia(c:MediaStreamConstraints){gum.push(c);if(wait)await wait;if(failures-->0)throw permission?new DOMException('private refusal','NotAllowedError'):Error('private refusal');const constraints=(c.audio||{}) as MediaTrackConstraints;for(const f of ['echoCancellation','noiseSuppression','autoGainControl']as const){const v=constraints[f];settings[f]=typeof v==='boolean'?v:(v as {exact:boolean}).exact;}const ownSettings={...settings,deviceId:'private-owned-device'};const track={readyState:'live',onended:null,stop(){this.readyState='ended';},getSettings:()=>({...ownSettings}),getCapabilities:()=>({echoCancellation:[true,false],noiseSuppression:[true,false],autoGainControl:[true,false]}),getConstraints:()=>constraints,async applyConstraints(c:MediaTrackConstraints){if(wait)await wait;for(const f of ['echoCancellation','noiseSuppression','autoGainControl']as const){const v=c[f];settings[f]=typeof v==='boolean'?v:(v as{exact:boolean}).exact;}}};tracks.push(track);return {getTracks:()=>[track],getAudioTracks:()=>[track]};}}};
 Object.defineProperty(globalThis,'window',{value:{AudioContext:Context,isSecureContext:true},configurable:true});Object.defineProperty(globalThis,'AudioContext',{value:Context,configurable:true});Object.defineProperty(globalThis,'AudioWorkletNode',{value:Worklet,configurable:true});Object.defineProperty(globalThis,'navigator',{value:navigator,configurable:true});const audio=new BrowserAudio(data=>sent.push(data),()=>{});
 try{await run({audio,gains,nodes,gum,sent,settings,tracks,fault(count,denied=false){failures=count;permission=denied;},defer(){wait=new Promise<void>(r=>{complete=r;});return {resolve:complete};}});}finally{await audio.dispose();for(const[key,value]of originals){if(value)Object.defineProperty(globalThis,key,value);else Reflect.deleteProperty(globalThis,key);}}
}
test('actual BrowserAudio capture bridge never requests permission; enabling creates a separate input gain',async()=>environment(async f=>{const target=new BrowserCaptureTarget(()=>f.audio.captureBinding());assert.equal(target.snapshot().active,false);assert.equal(f.gum.length,0);assert(await f.audio.enableMicrophone());assert.equal(f.gum.length,1);assert.equal(f.gains.length,2);const binding=f.audio.captureBinding()!;assert.equal(binding.gain.gain.value,1);await target.apply({field:'inputGainPercent',value:50},()=>true);assert.equal(f.gains[0].gain.value,1,'Playback/native mixer gain remains unchanged');assert.equal(f.gains[1].gain.value,.5);f.audio.stopMicrophone();assert.equal(f.tracks[0].readyState,'ended');assert(f.gains[1].disconnected);assert.equal(f.audio.captureBinding(),undefined);assert.equal(target.snapshot().active,false);}));
test('actual worklet transport composes DSP inhibition with PTT gate and never releases a refused hold',async()=>environment(async f=>{f.audio.setTransmitEnabled(false);await f.audio.enableMicrophone();const target=new BrowserCaptureTarget(()=>f.audio.captureBinding()),d=f.defer(),change=target.apply({field:'echoCancellation',value:false},()=>true),packet={data:{type:'microphone',buffer:new ArrayBuffer(1920)}};f.audio.setTransmitEnabled(true);f.nodes[0].port.onmessage!(packet);assert.equal(f.sent.length,0);f.audio.setTransmitEnabled(false);d.resolve();assert((await change).accepted);f.nodes[0].port.onmessage!(packet);assert.equal(f.sent.length,0);f.audio.setTransmitEnabled(true);f.nodes[0].port.onmessage!(packet);assert.equal(f.sent.length,1);f.audio.stopMicrophone();f.nodes[0].port.onmessage!(packet);assert.equal(f.sent.length,1);}));
test('actual desired capture settings survive mute/rearm locally and new permission request requires confirmed values',async()=>environment(async f=>{await f.audio.enableMicrophone();const target=new BrowserCaptureTarget(()=>f.audio.captureBinding());assert((await target.apply({field:'noiseSuppression',value:false},()=>true)).accepted);assert((await target.apply({field:'inputGainPercent',value:70},()=>true)).accepted);f.audio.stopMicrophone();assert(await f.audio.enableMicrophone());assert.equal(f.gum.length,3);assert.deepEqual((f.gum[2].audio as MediaTrackConstraints).noiseSuppression,{exact:false});assert.equal(f.audio.captureBinding()!.gain.gain.value,Math.fround(.7));assert.equal(target.snapshot().settings.noiseSuppression,false);}));
test('actual pending target cancellation stops the current track and cannot restart or unmute on a late API result',async()=>environment(async f=>{await f.audio.enableMicrophone();const binding=f.audio.captureBinding()!,target=new BrowserCaptureTarget(()=>f.audio.captureBinding()),d=f.defer(),operation=target.apply({field:'autoGainControl',value:false},()=>true);target.cancelPending();assert(f.audio.muted);assert.equal(f.tracks[0].readyState,'ended');assert.equal(f.audio.captureBinding(),undefined);assert.equal((await operation).reason,'cancelled');d.resolve();await Promise.resolve();assert(f.audio.muted);assert.equal(binding.current(),false);assert.equal(f.gum.length,2);}));

test('actual replacement preserves input gain/worklet and old queued ended event cannot stop its successor',async()=>environment(async f=>{
 await f.audio.enableMicrophone();const binding=f.audio.captureBinding()!,old=binding.track,ended=old.onended,target=new BrowserCaptureTarget(()=>f.audio.captureBinding());
 assert((await target.apply({field:'inputGainPercent',value:70},()=>true)).accepted);assert((await target.apply({field:'echoCancellation',value:false},()=>true)).accepted);
 assert.equal(old.readyState,'ended');assert.notEqual(binding.track,old);assert.equal(binding.track.readyState,'live');assert.equal(f.gum.length,2);assert.equal(f.gains.length,2);assert.equal(binding.gain.gain.value,Math.fround(.7));
 ended?.call(old,new Event('ended'));assert.equal(f.audio.captureBinding(),binding);assert.equal(f.audio.muted,false);assert.equal(target.snapshot().settings.echoCancellation,false);
}));
test('actual retired-track gap is inactive while logical consent and one unresolved resource slot stay owned',async()=>environment(async f=>{
 await f.audio.enableMicrophone();const binding=f.audio.captureBinding()!,target=new BrowserCaptureTarget(()=>f.audio.captureBinding()),d=f.defer(),p=target.apply({field:'noiseSuppression',value:false},()=>true);
 assert(binding.current());assert.equal(binding.track.readyState,'ended');assert.equal(target.snapshot().active,false);assert.equal(f.gum.length,2);assert.equal(await f.audio.enableMicrophone(),false);assert.equal(f.gum.length,2);
 d.resolve();assert((await p).accepted);assert.equal(f.audio.captureBinding(),binding);assert.equal(target.snapshot().active,true);
}));
test('actual cancellation in retired gap stops logical consent and blocks new grant until late candidate cleanup',async()=>environment(async f=>{
 await f.audio.enableMicrophone();const target=new BrowserCaptureTarget(()=>f.audio.captureBinding()),d=f.defer(),p=target.apply({field:'autoGainControl',value:false},()=>true);
 target.cancelPending();assert.equal((await p).reason,'cancelled');assert.equal(f.audio.captureBinding(),undefined);assert(f.audio.muted);assert.equal(await f.audio.enableMicrophone(),false);assert.equal(f.gum.length,2);
 d.resolve();for(let i=0;i<12;i++)await Promise.resolve();assert(f.tracks.every(t=>t.readyState==='ended'));assert.equal(f.gum.length,2);assert(f.audio.muted);assert(await f.audio.enableMicrophone());assert.equal(f.gum.length,3);
}));
test('actual original eight-second deadline owns pending request until settlement and never restores after expiry',async()=>environment(async f=>{
 await f.audio.enableMicrophone();let expiry!:()=>void;const target=new BrowserCaptureTarget(()=>f.audio.captureBinding(),{set(fn,ms){assert.equal(ms,8000);expiry=fn;return fn;},clear(){}}),d=f.defer(),p=target.apply({field:'echoCancellation',value:false},()=>true);
 expiry();assert.equal((await p).reason,'deadline');assert(f.audio.muted);assert.equal(await f.audio.enableMicrophone(),false);d.resolve();for(let i=0;i<12;i++)await Promise.resolve();assert.equal(f.gum.length,2);assert(f.tracks.every(t=>t.readyState==='ended'));
}));
test('actual refused replacement restores same logical gain and exact old settings without committing the request',async()=>environment(async f=>{
 await f.audio.enableMicrophone();const binding=f.audio.captureBinding()!,old=binding.track,target=new BrowserCaptureTarget(()=>f.audio.captureBinding());f.fault(1);
 const r=await target.apply({field:'noiseSuppression',value:false},()=>true);assert.equal(r.reason,'apply-refused');assert.equal(r.accepted,false);assert(r.state.active);assert.equal(r.state.settings.noiseSuppression,true);assert.equal(f.gum.length,3);assert.equal(old.readyState,'ended');assert.equal(f.audio.captureBinding(),binding);assert.equal(f.gains.length,2);
 f.audio.stopMicrophone();assert(await f.audio.enableMicrophone());assert.equal((f.gum[3].audio as MediaTrackConstraints).noiseSuppression,true,'A refused desired setting must not become a later exact preference');
}));
test('actual double refusal ends capture rather than inventing restored settings or another device',async()=>environment(async f=>{
 await f.audio.enableMicrophone();const target=new BrowserCaptureTarget(()=>f.audio.captureBinding());f.fault(2);const r=await target.apply({field:'echoCancellation',value:false},()=>true);assert.equal(r.reason,'rollback-refused');assert.equal(r.state.active,false);assert(f.audio.muted);assert.equal(f.gum.length,3);assert(f.tracks.every(t=>t.readyState==='ended'));
}));
test('actual dispose during replacement stops the late result and retains PTT and muted transport refusal',async()=>environment(async f=>{
 await f.audio.enableMicrophone();const target=new BrowserCaptureTarget(()=>f.audio.captureBinding()),d=f.defer(),p=target.apply({field:'echoCancellation',value:false},()=>true);await f.audio.dispose();d.resolve();const r=await p;assert.equal(r.accepted,false);assert.equal(f.gum.length,2);assert(f.tracks.every(t=>t.readyState==='ended'));assert(f.audio.muted);assert.equal(f.audio.captureBinding(),undefined);
}));

test('actual permission-denied replacement ends capture with no restore GUM or persisted preference',async()=>environment(async f=>{
 await f.audio.enableMicrophone();const target=new BrowserCaptureTarget(()=>f.audio.captureBinding());f.fault(1,true);const r=await target.apply({field:'echoCancellation',value:false},()=>true);assert.equal(r.reason,'rollback-refused');assert.equal(r.accepted,false);assert.equal(r.state.active,false);assert.equal(f.gum.length,2);assert(f.audio.muted);assert.equal(f.audio.captureBinding(),undefined);
}));
