// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {BrowserTablet} from './tablet.ts';import {parseTabletMessage,type TabletMessage} from './tablet-protocol.ts';import {inactiveCapture,type CaptureResult} from '../shared/browser-capture.mjs';
function fixture(){let settle!:(v:CaptureResult)=>void;const sent:unknown[]=[],calls:unknown[]=[],cancel:number[]=[];const result=new Promise<CaptureResult>(resolve=>settle=resolve);const tablet=Object.create(BrowserTablet.prototype);Object.assign(tablet,{connected:true,disposed:false,revision:2,sequence:1,navigationSequence:1,generation:0,visible:true,displayedFrameSequence:1,options:{send:(v:unknown)=>sent.push(v),onStatus:()=>{},onCapture:(v:unknown)=>{calls.push(v);return result;},onCaptureCancelled:()=>cancel.push(1)}});return{tablet:tablet as BrowserTablet,sent,calls,cancel,settle};}
const packet=(extra={})=>({type:'tablet',kind:'capture',revision:2,navigationSequence:1,schemaVersion:1,requestId:1,operation:'request',...extra}) as TabletMessage;
const ack:CaptureResult={schemaVersion:1,requestId:1,accepted:true,reason:'ok',state:inactiveCapture()};
const turn=()=>new Promise(resolve=>setImmediate(resolve));
test('actual browser parser keeps only strict capture fields and requires bounded current navigation',()=>{const parsed=parseTabletMessage(packet({deviceId:'private'}));assert(!JSON.stringify(parsed).includes('private'));assert.throws(()=>parseTabletMessage(packet({navigationSequence:0})));assert.throws(()=>parseTabletMessage(packet({operation:'change',field:'deviceId',value:'private'})));});
test('actual BrowserTablet async callback delivers only verified result for its same visible revision/navigation',async()=>{const f=fixture();f.tablet.receive(packet());assert.equal(f.calls.length,1);f.settle(ack);await turn();assert.equal(f.sent.length,1);assert.deepEqual(f.sent[0],{type:'tablet',action:'captureResult',navigationSequence:1,...ack,revision:2,sequence:2});});
test('actual Home send cancels pending browser work before any old asynchronous result can escape',async()=>{const f=fixture();f.tablet.receive(packet());(f.tablet as any).send({action:'home'});assert.equal(f.cancel.length,1);f.settle(ack);await turn();assert.equal(f.sent.length,1);assert.equal((f.sent[0] as any).action,'home');});
test('actual revision transition cancels work and discards stale callback without changing the old result',async()=>{const f=fixture();f.tablet.receive(packet());Object.assign(f.tablet,{show:()=>{},status:{textContent:''},snapshots:{cancel(){}}});f.tablet.receive({type:'tablet',kind:'state',revision:3,visible:false,loading:false,screen:'Home'});assert.equal(f.cancel.length,1);f.settle(ack);await turn();assert.equal(f.sent.length,0);});
test('actual hidden/disconnected/current-navigation gates refuse capture callbacks before work starts',()=>{for(const extra of [{visible:false},{connected:false},{navigationSequence:2}]){const f=fixture();Object.assign(f.tablet,extra);f.tablet.receive(packet());assert.equal(f.calls.length,0);}});
test('actual native page cancellation reaches the browser controller as an ordered current packet',async()=>{const f=fixture();f.tablet.receive(packet({operation:'cancel'}));assert.equal((f.calls[0] as any).operation,'cancel');f.settle(ack);await turn();assert.equal(f.sent.length,1);});

test('current Graphics completion is delivered while microphone callback is pending without replacing either operation',async()=>{
 const f=fixture(),graphics:unknown[]=[];(f.tablet as any).options.onGraphicsApplied=(v:unknown)=>graphics.push(v);
 f.tablet.receive(packet());const applied={type:'tablet',kind:'graphicsApplied',revision:2,schemaVersion:1,browserRequestId:1,accepted:true,settings:{version:1,fieldOfView:70,resolutionPercent:80,localLights:true,cameraClipping:true}} as TabletMessage;
 f.tablet.receive(applied);assert.equal(graphics.length,1);assert.equal(f.calls.length,1);assert.equal(f.cancel.length,0);assert.equal(f.sent.length,0);
 f.settle(ack);await turn();assert.equal(f.sent.length,1);assert.equal((f.sent[0] as any).action,'captureResult');assert.equal(graphics.length,1);
});
