// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {restartConsentedCapture} from './browser-capture-restart.ts';
const initial={deviceId:'private-already-consented',echoCancellation:true,noiseSuppression:true,autoGainControl:true};
function fixture(){let live=true,retired=0,stops=0;const calls:MediaStreamConstraints[]=[],published:MediaStreamTrack[]=[],made:Array<{readyState:string;onended:unknown;stop():void;getSettings():typeof initial}>=[];const old={readyState:'live',getSettings:()=>({...initial}),getConstraints:()=>({channelCount:1}),stop(){this.readyState='ended';}};let failure=0,mismatch=false,publishFails=false,deferred:Promise<void>|undefined,resolve=()=>{};
 const owner={current:()=>live,retire(){retired++;old.stop();},async acquire(c:MediaStreamConstraints){assert.equal(old.readyState,'ended','old source must end before the real request');calls.push(c);if(deferred)await deferred;if(failure-->0)throw Error('private device error');const a=c.audio as MediaTrackConstraints,track={readyState:'live',onended:null,stop(){this.readyState='ended';},getSettings:()=>({deviceId:mismatch?'other-private-device':initial.deviceId,echoCancellation:(a.echoCancellation as ConstrainBooleanParameters).exact!,noiseSuppression:(a.noiseSuppression as ConstrainBooleanParameters).exact!,autoGainControl:(a.autoGainControl as ConstrainBooleanParameters).exact!})};made.push(track);return {getTracks:()=>[track],getAudioTracks:()=>[track]} as unknown as MediaStream;},publish(s:MediaStream,t:MediaStreamTrack){if(publishFails)throw Error('private connect failure');published.push(t);},stop(){stops++;live=false;}};
 return{old:old as unknown as MediaStreamTrack,owner,calls,published,made,retired:()=>retired,stops:()=>stops,revoke(){live=false;},fail(n=1){failure=n;},mismatch(){mismatch=true;},publishFails(){publishFails=true;},defer(){deferred=new Promise<void>(r=>resolve=r);return()=>{deferred=undefined;resolve();};}};
}
test('all six changes/restores retire before one exact same-device request and verify all processing fields',async()=>{for(const field of ['echoCancellation','noiseSuppression','autoGainControl']as const)for(const value of [false,true]){const f=fixture();assert.equal(await restartConsentedCapture(f.old,{field,value},f.owner),'ok');assert.equal(f.calls.length,1);assert.equal(f.retired(),1);const a=f.calls[0].audio as MediaTrackConstraints;assert.deepEqual(a.deviceId,{exact:initial.deviceId});assert.equal(a.channelCount,1);for(const key of ['echoCancellation','noiseSuppression','autoGainControl']as const)assert.deepEqual(a[key],{exact:key===field?value:true});assert.equal(f.published.length,1);assert.equal(f.stops(),0);}});
test('failed desired acquisition restores original exact settings once but returns refusal',async()=>{const f=fixture();f.fail();assert.equal(await restartConsentedCapture(f.old,{field:'echoCancellation',value:false},f.owner),'apply-refused');assert.equal(f.calls.length,2);assert.equal(f.published.length,1);assert.equal((f.calls[1].audio as MediaTrackConstraints).echoCancellation&&JSON.stringify((f.calls[1].audio as MediaTrackConstraints).echoCancellation),'{"exact":true}');assert.equal(f.stops(),0);});
test('failed restore stops logical consent and never tries a third device acquisition',async()=>{const f=fixture();f.fail(2);assert.equal(await restartConsentedCapture(f.old,{field:'noiseSuppression',value:false},f.owner),'rollback-refused');assert.equal(f.calls.length,2);assert.equal(f.stops(),1);});
test('same-device mismatch is discarded, cannot be published, and bounded restore failure ends consent',async()=>{const f=fixture();f.mismatch();assert.equal(await restartConsentedCapture(f.old,{field:'autoGainControl',value:false},f.owner),'rollback-refused');assert.equal(f.calls.length,2);assert.equal(f.published.length,0);assert(f.made.every(t=>t.readyState==='ended'));});
test('source connection refusal discards every candidate and makes only one restore attempt',async()=>{const f=fixture();f.publishFails();assert.equal(await restartConsentedCapture(f.old,{field:'echoCancellation',value:false},f.owner),'rollback-refused');assert.equal(f.calls.length,2);assert(f.made.every(t=>t.readyState==='ended'));});
test('revocation while the desired request is unresolved stops the late candidate without restore',async()=>{const f=fixture(),release=f.defer(),p=restartConsentedCapture(f.old,{field:'echoCancellation',value:false},f.owner);f.revoke();release();assert.equal(await p,'cancelled');assert.equal(f.calls.length,1);assert.equal(f.published.length,0);assert.equal(f.made[0].readyState,'ended');});
test('revocation during the one rollback request stops its late result without further acquisition',async()=>{const f=fixture();f.fail();const acquire=f.owner.acquire;let release!:()=>void;f.owner.acquire=async c=>{if(f.calls.length===1)await new Promise<void>(r=>release=r);return acquire(c);};const p=restartConsentedCapture(f.old,{field:'echoCancellation',value:false},f.owner);for(let i=0;i<5&&!release;i++)await Promise.resolve();assert(release);f.revoke();release();assert.equal(await p,'cancelled');assert.equal(f.calls.length,2);assert.equal(f.made[0].readyState,'ended');});
test('absent/oversized private identity or incomplete processing cannot retire or request another device',async()=>{for(const settings of [{...initial,deviceId:''},{...initial,deviceId:'x'.repeat(4097)},{...initial,noiseSuppression:undefined}]){const f=fixture();f.old.getSettings=()=>settings as MediaTrackSettings;assert.equal(await restartConsentedCapture(f.old,{field:'echoCancellation',value:false},f.owner),'unsupported');assert.equal(f.retired(),0);assert.equal(f.calls.length,0);}});
test('gain and initially revoked operations cannot retire or acquire',async()=>{const f=fixture();assert.equal(await restartConsentedCapture(f.old,{field:'inputGainPercent',value:70},f.owner),'inactive');f.revoke();assert.equal(await restartConsentedCapture(f.old,{field:'echoCancellation',value:false},f.owner),'inactive');assert.equal(f.calls.length,0);assert.equal(f.retired(),0);});
test('invalid changes fail closed before reading or retiring the original track',async()=>{const f=fixture();await assert.rejects(restartConsentedCapture(f.old,{field:'echoCancellation',value:1} as unknown as Parameters<typeof restartConsentedCapture>[1],f.owner));assert.equal(f.calls.length,0);assert.equal(f.retired(),0);});

test('exact requested processing readback mismatch cannot publish a false success and restores once',async()=>{
 const f=fixture(),acquire=f.owner.acquire;let first=true;f.owner.acquire=async c=>{const stream=await acquire(c);if(first){first=false;const track=stream.getAudioTracks()[0],settings=track.getSettings();track.getSettings=()=>({...settings,echoCancellation:true});}return stream;};
 assert.equal(await restartConsentedCapture(f.old,{field:'echoCancellation',value:false},f.owner),'readback-mismatch');assert.equal(f.calls.length,2);assert.equal(f.published.length,1);assert.equal(f.made[0].readyState,'ended');assert.equal(f.made[1].readyState,'live');
});

test('definitive browser permission denial stops consent without attempting another permission request',async()=>{
 const f=fixture();f.owner.acquire=async c=>{f.calls.push(c);throw new DOMException('private denial','NotAllowedError');};assert.equal(await restartConsentedCapture(f.old,{field:'echoCancellation',value:false},f.owner),'rollback-refused');assert.equal(f.calls.length,1);assert.equal(f.stops(),1);assert.equal(f.published.length,0);
});
