// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {BrowserCaptureTarget,type CaptureBinding} from './browser-capture-target.ts';import {BrowserCaptureController} from './browser-capture-controller.ts';import {captureState,captureRequest,captureResult,inactiveCapture} from '../shared/browser-capture.mjs';
const deferred=()=>{let resolve!:(value?:unknown)=>void,reject!:(e:unknown)=>void;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
function fixture(){let current=true,enabled=true,stops=0;const held:boolean[]=[],committed:unknown[]=[],calls:MediaTrackConstraints[]=[],timers=new Set<()=>void>();let values={echoCancellation:true,noiseSuppression:true,autoGainControl:true},old:MediaTrackConstraints={channelCount:1,deviceId:{exact:'private-local-device'},echoCancellation:true,noiseSuppression:true,autoGainControl:true},gainValue=1;
 const track={readyState:'live',getSettings:()=>({...values,deviceId:'private-label-not-wire'}),getCapabilities:()=>({echoCancellation:[true,false],noiseSuppression:[true,false],autoGainControl:[true,false]}),getConstraints:()=>old,applyConstraints:async(c:MediaTrackConstraints)=>{calls.push(c);for(const field of ['echoCancellation','noiseSuppression','autoGainControl'] as const){const value=c[field];values[field]=typeof value==='boolean'?value:(value as {exact:boolean}).exact;}old=c;},stop(){this.readyState='ended';}};
 const param={get value(){return gainValue;},set value(value){gainValue=Math.fround(value);}},binding:CaptureBinding={track:track as unknown as MediaStreamTrack,gain:{gain:param} as unknown as GainNode,current:()=>current&&enabled,inhibit:value=>held.push(value),stop(){stops++;enabled=false;track.stop();},committed:c=>committed.push(c)};
 const target=new BrowserCaptureTarget(()=>enabled?binding:undefined,{set(fn,ms){assert.equal(ms,8000);timers.add(fn);return fn;},clear(id){timers.delete(id as ()=>void);}});const controller=new BrowserCaptureController(target,()=>current);controller.setAuthority(2,true);
 return{target,controller,binding,track,param,values,calls,held,committed,timers,stops:()=>stops,allowed(v:boolean){current=v;},mute(){enabled=false;track.stop();},replace(){enabled=false;},current:()=>current};}
const change=(field='echoCancellation',value:unknown=false,id=1)=>({schemaVersion:1,requestId:id,operation:'change',field,value});
test('strict DTO clones only supported effective fields and excludes device ids/private labels',()=>{const f=fixture(),s=f.target.snapshot();assert(s.active&&s.controls.echoCancellation);assert(!JSON.stringify(s).includes('private'));assert.deepEqual(captureState(s),s);assert.throws(()=>captureState({...s,deviceId:'private'}));assert.throws(()=>captureRequest({...change(),deviceId:'private'}));assert.throws(()=>captureResult({schemaVersion:1,requestId:1,accepted:true,reason:'apply-refused',state:s}));assert.throws(()=>captureState({...inactiveCapture(),active:false,controls:s.controls}));});
test('exact live DSP change reads actual settings before accepting and preserves local unrelated constraints',async()=>{const f=fixture(),r=await f.controller.receive(change(),2);assert.equal(r?.accepted,true);assert.equal(r?.state.settings.echoCancellation,false);assert.deepEqual(f.calls[0].echoCancellation,{exact:false});assert.deepEqual(f.calls[0].deviceId,{exact:'private-local-device'});assert.deepEqual(f.held,[true,false]);assert.equal(f.committed.length,1);});
test('unsupported capability and absent microphone do not call applyConstraints or request permission',async()=>{const f=fixture();f.track.getCapabilities=()=>({echoCancellation:[true],noiseSuppression:[true,false],autoGainControl:[true,false]});assert.equal((await f.controller.receive(change(),2))?.reason,'unsupported');assert.equal(f.calls.length,0);f.mute();assert.equal((await f.controller.receive(change('noiseSuppression',false,2),2))?.reason,'inactive');assert.deepEqual(f.target.snapshot(),inactiveCapture());});
test('false success from browser readback rolls back exact original constraints and does not commit',async()=>{const f=fixture();f.track.applyConstraints=async c=>{f.calls.push(c);};const r=await f.controller.receive(change(),2);assert.equal(r?.accepted,false);assert.equal(r?.reason,'readback-mismatch');assert.equal(r?.state.settings.echoCancellation,true);assert.equal(f.calls.length,2);assert.equal(f.committed.length,0);assert.deepEqual(f.held,[true,false]);});
test('failed apply uses a confirmed rollback without disclosing browser error text',async()=>{const f=fixture();f.track.applyConstraints=async c=>{f.calls.push(c);if(f.calls.length===1)throw Error('secret device error');};const r=await f.controller.receive(change(),2);assert.equal(r?.reason,'apply-refused');assert(!JSON.stringify(r).includes('secret'));assert.equal(f.calls.length,2);assert.equal(f.stops(),0);});
test('unconfirmed rollback stops capture and never reopens PCM',async()=>{const f=fixture();f.track.applyConstraints=async c=>{f.calls.push(c);throw Error('private failure');};const r=await f.controller.receive(change(),2);assert.equal(r?.reason,'rollback-refused');assert.equal(r?.state.active,false);assert.equal(f.stops(),1);assert.deepEqual(f.held,[true]);});
test('mute during asynchronous DSP work cannot commit, rollback or clear the old capture inhibition',async()=>{const f=fixture(),d=deferred();f.track.applyConstraints=async c=>{f.calls.push(c);await d.promise;};const operation=f.controller.receive(change(),2);f.mute();d.resolve();const r=await operation;assert.equal(r?.accepted,false);assert.equal(f.calls.length,1);assert.equal(f.committed.length,0);assert.deepEqual(f.held,[true]);});
test('authority revoke synchronously stops pending capture and suppresses every late acknowledgement',async()=>{const f=fixture(),d=deferred();f.track.applyConstraints=async()=>{await d.promise;};const p=f.controller.receive(change(),2);f.controller.setAuthority(3,false);assert.equal(f.stops(),1);assert.equal(await p,undefined);d.resolve();await Promise.resolve();assert.equal(f.committed.length,0);assert.deepEqual(f.held,[true]);});
test('closing/native page cancellation stops only outstanding capture work, never requests a microphone',async()=>{const f=fixture();f.controller.cancelPending();assert.equal(f.stops(),0);const d=deferred();f.track.applyConstraints=async()=>{await d.promise;};const p=f.controller.receive(change(),2);f.controller.close();assert.equal(f.stops(),1);assert.equal(await p,undefined);d.resolve();await Promise.resolve();assert.equal(f.committed.length,0);});
test('one native pending operation bounds repeated/replayed requests and keeps slot until actual settlement',async()=>{const f=fixture(),d=deferred();f.track.applyConstraints=async()=>{await d.promise;};const p=f.controller.receive(change(),2);assert.equal((await f.controller.receive(change('noiseSuppression',false,2),2))?.reason,'busy');assert.equal(await f.controller.receive(change(),2),undefined);d.resolve();await p;assert.equal(f.held.filter(v=>v).length,1);});
test('original eight-second deadline stops microphone; the unresolved browser operation cannot later commit',async()=>{const f=fixture(),d=deferred();f.track.applyConstraints=async()=>{await d.promise;};const p=f.controller.receive(change(),2);assert.equal(f.timers.size,1);for(const fn of [...f.timers])fn();const r=await p;assert.equal(r?.reason,'deadline');assert.equal(r?.state.active,false);assert.equal(f.stops(),1);d.resolve();await Promise.resolve();assert.equal(f.committed.length,0);});
test('capture gain controls only the separate input AudioParam and exposes actual Float32 readback',async()=>{const f=fixture(),r=await f.controller.receive(change('inputGainPercent',70),2);assert.equal(r?.accepted,true);assert.equal(r?.state.settings.inputGainPercent,70);assert.equal(r?.state.settings.inputGain,Math.fround(.7));assert.equal(f.calls.length,0);assert.equal(f.committed.length,1);assert.throws(()=>captureRequest(change('inputGainPercent',201)));});
test('gain setter mismatch must restore and confirm original amplitude before reporting failure',async()=>{const f=fixture();Object.defineProperty(f.param,'value',{get:()=>1,set(){}});const r=await f.controller.receive(change('inputGainPercent',70),2);assert.equal(r?.reason,'readback-mismatch');assert.equal(f.stops(),0);assert.equal(f.committed.length,0);});
test('capture gain and DSP controls cannot apply under a stale permission revision',async()=>{const f=fixture();assert.equal(await f.controller.receive(change(),1),undefined);f.allowed(false);assert.equal(await f.controller.receive(change(),2),undefined);assert.equal(f.calls.length,0);assert.equal(f.committed.length,0);});

test('support claims require the actual effective setting and never serialize a private device setting',()=>{const raw=inactiveCapture();raw.active=true;raw.controls.echoCancellation=true;assert.throws(()=>captureState(raw));});
