// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {BoxGeometry,CompressedTexture,DoubleSide,Group,InstancedMesh,LOD,Mesh,MeshBasicMaterial,PerspectiveCamera,RGBA_S3TC_DXT5_Format,Scene,SkinnedMesh,Texture,UnsignedByteType} from 'three';
import {ForegroundTexturePlan,ForegroundTextureCapacityError} from './foreground-texture-plan';
import {WorldTexturePreparation} from './world-texture-preparation';
const texture=()=>{const value=new CompressedTexture([{width:2,height:2,data:new Uint8Array(16)}],2,2,RGBA_S3TC_DXT5_Format,UnsignedByteType);value.needsUpdate=true;return value;};
function setup(){const scene=new Scene(),root=new Group(),camera=new PerspectiveCamera(90,1,1,100);scene.add(root);root.visible=false;const map=texture(),mesh:Mesh<BoxGeometry,MeshBasicMaterial|MeshBasicMaterial[]>=new Mesh(new BoxGeometry(1,1,1),new MeshBasicMaterial({map}));mesh.position.z=-5;root.add(mesh);let publishing=true;const plan=new ForegroundTexturePlan(root,scene,camera,()=>publishing);return{scene,root,camera,map,mesh,plan,setPublishing:(value:boolean)=>{publishing=value;}};}
function finish(s:ReturnType<typeof setup>){s.plan.dispose();s.mesh.geometry.dispose();(s.mesh.material as MeshBasicMaterial).dispose();s.map.dispose();}
test('90-degree main-view frustum selects an actual hidden publishing root; offscreen and behind-camera maps stay lazy',()=>{const s=setup();assert(s.plan.isEligible(s.map));s.mesh.position.x=100;assert(!s.plan.isEligible(s.map));s.mesh.position.set(0,0,5);assert(!s.plan.isEligible(s.map));s.mesh.position.set(0,0,-5);s.camera.rotation.y=Math.PI;assert(!s.plan.isEligible(s.map));s.camera.rotation.y=0;s.mesh.frustumCulled=false;s.mesh.position.x=100;assert(s.plan.isEligible(s.map));finish(s);});
test('nonuniform negative entity/world transforms and current camera changes use actual public renderer frustum bounds',()=>{const s=setup();s.root.scale.set(-2,.5,3);assert(s.plan.isEligible(s.map));s.root.position.x=100;assert(!s.plan.isEligible(s.map));s.camera.position.x=100;assert(s.plan.isEligible(s.map));s.camera.far=2;s.camera.updateProjectionMatrix();assert(!s.plan.isEligible(s.map));finish(s);});
test('renderer subtree visibility prunes ancestors while parent layer mismatch does not prune a visible child',()=>{const s=setup();s.root.layers.set(3);assert(s.plan.isEligible(s.map));s.mesh.layers.set(3);assert(!s.plan.isEligible(s.map));s.camera.layers.set(3);assert(s.plan.isEligible(s.map));s.root.parent!.visible=false;assert(!s.plan.isEligible(s.map));s.root.parent!.visible=true;s.mesh.visible=false;assert(!s.plan.isEligible(s.map));s.mesh.visible=true;s.setPublishing(false);assert(!s.plan.isEligible(s.map));finish(s);});
test('detached pending avatar, transferred drawable, nested hidden Group and reparented LOD are conservatively lazy',()=>{const s=setup(),parent=new Group();s.root.add(parent);parent.add(s.mesh);parent.visible=false;assert(!s.plan.isEligible(s.map));parent.visible=true;assert(s.plan.isEligible(s.map));s.scene.remove(s.root);assert(!s.plan.isEligible(s.map));s.scene.add(s.root);const other=new Group();s.scene.add(other);other.add(s.mesh);assert(!s.plan.isEligible(s.map));s.root.add(s.mesh);const lod=new LOD();s.root.add(lod);lod.add(s.mesh);assert(!s.plan.isEligible(s.map));finish(s);});
test('actual material-array groups select only renderer-used slots; current material visibility and binding replacements invalidate borrows',()=>{const s=setup(),other=texture(),first=new MeshBasicMaterial({map:s.map}),second=new MeshBasicMaterial({map:other});s.mesh.geometry.clearGroups();s.mesh.geometry.addGroup(0,0,1);s.mesh.material=[first,second];s.plan.dispose();s.plan=new ForegroundTexturePlan(s.root,s.scene,s.camera,()=>true);assert(!s.plan.isEligible(s.map));assert(s.plan.isEligible(other));second.visible=false;assert(!s.plan.isEligible(other));second.visible=true;second.map=s.map;assert(!s.plan.isEligible(other));assert(!s.plan.isEligible(s.map));s.mesh.geometry.clearGroups();assert(!s.plan.isEligible(other));s.plan.dispose();first.dispose();second.dispose();other.dispose();s.mesh.geometry.dispose();s.map.dispose();});
test('opacity zero, backface-only and zero draw range still setProgram/bind maps in Three before GPU/range culling',()=>{const s=setup(),material=s.mesh.material as MeshBasicMaterial;material.opacity=0;material.transparent=true;material.side=DoubleSide;s.mesh.geometry.setDrawRange(0,0);assert(s.plan.isEligible(s.map));finish(s);});
test('a shared Texture is eligible if any current slot is foreground, without holding mutable material snapshots',()=>{const s=setup(),visible=new Mesh(s.mesh.geometry,new MeshBasicMaterial({map:s.map}));visible.position.z=-5;s.root.add(visible);s.mesh.position.x=100;s.plan.dispose();s.plan=new ForegroundTexturePlan(s.root,s.scene,s.camera,()=>true);assert(s.plan.isEligible(s.map));(visible.material as MeshBasicMaterial).map=null;assert(!s.plan.isEligible(s.map));assert.equal(s.plan.stats.textures,1);assert.equal(s.plan.stats.bindings,2);visible.material.dispose();finish(s);});
test('skinned, instanced and LOD geometry uses original first-use path; ordinary merged static Mesh remains eligible',()=>{const s=setup();s.root.remove(s.mesh);const material=s.mesh.material as MeshBasicMaterial,a=new SkinnedMesh(s.mesh.geometry,material),b=new InstancedMesh(s.mesh.geometry,material,1),lod=new LOD();a.position.z=b.position.z=-5;lod.add(s.mesh);s.root.add(a,b,lod);s.plan.dispose();s.plan=new ForegroundTexturePlan(s.root,s.scene,s.camera,()=>true);assert(!s.plan.isEligible(s.map));assert.equal(s.plan.stats.unsupported,3);s.root.add(s.mesh);s.mesh.userData.browserStaticBatch=true;s.plan.dispose();s.plan=new ForegroundTexturePlan(s.root,s.scene,s.camera,()=>true);assert(s.plan.isEligible(s.map));finish(s);});
test('foreign frustum callback is never executed by optional eligibility planning',()=>{const s=setup();let calls=0;s.mesh.intersectsFrustum=()=>{calls++;return true;};s.plan.dispose();s.plan=new ForegroundTexturePlan(s.root,s.scene,s.camera,()=>true);assert(!s.plan.isEligible(s.map));assert.equal(calls,0);finish(s);});
test('queued foreground preparation rechecks camera and maps each task; no hidden/static GPU allocation after ownership changes',async()=>{const s=setup(),owner=new AbortController(),calls:Texture[]=[],scheduler=new WorldTexturePreparation({initTexture(value){calls.push(value);}},{signal:owner.signal});const pending=scheduler.prepare(s.root,()=>{},undefined,value=>s.plan.isEligible(value));s.camera.rotation.y=Math.PI;await pending;assert.equal(calls.length,0);assert.equal(scheduler.stats.references,0);assert.equal(scheduler.stats.completed,1);s.camera.rotation.y=0;await scheduler.prepare(s.root,()=>{},undefined,value=>s.plan.isEligible(value));assert.deepEqual(calls,[s.map]);owner.abort();finish(s);});
test('initially offscreen Texture does not enter queue, and later visibility is left to unchanged renderer rather than retained plan jobs',async()=>{const s=setup(),owner=new AbortController();let calls=0;const scheduler=new WorldTexturePreparation({initTexture(){calls++;}},{signal:owner.signal});s.mesh.position.x=100;await scheduler.prepare(s.root,()=>{},undefined,value=>s.plan.isEligible(value));assert.equal(scheduler.stats.submitted,0);assert.equal(calls,0);assert.equal(scheduler.stats.references,0);owner.abort();finish(s);});
test('scheduler rechecks material field after actual task suspension without resurrecting replaced borrowed GPU texture',async()=>{const s=setup(),owner=new AbortController();let calls=0;const scheduler=new WorldTexturePreparation({initTexture(){calls++;}},{signal:owner.signal});const pending=scheduler.prepare(s.root,()=>{},undefined,value=>s.plan.isEligible(value));(s.mesh.material as MeshBasicMaterial).map=null;await pending;assert.equal(calls,0);owner.abort();finish(s);});
test('disposed plan releases texture descriptors and refuses any later eligibility',()=>{const s=setup();assert.equal(s.plan.stats.textures,1);s.plan.dispose();assert.equal(s.plan.stats.textures,0);assert.equal(s.plan.stats.bindings,0);assert(!s.plan.isEligible(s.map));finish(s);});
test('per-owner remaining aggregate binding admission rejects before storing excess draw descriptors',()=>{const s=setup();assert.throws(()=>new ForegroundTexturePlan(s.root,s.scene,s.camera,()=>true,0),ForegroundTextureCapacityError);assert.equal(new ForegroundTexturePlan(s.root,s.scene,s.camera,()=>true,1).stats.bindings,1);assert.throws(()=>new ForegroundTexturePlan(s.root,s.scene,s.camera,()=>true,-1),/Invalid/);finish(s);});
test('foreign per-draw callbacks leave potential material mutation on normal first-render path',()=>{const s=setup();s.mesh.onBeforeRender=()=>{};s.plan.dispose();s.plan=new ForegroundTexturePlan(s.root,s.scene,s.camera,()=>true);assert(!s.plan.isEligible(s.map));finish(s);});
