// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Actual production scan/World methods with controlled lifecycle predicates; no GPU claim.
import test,{type TestContext} from 'node:test';import assert from 'node:assert/strict';
import {GraphicsScanFrames} from './graphics-scan-frames';import {GraphicsEnvironmentScan} from './graphics-environment-scan';import {BrowserWorld} from './world';
import {Group,PerspectiveCamera,Vector3} from 'three';import {SimulationClock} from './simulation-clock';
function fixture(){const abort=new AbortController();let live:unknown=true,current=true,applies=0,state={version:1 as const,fieldOfView:70,resolutionPercent:100,localLights:true,cameraClipping:true},apply:undefined|((percent:number)=>Promise<typeof state>);const frames=new GraphicsScanFrames(abort.signal,()=>{if(live instanceof Error)throw live;return live as boolean;});class Visibility extends EventTarget{visibilityState='visible' as DocumentVisibilityState;}const document=new Visibility();const scan=new GraphicsEnvironmentScan({frames,document,current:()=>current,presentationVisible:()=>true,settings:()=>({...state}),capabilities:()=>({webgl2:true,contextAntialias:true,maximumTextureDimension:8192,maximumRenderbufferDimension:8192,maximumViewportWidth:8192,maximumViewportHeight:8192,drawingBufferWidth:640,drawingBufferHeight:480}),applyResolution:async percent=>{applies++;return apply?apply(percent):(state={...state,resolutionPercent:percent});}},5000,()=>3000);return {abort,frames,scan,get applies(){return applies;},setLive(v:unknown){live=v;},setCurrent(v:boolean){current=v;},setApply(v:typeof apply){apply=v;},close(){scan.dispose();abort.abort();}};}
async function sample(f:ReturnType<typeof fixture>){const pending=f.scan.scan();for(let i=0;i<=20;i++)f.frames.publish({timestampMs:i*100,cpuSubmitMs:4,ready:true});const result=await pending;assert.equal(result.status,'complete');if(result.status==='complete')assert.equal(result.report.optionalResolutionPercent,90);return result;}
test('same controller refuses while lost, scans after restoration, and never applies a pre-loss recommendation',async()=>{const f=fixture();try{await sample(f);const first=f.frames.contextEpoch;f.setLive(false);f.frames.suspendContext();assert.equal((await f.scan.applyOptionalResolution()).accepted,false);assert.equal((await f.scan.scan()).status,'refused');assert.equal(f.applies,0);f.setLive(true);assert(f.frames.resumeContext());assert.equal(f.frames.contextEpoch,first!+1);assert.equal((await f.scan.applyOptionalResolution()).accepted,false);await sample(f);assert.equal((await f.scan.applyOptionalResolution()).accepted,true);assert.equal(f.applies,1);}finally{f.close();}});
test('loss before the DOM event invalidates completed advice synchronously and requires actual resume',async()=>{const f=fixture();try{await sample(f);const epoch=f.frames.contextEpoch;f.setLive(false);assert.equal((await f.scan.applyOptionalResolution()).accepted,false);f.setLive(true);assert.equal((await f.scan.scan()).status,'refused');assert(f.frames.resumeContext());assert.equal(f.frames.contextEpoch,epoch!+1);assert.equal((await f.scan.applyOptionalResolution()).accepted,false);}finally{f.close();}});
test('active scan cancellation settles on loss without publishing a late frame',async()=>{const f=fixture();try{const pending=f.scan.scan();f.frames.publish({timestampMs:0,cpuSubmitMs:4,ready:true});f.frames.suspendContext();assert.equal((await pending).status,'cancelled');assert.equal(f.frames.active,false);f.frames.publish({timestampMs:4000,cpuSubmitMs:4,ready:true});assert.equal((await f.scan.applyOptionalResolution()).accepted,false);}finally{f.close();}});
test('unknown, throwing and truthy nonboolean predicates never grant subscriptions or restoration',async()=>{for(const value of [undefined,null,1,'true',new Error('unreadable context')]){const f=fixture();try{f.setLive(value);assert.equal((await f.scan.scan()).status,'refused');assert.equal(f.frames.contextEpoch,undefined);assert.equal(f.frames.resumeContext(),false);assert.equal(f.frames.active,false);}finally{f.close();}}});
test('loss/restore cycles are monotonic and old unsubscribe cannot evict a new subscriber',()=>{const f=fixture();try{let oldCancels=0,newFrames=0;const old=f.frames.subscribe(()=>{},()=>oldCancels++);f.frames.suspendContext();f.frames.suspendContext();assert.equal(oldCancels,1);assert(f.frames.resumeContext());const epoch=f.frames.contextEpoch;assert(f.frames.resumeContext());assert.equal(f.frames.contextEpoch,epoch);f.frames.subscribe(()=>newFrames++,()=>{});old();f.frames.publish({timestampMs:1,cpuSubmitMs:1,ready:true});assert.equal(newFrames,1);f.frames.suspendContext();assert(f.frames.resumeContext());assert.equal(f.frames.contextEpoch,epoch!+1);}finally{f.close();}});
test('epoch exhaustion closes permanently instead of wrapping old approval',()=>{const f=fixture();try{(f.frames as any).epoch=Number.MAX_SAFE_INTEGER;f.frames.suspendContext();assert.equal(f.frames.contextEpoch,undefined);assert.equal(f.frames.resumeContext(),false);assert.throws(()=>f.frames.subscribe(()=>{},()=>{}),{name:'AbortError'});}finally{f.close();}});
test('World abort and explicit disposal cannot be reopened by a later resume',()=>{for(const action of ['abort','dispose']){const f=fixture();try{if(action==='abort')f.abort.abort();else f.frames.dispose();assert.equal(f.frames.resumeContext(),false);assert.equal(f.frames.contextEpoch,undefined);}finally{f.close();}}});
test('session revocation during loss remains refused after graphics restoration',async()=>{const f=fixture();try{await sample(f);f.frames.suspendContext();f.setCurrent(false);assert(f.frames.resumeContext());assert.equal((await f.scan.scan()).status,'refused');assert.equal((await f.scan.applyOptionalResolution()).accepted,false);assert.equal(f.applies,0);}finally{f.close();}});
test('loss/restore during setting confirmation refuses the late confirmation without repeating apply',async()=>{const f=fixture();try{await sample(f);let complete!:(value:any)=>void;f.setApply(()=>new Promise(resolve=>{complete=resolve;}));const pending=f.scan.applyOptionalResolution();assert.equal(f.applies,1);f.frames.suspendContext();assert(f.frames.resumeContext());complete({version:1,fieldOfView:70,resolutionPercent:90,localLights:true,cameraClipping:true});assert.equal((await pending).accepted,false);assert.equal(f.applies,1);}finally{f.close();}});
test('context predicate abort reentry cannot publish or reopen a revoked World signal',()=>{const abort=new AbortController();let shouldAbort=false;const frames=new GraphicsScanFrames(abort.signal,()=>{if(shouldAbort)abort.abort();return true;});let published=0;frames.subscribe(()=>published++,()=>{});shouldAbort=true;frames.publish({timestampMs:1,cpuSubmitMs:1,ready:true});assert.equal(published,0);assert.equal(frames.resumeContext(),false);assert.equal(frames.contextEpoch,undefined);});
function world(t:TestContext){const w:any=Object.create(BrowserWorld.prototype),listeners=new Map<string,{fn:Function,signal:AbortSignal}>(),canvas={addEventListener(name:string,fn:Function,options:any){listeners.set(name,{fn,signal:options.signal});}};let lost:unknown=false,renders=0;const gl={isContextLost(){if(lost instanceof Error)throw lost;return lost;}};const abort=new AbortController();Object.assign(w,{abort,disposed:false,graphicsContextAvailable:true,enabled:false,inputEnabled:true,keys:new Set(),options:{onStatus(){}},canvas,renderer:{getContext:()=>gl,render(){renders++;}},imagePulseOwners:new Map(),simulationClock:new SimulationClock(),metrics:{sample(){}},camera:new PerspectiveCamera(),thirdPerson:false,yaw:0,pitch:0,position:new Vector3(),self:new Group(),avatars:new Map(),localLights:new Set(),pointSlots:[],spotSlots:[],lastLightSelection:0,presentationEnabled:true,renderedFrames:0,recordLoadPhase(){},entities:new Map(),modelScheduler:{stats:{active:0,queued:0}},compilingGraphics:0});const oldWindow=globalThis.window,oldDocument=globalThis.document,oldRaf=globalThis.requestAnimationFrame;Object.assign(globalThis,{window:{addEventListener(){}},document:{addEventListener(){},pointerLockElement:null},requestAnimationFrame:()=>1});t.after(()=>{abort.abort();for(const [key,value]of [['window',oldWindow],['document',oldDocument],['requestAnimationFrame',oldRaf]]as const){if(value===undefined)Reflect.deleteProperty(globalThis,key);else Object.assign(globalThis,{[key]:value});}});return {w,listeners,canvas,setLost(v:unknown){lost=v;},get renders(){return renders;},fire(name:string,trusted=true,target:unknown=canvas){const entry=listeners.get(name)!;assert(entry);assert.equal(entry.signal,abort.signal);entry.fn({target,isTrusted:trusted,preventDefault(){}});}};}
test('actual World refuses lost-before-event and unknown contexts without rendering, sample publication or frame counts',t=>{const f=world(t);const frames=f.w.getGraphicsScanFrames();let published=0;frames.subscribe(()=>published++,()=>{});for(const value of [true,undefined,new Error('unreadable')]){f.setLost(value);f.w.animate(1000);}assert.equal(f.renders,0);assert.equal(f.w.renderedFrames,0);assert.equal(published,0);});
test('actual World detects loss inside render and does not count or publish that submission',t=>{const f=world(t),frames=f.w.getGraphicsScanFrames();let published=0;frames.subscribe(()=>published++,()=>{});f.w.renderer.render=()=>f.setLost(true);f.w.animate(1000);assert.equal(f.w.renderedFrames,0);assert.equal(published,0);assert.equal(frames.contextEpoch,undefined);});
test('actual owned restored handler resumes same source only on trusted current context without enabling session',t=>{const f=world(t),frames=f.w.getGraphicsScanFrames();f.w.installControls();f.setLost(true);f.fire('webglcontextlost');f.setLost(false);f.fire('webglcontextrestored',false);assert.equal(frames.contextEpoch,undefined);f.fire('webglcontextrestored',true,{});assert.equal(frames.contextEpoch,undefined);f.fire('webglcontextrestored');assert.equal(frames,f.w.getGraphicsScanFrames());assert.equal(frames.contextEpoch,1);assert.equal(f.w.enabled,false);let published=0;frames.subscribe(()=>published++,()=>{});f.w.animate(1100);assert.equal(f.w.renderedFrames,1);assert.equal(published,1);});
test('disposed or aborted actual World ignores a late restored handler',t=>{const f=world(t),frames=f.w.getGraphicsScanFrames();f.w.installControls();f.setLost(true);f.fire('webglcontextlost');f.setLost(false);f.w.abort.abort();f.fire('webglcontextrestored');assert.equal(frames.contextEpoch,undefined);assert.equal(f.w.graphicsContextAvailable,false);f.w.disposed=true;f.fire('webglcontextrestored');assert.equal(frames.resumeContext(),false);});
// The application closure is extracted verbatim, so this tests its actual request binding.
import {readFileSync} from 'node:fs';import {BrowserGraphicsIntent} from './browser-graphics-intent';import {BrowserGraphicsController} from './browser-graphics-controller';
function applicationApply(currentIntent:BrowserGraphicsIntent,scanFrames:GraphicsScanFrames){const source=readFileSync(new URL('./main.ts',import.meta.url),'utf8'),match=source.match(/applyResolution:(value=>\{const contextEpoch=scanFrames.contextEpoch;[^\n]+?\})\}\);/);assert(match,'actual scanner application closure');return Function('currentIntent','scanFrames',`return (${match[1]});`)(currentIntent,scanFrames) as (value:number)=>Promise<any>;}
function route(){const abort=new AbortController();let lost=false,state={version:1 as const,fieldOfView:70,resolutionPercent:100,localLights:true,cameraClipping:true},mutations=0,persisted=0;const frames=new GraphicsScanFrames(abort.signal,()=>!lost),messages:Record<string,unknown>[]=[];const intent=new BrowserGraphicsIntent({current:()=>true,snapshot:()=>({...state}),send:v=>messages.push(v)});const controller=new BrowserGraphicsController({snapshot:()=>({...state}),apply:v=>{mutations++;state={...v};}},()=>true,()=>persisted++);controller.setAuthority(1,true);return {frames,intent,controller,messages,apply:applicationApply(intent,frames),setLost(v:boolean){lost=v;},request(){return {schemaVersion:1 as const,requestId:1,operation:'change' as const,field:'resolutionPercent' as const,value:90,browserRequestId:messages.find(v=>v.action==='graphicsChange')!.browserRequestId as number};},get state(){return state;},get mutations(){return mutations;},get persisted(){return persisted;},close(){intent.dispose();abort.abort();}};}
test('actual main scan intent denies late native mutation and persistence after loss/restore before request',async()=>{const f=route();try{const pending=f.apply(90);const settled=assert.rejects(pending);f.frames.suspendContext();assert(f.frames.resumeContext());assert.equal(f.intent.permits(f.request()),false);await settled;assert.equal(f.state.resolutionPercent,100);assert.equal(f.mutations,0);assert.equal(f.persisted,0);assert.equal(f.messages.filter(v=>v.action==='graphicsCancel').length,1);}finally{f.close();}});
test('actual main pending intent detects lost GL before DOM event and cannot revive after restoration',async()=>{const f=route();try{const pending=f.apply(90),settled=assert.rejects(pending);f.setLost(true);assert.equal(f.intent.permits(f.request()),false);f.setLost(false);assert(f.frames.resumeContext());assert.equal(f.intent.permits(f.request()),false);await settled;assert.equal(f.mutations,0);}finally{f.close();}});
test('a fresh epoch scanner request uses ordinary actual controller apply/persistence/ACK route',async()=>{const f=route();try{f.frames.suspendContext();assert(f.frames.resumeContext());const pending=f.apply(90),request=f.request();assert(f.intent.permits(request));const result=f.controller.receive(request,1)!;assert(result.accepted);f.intent.complete({schemaVersion:1,browserRequestId:request.browserRequestId,accepted:true,settings:result.settings});assert.equal((await pending).resolutionPercent,90);assert.equal(f.mutations,1);assert.equal(f.persisted,1);}finally{f.close();}});
test('already applied before loss remains truthful; loss/restore refuses its late confirmation without undo',async()=>{const f=route();try{const pending=f.apply(90),settled=assert.rejects(pending),request=f.request();assert(f.intent.permits(request));const result=f.controller.receive(request,1)!;assert(result.accepted);f.frames.suspendContext();assert(f.frames.resumeContext());f.intent.complete({schemaVersion:1,browserRequestId:request.browserRequestId,accepted:true,settings:result.settings});await settled;assert.equal(f.state.resolutionPercent,90);assert.equal(f.mutations,1);assert.equal(f.persisted,1);}finally{f.close();}});
test('throwing and unknown request guards refuse while ordinary non-scan intents remain usable',async()=>{const f=route();try{for(const current of [()=>undefined as any,()=>{throw Error('unreadable');}])await assert.rejects(f.intent.changeResolution(90,current));assert.equal(f.messages.length,0);const pending=f.intent.changeResolution(90),request=f.request();assert(f.intent.permits(request));const result=f.controller.receive(request,1)!;f.intent.complete({schemaVersion:1,browserRequestId:request.browserRequestId,accepted:true,settings:result.settings});await pending;assert.equal(f.mutations,1);}finally{f.close();}});
test('in-flight recommendation loss/restore revokes the actual main native request before controller mutation',async()=>{const f=route(),document=Object.assign(new EventTarget(),{visibilityState:'visible' as const}),scan=new GraphicsEnvironmentScan({frames:f.frames,document,current:()=>true,presentationVisible:()=>true,settings:()=>f.state,capabilities:()=>({webgl2:true,contextAntialias:true,maximumTextureDimension:8192,maximumRenderbufferDimension:8192,maximumViewportWidth:8192,maximumViewportHeight:8192,drawingBufferWidth:640,drawingBufferHeight:480}),applyResolution:f.apply},5000,()=>3000);try{const sampling=scan.scan();for(let i=0;i<=20;i++)f.frames.publish({timestampMs:i*100,cpuSubmitMs:4,ready:true});assert.equal((await sampling).status,'complete');const applying=scan.applyOptionalResolution();f.frames.suspendContext();assert(f.frames.resumeContext());assert.equal(f.intent.permits(f.request()),false);assert.equal((await applying).accepted,false);assert.equal(f.mutations,0);assert.equal(f.persisted,0);assert.equal(f.state.resolutionPercent,100);}finally{scan.dispose();f.close();}});

test('actual World loss before first facade remains refused until an owned restored event even after GL clears',t=>{const f=world(t);f.w.installControls();assert.equal(f.w.graphicsScanSource,undefined);f.setLost(true);f.w.animate(1000);assert.equal(f.w.graphicsContextAvailable,false);assert.equal(f.w.graphicsScanSource,undefined);f.setLost(false);const frames=f.w.getGraphicsScanFrames();assert.equal(frames.contextEpoch,undefined);f.w.animate(1100);assert.equal(f.renders,0);f.fire('webglcontextrestored');assert.equal(frames.contextEpoch,1);f.w.animate(1200);assert.equal(f.renders,1);assert.equal(f.w.renderedFrames,1);});
test('actual World existing facade and frame counter remain suspended after GL clears before owned restoration',t=>{const f=world(t),frames=f.w.getGraphicsScanFrames();f.w.installControls();let published=0;frames.subscribe(()=>published++,()=>{});f.setLost(true);f.w.animate(1000);f.setLost(false);f.w.animate(1100);assert.equal(f.renders,0);assert.equal(f.w.renderedFrames,0);assert.equal(published,0);assert.equal(frames.contextEpoch,undefined);f.fire('webglcontextrestored');frames.subscribe(()=>published++,()=>{});f.w.animate(1200);assert.equal(f.renders,1);assert.equal(f.w.renderedFrames,1);assert.equal(published,1);});

test('actual World getter-first loss latches rendering until owned restoration even when GL clears before animate',t=>{const f=world(t),frames=f.w.getGraphicsScanFrames();f.w.installControls();f.setLost(true);assert.equal(frames.contextEpoch,undefined);assert.equal(f.w.graphicsContextAvailable,false);f.setLost(false);f.w.animate(1100);assert.equal(f.renders,0);assert.equal(f.w.renderedFrames,0);assert.equal(frames.contextEpoch,undefined);f.fire('webglcontextrestored');assert.equal(frames.contextEpoch,1);f.w.animate(1200);assert.equal(f.renders,1);assert.equal(f.w.renderedFrames,1);});
test('actual World presentation getter loss latches without a facade and requires an owned restored event',t=>{const f=world(t);f.w.installControls();f.w.enabled=true;f.setLost(true);assert.equal(f.w.graphicsScanPresentationVisible(),false);assert.equal(f.w.graphicsContextAvailable,false);assert.equal(f.w.graphicsScanSource,undefined);f.setLost(false);assert.equal(f.w.graphicsScanPresentationVisible(),false);f.w.enabled=false;f.w.animate(1100);assert.equal(f.renders,0);f.fire('webglcontextrestored');f.w.enabled=true;assert.equal(f.w.graphicsScanPresentationVisible(),true);f.w.enabled=false;f.w.animate(1200);assert.equal(f.renders,1);});
test('actual World presentation-only loss revokes completed recommendation epoch before immediate owned restoration',async t=>{const f=world(t),frames=f.w.getGraphicsScanFrames(),document=Object.assign(new EventTarget(),{visibilityState:'visible' as const});f.w.installControls();f.w.enabled=true;let applies=0;const state={version:1 as const,fieldOfView:70,resolutionPercent:100,localLights:true,cameraClipping:true},scan=new GraphicsEnvironmentScan({frames,document,current:()=>true,presentationVisible:()=>f.w.graphicsScanPresentationVisible(),settings:()=>state,capabilities:()=>({webgl2:true,contextAntialias:true,maximumTextureDimension:8192,maximumRenderbufferDimension:8192,maximumViewportWidth:8192,maximumViewportHeight:8192,drawingBufferWidth:640,drawingBufferHeight:480}),applyResolution:async percent=>{applies++;return {...state,resolutionPercent:percent};}},5000,()=>3000);try{const sampling=scan.scan();for(let i=0;i<=20;i++)frames.publish({timestampMs:i*100,cpuSubmitMs:4,ready:true});assert.equal((await sampling).status,'complete');f.setLost(true);assert.equal(f.w.graphicsScanPresentationVisible(),false);f.setLost(false);f.fire('webglcontextrestored');assert.equal((await scan.applyOptionalResolution()).accepted,false);assert.equal(applies,0);assert.equal(frames.contextEpoch,1);}finally{scan.dispose();}});
