// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {Group,Mesh,MeshBasicMaterial,PlaneGeometry,PerspectiveCamera,Vector2,Vector3} from 'three';
import {BrowserWorld} from './world';
import {WorldCpuFrameTiming} from './world-cpu-frame-timing';
function fixture(enabled=true){let now=0,draws=0,rafs=0,physics=0;const owner=new AbortController(),world=Object.create(BrowserWorld.prototype) as any;
 const timing=enabled?new WorldCpuFrameTiming(owner.signal,{sampleEveryFrames:1,now:()=>now}):undefined;
 const original=globalThis.requestAnimationFrame;globalThis.requestAnimationFrame=()=>{rafs++;return 17;};
 Object.assign(world,{entities:new Map([['private-id',{type:'Box'}]]),disposed:false,abort:owner,graphicsContextAvailable:true,imagePulseOwners:new Map(),cpuFrameTiming:timing,metrics:{sample(){now+=1;}},simulationClock:{advance(){return 1;},stepSeconds:1/60},modelScheduler:{stats:{active:0,queued:0}},compilingGraphics:0,enabled:true,initialSurfaceWait:{needsSupport:false,update(){return{waiting:false};}},pendingModelColliders:[],meshCollisions:new Map(),position:new Vector3(),spawn:new Vector3(),lastPose:10000,simulateMovement(){physics++;now+=2;},options:{onStatus(){},onPose(){throw Error('No out-of-sequence pose');}},pitch:0,yaw:0,camera:new PerspectiveCamera(),thirdPerson:false,self:new Group(),avatars:new Map(),lastLightSelection:10000,localLights:new Set(),pointSlots:[],spotSlots:[],presentationEnabled:true,scene:new Group(),renderer:{getContext:()=>({isContextLost:()=>false}),render(scene:Group,camera:PerspectiveCamera){assert.equal(scene,world.scene);assert.equal(camera,world.camera);draws++;now+=7;}},renderedFrames:0,recordLoadPhase(name:string){assert.equal(name,'graphicsSubmit');}});
 return{world,timing,owner,advance(ms:number){now+=ms;},get draws(){return draws;},get rafs(){return rafs;},get physics(){return physics;},cleanup(){timing?.dispose();globalThis.requestAnimationFrame=original;}};
}
test('actual World animate samples exclusive physics and original single render without changing arguments, ticks or RAF sequence',()=>{const f=fixture();try{f.world.animate(100);assert.equal(f.physics,1);assert.equal(f.draws,1);assert.equal(f.rafs,1);assert.equal(f.world.renderedFrames,1);const value=f.timing!.getSnapshot().populations.modelJobsIdle;assert.equal(value.samples,1);assert.equal(value.total.totalMs,10);assert.equal(value.segments.setup.totalMs,1);assert.equal(value.segments.physicsPose.totalMs,2);assert.equal(value.segments.renderSubmission.totalMs,7);}finally{f.cleanup();}});
test('actual default-off animate preserves original physics/render/RAF and allocates no diagnostic sampler',()=>{const f=fixture(false);try{f.world.animate(100);assert.equal(f.world.cpuFrameTiming,undefined);assert.equal(f.physics,1);assert.equal(f.draws,1);assert.equal(f.rafs,1);}finally{f.cleanup();}});
test('actual paused presentation still runs physics and labels its separate no-render sample correctly',()=>{const f=fixture();try{f.world.presentationEnabled=false;f.world.animate(100);assert.equal(f.draws,0);assert.equal(f.physics,1);assert.equal(f.rafs,1);const result=f.timing!.getSnapshot();assert.equal(result.populations.modelJobsIdle.samples,0);assert.equal(result.populations.paused.samples,1);assert.equal(result.populations.paused.segments.renderSubmission.totalMs,0);}finally{f.cleanup();}});
test('actual renderer failure consumes sampled ownership but retains original failure/RAF semantics',()=>{const f=fixture();try{f.world.renderer.render=()=>{throw Error('Actual render failure');};assert.throws(()=>f.world.animate(100),/Actual render failure/);assert.equal(f.rafs,0);assert.equal(f.timing!.getSnapshot().active,false);assert.equal(f.timing!.getSnapshot().failedFrames,1);assert.equal(f.timing!.getSnapshot().completedFrames,0);}finally{f.cleanup();}});
test('actual current load counters label samples loading, while post-load state labels modelJobsIdle rather than mixing async awaits',()=>{const f=fixture();try{f.world.modelScheduler.stats.queued=1;f.world.animate(100);f.world.modelScheduler.stats.queued=0;f.world.animate(101);const result=f.timing!.getSnapshot();assert.equal(result.populations.loading.samples,1);assert.equal(result.populations.modelJobsIdle.samples,1);}finally{f.cleanup();}});

test('actual pre-snapshot empty scene never contaminates the model-jobs-idle population',()=>{const f=fixture();try{f.world.entities.clear();f.world.animate(100);const result=f.timing!.getSnapshot();assert.equal(result.populations.emptyScene.samples,1);assert.equal(result.populations.modelJobsIdle.samples,0);}finally{f.cleanup();}});

test('modelJobsIdle deliberately does not claim Image or Material asset readiness outside the model scheduler',()=>{const f=fixture();try{f.world.pendingImageLoads=1;f.world.pendingMaterialLoads=1;f.world.animate(100);const result=f.timing!.getSnapshot();assert.equal(result.populations.modelJobsIdle.samples,1);assert.equal(Object.hasOwn(result.populations,'ready'),false);assert.equal(f.world.pendingImageLoads,1);assert.equal(f.world.pendingMaterialLoads,1);}finally{f.cleanup();}});

test('actual World bounded Image property work stays inside the exclusive visual-property segment without changing render order',()=>{const f=fixture(),root=new Group(),material=new MeshBasicMaterial(),mesh=new Mesh(new PlaneGeometry(),material);root.visible=true;const original=material.color.setRGB.bind(material.color);material.color.setRGB=(...args:Parameters<typeof material.color.setRGB>)=>{f.advance(3);return original(...args);};f.world.imagePulseOwners.set(root,{pulse:{created:0,min:0,max:1,period:0,colorMode:'in',alphaMode:'none'},entity:{color:{red:128,green:128,blue:128}},mesh,material,assertCurrent(){f.advance(2);},stop(){throw Error('Current pulse owner must remain active');}});try{f.world.animate(100);const result=f.timing!.getSnapshot().populations.modelJobsIdle;assert.equal(result.segments.avatarCamera.totalMs,5);assert.equal(result.segments.renderSubmission.totalMs,7);assert.equal(result.total.totalMs,15);assert.equal(f.draws,1);assert.equal(f.physics,1);assert.equal(f.rafs,1);}finally{mesh.geometry.dispose();material.dispose();f.cleanup();}});
