// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {getEventListeners} from 'node:events';
import {CPU_FRAME_SEGMENTS,WorldCpuFrameTiming} from './world-cpu-frame-timing';
function fixture(options:{sampleEveryFrames?:number;maximumSamples?:number}={}){let clock=0;const owner=new AbortController(),timing=new WorldCpuFrameTiming(owner.signal,{...options,now:()=>clock});return{timing,owner,set(value:number){clock=value;},add(value:number){clock+=value;}};}
test('exclusive synchronous spans sum exactly to the sampled frame, separated by loading/modelJobsIdle/paused populations',()=>{
 const f=fixture({sampleEveryFrames:1});for(const label of ['emptyScene','loading','modelJobsIdle','paused'] as const){const token=f.timing.beginFrame(label)!;CPU_FRAME_SEGMENTS.forEach((name,index)=>{f.add(index+1);assert.equal(f.timing.segment(token,name),true);});assert.equal(f.timing.endFrame(token,true),true);}
 const result=f.timing.getSnapshot();for(const population of Object.values(result.populations)){assert.equal(population.samples,1);assert.equal(population.total.totalMs,21);assert.equal(Object.values(population.segments).reduce((sum,segment)=>sum+segment.totalMs,0),21);assert.equal(population.segments.physicsPose.totalMs,2);assert.equal(population.segments.renderSubmission.totalMs,5);}f.timing.dispose();
});
test('one identity-owned token and fixed sample density reject foreign/stale end and clear abandoned frames',()=>{const f=fixture();const first=f.timing.beginFrame('modelJobsIdle')!;assert.equal(f.timing.endFrame({},true),false);assert.equal(f.timing.beginFrame('modelJobsIdle'),undefined);assert.equal(f.timing.endFrame(first,true),false);for(let i=0;i<6;i++)assert.equal(f.timing.beginFrame('modelJobsIdle'),undefined);const next=f.timing.beginFrame('modelJobsIdle')!;f.add(2);f.timing.endFrame(next,true);const result=f.timing.getSnapshot();assert.equal(result.observedFrames,9);assert.equal(result.sampledFrames,2);assert.equal(result.completedFrames,1);assert.equal(result.orphanedFrames,1);f.timing.dispose();});
test('maximum samples bound counters/storage; returned histogram/state copies cannot mutate internal diagnostics',()=>{const f=fixture({sampleEveryFrames:1,maximumSamples:2});for(let i=0;i<5;i++){const token=f.timing.beginFrame('modelJobsIdle');f.add(3);f.timing.endFrame(token,true);}const result=f.timing.getSnapshot();assert.equal(result.status,'complete');assert.equal(result.sampledFrames,2);assert.equal(result.observedFrames,2);assert.equal(result.completedFrames,2);result.populations.modelJobsIdle.total.histogram.fill(100);assert.equal(f.timing.getSnapshot().populations.modelJobsIdle.total.histogram.reduce((a,b)=>a+b),2);f.timing.dispose();});
test('failed render does not commit a misleading successful partial breakdown',()=>{const f=fixture();const token=f.timing.beginFrame('modelJobsIdle')!;f.add(9);f.timing.segment(token,'physicsPose');assert.equal(f.timing.endFrame(token,false),false);assert.equal(f.timing.getSnapshot().completedFrames,0);assert.equal(f.timing.getSnapshot().failedFrames,1);assert.equal(f.timing.getSnapshot().populations.modelJobsIdle.samples,0);f.timing.dispose();});
test('nonmonotonic/invalid clocks and intervals over the finite bound refuse samples without throwing into render',()=>{for(const value of [-1,NaN,Infinity,5001]){const f=fixture();const token=f.timing.beginFrame('modelJobsIdle')!;f.set(value);assert.equal(f.timing.segment(token,'renderSubmission'),false);assert.equal(f.timing.endFrame(token,true),false);assert.equal(f.timing.getSnapshot().invalidFrames,1);f.timing.dispose();}});
test('abort disposes ownership and its listener; context loss requires a fresh observer and retains no active token',()=>{for(const abort of [true,false]){const f=fixture();const token=f.timing.beginFrame('modelJobsIdle')!;if(abort){assert.equal(getEventListeners(f.owner.signal,'abort').length,1);f.owner.abort();assert.equal(getEventListeners(f.owner.signal,'abort').length,0);}else f.timing.loseContext();assert.equal(f.timing.endFrame(token,true),false);assert.equal(f.timing.beginFrame('modelJobsIdle'),undefined);assert.equal(f.timing.getSnapshot().active,false);assert.equal(f.timing.getSnapshot().status,abort?'disposed':'context-lost');f.timing.dispose();}});
test('construction refuses unbounded density/capacity and an already-aborted owner creates no listener',()=>{for(const value of [0,121,.5,Infinity])assert.throws(()=>fixture({sampleEveryFrames:value}),/Invalid/);assert.throws(()=>fixture({maximumSamples:2049}),/Invalid/);const owner=new AbortController();owner.abort();const timing=new WorldCpuFrameTiming(owner.signal);assert.equal(timing.beginFrame('modelJobsIdle'),undefined);assert.equal(getEventListeners(owner.signal,'abort').length,0);});
test('a forgotten final capacity token cannot remain active indefinitely through later frame starts',()=>{const f=fixture({maximumSamples:1});const token=f.timing.beginFrame('modelJobsIdle')!;assert.equal(f.timing.beginFrame('modelJobsIdle'),undefined);assert.equal(f.timing.getSnapshot().active,false);assert.equal(f.timing.getSnapshot().orphanedFrames,1);assert.equal(f.timing.endFrame(token,true),false);f.timing.dispose();});
test('invalid-clock attempts have a bounded observation lifetime even when no sample could begin',()=>{const f=fixture({maximumSamples:2,sampleEveryFrames:1});f.set(NaN);for(let i=0;i<10;i++)assert.equal(f.timing.beginFrame('modelJobsIdle'),undefined);const result=f.timing.getSnapshot();assert.equal(result.observedFrames,2);assert.equal(result.invalidFrames,2);assert.equal(result.status,'complete');f.timing.dispose();});
