// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {getEventListeners} from 'node:events';
import {Group,Mesh,PlaneGeometry,MeshBasicMaterial,Texture} from 'three';
import {BrowserWorld} from './world';import {GraphicsWarmupOwner} from './graphics-warmup-owner';import {WorldBitmapUpload,SessionUploadTexture} from './world-bitmap-upload';import {ModelResources} from './model-resources';
class ImageBoundary{naturalWidth=2;naturalHeight=2;}
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(error:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no;});return{promise,resolve,reject};}
function fixture(enabled=true){const previous=Object.getOwnPropertyDescriptor(globalThis,'HTMLImageElement');Object.defineProperty(globalThis,'HTMLImageElement',{value:ImageBoundary,configurable:true});
 const world=Object.create(BrowserWorld.prototype),abort=new AbortController(),root=new Group(),reader=new AbortController(),original=new Texture(new ImageBoundary() as unknown as HTMLImageElement),material=new MeshBasicMaterial({map:original});root.add(new Mesh(new PlaneGeometry(),material));
 const conversions:ReturnType<typeof deferred<ImageBitmap>>[]=[],compiler=deferred<void>();let compiled=0,current=true,generation='one',closes=0;
 Object.assign(world,{abort,disposed:false,shaderWarmup:false,zeroLightGuard:false,compilingGraphics:0,objects:new Map([['model',root]]),entities:new Map([['model',{type:'Model'}]]),modelReaders:new WeakMap([[root,reader]]),loadPhases:new Map(),bitmapBindingCounters:{roots:0,converted:0,fallbacks:0,unsupported:0,capacityFallbacks:0,activeRoots:0,peakRoots:0},renderer:{compileAsync(){compiled++;return compiler.promise;}},options:{captureAssetAuthority:()=>{const captured=generation;return{generation:captured,assertCurrent(){if(!current||captured!==generation)throw new DOMException('Actual authority ended','AbortError');}};},onStatus(){}},graphicsWarmups:new GraphicsWarmupOwner(abort.signal)});
 if(enabled)world.bitmapUploads=new WorldBitmapUpload({signal:abort.signal,createBitmap:()=>{const d=deferred<ImageBitmap>();conversions.push(d);return d.promise;}});
 return{world,abort,root,reader,original,material,conversions,compiler,get compiled(){return compiled;},get closes(){return closes;},pixels:()=>({width:2,height:2,close(){closes++;}} as ImageBitmap),revoke:()=>{current=false;},changeGeneration:()=>{generation='two';},close(){abort.abort();const resources=new ModelResources();resources.capture(root);resources.releaseKeeping();if(previous)Object.defineProperty(globalThis,'HTMLImageElement',previous);else Reflect.deleteProperty(globalThis,'HTMLImageElement');}};
}
const tick=async()=>{await new Promise(resolve=>setImmediate(resolve));};
async function promptly(p:Promise<unknown>){let timer:ReturnType<typeof setTimeout>|undefined;try{await Promise.race([assert.rejects(p,{name:'AbortError'}),new Promise((_yes,no)=>{timer=setTimeout(()=>no(Error('Cancellation did not settle owned bitmap preparation')),500);})]);}finally{if(timer)clearTimeout(timer);}}
test('actual default-off World performs original compile without bitmap authority capture or ownership',async()=>{const f=fixture(false);try{f.world.options.captureAssetAuthority=()=>{throw Error('Default path captured optional authority');};const p=f.world.prepareGraphics(f.root);assert.equal(f.compiled,1);assert.equal(f.material.map,f.original);f.compiler.resolve();await p;assert.equal(f.root.userData.shadersReady,true);}finally{f.close();}});
test('actual World retains original maps through exact compiler readiness, then publishes converted maps atomically',async()=>{const f=fixture();try{const p=f.world.prepareGraphics(f.root);assert.equal(f.conversions.length,0);assert.equal(f.compiled,1);assert.equal(f.material.map,f.original);f.compiler.resolve();await tick();assert.equal(f.conversions.length,1);assert.equal(f.material.map,f.original);f.conversions[0].resolve(f.pixels());await p;assert(f.material.map instanceof SessionUploadTexture);assert.equal(f.root.userData.shadersReady,true);assert.equal(f.world.compilingGraphics,0);assert.equal(f.world.bitmapBindingCounters.converted,1);}finally{f.close();}});
for(const cause of ['reader','root','world'])test('actual '+cause+' bitmap preparation cancellation settles with no original compiler resolution',async()=>{const f=fixture();try{
 const p=f.world.prepareGraphics(f.root,()=>f.world.objects.get('model')===f.root);assert.equal(getEventListeners(f.reader.signal,'abort').length,1);f.compiler.resolve();await tick();assert.equal(f.conversions.length,1);
 if(cause==='reader')f.reader.abort();else if(cause==='root'){f.world.cancelGraphics(f.root);f.world.objects.set('model',new Group());}else f.abort.abort();
 await promptly(p);assert.equal(f.compiled,1);assert.equal(f.material.map,f.original);assert.equal(f.world.compilingGraphics,0);assert.equal(getEventListeners(f.reader.signal,'abort').length,0);f.conversions[0].resolve(f.pixels());await tick();assert.equal(f.closes,1);assert.equal(f.root.userData.shadersReady,false);
 }finally{f.close();}});
test('actual authority ends while conversion runs: late pixels cannot replace an original borrowed sampler',async()=>{const f=fixture();try{const p=f.world.prepareGraphics(f.root);f.compiler.resolve();await tick();f.revoke();f.conversions[0].resolve(f.pixels());await assert.rejects(p,{name:'AbortError'});assert.equal(f.material.map,f.original);assert.equal(f.compiled,1);assert.equal(f.world.compilingGraphics,0);f.abort.abort();assert.equal(f.closes,1);}finally{f.close();}});
test('actual normal compiler wait after converted maps remains bounded and cancellable',async()=>{const f=fixture();try{const p=f.world.prepareGraphics(f.root);assert.equal(f.conversions.length,0);assert.equal(f.compiled,1);f.reader.abort();await promptly(p);assert.equal(f.world.compilingGraphics,0);assert.equal(getEventListeners(f.reader.signal,'abort').length,0);assert.equal(f.root.userData.shadersReady,false);f.compiler.reject(Error('Late real compile rejection'));await tick();}finally{f.close();}});
test('actual epoch invalidation keeps active physical bounds and refuses prior cached Source reuse',async()=>{const f=fixture();try{const p=f.world.prepareGraphics(f.root);f.compiler.resolve();await tick();f.world.invalidateSourceTexts();f.changeGeneration();await assert.rejects(p,{name:'AbortError'});assert.equal(f.world.bitmapUploads.stats().active,1);assert.equal(f.material.map,f.original);f.conversions[0].resolve(f.pixels());await tick();assert.equal(f.closes,1);assert.equal(f.world.bitmapUploads.stats().bytes,0);}finally{f.close();}});
test('actual World removal never directly closes a private bitmap while an independent current root retains its cloned sampler',async()=>{const f=fixture(),descriptor=Object.getOwnPropertyDescriptor(globalThis,'ImageBitmap');let closes=0;
 class BitmapBoundary{width=2;height=2;close(){closes++;}}
 Object.defineProperty(globalThis,'ImageBitmap',{value:BitmapBoundary,configurable:true});
 try{
  const pending=f.world.bitmapUploads.prepare(f.original,f.abort.signal);f.conversions[0].resolve(new BitmapBoundary() as unknown as ImageBitmap);const texture=await pending,clone=texture.clone(),other=new Group();f.material.map=texture;other.add(new Mesh(new PlaneGeometry(),new MeshBasicMaterial({map:clone})));
  Object.assign(f.world,{scene:new Group(),objects:new Map([['one',f.root],['two',other]]),entities:new Map([['one',{type:'Model'}],['two',{type:'Model'}]]),signatures:new Map(),meshCollisions:new Map(),modelGeometry:new WeakMap(),modelBatches:new Map(),localLights:new Map(),colliders:[],pendingModelColliders:[]});f.world.scene.add(f.root,other);
  f.world.removeEntities(['one']);assert.equal(closes,0);assert(f.world.bitmapUploads.isCurrent(clone));assert.equal(f.world.bitmapUploads.stats().leases,1);
  f.abort.abort();assert.equal(closes,0);f.world.removeEntities(['two']);assert.equal(closes,1);assert.equal(f.world.bitmapUploads.stats().leases,0);assert.equal(f.world.bitmapUploads.stats().bytes,0);assert.equal(f.world.objects.size,0);
 }finally{f.close();if(descriptor)Object.defineProperty(globalThis,'ImageBitmap',descriptor);else Reflect.deleteProperty(globalThis,'ImageBitmap');}
});

test('aggregate optional bitmap root budget falls back to original maps only under fresh current authority',async()=>{const f=fixture();try{f.world.bitmapBindingCounters.activeRoots=16;const p=f.world.prepareGraphics(f.root);assert.equal(f.conversions.length,0);assert.equal(f.compiled,1);assert.equal(f.material.map,f.original);f.compiler.resolve();await p;assert.equal(f.world.bitmapBindingCounters.activeRoots,16);assert.equal(f.world.bitmapBindingCounters.capacityFallbacks,1);assert.equal(f.root.userData.shadersReady,true);}finally{f.close();}});
test('authority revocation in bitmap capacity diagnostics prevents compiler or ready publication',async()=>{const f=fixture();try{f.world.bitmapBindingCounters.activeRoots=16;f.world.options.onStatus=f.revoke;const pending=f.world.prepareGraphics(f.root);f.compiler.resolve();await assert.rejects(pending,{name:'AbortError'});assert.equal(f.compiled,1);assert.equal(f.conversions.length,0);assert.equal(f.material.map,f.original);assert.equal(f.world.compilingGraphics,0);assert.equal(f.root.userData.shadersReady,false);}finally{f.close();}});

test('real shader compiler failure leaves original borrowed sampler and dispose listeners untouched without bitmap work',async()=>{const f=fixture();try{let disposals=0;f.original.addEventListener('dispose',()=>disposals++);const pending=f.world.prepareGraphics(f.root);f.compiler.reject(Error('Actual compiler failed'));await assert.rejects(pending,/Actual compiler failed/);assert.equal(f.material.map,f.original);assert.equal(disposals,0);assert.equal(f.conversions.length,0);assert.equal(f.world.bitmapUploads.stats().bytes,0);assert.equal(f.root.userData.shadersReady,false);assert.equal(f.world.compilingGraphics,0);}finally{f.close();}});
