// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Actual BrowserWorld methods, owned root/authority/reader transitions and Three
// graphs. The controlled driver is a boundary fixture, not a GPU speed claim.
import assert from 'node:assert/strict';
import test from 'node:test';
import {getEventListeners} from 'node:events';
import {BoxGeometry,CompressedTexture,Group,Mesh,MeshBasicMaterial,PerspectiveCamera,RGBA_S3TC_DXT5_Format,Scene,Texture,UnsignedByteType} from 'three';
import {BrowserWorld} from './world';
import {GraphicsWarmupOwner} from './graphics-warmup-owner';
import {WorldTexturePreparation} from './world-texture-preparation';
function deferred(){let resolve!:()=>void,reject!:(reason:unknown)=>void;const promise=new Promise<void>((yes,no)=>{resolve=yes;reject=no;});return {resolve,reject,promise};}
function fixture(enabled=true){
 const diagnostics:{message:string;kind:string}[]=[];const world=Object.create(BrowserWorld.prototype),abort=new AbortController(),scene=new Scene(),root=new Group(),camera=new PerspectiveCamera(90,1,1,100),ready=deferred(),calls:Texture[]=[];
 const texture=new CompressedTexture([{width:2,height:2,data:new Uint8Array(16)}],2,2,RGBA_S3TC_DXT5_Format,UnsignedByteType);texture.needsUpdate=true;
 const mesh=new Mesh(new BoxGeometry(),new MeshBasicMaterial({map:texture}));mesh.position.z=-5;root.add(mesh);scene.add(root);
 let approved=true,authorityCaptures=0,compiles=0;
 const renderer={compileAsync:async()=>{compiles++;await ready.promise;},initTexture:(value:Texture)=>calls.push(value)};
 Object.assign(world,{abort,disposed:false,enabled:true,presentationEnabled:true,shaderWarmup:false,zeroLightGuard:false,compilingGraphics:0,loadPhases:new Map(),scene,camera,objects:new Map([['entity',root]]),entities:new Map([['entity',{visible:true}]]),avatars:new Map(),self:new Group(),modelReaders:new WeakMap(),foregroundTextureCounts:{roots:0,bindings:0,unsupported:0,activeBindings:0,peakBindings:0,capacityFallbacks:0},renderer,options:{onStatus:(message:string,kind:string)=>diagnostics.push({message,kind}),captureAssetAuthority:()=>{authorityCaptures++;return {generation:'fixture',assertCurrent:()=>{if(!approved)throw new DOMException('Asset approval ended','AbortError');}};}}});
 if(enabled){world.graphicsWarmups=new GraphicsWarmupOwner(abort.signal);world.texturePreparations=new WorldTexturePreparation(renderer,{signal:abort.signal});}
 return {world,abort,scene,root,camera,mesh,texture,ready,calls,diagnostics,revoke:()=>{approved=false;},get authorityCaptures(){return authorityCaptures;},get compiles(){return compiles;},cleanup:()=>{abort.abort();mesh.geometry.dispose();mesh.material.dispose();texture.dispose();}};
}
test('actual default-off World keeps original compile and allocates no optional scheduler/authority ownership even if options later mutate',async()=>{const f=fixture(false);f.world.options.texturePreparation=true;const pending=f.world.prepareGraphics(f.root);assert.equal(f.compiles,1);assert.equal(f.authorityCaptures,0);f.ready.resolve();await pending;assert.equal(f.calls.length,0);assert.equal(f.root.userData.shadersReady,true);f.cleanup();});
test('actual World captures approval before compiler wait, then prepares only current foreground map before readiness publication',async()=>{const f=fixture();const pending=f.world.prepareGraphics(f.root,()=>f.world.objects.get('entity')===f.root);assert.equal(f.authorityCaptures,1);assert.equal(f.calls.length,0);assert.equal(f.root.visible,false);f.ready.resolve();await pending;assert.deepEqual(f.calls,[f.texture]);assert.equal(f.root.userData.shadersReady,true);assert.equal(f.root.visible,false,'Only existing publisher may reveal the root');assert.equal(f.world.compilingGraphics,0);assert.equal(f.world.loadPhases.get('foregroundTexturePreparation').count,1);f.cleanup();});
test('approval revoked while real compiler boundary waits never initializes a texture or reports ready',async()=>{const f=fixture();const pending=f.world.prepareGraphics(f.root);f.revoke();f.ready.resolve();await assert.rejects(pending,{name:'AbortError'});assert.equal(f.calls.length,0);assert.equal(f.root.userData.shadersReady,false);assert.equal(f.world.compilingGraphics,0);f.cleanup();});
test('root replacement while compiler waits invalidates captured private owner even with matching imported userData',async()=>{const f=fixture();const pending=f.world.prepareGraphics(f.root,()=>f.world.objects.get('entity')===f.root);const replacement=new Group();replacement.userData={...f.root.userData};f.world.cancelGraphics(f.root);f.world.objects.set('entity',replacement);f.ready.resolve();await assert.rejects(pending,{name:'AbortError'});assert.equal(f.calls.length,0);assert.equal(f.root.userData.shadersReady,false);f.cleanup();});
test('original model reader abort while compiler waits cancels upload/readiness although its root remains in private map',async()=>{const f=fixture(),reader=new AbortController();f.world.modelReaders.set(f.root,reader);const pending=f.world.prepareGraphics(f.root);reader.abort();f.ready.resolve();await assert.rejects(pending,{name:'AbortError'});assert.equal(f.calls.length,0);assert.equal(f.root.userData.shadersReady,false);assert.equal(f.world.texturePreparations.stats.references,0);f.cleanup();});
test('World presentation pause and entity visible:false do not eagerly allocate future/offscreen GPU maps',async()=>{for(const paused of [true,false]){const f=fixture();if(paused)f.world.presentationEnabled=false;else f.world.entities.set('entity',{visible:false});const pending=f.world.prepareGraphics(f.root);f.ready.resolve();await pending;assert.equal(f.calls.length,0);assert.equal(f.root.userData.shadersReady,true);assert.equal(f.world.texturePreparations.stats.submitted,0);f.cleanup();}});
test('first-person self, unattached rig and unowned imported publishing metadata remain original renderer first-use',async()=>{for(const mode of ['self','detached','unowned']){const f=fixture();f.world.objects.clear();if(mode==='self'){f.world.self=f.root;f.world.thirdPerson=false;}else if(mode==='detached'){f.scene.remove(f.root);f.world.avatars.set('participant',f.root);}else f.root.userData.entityID='entity';const pending=f.world.prepareGraphics(f.root);f.ready.resolve();await pending;assert.equal(f.calls.length,0);f.cleanup();}});
test('missing actual captured authority fails explicit opt-in while baseline was unchanged',async()=>{const f=fixture();f.world.options.captureAssetAuthority=undefined;await assert.rejects(f.world.prepareGraphics(f.root),/Missing texture preparation authority/);assert.equal(f.compiles,0);assert.equal(f.calls.length,0);assert.equal(f.root.userData.shadersReady,false);f.cleanup();});
async function promptRefusal(pending:Promise<void>){let timer:ReturnType<typeof setTimeout>|undefined;try{await Promise.race([assert.rejects(pending,{name:'AbortError'}),new Promise((_yes,no)=>{timer=setTimeout(()=>no(Error('Owned cancellation failed to settle a never-ready compiler')),500);})]);}finally{if(timer)clearTimeout(timer);}}
for(const cancellation of ['reader','root','world'] as const)test(`actual ${cancellation} cancellation promptly settles a never-ready compiler without resolving its original promise`,async()=>{
 const f=fixture(),reader=new AbortController();f.world.modelReaders.set(f.root,reader);const pending=f.world.prepareGraphics(f.root);assert.equal(f.world.compilingGraphics,1);assert.equal(getEventListeners(reader.signal,'abort').length,1);
 if(cancellation==='reader')reader.abort();else if(cancellation==='root')f.world.cancelGraphics(f.root);else f.abort.abort();
 await promptRefusal(pending);assert.equal(f.world.compilingGraphics,0);assert.equal(getEventListeners(reader.signal,'abort').length,0);assert.equal(f.world.texturePreparations.stats.references,0);assert.equal(f.root.userData.shadersReady,false);assert.equal(f.calls.length,0);f.cleanup();
});
test('actual aborted compiler late rejection is consumed after owner/listener cleanup',async()=>{
 const f=fixture(),errors:unknown[]=[],onUnhandled=(error:unknown)=>errors.push(error);process.on('unhandledRejection',onUnhandled);
 try{const pending=f.world.prepareGraphics(f.root);f.world.cancelGraphics(f.root);await promptRefusal(pending);f.ready.reject(Error('Late original driver compile failed'));await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(errors,[]);assert.equal(f.world.compilingGraphics,0);assert.equal(f.calls.length,0);}finally{process.removeListener('unhandledRejection',onUnhandled);f.cleanup();}
});
test('actual foreground-only readiness deadline rejects a never-ready original compiler and consumes its later failure',async t=>{
 t.mock.timers.enable({apis:['setTimeout']});const f=fixture(),reader=new AbortController();f.world.modelReaders.set(f.root,reader);const pending=f.world.prepareGraphics(f.root),refusal=assert.rejects(pending,/Graphics readiness exceeded its bounded timeout/);t.mock.timers.tick(30000);await refusal;assert.equal(f.world.compilingGraphics,0);assert.equal(f.root.userData.shadersReady,false);assert.equal(getEventListeners(reader.signal,'abort').length,0);assert.equal(f.calls.length,0);f.ready.reject(Error('Late deadline driver failure'));await new Promise(resolve=>setImmediate(resolve));f.cleanup();
});
test('actual aggregate descriptor-cap refusal keeps valid compiled geometry ready and records explicit normal-renderer fallback',async()=>{
 const f=fixture();f.world.foregroundTextureCounts.activeBindings=65536;const pending=f.world.prepareGraphics(f.root);f.ready.resolve();await pending;assert.equal(f.root.userData.shadersReady,true);assert.equal(f.world.foregroundTextureCounts.activeBindings,65536,'Other existing owners retain their reservation');assert.equal(f.world.foregroundTextureCounts.capacityFallbacks,1);assert.equal(f.calls.length,0);assert.equal(f.world.texturePreparations.stats.references,0);assert.equal(f.diagnostics.length,1);assert.equal(f.diagnostics[0].kind,'info');assert.match(f.diagnostics[0].message,/normal rendering/);f.cleanup();
});
test('actual queue-capacity refusal releases this plan and keeps original compiled geometry while another queue owner remains',async()=>{
 const f=fixture();f.world.texturePreparations.dispose();f.world.texturePreparations=new WorldTexturePreparation({initTexture:(map:Texture)=>f.calls.push(map)},{signal:f.abort.signal,maximumJobs:1});
 const other=new Group();other.add(new Mesh(new BoxGeometry(),new MeshBasicMaterial({map:f.texture})));const retained=f.world.texturePreparations.prepare(other,()=>{});const pending=f.world.prepareGraphics(f.root);f.ready.resolve();await pending;await retained;assert.equal(f.root.userData.shadersReady,true);assert.equal(f.world.foregroundTextureCounts.capacityFallbacks,1);assert.equal(f.world.foregroundTextureCounts.activeBindings,0);assert.equal(f.world.texturePreparations.stats.references,0);assert.equal(f.diagnostics.length,1);other.children.forEach((mesh:any)=>{mesh.geometry.dispose();mesh.material.dispose();});f.cleanup();
});
test('driver initialization failure is not optional-capacity fallback and cannot publish readiness',async()=>{
 const f=fixture();f.world.texturePreparations.dispose();f.world.texturePreparations=new WorldTexturePreparation({initTexture:()=>{throw Error('Real driver failure');}},{signal:f.abort.signal});const pending=f.world.prepareGraphics(f.root);f.ready.resolve();await assert.rejects(pending,/Real driver failure/);assert.equal(f.root.userData.shadersReady,false);assert.equal(f.world.foregroundTextureCounts.capacityFallbacks,0);assert.equal(f.world.foregroundTextureCounts.activeBindings,0);assert.deepEqual(f.diagnostics,[]);f.cleanup();
});
test('authority revocation takes precedence over an otherwise allowed optional resource fallback',async()=>{
 const f=fixture();f.world.foregroundTextureCounts.activeBindings=65536;const original=f.world.options.captureAssetAuthority;let checks=0;f.world.options.captureAssetAuthority=()=>{const authority=original();return {...authority,assertCurrent:()=>{if(++checks===4)f.revoke();authority.assertCurrent();}};};const pending=f.world.prepareGraphics(f.root);f.ready.resolve();await assert.rejects(pending,{name:'AbortError'});assert.equal(f.root.userData.shadersReady,false);assert.equal(f.world.foregroundTextureCounts.capacityFallbacks,0);assert.deepEqual(f.diagnostics,[]);f.cleanup();
});
test('authority changed by fallback diagnostics cannot publish a supposedly ready root afterward',async()=>{
 const f=fixture();f.world.foregroundTextureCounts.activeBindings=65536;f.world.options.onStatus=()=>f.revoke();const pending=f.world.prepareGraphics(f.root);f.ready.resolve();await assert.rejects(pending,{name:'AbortError'});assert.equal(f.root.userData.shadersReady,false);assert.equal(f.world.compilingGraphics,0);assert.equal(f.calls.length,0);f.cleanup();
});
