apply plugin: 'com.android.library'

def qtJarDir = System.getenv('HIFI_ANDROID_QT_ROOT') ?
    new File(System.getenv('HIFI_ANDROID_QT_ROOT'), 'jar') : file('libs')

android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api fileTree(dir: qtJarDir, include: ['*.jar'])
    api 'com.google.guava:guava:23.0'
}
