// SPDX-License-Identifier: Apache-2.0
// Executes the installed server's actual connection/revoke/watchdog functions,
// with sockets and launch/teardown replaced by bounded in-memory fixtures.
import test from 'node:test';import assert from 'node:assert/strict';
import vm from 'node:vm';import {EventEmitter} from 'node:events';import{readFileSync}from'node:fs';
import {AvatarSnapshotSender} from './avatar-snapshot-sender.mjs';
import {SharedTeardown}from'./process-lifecycle.mjs';import{pose,parse}from'./avatar-snapshot-fixture.mjs';
const source=readFileSync(new URL('./server.mjs',import.meta.url),'utf8');
function between(start,end){const a=source.indexOf(start),b=source.indexOf(end,a);assert(a>=0&&b>a);assert.equal(source.indexOf(start,a+start.length),-1);return source.slice(a,b);}
const sender=between('const send = (socket, value, observe) => {','const cookie = request');
const sessionSource=between('class Session extends SharedTeardown {','const server = http.createServer');
const browserSource=between("browserServer.on('connection', (browser, request) => {","nativeServer.on('connection', native => {");
const nativeSource=between("nativeServer.on('connection', native => {",'const heartbeat = setInterval');
class Socket extends EventEmitter{constructor(){super();this.readyState=1;this.bufferedAmount=0;this.writes=[];this.closes=[];}send(text,callback){this.writes.push({text,callback});}close(code,reason){this.closes.push({code,reason});if(this.readyState===3)return;this.readyState=3;this.emit('close');}}
function fixture(){let now=1000,uuid=0;const browserServer=new EventEmitter(),nativeServer=new EventEmitter();const context={AvatarSnapshotSender,SharedTeardown,WebSocket:{OPEN:1},sockets:new Set(),sessions:new Map(),shuttingDown:false,maximumSessions:4,browserServer,nativeServer,JSON,Number,Math,Map,Set,Promise,Date:{now:()=>now},randomUUID:()=>`session-${++uuid}`,randomBytes:()=>({toString:()=>`token-${uuid}`}),cookie:()=> 'synthetic-owner',equal:(a,b)=>a===b,send:undefined,PushToTalkSession:class{reset(){}receiveNative(){}},NativeHeartbeat:class{},clearTimeout:()=>{},setTimeout:()=>0,validateNativePermissions:()=>{},validatePublicPermissions:()=>{},process:{env:{OVERTE_GATEWAY_AVATAR_SAMPLE_DIAGNOSTICS:'1'},stdout:{write:()=>{}}}};
 vm.createContext(context);vm.runInContext(sender+sessionSource+'\nglobalThis.Session=Session;'+browserSource+nativeSource,context);
 context.Session.prototype.launch=async function() {this.permissionPolicy={permissions:{},settingsFile:'synthetic'};this.nativeDomain='synthetic';};
 context.Session.prototype.teardown=async function(){context.sessions.delete(this.id);};
 const browser=new Socket();browserServer.emit('connection',browser,{headers:{}});
 const call=async(socket,value)=>socket.listeners('message')[0](Buffer.from(JSON.stringify(value)),false);
 const join=async()=>{await call(browser,{type:'join',domain:'synthetic'});return [...context.sessions.values()].at(-1);};
 const connect=async(owner)=>{const native=new Socket();nativeServer.emit('connection',native);await call(native,{type:'nativeHello',token:owner.token});await call(native,{type:'permissions',permissionRevision:1,permissions:{}});return native;};
 return {context,browser,call,join,connect,time:value=>{now=value;},avatarWrites:()=>browser.writes.filter(x=>JSON.parse(x.text).type==='avatars')};}
function complete(target=false){const value=pose(target?{x:4,y:1.8,z:2}:{x:3,y:1.8,z:3});value.avatars[1].displayName='Native-Lab-Participant';return value;}
async function queued(){const f=fixture(),owner=await f.join(),native=await f.connect(owner);await f.call(native,complete());f.time(1800);await f.call(native,complete(true));return {...f,owner,native};}
test('actual callback observes captured payload and original receive time, not newer heartbeat',async()=>{const f=await queued();f.time(9000);await f.call(f.native,{type:'heartbeat'});assert.equal(f.owner.lastNativeMessage,9000);assert.equal(f.avatarWrites().length,1);f.avatarWrites()[0].callback();assert.equal(f.avatarWrites().length,2);assert.equal(f.owner.avatarDelivery.snapshot.at,1800);assert.equal(f.owner.avatarDelivery.snapshot.capturedFixtureTargetDistanceMeters,0);const value=parse(f.avatarWrites()[1].text);assert.equal(value.sessionId,f.owner.id);assert.equal(value.avatars.length,2);});
test('actual connecting and same-revision reapproval cannot resurrect unsent data',async()=>{const f=await queued();await f.call(f.native,{type:'state',state:'connecting'});assert.equal(f.owner.avatarSender.bounds().latestPending,0);await f.call(f.native,{type:'permissions',permissionRevision:1,permissions:{}});assert.equal(f.owner.connected,false);f.avatarWrites()[0].callback();assert.equal(f.avatarWrites().length,1);await f.call(f.native,complete(true));assert.equal(f.avatarWrites().length,2,'approved-before-connected remains eligible');});
test('actual changed permissions revision clears unsent snapshot',async()=>{const f=await queued();await f.call(f.native,{type:'permissions',permissionRevision:2,permissions:{}});f.avatarWrites()[0].callback();assert.equal(f.avatarWrites().length,1);assert.equal(f.owner.permissionRevision,2);});
test('actual leave/rejoin shares flight token and closes current owner on old callback failure',async()=>{const f=await queued(),channel=f.owner.avatarSender;await f.call(f.browser,{type:'leave'});const current=await f.join(),native=await f.connect(current);assert.equal(current.avatarSender,channel);await f.call(native,complete(true));assert.equal(f.avatarWrites().length,1);assert.equal(channel.bounds().physicalInFlight,1);f.avatarWrites()[0].callback(Error('private synthetic error'));assert(current.closed);assert.equal(f.browser.readyState,3);assert.equal(f.browser.closes.at(-1).code,1011);assert(!f.browser.writes.some(x=>x.text.includes('private synthetic error')));assert.equal(channel.bounds().latestPending,0);assert.equal(f.avatarWrites().length,1);});
test('actual native or browser close eagerly removes pending while flight remains until callback',async()=>{for(const kind of ['native','browser']){const f=await queued(),channel=f.owner.avatarSender;f[kind].close();assert.equal(channel.bounds().latestPending,0);assert.equal(channel.bounds().physicalInFlight,1);f.avatarWrites()[0].callback();assert.equal(channel.bounds().physicalInFlight,0);assert.equal(f.avatarWrites().length,1);}});
test('actual permission validation failure revokes before pending callback',async()=>{const f=await queued();f.context.validateNativePermissions=()=>{throw Error('synthetic');};await f.call(f.native,{type:'permissions',permissionRevision:1,permissions:{}});assert(f.owner.closed);assert.equal(f.owner.avatarSender.bounds().latestPending,0);f.avatarWrites()[0].callback();assert.equal(f.avatarWrites().length,1);});
function watchdog(f,start,end){const block=between(start,end);f.context.setInterval=fn=>fn;f.context.domains=[];f.context.readPolicyFile=async()=>new Map();f.context.resolvePublicPlace=async()=>{throw Error('synthetic');};vm.runInContext(block+'\nglobalThis.watch='+ (start.startsWith('let checkingPolicies')?'policyWatchdog':'publicPlaceWatchdog')+';',f.context);return f.context.watch;}
test('actual managed policy change/error and public destination change revoke pending',async()=>{for(const mode of ['managed-change','managed-error','public']){const f=await queued();let run;if(mode==='public'){f.owner.publicPlace={name:'synthetic',nativeDomain:'overte://synthetic'};run=watchdog(f,'let checkingPublicPlaces = false;','for (const websocketServer');}else{run=watchdog(f,'let checkingPolicies = false;','let checkingPublicPlaces = false;');if(mode==='managed-error')f.context.readPolicyFile=async()=>{throw Error('synthetic');};}await run();assert(f.owner.closed,mode);assert.equal(f.owner.avatarSender.bounds().latestPending,0,mode);f.avatarWrites()[0].callback();assert.equal(f.avatarWrites().length,1,mode);}});
test('actual entity overflow and generic audio/Tablet controls remain source-exact',async()=>{const f=await queued();f.browser.bufferedAmount=4*1024*1024;await f.call(f.native,{type:'entityUpdates',entities:[],removed:[]});assert.equal(f.browser.closes.at(-1).code,1013);assert(f.owner.closed);assert(source.includes('this.browser.bufferedAmount < 192000'));assert(source.includes("session.tablet?.receiveNative(message).catch(() => {"));});
test('coalesced offers are not falsely labeled as low-buffer write refusals',async()=>{const f=await queued();const first=f.owner.avatarDelivery.snapshot;assert.equal(first.sequence,1);assert.equal(first.writeInvoked,true);assert.equal(f.owner.avatarSender.bounds().latestPending,1);assert.equal(f.owner.avatarDelivery.snapshot,first);f.avatarWrites()[0].callback();assert.equal(f.owner.avatarDelivery.snapshot.sequence,2);assert.equal(f.owner.avatarDelivery.snapshot.writeInvoked,true);assert.equal(f.owner.avatarDelivery.snapshot.at,1800);});
test('diagnostics-off still uses same complete scheduling without exporting observations',async()=>{const f=fixture();delete f.context.process.env.OVERTE_GATEWAY_AVATAR_SAMPLE_DIAGNOSTICS;const owner=await f.join(),native=await f.connect(owner);await f.call(native,complete());await f.call(native,complete(true));assert.equal(f.avatarWrites().length,1);f.avatarWrites()[0].callback();assert.equal(f.avatarWrites().length,2);assert.equal(owner.avatarDelivery,undefined);});
