// SPDX-License-Identifier: Apache-2.0
import test from'node:test';import assert from'node:assert/strict';import{once}from'node:events';import{performance}from'node:perf_hooks';import WebSocket,{WebSocketServer}from'ws';import{AvatarSnapshotSender}from'./avatar-snapshot-sender.mjs';
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
export async function controlledPeer(Sender, mode){let server,client,socket,sender,owner,processing=false,consumedTargetAt=null,received=0,callbacks=0,closed=false;const queue=[],trace=[];const begin=performance.now();const note=(event,value)=>{if(trace.length<512)trace.push({event,elapsedMs:Math.round((performance.now()-begin)*1000)/1000,sequence:value?.delivery?.sequence??null,target:value?.avatars?.[0]?.position.x===4});};let cancelled=false;const timers=new Map();const delay=ms=>new Promise(resolve=>{const id=setTimeout(()=>{timers.delete(id);resolve();},ms);timers.set(id,resolve);});let processingDone=Promise.resolve();
try{server=new WebSocketServer({host:'127.0.0.1',port:0,perMessageDeflate:false,maxPayload:192*1024});await once(server,'listening');const connected=once(server,'connection');client=new WebSocket(`ws://127.0.0.1:${server.address().port}`);client.on('error',()=>{});[socket]=await connected;await once(client,'open');socket.on('error',()=>{});owner={id:'owned',browser:socket,native:{},permissionRevision:1,permissionsApproved:true,avatarConsumption:mode,closed:false,isCurrent:()=>!closed};sender=new Sender(socket,()=>owner);socket.on('message',data=>sender.acknowledge?.(owner,JSON.parse(data.toString())));
async function processQueue(){if(processing)return;processing=true;await delay(Math.max(0,700-(performance.now()-begin)));while(!cancelled && queue.length){const value=queue.shift();await delay(55);if(cancelled)break;note(2,value);const peer=value.avatars[0];if(peer.position.x===4)consumedTargetAt=performance.now()-begin;if(value.delivery){note(3,value);client.send(JSON.stringify({type:'avatarConsumed',delivery:value.delivery}));}}processing=false;}
client.on('message',data=>{received++;queue.push(JSON.parse(data.toString()));processingDone=processQueue();});const originalSend=socket.send.bind(socket);socket.send=(data,cb)=>{const value=JSON.parse(data);note(0,value);return originalSend(data,error=>{callbacks++;note(error?5:1,value);cb?.(error);});};
for(let i=0;i<60;i++){sender.offer(owner,{type:'avatars',avatars:[{id:'peer',position:{x:0,y:1.8,z:0}}]},i+1);await sleep(2);}sender.offer(owner,{type:'avatars',avatars:[{id:'peer',position:{x:4,y:1.8,z:2},jointNames:['hand'],jointTranslations:[{x:1,y:2,z:3}]}]},61);
await sleep(Math.max(0,2800-(performance.now()-begin)));const result={mode,trace,received,callbacks,targetWithinOriginal2800ms:consumedTargetAt!==null && consumedTargetAt<=2800,targetAtMs:consumedTargetAt,queueLength:queue.length,physicalInFlight:sender.bounds().physicalInFlight,pending:sender.bounds().latestPending};return result;
}finally{cancelled=true;closed=true;sender?.close();for(const [id,resolve] of timers){clearTimeout(id);resolve();}timers.clear();if(client){client.terminate();if(client.readyState!==WebSocket.CLOSED)await once(client,'close');}if(socket){socket.terminate();if(socket.readyState!==WebSocket.CLOSED)await once(socket,'close');}if(server)await new Promise(resolve=>server.close(resolve));assert.equal(server?server._server?.listening??false:false,false);assert.equal(server?server.clients.size:0,0);assert.equal(client?client.readyState:WebSocket.CLOSED,WebSocket.CLOSED);assert.equal(socket?socket.readyState:WebSocket.CLOSED,WebSocket.CLOSED);}}
test('real owned ws application-consumption credit coalesces newest complete behind slow consumption', {timeout:8000},async(t)=>{const legacy=await controlledPeer(AvatarSnapshotSender,'legacy'),current=await controlledPeer(AvatarSnapshotSender,'ack-v1');assert.equal(legacy.targetWithinOriginal2800ms,false);assert(legacy.received>=50);assert.equal(current.targetWithinOriginal2800ms,true);assert.equal(current.received,2);assert.equal(current.queueLength,0);assert.equal(current.pending,0);assert.equal(current.physicalInFlight,0);t.diagnostic(JSON.stringify({legacy,current}));});
