// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import{AvatarSnapshotSender,MAX_BUFFER,MAX_TEXT_CODE_UNITS,validAvatarDelivery}from'./avatar-snapshot-sender.mjs';
function setup(){let owner;const writes=[],socket={readyState:1,bufferedAmount:0,send(text,callback){writes.push({text,callback,delivery:JSON.parse(text).delivery});}};owner={id:'owned',browser:socket,native:{},permissionRevision:1,permissionsApproved:true,avatarConsumption:'ack-v1',closed:false,isCurrent:()=>true};let failures=0;const sender=new AvatarSnapshotSender(socket,()=>owner,()=>{},()=>{failures++;owner.closed=true;});return{sender,writes,socket,get owner(){return owner;},replace(v){owner=v;},get failures(){return failures;}};}
const pose=x=>({type:'avatars',avatars:[{id:'self',position:{x,y:1.8,z:2}}]});
const ack=delivery=>({type:'avatarConsumed',delivery});
test('callback completion alone cannot enqueue unconsumed application snapshots',()=>{const x=setup();x.sender.offer(x.owner,pose(0),1);x.writes[0].callback();for(let i=1;i<50;i++)x.sender.offer(x.owner,pose(i),i+1);assert.equal(x.writes.length,1);assert.equal(x.sender.bounds().physicalInFlight,0);assert.equal(x.sender.bounds().latestPending,1);assert.equal(x.sender.acknowledge(x.owner,ack(x.writes[0].delivery)),true);assert.equal(x.writes.length,2);assert.equal(JSON.parse(x.writes[1].text).avatars[0].position.x,49);});
test('ACK before real callback cannot release the physical flight',()=>{const x=setup();x.sender.offer(x.owner,pose(0),1);x.sender.offer(x.owner,pose(4),2);assert.equal(x.sender.acknowledge(x.owner,ack(x.writes[0].delivery)),true);assert.equal(x.writes.length,1);assert.equal(x.sender.bounds().physicalInFlight,1);x.writes[0].callback();assert.equal(x.writes.length,2);});
test('revocation/rejoin retires consumption but never old physical write',()=>{const x=setup(),old=x.owner;x.sender.offer(old,pose(0),1);const first=x.writes[0];old.closed=true;x.sender.invalidate(old);x.replace({...old,closed:false,id:'next',native:{}});x.sender.offer(x.owner,pose(4),2);assert.equal(x.sender.acknowledge(old,ack(first.delivery)),false);assert.equal(x.writes.length,1);first.callback();assert.equal(x.writes.length,2);first.callback();assert.equal(x.writes.length,2);assert.equal(x.writes[1].delivery.sessionId,'next');assert.equal(x.writes[1].delivery.epoch,1);});
test('late callback error closes current owner even after retired logical ACK',()=>{const x=setup(),old=x.owner;x.sender.offer(old,pose(0),1);x.sender.invalidate(old);x.replace({...old,id:'next',native:{}});x.sender.offer(x.owner,pose(4),2);x.writes[0].callback(Error('fixed-test'));assert.equal(x.failures,1);assert.equal(x.owner.closed,true);assert.equal(x.sender.bounds().latestPending,0);assert.equal(x.sender.consumption,null);});
test('strict stale/duplicate/future/foreign/private ACKs cannot retire credit',()=>{const x=setup();x.sender.offer(x.owner,pose(0),1);const d=x.writes[0].delivery;for(const message of [ack({...d,sequence:2}),ack({...d,epoch:1}),ack({...d,sessionId:'foreign'}),ack({...d,permissionRevision:2}),ack({...d,private:'no'}),{...ack(d),private:'no'},{type:'nativeConsumed',delivery:d}])assert.equal(x.sender.acknowledge(x.owner,message),false);assert.equal(x.sender.acknowledge({...x.owner},ack(d)),false);assert.equal(x.sender.acknowledge(x.owner,ack(d)),true);assert.equal(x.sender.acknowledge(x.owner,ack(d)),false);});
test('same revision reapproval cannot accept prior epoch ACK',()=>{const x=setup();x.sender.offer(x.owner,pose(0),1);const d=x.writes[0].delivery;x.owner.permissionsApproved=false;x.sender.invalidate(x.owner);x.owner.permissionsApproved=true;x.sender.offer(x.owner,pose(4),2);x.writes[0].callback();assert.equal(x.writes.length,2);assert.equal(x.sender.acknowledge(x.owner,ack(d)),false);assert.equal(x.sender.acknowledge(x.owner,ack(x.writes[1].delivery)),true);});
test('synchronous ACK/callback with reentrant offer remains bounded',()=>{const x=setup();let depth=0,max=0;x.socket.send=(text,callback)=>{depth++;max=Math.max(max,depth);const delivery=JSON.parse(text).delivery;x.writes.push({text,delivery,callback});assert.equal(x.sender.acknowledge(x.owner,ack(delivery)),true);callback();x.sender.offer(x.owner,pose(9),9);depth--;};x.sender.offer(x.owner,pose(0),1);assert.equal(x.writes.length,1);assert.equal(max,1);assert.equal(x.sender.bounds().latestPending,1);x.sender.offer(x.owner,pose(4),2);assert.equal(x.writes.length,2);assert.equal(max,1);});
test('approved before connected is eligible and immutable full data is retained',()=>{const x=setup();x.owner.connected=false;const v=pose(4);v.avatars[0].jointNames=['hand'];v.avatars[0].jointTranslations=[{x:1,y:2,z:3}];x.sender.offer(x.owner,v,1);v.avatars[0].position.x=99;assert.equal(JSON.parse(x.writes[0].text).avatars[0].position.x,4);assert.deepEqual(JSON.parse(x.writes[0].text).avatars[0].jointTranslations,[{x:1,y:2,z:3}]);x.writes[0].callback();assert(x.sender.acknowledge(x.owner,ack(x.writes[0].delivery)));});
test('send sequence is not consumed by buffering or pending replacement and fails closed at overflow',()=>{const x=setup();x.socket.bufferedAmount=MAX_BUFFER;x.sender.offer(x.owner,pose(0),1);x.sender.offer(x.owner,pose(4),2);assert.equal(x.sender.sequence,0);x.socket.bufferedAmount=0;x.sender.offer(x.owner,pose(4),3);assert.equal(x.writes[0].delivery.sequence,1);x.writes[0].callback();x.sender.acknowledge(x.owner,ack(x.writes[0].delivery));x.sender.sequence=Number.MAX_SAFE_INTEGER;assert.throws(()=>x.sender.offer(x.owner,pose(4),4),/exhausted/);assert.equal(x.failures,1);assert.equal(x.writes.length,1);});
test('unknown delivery shape, native injection and old legacy mode are explicit',()=>{const x=setup();for(const d of [null,{}, {version:2,sessionId:'owned',permissionRevision:1,epoch:0,sequence:1},{version:1,sessionId:'owned',permissionRevision:1,epoch:-1,sequence:1}])assert.equal(validAvatarDelivery(d),false);assert.throws(()=>x.sender.offer(x.owner,{...pose(0),delivery:{}},1),/not admitted/);x.owner.avatarConsumption='legacy';x.sender.offer(x.owner,pose(0),1);assert.equal(x.writes[0].delivery,undefined);x.writes[0].callback();x.sender.offer(x.owner,pose(4),2);assert.equal(x.writes.length,2);});

test('delivery metadata remains charged to unchanged wire text limit',()=>{const x=setup();const value=pose(0);value.padding='';value.padding='x'.repeat(MAX_TEXT_CODE_UNITS-JSON.stringify(value).length);assert.throws(()=>x.sender.offer(x.owner,value,1),/Gateway response too large/);assert.equal(x.writes.length,0);assert.equal(x.sender.sequence,0);assert.equal(x.failures,1);});
