// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import {AvatarSnapshotSender as AvatarSenderPrototype,MAX_BUFFER,MAX_TEXT_CODE_UNITS,MAX_TEXT_BYTES,avatarSnapshotText} from './avatar-snapshot-sender.mjs';
import {pose,parse,oldSend,setup} from './avatar-snapshot-fixture.mjs';
test('one physical callback and newest complete immutable snapshot',()=>{const x=setup(),first=pose({x:0,y:1.8,z:0}),last=pose({x:4,y:1.8,z:2});last.avatars[1].jointNames=['hand'];last.avatars[1].jointRotations=[{x:0,y:0,z:0,w:1}];last.avatars[1].jointTranslations=[{x:1,y:2,z:3}];x.sender.offer(x.owner,first,1);for(let i=0;i<40;i++)x.sender.offer(x.owner,pose({x:i,y:1.8,z:0}),2+i);x.sender.offer(x.owner,last,50);last.avatars[1].position.x=99;assert.equal(x.calls.length,1);assert.deepEqual(x.sender.bounds().physicalInFlight,1);assert.equal(x.sender.bounds().latestPending,1);x.calls[0].callback();assert.equal(x.calls.length,2);const decoded=parse(x.calls[1].text);assert.equal(decoded.avatars.length,2);assert.equal(decoded.avatars[1].position.x,4);assert.deepEqual(Array.from(decoded.avatars[1].jointNames),['hand']);assert.equal(decoded.avatars[1].jointTranslations[0].y,2);assert.equal(x.observed[1].at,50);});
test('same socket cannot acquire a second physical write channel',()=>{const x=setup();assert.throws(()=>new AvatarSenderPrototype(x.socket,()=>x.owner),/avatar-channel-already-owned/);x.sender.close();assert.throws(()=>new AvatarSenderPrototype(x.socket,()=>x.owner),/avatar-channel-already-owned/);});
test('known shared buffer cap keeps one latest without timer or inflation',()=>{const x=setup();x.socket.bufferedAmount=MAX_BUFFER;x.sender.offer(x.owner,pose({x:0,y:1.8,z:0}),1);x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),2);assert.equal(x.calls.length,0);assert.equal(x.observed.at(-1).writeInvoked,false);x.socket.bufferedAmount=0;assert.equal(x.calls.length,0);x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),3);assert.equal(x.calls.length,1);});
test('approval revocation with same revision needs eager invalidation',()=>{const x=setup();x.sender.offer(x.owner,pose({x:0,y:1.8,z:0}),1);x.sender.offer(x.owner,pose({x:1,y:1.8,z:0}),2);x.owner.permissionsApproved=false;x.sender.invalidate(x.owner);x.owner.permissionsApproved=true;x.calls[0].callback();assert.equal(x.calls.length,1);assert.equal(x.sender.bounds().latestPending,0);});
test('revision/native replacement and old owner refuse pending at callback',()=>{for(const change of ['revision','native','owner','closed']){const x=setup();x.sender.offer(x.owner,pose({x:0,y:1.8,z:0}),1);x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),2);if(change==='revision')x.owner.permissionRevision++;if(change==='native')x.owner.native={};if(change==='owner')x.replace({...x.owner});if(change==='closed')x.owner.closed=true;x.calls[0].callback();assert.equal(x.calls.length,1,change);}});
test('new session shares existing physical slot and old reset cannot discard new owner',()=>{const x=setup(),old=x.owner;x.sender.offer(old,pose({x:0,y:1.8,z:0}),1);old.closed=true;x.sender.invalidate(old);x.replace({...old,closed:false,native:{}});x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),2);x.sender.invalidate(old);assert.equal(x.calls.length,1);x.calls[0].callback();assert.equal(x.calls.length,2);x.calls[0].callback();assert.equal(x.calls.length,2);assert.equal(x.sender.bounds().physicalInFlight,1);});
test('browser close and callback errors cannot report retirement or resume',()=>{for(const error of [false,true]){const x=setup();x.sender.offer(x.owner,pose({x:0,y:1.8,z:0}),1);x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),2);if(!error)x.sender.close();x.calls[0].callback(error?Error('synthetic'):undefined);assert.equal(x.calls.length,1);assert.equal(x.sender.bounds().latestPending,0);assert.equal(x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),3),false);}});
test('observer exception cannot clear a physical write or alter complete payload',()=>{const x=setup();x.sender.observe=()=>{throw Error('synthetic-observer');};assert.equal(x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),1),true);assert.equal(x.sender.bounds().physicalInFlight,1);assert.equal(x.sender.observationRefused,true);assert.equal(parse(x.calls[0].text).avatars[1].position.x,4);x.calls[0].callback();assert.equal(x.sender.bounds().physicalInFlight,0);});
test('synchronous write failure propagates and retains no pending authority',()=>{const x=setup();x.socket.send=()=>{throw Error('synthetic');};assert.throws(()=>x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),1),/synthetic/);assert.equal(x.sender.bounds().latestPending,0);assert.equal(x.sender.bounds().physicalInFlight,0);});
test('authority getter mutation invalidates offer before writes',()=>{const x=setup();x.owner.isCurrent=()=>{x.sender.invalidate(x.owner);return true;};assert.equal(x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),1),false);assert.equal(x.calls.length,0);});
test('original generic send closed/cap/write branches characterized unchanged',()=>{for(const [state,bytes,expected]of[[3,0,0],[1,MAX_BUFFER,0],[1,0,1]]){const sent=[],observed=[],socket={readyState:state,bufferedAmount:bytes,send:t=>sent.push(t)};oldSend(socket,pose({x:4,y:1.8,z:2}),(...x)=>observed.push(x));assert.equal(sent.length,expected);assert.equal(observed[0][2],!!expected);}});

test('synchronous callback and reentrant offers cannot recursively write',()=>{const x=setup();let depth=0,maxDepth=0;x.socket.send=(text,callback)=>{depth++;maxDepth=Math.max(maxDepth,depth);x.calls.push({text,callback});callback();x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),2);depth--;};x.sender.offer(x.owner,pose({x:0,y:1.8,z:0}),1);assert.equal(x.calls.length,1);assert.equal(maxDepth,1);assert.equal(x.sender.bounds().physicalInFlight,0);assert.equal(x.sender.bounds().latestPending,1);x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),3);assert.equal(x.calls.length,2);assert.equal(maxDepth,1);assert.equal(parse(x.calls[1].text).sessionId,'synthetic');});
test('reentrant authority supersession sends only the newest captured owner value',()=>{const x=setup();x.socket.bufferedAmount=MAX_BUFFER;x.sender.offer(x.owner,pose({x:0,y:1.8,z:0}),1);x.socket.bufferedAmount=0;let once=true;x.owner.isCurrent=()=>{if(once){once=false;x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),7);}return true;};x.sender.pump();assert.equal(x.calls.length,0);assert.equal(x.sender.bounds().latestPending,1);x.sender.pump();assert.equal(x.calls.length,1);assert.equal(parse(x.calls[0].text).avatars[1].position.x,4);assert.equal(x.observed.at(-1).at,7);assert.equal(x.observed.at(-1).writeInvoked,true);});
test('reentrant revocation and new session offer cannot free the old physical slot',()=>{const x=setup(),old=x.owner;x.sender.observe=()=>{x.owner.permissionsApproved=false;x.sender.invalidate(old);x.replace({...old,permissionsApproved:true,native:{}});x.sender.observe=v=>x.observed.push(v);x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),9);};x.sender.offer(old,pose({x:0,y:1.8,z:0}),1);assert.equal(x.calls.length,1);assert.equal(x.sender.bounds().physicalInFlight,1);assert.equal(x.sender.bounds().latestPending,1);x.calls[0].callback();assert.equal(x.calls.length,2);x.calls[0].callback();assert.equal(x.calls.length,2);assert.equal(x.observed[0].at,9);assert.equal(parse(x.calls[1].text).sessionId,'synthetic');});
test('approved before connected remains eligible without inventing a connected gate',()=>{const x=setup();x.owner.connected=false;assert.equal(x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),4),true);assert.equal(x.calls.length,1);});
test('frontend code-unit limit admits Unicode bytes above16MiB and refuses one extra unit',()=>{const value=pose({x:4,y:1.8,z:2});value.padding='';const overhead=JSON.stringify(value).length;value.padding='é'.repeat(MAX_TEXT_CODE_UNITS-overhead);const text=avatarSnapshotText(value);assert.equal(text.length,MAX_TEXT_CODE_UNITS);assert(Buffer.byteLength(text)>MAX_TEXT_CODE_UNITS);assert(Buffer.byteLength(text)<=MAX_TEXT_BYTES);assert.equal(parse(text).avatars.length,2);value.padding+='x';assert.throws(()=>avatarSnapshotText(value),/Gateway response too large/);});
test('avatar and joint boundaries agree with shipping frontend parser and keep full participants',()=>{for(const mutate of [v=>{v.avatars=Array(10001).fill(v.avatars[0]);},v=>{v.avatars[1].jointNames=Array(1001).fill('hand');},v=>{v.avatars[1].jointNames=['hand'];v.avatars[1].jointRotations=[];},v=>{v.avatars[1].jointNames=['hand'];v.avatars[1].jointTranslations=[{x:1000000,y:0,z:0}];},v=>{v.avatars[1].scale=1001;},v=>{v.message=42;}]){const v=pose({x:4,y:1.8,z:2});mutate(v);assert.throws(()=>parse(JSON.stringify(v)));assert.throws(()=>avatarSnapshotText(v));}const v=pose({x:4,y:1.8,z:2});v.avatars=Array.from({length:10000},(_,i)=>({...v.avatars[i%2],id:String(i)}));assert.equal(parse(avatarSnapshotText(v)).avatars.length,10000);});
test('closed socket offer records an actual refused branch without creating a write',()=>{const x=setup();x.socket.readyState=3;x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),10);assert.equal(x.calls.length,0);assert.equal(x.observed.length,1);assert.equal(x.observed[0].open,false);assert.equal(x.observed[0].bytes,null);assert.equal(x.observed[0].writeInvoked,false);});
test('reentrant socket-state inspection rechecks approval before issuing',()=>{const x=setup();Object.defineProperty(x.socket,'bufferedAmount',{get(){x.owner.permissionsApproved=false;x.sender.invalidate(x.owner);return 0;}});x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),10);assert.equal(x.calls.length,0);assert.equal(x.sender.bounds().latestPending,0);});
test('synchronous callback error followed by throw reports physical failure once',()=>{const x=setup();let failures=0;x.sender.onError=()=>{failures++;};x.socket.send=(text,callback)=>{callback(Error('synthetic'));throw Error('synthetic');};assert.throws(()=>x.sender.offer(x.owner,pose({x:4,y:1.8,z:2}),10));assert.equal(failures,1);assert.equal(x.sender.bounds().physicalInFlight,0);assert.equal(x.sender.bounds().latestPending,0);});
