// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {gunzipSync} from 'node:zlib';
import {buildBrowserCaptureUI,AUDIO_SCRIPT_SHA256} from './browser-capture-overrides.mjs';import {inactiveCapture} from '../shared/browser-capture.mjs';
const signal=()=>({callbacks:new Set(),connect(fn){this.callbacks.add(fn);},disconnect(fn){this.callbacks.delete(fn);},emit(...args){for(const fn of [...this.callbacks])fn(...args);}}),channel='overte.browser.capture.'+'1'.repeat(32);
const original=gunzipSync(await readFile(new URL('./fixtures/native-audio-f91d15a.js.gz',import.meta.url))).toString(),helper=await readFile(new URL('./native-browser-capture.js',import.meta.url),'utf8');
const historicalHelper=gunzipSync(await readFile(new URL('./fixtures/native-browser-capture-readback-before.js.gz',import.meta.url))).toString();
function native(source=helper){const message=signal(),sent=[],local=[];let now=0,nav=1,visible=true;const ctx={Messages:{subscribe(){},unsubscribe(){},messageReceived:message,sendLocalMessage(c,t){local.push(JSON.parse(t));}}};vm.runInNewContext(source+';this.create=createBrowserCapture;',ctx);const instance=ctx.create({channel,send:m=>sent.push(m),now:()=>now,current:()=>visible,navigation:()=>nav,qmlURL:'file:///tmp/own/browser-audio.qml'});return{message,sent,local,instance,time:v=>now=v,navigate(v){nav=v;instance.resetView();},hide(){visible=false;instance.poll();},page(active=true){instance.screen(active?'QML':'Home',active?'file:///tmp/own/browser-audio.qml':'');},epoch(){return local.filter(m=>m.kind==='scope').at(-1).epoch;},change(field,value){message.emit(channel,JSON.stringify({kind:'change',epoch:local.filter(m=>m.kind==='scope').at(-1).epoch,field,value}),'',true);},ack(state,extra={}){const q=sent.at(-1);instance.receive({action:'captureResult',schemaVersion:1,requestId:q.requestId,revision:2,navigationSequence:nav,accepted:true,reason:'ok',state,...extra});}};}
function active(){return{version:1,active:true,controls:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,inputGainPercent:true},settings:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,inputGainPercent:100,inputGain:1}};}
test('exact packaged native Audio script retains original native controls and opens only an own file wrapper',()=>{assert.equal(createHash('sha256').update(original).digest('hex'),AUDIO_SCRIPT_SHA256);const g=buildBrowserCaptureUI(original,channel,'file:///tmp/own/browser-audio.qml');assert(g.script.includes('tablet.loadQMLSource(AUDIO_QML_SOURCE)'));assert(g.script.includes('Audio.pushToTalkChanged.connect(onMuteToggled)'));assert(g.script.includes('Audio.mutedChanged.connect(onMuteToggled)'));assert(g.qml.includes("source:'qrc:/qml/hifi/audio/Audio.qml'"));assert(g.qml.includes("text:'Native connection'"));assert(g.qml.includes("text:'Browser microphone'"));assert(!g.qml.includes('AudioScriptingInterface.acousticEchoCancellation ='));assert(!g.qml.includes('objectName:'));assert(g.qml.includes("onPressedChanged:if(!pressed)root.change('inputGainPercent'"));assert.throws(()=>buildBrowserCaptureUI(original+'\n',channel,'file:///tmp/browser-audio.qml'));assert.throws(()=>buildBrowserCaptureUI(original,channel,'https://example.invalid/browser-audio.qml'));assert.throws(()=>buildBrowserCaptureUI(original,channel,'file:///tmp/other.qml'));});
test('real authored Audio click opens the own QML path and selected page publishes only a private local request',()=>{const m=signal(),screen=signal(),from=signal(),click=signal(),ending=signal(),loaded=[],calls=[];const generated=buildBrowserCaptureUI(original,channel,'file:///tmp/own/browser-audio.qml');vm.runInNewContext(generated.script,{Script:{resolvePath:x=>x,getExternalPath:()=>'',ExternalPaths:{HF_Content:0},scriptEnding:ending},Entities:{editEntity(){throw Error('Desktop must not mutate an entity');}},HMD:{tabletID:null,displayModeChanged:signal()},Audio:{pushToTalk:false,muted:true,pushToTalkChanged:signal(),mutedChanged:signal()},Messages:{subscribe(){},unsubscribe(){},messageReceived:m,sendLocalMessage(c,t){calls.push({c,m:JSON.parse(t)});}},Tablet:{getTablet(){return {screenChanged:screen,fromQml:from,addButton(p){assert.equal(p.text,'AUDIO');assert.equal(p.sortOrder,1);return{clicked:click,editProperties(){}};},loadQMLSource:s=>loaded.push(s),sendToQml:m=>calls.push({qml:m}),gotoHomeScreen(){},removeButton(){}};}}});click.emit();assert.equal(loaded[0],'file:///tmp/own/browser-audio.qml');screen.emit('QML',loaded[0]);m.emit(channel,JSON.stringify({kind:'scope',epoch:1,active:true}),'',true);from.emit({type:'browserCaptureChange',epoch:1,field:'echoCancellation',value:false});assert(calls.some(v=>v.m?.kind==='change'&&v.m.field==='echoCancellation'));m.emit(channel,JSON.stringify({kind:'effective',epoch:1,sequence:1,ready:true,state:{...active(),privateDevice:'secret'},reason:'ok'}),'',true);assert(!calls.some(v=>v.qml?.type==='browserCaptureState')); m.emit(channel,JSON.stringify({kind:'effective',epoch:1,sequence:2,ready:true,state:active(),reason:'ok'}),'',true);assert(calls.some(v=>v.qml?.type==='browserCaptureState'));ending.emit();assert.equal(from.callbacks.size,0);assert.equal(m.callbacks.size,0);});
test('native capture adapter refuses unapproved UI, wrong channel and nonlocal requests',()=>{const f=native();f.page();assert.equal(f.sent.length,0);f.instance.setAuthority(2,true);assert.equal(f.sent.length,1);f.ack(active());f.message.emit('foreign',JSON.stringify({kind:'change',field:'echoCancellation',value:false}),'',true);f.message.emit(channel,JSON.stringify({kind:'change',field:'echoCancellation',value:false}),'',false);assert.equal(f.sent.length,1);});
test('one native pending request requires exact id/revision/effective state and never acknowledges unsupported UI control',()=>{const f=native();f.instance.setAuthority(2,true);f.page();f.ack(active(),{revision:1});assert.equal(f.local.filter(m=>m.kind==='effective').at(-1).ready,false);f.ack(active());f.change('deviceId','private');assert.equal(f.sent.length,1);f.change('noiseSuppression',false);f.change('echoCancellation',false);assert.equal(f.sent.length,2);const q=f.sent.at(-1);assert.equal(q.field,'noiseSuppression');assert.equal(q.value,false);f.ack(active(),{requestId:999});assert.equal(f.local.filter(m=>m.kind==='effective').at(-1).ready,false);});
test('native page/authority/close discard pending confirmations and keep original eight-second deadline',()=>{const f=native();f.instance.setAuthority(2,true);f.page();f.page(false);f.ack(active());assert.equal(f.local.filter(m=>m.kind==='effective').at(-1).ready,false);f.page();f.time(8000);f.instance.poll();assert.equal(f.local.filter(m=>m.kind==='effective').at(-1).reason,'deadline');f.instance.setAuthority(3,false);f.ack(active());assert.equal(f.local.filter(m=>m.kind==='effective').at(-1).ready,false);f.instance.close();assert.equal(f.message.callbacks.size,0);});
test('inactive browser capture stays visibly unsupported; no native adapter can request microphone consent or devices',()=>{const f=native();f.instance.setAuthority(2,true);f.page();f.ack(inactiveCapture());f.change('echoCancellation',false);assert.equal(f.sent.length,1);assert(!helper.includes('getUserMedia'));assert(!helper.includes('enumerateDevices'));});

test('native navigation and hide invalidate pending operation ownership; old confirmation cannot enable controls',()=>{const f=native();f.instance.setAuthority(2,true);f.page();f.ack(active());f.change('echoCancellation',false);const old=f.sent.at(-1);f.navigate(2);f.instance.receive({...old,action:'captureResult',revision:2,accepted:true,reason:'ok',state:active()});assert.equal(f.local.filter(m=>m.kind==='effective').at(-1).ready,false);f.page();f.ack(active());assert.equal(f.local.filter(m=>m.kind==='effective').at(-1).ready,true);f.hide();assert.equal(f.local.filter(m=>m.kind==='effective').at(-1).ready,false);});
test('a genuine native page departure sends an ordered cancellation only for its current pending operation',()=>{const f=native();f.instance.setAuthority(2,true);f.page();f.ack(active());f.change('noiseSuppression',false);const old=f.sent.at(-1);f.page(false);assert.equal(f.sent.at(-1).operation,'cancel');assert.equal(f.sent.at(-1).navigationSequence,1);assert(f.sent.at(-1).requestId>old.requestId);f.ack(active());assert.equal(f.local.filter(m=>m.kind==='effective').at(-1).ready,false);});
test('supported controls cannot claim a missing effective browser readback in the native helper or authored UI',()=>{const f=native();f.instance.setAuthority(2,true);f.page();const invalid=active();invalid.settings.echoCancellation=null;f.ack(invalid);assert.equal(f.local.filter(m=>m.kind==='effective').at(-1).ready,false);const ui=buildBrowserCaptureUI(original,channel,'file:///tmp/browser-audio.qml');assert(ui.script.includes('(s.controls[f]&&v===null)'));assert(ui.qml.includes('function restoreControls()'));assert(ui.qml.includes('Connections{target:nativeAudio.item'));});

test('historical periodic readback disables previously ready UI before delivery; old omission is a counterexample',()=>{
 const f=native(historicalHelper);f.instance.setAuthority(2,true);f.page();f.ack(active());assert.equal(f.local.at(-1).ready,true);f.time(1000);f.instance.poll();assert.equal(f.sent.at(-1).operation,'request');assert.equal(f.local.at(-1).ready,false);assert.equal(f.local.at(-1).reason,'busy');
 assert(historicalHelper.includes("ui('busy');config.send(m);"));
 const old=historicalHelper.replace("ui('busy');config.send(m);","config.send(m);if(operation==='change'||!state)ui();");const ctx={Messages:{subscribe(){},unsubscribe(){},messageReceived:signal(),sendLocalMessage(c,t){ctx.local.push(JSON.parse(t));}},local:[]};vm.runInNewContext(old+';this.create=createBrowserCapture;',ctx);let now=0;const sent=[];const instance=ctx.create({channel,qmlURL:'own',current:()=>true,navigation:()=>1,now:()=>now,send:m=>sent.push(m)});instance.setAuthority(2,true);instance.screen('QML','own');instance.receive({action:'captureResult',schemaVersion:1,revision:2,requestId:sent.at(-1).requestId,navigationSequence:1,accepted:true,reason:'ok',state:active()});now=1000;instance.poll();assert.equal(ctx.local.at(-1).ready,true);
});
test('one already-issued current-epoch intent survives periodic readback and never overlaps a browser operation',()=>{
 const f=native();f.instance.setAuthority(2,true);f.page();f.ack(active());f.time(1000);f.instance.poll();const count=f.sent.length;f.change('noiseSuppression',false);f.change('echoCancellation',false);assert.equal(f.sent.length,count);assert.equal(f.local.at(-1).reason,'busy');f.ack(active());assert.equal(f.sent.length,count+1);assert.equal(f.sent.at(-1).field,'noiseSuppression');assert.equal(f.local.at(-1).ready,false);const changed=active();changed.settings.noiseSuppression=false;f.ack(changed);assert.equal(f.local.at(-1).ready,true);assert.equal(f.local.at(-1).state.settings.noiseSuppression,false);
});
test('readback timeout/refusal and navigation discard queued intent without late application',()=>{
 for(const mode of ['timeout','refusal','home','revision']){const f=native();f.instance.setAuthority(2,true);f.page();f.ack(active());f.time(1000);f.instance.poll();f.change('noiseSuppression',false);if(mode==='timeout'){f.time(9000);f.instance.poll();}else if(mode==='refusal')f.ack(active(),{accepted:false,reason:'busy'});else if(mode==='home')f.navigate(2);else f.instance.setAuthority(3,false);assert(!f.sent.some(m=>m.operation==='change'));}
});
test('old local page and old QML epoch cannot rebind Home, authority reset or genuine Audio reentry',()=>{
 const f=native();f.instance.setAuthority(2,true);f.page();f.ack(active());const old=f.epoch();f.navigate(2);const count=f.sent.length;for(const m of [{kind:'page',active:true},{kind:'ready',epoch:old},{kind:'change',epoch:old,field:'echoCancellation',value:false}])f.message.emit(channel,JSON.stringify(m),'',true);assert.equal(f.sent.length,count);f.page();assert(f.epoch()>old);f.ack(active());const newCount=f.sent.length;f.message.emit(channel,JSON.stringify({kind:'change',epoch:old,field:'echoCancellation',value:false}),'',true);assert.equal(f.sent.length,newCount);f.instance.setAuthority(3,false);f.message.emit(channel,JSON.stringify({kind:'page',active:true}),'',true);assert.equal(f.sent.length,newCount);f.instance.setAuthority(4,true);const r=f.sent.length;f.message.emit(channel,JSON.stringify({kind:'ready',epoch:old}),'',true);assert.equal(f.sent.length,r);
});
test('exact native screen source rejects path aliases and resets epoch on same-navigation departure/reentry',()=>{
 const f=native();f.instance.setAuthority(2,true);f.instance.screen('QML','file:///other/browser-audio.qml');f.instance.screen('Web','file:///tmp/own/browser-audio.qml');assert.equal(f.sent.length,0);f.page();f.ack(active());const epoch=f.epoch();f.page(false);f.page();assert(f.epoch()>epoch);assert.equal(f.sent.at(-1).navigationSequence,1);
});
test('supported native gain cannot accept null amplitude in shared or generated-script validation',async()=>{
 const {captureState}=await import('../shared/browser-capture.mjs');const invalid=active();invalid.settings.inputGain=null;assert.throws(()=>captureState(invalid),/amplitude/);const f=native();f.instance.setAuthority(2,true);f.page();f.ack(invalid);assert.equal(f.local.at(-1).ready,false);
 const script=buildBrowserCaptureUI(original,channel,'file:///tmp/own/browser-audio.qml').script;const a=script.indexOf('function browserCaptureStateValid('),z=script.indexOf('\nfunction browserCaptureMessage',a);const ctx={};vm.runInNewContext(script.slice(a,z)+';this.valid=browserCaptureStateValid;',ctx);assert.equal(ctx.valid(invalid),false);assert.equal(ctx.valid(active()),true);
});
test('generated original Audio route forwards only originating current QML epoch on actual Audio page',()=>{
 const screen=signal(),from=signal(),messages=signal(),sent=[],qml=[],ending=signal();const g=buildBrowserCaptureUI(original,channel,'file:///tmp/own/browser-audio.qml');vm.runInNewContext(g.script,{Script:{resolvePath:x=>x,getExternalPath:()=>'',ExternalPaths:{HF_Content:0},scriptEnding:ending},Entities:{editEntity(){}},HMD:{tabletID:null,displayModeChanged:signal()},Audio:{pushToTalk:false,muted:true,pushToTalkChanged:signal(),mutedChanged:signal()},Messages:{subscribe(){},unsubscribe(){},messageReceived:messages,sendLocalMessage(c,t){sent.push(JSON.parse(t));}},Tablet:{getTablet:()=>({screenChanged:screen,fromQml:from,addButton:()=>({clicked:signal(),editProperties(){}}),loadQMLSource(){},sendToQml:m=>qml.push(m),gotoHomeScreen(){},removeButton(){}})}});
 messages.emit(channel,JSON.stringify({kind:'scope',epoch:1,active:true}),'',true);screen.emit('QML','file:///tmp/own/browser-audio.qml');from.emit({type:'browserCaptureChange',epoch:1,field:'noiseSuppression',value:false});assert.equal(sent.at(-1).epoch,1);screen.emit('Home','');messages.emit(channel,JSON.stringify({kind:'scope',epoch:2,active:false}),'',true);const count=sent.length;from.emit({type:'browserCaptureChange',epoch:1,field:'noiseSuppression',value:false});assert.equal(sent.length,count);screen.emit('QML','file:///tmp/own/browser-audio.qml');messages.emit(channel,JSON.stringify({kind:'scope',epoch:3,active:true}),'',true);from.emit({type:'browserCaptureChange',epoch:1,field:'noiseSuppression',value:false});assert.equal(sent.length,count+1);from.emit({type:'browserCaptureChange',epoch:3,field:'noiseSuppression',value:false});assert.equal(sent.at(-1).epoch,3);assert(qml.some(m=>m.type==='browserCaptureScope'&&m.epoch===3));
});
test('real generated QML change function keeps actual Browser tab and originating epoch ownership',()=>{
 const qml=buildBrowserCaptureUI(original,channel,'file:///tmp/own/browser-audio.qml').qml;const start=qml.indexOf(' function change('),end=qml.indexOf('\n ColumnLayout',start);const sent=[],ctx={tabs:{currentIndex:0},browserUiEpoch:7,browserReady:true,awaiting:false,applyingState:false,browserState:active(),sendToScript:m=>sent.push(m)};vm.runInNewContext(qml.slice(start,end)+';this.change=change;',ctx);ctx.change('noiseSuppression',false);assert.equal(sent.length,0);ctx.tabs.currentIndex=1;ctx.change('noiseSuppression',false);assert.equal(sent[0].epoch,7);assert.equal(ctx.awaiting,true);
});
test('queued intent is not applied when fresh readback withdraws control support',()=>{const f=native();f.instance.setAuthority(2,true);f.page();f.ack(active());f.time(1000);f.instance.poll();f.change('noiseSuppression',false);const s=active();s.controls.noiseSuppression=false;s.settings.noiseSuppression=null;f.ack(s);assert(!f.sent.some(m=>m.operation==='change'));assert.equal(f.local.at(-1).ready,true);assert.equal(f.local.at(-1).state.controls.noiseSuppression,false);});
test('epoch exhaustion never wraps or restores old local authority after reset',()=>{const messages=signal(),sent=[],local=[],ctx={Messages:{subscribe(){},unsubscribe(){},messageReceived:messages,sendLocalMessage(c,t){local.push(JSON.parse(t));}}};const nearLimit=helper.replace('epoch=0,queued=null','epoch=2147483646,queued=null');assert.notEqual(nearLimit,helper);vm.runInNewContext(nearLimit+';this.create=createBrowserCapture;',ctx);const f=ctx.create({channel,qmlURL:'own',current:()=>true,navigation:()=>1,now:()=>0,send:m=>sent.push(m)});f.setAuthority(2,true);f.screen('QML','own');assert.equal(sent.length,0);f.setAuthority(3,true);messages.emit(channel,JSON.stringify({kind:'ready',epoch:2147483647}),'',true);assert.equal(sent.length,0);assert(local.every(m=>m.epoch<=2147483647));});

test('cached periodic readback keeps usable control authority but queues only one intent',()=>{const f=native();f.instance.setAuthority(2,true);f.page();f.ack(active());f.time(1000);f.instance.poll();assert.equal(f.sent.at(-1).operation,'request');assert.equal(f.local.at(-1).ready,true);const before=f.sent.length;f.change('echoCancellation',false);assert.equal(f.sent.length,before);assert.equal(f.local.at(-1).ready,false);f.change('noiseSuppression',false);f.ack(active());assert.equal(f.sent.length,before+1);assert.equal(f.sent.at(-1).field,'echoCancellation');assert.equal(f.local.at(-1).ready,false);});
function extractedQml(source,name){const start=source.indexOf('function '+name+'(');assert(start>=0);let depth=0;for(let i=source.indexOf('{',start);i<source.length;i++){if(source[i]==='{')depth++;if(source[i]==='}'&&!--depth)return source.slice(start,i+1);}throw Error('unterminated original function');}
async function readbackQml(historical=false){const qml=historical?gunzipSync(await readFile(new URL('./fixtures/native-browser-capture-readback-before.qml.gz',import.meta.url)),{maxOutputLength:16384}).toString():buildBrowserCaptureUI(original,channel,'file:///tmp/own/browser-audio.qml').qml;let ready=true,restored=0;const transitions=[],ctx={browserUiEpoch:7,awaiting:false,applyingState:false,browserState:active(),browserReason:'ok',tabs:{currentIndex:1},sendToScript(){},restoreControls(){restored++;}};Object.defineProperty(ctx,'browserReady',{get:()=>ready,set:v=>{if(v!==ready)transitions.push(v);ready=v;}});vm.runInNewContext((historical?'':extractedQml(qml,'sameCaptureState'))+extractedQml(qml,'fromScript'),ctx);return{ctx,transitions,restored:()=>restored};}
test('unchanged ready readback preserves native enabled state and original checked binding',async()=>{const old=await readbackQml(true),now=await readbackQml();const message={type:'browserCaptureState',epoch:7,ready:true,state:active(),reason:'ok'};old.ctx.fromScript(message);now.ctx.fromScript(message);assert.deepEqual(old.transitions,[false,true]);assert.equal(old.restored(),1);assert.deepEqual(now.transitions,[]);assert.equal(now.restored(),0);assert.equal(now.ctx.browserReady,true);});
test('unchanged cached busy readback cannot cancel pressed control in candidate; historical counterexample disables',async()=>{const old=await readbackQml(true),now=await readbackQml();const message={type:'browserCaptureState',epoch:7,ready:true,state:active(),reason:'busy'};old.ctx.fromScript(message);now.ctx.fromScript(message);assert.equal(old.transitions[0],false);assert.equal(old.restored(),1);assert.equal(now.transitions.length,0);assert.equal(now.restored(),0);assert.equal(now.ctx.browserReason,'busy');});
test('authority scope, support withdrawal and pending change still immediately disable and restore',async()=>{for(const kind of ['scope','busyChange','support']){const f=await readbackQml();if(kind==='scope')f.ctx.fromScript({type:'browserCaptureScope',epoch:8,active:false});else{const state=active();if(kind==='support'){state.controls.echoCancellation=false;state.settings.echoCancellation=null;}f.ctx.fromScript({type:'browserCaptureState',epoch:7,ready:kind==='support',state,reason:'busy'});}if(kind==='support'){assert.equal(f.ctx.browserState.controls.echoCancellation,false);assert.equal(f.restored(),1);}else{assert.equal(f.ctx.browserReady,false);assert.equal(f.transitions[0],false);}}});
test('unchanged failed change restores user-broken binding even with live old settings',async()=>{for(const reason of ['apply-refused','readback-mismatch','rollback-refused']){const f=await readbackQml();f.ctx.awaiting=true;f.ctx.fromScript({type:'browserCaptureState',epoch:7,ready:true,state:active(),reason});assert.equal(f.restored(),1);assert.equal(f.ctx.awaiting,false);assert.equal(f.ctx.browserReason,reason);}});
test('periodic request still expires after original eight seconds and no late queued change escapes',()=>{const f=native();f.instance.setAuthority(2,true);f.page();f.ack(active());f.time(1000);f.instance.poll();f.change('echoCancellation',false);f.time(9000);f.instance.poll();assert.equal(f.local.at(-1).ready,false);assert.equal(f.local.at(-1).reason,'deadline');f.ack(active());assert(!f.sent.some(x=>x.operation==='change'));});
function callbackQml(){const qml=buildBrowserCaptureUI(original,channel,'file:///tmp/own/browser-audio.qml').qml,sent=[];let state=active();const ctx={browserUiEpoch:7,browserReady:true,awaiting:false,applyingState:false,browserReason:'ok',tabs:{currentIndex:1},sendToScript:m=>sent.push(m),Qt:{binding:fn=>fn}};for(const [name,field,property]of [['echoControl','echoCancellation','checked'],['noiseControl','noiseSuppression','checked'],['agcControl','autoGainControl','checked'],['gainControl','inputGainPercent','value']]){let value=state.settings[field];ctx[name]={};Object.defineProperty(ctx[name],property,{get:()=>value,set:v=>{const next=typeof v==='function'?v():v;if(next!==value){value=next;ctx.change(field,next);}}});}Object.defineProperty(ctx,'browserState',{get:()=>state,set:v=>{state=v;for(const [name,field,property]of [['echoControl','echoCancellation','checked'],['noiseControl','noiseSuppression','checked'],['agcControl','autoGainControl','checked'],['gainControl','inputGainPercent','value']])ctx[name][property]=state.settings[field];}});ctx.root=ctx;vm.runInNewContext(['sameCaptureState','restoreControls','fromScript','change'].map(n=>extractedQml(qml,n)).join('\n'),ctx);return{ctx,sent};}
test('real QML effective switch/gain bindings and refusal restoration do not echo changes',()=>{const f=callbackQml(),state=active();state.settings.echoCancellation=false;state.settings.inputGainPercent=110;state.settings.inputGain=1.1;f.ctx.fromScript({type:'browserCaptureState',epoch:7,ready:true,state,reason:'ok'});assert.equal(f.ctx.echoControl.checked,false);assert.equal(f.ctx.gainControl.value,110);assert.equal(f.sent.length,0);assert.equal(f.ctx.applyingState,false);f.ctx.echoControl.checked=true;assert.equal(f.sent.length,1);assert.equal(f.ctx.awaiting,true);f.ctx.fromScript({type:'browserCaptureState',epoch:7,ready:true,state,reason:'apply-refused'});assert.equal(f.ctx.echoControl.checked,false);assert.equal(f.sent.length,1);assert.equal(f.ctx.awaiting,false);assert.equal(f.ctx.applyingState,false);});
test('programmatic state guard refuses callbacks while genuine current physical changes remain allowed',()=>{const f=callbackQml();f.ctx.applyingState=true;f.ctx.change('echoCancellation',false);f.ctx.change('inputGainPercent',110);assert.equal(f.sent.length,0);f.ctx.applyingState=false;f.ctx.change('echoCancellation',false);assert.equal(f.sent.length,1);});
test('capture ended, close epoch, stale epoch and pending CHANGE cannot forward binding callbacks',()=>{for(const mode of ['ended','scope','stale','change']){const f=callbackQml();if(mode==='ended')f.ctx.fromScript({type:'browserCaptureState',epoch:7,ready:true,state:inactiveCapture(),reason:'inactive'});if(mode==='scope')f.ctx.fromScript({type:'browserCaptureScope',epoch:8,active:false});if(mode==='stale'){f.ctx.browserReady=false;f.ctx.fromScript({type:'browserCaptureState',epoch:6,ready:true,state:active(),reason:'ok'});}if(mode==='change')f.ctx.fromScript({type:'browserCaptureState',epoch:7,ready:false,state:active(),reason:'busy'});f.ctx.change('echoCancellation',false);assert.equal(f.sent.length,0);assert.equal(f.ctx.applyingState,false);}});
test('state application exception releases guard without publishing user intent',()=>{const f=callbackQml();f.ctx.restoreControls=()=>{throw Error('authored binding failure');};assert.throws(()=>f.ctx.fromScript({type:'browserCaptureState',epoch:7,ready:false,state:active(),reason:'busy'}),/authored binding failure/);assert.equal(f.ctx.applyingState,false);assert.equal(f.ctx.browserReady,false);assert.equal(f.sent.length,0);});
