// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import {TabletSession,validateTabletInput} from './tablet.mjs';import {inactiveCapture} from '../shared/browser-capture.mjs';
const packet=(requestId=1,extra={})=>({type:'tablet',kind:'capture',revision:2,navigationSequence:1,schemaVersion:1,requestId,operation:'request',...extra});
function fixture(){let revision=2,approved=true;const browser=[],native=[];const session=new TabletSession({framePath:'/unused',sendNative:v=>native.push(v),sendBrowser:v=>browser.push(v),isActive:()=>approved,getRevision:()=>revision});session.receive({type:'tablet',action:'open',sequence:1});return{session,browser,native,revision(v){revision=v;},approved(v){approved=v;}};}
const result=(id=1,extra={})=>({type:'tablet',action:'captureResult',sequence:2,revision:2,navigationSequence:1,schemaVersion:1,requestId:id,accepted:true,reason:'ok',state:inactiveCapture(),...extra});
test('actual TabletSession delivers only current native capture DTO and forwards exact pending confirmation',async()=>{const f=fixture();await f.session.receiveNative(packet(1,{privateDevice:'not exposed'}));assert.deepEqual(f.browser,[packet()]);f.session.receive(result(1,{privateDevice:'not exposed'}));assert(!JSON.stringify(f.native).includes('not exposed'));assert.equal(f.native.at(-1).action,'captureResult');assert.equal(f.native.at(-1).navigationSequence,1);f.session.close();});
test('actual capture ingress rejects unsupported settings/device details and mismatched nested effective state',async()=>{const f=fixture();await assert.rejects(f.session.receiveNative(packet(1,{operation:'change',field:'deviceId',value:'private'})));const invalid=inactiveCapture();invalid.settings.deviceId='private';assert.throws(()=>validateTabletInput(result(1,{state:invalid})));const wrong=inactiveCapture();wrong.active=true;wrong.controls.noiseSuppression=true;assert.throws(()=>validateTabletInput(result(1,{state:wrong})));f.session.close();});
test('native revisions/navigation/approval and monotonic request ids gate every capture request',async()=>{const f=fixture();await f.session.receiveNative(packet(1,{revision:1}));await f.session.receiveNative(packet(1,{navigationSequence:9}));assert.equal(f.browser.length,0);await f.session.receiveNative(packet());await f.session.receiveNative(packet());assert.equal(f.browser.length,1);f.approved(false);await f.session.receiveNative(packet(2));assert.equal(f.browser.length,1);f.session.close();});
test('actual Home navigation discards previous DSP confirmations and admits only fresh bounded navigation',async()=>{const f=fixture();await f.session.receiveNative(packet());f.session.receive({type:'tablet',action:'home',sequence:2,revision:2});const count=f.native.length;f.session.receive(result(1,{sequence:3}));assert.equal(f.native.length,count);await f.session.receiveNative(packet(2));assert.equal(f.browser.length,1);await f.session.receiveNative(packet(2,{navigationSequence:2}));f.session.receive(result(2,{navigationSequence:2,sequence:4}));assert.equal(f.native.at(-1).requestId,2);f.session.close();});
test('actual revision/reset/end prevent late DSP confirmations from reaching a replacement native worker',async()=>{const f=fixture();await f.session.receiveNative(packet());f.revision(3);assert.throws(()=>f.session.receive(result()));await f.session.receiveNative(packet());assert.equal(f.browser.length,1);f.session.close();await f.session.receiveNative(packet(2,{revision:3}));assert.equal(f.browser.length,1);});
test('current authenticated native page cancellation is a strict ordered DTO, not a new microphone right',async()=>{const f=fixture();await f.session.receiveNative(packet());await f.session.receiveNative(packet(2,{operation:'cancel'}));assert.equal(f.browser.at(-1).operation,'cancel');assert.equal(f.session.captureRequest,2);assert.throws(()=>validateTabletInput(result(2,{navigationSequence:0})));f.session.close();});

test('current Graphics intent and microphone requests keep independent correlation; neither clears the other pending owner',async()=>{
 const f=fixture();const settings={version:1,fieldOfView:70,resolutionPercent:100,localLights:true,cameraClipping:true};
 try{f.session.receive({type:'tablet',action:'graphicsChange',schemaVersion:1,browserRequestId:1,field:'resolutionPercent',value:80,sequence:2,revision:2});
 await f.session.receiveNative({type:'tablet',kind:'graphics',revision:2,schemaVersion:1,requestId:1,browserRequestId:1,operation:'change',field:'resolutionPercent',value:80});
 await f.session.receiveNative(packet());assert.equal(f.session.graphicsRequest,1);assert.equal(f.session.captureRequest,1);
 f.session.receive(result(1,{sequence:3}));assert.equal(f.session.captureRequest,0);assert.equal(f.session.graphicsRequest,1);assert.equal(f.session.graphicsLocalRequest,1);
 f.session.receive({type:'tablet',action:'graphicsResult',revision:2,sequence:4,schemaVersion:1,requestId:1,accepted:true,settings});assert.equal(f.session.graphicsRequest,0);
 await f.session.receiveNative({type:'tablet',kind:'graphicsApplied',revision:2,schemaVersion:1,browserRequestId:1,accepted:true,settings});assert.equal(f.session.graphicsLocalRequest,0);assert.equal(f.browser.at(-1).kind,'graphicsApplied');
 }finally{f.session.close();}
});
