// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,symlink,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import vm from 'node:vm';import {sandboxCommand} from './worker-sandbox.mjs';
const signal=()=>({callbacks:new Set(),connect(f){this.callbacks.add(f);},disconnect(f){this.callbacks.delete(f);},emit(...a){for(const f of [...this.callbacks])f(...a);}});
const tabletSource=await readFile(new URL('./native-tablet.js',import.meta.url),'utf8'),captureSource=await readFile(new URL('./native-browser-capture.js',import.meta.url),'utf8');
test('actual worker command admits only exact canonical own Audio script to installed Audio target with read-only bind',async()=>{const base=await mkdtemp(path.join(tmpdir(),'overte-audio-bind-'));try{const own=path.join(base,'own'),installed=path.join(base,'installed'),target=path.join(installed,'scripts/system/audio.js'),source=path.join(own,'browser-audio.js');await mkdir(own);await mkdir(path.dirname(target),{recursive:true});await writeFile(target,'installed original');await writeFile(source,'prepared own adapter');const args={directory:own,executable:process.execPath,env:{},roots:[installed]},override={source,target};const command=await sandboxCommand({...args,readOnlyOverrides:[override]});const index=command.args.indexOf(source);assert.equal(command.args[index-1],'--ro-bind');assert.equal(command.args[index+1],target);assert.equal(await readFile(target,'utf8'),'installed original');const sibling=path.join(base,'sibling');await mkdir(sibling);await writeFile(path.join(sibling,'browser-audio.js'),'another visitor');await assert.rejects(sandboxCommand({...args,readOnlyOverrides:[{...override,source:path.join(sibling,'browser-audio.js')}]}));await assert.rejects(sandboxCommand({...args,readOnlyOverrides:[{...override,target:path.join(installed,'scripts/system/snapshot.js')}]}));const parentAlias=path.join(base,'alias');await symlink(installed,parentAlias);await assert.rejects(sandboxCommand({...args,roots:[parentAlias],readOnlyOverrides:[{source,target:path.join(parentAlias,'scripts/system/audio.js')}]}),/canonical/);await rm(source);await symlink(target,source);await assert.rejects(sandboxCommand({...args,readOnlyOverrides:[override]}),/regular/);}finally{await rm(base,{recursive:true,force:true});}});
function native(){const messages=signal(),qml=signal(),screen=signal(),ending=signal(),sent=[],local=[],timers=[];const helper={sendToQml(){},fromQml:qml,close(){}},tablet={screenChanged:screen,loadQMLSource(){},returnToPreviousApp(){}};const channel='overte.browser.capture.'+'1'.repeat(32),ctx={Tablet:{getTablet:()=>tablet},OverlayWindow:function(){return helper;},Audio:{muted:true,mutedChanged:signal()},Settings:{getValue:()=>true,setValue(){}},Script:{include(){vm.runInContext(captureSource,ctx);},load(){},setInterval(fn){timers.push(fn);return timers.length;},clearInterval(){},setTimeout(){},scriptEnding:ending},Messages:{subscribe(){},unsubscribe(){},messageReceived:messages,sendLocalMessage(c,t){local.push(JSON.parse(t));}}};vm.createContext(ctx);vm.runInContext(tabletSource,ctx);const factory=ctx.createBrowserTablet({capture:{channel,qmlURL:'file:///owned/browser-audio.qml',scriptURL:'file:///owned/helper.js'},qmlURL:'file:///owned/capture.qml',defaultScriptsURL:'file:///installed/defaultScripts.js',framePath:'/owned/frame',send:m=>sent.push(m)});return{factory,channel,sent,local,tick:()=>timers[0](),page:active=>screen.emit(active?'QML':'Home',active?'file:///owned/browser-audio.qml':'')};}
test('actual native Tablet queues capture on its existing engine flush and drops old navigation before send',()=>{const f=native();f.factory.setAuthority(2,true);f.factory.receive({action:'open',revision:2,navigationSequence:1});f.page(true);assert.equal(f.sent.length,0);f.factory.receive({action:'home',revision:2,navigationSequence:2});f.tick();assert(!f.sent.some(v=>v.kind==='capture'));f.page(true);f.tick();assert(f.sent.some(v=>v.kind==='capture'&&v.navigationSequence===2&&v.revision===2));f.factory.close();assert.equal(f.local.filter(m=>m.kind==='effective').at(-1).ready,false);});
test('actual native Tablet authority and close suppress already queued capture records',()=>{for(const action of ['revoke','close']){const f=native();f.factory.setAuthority(2,true);f.factory.receive({action:'open',revision:2,navigationSequence:1});f.page(true);if(action==='revoke')f.factory.setAuthority(3,false);else f.factory.close();f.tick();assert(!f.sent.some(v=>v.kind==='capture'));}});
