// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Actual source functions; finite mocks only, no network/browser/native process.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {EventEmitter} from 'node:events';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {attachNativeAvatarProjection} from './native-avatar-stdout-projection.mjs';
import {AvatarSnapshotSender} from './avatar-snapshot-sender.mjs';
const read=path=>readFileSync(new URL(path,import.meta.url),'utf8');
const bridge=read('./native-bridge.js'),server=read('./server.mjs'),core=read('../tests/integration/real-session.mjs');
function section(text,start,end){assert.equal(text.split(start).length,2);assert.equal(text.split(end).length,2);return text.slice(text.indexOf(start),text.indexOf(end));}
const outputSource=section(bridge,'    function utf8Size(text) {','    function clearOutput() {');
const samplerSource=read('./native-avatar-sample-diagnostics.js');
const captureSource=section(read('../tests/integration/native-peer-diagnostic.mjs'),'export function captureNativePeerSnapshot(','\nconst MAX_TAIL_BYTES').replace('export function','function');
const initSource=section(core,'    await page.addInitScript(avatarDeliveryEnabled => {','    const join = async () => {');
const sendSource=section(server,'const send = (socket, value, observe) => {','const cookie = ');
const target={x:4,y:1.8,z:2},old={x:3,y:1.8,z:1};
const envelope=position=>({type:'avatars',avatars:[{id:'11111111-1111-1111-1111-111111111111',displayName:'Native-Lab-Participant',position:{...position}}],selfId:'self'});
function native(enabled=true){let authority='a';const wire=[];const c={JSON,Math,Date,isFinite,outbound:[],outboundBytes:0,outputFailed:false,pushToTalk:{setAuthority(){}},Audio:{},worldStream:{stop(){}},permissionRevision:1,outputAuthority:()=>authority,active:true,permissionsApproved:true,lastConnected:true,location:{isConnected:true},socket:{readyState:1,send:t=>wire.push(t)},avatarDelivery:enabled?{queued:0,writeInvoked:0,refused:0,lastAdmission:'none',censored:false}:null};vm.createContext(c);vm.runInContext(outputSource,c);return {c,wire,authority:v=>authority=v};}
function gateway(enabled='1',publicPlace=false){const logs=[],writes=[];const session={publicPlace,lastNativeMessage:1000};const c={WebSocket:{OPEN:1},Number,Math,JSON,process:{env:{OVERTE_GATEWAY_AVATAR_SAMPLE_DIAGNOSTICS:enabled},stdout:{write:t=>logs.push(JSON.parse(t.slice('BROWSER_AVATAR_SAMPLE '.length)))}}};vm.createContext(c);vm.runInContext(sendSource+'\nglobalThis.send=send;',c);const socket={readyState:1,bufferedAmount:0,send:t=>writes.push(t)};return {c,session,socket,get logs(){return session.avatarDelivery?.snapshot?[session.avatarDelivery.snapshot]:[];},writes,forward:value=>c.send(socket,value,(...args)=>c.observeAvatarForward(session,value,...args))};}
function projected(value){const child=new EventEmitter();child.stdout=new EventEmitter();const rows=[];attachNativeAvatarProjection(child,{enabled:true,publicPlace:false,emit:t=>rows.push(JSON.parse(t.slice('BROWSER_AVATAR_SAMPLE '.length)))});child.stdout.emit('data',Buffer.from('BROWSER_AVATAR_SAMPLE '+JSON.stringify(value)+'\n'));child.emit('close');return rows;}
function sample(record){return {version:1,kind:'sample',at:1000,sequence:1,role:'fixture-peer',batchMs:0,publishedPoseAgeMs:0,avatarBuildMs:0,jointNamesMs:null,jointRotationsMs:null,jointTranslationsMs:null,postPublicationPoseDeltaMeters:null,postPublicationProbeMs:null,peerPacketRateHz:null,peerGlobalPositionUpdateRateHz:null,peerSimulationRateHz:null,capturedFixtureTargetDistanceMeters:0,nativeDelivery:record,gatewayDelivery:null,interstitialState:'unknown',interstitialSignalAgeMs:null};}
async function browser(enabled=true){class Socket{constructor(){this.readyState=0;this.listeners={};}addEventListener(k,fn){this.listeners[k]=fn;}send(){}receive(value){this.listeners.message({data:JSON.stringify(value)});}}const c={window:{WebSocket:Socket},performance:{now:()=>100},Date,ArrayBuffer,Int16Array,WeakMap,JSON,Math,Number,process:{env:{OVERTE_LAB_AVATAR_SAMPLE_DIAGNOSTICS:enabled?'1':''}}};vm.createContext(c);c.page={addInitScript:(fn,arg)=>fn(arg)};await vm.runInContext('(async()=>{'+initSource+'})()',c);vm.runInContext(captureSource,c);return {c,create:()=>new c.window.WebSocket(),capture:()=>c.captureNativePeerSnapshot({fixtureName:'Native-Lab-Participant',target})};}

test('native exact send/flush reports queue and write invocation, never write acceptance',()=>{const n=native();n.c.send(envelope(target));assert.equal(n.c.avatarDeliverySnapshot().lastAdmission,'queued');n.c.flush();const d=n.c.avatarDeliverySnapshot();assert.equal(d.queued,1);assert.equal(d.writeInvoked,1);assert.equal(d.writeReturnAccepted,null);assert.equal(n.wire.length,1);assert.deepEqual(JSON.parse(n.wire[0]),envelope(target));assert.equal(projected(sample(d)).length,1);});
test('native closed and failed admission has no write witness',()=>{for(const field of ['readyState','outputFailed']){const n=native();if(field==='readyState')n.c.socket.readyState=0;else n.c.outputFailed=true;n.c.send(envelope(target));n.c.flush();assert.equal(n.wire.filter(t=>JSON.parse(t).type==='avatars').length,0);assert.equal(n.c.avatarDelivery.refused,1);assert.equal(n.c.avatarDelivery.writeInvoked,0);}});
test('native queued then socket close, authority change or revocation remains refused',()=>{for(const reason of ['socket','authority','revision','approval']){const n=native();n.c.send(envelope(target));if(reason==='socket')n.c.socket.readyState=3;if(reason==='authority')n.authority('b');if(reason==='revision')n.c.permissionRevision++;if(reason==='approval')n.c.permissionsApproved=false;n.c.flush();assert.equal(n.wire.length,0);assert.equal(n.c.avatarDelivery.refused,1);assert.equal(n.c.avatarDelivery.writeInvoked,0);}});
test('native coalescing preserves latest complete JSON and bounded counters',()=>{const n=native();n.c.send(envelope(old));n.c.send(envelope(target));n.c.avatarDelivery.queued=65535;n.c.send(envelope(target));n.c.flush();assert.equal(n.wire.length,1);assert.deepEqual(JSON.parse(n.wire[0]),envelope(target));assert.equal(n.c.avatarDelivery.queued,65535);assert.equal(n.c.avatarDelivery.censored,true);});
test('native automatic off adds no type reads on closed admission and no diagnostic record',()=>{const n=native(false);n.c.socket.readyState=0;const value={get type(){throw Error('unexpected new getter');}};n.c.send(value);assert.equal(n.c.avatarDeliverySnapshot(),null);});
test('sampler real producer captures branch witness beside copied target, not delivery claim',()=>{const n=native(),logs=[],c={JSON,Math,isFinite,config:{now:()=>1000,current:()=>true,authority:()=> 'a',mode:'passive',print:t=>logs.push(JSON.parse(t.slice('BROWSER_AVATAR_SAMPLE '.length))),delivery:()=>n.c.avatarDeliverySnapshot()}};vm.createContext(c);vm.runInContext(samplerSource+'\nvar d=createNativeAvatarSampleDiagnostics(config);',c);c.d.beginBatch();const row=c.d.beginAvatar();c.d.poseSampled(row);const dto=envelope(target).avatars[0];c.d.completed(row,dto,false,{});n.c.socket.readyState=0;n.c.send(envelope(target));n.c.flush();c.d.published();assert.equal(logs[0].capturedFixtureTargetDistanceMeters,0);assert.equal(logs[0].nativeDelivery.writeInvoked,0);assert.equal(logs[0].nativeDelivery.lastAdmission,'not-admitted');assert.equal(projected(logs[0]).length,1);c.d.stop();c.d.beginBatch();c.d.published();assert.equal(logs.length,1);});
test('gateway actual accepted/drop4MiB branch captures existing reads once and preserves payload',()=>{for(const bytes of [0,4*1024*1024]){const g=gateway(),reads=[];Object.defineProperty(g.socket,'readyState',{get(){reads.push('ready');return 1;}});Object.defineProperty(g.socket,'bufferedAmount',{get(){reads.push('buffer');return bytes;}});g.forward(envelope(target));assert.deepEqual(reads,['ready','buffer']);assert.equal(g.writes.length,bytes===0?1:0);assert.equal(g.logs[0].writeInvoked,bytes===0);assert.equal(g.logs[0].writeReturnAccepted,null);assert.equal(g.logs[0].capturedFixtureTargetDistanceMeters,0);assert.equal(projected({...sample(null),gatewayDelivery:g.logs[0]}).length,1);if(g.writes.length)assert.deepEqual(JSON.parse(g.writes[0]),envelope(target));}});
test('gateway closed branch does not read buffer; exceptions preserve original refusal',()=>{const g=gateway();g.socket.readyState=3;Object.defineProperty(g.socket,'bufferedAmount',{get(){throw Error('must not read');}});g.forward(envelope(target));assert.equal(g.logs[0].socketOpen,false);assert.equal(g.logs[0].bufferedBytes,null);assert.equal(g.logs[0].writeInvoked,false);const thrown=gateway();thrown.socket.send=()=>{throw Error('original write failed');};assert.throws(()=>thrown.forward(envelope(target)),/original write failed/);assert.equal(thrown.logs.length,0);});
test('gateway disabled/public opt-out emits no rows and per-session lifetime state is isolated',()=>{for(const args of [['',false],['unknown',false],['1',true]]){const g=gateway(...args);g.forward(envelope(target));assert.equal(g.logs.length,0);assert.equal(g.session.avatarDelivery,undefined);assert.equal(g.writes.length,1);}const a=gateway(),b=gateway();a.forward(envelope(target));a.session.lastNativeMessage+=500;a.forward(envelope(old));b.forward(envelope(target));assert.equal(a.logs[0].sequence,2);assert.equal(b.logs[0].sequence,1);});
test('gateway reuses existing timestamp, bounded128 with clock backstep throttle and no new clock',()=>{const g=gateway();for(let i=0;i<130;i++){g.session.lastNativeMessage=1000+i*500;g.forward(envelope(target));}assert.equal(g.logs[0].sequence,128);assert.equal(g.logs[0].observationCensored,true);assert.equal(g.writes.length,130);const h=gateway();h.forward(envelope(target));h.session.lastNativeMessage=0;h.forward(envelope(target));assert.equal(h.logs.length,1);h.session.lastNativeMessage=1500;h.forward(envelope(target));assert.equal(h.logs[0].sequence,2);});
test('gateway projection refuses ambiguity/oversize pose instead of selecting a private peer',()=>{const g=gateway(),v=envelope(target);v.avatars.push({...v.avatars[0],id:'different'});g.forward(v);assert.equal(g.logs[0].fixtureNameMatches,2);assert.equal(g.logs[0].capturedFixtureTargetDistanceMeters,null);const h=gateway(),many=envelope(target);many.avatars.push(...Array.from({length:32},()=>({})));h.forward(many);assert.equal(h.logs[0].avatarProjectionCensored,true);assert.equal(h.logs[0].capturedFixtureTargetDistanceMeters,null);});
test('strict production projector refuses old/malformed/unknown/private/counter claims',()=>{const n=native(),good=sample(n.c.avatarDeliverySnapshot());assert.equal(projected(good).length,1);for(const mutate of [v=>delete v.nativeDelivery,v=>v.nativeDelivery.extra='private',v=>v.nativeDelivery.writeReturnAccepted=true,v=>v.nativeDelivery.queued=-1,v=>v.nativeDelivery.queued=65536,v=>v.nativeDelivery.queued=true,v=>v.nativeDelivery.lastAdmission='secret',v=>v.extra='private']){const v=structuredClone(good);mutate(v);assert.equal(projected(v).length,0);}const g=gateway();g.forward(envelope(target));for(const mutate of [v=>v.sequence=129,v=>v.bufferedBytes=64*1024*1024+1,v=>v.writeReturnAccepted=true,v=>v.extra='private',v=>v.socketOpen=1,v=>{v.socketOpen=false;v.writeInvoked=true;},v=>{v.fixtureNameMatches=2;v.capturedFixtureTargetDistanceMeters=0;},v=>v.observationCensored=true]){const v=structuredClone(g.logs[0]);mutate(v);assert.equal(projected({...sample(null),gatewayDelivery:v}).length,0);}});
test('Core actual opt-in distinguishes current open snapshot from late older socket, preserving selection',async()=>{const b=await browser(),a=b.create(),c=b.create();c.readyState=1;c.receive(envelope(target));let d=b.capture();assert.equal(d.diagnostic.socketSelection.selectedSocketOrdinal,2);assert.equal(d.diagnostic.socketSelection.selectedIsLatest,true);assert.equal(d.diagnostic.socketSelection.latestReadyState,'open');a.readyState=3;a.receive(envelope(old));d=b.capture();assert.equal(d.diagnostic.socketSelection.selectedSocketOrdinal,1);assert.equal(d.diagnostic.socketSelection.selectedIsLatest,false);assert.equal(d.diagnostic.socketSelection.selectedReadyState,'closed');assert.ok(Math.abs(d.diagnostic.peers[0].targetDistance-Math.SQRT2)<1e-12);});
test('Core default off retains exact old diagnostic keys and does not read socket states',async()=>{const b=await browser(false),s=b.create();Object.defineProperty(s,'readyState',{get(){throw Error('new off getter');}});s.receive(envelope(target));const d=b.capture().diagnostic;assert.equal(b.c.window.__labAudio.delivery,undefined);assert.deepEqual(Object.keys(d).sort(),['snapshotPresent','snapshotAgeMs','avatarCount','peerCount','fixtureNameMatchCount','peerProjectionTruncated','peers'].sort());});
test('Core socket ordinals cap32/null and new observer lifetime resets independently',async()=>{const b=await browser();for(let i=0;i<33;i++)b.create().receive(envelope(target));const d=b.capture().diagnostic.socketSelection;assert.equal(d.ordinalCensored,true);assert.equal(d.selectedSocketOrdinal,null);assert.equal(d.latestCreatedSocketOrdinal,null);const next=await browser();next.create().receive(envelope(target));assert.equal(next.capture().diagnostic.socketSelection.selectedSocketOrdinal,1);});
test('real curator accepts fixed socket selection and refuses unknown/private fields without reflection',()=>{const module=fileURLToPath(new URL('../lab/curate-core-journey.py',import.meta.url));const script=`import importlib.util,json,sys\ns=importlib.util.spec_from_file_location('curator',sys.argv[1]);m=importlib.util.module_from_spec(s);s.loader.exec_module(m)\nv=json.loads(sys.stdin.read());print(json.dumps(m.peer_diagnostic(v)))\n`;const selection={selectedSocketOrdinal:1,latestCreatedSocketOrdinal:2,selectedIsLatest:false,selectedReadyState:'closed',latestReadyState:'open',ordinalCensored:false};const run=v=>{const p=spawnSync('python3',['-B','-c',script,module],{input:JSON.stringify({browser:{socketSelection:v}}),encoding:'utf8',timeout:5000,maxBuffer:65536});assert.equal(p.status,0);return JSON.parse(p.stdout);};assert.deepEqual(run(selection).browser.socketSelection,selection);for(const mutate of [v=>v.secret='private',v=>v.selectedSocketOrdinal=33,v=>v.selectedIsLatest='private',v=>v.selectedReadyState='private',v=>v.ordinalCensored=1]){const v=structuredClone(selection);mutate(v);const result=run(v);assert.equal(result.browser.socketSelection,undefined);assert.ok(!JSON.stringify(result).includes('private'));}});
test('actual gateway native callback uses observer only after token/permission/session admission',async()=>{const g=gateway(),callbacks={},nativeHandlers={},session=g.session;Object.assign(session,{id:'owned',token:'fixed',permissionsApproved:true,permissionRevision:1,connected:true,closed:false,waitForDomain(){},browser:g.socket});session.isCurrent=()=>true;session.avatarSender=new AvatarSnapshotSender(g.socket,()=>session,value=>g.c.observeAvatarForward(session,JSON.parse(value.text),value.open,value.bytes,value.writeInvoked,value.at));const native={on:(k,fn)=>nativeHandlers[k]=fn,send(){},close(){}};Object.assign(g.c,{sockets:new Set(),sessions:new Map([['owned',session]]),equal:(a,b)=>a===b,NativeHeartbeat:class{receive(){}},setTimeout:()=>1,clearTimeout(){},Date,Buffer,nativeServer:{on:(k,fn)=>callbacks[k]=fn}});vm.runInContext(section(server,"nativeServer.on('connection', native => {",'const heartbeat = setInterval('),g.c);callbacks.connection(native);const receive=m=>nativeHandlers.message(Buffer.from(JSON.stringify(m)));await receive({type:'nativeHello',token:'fixed'});await receive(envelope(target));assert.equal(session.avatarDelivery.sequence,1);assert.equal(session.avatarDelivery.snapshot.writeInvoked,true);session.permissionsApproved=false;await receive(envelope(old));assert.equal(session.avatarDelivery.sequence,1);session.permissionsApproved=true;session.closed=true;await receive(envelope(old));assert.equal(session.avatarDelivery.sequence,1);});
test('real native projector → existing gateway emit → same strict collector retains all512 rows',()=>{const g=gateway();g.forward(envelope(target));const output=[];g.c.process.stdout.write=t=>output.push(t);const child=new EventEmitter();child.stdout=new EventEmitter();attachNativeAvatarProjection(child,{enabled:true,publicPlace:false,emit:line=>g.c.emitAvatarProjection(g.session,line)});const value=sample(null);for(let i=0;i<513;i++)child.stdout.emit('data',Buffer.from('BROWSER_AVATAR_SAMPLE '+JSON.stringify({...value,sequence:Math.min(i+1,512)})+'\n'));assert.equal(output.length,512);assert.equal(child.stdout.listenerCount('data'),0);const projectedRows=output.flatMap(line=>projected(JSON.parse(line.slice('BROWSER_AVATAR_SAMPLE '.length))));assert.equal(projectedRows.length,512);assert.equal(projectedRows[0].gatewayDelivery.capturedFixtureTargetDistanceMeters,0);assert.equal(projectedRows[0].nativeDelivery,null);assert.ok(output.every(t=>!t.includes('11111111')&&!t.includes('Native-Lab-Participant')));});
test('known finite gateway branch claim must equal the actual source send condition in both directions',()=>{
 for(const bytes of [0,4*1024*1024]){
  const g=gateway();g.socket.bufferedAmount=bytes;g.forward(envelope(target));
  const dto={...sample(null),gatewayDelivery:structuredClone(g.logs[0])};
  assert.equal(projected(dto).length,1);dto.gatewayDelivery.writeInvoked=!dto.gatewayDelivery.writeInvoked;
  assert.equal(projected(dto).length,0);
 }
});
