// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import{readFile}from'node:fs/promises';
const qml=await readFile(new URL('../native-input/application-key-web/key-fixture.qml',import.meta.url),'utf8');
function method(name){const start=qml.indexOf(' function '+name+'(');assert(start>=0);let p=qml.indexOf('{',start)+1,depth=1,quote='',escape=false;for(;depth&&p<qml.length;p++){const c=qml[p];if(quote){if(escape)escape=false;else if(c==='\\')escape=true;else if(c===quote)quote='';}else if(c==='"'||c==="'")quote=c;else if(c==='{')depth++;else if(c==='}')depth--;}assert.equal(depth,0);return qml.slice(start,p);}
function installed(current={qml:false,editable:true}){const rows=[];const before={filterPresses:0,filterReleases:0,applicationPresses:0,applicationReleases:0,consumedKeys:0};const now={filterPresses:1,filterReleases:1,applicationPresses:0,applicationReleases:0,consumedKeys:0};const context={current,before,accepted:true,quiet:0,stats:()=>now,probe:{restart(){}},finishCase:(...args)=>rows.push(args)};vm.createContext(context);vm.runInContext(method('delta')+'\n'+method('verify'),context);return{context,now,rows};}
const trusted=()=>({down:1,up:1,input:1,untrusted:0,length:5,xCount:1});
test('actual QML oracle requires five quiet checks and once native press/release with zero protected global delivery',()=>{const h=installed();for(let i=0;i<4;i++)h.context.verify(trusted(),true);assert.equal(h.rows.length,0);h.context.verify(trusted(),true);assert.equal(h.rows.length,1);assert.equal(h.rows[0][0],true);});
for(const field of ['filterPresses','filterReleases','applicationPresses','applicationReleases','consumedKeys'])test('extra/missing route evidence cannot pass '+field,()=>{const h=installed();h.now[field]=field.startsWith('filter')?2:1;for(let i=0;i<8;i++)h.context.verify(trusted(),true);assert.equal(h.rows.length,0);});
for(const [field,value]of [['down',2],['up',0],['untrusted',1]])test('trusted DOM native event oracle refuses '+field,()=>{const h=installed();for(let i=0;i<8;i++)h.context.verify({...trusted(),[field]:value},true);assert.equal(h.rows.length,0);});
test('noneditable fallback requires original one global pair, not swallowed or duplicate input',()=>{const h=installed({qml:false,global:true,editable:false});for(let i=0;i<8;i++)h.context.verify({...trusted(),input:0},true);assert.equal(h.rows.length,0);h.now.applicationPresses=1;h.now.applicationReleases=1;for(let i=0;i<5;i++)h.context.verify({...trusted(),input:0},true);assert.equal(h.rows.length,1);});
test('QML has no fabricated DOM counters and still requires real routing/value gates',()=>{const h=installed({qml:true});for(let i=0;i<5;i++)h.context.verify({down:-1,up:-1,untrusted:-1},false);assert.equal(h.rows.length,0);for(let i=0;i<5;i++)h.context.verify({down:-1,up:-1,untrusted:-1},true);assert.equal(h.rows.length,1);assert(qml.includes('down:-1,up:-1,untrusted:-1'));});
test('rejected actual NativeInput return cannot pass regardless of GUI value or counters',()=>{const h=installed();h.context.accepted=false;for(let i=0;i<8;i++)h.context.verify(trusted(),true);assert.equal(h.rows.length,0);});
test('readonly/disabled original value cannot pass a spurious trusted input event',()=>{const h=installed({qml:false,editable:false});for(let i=0;i<8;i++)h.context.verify({...trusted(),input:1},true);assert.equal(h.rows.length,0);for(let i=0;i<5;i++)h.context.verify({...trusted(),input:0},true);assert.equal(h.rows.length,1);});
test('late duplicate before quiet window completion resets acceptance rather than approving early',()=>{const h=installed();for(let i=0;i<4;i++)h.context.verify(trusted(),true);h.now.filterPresses=2;h.context.verify(trusted(),true);assert.equal(h.context.quiet,0);assert.equal(h.rows.length,0);});

test('disabled and noneditable actual body-focus cases require the same original global pair while readonly stays protected',()=>{
 const source=qml.match(/property var cases:\[([\s\S]*?)\n \]/);assert(source);
 const cases=vm.runInNewContext('['+source[1]+']');
 for(const kind of ['web-disabled','web-noneditable']){const entry=cases.find(r=>r.kind===kind);assert(entry.body&&entry.global);assert.equal(entry.editable,false);const h=installed(entry);const state={...trusted(),input:0};for(let i=0;i<8;i++)h.context.verify(state,true);assert.equal(h.rows.length,0);h.now.applicationPresses=1;h.now.applicationReleases=1;for(let i=0;i<5;i++)h.context.verify(state,true);assert.equal(h.rows.length,1);}
 const entry=cases.find(r=>r.kind==='web-readonly');assert(!entry.body&&!entry.global);const h=installed(entry);for(let i=0;i<5;i++)h.context.verify({...trusted(),input:0},true);assert.equal(h.rows.length,1);const bad=installed(entry);bad.now.applicationPresses=1;bad.now.applicationReleases=1;for(let i=0;i<8;i++)bad.context.verify({...trusted(),input:0},true);assert.equal(bad.rows.length,0);
});
