// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Executes actual production Session and HTTP callback. No sockets/listeners.
import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {randomBytes,randomUUID} from 'node:crypto';import {EventEmitter} from 'node:events';import vm from 'node:vm';import {SessionAssets} from './session-assets.mjs';import {PushToTalkSession} from './push-to-talk.mjs';import {SharedTeardown} from './process-lifecycle.mjs';import {approvedAssetAddress,ASSET_SANDBOX_POLICY} from './validation.mjs';
async function fixture(){const source=await readFile(new URL('./server.mjs',import.meta.url),'utf8'),a=source.indexOf('class Session extends SharedTeardown {'),z=source.indexOf('\nconst server = http.createServer',a),end=source.indexOf('// Allowed clipboard quotation',z);assert(a>=0&&z>a&&end>z);const sessions=new Map(),origins=new Set(['https://assets.example']);let loads=0;const targets=[];const context={SharedTeardown,randomBytes,randomUUID,SessionAssets,PushToTalkSession,approvedAssetAddress,downloadAsset:async(url)=>{loads++;targets.push(url);return{data:Buffer.from('PNG-authored-CPU'),type:'image/png'};},assetOrigins:origins,publicAssetOrigins:new Set(),Buffer};const GatewaySession=vm.runInNewContext(source.slice(a,z)+'\nSession;',context),session=new GatewaySession({},'visitor-cookie');session.permissionsApproved=true;session.permissionRevision=1;session.nativeDomain='overte://test:40102';sessions.set(session.id,session);let handler;vm.runInNewContext(source.slice(z+1,end),{shuttingDown:false,URL,port:8090,sessions,cookie:r=>r.headers.cookie,equal:(a,b)=>a===b,json:(res,status,value)=>{res.writeHead(status,{});res.end(JSON.stringify(value));},AbortController,ASSET_SANDBOX_POLICY,http:{createServer(fn){handler=fn;return{};}}});return{session,targets,get loads(){return loads;},async request(parts=[],owner='visitor-cookie',asset='https://assets.example/texture.png',during){const url=new URL('/api/assets/'+session.id,'http://localhost:8090');url.searchParams.set('url',asset);for(const value of parts)url.searchParams.append('imagePartition',value);const response=new EventEmitter();Object.assign(response,{destroyed:false,writableEnded:false,writeHead(status,headers){this.status=status;this.headers=headers;},end(data){this.data=data;this.writableEnded=true;}});const p=handler({url:url.pathname+url.search,headers:{cookie:owner}},response);during?.();await p;return response;},close(){session.assets?.close();}};}
const valid='a'.repeat(32)+'.0';
test('actual proxy accepts bounded image partition but upstream bytes/key remain exact and shared',async()=>{const f=await fixture();try{const first=await f.request([valid]),second=await f.request(['b'.repeat(32)+'.1']),old=await f.request();assert.equal(first.status,200);assert.equal(second.status,200);assert.equal(old.status,200);assert.equal(f.loads,1);assert.deepEqual(f.targets,['https://assets.example/texture.png']);assert.equal(second.headers['x-overte-asset-source'],'memory');assert.equal(first.headers['cache-control'],'private, no-store');assert.equal(second.headers['content-security-policy'],ASSET_SANDBOX_POLICY);assert.deepEqual(first.data,second.data);}finally{f.close();}});
test('actual optional partition parser refuses duplicate malformed unsafe and oversized values before load',async()=>{const f=await fixture();try{for(const parts of[[valid,valid],[''],['secret'],['a'.repeat(32)+'.-1'],['a'.repeat(32)+'.01'],['a'.repeat(32)+'.9007199254740992'],['A'.repeat(32)+'.1'],['a'.repeat(4096)]])assert.equal((await f.request(parts)).status,400);assert.equal(f.loads,0);assert.equal((await f.request(['a'.repeat(32)+'.9007199254740991'])).status,200);}finally{f.close();}});
test('partition never substitutes for cookie current permissions session or allowlisted upstream authority',async()=>{const f=await fixture();try{assert.equal((await f.request([valid],'foreign')).status,403);f.session.permissionsApproved=false;assert.equal((await f.request([valid])).status,403);f.session.permissionsApproved=true;assert.equal((await f.request([valid],undefined,'https://unapproved.example/texture.png')).status,502);assert.equal(f.loads,0);assert.equal((await f.request([valid])).status,200);f.session.permissionRevision=2;assert.equal((await f.request([valid])).status,200);assert.equal(f.loads,2);}finally{f.close();}});
