// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';
const qml=await readFile(new URL('./tablet-capture.qml',import.meta.url),'utf8');
function method(name){const start=qml.indexOf('    function '+name+'('),next=qml.indexOf('\n    function ',start+10);assert(start>=0);return qml.slice(start,next<0?qml.lastIndexOf('\n}'):next);}
function fixture(){const rows=[],calls=[],root={objectName:'root',visible:true,children:[]},tablet={objectName:'tabletRoot',visible:false,children:[]};root.children.push(tablet);let ready=false;const c={pendingText:null,pointerSurface:null,inputSurface:null,savedSurface:null,activeCapture:null,privateGrab:null,worldKeyRoot:null,worldKeyRequest:0,worldKeyRevision:0,worldKeyNavigation:0,worldKeyWasReady:false,sendToScript:x=>rows.push(x),topRoot:()=>root,nativeInput:{worldKeyReady:x=>{assert.equal(x,root);return ready;},clickWorldKey:x=>{assert.equal(x,root);calls.push('original-native-route');return true;}}};c.helper=c;vm.createContext(c);for(const name of ['cancelWorldKeys','findWorldKeyRoot','worldKeyInputIdle','updateWorldKeyReadiness','fromScript'])vm.runInContext(method(name),c);return {c,rows,calls,root,tablet,setReady:x=>{ready=x;},arm:()=>c.fromScript({kind:'armWorldKey',revision:2,navigationSequence:8,requestId:9}),key:(extra={})=>c.fromScript({kind:'worldKey',revision:2,navigationSequence:8,requestId:9,key:'x',...extra})};}
test('actual QML cannot grant a fading/open native UI; only real readiness transitions arm the native path',()=>{const f=fixture();f.arm();assert.equal(f.rows.length,1);assert.equal(f.rows[0].ready,false);f.key();assert.equal(f.calls.length,0);f.setReady(true);f.c.updateWorldKeyReadiness();assert.equal(f.rows.at(-1).ready,true);f.key();assert.deepEqual(f.calls,['original-native-route']);f.setReady(false);f.key();assert.equal(f.rows.at(-1).ready,false);assert.equal(f.calls.length,1);});
test('actual QML exact revision/navigation/request/key/cancel guard refuses before delivery',()=>{const f=fixture();f.setReady(true);f.arm();for(const extra of [{revision:3},{navigationSequence:9},{requestId:10},{key:'w'}])f.key(extra);assert.equal(f.calls.length,0);f.c.fromScript({kind:'cancelWorldKey'});f.key();assert.equal(f.calls.length,0);assert.equal(f.c.worldKeyRoot,null);});
test('own root lookup refuses duplicate roots/cycle/visible depth and bounds without traversing hidden branches',()=>{for(const mutation of ['duplicate','cycle','deep']){const f=fixture();if(mutation==='duplicate')f.root.children.push({objectName:'tabletRoot',visible:false,children:[]});if(mutation==='cycle')f.root.children.push(f.root);if(mutation==='deep'){let p=f.root;for(let i=0;i<26;i++){const item={visible:true,children:[]};p.children.push(item);p=item;}}f.arm();assert.equal(f.c.worldKeyRoot,null,mutation);}const f=fixture();f.root.children.push({visible:false,get children(){throw Error('Hidden UI is not walked');}});f.arm();assert.equal(f.c.worldKeyRoot,f.tablet);});

test('active text/pointer/display/GPU ownership blocks readiness and dispatch until actual release',()=>{for(const field of ['pendingText','pointerSurface','inputSurface','savedSurface','activeCapture','privateGrab']){const f=fixture();f.setReady(true);f.c[field]={};f.arm();assert.equal(f.rows.length,1);assert.equal(f.rows[0].ready,false);f.key();assert.equal(f.calls.length,0);f.c[field]=null;f.c.updateWorldKeyReadiness();assert.equal(f.rows.at(-1).ready,true);f.key();assert.equal(f.calls.length,1);}});

test('missing or ambiguous root replies false with exact arm identity and never queries or dispatches native input',()=>{for(const mutation of ['missing','duplicate','cycle','deep']){const f=fixture();if(mutation==='missing')f.root.children=[];if(mutation==='duplicate')f.root.children.push({objectName:'tabletRoot',visible:false,children:[]});if(mutation==='cycle')f.root.children.push(f.root);if(mutation==='deep'){let p=f.root;for(let i=0;i<26;i++){const item={visible:true,children:[]};p.children.push(item);p=item;}}f.c.nativeInput.worldKeyReady=()=>{throw Error('Refused graph must not query native input');};f.arm();assert.equal(f.rows.length,1);assert.deepEqual(JSON.parse(JSON.stringify(f.rows[0])),{kind:'worldKeyReady',revision:2,navigationSequence:8,requestId:9,ready:false});f.key();assert.equal(f.calls.length,0);assert.equal(f.rows.at(-1).ready,false);}});
