// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
export const CAPTURE_FIELDS=Object.freeze(['echoCancellation','noiseSuppression','autoGainControl','inputGainPercent']);
const object=v=>!!v&&typeof v==='object'&&!Array.isArray(v);
function exact(v,keys){if(!object(v)||Object.keys(v).length!==keys.length||Object.keys(v).some(k=>!keys.includes(k)))throw Error('Invalid browser capture schema');}
export function captureChange(field,value){if(!CAPTURE_FIELDS.includes(field))throw Error('Unsupported browser capture setting');if(field==='inputGainPercent'){if(!Number.isInteger(value)||value<0||value>200)throw Error('Invalid browser capture gain');}else if(typeof value!=='boolean')throw Error('Invalid browser capture switch');return{field,value};}
export function captureState(v){exact(v,['version','active','controls','settings']);if(v.version!==1||typeof v.active!=='boolean')throw Error('Invalid browser capture state');exact(v.controls,CAPTURE_FIELDS);exact(v.settings,[...CAPTURE_FIELDS,'inputGain']);const controls={},settings={};for(const field of CAPTURE_FIELDS){if(typeof v.controls[field]!=='boolean')throw Error('Invalid browser capture support');controls[field]=v.controls[field];const x=v.settings[field];if(controls[field]&&x===null)throw Error('Supported capture control requires effective readback');if(field==='inputGainPercent'){if(x!==null&&(!Number.isInteger(x)||x<0||x>200))throw Error('Invalid effective capture gain');}else if(x!==null&&typeof x!=='boolean')throw Error('Invalid effective capture switch');settings[field]=x;if(!v.active&&(controls[field]||x!==null))throw Error('Inactive capture cannot claim effective settings');}if(v.settings.inputGain!==null&&(typeof v.settings.inputGain!=='number'||!Number.isFinite(v.settings.inputGain)||v.settings.inputGain<0||v.settings.inputGain>2))throw Error('Invalid effective capture amplitude');settings.inputGain=v.settings.inputGain;if(controls.inputGainPercent&&settings.inputGain===null)throw Error('Supported capture gain requires amplitude readback');if(!v.active&&settings.inputGain!==null)throw Error('Inactive capture gain');if(settings.inputGain!==null&&settings.inputGainPercent!==Math.round(settings.inputGain*100))throw Error('Capture amplitude/readback mismatch');return{version:1,active:v.active,controls,settings};}
export function captureRequest(v){if(!object(v)||v.schemaVersion!==1||!Number.isSafeInteger(v.requestId)||v.requestId<1||!['request','change','cancel'].includes(v.operation))throw Error('Invalid browser capture request');exact(v,v.operation!=='change'?['schemaVersion','requestId','operation']:['schemaVersion','requestId','operation','field','value']);return{schemaVersion:1,requestId:v.requestId,operation:v.operation,...(v.operation==='change'?captureChange(v.field,v.value):{})};}
export const CAPTURE_REASONS=Object.freeze(['ok','inactive','unsupported','busy','apply-refused','readback-mismatch','rollback-refused','deadline','cancelled']);
export function captureResult(v){exact(v,['schemaVersion','requestId','accepted','reason','state']);if(v.schemaVersion!==1||!Number.isSafeInteger(v.requestId)||v.requestId<1||typeof v.accepted!=='boolean'||!CAPTURE_REASONS.includes(v.reason)||v.accepted!==(v.reason==='ok'))throw Error('Invalid browser capture acknowledgement');return{schemaVersion:1,requestId:v.requestId,accepted:v.accepted,reason:v.reason,state:captureState(v.state)};}
export function inactiveCapture(){return{version:1,active:false,controls:Object.fromEntries(CAPTURE_FIELDS.map(f=>[f,false])),settings:{echoCancellation:null,noiseSuppression:null,autoGainControl:null,inputGainPercent:null,inputGain:null}};}
