#!/usr/bin/env python3
# Copyright 2026 Overte contributors
# SPDX-License-Identifier: Apache-2.0
"""Generate browser packet versions by executing the production C++ version table."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import shlex
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]
DESTINATION = ROOT / "browser-direct-client/src/protocol/generated.ts"
SOURCE = ROOT / "libraries/networking/src/udt"

PROGRAM = r'''
#include "PacketHeaders.h"
#include "Constants.h"
#include <QCoreApplication>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QMetaEnum>
#include <iostream>
int main(int argc, char** argv) {
    QCoreApplication app(argc, argv);
    const auto meta = QMetaEnum::fromType<PacketType>();
    QJsonArray packets;
    QJsonArray nonSourced, nonVerified, domainSourced, domainIgnoredVerification, replicated;
    const auto replicatedMapping = PacketTypeEnum::getReplicatedPacketMapping();
    for (int i = 0; i < static_cast<int>(PacketType::NUM_PACKET_TYPE); ++i) {
        const auto type = static_cast<PacketType>(i);
        packets.append(QJsonObject{{"name", meta.valueToKey(i)}, {"id", i},
            {"version", static_cast<int>(versionForPacketType(type))}});
        if (PacketTypeEnum::getNonSourcedPackets().contains(type)) nonSourced.append(i);
        if (PacketTypeEnum::getNonVerifiedPackets().contains(type)) nonVerified.append(i);
        if (PacketTypeEnum::getDomainSourcedPackets().contains(type)) domainSourced.append(i);
        if (PacketTypeEnum::getDomainIgnoredVerificationPackets().contains(type)) domainIgnoredVerification.append(i);
        if (replicatedMapping.contains(type)) replicated.append(QJsonArray{i, static_cast<int>(replicatedMapping.value(type))});
    }
    std::cout << QJsonDocument(QJsonObject{{"signature", protocolVersionsSignatureHex()},
        {"maxPacketBytes", udt::MAX_PACKET_SIZE},
        {"nonSourced", nonSourced}, {"nonVerified", nonVerified},
        {"domainSourced", domainSourced}, {"domainIgnoredVerification", domainIgnoredVerification},
        {"replicated", replicated},
        {"packets", packets}}).toJson(QJsonDocument::Compact).constData();
}
'''


def generate(include_directories: list[Path]) -> str:
    package = "Qt6Core"
    moc = shutil.which("moc6") or "/usr/lib64/qt6/libexec/moc"
    if not Path(moc).is_file():
        # Ubuntu packages keep moc under this directory.
        moc = "/usr/lib/qt6/libexec/moc"
    flags = shlex.split(subprocess.check_output(["pkg-config", "--cflags", "--libs", package], text=True))
    with tempfile.TemporaryDirectory(prefix="overte-direct-protocol-") as temporary:
        work = Path(temporary)
        (work / "main.cpp").write_text(PROGRAM)
        subprocess.run([moc, str(SOURCE / "PacketHeaders.h"), "-o", str(work / "moc.cpp")], check=True)
        include_flags = [flag for path in include_directories for flag in ("-I", str(path.resolve()))]
        subprocess.run(["c++", "-std=c++17", "-fPIC", "-I", str(SOURCE), *include_flags,
            str(work / "main.cpp"), str(work / "moc.cpp"), str(SOURCE / "PacketHeaders.cpp"),
            "-o", str(work / "protocol"), *flags], check=True)
        result = json.loads(subprocess.check_output([str(work / "protocol")], text=True))
    packets = result["packets"]
    return ("// Generated by tools/generate-protocol.py from production PacketHeaders.cpp.\n"
        "// Copyright 2026 Overte contributors; SPDX-License-Identifier: Apache-2.0\n"
        "export const protocolSignatureHex = " + json.dumps(result["signature"]) + ";\n"
        "export const maxPacketBytes = " + str(result["maxPacketBytes"]) + ";\n"
        "export const packetVersions = " + json.dumps([p["version"] for p in packets]) + " as const;\n"
        "export const nonSourcedPacketIds = " + json.dumps(result["nonSourced"]) + " as const;\n"
        "export const nonVerifiedPacketIds = " + json.dumps(result["nonVerified"]) + " as const;\n"
        "export const domainSourcedPacketIds = " + json.dumps(result["domainSourced"]) + " as const;\n"
        "export const domainIgnoredVerificationPacketIds = " + json.dumps(result["domainIgnoredVerification"]) + " as const;\n"
        "export const replicatedPacketIds = " + json.dumps(result["replicated"]) + " as const;\n"
        "export const packetIds = " + json.dumps({p["name"]: p["id"] for p in packets}, indent=2) + " as const;\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--include-directory", type=Path, action="append", default=[],
                        help="additional prepared native header directory (for example Conan's GLM include)")
    args = parser.parse_args()
    generated = generate(args.include_directory)
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text() != generated:
            raise SystemExit("Browser/native packet table differs; regenerate and review protocol changes.")
        print("Browser/native packet table and signature match production C++.")
    else:
        DESTINATION.parent.mkdir(parents=True, exist_ok=True)
        DESTINATION.write_text(generated)
        print("Generated browser packet table from production C++.")


if __name__ == "__main__":
    main()
