pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'overte-phone'
rootProject.buildFileName = 'build-phone.gradle'

include ':phoneInterface'
project(':phoneInterface').projectDir = file('apps/phoneInterface')
