pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'overte-pico'
rootProject.buildFileName = 'build.gradle'

include ':picoInterface'
project(':picoInterface').projectDir = file('apps/picoInterface')
