#!/usr/bin/env bash
# Copyright 2026 Overte e.V.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

readonly script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly source_root="$(cd -- "$script_dir/.." && pwd)"
readonly versions_file="$script_dir/versions.env"
readonly overte_conan_remote_url="https://artifactory.overte.org/artifactory/api/conan/overte"

fail() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

note() {
    printf '%s\n' "$*"
}

usage() {
    cat <<'EOF'
Usage: ios/build-ios.sh COMMAND [OPTIONS]

Commands:
  doctor                         Validate the macOS, Xcode, CMake and Conan host.
  bootstrap                      Create the local Python tool environment.
  deps --platform TARGET        Resolve the staged native dependency graph.
  configure --platform TARGET   Generate the Xcode project (simulator or device).
  build --platform TARGET       Configure and build the bootstrap application.
  test [--platform TARGET]      Run host contracts, optionally build for TARGET.
  package --platform TARGET     Produce a simulator archive or device IPA plus manifest.
  package-client --platform TARGET
                                 Package an already-built experimental Overte client.
  clean --platform TARGET       Print the build directory; use --confirm to remove it.

Options:
  --platform simulator|device   Target platform. Defaults to simulator.
  --configuration NAME          Xcode configuration. Defaults to Debug.
  --build-dir PATH              Override the target build directory.
  --bundle-id IDENTIFIER        Override the product-specific bundle identifier.
  --development-team TEAM       Enable device signing with this Apple team ID.
  --require-qt                  Make doctor fail unless Qt 6 for iOS is configured.
  --require-v8                  Make doctor validate the static iOS V8/libnode package.
  --graphics-toolchain          Include Vulkan and host shader tools in deps.
  --require-moltenvk            Make doctor validate the MoltenVK XCFramework.
  --client-graph                Configure the experimental full client dependency graph.
  --confirm                     Confirm clean removal of the resolved build directory.
  -h, --help                    Show this help.

Signing is disabled unless --development-team is supplied for a device build.
The experimental --client-graph option is supported by configure only. It requires
OVERTE_IOS_QT_ROOT and a Conan toolchain generated by the deps command.
EOF
}

[[ -f "$versions_file" ]] || fail "missing version contract: $versions_file"
# shellcheck disable=SC1090
source "$versions_file"

command_name="${1:-}"
[[ -n "$command_name" ]] || {
    usage
    exit 2
}
shift

platform="simulator"
configuration="Debug"
build_dir=""
bundle_id=""
development_team=""
confirm_clean=0
require_qt=0
require_v8=0
with_graphics_toolchain=False
require_moltenvk=0
client_graph=0
compiler_launcher="${OVERTE_IOS_COMPILER_LAUNCHER:-}"
build_jobs="$(sysctl -n hw.logicalcpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)"
[[ "$build_jobs" =~ ^[1-9][0-9]*$ ]] || build_jobs=4

while (($#)); do
    case "$1" in
        --platform)
            (($# >= 2)) || fail "--platform requires a value"
            platform="$2"
            shift 2
            ;;
        --configuration)
            (($# >= 2)) || fail "--configuration requires a value"
            configuration="$2"
            shift 2
            ;;
        --build-dir)
            (($# >= 2)) || fail "--build-dir requires a value"
            build_dir="$2"
            shift 2
            ;;
        --bundle-id)
            (($# >= 2)) || fail "--bundle-id requires a value"
            bundle_id="$2"
            shift 2
            ;;
        --development-team)
            (($# >= 2)) || fail "--development-team requires a value"
            development_team="$2"
            shift 2
            ;;
        --confirm)
            confirm_clean=1
            shift
            ;;
        --require-qt)
            require_qt=1
            shift
            ;;
        --require-v8)
            require_v8=1
            shift
            ;;
        --graphics-toolchain)
            with_graphics_toolchain=True
            shift
            ;;
        --require-moltenvk)
            require_moltenvk=1
            shift
            ;;
        --client-graph)
            client_graph=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            fail "unknown option: $1"
            ;;
    esac
done

if ((client_graph)) && [[ "$command_name" != "configure" ]]; then
    fail "--client-graph is only valid with the configure command"
fi

# Bootstrap and Full Client are separate products. Keeping their default
# identities distinct prevents a bootstrap preview from silently replacing a
# Full Client (or vice versa) during Sideloadly and simulator installs.
if [[ -z "$bundle_id" ]]; then
    if ((client_graph)) || [[ "$command_name" == "package-client" ]]; then
        bundle_id="org.overte.interface.dev"
    else
        bundle_id="org.overte.bootstrap.dev"
    fi
fi

case "$platform" in
    simulator)
        sdk_name="iphonesimulator"
        conan_profile="$script_dir/conan/profiles/ios-simulator-arm64"
        ;;
    device)
        sdk_name="iphoneos"
        conan_profile="$script_dir/conan/profiles/ios-arm64"
        ;;
    *)
        fail "unsupported platform '$platform'; use simulator or device"
        ;;
esac

[[ "$configuration" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]] \
    || fail "invalid Xcode configuration name: $configuration"
[[ "$bundle_id" =~ ^[A-Za-z0-9][A-Za-z0-9-]*(\.[A-Za-z0-9][A-Za-z0-9-]*)+$ ]] \
    || fail "invalid bundle identifier: $bundle_id"
if [[ -n "$development_team" && ! "$development_team" =~ ^[A-Z0-9]{10}$ ]]; then
    fail "Apple development team IDs must contain exactly 10 uppercase letters or digits"
fi

if [[ -z "$build_dir" ]]; then
    build_dir="$source_root/build-ios/$platform"
elif [[ "$build_dir" != /* ]]; then
    build_dir="$source_root/$build_dir"
fi

version_at_least() {
    local actual="$1"
    local required="$2"
    python3 "$script_dir/tools/version-at-least.py" "$actual" "$required"
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

require_macos() {
    [[ "$(uname -s)" == "Darwin" ]] || fail "iOS builds require macOS with Xcode"
}

run_doctor() {
    require_macos
    require_command xcodebuild
    require_command xcrun
    require_command cmake
    require_command python3

    local xcode_version sdk_version cmake_version conan_version python_version
    xcode_version="$(xcodebuild -version | sed -n '1s/^Xcode //p')"
    [[ -n "$xcode_version" ]] || fail "could not determine the Xcode version"
    version_at_least "$xcode_version" "$OVERTE_IOS_REQUIRED_XCODE_MAJOR" \
        || fail "Xcode $OVERTE_IOS_REQUIRED_XCODE_MAJOR or newer is required; found $xcode_version"

    sdk_version="$(xcrun --sdk "$sdk_name" --show-sdk-version)"
    version_at_least "$sdk_version" "$OVERTE_IOS_REQUIRED_SDK_MAJOR" \
        || fail "iOS SDK $OVERTE_IOS_REQUIRED_SDK_MAJOR or newer is required; found $sdk_version"

    cmake_version="$(cmake --version | sed -n '1s/^cmake version //p')"
    version_at_least "$cmake_version" "$OVERTE_IOS_CMAKE_MIN_VERSION" \
        || fail "CMake $OVERTE_IOS_CMAKE_MIN_VERSION or newer is required; found $cmake_version"

    python_version="$(python3 -c 'import platform; print(platform.python_version())')"
    version_at_least "$python_version" "$OVERTE_IOS_PYTHON_MIN_VERSION" \
        || fail "Python $OVERTE_IOS_PYTHON_MIN_VERSION or newer is required; found $python_version"

    if command -v conan >/dev/null 2>&1; then
        conan_version="$(conan --version | awk '{print $3}')"
        [[ "$conan_version" == "$OVERTE_IOS_CONAN_VERSION" ]] \
            || fail "Conan $OVERTE_IOS_CONAN_VERSION is required for the audited graph; found $conan_version"
    else
        conan_version="not installed (run bootstrap before dependency resolution)"
    fi

    note "Xcode: $xcode_version"
    note "$sdk_name SDK: $sdk_version"
    note "CMake: $cmake_version"
    note "Python: $python_version"
    note "Conan: $conan_version"
    note "Conan host profile: $conan_profile"

    local qt_root="${OVERTE_IOS_QT_ROOT:-}"
    if [[ -n "$qt_root" ]]; then
        [[ -f "$qt_root/lib/cmake/Qt6/Qt6Config.cmake" ]] \
            || fail "OVERTE_IOS_QT_ROOT does not contain lib/cmake/Qt6/Qt6Config.cmake"
        local qt_version_file="$qt_root/lib/cmake/Qt6/Qt6ConfigVersionImpl.cmake"
        [[ -f "$qt_version_file" ]] \
            || fail "OVERTE_IOS_QT_ROOT does not contain Qt6ConfigVersionImpl.cmake"
        [[ -x "$qt_root/bin/qt-cmake" ]] \
            || fail "OVERTE_IOS_QT_ROOT does not contain bin/qt-cmake"
        [[ -f "$qt_root/lib/cmake/Qt6/qt.toolchain.cmake" ]] \
            || fail "OVERTE_IOS_QT_ROOT does not contain lib/cmake/Qt6/qt.toolchain.cmake"
        local qt_version
        qt_version="$(sed -n 's/^set(PACKAGE_VERSION "\([0-9.]*\)")$/\1/p' "$qt_version_file" | head -n 1)"
        [[ -n "$qt_version" ]] || fail "could not determine Qt version below OVERTE_IOS_QT_ROOT"
        version_at_least "$qt_version" "$OVERTE_IOS_QT_MIN_VERSION" \
            || fail "Qt $OVERTE_IOS_QT_MIN_VERSION or newer is required; found $qt_version"
        note "Qt for iOS: $qt_root ($qt_version)"
    elif ((require_qt)); then
        fail "set OVERTE_IOS_QT_ROOT to a Qt 6 iOS installation"
    else
        note "Qt for iOS: not configured (native bootstrap only)"
    fi

    local v8_root="${OVERTE_IOS_V8_ROOT:-}"
    if [[ -n "$v8_root" ]]; then
        [[ -f "$v8_root/include/node/v8.h" ]] \
            || fail "OVERTE_IOS_V8_ROOT does not contain include/node/v8.h"
        local v8_archive=""
        for candidate in "$v8_root/lib/libnode.a" "$v8_root/lib/libv8_monolith.a"; do
            if [[ -f "$candidate" ]]; then
                v8_archive="$candidate"
                break
            fi
        done
        [[ -n "$v8_archive" ]] \
            || fail "OVERTE_IOS_V8_ROOT does not contain a static libnode.a or libv8_monolith.a"
        require_command lipo
        lipo "$v8_archive" -verify_arch arm64 >/dev/null \
            || fail "iOS V8 archive does not contain arm64: $v8_archive"
        note "Static non-JIT V8: $v8_archive (arm64)"
    elif ((require_v8)); then
        fail "set OVERTE_IOS_V8_ROOT to an audited static non-JIT iOS package"
    else
        note "Static non-JIT V8: not configured (scripting integration disabled)"
    fi

    local moltenvk_root="${OVERTE_IOS_MOLTENVK_ROOT:-}"
    if [[ -n "$moltenvk_root" ]]; then
        local moltenvk_slice="ios-arm64"
        [[ "$platform" == "simulator" ]] && moltenvk_slice="ios-arm64_x86_64-simulator"
        [[ -f "$moltenvk_root/MoltenVK/include/vulkan/vulkan.h" ]] \
            || fail "MoltenVK headers not found below OVERTE_IOS_MOLTENVK_ROOT"
        local moltenvk_xcframework="$moltenvk_root/MoltenVK/static/MoltenVK.xcframework"
        [[ -d "$moltenvk_xcframework" ]] \
            || moltenvk_xcframework="$moltenvk_root/MoltenVK/MoltenVK.xcframework"
        [[ -f "$moltenvk_xcframework/$moltenvk_slice/libMoltenVK.a" ]] \
            || fail "MoltenVK static slice not found: $moltenvk_slice"
        require_command lipo
        lipo "$moltenvk_xcframework/$moltenvk_slice/libMoltenVK.a" \
            -verify_arch arm64 >/dev/null \
            || fail "MoltenVK static slice does not contain arm64: $moltenvk_slice"
        note "MoltenVK: $moltenvk_root ($moltenvk_slice)"
    elif ((require_moltenvk)); then
        fail "set OVERTE_IOS_MOLTENVK_ROOT to an unpacked MoltenVK distribution"
    else
        note "MoltenVK: not configured (native Metal bootstrap only)"
    fi
    note "iOS build environment is ready for the $platform bootstrap target."
}

run_bootstrap() {
    require_macos
    require_command python3
    require_command cmake
    require_command xcodebuild
    require_command xcrun

    local python_version
    python_version="$(python3 -c 'import platform; print(platform.python_version())')"
    version_at_least "$python_version" "$OVERTE_IOS_PYTHON_MIN_VERSION" \
        || fail "Python $OVERTE_IOS_PYTHON_MIN_VERSION or newer is required; found $python_version"

    local venv_dir="$source_root/build-ios/tooling-venv"
    python3 -m venv "$venv_dir"
    "$venv_dir/bin/python" -m pip install --upgrade pip
    "$venv_dir/bin/python" -m pip install "conan==${OVERTE_IOS_CONAN_VERSION}"
    "$venv_dir/bin/python" -m pip freeze --all > "$venv_dir/tooling-versions.txt"
    note "Tool environment created at $venv_dir"
    note "Resolved Python tooling recorded at $venv_dir/tooling-versions.txt"
    note "Activate it with: source $venv_dir/bin/activate"
}

resolve_dependencies() {
    run_doctor
    require_command conan
    if conan remote list | grep -q '^overte:'; then
        conan remote update overte --url "$overte_conan_remote_url"
    else
        conan remote add overte "$overte_conan_remote_url"
    fi
    # These upstream recipes produce dylibs even when the graph requests
    # *:shared=False.  Export dedicated, source-pinned static iOS recipes into
    # the job-local Conan home before graph resolution.
    conan export "$script_dir/conan/recipes/onetbb" \
        --user=overte --channel=ios-static
    conan export "$script_dir/conan/recipes/webrtc-audio-processing" \
        --user=overte --channel=ios-static
    local sdk_path conan_output="$build_dir/conan"
    sdk_path="$(xcrun --sdk "$sdk_name" --show-sdk-path)"
    if [[ "$platform" == "simulator" ]]; then
        export OVERTE_IOS_SIMULATOR_SDK_PATH="$sdk_path"
    else
        export OVERTE_IOS_DEVICE_SDK_PATH="$sdk_path"
    fi
    mkdir -p "$conan_output"
    conan install "$script_dir" \
        --profile:host="$conan_profile" \
        --profile:build="$script_dir/conan/profiles/macos-arm64" \
        --build=missing \
        --options="overte-ios-dependencies/*:with_graphics_toolchain=$with_graphics_toolchain" \
        --output-folder="$conan_output" \
        --format=json > "$conan_output/graph.json"
    python3 "$script_dir/tools/audit-conan-graph.py" "$conan_output/graph.json"
    python3 "$script_dir/tools/generate-sbom.py" \
        "$conan_output/graph.json" "$script_dir/dependencies.json" "$conan_output/sbom.cdx.json"
    note "Resolved staged dependency graph at $conan_output"
    note "Generated dependency and compliance inventory at $conan_output/sbom.cdx.json"
}

configure_project() {
    run_doctor
    local sdk_path signing=OFF
    local cmake_frontend="cmake"
    sdk_path="$(xcrun --sdk "$sdk_name" --show-sdk-path)"
    if [[ -n "$development_team" ]]; then
        [[ "$platform" == "device" ]] \
            || fail "--development-team is only valid with --platform device"
        signing=ON
    fi

    local bootstrap_only=ON
    local -a configure_arguments=()
    if ((client_graph)); then
        local qt_root="${OVERTE_IOS_QT_ROOT:-}"
        local conan_toolchain="$build_dir/conan/conan_toolchain.cmake"
        [[ -n "$qt_root" ]] \
            || fail "--client-graph requires OVERTE_IOS_QT_ROOT"
        [[ -f "$qt_root/lib/cmake/Qt6/Qt6Config.cmake" ]] \
            || fail "OVERTE_IOS_QT_ROOT does not contain lib/cmake/Qt6/Qt6Config.cmake"
        [[ -f "$conan_toolchain" ]] \
            || fail "--client-graph requires $conan_toolchain; run deps first"
        bootstrap_only=OFF
        cmake_frontend="$qt_root/bin/qt-cmake"
        configure_arguments+=(
            "-DQT_CHAINLOAD_TOOLCHAIN_FILE=$conan_toolchain"
        )
        note "Configuring the experimental full iOS client graph through Qt with Conan chainloaded."
    fi

    # Keep this array unconditionally non-empty. Bash 3.2 with `set -u` treats
    # expansion of a declared but empty array as an unbound variable.
    configure_arguments+=(
        -S "$source_root"
        -B "$build_dir"
        -G Xcode
        -DCMAKE_SYSTEM_NAME=iOS
        -DCMAKE_OSX_ARCHITECTURES=arm64
        "-DCMAKE_OSX_DEPLOYMENT_TARGET=$OVERTE_IOS_MIN_VERSION"
        "-DCMAKE_OSX_SYSROOT=$sdk_path"
        "-DOVERTE_IOS_SDK_NAME=$sdk_name"
        "-DOVERTE_IOS_BUNDLE_IDENTIFIER=$bundle_id"
        "-DOVERTE_IOS_DEVELOPMENT_TEAM=$development_team"
        "-DOVERTE_IOS_ENABLE_SIGNING=$signing"
        "-DOVERTE_IOS_BOOTSTRAP_ONLY=$bootstrap_only"
    )
    if [[ -n "$compiler_launcher" ]]; then
        local compiler_launcher_path
        compiler_launcher_path="$(command -v "$compiler_launcher" 2>/dev/null || true)"
        [[ -n "$compiler_launcher_path" && -x "$compiler_launcher_path" ]] \
            || fail "OVERTE_IOS_COMPILER_LAUNCHER is not executable: $compiler_launcher"
        # CMAKE_<LANG>_COMPILER_LAUNCHER is not implemented by CMake's Xcode
        # generator. Xcode's C_COMPILER_LAUNCHER build setting covers the C,
        # C++, Objective-C and Objective-C++ compile rules instead. Disable the
        # Xcode features that bypass sccache's documented integration contract,
        # including compiler response files.
        configure_arguments+=(
            "-DCMAKE_XCODE_ATTRIBUTE_C_COMPILER_LAUNCHER=$compiler_launcher_path"
            -DCMAKE_XCODE_ATTRIBUTE_CLANG_ENABLE_MODULES=NO
            -DCMAKE_XCODE_ATTRIBUTE_COMPILER_INDEX_STORE_ENABLE=NO
            -DCMAKE_XCODE_ATTRIBUTE_CLANG_USE_RESPONSE_FILE=NO
        )
        note "Configuring Xcode compiler checkpoint through $compiler_launcher_path"
    fi
    "$cmake_frontend" "${configure_arguments[@]}"
}

build_project() {
    configure_project
    cmake --build "$build_dir" --config "$configuration" \
        --parallel "$build_jobs" --target OverteIOSBootstrap
}

run_tests() {
    "$script_dir/tests/run-tests.sh"
    if [[ "$platform" == "simulator" || "$platform" == "device" ]]; then
        if [[ "$(uname -s)" == "Darwin" ]]; then
            build_project
        else
            note "Skipping Xcode build tier on non-macOS host."
        fi
    fi
}

run_package() {
    build_project
    local artifact_sequence="${OVERTE_IOS_ARTIFACT_SEQUENCE:-${GITHUB_RUN_NUMBER:-0}}"
    [[ "$artifact_sequence" =~ ^[0-9]+$ ]] \
        || fail "artifact sequence must contain digits only: $artifact_sequence"
    local artifact_prefix
    printf -v artifact_prefix '%04d' "$((10#$artifact_sequence))"
    local app_path="$build_dir/ios/$configuration-iphoneos/OverteIOSBootstrap.app"
    if [[ "$platform" == "simulator" ]]; then
        app_path="$build_dir/ios/$configuration-iphonesimulator/OverteIOSBootstrap.app"
    fi
    [[ -d "$app_path" ]] || fail "built application not found: $app_path"

    local artifact_dir="$source_root/build-ios/artifacts"
    mkdir -p "$artifact_dir"
    if [[ "$platform" == "simulator" ]]; then
        local archive="$artifact_dir/${artifact_prefix}-OverteIOSBootstrap-${configuration}-simulator.zip"
        ditto -c -k --sequesterRsrc --keepParent "$app_path" "$archive"
        local archive_sha source_revision manifest
        archive_sha="$(shasum -a 256 "$archive" | awk '{print $1}')"
        source_revision="$(git -C "$source_root" rev-parse HEAD)"
        manifest="$artifact_dir/${artifact_prefix}-OverteIOSBootstrap-${configuration}-simulator.json"
        python3 - "$manifest" "$archive" "$archive_sha" "$source_revision" \
            "$configuration" "$(xcodebuild -version | tr '\n' ' ')" \
            "$(xcrun --sdk iphonesimulator --show-sdk-version)" "$artifact_sequence" <<'PY'
import json
import pathlib
import sys

output, archive, digest, revision, configuration, xcode, sdk, build_number = sys.argv[1:]
payload = {
    "schemaVersion": 1,
    "buildNumber": int(build_number),
    "artifact": pathlib.Path(archive).name,
    "sha256": digest,
    "sourceRevision": revision,
    "platform": "iphonesimulator",
    "architecture": "arm64",
    "configuration": configuration,
    "xcode": xcode.strip(),
    "sdk": sdk,
    "signed": False,
}

pathlib.Path(output).write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
PY
        note "Created unsigned simulator artifact: $archive"
        note "Created artifact manifest: $manifest"
    else
        local signing_label="unsigned" signed_state="false"
        if [[ -n "$development_team" ]]; then
            signing_label="signed"
            signed_state="true"
        fi

        local ipa="$artifact_dir/${artifact_prefix}-OverteIOSBootstrap-${configuration}-device-${signing_label}.ipa"
        local payload_root
        payload_root="$(mktemp -d "${TMPDIR:-/tmp}/overte-ios-device-package.XXXXXX")"
        [[ -d "$payload_root" && "$payload_root" == */overte-ios-device-package.* ]] \
            || fail "could not create a bounded device packaging directory"
        mkdir -p "$payload_root/Payload"
        ditto "$app_path" "$payload_root/Payload/OverteIOSBootstrap.app"
        ditto -c -k --sequesterRsrc --keepParent "$payload_root/Payload" "$ipa"
        cmake -E remove_directory "$payload_root"

        local ipa_sha source_revision manifest
        ipa_sha="$(shasum -a 256 "$ipa" | awk '{print $1}')"
        source_revision="$(git -C "$source_root" rev-parse HEAD)"
        manifest="$artifact_dir/${artifact_prefix}-OverteIOSBootstrap-${configuration}-device-${signing_label}.json"
        python3 - "$manifest" "$ipa" "$ipa_sha" "$source_revision" \
            "$configuration" "$(xcodebuild -version | tr '\n' ' ')" \
            "$(xcrun --sdk iphoneos --show-sdk-version)" "$signed_state" "$artifact_sequence" <<'PY'
import json
import pathlib
import sys

output, archive, digest, revision, configuration, xcode, sdk, signed, build_number = sys.argv[1:]
is_signed = signed == "true"
payload = {
    "schemaVersion": 1,
    "buildNumber": int(build_number),
    "artifact": pathlib.Path(archive).name,
    "sha256": digest,
    "sourceRevision": revision,
    "platform": "iphoneos",
    "architecture": "arm64",
    "configuration": configuration,
    "xcode": xcode.strip(),
    "sdk": sdk,
    "signed": is_signed,
    "requiresSigning": not is_signed,
}
pathlib.Path(output).write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
PY
        note "Created ${signing_label} device IPA: $ipa"
        note "Created artifact manifest: $manifest"
    fi
}

run_package_client() {
    require_macos
    require_command ditto
    require_command shasum
    require_command xcrun

    local artifact_sequence="${OVERTE_IOS_ARTIFACT_SEQUENCE:-${GITHUB_RUN_NUMBER:-}}"
    [[ "$artifact_sequence" =~ ^[1-9][0-9]*$ ]] \
        || fail "package-client requires a positive OVERTE_IOS_ARTIFACT_SEQUENCE or GITHUB_RUN_NUMBER"
    local artifact_prefix
    printf -v artifact_prefix '%04d' "$((10#$artifact_sequence))"

    local sdk_suffix="iphoneos" archive_suffix="device" extension="ipa"
    local app_path="$build_dir/interface/${configuration}-iphoneos/Overte.app"
    if [[ "$platform" == "simulator" ]]; then
        sdk_suffix="iphonesimulator"
        archive_suffix="simulator"
        extension="zip"
        app_path="$build_dir/interface/${configuration}-iphonesimulator/Overte.app"
    fi
    [[ -d "$app_path" ]] || fail "integrated client app not found: $app_path; build target Overte first"
    [[ -f "$app_path/Info.plist" ]] || fail "integrated client app has no Info.plist: $app_path"
    [[ -x "$app_path/Overte" ]] || fail "integrated client executable is missing or not executable: $app_path/Overte"
    [[ -f "$app_path/PrivacyInfo.xcprivacy" ]] \
        || fail "integrated client privacy manifest not found: $app_path/PrivacyInfo.xcprivacy"
    python3 "$script_dir/tools/verify-client-bundle-info.py" \
        "$app_path" "$bundle_id" "$sdk_suffix" "$OVERTE_IOS_MIN_VERSION" \
        || fail "integrated client install metadata failed validation"
    python3 "$script_dir/tools/verify-privacy-manifest.py" \
        "$app_path/PrivacyInfo.xcprivacy" \
        || fail "integrated client privacy manifest failed the audited contract"
    python3 "$script_dir/tools/verify-ios-static-runtime.py" "$app_path" \
        || fail "integrated client has unsafe or unresolved Mach-O runtime dependencies"

    local dsym_path="$build_dir/interface/${configuration}-${sdk_suffix}/Overte.app.dSYM"
    local dsym_binary="$dsym_path/Contents/Resources/DWARF/Overte"
    local app_uuid="" symbols_archive="" symbols_sha=""
    if [[ "$configuration" == "Release" ]]; then
        [[ -d "$dsym_path" ]] \
            || fail "Release integrated client dSYM is missing: $dsym_path"
        [[ -f "$dsym_binary" ]] \
            || fail "Release integrated client dSYM has no Overte DWARF image: $dsym_binary"
        local binary_uuid symbol_uuid
        binary_uuid="$(xcrun dwarfdump --uuid "$app_path/Overte")" \
            || fail "could not read the Release client Mach-O UUID"
        symbol_uuid="$(xcrun dwarfdump --uuid "$dsym_binary")" \
            || fail "could not read the Release client dSYM UUID"
        app_uuid="$(python3 - "$binary_uuid" "$symbol_uuid" <<'PY'
import re
import sys

uuid_pattern = re.compile(
    r"^UUID: ([0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}) \(arm64\)(?: .*)?$"
)

def one_uuid(label, output):
    values = [match.group(1).lower() for line in output.splitlines()
              if (match := uuid_pattern.fullmatch(line.strip()))]
    if len(values) != 1:
        raise SystemExit(f"{label} must contain exactly one arm64 UUID")
    return values[0]

binary_uuid = one_uuid("application binary", sys.argv[1])
symbol_uuid = one_uuid("dSYM DWARF image", sys.argv[2])
if binary_uuid != symbol_uuid:
    raise SystemExit("application binary and dSYM UUIDs differ")
print(binary_uuid)
PY
)" || fail "Release integrated client dSYM does not match the packaged executable"
    fi

    local artifact_dir="$source_root/build-ios/artifacts"
    mkdir -p "$artifact_dir"
    local signing_label="unsigned" signed_state="false"
    local provisioned_state="false" application_identifier="" get_task_allow="null"
    if [[ -n "$development_team" ]]; then
        [[ "$platform" == "device" ]] || fail "--development-team is only valid with --platform device"
        require_command codesign
        require_command security
        [[ -f "$app_path/embedded.mobileprovision" ]] \
            || fail "signed integrated client has no embedded.mobileprovision"
        codesign --verify --deep --strict "$app_path" \
            || fail "integrated client bundle did not pass code-signature verification"
        local signing_audit_dir profile_plist signature_plist signing_audit
        signing_audit_dir="$(mktemp -d "${TMPDIR:-/tmp}/overte-ios-signing-audit.XXXXXX")"
        profile_plist="$signing_audit_dir/profile.plist"
        signature_plist="$signing_audit_dir/signature.plist"
        security cms -D -i "$app_path/embedded.mobileprovision" > "$profile_plist" \
            || fail "could not decode integrated client provisioning profile"
        codesign -d --entitlements :- "$app_path" > "$signature_plist" 2>/dev/null \
            || fail "could not extract integrated client signing entitlements"
        signing_audit="$(python3 - "$profile_plist" "$signature_plist" "$bundle_id" "$development_team" <<'PY'
import plistlib
import sys

profile_path, signature_path, bundle_id, expected_team = sys.argv[1:]
with open(profile_path, "rb") as stream:
    profile = plistlib.load(stream)
with open(signature_path, "rb") as stream:
    signature = plistlib.load(stream)
profile_entitlements = profile.get("Entitlements", {})
application_identifier = signature.get("application-identifier")
team_identifier = signature.get("com.apple.developer.team-identifier")
expected_identifier = f"{expected_team}.{bundle_id}"
if application_identifier != expected_identifier:
    raise SystemExit(f"application-identifier mismatch: expected {expected_identifier}")
if team_identifier != expected_team or expected_team not in profile.get("TeamIdentifier", []):
    raise SystemExit("signing team does not match the provisioning profile")
if profile_entitlements.get("application-identifier") != expected_identifier:
    raise SystemExit("provisioning profile application-identifier mismatch")
get_task_allow = signature.get("get-task-allow", False)
if get_task_allow != profile_entitlements.get("get-task-allow", False):
    raise SystemExit("get-task-allow differs between signature and provisioning profile")
print(f"{application_identifier}\t{str(bool(get_task_allow)).lower()}")
PY
)" || fail "integrated client signing metadata failed validation"
        cmake -E remove_directory "$signing_audit_dir"
        IFS=$'\t' read -r application_identifier get_task_allow <<< "$signing_audit"
        signing_label="signed"
        signed_state="true"
        provisioned_state="true"
    elif [[ "$platform" == "device" ]]; then
        [[ ! -e "$app_path/embedded.mobileprovision" ]] \
            || fail "unsigned integrated client unexpectedly contains embedded.mobileprovision"
        [[ ! -d "$app_path/_CodeSignature" ]] \
            || fail "unsigned integrated client unexpectedly contains _CodeSignature"
    fi
    local stem="${artifact_prefix}-OverteIOSClient-${configuration}-${archive_suffix}"
    [[ "$platform" == "simulator" ]] || stem="${stem}-${signing_label}"
    local archive="$artifact_dir/${stem}.${extension}"

    if [[ "$configuration" == "Release" ]]; then
        symbols_archive="$artifact_dir/${stem}-symbols.zip"
        ditto -c -k --sequesterRsrc --keepParent "$dsym_path" "$symbols_archive"
        symbols_sha="$(shasum -a 256 "$symbols_archive" | awk '{print $1}')"
    fi

    if [[ "$platform" == "simulator" ]]; then
        ditto -c -k --sequesterRsrc --keepParent "$app_path" "$archive"
    else
        local payload_root
        payload_root="$(mktemp -d "${TMPDIR:-/tmp}/overte-ios-client-package.XXXXXX")"
        [[ -d "$payload_root" && "$payload_root" == */overte-ios-client-package.* ]] \
            || fail "could not create a bounded integrated-client packaging directory"
        mkdir -p "$payload_root/Payload"
        ditto "$app_path" "$payload_root/Payload/Overte.app"
        ditto -c -k --sequesterRsrc --keepParent "$payload_root/Payload" "$archive"
        cmake -E remove_directory "$payload_root"
    fi

    local archive_sha source_revision manifest latest_json latest_text
    archive_sha="$(shasum -a 256 "$archive" | awk '{print $1}')"
    source_revision="$(git -C "$source_root" rev-parse HEAD)"
    manifest="$artifact_dir/${stem}.json"
    latest_json="$artifact_dir/LATEST-OverteIOSClient.json"
    latest_text="$artifact_dir/LATEST-OverteIOSClient.txt"
    python3 - "$manifest" "$latest_json" "$latest_text" "$archive" "$archive_sha" \
        "$source_revision" "$configuration" "$sdk_suffix" "$signed_state" "$artifact_sequence" \
        "$(xcodebuild -version | tr '\n' ' ')" "$(xcrun --sdk "$sdk_name" --show-sdk-version)" \
        "$provisioned_state" "$application_identifier" "$get_task_allow" \
        "$symbols_archive" "$symbols_sha" "$app_uuid" <<'PY'
import json
import pathlib
import sys

manifest_name, latest_name, latest_text_name, archive_name, digest, revision, configuration, platform, signed, sequence, xcode, sdk, provisioned, application_identifier, get_task_allow, symbols_name, symbols_digest, binary_uuid = sys.argv[1:]
archive = pathlib.Path(archive_name)
manifest = pathlib.Path(manifest_name)
payload = {
    "schemaVersion": 1,
    "product": "overte-ios-integrated-client",
    "buildNumber": int(sequence),
    "artifact": archive.name,
    "manifest": manifest.name,
    "sha256": digest,
    "sourceRevision": revision,
    "platform": platform,
    "architecture": "arm64",
    "configuration": configuration,
    "xcode": xcode.strip(),
    "sdk": sdk,
    "signed": signed == "true",
    "requiresSigning": platform == "iphoneos" and signed != "true",
    "signing": {
        "embeddedProvisioningProfile": provisioned == "true",
        "applicationIdentifier": application_identifier or None,
        "getTaskAllow": None if get_task_allow == "null" else get_task_allow == "true",
    },
    "debugSymbols": None if not symbols_name else {
        "artifact": pathlib.Path(symbols_name).name,
        "sha256": symbols_digest,
        "uuid": binary_uuid,
        "format": "dSYM",
        "architecture": "arm64",
    },
    "windowsVm": {
        "sharedFolderRelativePath": archive.name,
        "verifyCommand": f"certutil -hashfile {archive.name} SHA256",
    },
}
manifest.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
pathlib.Path(latest_name).write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
pathlib.Path(latest_text_name).write_text(archive.name + "\n", encoding="utf-8")
PY
    note "Created numbered integrated client artifact: $archive"
    if [[ -n "$symbols_archive" ]]; then
        note "Created matching integrated client dSYM artifact: $symbols_archive"
    fi
    note "Created manifest and Windows VM transfer metadata: $manifest, $latest_json, $latest_text"
}

run_clean() {
    case "$build_dir" in
        "$source_root"/build-ios/simulator|"$source_root"/build-ios/device|"$source_root"/build-ios/custom-*) ;;
        *) fail "refusing to clean unrecognized directory: $build_dir" ;;
    esac
    if ((confirm_clean == 0)); then
        note "Resolved build directory: $build_dir"
        note "Run again with --confirm to remove it."
        return
    fi
    [[ -e "$build_dir" ]] || {
        note "Build directory does not exist: $build_dir"
        return
    }
    rm -rf -- "$build_dir"
    note "Removed build directory: $build_dir"
}

case "$command_name" in
    doctor) run_doctor ;;
    bootstrap) run_bootstrap ;;
    deps) resolve_dependencies ;;
    configure) configure_project ;;
    build) build_project ;;
    test) run_tests ;;
    package) run_package ;;
    package-client) run_package_client ;;
    clean) run_clean ;;
    help|-h|--help) usage ;;
    *)
        usage >&2
        fail "unknown command: $command_name"
        ;;
esac
