// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from'node:test';import assert from'node:assert/strict';import{deflateSync}from'node:zlib';import vm from'node:vm';import{readFile}from'node:fs/promises';import{createHash}from'node:crypto';
import{readEmbeddingCanvasReady,qualifyEmbeddingCanvasState,qualifyEmbeddingComposedPng,observeEmbeddingComposedReady,pngCrc32}from'./fullscreen-embedding-composed-ready.mjs';
const state=()=>({connected:true,currentCanvas:true,visible:true,density:1.6666666269302368,inner:{width:1113,height:1108},bounds:{x:316.5,y:219.69,width:480,height:705.99},ack:{revision:1,frameSequence:1,sequence:2,displayed:true},navigation:{action:'open',sequence:1}});
const chunk=(name,data)=>{const tag=Buffer.from(name),n=Buffer.alloc(4),crc=Buffer.alloc(4);n.writeUInt32BE(data.length);crc.writeUInt32BE(pngCrc32(Buffer.concat([tag,data])));return Buffer.concat([n,tag,data,crc]);};
const png=(pixel=[40,80,100,255],filter=0,color=6,badLast=false,extraRaw=false)=>{const width=8,height=8,channels=color===6?4:3,header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=color;const row=Buffer.from(Array.from({length:width},()=>pixel.slice(0,channels)).flat()),raw=Buffer.alloc((row.length+1)*height),paeth=(a,b,c)=>{const p=a+b-c,da=Math.abs(p-a),db=Math.abs(p-b),dc=Math.abs(p-c);return da<=db&&da<=dc?a:db<=dc?b:c;};for(let y=0;y<height;y++){const at=y*(row.length+1);raw[at]=badLast&&y===height-1?5:filter;for(let x=0;x<row.length;x++){const a=x>=channels?row[x-channels]:0,b=y?row[x]:0,c=y&&x>=channels?row[x-channels]:0,predict=filter===0?0:filter===1?a:filter===2?b:filter===3?Math.floor((a+b)/2):paeth(a,b,c);raw[at+1+x]=(row[x]-predict)&255;}}return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(extraRaw?Buffer.concat([raw,Buffer.from([0])]):raw)),chunk('IEND',Buffer.alloc(0))]);};
test('actual source-bound callback reads only current own canvas/ACK/native density; no event/focus/scroll/style operations',()=>{
 const e={isConnected:true,getBoundingClientRect:()=>state().bounds},h={isConnected:true,querySelector:()=>e},c=vm.createContext({window:{__fullscreenTablet:{host:h,sent:[{action:'open',sequence:1},{action:'frameAck',displayed:true,revision:1,frameSequence:1,sequence:2,password:'secret'}]}},document:{visibilityState:'visible'},devicePixelRatio:state().density,innerWidth:1113,innerHeight:1108});vm.runInContext('function read(e){return ('+readEmbeddingCanvasReady.toString()+')(e);}',c);const r=JSON.parse(JSON.stringify(c.read(e)));assert.deepEqual(r,state());assert(!JSON.stringify(r).includes('secret'));assert.doesNotMatch(readEmbeddingCanvasReady.toString(),/dispatchEvent|\.click\(|\.focus\(|scrollIntoView|setAttribute|\.style|requestFullscreen/);
});
test('original CPU pixel alone does not prove composed output; blank/wrong/transparent actual screenshot rejects',()=>{
 for(const color of [2,6])for(let filter=0;filter<=4;filter++)assert.deepEqual(qualifyEmbeddingComposedPng(png([40,80,100,255],filter,color)).center,[40,80,100,255]);for(const pixel of [[255,255,255,255],[40,80,100,0],[40,81,100,255]])assert.throws(()=>qualifyEmbeddingComposedPng(png(pixel)));assert.throws(()=>qualifyEmbeddingComposedPng(Buffer.alloc(32)));const huge=png();huge.writeUInt32BE(4097,16);huge.writeUInt32BE(pngCrc32(huge.subarray(12,29)),29);assert.throws(()=>qualifyEmbeddingComposedPng(huge));const deep=png();deep[24]=16;deep.writeUInt32BE(pngCrc32(deep.subarray(12,29)),29);assert.throws(()=>qualifyEmbeddingComposedPng(deep));assert.throws(()=>qualifyEmbeddingComposedPng(new Uint8Array(4*1024*1024+1)));
});
test('actual visible/owned/frame/quality bounds required without scrolling; old pending/replaced/missing-owner negatives refuse',()=>{
 assert.deepEqual(qualifyEmbeddingCanvasState(state()),state());for(const change of [{visible:false},{connected:false},{currentCanvas:false},{density:NaN},{bounds:{...state().bounds,x:-1}},{bounds:{...state().bounds,height:1500}},{ack:null},{ack:{...state().ack,displayed:false}},{navigation:null},{navigation:{action:'home',sequence:3}},{navigation:{action:'open',sequence:0}},{ack:{...state().ack,sequence:1}}])assert.throws(()=>qualifyEmbeddingCanvasState({...state(),...change}));
});
test('single public screenshot with no scrolling/viewport expansion then identical actual owner/frame/native density; not hit-ready or input retry',async()=>{
 const calls=[],canvas={evaluate:async fn=>{assert.equal(fn,readEmbeddingCanvasReady);calls.push('read');return state();},screenshot:async options=>{calls.push(options);return png();}};const r=await observeEmbeddingComposedReady(canvas);assert.equal(r.hitTargetQualified,false);assert.deepEqual(calls,['read',{type:'png',scrollIntoView:false,captureBeyondViewport:false,fromSurface:true,omitBackground:false},'read']);assert.deepEqual(r.before,r.after);
});
test('before refusal skips screenshot; screenshot error propagates, late density/layout/frame replacement never admits',async()=>{
 let calls=0;const bad={evaluate:async()=>({...state(),visible:false}),screenshot:async()=>{calls++;return png();}};await assert.rejects(observeEmbeddingComposedReady(bad));assert.equal(calls,0);const failure=new Error('original-screenshot');await assert.rejects(observeEmbeddingComposedReady({evaluate:async()=>state(),screenshot:async()=>{throw failure;}}),e=>e===failure);
 for(const field of ['density','bounds','ack']){let n=0;const changed={evaluate:async()=>++n===1?state():({...state(),[field]:field==='density'?1:field==='bounds'?{...state().bounds,x:317}:{...state().ack,sequence:3}}),screenshot:async()=>png()};await assert.rejects(observeEmbeddingComposedReady(changed));}
});
test('driver amendment strips to exact passive diagnostic source; original physical click/wire/API assertions/case deadline unchanged',async()=>{
 let driver=await readFile(new URL('./fullscreen-embedding-stock.mjs',import.meta.url),'utf8');const archive=",{privatePngPath:path.join(output,delegated?'delegated-positive-composed.png':'embedding-negative-composed.png')}";assert.equal(driver.split(archive).length-1,1);driver=driver.replace(archive,'');assert.equal(createHash('sha256').update(driver).digest('hex'),'c007015b8a501c6c167b969a8bacd7b1e74365234420b7273bb7edc2a03c4f7a');assert(driver.includes('witness.composedReadiness=await observeEmbeddingComposedReady(canvas);'));driver=driver.replace("import {observeEmbeddingComposedReady} from './fullscreen-embedding-composed-ready.mjs';\n",'').replace('witness.composedReadiness=await observeEmbeddingComposedReady(canvas);','');assert.equal(createHash('sha256').update(driver).digest('hex'),'af12ccf3f6e6dc3094ea418b2a796efb3a83358552afa6631192663c46bf110a');assert(driver.includes('await page.mouse.click(bounds.x+bounds.width/2,bounds.y+bounds.height/2)'));assert(driver.includes('qualifyCanvasWire(await proof(frame),bounds,await frame.evaluate(()=>window.__ownedFullscreenPointer))'));
});

test('bounded original-helper timeout consumes late screenshot completion and refuses new reads/decoding without input or retries',async()=>{
 let expire,resolveShot,started,reads=0,decoded=0,cleared=0;const screenshotStarted=new Promise(resolve=>{started=resolve;});const canvas={evaluate:async()=>{reads++;return state();},screenshot:()=>new Promise(resolve=>{resolveShot=resolve;started();})};const c=vm.createContext({assert,Promise,Error,readEmbeddingCanvasReady,qualifyEmbeddingCanvasState,qualifyEmbeddingComposedPng:b=>{decoded++;return qualifyEmbeddingComposedPng(b);},setTimeout:(fn,ms)=>{assert.equal(ms,10000);expire=fn;return 1;},clearTimeout:()=>{cleared++;}});const fn=vm.runInContext('('+observeEmbeddingComposedReady.toString()+')',c),pending=fn(canvas);await screenshotStarted;expire();await assert.rejects(pending,/bounded compositor-output setup deadline/);assert.equal(cleared,1);assert.equal(reads,1);resolveShot(png());await Promise.resolve();await Promise.resolve();assert.equal(decoded,0);assert.equal(reads,1);
});

test('strict complete screenshot stream rejects late row-filter, CRC, trailing and inflated-length faults before accepting center',()=>{
 const badCrc=png();badCrc[29]^=1;for(const b of [badCrc,Buffer.concat([png(),Buffer.from([0])]),png([40,80,100,255],0,6,true),png([40,80,100,255],0,6,false,true)])assert.throws(()=>qualifyEmbeddingComposedPng(b));
});
test('exact installed public Puppeteer screenshot option branches avoid scroll/background/viewport mutation for this source-bound recipe',async()=>{
 const base=new URL('../../node_modules/puppeteer-core/',import.meta.url),get=p=>readFile(new URL(p,base),'utf8'),element=await get('src/api/ElementHandle.ts'),page=await get('src/api/Page.ts'),cdp=await get('src/cdp/Page.ts');assert.equal(createHash('sha256').update(element).digest('hex'),'50b86666e922010f2d247e0229eae325eeb23addf832b62a1e4917089f6801db');assert.equal(createHash('sha256').update(page).digest('hex'),'b39b1cc7c282286a6544474684f365dd765d0127e9d12c5fe9d1e42ab65c2ebd');assert.equal(createHash('sha256').update(cdp).digest('hex'),'80f5d0005402bc2501676a0ddfe8709c3bd5822ed1b19424c565690c2e0abc97');assert(element.includes('const {scrollIntoView = true, clip} = options;'));assert(element.includes('if (scrollIntoView) {\n      await this.scrollIntoViewIfNeeded();'));assert(page.includes('if (options.clip) {\n      if (options.fullPage)'));assert(cdp.includes('if (omitBackground &&'));assert(cdp.includes("'Page.captureScreenshot'"));
});

test('actual production send body provides command ownership without inventing ACK navigation metadata',async()=>{
 const source=await readFile(new URL('../../src/tablet.ts',import.meta.url),'utf8'),marker='    private send(value:Record<string,unknown>):void {',end='    private show(visible:boolean):void {';assert.equal(source.split(marker).length,2);const rest=source.split(marker)[1];assert.equal(rest.split(end).length,2);const body=rest.split(end)[0].trim();assert(body.endsWith('}'));
 const send=vm.runInNewContext('(function(value){'+body.slice(0,-1)+'})'),sent=[],owner={connected:true,disposed:false,revision:1,sequence:0,visible:true,displayedFrameSequence:0,generation:0,clearPointer(){},options:{send:v=>sent.push(v)}};
 send.call(owner,{action:'open'});send.call(owner,{action:'frameAck',frameSequence:1,displayed:true});assert.equal(Object.hasOwn(sent[1],'navigationSequence'),false);assert.equal(sent[0].sequence,1);assert.equal(sent[1].sequence,2);
 const element={isConnected:true,getBoundingClientRect:()=>state().bounds},host={isConnected:true,querySelector:()=>element},context=vm.createContext({window:{__fullscreenTablet:{host,sent}},document:{visibilityState:'visible'},devicePixelRatio:state().density,innerWidth:1113,innerHeight:1108}),read=vm.runInContext('('+readEmbeddingCanvasReady.toString()+')',context);
 const snapshot=JSON.parse(JSON.stringify(read(element)));assert.deepEqual(qualifyEmbeddingCanvasState(snapshot),state());assert.throws(()=>{assert(Number.isSafeInteger(snapshot.ack.navigationSequence)&&snapshot.ack.navigationSequence>=1);},'Exact old assumption rejects actual production ACK');
 send.call(owner,{action:'home'});assert.throws(()=>qualifyEmbeddingCanvasState(JSON.parse(JSON.stringify(read(element)))));send.call(owner,{action:'frameAck',frameSequence:1,displayed:true});assert.throws(()=>qualifyEmbeddingCanvasState(JSON.parse(JSON.stringify(read(element)))));
 send.call(owner,{action:'open'});assert.throws(()=>qualifyEmbeddingCanvasState(JSON.parse(JSON.stringify(read(element)))),'A prior displayed ACK cannot own a later open');send.call(owner,{action:'frameAck',frameSequence:1,displayed:true});const fresh=JSON.parse(JSON.stringify(read(element)));assert.equal(qualifyEmbeddingCanvasState(fresh).navigation.sequence,5);assert.equal(fresh.ack.sequence,6);
});
