// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {deflateSync} from 'node:zlib';import {mkdtemp,readFile,stat,chmod,rm,symlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';
import {qualifyReviewedScreenshotICC,expectedEmbeddingScreenshotColor,preservePrivateComposedPng,REVIEWED_SCREENSHOT_ICC_SHA256} from './fullscreen-screenshot-profile.mjs';
import {qualifyEmbeddingComposedPng,pngCrc32,observeEmbeddingComposedReady} from './fullscreen-embedding-composed-ready.mjs';
// Fixed generated RGB matrix/TRC profile only, no captured screenshot or participant/device data.
const reviewedProfile=Buffer.from('AAAB4AAAAAAEMAAAbW50clJHQiBYWVogB+AAAQABAAAAAAAAYWNzcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAPbWAAEAAAAA0y0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJZGVzYwAAAPAAAABUclhZWgAAAUQAAAAUZ1hZWgAAAVgAAAAUYlhZWgAAAWwAAAAUd3RwdAAAAYAAAAAUclRSQwAAAZQAAAAQZ1RSQwAAAZQAAAAQYlRSQwAAAZQAAAAQY3BydAAAAaQAAAA8bWx1YwAAAAAAAAABAAAADGVuVVMAAAA4AAAAHABzAFIARwBCACAARwBhAG0AdQB0ACAAdwBpAHQAaAAgADIALgAyACAAVAByAGEAbgBzAGYAZQByWFlaIAAAAAAAAG+iAAA49QAAA5BYWVogAAAAAAAAYpkAALeFAAAY2lhZWiAAAAAAAAAkoAAAD4QAALbPWFlaIAAAAAAAAPbWAAEAAAAA0y1wYXJhAAAAAAAAAAAAAjMzbWx1YwAAAAAAAAABAAAADGVuVVMAAAAgAAAAHABHAG8AbwBnAGwAZQAgAEkAbgBjAC4AIAAyADAAMQA2','base64'),sha=b=>createHash('sha256').update(b).digest('hex');
const chunk=(name,data)=>{const tag=Buffer.from(name),n=Buffer.alloc(4),crc=Buffer.alloc(4);n.writeUInt32BE(data.length);crc.writeUInt32BE(pngCrc32(Buffer.concat([tag,data])));return Buffer.concat([n,tag,data,crc]);};
function png(pixel=[40,80,100,255],metadata=[],afterData=[]){const header=Buffer.alloc(13);header.writeUInt32BE(8);header.writeUInt32BE(8,4);header[8]=8;header[9]=6;const raw=Buffer.alloc(33*8);for(let y=0;y<8;y++)for(let x=0;x<8;x++)Buffer.from(pixel).copy(raw,y*33+1+x*4);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),...metadata,chunk('IDAT',deflateSync(raw)),...afterData,chunk('IEND',Buffer.alloc(0))]);}
const iccp=(profile=reviewedProfile,{name='Skia',method=0,trailing=false}={})=>chunk('iCCP',Buffer.concat([Buffer.from(name+'\0','latin1'),Buffer.from([method]),deflateSync(profile),...(trailing?[Buffer.from([1])]:[])]));
const state=()=>({connected:true,currentCanvas:true,visible:true,density:1.6666666269302368,inner:{width:1113,height:1108},bounds:{x:316.5,y:219.69,width:480,height:705.99},ack:{revision:1,frameSequence:1,sequence:2,displayed:true},navigation:{action:'open',sequence:1}});
test('entire actual generated ICC profile and exact matrix/TRCs bind the source color to precise gamma22 integer encoding',()=>{assert.equal(sha(reviewedProfile),REVIEWED_SCREENSHOT_ICC_SHA256);const profile=qualifyReviewedScreenshotICC(reviewedProfile);assert.equal(profile.gammaFixed16,144179);assert.deepEqual(profile.matrixFixed16,[[0x6fa2,0x38f5,0x390],[0x6299,0xb785,0x18da],[0x24a0,0xf84,0xb6cf]]);assert.deepEqual(expectedEmbeddingScreenshotColor(reviewedProfile).expected,[44,81,100,255]);assert.deepEqual(expectedEmbeddingScreenshotColor().expected,[40,80,100,255]);for(const offset of [0,8,12,16,20,36,128,136,324,344,364,384,404]){const bad=Buffer.from(reviewedProfile);bad[offset]^=1;assert.throws(()=>qualifyReviewedScreenshotICC(bad),/Unsupported/);}for(const bytes of [Buffer.alloc(479),Buffer.alloc(481),Buffer.alloc(480)])assert.throws(()=>qualifyReviewedScreenshotICC(bytes));});
test('known actual iCCP computes expected encoding; name is not trusted and raw-sRGB/tagged near misses fail exactly',()=>{for(const name of ['Skia','Reviewed generic RGB']){const proof=qualifyEmbeddingComposedPng(png([44,81,100,255],[iccp(reviewedProfile,{name})]));assert.deepEqual(proof.authoredCenter,[40,80,100,255]);assert.deepEqual(proof.expectedEncodedCenter,[44,81,100,255]);assert.equal(proof.colorEncoding.profileSHA256,REVIEWED_SCREENSHOT_ICC_SHA256);}assert.throws(()=>qualifyEmbeddingComposedPng(png([44,81,100,255])));for(const value of [[40,80,100,255],[43,81,100,255],[45,81,100,255],[44,80,100,255],[44,82,100,255],[44,81,99,255],[44,81,101,255],[44,81,100,254]])assert.throws(()=>qualifyEmbeddingComposedPng(png(value,[iccp()])));assert.deepEqual(qualifyEmbeddingComposedPng(png([40,80,100,255],[chunk('sRGB',Buffer.from([0]))])).center,[40,80,100,255]);});
test('unsupported/duplicate/late/contradictory/malformed profiles and bounded inflate bombs never become an alternate color acceptance',()=>{const wrong=Buffer.from(reviewedProfile);wrong[344]^=1;for(const metadata of [[iccp(wrong)],[iccp(),iccp()],[iccp(),chunk('sRGB',Buffer.from([0]))],[chunk('sRGB',Buffer.from([0])),iccp()],[iccp(reviewedProfile,{name:' bad'})],[iccp(reviewedProfile,{name:'bad  name'})],[iccp(reviewedProfile,{method:1})],[iccp(reviewedProfile,{trailing:true})],[iccp(Buffer.alloc(4096))],[chunk('sRGB',Buffer.from([4]))]])assert.throws(()=>qualifyEmbeddingComposedPng(png([44,81,100,255],metadata)));assert.throws(()=>qualifyEmbeddingComposedPng(png([44,81,100,255],[],[iccp()])));for(const name of ['gAMA','cHRM','cICP','mDCV','cLLI','sBIT','tRNS','acTL','fcTL','fdAT'])assert.throws(()=>qualifyEmbeddingComposedPng(png([40,80,100,255],[chunk(name,Buffer.from([0]))])));});
test('private exact screenshot bytes are retained before a strict color failure, O_EXCL0600 never overwrites existing or symlink targets',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'overte-composed-private-test-'));await chmod(directory,0o700);try{const filename=path.join(directory,'embedding-negative-composed.png'),bytes=png([43,81,100,255],[iccp()]);await assert.rejects(observeEmbeddingComposedReady({evaluate:async()=>state(),screenshot:async()=>bytes},{privatePngPath:filename}));assert.deepEqual(await readFile(filename),bytes);assert.equal((await stat(filename)).mode&0o777,0o600);await assert.rejects(preservePrivateComposedPng(png(),filename),e=>e.code==='EEXIST');assert.deepEqual(await readFile(filename),bytes);const link=path.join(directory,'delegated-positive-composed.png');await symlink(filename,link);await assert.rejects(preservePrivateComposedPng(png(),link));assert.deepEqual(await readFile(filename),bytes);await assert.rejects(preservePrivateComposedPng(png(),path.join(directory,'unreviewed-name.png')));await assert.rejects(preservePrivateComposedPng(new Uint8Array(4*1024*1024+1),link));await chmod(directory,0o755);await assert.rejects(preservePrivateComposedPng(png(),filename));}finally{await rm(directory,{recursive:true,force:true});}});
test('public screenshot, color proof and archive preserve original API error identity and current owner/deadline ordering',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'overte-composed-private-test-'));await chmod(directory,0o700);try{const filename=path.join(directory,'delegated-positive-composed.png'),failure=Error('original-public-screenshot');await assert.rejects(observeEmbeddingComposedReady({evaluate:async()=>state(),screenshot:async()=>{throw failure;}},{privatePngPath:filename}),e=>e===failure);await assert.rejects(stat(filename),e=>e.code==='ENOENT');let screenshots=0;await assert.rejects(observeEmbeddingComposedReady({evaluate:async()=>({...state(),visible:false}),screenshot:async()=>{screenshots++;return png();}},{privatePngPath:filename}));assert.equal(screenshots,0);await assert.rejects(stat(filename),e=>e.code==='ENOENT');const proof=await observeEmbeddingComposedReady({evaluate:async()=>state(),screenshot:async()=>png([44,81,100,255],[iccp()])},{privatePngPath:filename});assert.equal(proof.hitTargetQualified,false);assert.equal(proof.composed.colorEncoding.profileSHA256,REVIEWED_SCREENSHOT_ICC_SHA256);assert.deepEqual(proof.before,proof.after);assert.equal(sha(await readFile(filename)),proof.composed.sha256);}finally{await rm(directory,{recursive:true,force:true});}});
