// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from'node:test';import assert from'node:assert/strict';import vm from'node:vm';import{readFile}from'node:fs/promises';import{createHash}from'node:crypto';
import{installEmbeddingPointerDiagnostic,readEmbeddingPointerDiagnostic}from'./fullscreen-embedding-pointer-diagnostic.mjs';
test('actual passive observer separates canvas/foreign iframe and captures exact trusted real-event geometry without dispatch/focus/values',()=>{
 class Node{};const canvas=new Node,keyboard=new Node,iframe=new Node,host=new Node;canvas.getBoundingClientRect=()=>({x:10,y:20,width:480,height:706});host.isConnected=true;host.contains=e=>e===canvas||e===keyboard;host.querySelector=s=>s==='canvas'?canvas:keyboard;const listeners={};const c=vm.createContext({Node,window:{__fullscreenTablet:{sent:[{action:'frameAck',displayed:true}]}},document:{visibilityState:'visible',getElementById:id=>id==='fullscreen-tablet-owner'?host:iframe,elementFromPoint:()=>canvas,addEventListener:(t,f,o)=>{assert.equal(o.capture,true);assert.equal(o.passive,true);listeners[t]=f;}}});vm.runInContext('('+installEmbeddingPointerDiagnostic.toString()+')()',c);
 listeners.pointerdown({type:'pointerdown',target:canvas,isTrusted:true,button:0,buttons:1,pointerId:0,isPrimary:true,pointerType:'mouse',clientX:250,clientY:373});listeners.pointerup({type:'pointerup',target:iframe,isTrusted:true,button:0,buttons:0,pointerId:0,isPrimary:true,pointerType:'mouse',clientX:250,clientY:373});const d=JSON.parse(JSON.stringify(c.window.__embeddingPointerDiagnostic));assert.equal(d.events[0].eventTargetCanvas,true);assert.equal(d.events[0].hitCanvas,true);assert.equal(d.events[0].pointerId,0);assert.equal(d.events[1].eventTargetIframe,true);assert.equal(d.events[1].eventTargetCanvas,false);assert.equal(d.events[0].displayedAck,true);
 for(let i=0;i<100;i++)listeners.pointermove({type:'pointermove',target:canvas,clientX:NaN,clientY:NaN});assert.equal(c.window.__embeddingPointerDiagnostic.events.length,64);assert.equal(c.window.__embeddingPointerDiagnostic.censored,true);
});
test('private wire readback projects only actual inputs and fixed fields, bounds and missing input remain honest',()=>{
 const c=vm.createContext({window:{__embeddingPointerDiagnostic:{events:[],censored:false},__fullscreenTablet:{sent:[]}}});vm.runInContext('function read(){return ('+readEmbeddingPointerDiagnostic.toString()+')();}',c);assert.equal(c.read().wire.length,0);
 c.window.__fullscreenTablet.sent=Array.from({length:70},(_,i)=>({action:'input',event:'move',revision:1,frameSequence:1,x:.5,y:.5,privateText:'secret',sequence:i}));const d=JSON.parse(JSON.stringify(c.read()));assert.equal(d.wire.length,64);assert.equal(d.wireCensored,true);assert(!JSON.stringify(d).includes('secret'));
});
test('composed driver recovers exact reviewed passive and original bodies; observer saves diagnostics BEFORE unchanged wire refusal',async()=>{
 let observed=await readFile(new URL('./fullscreen-embedding-stock.mjs',import.meta.url),'utf8');
 const historicalBindingChanges=[{"before": "import {SOURCE_PINS,sha,fixtureCallbacks,", "after": "import {SOURCE_PINS,AUTHORED_FIXTURE_SOURCE,sha,fixtureCallbacks,"}, {"before": "path.join(root,'tests/tablet-fullscreen.browser.spec.ts')", "after": "path.join(root,AUTHORED_FIXTURE_SOURCE)"}, {"before": "Two additional actual embedding denial/delegation cases; original four bodies not run/replaced and stock HTTP-header negative remains failed", "after": "Two actual embedding cases with byte-identical historical authored callbacks; corrected active main spec separately source-pinned; historical stock HTTP-header failure retained"}, {"before": "registeredBodiesUnchanged:true", "after": "historicalOriginalBodiesUnchanged:true,activeRegisteredSpecChanged:true"}];
 for(const change of historicalBindingChanges){assert.equal(observed.split(change.after).length-1,1);observed=observed.replace(change.after,change.before);}
 assert.equal(createHash('sha256').update(observed).digest('hex'),'a55ed7e614716358e31c8f2ce94b3ec1855c80535fef3fc6b45966d867d000a7');
 const archive=",{privatePngPath:path.join(output,delegated?'delegated-positive-composed.png':'embedding-negative-composed.png')}";assert.equal(observed.split(archive).length-1,1);const source=observed.replace(archive,'');assert.equal(createHash('sha256').update(source).digest('hex'),'c007015b8a501c6c167b969a8bacd7b1e74365234420b7273bb7edc2a03c4f7a');
 const reviewedComposedAnchors=["import {observeEmbeddingComposedReady} from './fullscreen-embedding-composed-ready.mjs';\n",'witness.composedReadiness=await observeEmbeddingComposedReady(canvas);'];
 let passiveSource=source;
 for(const anchor of reviewedComposedAnchors){assert.equal(passiveSource.split(anchor).length-1,1,'Exact reviewed composed readiness anchor must occur once');passiveSource=passiveSource.replace(anchor,'');}
 assert.equal(createHash('sha256').update(passiveSource).digest('hex'),'af12ccf3f6e6dc3094ea418b2a796efb3a83358552afa6631192663c46bf110a');
 const stripped=passiveSource.replace("import {installEmbeddingPointerDiagnostic,readEmbeddingPointerDiagnostic} from './fullscreen-embedding-pointer-diagnostic.mjs';\n",'').replace('  await page.evaluate(installEmbeddingPointerDiagnostic);await frame.evaluate(installEmbeddingPointerDiagnostic);\n','').replace('witness.pointerDiagnostic={parent:await page.evaluate(readEmbeddingPointerDiagnostic),child:await frame.evaluate(readEmbeddingPointerDiagnostic),requestedBounds:bounds};','');assert.equal(createHash('sha256').update(stripped).digest('hex'),'7fa23ae577f9fa52d5de8755c4b75d05877a14cd3d94f26c5abdfb38e9fbed8e');
 assert(source.indexOf('witness.pointerDiagnostic=')<source.indexOf('qualifyCanvasWire(await proof(frame)'));
 assert.doesNotMatch(installEmbeddingPointerDiagnostic.toString()+readEmbeddingPointerDiagnostic.toString(),/dispatchEvent|\.click\(|\.focus\(|setAttribute|requestFullscreen|setTimeout|\.value|textContent|location/);
});
