// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import {OriginalImageErrorCollector,classifyAssetError}from './hub-original-image-errors.mjs';
function response({url='http://localhost:8095/api/assets/session?url=https%3A%2F%2Fassets.example%2Fimage.dds',status=502,message='Asset server returned HTTP 404.',length=true,body,headers}={}){const bytes=Buffer.from(JSON.stringify({error:message}));return{status:()=>status,url:()=>url,headers:()=>headers??{'content-type':'application/json',...(length?{'content-length':String(bytes.length)}:{})},body:body??(()=>bytes)};}
test('fixed classifications never serialize raw unknown errors',()=>{assert.equal(classifyAssetError('Asset server returned HTTP 404.'),'upstream-http');assert.equal(classifyAssetError('The asset origin is not enabled by the gateway administrator.'),'origin-refused');assert.equal(classifyAssetError('secret URL https://private.example'),'unknown');});
test('reads already received body once and retains hashes/fixed enums only',async()=>{let reads=0;const c=new OriginalImageErrorCollector('http://localhost:8095');c.observe(response({body:()=>{reads++;return Buffer.from('{"error":"fetch failed"}');},headers:{'content-type':'application/json','content-length':'24'}}));const d=await c.finish();assert.equal(reads,1);assert.equal(d.entries[0].category,'upstream-network');assert.equal(JSON.stringify(d).includes('assets.example'),false);assert.match(d.entries[0].urlSHA256,/^[a-f0-9]{64}$/);});
test('unknown length is refused before reading',async()=>{let reads=0;const c=new OriginalImageErrorCollector('http://localhost:8095');c.observe(response({length:false,body:()=>{reads++;return Buffer.alloc(0);}}));const d=await c.finish();assert.equal(reads,0);assert.equal(d.entries[0].category,'body-unbounded');});
test('oversized declared body never read; mismatched/invalid JSON is censored',async()=>{let reads=0;const c=new OriginalImageErrorCollector('http://localhost:8095');c.observe(response({headers:{'content-type':'application/json','content-length':'8193'},body:()=>{reads++;}}));c.observe(response({headers:{'content-type':'application/json','content-length':'2'},body:()=>Buffer.from('bad')}));const d=await c.finish();assert.equal(reads,0);assert.deepEqual(d.entries.map(e=>e.category),['body-unbounded','body-invalid']);});
test('rejects foreign response, unrelated route/status and nonoriginal image',async()=>{const c=new OriginalImageErrorCollector('http://localhost:8095');for(const options of [{status:403},{url:'https://foreign.example/api/assets/session?url=https%3A%2F%2Fa%2Fi.png'},{url:'http://localhost:8095/api/assets/session?url=https%3A%2F%2Fa%2Fi.ktx'},{url:'http://localhost:8095/api/assets/session?url=https%3A%2F%2Fa%2Fi.png&extra=1'}])c.observe(response(options));assert.equal((await c.finish()).accepted,0);});
test('bounded completion drops late body publication',async()=>{let release;const c=new OriginalImageErrorCollector('http://localhost:8095',{deadlineMs:10});c.observe(response({body:()=>new Promise(resolve=>release=resolve)}));const d=await c.finish();const saved=JSON.stringify(d);release(Buffer.from('{"error":"fetch failed"}'));await new Promise(resolve=>setImmediate(resolve));assert.equal(JSON.stringify(d),saved);assert.equal(c.closed,true);});
test('pending queue and request count are bounded without retries',async()=>{const c=new OriginalImageErrorCollector('http://localhost:8095',{deadlineMs:10});for(let n=0;n<200;n++)c.observe(response({body:()=>new Promise(()=>{})}));assert(c.active<=4);assert(c.queue.length<=32);const d=await c.finish();assert(d.accepted<=36);assert(d.dropped>0);});
test('gateway JSON header measures encoded bytes without changing its body',async()=>{
 const {readFile}=await import('node:fs/promises');const {runInNewContext}=await import('node:vm');
 const source=await readFile(new URL('../../gateway/server.mjs',import.meta.url),'utf8');const line=source.split('\n').find(v=>v.startsWith('const json = '));
 assert(line);const call=runInNewContext(line+';json',{Buffer});let code,headers,body;
 const value={error:'é👋'};call({writeHead:(c,h)=>{code=c;headers=h;},end:v=>body=v},502,value);
 assert.equal(code,502);assert.equal(body,JSON.stringify(value));assert.equal(headers['content-length'],Buffer.byteLength(body));assert.equal(headers['cache-control'],'no-store');
});
test('existing failure collection and original world/fluid gates remain in caller',async()=>{
 const {readFile}=await import('node:fs/promises');const source=await readFile(new URL('./public-hub.mjs',import.meta.url),'utf8');
 assert(source.includes("report.failedResources.push({status:response.status(),url:response.url()});originalImageErrors.observe(response);"));
 assert(source.indexOf('report.originalImageErrors=await originalImageErrors.finish();')>source.indexOf('finally{'));
 assert(source.includes("assert(report.movementMeters>0.5"));assert(source.includes('Actual loaded-world, walking and reconnect measurements must meet30FPS, p95<=66.7ms and no steady stall>250ms'));
 assert(!source.includes('await originalImageErrors.finish();\n  report.completed=true'));
});
