// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {configureHubBitmapCohort,projectHubBitmapCohort,attestHubBitmapCohort,compareHubBitmapCohorts} from './hub-bitmap-cohort.mjs';
const env=()=>({OVERTE_LAB_REQUIRE_FLUID:'1',OVERTE_LAB_RECONNECT:'1',OVERTE_LAB_BROWSER_DISPLAY:':0',OVERTE_LAB_CHROMIUM:'/authored/chromium'});
const snapshot=enabled=>({loadingModels:0,queuedModels:0,compilingGraphics:0,drawingBufferWidth:1280,drawingBufferHeight:800,bitmapUpload:enabled?{enabled:true,roots:1,converted:1,fallbacks:0,unsupported:0,capacityFallbacks:0,activeRoots:0,peakRoots:1,requests:1,hits:0,created:1,closed:0,evictions:0,cancelled:0,failed:0,closeFailures:0,peakActive:1,invalidations:0,active:0,pending:0,readers:0,retainedEntries:1,liveEntries:1,bytes:64,leases:1}:{enabled:false,roots:0,converted:0,fallbacks:0,unsupported:0,capacityFallbacks:0,activeRoots:0,peakRoots:0}});
test('default is off and cannot silently opt in or rewrite caller configuration',()=>{const e=env(),before={...e};assert.equal(configureHubBitmapCohort(undefined,e),null);assert.equal(configureHubBitmapCohort('',e),null);assert.deepEqual(e,before);assert.throws(()=>configureHubBitmapCohort('unknown',e));assert.equal(configureHubBitmapCohort('baseline',e).mode,'baseline');assert.throws(()=>configureHubBitmapCohort('bitmap',e));e.OVERTE_LAB_BITMAP_UPLOAD='1';assert.equal(configureHubBitmapCohort('bitmap',e).mode,'bitmap');assert.throws(()=>configureHubBitmapCohort('baseline',e));});
test('both original admissions and all four original fluid gates are mandatory, stock headed execution and diagnostic parity stay explicit',()=>{for(const key of ['OVERTE_LAB_REQUIRE_FLUID','OVERTE_LAB_RECONNECT','OVERTE_LAB_BROWSER_DISPLAY','OVERTE_LAB_CHROMIUM']){const e=env();delete e[key];assert.throws(()=>configureHubBitmapCohort('baseline',e));}for(const key of ['OVERTE_LAB_UPLOAD_PROFILE','OVERTE_LAB_RENDER_CPU_TIMING','OVERTE_LAB_RENDER_DISPATCH_ATTRIBUTION','OVERTE_LAB_TEXTURE_PREPARATION','OVERTE_LAB_SWIFTSHADER'])assert.throws(()=>configureHubBitmapCohort('baseline',{...env(),[key]:'1'}));assert.equal(configureHubBitmapCohort('baseline',{...env(),OVERTE_LAB_BROWSER:'system-firefox',OVERTE_LAB_FIREFOX:'/authored/firefox'}).mode,'baseline');});
test('uses already captured samples only, preserves actual counters and excludes private additions',()=>{const p=snapshot(true);p.bitmapUpload.privateURL='NEVER_PUBLISH';p.position={x:3};const before=JSON.stringify(p),r=projectHubBitmapCohort(p,'bitmap',2);assert.equal(r.owner.bytes,64);assert.equal(r.bindingCounters.converted,1);assert.equal(r.admissionOrdinal,2);assert(!JSON.stringify(r).includes('NEVER_PUBLISH'));assert(!JSON.stringify(r).includes('position'));assert.equal(JSON.stringify(p),before);assert.equal(projectHubBitmapCohort(snapshot(false),'baseline',1).owner,null);});
test('missing experiment, no real conversions, enlarged original memory/concurrency or ongoing model work refuses',()=>{for(const mutate of [s=>s.bitmapUpload.enabled=false,s=>s.bitmapUpload.converted=0,s=>s.bitmapUpload.created=0,s=>s.bitmapUpload.bytes=128*1024*1024+1,s=>s.bitmapUpload.active=3,s=>s.bitmapUpload.peakActive=3,s=>s.bitmapUpload.pending=17,s=>s.loadingModels=1,s=>s.compilingGraphics=1]){const s=snapshot(true);mutate(s);assert.throws(()=>projectHubBitmapCohort(s,'bitmap',1));}assert.throws(()=>projectHubBitmapCohort(snapshot(true),'baseline',1));assert.throws(()=>projectHubBitmapCohort(snapshot(false),'baseline',3));});
test('changed or missing source/distribution fails exact attestation instead of claiming tested pixels',()=>{const hash='a'.repeat(64),files=['browser-client/src/world-bitmap-upload.ts'],start={[files[0]]:hash},dist={'bundle.js':{sha256:hash,bytes:5}};assert.deepEqual(attestHubBitmapCohort(files,start,start,dist,dist),{sourceCoherent:true,distributionCoherent:true,sourceFileCount:1});assert.equal(attestHubBitmapCohort(files,start,{},dist,dist).sourceCoherent,false);assert.equal(attestHubBitmapCohort(files,start,start,dist,{'bundle.js':{sha256:hash,bytes:6}}).distributionCoherent,false);});
test('actual harness retains original physical actions, deadlines, four unchanged fluid populations and no additional sampling before their gates',async()=>{const text=await readFile(new URL('./public-hub.mjs',import.meta.url),'utf8');assert(text.includes("process.env.OVERTE_LAB_REQUIRE_FLUID==='1')assert(report.fluidMovementAcceptancePassed"));assert(text.includes('report.steadyFluidPerformance,report.walkFluidPerformance'));assert(text.includes('report.reconnectedSteadyFluidPerformance,report.reconnectedWalkFluidPerformance'));assert(text.includes("projectHubBitmapCohort(report.performance?.at(-1)"));assert(text.includes('projectHubBitmapCohort(report.reconnectedAfterMovement?.performance'));assert(text.indexOf('if(report.bitmapUploadCohort){')>text.indexOf('report.originalImageErrors='));assert(!text.includes('page.evaluate(projectHubBitmapCohort'));assert(text.includes('timeout:90000'));assert(text.includes("await page.keyboard.down('KeyW')"));});

test('paired source/viewport/density comparison preserves negative fluid outcomes and cannot assert loading or whole-Hub pixel gains',()=>{const hash='a'.repeat(64),sources={'browser-client/src/world.ts':hash},dist={'bundle.js':{sha256:hash,bytes:5}},make=mode=>({bitmapUploadCohort:{mode,attestation:{sourceCoherent:true,distributionCoherent:true},samples:[{drawingBuffer:{width:1280,height:800}},{drawingBuffer:{width:1280,height:800}}]},startSourceSHA256:sources,startDistributionManifest:dist,browserVersion:'authored-stock',viewport:{width:1280,height:800,devicePixelRatio:1},steadyFluidPerformance:{passed:false},walkFluidPerformance:{passed:false},reconnectedSteadyFluidPerformance:{passed:false},reconnectedWalkFluidPerformance:{passed:false},completed:false,fluidMovementAcceptancePassed:false});const a=make('baseline'),b=make('bitmap'),r=compareHubBitmapCohorts(a,b);assert.equal(r.bothFluidAcceptance,false);assert.equal(r.bothOriginalJourneysCompleted,false);assert.equal(r.causalLoadingGain,false);assert.equal(r.wholeHubPixelEquivalence,false);for(const mutate of [b=>b.viewport.devicePixelRatio=0.8,b=>b.bitmapUploadCohort.samples[1].drawingBuffer.width=1024,b=>b.startSourceSHA256={'browser-client/src/world.ts':'b'.repeat(64)},b=>delete b.reconnectedWalkFluidPerformance]){const changed=make('bitmap');mutate(changed);assert.throws(()=>compareHubBitmapCohorts(a,changed));}});
