// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {runInNewContext} from 'node:vm';
import {installHubUploadProfile} from './hub-upload-profile.mjs';
function fixture(){installHubUploadProfile();return globalThis.__hubUploadProfile;}
test('bone-sized repeated typed-data updates are separate from independent large static image arguments without emitting identities',()=>{
 const old=globalThis.HTMLImageElement;class Image{get naturalWidth(){return 4096;}get naturalHeight(){return 2048;}}globalThis.HTMLImageElement=Image;
 try{const observer=fixture(),bones=new Float32Array(16*16*4),image=new Image();observer.setPhase('loading');observer.record('texSubImage2D',[1,0,0,0,1,1,image],200);observer.setPhase('steady');for(let i=0;i<100;i++)observer.record('texSubImage2D',[1,0,0,0,16,16,1,1,bones],.1);const result=observer.snapshot();assert.equal(result.records,101);assert.equal(result.uniqueArgumentSourcesLowerBound,2);assert.equal(result.uniqueArgumentSourcesByKind.image,1);assert.equal(result.uniqueArgumentSourcesByKind.data,1);assert.equal(result.buckets[0].width,4096);assert.equal(result.buckets[1].width,16);assert.equal(result.buckets[1].calls,100);assert.equal(result.buckets[1].phase,'steady');assert.equal(JSON.stringify(result).includes('uuid'),false);}finally{if(old===undefined)delete globalThis.HTMLImageElement;else globalThis.HTMLImageElement=old;delete globalThis.__hubUploadProfile;}
});
test('native image intrinsic dimensions ignore foreign own width/src getter and unknown objects are never inspected',()=>{const old=globalThis.ImageBitmap;class Bitmap{get width(){return 32;}get height(){return 16;}}globalThis.ImageBitmap=Bitmap;try{const observer=fixture(),bitmap=new Bitmap();Object.defineProperty(bitmap,'width',{get(){throw Error('Foreign width');}});Object.defineProperty(bitmap,'src',{get(){throw Error('Private URL');}});observer.record('texImage2D',[1,0,1,1,1,bitmap],3);observer.record('texImage2D',[1,0,1,1,1,{get width(){throw Error('Foreign field');}}],3);const values=observer.snapshot().buckets;assert.equal(values[0].kind,'bitmap');assert.equal(values[0].width,32);assert.equal(values[1].kind,'unknown');assert.equal(values[1].width,null);}finally{if(old===undefined)delete globalThis.ImageBitmap;else globalThis.ImageBitmap=old;delete globalThis.__hubUploadProfile;}});
test('compressed mip dimensions and overflow bounds remain scalar, snapshots cannot mutate state',()=>{const observer=fixture(),data=new Uint8Array(16);observer.record('compressedTexSubImage2D',[1,2,0,0,64,32,1,data],1);let result=observer.snapshot();assert.equal(result.buckets[0].mipLevel,2);assert.equal(result.buckets[0].width,64);assert.equal(result.buckets[0].height,32);result.buckets[0].calls=300;for(let i=1;i<200;i++)observer.record('texSubImage2D',[1,0,0,0,i,1,1,1,data],.1);result=observer.snapshot();assert.equal(result.buckets.length,128);assert.ok(result.droppedRecords>0);assert.equal(result.buckets[0].calls,1);delete globalThis.__hubUploadProfile;});
test('source tracking is bounded without retaining submitted images or growing raw record arrays',()=>{const observer=fixture();for(let i=0;i<1100;i++)observer.record('texSubImage2D',[1,0,0,0,1,1,1,1,new Uint8Array(4)],0);const result=observer.snapshot();assert.equal(result.uniqueArgumentSourcesLowerBound,1024);assert.equal(result.sourceLimitReached,true);assert.equal(result.buckets.length,1);assert.equal(result.buckets[0].calls,1100);delete globalThis.__hubUploadProfile;});
test('the exact serialized init-script function has no module closure dependencies and invalid clock inputs never poison aggregates',()=>{const context={};runInNewContext('('+installHubUploadProfile.toString()+')()',context);const observer=context.__hubUploadProfile;observer.record('texSubImage2D',[1,0,0,0,2,2,1,1,new Uint8Array(16)],Infinity);const result=observer.snapshot();assert.equal(result.invalidDurations,1);assert.equal(result.buckets[0].totalMs,0);assert.equal(result.buckets[0].maxMs,0);});

function borrowedTypes(types,run){const saved=new Map();for(const [name,Type]of Object.entries(types)){saved.set(name,Object.getOwnPropertyDescriptor(globalThis,name));Object.defineProperty(globalThis,name,{configurable:true,writable:true,value:Type});}try{return run();}finally{for(const [name,descriptor]of saved){if(descriptor)Object.defineProperty(globalThis,name,descriptor);else delete globalThis[name];}delete globalThis.__hubUploadProfile;}}
test('all seven DOM source kinds support inherited and explicit-dimension WebGL2 image/subimage overloads',()=>{
 class Image{get naturalWidth(){return 31;}get naturalHeight(){return 17;}}class Dimensions{get width(){return 31;}get height(){return 17;}}class Video{get videoWidth(){return 31;}get videoHeight(){return 17;}}class Frame{get displayWidth(){return 31;}get displayHeight(){return 17;}}
 const types={HTMLImageElement:Image,ImageBitmap:class extends Dimensions{get width(){return super.width;}get height(){return super.height;}},HTMLCanvasElement:class extends Dimensions{get width(){return super.width;}get height(){return super.height;}},OffscreenCanvas:class extends Dimensions{get width(){return super.width;}get height(){return super.height;}},HTMLVideoElement:Video,ImageData:class extends Dimensions{get width(){return super.width;}get height(){return super.height;}},VideoFrame:Frame};
 borrowedTypes(types,()=>{const observer=fixture();for(const [name,Type]of Object.entries(types)){const source=new Type();Object.defineProperty(source,'src',{get(){throw Error('Must not read private URL');}});for(const [method,args]of [['texImage2D',[1,0,6408,6408,5121,source]],['texSubImage2D',[1,0,0,0,6408,5121,source]],['texImage2D',[1,0,6408,19,13,0,6408,5121,source]],['texSubImage2D',[1,0,0,0,19,13,6408,5121,source]]]){observer.record(method,args,1);const last=observer.snapshot().buckets.at(-1);assert.notEqual(last.kind,'unknown',name);assert.deepEqual([last.width,last.height,last.format,last.type],args.length===9?[19,13,6408,5121]:[31,17,6408,5121]);}}
 const result=observer.snapshot();assert.equal(result.records,28);assert.equal(result.unknownSignatures,0);assert.equal(result.uniqueArgumentSourcesLowerBound,7);});
});
test('typed-data, null-data and zero/nonzero PBO offsets retain exact declared dimensions/format/type independently of object discovery',()=>{
 const observer=fixture(),data=new Uint8Array(32);for(const method of ['texImage2D','texSubImage2D']){const head=method==='texImage2D'?[1,2,6408,4,2,0,6408,5121]:[1,2,0,0,4,2,6408,5121];for(const [tail,kind]of [[[data],'data'],[[data,1],'data'],[[null],'null-data'],[[0],'pbo'],[[1048576],'pbo']]){observer.record(method,[...head,...tail],.1);const match=observer.snapshot().buckets.find(value=>value.method===method&&value.kind===kind);assert.deepEqual([match.width,match.height,match.format,match.type],[4,2,6408,5121]);}}
 const result=observer.snapshot();assert.equal(result.unknownSignatures,0);assert.equal(result.uniqueArgumentSourcesLowerBound,1);assert.equal(result.buckets.filter(value=>value.kind==='pbo').reduce((sum,value)=>sum+value.calls,0),4);delete globalThis.__hubUploadProfile;
});
test('all compressed typed offset/length and imageSize/PBO overloads preserve dimensions without inventing source identities',()=>{
 const observer=fixture(),data=new Uint8Array(32);for(const method of ['compressedTexImage2D','compressedTexSubImage2D']){const head=method==='compressedTexImage2D'?[1,2,33777,8,4,0]:[1,2,0,0,8,4,33777];for(const tail of [[data],[data,1],[data,1,16],[data,undefined,undefined],[32,0],[32,1048576]])observer.record(method,[...head,...tail],1);}
 const result=observer.snapshot();assert.equal(result.unknownSignatures,0);assert.equal(result.records,12);assert.equal(result.uniqueArgumentSourcesLowerBound,1);for(const bucket of result.buckets){assert.deepEqual([bucket.width,bucket.height,bucket.format,bucket.type],[8,4,33777,null]);assert.ok(['data','pbo'].includes(bucket.kind));}delete globalThis.__hubUploadProfile;
});
test('malformed lengths/noninteger fields and unsupported objects remain explicitly unknown without inspecting foreign fields or coercion',()=>{
 const observer=fixture(),data=new Uint8Array(16),foreign={get width(){throw Error('Foreign width');},valueOf(){throw Error('Foreign scalar');}};
 const typed=[1,0,6408,2,2,0,6408,5121,data],cases=[[...typed,0,0],[...typed.slice(0,8)],typed.with(3,1.5),typed.with(4,NaN),typed.with(6,foreign),typed.with(5,1),typed.with(8,foreign),typed.with(8,new ArrayBuffer(16)),typed.with(8,-1),[...typed,undefined],['1',...typed.slice(1)],['compressedTexImage2D'],[1,0,33777,4,4,0,null],[1,0,33777,4,4,0,16,1.5],[1,0,33777,4,4,0,data,-1],null];
 for(const args of cases)observer.record('texImage2D',args,1);
 observer.record('compressedTexImage2D',[1,0,33777,4,4,0,16,1.5],1);observer.record('compressedTexImage2D',[1,0,33777,4,4,0,data,-1],1);
 const result=observer.snapshot();assert.equal(result.unknownSignatures,cases.length+2);assert.equal(result.uniqueArgumentSourcesLowerBound,0);assert.ok(result.buckets.every(value=>value.kind==='unknown'&&value.width===null&&value.height===null&&value.format===null&&value.type===null));delete globalThis.__hubUploadProfile;
});
test('explicit image and numeric PBO observations contradict the previous object-search/index rule',()=>{
 class Image{get naturalWidth(){return 4096;}get naturalHeight(){return 2048;}}
 borrowedTypes({HTMLImageElement:Image},()=>{const observer=fixture(),source=new Image(),args=[1,0,6408,64,32,0,6408,5121,source];observer.record('texImage2D',args,1);const measured=observer.snapshot().buckets[0];
 // Exact old rule: DOM sources borrowed native dimensions and took args3/4
 // for format/type regardless of the explicit-size nine-argument signature.
 const old={width:source.naturalWidth,height:source.naturalHeight,format:args[3],type:args[4]};assert.deepEqual([measured.width,measured.height,measured.format,measured.type],[64,32,6408,5121]);assert.notDeepEqual(measured.width,old.width);assert.notDeepEqual(measured.format,old.format);
 observer.record('texImage2D',[1,0,6408,64,32,0,6408,5121,0],1);const pbo=observer.snapshot().buckets.at(-1);assert.equal(pbo.kind,'pbo');assert.equal(pbo.width,64);assert.equal([1,0,6408,64,32,0,6408,5121,0].find(value=>value&&typeof value==='object'),undefined);});
});

test('closed native source intrinsic getters are caught and large source dimensions remain bounded without foreign property access',()=>{
 class Frame{get displayWidth(){throw Error('Closed native frame');}get displayHeight(){return 2147483647;}}
 borrowedTypes({VideoFrame:Frame},()=>{const observer=fixture(),source=new Frame();Object.defineProperty(source,'width',{get(){throw Error('Foreign width');}});Object.defineProperty(source,'data',{get(){throw Error('Foreign data');}});observer.record('texImage2D',[1,0,6408,6408,5121,source],1);const result=observer.snapshot();assert.equal(result.unknownSignatures,0);assert.equal(result.buckets[0].kind,'videoFrame');assert.equal(result.buckets[0].width,null);assert.equal(result.buckets[0].height,null);assert.equal(result.uniqueArgumentSourcesLowerBound,1);});
});
