// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Registration/cleanup CPU contracts only; no simulated result is GPU evidence.
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import {bitmapCases,registeredBitmapBodies,finishStockBitmapCleanup}from'./stock-bitmap-registration.mjs';
const client=new URL('../..',import.meta.url).pathname;
const report=()=>({completed:true,cleanup:{contextsClosed:0,browser:'not-created',server:'not-created'}});
test('registers exactly the two ORIGINAL case bodies with actual expect without modifying any assertion',async()=>{const entries=await registeredBitmapBodies(client);assert.equal(entries.length,2);assert.deepEqual(entries.map(e=>e.name),bitmapCases.map(e=>e.name));for(const entry of entries){const source=await readFile(path.join(client,entry.file),'utf8');assert(source.includes(entry.name));assert(entry.callback.toString().includes('expect(report.'));}assert(entries[0].callback.toString().includes('toHaveLength(12)'));assert(entries[1].callback.toString().includes('expect(prepared.pixelHash).toBe(original.pixelHash)'));});
test('actual registered twelve-variant expect still refuses nonzero channel error or incomplete cleanup under authored CPU adapter',async()=>{const [entry]=await registeredBitmapBodies(client);const fixed={completed:true,checks:Array.from({length:12},(_,i)=>({prepared:i%6<3,premultiplyAlpha:i%6>=3,maximumChannelError:0})),ownership:{leases:0,bytes:0,active:0,closeFailures:0},textureCountAfterClose:0,geometryCountAfterClose:0};const invoke=record=>entry.callback({page:{goto:async()=>{},evaluate:async()=>record}},{attach:async(name,value)=>{assert.equal(name,'bitmap-upload-parity');assert.equal(value.contentType,'application/json');}});await invoke(fixed);for(const mutate of [r=>r.checks[0].maximumChannelError=1,r=>r.ownership.leases=1,r=>r.textureCountAfterClose=1,r=>r.checks[3].prepared=true]){const r=structuredClone(fixed);mutate(r);await assert.rejects(invoke(r));}});
test('unknown title/additional registered case refuses instead of substituting an unregistered GPU predicate',async()=>{const tmp=await mkdtemp(path.join(tmpdir(),'bitmap-registration-contract-'));try{await mkdir(path.join(tmp,'tests'));for(const entry of bitmapCases)await writeFile(path.join(tmp,entry.file),await readFile(path.join(client,entry.file)));const f=path.join(tmp,bitmapCases[0].file);await writeFile(f,(await readFile(f,'utf8')).replace(bitmapCases[0].name,'foreign assertion body'));await assert.rejects(registeredBitmapBodies(tmp));}finally{await rm(tmp,{recursive:true,force:true});}});
test('context close failure never bypasses owned browser/server close or overwrites original failure',async()=>{const r=report(),events=[],before=process.exitCode;r.failure='original-literal-pixel-refusal';try{await finishStockBitmapCleanup({context:{close:async()=>{events.push('context');throw Error('context');}},browser:{close:async()=>{events.push('browser');throw Error('browser');}},server:{close:async()=>{events.push('server');}}},r);assert.deepEqual(events,['context','browser','server']);assert.equal(r.failure,'original-literal-pixel-refusal');assert.equal(r.completed,false);assert.equal(r.cleanup.browser,'failed');assert.equal(r.cleanup.server,'closed');}finally{process.exitCode=before;}});
test('successful cleanup records actual per-context, browser and Vite completions',async()=>{const r=report();await finishStockBitmapCleanup({context:{close:async()=>{}},browser:{close:async()=>{}},server:{close:async()=>{}}},r);assert.equal(r.cleanup.contextsClosed,1);assert.equal(r.cleanup.browser,'closed');assert.equal(r.cleanup.server,'closed');assert.equal(r.completed,true);});
test('stock runner attests all actual source files and fixed original fixtures, retains source hashes on failed assertions and finally cleanup',async()=>{const source=await readFile(new URL('./stock-bitmap-pixels.mjs',import.meta.url),'utf8');assert(source.includes("await visit('src')"));for(const entry of bitmapCases)assert(source.includes(entry.file));assert(source.includes("report.browserVersion=await browser.version()"));assert(source.includes("const expectedMajor=engine==='system-chromium'?154:156"));assert(source.includes('await test.callback({page}'));assert(source.includes('await finishStockBitmapCleanup({context,browser,server},report)'));assert(source.includes("flag:'wx',mode:0o600"));assert(source.includes('embeddedFbxGpuCoverage:false'));assert(!source.includes('toBeCloseTo'));assert(!source.includes('no-sandbox'));});

test('owned fixture follows working configless Vite recipe and cannot complete after an expired overall owner deadline',async()=>{const s=await readFile(new URL('./stock-bitmap-pixels.mjs',import.meta.url),'utf8');assert(s.includes('createServer({root:client,configFile:false,'));assert(!s.includes("configFile:path.join(client,'vite.config.ts')"));assert(s.includes("assert(!report.ownerDeadlineExceeded,'Owned bitmap fixture deadline exceeded');report.completed=true;"));const accepted=()=>{const report={ownerDeadlineExceeded:true};assert(!report.ownerDeadlineExceeded,'Owned bitmap fixture deadline exceeded');report.completed=true;};assert.throws(accepted,/deadline/);});
