// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
import {readPttKeyDownSnapshot,validatePttKeyDownSnapshots} from './tablet-ptt-keydown-snapshot.mjs';
import {observePttVisibilityEvents} from './tablet-ptt-visibility.mjs';
const runner=readFileSync(new URL('./tablet-push-to-talk.mjs',import.meta.url),'utf8');
const start=runner.indexOf(" await page.addInitScript('window.__pttKeyDownSnapshot="),end=runner.indexOf('\n await page.goto(base);',start);assert(start>=0&&end>start);const initialization=runner.slice(start,end);
async function fixture(){
 const events={},documentEvents={};let gum=0,writes=0;
 const button={disabled:true,getAttribute(name){assert.equal(name,'aria-pressed');return 'false';},get value(){throw Error('Private input must not be read');}};
 const window={WebSocket:class{},__overte:{connected:true,tabletVisible:false},addEventListener(type,fn){(events[type]??=[]).push(fn);}};
 const document={hidden:false,querySelector(selector){assert.equal(selector,'#microphone');return button;},addEventListener(type,fn){(documentEvents[type]??=[]).push(fn);}};
 const navigator={mediaDevices:{getUserMedia:async()=>{gum++;throw Error('No consent request authorized in a passive observer');}}};
 const ctx=vm.createContext({window,document,navigator});
 await vm.runInNewContext('(async()=>{'+initialization+'})()',{page:{addInitScript:script=>vm.runInContext(script,ctx)},readPttKeyDownSnapshot,observePttVisibilityEvents});
 const event=(options={})=>({code:'KeyT',isTrusted:true,...options});
 return {window,button,ctx,events,a:window.__pttAudit,gum:()=>gum,emit(e=event()){for(const fn of events.keydown)fn(e);},event,writes:()=>writes};
}
test('actual runner audit records pending microphone before production KeyT handling with no consent/input operation',async()=>{const f=await fixture();f.a.state={enabled:false,held:false,muted:true,sequence:4,permissionRevision:2};f.a.commands=[{held:false,sequence:4}];f.events.keydown.push(()=>{f.a.state.held=true;});f.emit();const [row]=validatePttKeyDownSnapshots(f.a.keyDownSnapshots);assert.equal(row.microphone.disabled,true);assert.equal(row.microphone.ariaPressed,'false');assert.equal(row.getUserMediaCalls,0);assert.equal(row.liveTrackCount,0);assert.equal(row.native.enabled,false);assert.equal(row.native.held,false);assert.equal(f.a.state.held,true);assert.equal(row.connected,true);assert.equal(row.tabletVisible,false);assert.equal(f.gum(),0);});
test('trusted current state records grant/live tracks and last effective command as fixed scalars only',async()=>{const f=await fixture();f.button.disabled=false;f.button.getAttribute=()=> 'true';f.a.getUserMediaCalls=3;f.a.tracks=[{readyState:'ended',get label(){throw Error('private');}},{readyState:'live',get id(){throw Error('private');}}];f.a.state={enabled:true,held:false,muted:true,sequence:7,permissionRevision:2,token:'private'};f.a.commands=[{held:false,sequence:7,token:'private'}];f.emit();const rows=validatePttKeyDownSnapshots(f.a.keyDownSnapshots);assert.equal(rows[0].liveTrackCount,1);assert.equal(rows[0].getUserMediaCalls,3);assert.equal(rows[0].microphone.disabled,false);assert.equal(rows[0].microphone.ariaPressed,'true');assert.equal(rows[0].native.sequence,7);assert.equal(rows[0].native.permissionRevision,2);assert(!JSON.stringify(rows).includes('private'));assert.equal(f.gum(),0);});
test('untrusted and other keys cannot add a snapshot or change original trusted KeyT counter',async()=>{const f=await fixture();f.emit(f.event({isTrusted:false}));f.emit(f.event({code:'KeyA'}));assert.equal(f.a.keyDownSnapshots.length,0);assert.equal(f.a.events.keyDown,0);f.emit();assert.equal(f.a.events.keyDown,1);assert.equal(f.a.keyDownSnapshots.length,1);});
test('actual registration retains at most16 recent scalar rows with independent earlier state values',async()=>{const f=await fixture();for(let n=0;n<25;n++){f.a.getUserMediaCalls=n;f.emit();}assert.equal(f.a.events.keyDown,25);assert.equal(f.a.keyDownSnapshots.length,16);assert.equal(f.a.keyDownSnapshots[0].getUserMediaCalls,9);assert.equal(f.a.keyDownSnapshots.at(-1).getUserMediaCalls,24);assert.equal(f.gum(),0);});
test('unavailable or oversized local observations are unknown without arbitrary strings or counts',async()=>{const f=await fixture();f.a.getUserMediaCalls=65536;f.a.tracks=Array.from({length:5},()=>({readyState:'live'}));f.button.getAttribute=()=> 'private';f.emit();const row=validatePttKeyDownSnapshots(f.a.keyDownSnapshots)[0];assert.equal(row.getUserMediaCalls,null);assert.equal(row.liveTrackCount,null);assert.equal(row.microphone.ariaPressed,'unknown');assert.equal(row.native.sequence,null);assert(!JSON.stringify(row).includes('private'));});
test('exact schema/byte/count and range admission refuses extra secrets and returns independent clones',async()=>{const f=await fixture();f.emit();const row=f.a.keyDownSnapshots[0];assert.throws(()=>validatePttKeyDownSnapshots(Array(17).fill(row)));for(const changed of [{...row,path:'private'},{...row,getUserMediaCalls:-1},{...row,liveTrackCount:5},{...row,native:{...row.native,secret:'private'}},{...row,microphone:{...row.microphone,ariaPressed:'private'}}])assert.throws(()=>validatePttKeyDownSnapshots([changed]));const copy=validatePttKeyDownSnapshots([row]);copy[0].microphone.disabled=false;assert.equal(row.microphone.disabled,true);});
test('actual original hold and all actions/voice/consent/cleanup gates remain while final diagnostics use one existing RPC',()=>{const hold=runner.slice(runner.indexOf('async function hold()'),runner.indexOf('async function released()'));assert(hold.includes('timeout:15000'));assert(hold.includes('last?.held===true&&a.state?.enabled&&a.state.held&&!a.state.muted&&a.state.sequence===last.sequence&&a.state.permissionRevision===last.permissionRevision'));assert(runner.includes('const finalGrantCalls=await page.evaluate(()=>window.__pttAudit.getUserMediaCalls);'));assert(runner.includes("m.disabled===false&&m.getAttribute('aria-pressed')==='true'&&a.getUserMediaCalls===calls+1&&a.tracks.filter(t=>t.readyState==='live').length===1"));assert(runner.includes('readPttKeyDownSnapshot.toString()'));assert(runner.includes("'tests/integration/tablet-ptt-keydown-snapshot.mjs'"));assert(runner.includes('report.trustedInputDiagnostics=d.trusted;report.trustedKeyDownSnapshots=validatePttKeyDownSnapshots(d.keyDownSnapshots)'));const helper=readFileSync(new URL('./tablet-ptt-keydown-snapshot.mjs',import.meta.url),'utf8');for(const bad of ['dispatchEvent(','getUserMedia(','preventDefault(','stopPropagation(','.focus(','.value=','.send(','setTimeout('])assert(!helper.includes(bad));});

const nativeReleasedGate=" await page.waitForFunction(()=>window.__pttAudit.state?.enabled&&!window.__pttAudit.state.held&&window.__pttAudit.state.muted,undefined,{timeout:15000});";
const finalStart=runner.lastIndexOf(nativeReleasedGate),finalEnd=runner.indexOf('await writeFile',finalStart);assert(finalStart>=0&&finalEnd>finalStart);
const finalFlow=runner.slice(finalStart,finalEnd),actualHold=runner.slice(runner.indexOf(' async function hold()'),runner.indexOf(' async function released()'));
function finalFixture({nativeEnabled=true,immediateGrant=false}={}){
 const a={events:{keyDown:0},state:{enabled:nativeEnabled,held:false,muted:true,sequence:8,permissionRevision:1},getUserMediaCalls:2,tracks:[{readyState:'ended'},{readyState:'ended'}],commands:[{held:false,sequence:8,permissionRevision:1}]};
 const microphone={disabled:false,pressed:'false',getAttribute(name){assert.equal(name,'aria-pressed');return this.pressed;}};
 const window={__pttAudit:a,__overte:{connected:true,tabletVisible:false}},document={querySelector(name){assert.equal(name,'#microphone');return microphone;}},context=vm.createContext({window,document});
 const waits=[],pending=new Map(),keys=[];let clicks=0;
 const invoke=(fn,arg)=>vm.runInContext('('+fn.toString()+')',context)(arg);
 function ready(){microphone.disabled=false;microphone.pressed='true';a.tracks.push({readyState:'live'});}
 const page={async bringToFront(){},async evaluate(fn){return invoke(fn);},locator(name){assert.equal(name,'#microphone');return {async click(){clicks++;a.getUserMediaCalls++;microphone.disabled=true;if(immediateGrant)ready();}};},
  keyboard:{async down(key){assert.equal(key,'t');keys.push({pending:microphone.disabled,live:a.tracks.filter(t=>t.readyState==='live').length});a.events.keyDown++;if(!microphone.disabled&&microphone.pressed==='true'&&a.tracks.some(t=>t.readyState==='live')&&a.state.enabled){a.commands.push({held:true,sequence:9,permissionRevision:1});a.state={enabled:true,held:true,muted:false,sequence:9,permissionRevision:1};}}},
  async waitForFunction(fn,arg,options){assert.equal(options.timeout,15000);const text=fn.toString(),stage=text.includes('getUserMediaCalls===calls+1')?'grant':text.includes('last?.held')?'hold':'native';waits.push(stage);if(invoke(fn,arg))return;return new Promise((resolve,reject)=>pending.set(stage,{resolve,reject,fn,arg}));}};
 return {a,microphone,keys,waits,clicks:()=>clicks,run:()=>vm.runInNewContext('(async()=>{'+actualHold+finalFlow+'})()',{page,assert}),original:()=>vm.runInNewContext('(async()=>{'+actualHold+"await page.locator('#microphone').click();await hold();})()",{page,assert}),ready,resolve(stage){const p=pending.get(stage);assert(p);assert(invoke(p.fn,p.arg));pending.delete(stage);p.resolve();},reject(stage){const p=pending.get(stage);assert(p);pending.delete(stage);p.reject(Error('original-'+stage+'-refusal'));}};
}
const nextTurn=()=>new Promise(resolve=>setImmediate(resolve));
test('actual final runner cannot press while explicit GUM is pending; completed owned grant precedes one unchanged hold',async()=>{const f=finalFixture(),run=f.run();await nextTurn();assert.equal(f.clicks(),1);assert.equal(f.a.getUserMediaCalls,3);assert.equal(f.microphone.disabled,true);assert.equal(f.keys.length,0);assert.deepEqual(f.waits,['native','grant']);f.ready();f.resolve('grant');await run;assert.equal(f.keys.length,1);assert.deepEqual(f.keys[0],{pending:false,live:1});assert.deepEqual(f.waits,['native','grant','hold']);assert.equal(f.a.commands.at(-1).sequence,9);});
test('exact original final-stage counterfactual physically presses before GUM resolves and fails original effective held ACK gate',async()=>{const f=finalFixture(),run=f.original();await nextTurn();assert.equal(f.keys.length,1);assert.deepEqual(f.keys[0],{pending:true,live:0});assert.equal(f.a.commands.length,1);assert.deepEqual(f.waits,['hold']);f.reject('hold');await assert.rejects(run,/original-hold-refusal/);});
test('completed-grant rejection leaves original hold unpressed and requests no retry',async()=>{const f=finalFixture(),run=f.run();await nextTurn();f.microphone.disabled=false;f.reject('grant');await assert.rejects(run,/original-grant-refusal/);assert.equal(f.keys.length,0);assert.equal(f.clicks(),1);assert.deepEqual(f.waits,['native','grant']);});
test('unknown or unacknowledged native mode cannot request permission or press before original released-state gate',async()=>{for(const nativeEnabled of [false,undefined]){const f=finalFixture({nativeEnabled});if(nativeEnabled===undefined)f.a.state.enabled=undefined;const run=f.run();await nextTurn();assert.equal(f.clicks(),0);assert.equal(f.keys.length,0);f.reject('native');await assert.rejects(run,/original-native-refusal/);assert.equal(f.a.getUserMediaCalls,2);}});
test('already completed consent proceeds once through identical15-second effective native hold without extra key or grant',async()=>{const f=finalFixture({immediateGrant:true});await f.run();assert.equal(f.clicks(),1);assert.equal(f.keys.length,1);assert.deepEqual(f.waits,['native','grant','hold']);assert.equal(f.a.commands.filter(c=>c.held).length,1);});
test('grant predicate refuses a changed request count or missing live track despite painted pressed microphone',async()=>{for(const change of [f=>f.a.getUserMediaCalls++,f=>f.a.tracks.forEach(t=>t.readyState='ended')]){const f=finalFixture(),run=f.run();await nextTurn();f.ready();change(f);assert.throws(()=>f.resolve('grant'));assert.equal(f.keys.length,0);f.reject('grant');await assert.rejects(run,/original-grant-refusal/);assert.equal(f.clicks(),1);}});
