// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
import {peopleProofQueueInstallerSource,samplePeopleDisplayedControl,paintedPeopleControl} from './tablet-people-proof-queue.mjs';
import {createPeopleTrustedEventOracle} from './tablet-people-trusted-event-oracle.mjs';
import {peopleTrustedBindingInstallerSource} from './tablet-people-trusted-binding.mjs';
import {peopleAuditBrowserBindingsSource,encodeValidatedPeopleRecords,parsePeopleAudit,peopleHomeControl,PEOPLE_AUDIT_QML} from './tablet-people-audit.mjs';
const peer='12345678-1234-1234-1234-123456789abc',plain=v=>JSON.parse(JSON.stringify(v));
const makeFrame=n=>({sequence:n,revision:2,navigationSequence:3,width:480,height:706,surface:'tablet',tabletRect:{x:0,y:0,width:480,height:706},data:Buffer.from('owned PNG').toString('base64')});
function record(seq,{home=false,change=()=>{}}={}){const r={version:1,sequence:seq,revision:2,navigationSequence:3,scope:'native-people-nearby',palCount:home?0:1,activeTab:home?'other':'nearby',admin:home?null:false,nodes:80,truncated:false,rows:home?[]:[{sessionId:peer,ignore:false,nativeIgnore:false,checked:false,enabled:true,visible:true,rect:{x:100,y:150,width:24,height:24}}],homeButtonCount:home?1:0,homeButton:home?{enabled:true,rect:{x:175,y:255,width:129,height:129}}:null};change(r);return r;}
const tablet=readFileSync(new URL('../../src/tablet.ts',import.meta.url),'utf8');
function slice(a,b){assert.equal(tablet.split(a).length,2);return tablet.slice(tablet.indexOf(a),tablet.indexOf(b,tablet.indexOf(a)));}
let methods=slice('    private coordinates(','    get worldInputReady(')+slice('    private send(','    private show(')+slice('    private modifiers(','    private fit(');
// Exact signature-only erasure, supported without a new Node/TypeScript runtime requirement.
for(const [from,to] of [["private coordinates(event:MouseEvent):{x:number;y:number}","coordinates(event)"],["private clearPointer():void","clearPointer()"],["private pointer(event:'press'|'release'|'cancel'|'move',pointer:PointerEvent):void","pointer(event,pointer)"],["private send(value:Record<string,unknown>):void","send(value)"],["private modifiers(event:KeyboardEvent|MouseEvent):number","modifiers(event)"]]){assert.equal(methods.split(from).length,2);methods=methods.replace(from,to);}
const Actual=vm.runInNewContext('class Actual {\n'+methods+'\n};Actual;');
const downBody=slice("        this.canvas.addEventListener('pointerdown',event=>{","        this.canvas.addEventListener('pointerup'").split('event=>{')[1].split('},{signal});')[0],onDown=Function('event',downBody);
function fixture(){
 const listeners=[],sent=[];let pixels=0,focus=0;
 const captures=new Set(),canvas={width:480,height:706,getBoundingClientRect:()=>({left:10,top:20,width:240,height:353}),setPointerCapture:id=>captures.add(id),hasPointerCapture:id=>captures.has(id),releasePointerCapture:id=>captures.delete(id),getContext:()=>({getImageData(x,y,w,h){pixels++;const data=new Uint8ClampedArray(w*h*4);for(let i=0;i<data.length;i+=4)data.set(i<data.length/2?[20,20,20,255]:[230,230,230,255],i);return {data};}})};
 const audit={navigation:3,frame:makeFrame(5),state:{visible:true}},ctx={window:{__peopleAudit:audit,__overte:{connected:true,tabletVisible:true}},AbortController,TextEncoder,atob:v=>Buffer.from(v,'base64').toString('binary'),document:{querySelector(selector){assert.equal(selector,'canvas[aria-label="Native tablet apps and dialogs"]');return canvas;},addEventListener(type,fn,options){assert.equal(options.capture,true);listeners.push({type,fn,options});}}};
 vm.runInNewContext(peopleProofQueueInstallerSource(samplePeopleDisplayedControl,paintedPeopleControl),ctx);audit.proofs=ctx.window.__peopleProofFactory();
 vm.runInNewContext(peopleTrustedBindingInstallerSource(peopleAuditBrowserBindingsSource(),createPeopleTrustedEventOracle),ctx);audit.trusted=ctx.window.__peopleTrustedFactory();
 const actual=new Actual();Object.assign(actual,{canvas,keyboard:{focus:()=>focus++},revision:2,displayedFrameSequence:5,navigationSequence:3,sequence:50,connected:true,visible:true,disposed:false,options:{send:m=>{sent.push(m);audit.trusted.wire(m);}}});
 const event=(up=false)=>({target:canvas,isTrusted:true,pointerId:7,button:0,buttons:up?0:1,clientX:66,clientY:101,shiftKey:false,ctrlKey:false,altKey:false,metaKey:false,preventDefault(){}});
 function dispatch(type,e){for(const row of listeners)if(row.type===type&&!row.options.signal.aborted)row.fn(e);}
 function setFrame(frame){audit.frame=frame;actual.displayedFrameSequence=frame.sequence;actual.revision=frame.revision;}
 const value={kind:'ignore',peer,ignored:false},records=rows=>encodeValidatedPeopleRecords(rows);
 function prepare(rows=[record(5)],v=value){const r=audit.trusted.prepare(v,records(rows));return {value:v,expected:{...r.sample?.frame,...r.point},result:r,text:records(rows)};}
 function arm(prepared){return audit.trusted.arm(prepared.value,prepared.text,prepared.expected);}
 function click(e=event()){dispatch('pointerdown',e);onDown.call(actual,e);const up={...e,buttons:0};dispatch('pointerup',up);actual.pointer('release',up);}
 return {ctx,audit,canvas,actual,listeners,sent,event,dispatch,setFrame,prepare,arm,click,records,pixels:()=>pixels,focus:()=>focus};
}
test('exact serialized parser/qualifiers run in browser with the same original Node admission',()=>{const source=peopleAuditBrowserBindingsSource();for(const token of ['parsePeopleAudit','peopleIgnoreControl','peopleHomeControl'])assert(source.includes(token));const f=fixture(),prepared=f.prepare();assert.equal(prepared.result.refusal,null);assert.equal(prepared.expected.sequence,5);assert.equal(f.listeners.length,3);assert.equal(f.focus(),0);});
test('old5/current6 actual production sends6; only fresh6 native rows/pixels permit matching real press and release',()=>{const f=fixture(),prepared=f.prepare([record(5),record(6)]),armed=f.arm(prepared);assert.equal(armed.refusal,null);f.setFrame(makeFrame(6));f.click();const proof=f.audit.trusted.complete(armed.intentOrdinal);assert(proof.press.accepted&&proof.release.accepted);assert.equal(proof.press.frame.sequence,6);assert.equal(f.sent[0].frameSequence,6);assert.equal(f.sent[1].frameSequence,6);assert.equal(f.focus(),1);assert.equal(f.audit.trusted.readProofMetadata().length,1);assert.equal(f.pixels(),2);});
test('current6 without an actual6 native record refuses even if old5 control geometry matches',()=>{const f=fixture(),armed=f.arm(f.prepare());f.setFrame(makeFrame(6));f.click();assert.throws(()=>f.audit.trusted.complete(armed.intentOrdinal));assert.equal(f.audit.trusted.readProofMetadata().length,0);assert.equal(f.audit.trusted.diagnostics().failures['current-native-control-not-qualified'],1);});
test('same-navigation moved control refuses before event pixels without accepting inside another rect',()=>{const f=fixture(),prepared=f.prepare([record(5),record(6,{change:r=>r.rows[0].rect.x=101})]),armed=f.arm(prepared);f.setFrame(makeFrame(6));f.click();assert.throws(()=>f.audit.trusted.complete(armed.intentOrdinal));assert.equal(f.pixels(),1);assert.equal(f.audit.trusted.diagnostics().failures['control-geometry-changed'],1);});
test('same-navigation disabled/admin/nativeIgnore rights contradictions refuse actual event qualification',()=>{for(const change of [r=>r.rows[0].enabled=false,r=>r.admin=true,r=>r.rows[0].nativeIgnore=true]){const f=fixture(),armed=f.arm(f.prepare([record(5),record(6,{change})]));f.setFrame(makeFrame(6));f.click();assert.throws(()=>f.audit.trusted.complete(armed.intentOrdinal));assert.equal(f.pixels(),1);}});
test('physical synthetic wrong-target event cannot certify original production outgoing commands',()=>{for(const change of [e=>e.isTrusted=false,e=>e.target={}]){const f=fixture(),armed=f.arm(f.prepare()),e=f.event();change(e);f.click(e);assert.throws(()=>f.audit.trusted.complete(armed.intentOrdinal));assert.equal(f.audit.trusted.readProofMetadata().length,0);}});
test('changed navigation/revision or disconnected authority cannot authorize same-looking button',()=>{for(const change of [f=>{f.audit.navigation=4;},f=>f.setFrame({...makeFrame(6),revision:3}),f=>{f.ctx.window.__overte.connected=false;}]){const f=fixture(),armed=f.arm(f.prepare());change(f);f.click();assert.throws(()=>f.audit.trusted.complete(armed.intentOrdinal));assert.equal(f.audit.trusted.readProofMetadata().length,0);}});
test('press proof alone and forged mismatched release do not complete a genuine click',()=>{const f=fixture(),armed=f.arm(f.prepare());const e=f.event();f.dispatch('pointerdown',e);onDown.call(f.actual,e);assert.throws(()=>f.audit.trusted.complete(armed.intentOrdinal));const up=f.event(true);f.dispatch('pointerup',up);f.audit.trusted.wire({...f.sent[0],event:'release',sequence:52,buttons:0,x:.99});assert.throws(()=>f.audit.trusted.complete(armed.intentOrdinal));});
test('reentrant focus invalidation and native cancellation preserve failure and never suppress the production effect',()=>{const f=fixture(),armed=f.arm(f.prepare());f.actual.keyboard.focus=()=>f.audit.trusted.invalidate();f.click();assert.equal(f.sent.length,2);assert.throws(()=>f.audit.trusted.complete(armed.intentOrdinal));const g=fixture(),arm=g.arm(g.prepare());g.dispatch('pointercancel',g.event());assert.throws(()=>g.audit.trusted.complete(arm.intentOrdinal));assert.equal(g.audit.trusted.diagnostics().failures['physical-pointer-cancelled'],1);});
test('record projection rejects unknown schema/oversized input and exact audit parser preserves current fields',()=>{assert.throws(()=>encodeValidatedPeopleRecords([record(5,{change:r=>r.private='not-exported'})]));const f=fixture();assert.throws(()=>f.audit.trusted.prepare({kind:'ignore',peer,ignored:false},'x'.repeat(32*(16384+256)+1)));assert.throws(()=>encodeValidatedPeopleRecords(Array.from({length:33},()=>record(5))));assert.equal(parsePeopleAudit(f.records([record(5)])).length,1);});
test('actual native Home PEOPLE audit requires unique source7 button and matching current painted frame',()=>{assert(PEOPLE_AUDIT_QML.includes("node.text==='PEOPLE'&&node.sortOrder===7"));const r=record(5,{home:true});assert(peopleHomeControl([r],makeFrame(5)));for(const change of [x=>x.homeButtonCount=2,x=>x.homeButton.enabled=false,x=>x.truncated=true,x=>x.sequence=4,x=>x.palCount=1]){const n=plain(r);change(n);assert.equal(peopleHomeControl([n],makeFrame(5)),null);}const f=fixture(),prepared=f.prepare([r],{kind:'home'}),armed=f.arm(prepared);const e={...f.event(),clientX:130,clientY:180};f.click(e);const p=f.audit.trusted.complete(armed.intentOrdinal);assert.equal(p.kind,'home');});
test('driver lifetime bounds and retirement release listeners and private references without touching input',()=>{const f=fixture(),armed=f.arm(f.prepare());f.click();assert(f.audit.trusted.complete(armed.intentOrdinal));assert.equal(f.audit.trusted.readProofMetadata().length,1);const id=f.audit.trusted.readProofMetadata()[0].proofOrdinal;f.audit.proofs.release(id);f.audit.trusted.forgetProof(id);assert.equal(f.audit.trusted.readProofMetadata().length,0);f.audit.trusted.retire();f.audit.trusted.retire();assert(f.listeners.every(l=>l.options.signal.aborted));assert.equal(f.audit.trusted.diagnostics().recordCount,0);assert.throws(()=>f.arm(f.prepare()));});
test('fixture observer source cannot generate input focus DOM editing or navigation',()=>{const source=readFileSync(new URL('./tablet-people-trusted-binding.mjs',import.meta.url),'utf8');for(const forbidden of ['dispatchEvent(','preventDefault(','stopPropagation(','setPointerCapture(','\.focus(','\.send(','\.click(','\.value='])assert(!source.includes(forbidden));assert(source.includes('capture:true'));assert(source.includes('sample(canvas,p)')||source.includes('audit.proofs.sample(el,p)'));});
const runner=readFileSync(new URL('./tablet-people-session.mjs',import.meta.url),'utf8');
test('shipping production stale checks untouched while runner requires actual physical event/production packet proofs',()=>{assert(tablet.includes('frameSequence:held?.sequence??this.displayedFrameSequence'));assert(runner.includes('await page.mouse.click(sampled.x,sampled.y)'));assert(runner.includes('trusted.complete(id)'));assert(runner.includes('assert(proof.press.accepted&&proof.release.accepted)'));assert(runner.includes('a.trusted?.wire(m)'));assert(runner.includes('a.navigation=m.sequence'));assert(runner.includes('a.trusted?.invalidate()'));assert(!runner.includes('freshPeopleClickCoordinates'));});
test('original native Home/open deadlines account for added calibration within the same20s/30s instead of extra waits',()=>{assert(runner.includes('homeDeadline=Date.now()+20000'));assert(runner.includes("control(undefined,'home',remaining)"));const audio=readFileSync(new URL('./tablet-people-audio.mjs',import.meta.url),'utf8');const section=audio.slice(audio.indexOf('export async function reopenPeopleSyntheticTablet('),audio.indexOf('/** Fixed scalar projection'));assert(section.includes('deadline=Date.now()+30000'));assert(section.includes('timeout:Math.max(1,deadline-Date.now())'));assert(section.includes('enterPeople({deadline})'));});
test('same actual QML Home walk emits only unique source-bound PEOPLE7 buttons and rejects ambiguity/hidden ancestry',()=>{
 const run=buttons=>{const logs=[],root={children:[]},parent={parent:root,children:[],visible:true,opacity:1};root.children.push(parent);for(const fields of buttons){parent.children.push({parent,children:[],visible:true,opacity:1,text:'PEOPLE',sortOrder:7,isActive:false,buttonIndex:1,enabled:true,width:129,height:129,mapToItem:()=>({x:175,y:255}),...fields});}const code=PEOPLE_AUDIT_QML.slice(PEOPLE_AUDIT_QML.indexOf('    function peopleAudit'));const ctx={peopleAuditCount:0,peopleAuditBytes:0,Users:{getIgnoreStatus:()=>false},console:{log:line=>logs.push(line)}};vm.runInNewContext(code,ctx);ctx.peopleAudit(root,{sequence:5,revision:2,navigationSequence:3});return parsePeopleAudit(logs.join('\n'))[0];};
 const one=run([{}]);assert.equal(one.homeButtonCount,1);assert(peopleHomeControl([one],makeFrame(5)));for(const widgets of [[{},{}],[{sortOrder:8}],[{visible:false}],[{enabled:false}],[{enabled:undefined}]]){const r=run(widgets);assert.equal(peopleHomeControl([r],makeFrame(5)),null);}
});
test('malformed Home record cannot bypass coupled count/control or exported parser guards',()=>{for(const change of [r=>delete r.homeButtonCount,r=>delete r.homeButton,r=>r.homeButton.enabled='true',r=>r.homeButton.rect.width=0])assert.throws(()=>encodeValidatedPeopleRecords([record(5,{home:true,change})]));});
test('actual event-proof adoption handles delayed Node ledger order with exact sorted owners then private flush/releases',async()=>{
 const f=fixture(),prepared=f.prepare([record(5),record(6)]),armed=f.arm(prepared);f.setFrame(makeFrame(6));f.click();f.audit.trusted.complete(armed.intentOrdinal);
 const later=f.audit.proofs.sample(f.canvas,{...makeFrame(6),rect:{x:100,y:150,width:24,height:24}}),ledger=new Map();
 const metadata=p=>({file:'owned-'+p.proofOrdinal+'.png',displayedFile:null,frame:plain(p.frame),canvas:plain(p.canvas),image:plain(p.image)});
 ledger.set(prepared.result.sample.proofOrdinal,metadata(prepared.result.sample));ledger.set(later.proofOrdinal,metadata(later));
 const body=runner.slice(runner.indexOf('async function flushControlProofs'),runner.indexOf('async function waitFor'));
 const page={async evaluate(fn,arg){const result=vm.runInNewContext('('+fn.toString()+')',f.ctx)(arg);return result===undefined?undefined:plain(result);}},writes=[];
 const flush=Function('assert','pages','privateControlProofs','assertPaintedPeopleControl','Buffer','writeFile','path','directory',body+'\nreturn flushControlProofs;')(assert,[page],ledger,image=>assert(paintedPeopleControl(image)),Buffer,async(name,data,options)=>writes.push({name,data,options}),{join:(...p)=>p.join('/')},'owned-evidence');
 await flush();assert.equal(writes.length,3);assert(writes.every(w=>w.options.flag==='wx'&&w.options.mode===0o600));assert.equal(ledger.size,0);assert.equal(f.audit.proofs.metadata().bytes,0);assert.equal(f.audit.trusted.readProofMetadata().length,0);
});
test('actual failure finally never changes primary error when private proof read/write refuses',async()=>{const statement='try{await flushControlProofs();}catch{report.privateControlEvidenceFailed=true;report.completed=false;process.exitCode=1;}';assert(runner.includes(statement));const report={completed:false,error:'original-acceptance-refused'},process={exitCode:1};await vm.runInNewContext('(async()=>{'+statement+'})',{report,process,flushControlProofs:async()=>{throw Error('owned I/O failure');}})();assert.equal(report.error,'original-acceptance-refused');assert.equal(report.privateControlEvidenceFailed,true);assert.equal(process.exitCode,1);});

// The added world-input methods are genuine production source, not pointer
// fixture methods. Select each bounded pointer/send region without erasing
// unrelated TypeScript or changing any selected production method body.
test('old broad fixture slice reproduces the typed World-X getter import failure',()=>{
 const world=slice('    get worldInputReady(','    private send(');assert.equal(methods.split('    send(value)').length,2);
 const original=methods.replace('    send(value)',world+'    send(value)');
 assert(original.includes('get worldInputReady():boolean'));
 assert.throws(()=>vm.runInNewContext('class Original {\n'+original+'\n};Original;'),{name:'SyntaxError',message:/Unexpected token ':'/});
});
test('bounded selected methods exclude only the exact intervening World-X source region',()=>{
 const world=slice('    get worldInputReady(','    private send(');
 const old=slice('    private coordinates(','    private show(')+slice('    private modifiers(','    private fit(');
 const selected=slice('    private coordinates(','    get worldInputReady(')+slice('    private send(','    private show(')+slice('    private modifiers(','    private fit(');
 assert.equal(old.split(world).length,2);assert.equal(old.replace(world,''),selected);
 assert(!methods.includes('get worldInputReady('));assert(!methods.includes('worldInputFocus('));assert(!methods.includes('worldKey(event:'));
 assert(world.includes('event.isComposing||event.defaultPrevented'));assert(world.includes("key:'x'"));
 assert.equal(typeof Actual.prototype.pointer,'function');assert.equal(typeof Actual.prototype.send,'function');assert.equal(typeof Actual.prototype.coordinates,'function');
});
