// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {gunzipSync} from 'node:zlib';import vm from 'node:vm';
import {admitServedAuthor,HISTORICAL_SERVED_SHA256,HISTORICAL_AUTHOR_SOURCE_SHA256,HISTORICAL_AUTHOR_DIAGNOSTICS_SHA256,projectAuthorAudio,createAuthorConsent} from './tablet-ptt-native-peer.mjs';
const source=await readFile(new URL('../../lab/native-participant.js',import.meta.url)),diagnostics=await readFile(new URL('../../gateway/native-avatar-sample-diagnostics.js',import.meta.url)),oldSource=gunzipSync(await readFile(new URL('./fixtures/historical-native-participant.js.gz',import.meta.url))),oldDiagnostics=gunzipSync(await readFile(new URL('./fixtures/historical-native-avatar-diagnostics.js.gz',import.meta.url))),prefix=Buffer.from('var BROWSER_LAB_AVATAR_SAMPLE_DIAGNOSTICS = true;\n'),served=Buffer.concat([prefix,oldDiagnostics,Buffer.from('\n'),oldSource]),sha=b=>createHash('sha256').update(b).digest('hex');
test('immutable historical full served bytes and both licensed source components are independently pinned',()=>{assert.equal(sha(oldSource),HISTORICAL_AUTHOR_SOURCE_SHA256);assert.equal(sha(oldDiagnostics),HISTORICAL_AUTHOR_DIAGNOSTICS_SHA256);assert.equal(sha(served),HISTORICAL_SERVED_SHA256);assert.deepEqual(admitServedAuthor(served,{source,diagnostics}),{sourceSHA256:HISTORICAL_AUTHOR_SOURCE_SHA256,diagnosticsSHA256:HISTORICAL_AUTHOR_DIAGNOSTICS_SHA256,servedSourceSHA256:HISTORICAL_SERVED_SHA256,registration:'historical-full-no-mode'});});
test('new current plain/full/passive registration remains exact and separately identified',()=>{for(const mode of ['plain','full','passive']){const input=mode==='plain'?source:Buffer.concat([prefix,Buffer.from('var BROWSER_LAB_AVATAR_SAMPLE_DIAGNOSTICS_MODE = '+JSON.stringify(mode)+';\n'),diagnostics,Buffer.from('\n'),source]);assert.equal(admitServedAuthor(input,{source,diagnostics}).registration,'current-'+mode);}});
test('no historic prefix/suffix or mode spoof can admit modified native author/helper bytes',()=>{for(const input of [Buffer.concat([served,Buffer.from('\n')]),Buffer.concat([prefix,oldDiagnostics,Buffer.from('\n'),source]),Buffer.concat([prefix,diagnostics,Buffer.from('\n'),oldSource]),Buffer.concat([prefix,Buffer.from('var injected=true;\n'),oldDiagnostics,Buffer.from('\n'),oldSource]),Buffer.concat([Buffer.from('var BROWSER_LAB_AVATAR_SAMPLE_DIAGNOSTICS = false;\n'),oldDiagnostics,Buffer.from('\n'),oldSource])])assert.throws(()=>admitServedAuthor(input,{source,diagnostics}));});
test('historical admission does not excuse changed current source pins or unbounded/invalid inputs',()=>{assert.throws(()=>admitServedAuthor(served,{source:Buffer.concat([source,Buffer.from('\n')]),diagnostics}));assert.throws(()=>admitServedAuthor(served,{source,diagnostics:Buffer.concat([diagnostics,Buffer.from('\n')])}));assert.throws(()=>admitServedAuthor('not bytes',{source,diagnostics}));assert.throws(()=>admitServedAuthor(Buffer.alloc(131073),{source,diagnostics}));});
test('actual historical authored script command loop unmutes/restores with identical private command-applied observations',()=>{const timers=[],requests=[],records=[],Audio={},ending={connect(){}};const ctx={Audio,Render:{},Window:{},MyAvatar:{},location:{isConnected:false},Script:{setInterval(fn,ms){timers.push({fn,ms});},scriptEnding:ending},XMLHttpRequest:function(){this.open=()=>{};this.send=()=>requests.push(this);},print(line){if(line.startsWith('BROWSER_LAB '))records.push(JSON.parse(line.slice(12)));},About:{version:'f91'},Entities:{canRez:()=>false,addEntity(){throw Error('No native entity write');},deleteEntity(){throw Error('No native entity delete');}}};vm.runInNewContext(served.toString(),ctx);assert.equal(Audio.muted,true);const poll=timers.find(x=>x.ms===500).fn;function command(sequence,muted){poll();const r=requests.at(-1);r.readyState=4;r.status=200;r.responseText=JSON.stringify({sequence,muted});r.onreadystatechange();}command(5,false);assert.equal(Audio.muted,false);command(5,true);assert.equal(Audio.muted,false,'Old duplicate command must not overwrite state');command(6,true);assert.equal(Audio.muted,true);const applied=records.filter(r=>r.kind==='command-applied');assert.equal(applied.length,2);assert.deepEqual(JSON.parse(JSON.stringify(applied.map(r=>r.data))),[{sequence:5,muted:false},{sequence:6,muted:true}]);const last=applied.at(-1),text='BROWSER_LAB '+JSON.stringify(last)+'\nBROWSER_LAB '+JSON.stringify({kind:'observation',at:last.at+1,data:{muted:true}});assert(projectAuthorAudio(text,{sequence:6,muted:true,since:last.at,now:last.at+2}).observationAfterCommand);});
test('production transaction confirms the admitted historical author hash instead of falsely claiming current source',async()=>{let state=true;const actor=createAuthorConsent({sourceSHA256:HISTORICAL_AUTHOR_SOURCE_SHA256,now:()=>1000,wait:async()=>{},identity:async()=>{},readCommand:async()=>({sequence:0}),projection:async()=>({lastSequence:0,commandApplied:true,observationAfterCommand:true,observationFresh:true,observationMuted:state}),writeCommand:async v=>{state=v.muted;}});const r=await actor.setMuted(false);assert.equal(r.sourceSHA256,HISTORICAL_AUTHOR_SOURCE_SHA256);await actor.restore();await actor.close();assert.equal(state,true);});
