// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import {locateNativeGraphicsPopup,stableNativePopup,measureNativeGraphicsPopup} from './tablet-graphics-popup.mjs';
const blank=()=>Array.from({length:330},(_,i)=>({y:70+i,dark:0,highlight:0,text:0,hash:i}));
function paint(rows,{top=140,count=4,height=40,selected=3}={}){for(const r of rows){if(r.y<top||r.y>=top+count*height)continue;const index=Math.floor((r.y-top)/height),within=(r.y-top)%height;r.dark=index===selected?0:170;r.highlight=index===selected?170:0;r.text=within>=14&&within<25?15:0;}return rows;}
test('four painted native rows identify Custom3 and ArrowUp2 exactly',()=>{for(const selected of [0,1,2,3]){const found=locateNativeGraphicsPopup(paint(blank(),{selected}));assert.equal(found.highlightedIndex,selected);assert.equal(found.options.length,4);assert(found.options.every(r=>r.glyphRows>=3));}});
test('closed hover, missing fourth row, empty glyphs, multiselection and clipped popup refuse readiness',()=>{assert.equal(locateNativeGraphicsPopup(blank()),null);assert.equal(locateNativeGraphicsPopup(paint(blank(),{count:3})),null);const noText=paint(blank());for(const r of noText)r.text=0;assert.equal(locateNativeGraphicsPopup(noText),null);const allGray=paint(blank());for(const r of allGray)if(r.dark)r.highlight=r.dark;assert.equal(locateNativeGraphicsPopup(allGray),null);const clipped=paint(blank());for(const r of clipped)if(r.y>=260){r.dark=0;r.highlight=0;r.text=0;}assert.equal(locateNativeGraphicsPopup(clipped),null);});
test('ambiguous separate four-row popups and malformed measurements fail',()=>{const rows=paint(paint(blank(),{top:70,height:24}),{top:200,height:24});assert.throws(()=>locateNativeGraphicsPopup(rows),/Ambiguous/);const malformed=blank();malformed[0].dark=188;assert.throws(()=>locateNativeGraphicsPopup(malformed));assert.throws(()=>locateNativeGraphicsPopup([]));});
test('stable popup requires two different actual capture sequences, same revision, geometry, index and pixel fingerprint',()=>{const popup=locateNativeGraphicsPopup(paint(blank()));const a={sequence:7,revision:1,popup},b={sequence:8,revision:1,popup:{...popup}};assert(stableNativePopup(a,b));assert(!stableNativePopup(a,a));for(const [key,value] of [['top',popup.top+1],['height',popup.height+1],['highlightedIndex',0],['fingerprint',popup.fingerprint+1]])assert(!stableNativePopup(a,{...b,popup:{...popup,[key]:value}}));assert(!stableNativePopup(a,{...b,revision:2}));assert(!stableNativePopup({...a,popup:null},b));});
test('actual RGBA measurement detects pinned gray delegate and dark background, excludes closed #333 card and bounds allocation',()=>{const bytes=new Uint8ClampedArray(480*706*4);for(let i=0;i<bytes.length;i+=4){bytes[i]=bytes[i+1]=bytes[i+2]=28;bytes[i+3]=255;}for(let y=140;y<300;y++)for(let x=272;x<459;x++){const offset=(y*480+x)*4,selected=y>=260;const color=selected?128:3;bytes[offset]=bytes[offset+1]=bytes[offset+2]=color;const within=(y-140)%40;if(within>=14&&within<25&&x<292)bytes[offset]=bytes[offset+1]=bytes[offset+2]=255;}
 const canvas={width:480,height:706,getContext:()=>({getImageData:()=>({data:bytes})})},rect={x:0,y:0,width:480,height:706};assert.equal(locateNativeGraphicsPopup(measureNativeGraphicsPopup(canvas,rect)).highlightedIndex,3);for(let i=0;i<bytes.length;i+=4)bytes[i]=bytes[i+1]=bytes[i+2]=51;assert.equal(locateNativeGraphicsPopup(measureNativeGraphicsPopup(canvas,rect)),null);assert.throws(()=>measureNativeGraphicsPopup({...canvas,width:4000,height:4000},rect));assert.throws(()=>measureNativeGraphicsPopup(canvas,{...rect,width:600}));});
