// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
import {peopleProofQueueInstallerSource,samplePeopleDisplayedControl,paintedPeopleControl,assertPaintedPeopleControl,freshPeopleClickCoordinates,incrementPeopleRefusal} from './tablet-people-proof-queue.mjs';
const frame=()=>({sequence:5,revision:2,navigationSequence:3,width:480,height:706,surface:'tablet',tabletRect:{x:0,y:0,width:480,height:706},data:Buffer.from('owned native PNG').toString('base64')});
const point=()=>({sequence:5,revision:2,navigationSequence:3,x:112,y:162,rect:{x:100,y:150,width:24,height:24}});
const plain=v=>JSON.parse(JSON.stringify(v));
function fixture(){let reads=0;const ctx={window:{__peopleAudit:{frame:frame()}},atob:v=>Buffer.from(v,'base64').toString('binary')};
 const el={width:480,height:706,getBoundingClientRect:()=>({x:10,y:20,width:240,height:353}),toDataURL:()=> 'data:image/png;base64,'+Buffer.from('owned displayed PNG').toString('base64'),getContext:()=>({getImageData(x,y,w,h){reads++;const data=new Uint8ClampedArray(w*h*4);for(let i=0;i<data.length;i+=4)data.set(i<data.length/2?[20,20,20,255]:[230,230,230,255],i);return {data};}})};
 vm.runInNewContext(peopleProofQueueInstallerSource(samplePeopleDisplayedControl,paintedPeopleControl),ctx);return {ctx,el,queue:ctx.window.__peopleProofFactory(),click:vm.runInNewContext('('+freshPeopleClickCoordinates.toString()+')',ctx),reads:()=>reads};}
const source=readFileSync(new URL('./tablet-people-session.mjs',import.meta.url),'utf8');
test('same original >20 contrast threshold rejects20, accepts21 and retains area bounds',()=>{const image=value=>({width:8,height:8,rgba:Array.from({length:256},(_,i)=>i%4===3?255:i<128?10:10+value)});assert.equal(paintedPeopleControl(image(20)),false);assert.equal(paintedPeopleControl(image(21)),true);assert.throws(()=>assertPaintedPeopleControl(image(20)));assert.equal(paintedPeopleControl({...image(21),width:7}),false);});
test('control response is small; original synchronous contrast and native witness retained privately',()=>{const f=fixture(),s=f.queue.sample(f.el,point());assert.equal(s.refusal,null);assert(JSON.stringify(s).length<512);assert(!('data'in s.frame));assert(!('rgba'in s.image));assert(!('nativePNG'in s));const p=f.queue.read(s.proofOrdinal);assertPaintedPeopleControl(p.image);assert.equal(p.nativePNG,frame().data);assert.equal(f.reads(),1);f.queue.release(s.proofOrdinal);assert.deepEqual(plain(f.queue.metadata()),{ordinals:[],count:0,bytes:0});});
test('Home PNG pair retained without bulk transfer before strict unchanged physical route',()=>{const f=fixture(),s=f.queue.capture(f.el);assert.equal(s.refusal,null);assert(JSON.stringify(s).length<512);assert(!('data'in s.frame));assert.equal(s.image,null);const p=f.queue.read(s.proofOrdinal);assert.equal(p.nativePNG,frame().data);assert.equal(p.displayedPNG,f.el.toDataURL().split(',')[1]);assert.equal(f.click(f.el,{...point(),x:240,y:320}).refusal,null);});
test('counterexample old bulk witness/RPC turn permits ACK6 and fresh source CAS still refuses5',async()=>{const f=fixture(),s=f.queue.sample(f.el,point());const full=f.queue.read(s.proofOrdinal);assertPaintedPeopleControl(full.image);await Promise.resolve().then(()=>f.ctx.window.__peopleAudit.frame={...frame(),sequence:6});assert.equal(f.click(f.el,point()).refusal,'frame-sequence-changed');assert.equal(f.queue.sample(f.el,point()).refusal,'frame-sequence-changed');assertPaintedPeopleControl(f.queue.read(s.proofOrdinal).image);});
test('all sequence revision and navigation mismatches reject before pixel reads',()=>{for(const [key,reason]of [['sequence','frame-sequence-changed'],['revision','frame-revision-changed'],['navigationSequence','frame-navigation-changed']]){const f=fixture();f.ctx.window.__peopleAudit.frame[key]++;assert.equal(f.queue.sample(f.el,point()).refusal,reason);assert.equal(f.click(f.el,point()).refusal,reason);assert.equal(f.reads(),0);assert.equal(f.queue.metadata().count,0);}});
test('pixel-read and native-PNG-validation reentrancy cannot mix frames or insert evidence',()=>{for(const kind of ['pixels','png','displayed']){const f=fixture(),change=()=>f.ctx.window.__peopleAudit.frame={...frame(),sequence:6};if(kind==='pixels'){const get=f.el.getContext;f.el.getContext=()=>({getImageData(...args){const r=get().getImageData(...args);change();return r;}});}else if(kind==='png')f.ctx.atob=v=>{change();return Buffer.from(v,'base64').toString('binary');};else f.el.toDataURL=()=>{change();return 'data:image/png;base64,'+frame().data;};assert.equal((kind==='displayed'?f.queue.capture(f.el):f.queue.sample(f.el,point())).refusal,'frame-changed-during-sample');assert.equal(f.queue.metadata().count,0);}});
test('unpainted control returns refusal for original20s wait rather than a changed success/threshold',()=>{const f=fixture();f.el.getContext=()=>({getImageData:(x,y,w,h)=>({data:new Uint8ClampedArray(w*h*4).fill(255)})});assert.equal(f.queue.sample(f.el,point()).refusal,'control-not-painted');assert.equal(f.queue.metadata().count,0);});
test('mapping bounds remain strict including negative/outside/too small/oversized area',()=>{for(const change of [p=>p.rect.x=-1,p=>p.rect.y=700,p=>p.rect.width=7,p=>{p.rect.width=257;p.rect.height=257;}]){const f=fixture(),p=point();change(p);assert.equal(f.queue.sample(f.el,p).refusal,'mapped-control-out-of-bounds');assert.equal(f.queue.metadata().count,0);}});
test('invalid empty missing and over2MiB PNG cannot qualify control or Home',()=>{for(const png of ['',null,'not valid!',Buffer.alloc(2*1024*1024+1).toString('base64')]){const f=fixture();f.ctx.window.__peopleAudit.frame.data=png;assert.throws(()=>f.queue.sample(f.el,point()));assert.throws(()=>f.queue.capture(f.el));assert.equal(f.queue.metadata().count,0);}const f=fixture();f.el.width=4096;f.el.height=4096;assert.equal(f.queue.capture(f.el).refusal,'capture-canvas-bounds-refused');});
test('16 shared control/Home rows refuse before pixels; release admits a new unique handle',()=>{const f=fixture(),ids=[];for(let i=0;i<16;i++)ids.push((i%2?f.queue.capture(f.el):f.queue.sample(f.el,point())).proofOrdinal);const reads=f.reads();assert.throws(()=>f.queue.sample(f.el,point()));assert.throws(()=>f.queue.capture(f.el));assert.equal(f.reads(),reads);f.queue.release(ids[0]);assert.throws(()=>f.queue.read(ids[0]));assert(f.queue.sample(f.el,point()).proofOrdinal>ids.at(-1));});
test('32MiB bound accounts both HomePNG UTF16 strings plus ROI and metadata',()=>{const f=fixture(),large=Buffer.alloc(2*1024*1024).toString('base64');f.ctx.window.__peopleAudit.frame.data=large;f.el.toDataURL=()=> 'data:image/png;base64,'+large;let admitted=0;while(admitted<16){try{f.queue.capture(f.el);admitted++;}catch(e){assert.match(e.message,/byte bound/);break;}}assert(admitted>0&&admitted<16);assert(f.queue.metadata().bytes<=32*1024*1024);f.queue.retire();});
test('copies cannot mutate original pixels nested tablet rect or canvas metadata',()=>{const f=fixture(),id=f.queue.sample(f.el,point()).proofOrdinal,p=f.queue.read(id);p.image.rgba.fill(0);p.frame.tabletRect.width=1;p.canvas.width=1;const next=f.queue.read(id);assertPaintedPeopleControl(next.image);assert.equal(next.frame.tabletRect.width,480);assert.equal(next.canvas.width,480);});
test('retirement releases bytes and prevents prior handles surviving new queue',()=>{const f=fixture(),id=f.queue.sample(f.el,point()).proofOrdinal;f.queue.retire();f.queue.retire();for(const act of [()=>f.queue.sample(f.el,point()),()=>f.queue.read(id),()=>f.queue.release(id),()=>f.queue.metadata()])assert.throws(act);const fresh=f.ctx.window.__peopleProofFactory();assert.equal(fresh.metadata().count,0);assert.throws(()=>fresh.read(id));});
test('refusal counters accept only fixed bounded labels',()=>{const counts={};incrementPeopleRefusal(counts,'frame-sequence-changed');assert.equal(counts['frame-sequence-changed'],1);counts['frame-sequence-changed']=2147483647;incrementPeopleRefusal(counts,'frame-sequence-changed');assert.equal(counts['frame-sequence-changed'],2147483647);assert.throws(()=>incrementPeopleRefusal(counts,'private'));counts['frame-sequence-changed']=-1;assert.throws(()=>incrementPeopleRefusal(counts,'frame-sequence-changed'));});
test('actual harness samples exact native control then requires passive event and production press/release proofs',()=>{const control=source.slice(source.indexOf(' async function control('),source.indexOf(' async function clickPoint('));assert(control.includes('trusted.prepare(value,text)'));assert(control.includes('timeout=20000'));for(const token of ['image.rgba','nativePNG','writeFile('])assert(!control.includes(token));const click=source.slice(source.indexOf(' async function clickPoint('),source.indexOf(" report.step='home-native-tablet'"));assert(click.includes('trusted.arm(value,text,expected)'));assert(click.includes('assert.equal(sampled.refusal,null'));assert(click.includes('await page.mouse.click(sampled.x,sampled.y)'));assert(click.includes('trusted.complete(id)'));assert(click.includes('proof.press.accepted&&proof.release.accepted'));assert(click.includes('assert.deepEqual(proof.press.frame,proof.release.frame)'));assert(!click.includes('boundingBox'));});
test('actual native Home state/new frame keeps original total20s bound and only native-audited Homecontrol click',()=>{const home=source.slice(source.indexOf(" report.step='home-native-tablet'"),source.indexOf(" report.step='calibrate-native-ignore-control'"));assert(home.includes("getByRole('button',{name:'Home',exact:true}).click()"));assert(home.includes("state?.screen==='Home'"));assert(home.includes('homeDeadline=Date.now()+20000'));assert(home.includes("retainCapture('home')"));assert(home.includes("control(undefined,'home',remaining)"));assert(home.indexOf('clickPoint(')<home.indexOf('flushControlProofs()'));});
test('all original geometry reciprocal audio and cleanup predicates remain independently required',()=>{for(const token of ['before.geometry.remoteRoots>1','geometryMeshes>0','window.__peopleGeometryProof.ignored(value)','window.__peopleGeometryProof.restored(value)','timeout:ignored?15000:90000','await reciprocal(true)','await reciprocal(false)','runPeopleSyntheticAudioSuppression({pages,waitFor','baselineIdentity','Both exact owned native profiles removed','report.cleanupVerified=profiles.length===2&&pages.length===2'])assert(source.includes(token),token);assert(source.includes('proofs?.retire()'));assert(source.includes('privateControlEvidenceFailed=true;report.completed=false;process.exitCode=1;'));});
function extractedFlush(f,entries,writeFile){const body=source.slice(source.indexOf('async function flushControlProofs'),source.indexOf('async function waitFor'));f.ctx.window.__peopleAudit.proofs=f.queue;const page={async evaluate(fn,arg){const value=vm.runInNewContext('('+fn.toString()+')',f.ctx)(arg);return value===undefined?undefined:plain(value);}};return Function('assert','pages','privateControlProofs','assertPaintedPeopleControl','Buffer','writeFile',body+'\nreturn flushControlProofs;')(assert,[page],entries,assertPaintedPeopleControl,Buffer,writeFile);}
function tracked(f,capture=false){const p=capture?f.queue.capture(f.el):f.queue.sample(f.el,point());return new Map([[p.proofOrdinal,{file:'owned-native.png',displayedFile:capture?'owned-displayed.png':null,frame:plain(p.frame),canvas:plain(p.canvas),image:plain(p.image)}]]);}
test('actual flush reasserts original pixels and exact PNGpair/private write then releases ownership',async()=>{for(const capture of [false,true]){const f=fixture(),entries=tracked(f,capture),writes=[];await extractedFlush(f,entries,async(file,png,options)=>{assert.equal(f.queue.metadata().count,1);writes.push({file,bytes:png.length,options});})();assert.equal(writes.length,capture?2:1);for(const w of writes)assert.deepEqual(w.options,{flag:'wx',mode:0o600});assert.equal(entries.size,0);assert.equal(f.queue.metadata().count,0);assert.equal(f.queue.metadata().bytes,0);}});
test('mismatched or unpainted retained proof refuses before write or release',async()=>{for(const corrupt of [p=>p.frame.sequence++,p=>p.image.rgba.fill(0)]){const f=fixture(),entries=tracked(f),read=f.queue.read;f.queue.read=id=>{const p=read(id);corrupt(p);return p;};let writes=0;await assert.rejects(extractedFlush(f,entries,async()=>writes++)());assert.equal(writes,0);assert.equal(entries.size,1);assert.equal(f.queue.metadata().count,1);f.queue.retire();}});
test('private I/O failure remains failure and retained evidence releases only after completed write',async()=>{const f=fixture(),entries=tracked(f),original=new Error('authored I/O failure');await assert.rejects(extractedFlush(f,entries,async()=>{throw original;})(),e=>e===original);assert.equal(entries.size,1);assert.equal(f.queue.metadata().count,1);await extractedFlush(f,entries,async()=>{})();assert.equal(entries.size,0);assert.equal(f.queue.metadata().count,0);});
