// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
import {CREATE_READINESS_QUERY,instrumentCreateReadiness,parseCreateReadiness,readyCreateView,controlPaintBox,headingPaintBox,controlTabletPoint,readyFilteredOwnList,PREFIX} from './tablet-create-readiness.mjs';
const own='{00000000-0000-4000-8000-000000000001}',rect={x:36,y:58,width:350,height:25,visible:true,enabled:true};
const frame={sequence:3,revision:1,width:480,height:706};
function entry(route='properties'){return {sequence:3,revision:1,web:{x:0,y:40,width:480,height:666,loading:false},dom:{route,readyState:'complete',eventBridge:true,fontsStatus:'loaded',fonts:[{family:'Raleway-Regular',status:'loaded'}],requiredFonts:['Raleway-Regular','Raleway-Bold','FiraSans-SemiBold'].map(family=>({family,loaded:true})),viewport:{width:480,height:666},labelCount:8,rowCount:8,selectedUUID:own,controls:Object.fromEntries(['property-name','property-id','tab-base','filter-search','delete','entity-table-header','entity-table-body'].map(id=>[id,{...rect}]))}};}
test('reject stale Properties screenshot as List and stale capture/revision',()=>{assert.equal(readyCreateView([entry()],frame,'list',own),null);for(const key of ['sequence','revision']){const e=entry();e[key]++;assert.equal(readyCreateView([e],frame,'properties',own),null);}assert(readyCreateView([entry()],frame,'properties',own));assert(readyCreateView([entry('list')],frame,'list',own));});
test('reject skeleton, unloaded font, missing bridge, wrong own UUID and empty List',()=>{for(const mutate of [e=>e.dom.labelCount=0,e=>e.dom.readyState='loading',e=>e.dom.eventBridge=false,e=>e.dom.fontsStatus='loading',e=>e.dom.requiredFonts[0].loaded=false,e=>e.dom.selectedUUID=own.replace(/1}/,'2}'),e=>e.web.loading=true,e=>e.dom.controls['property-name'].visible=false]){const e=entry();mutate(e);assert.equal(readyCreateView([e],frame,'properties',own),null);}const list=entry('list');list.dom.rowCount=0;assert.equal(readyCreateView([list],frame,'list',own),null);});
test('fixed query reads exact native page without exporting URL, input text or executing events',()=>{const elements=new Map(['property-name','property-id','tab-base','tab-shape','tab-spatial'].map(id=>[id,{value:id==='property-id'?own:'sensitive display name',getBoundingClientRect:()=>rect}]));const fonts={status:'loaded',forEach:fn=>fn({family:'Raleway-Regular',status:'loaded'}),check:()=>true};const context={location:{pathname:'/approved/scripts/system/create/entityProperties/html/entityProperties.html'},window:{EventBridge:{emitWebEvent(){throw Error('No writes permitted');}}},EventBridge:{emitWebEvent(){throw Error('No writes permitted');}},document:{readyState:'complete',fonts,getElementById:id=>elements.get(id),querySelectorAll:selector=>selector.includes('label')?Array(8):[]},getComputedStyle:()=>({display:'block',visibility:'visible'}),innerWidth:480,innerHeight:666};const result=vm.runInNewContext(CREATE_READINESS_QUERY,context,{timeout:1000});assert.equal(result.route,'properties');assert.equal(result.selectedUUID,own);assert(!JSON.stringify(result).includes('sensitive'));context.location.pathname='/unapproved.html';assert.equal(vm.runInNewContext(CREATE_READINESS_QUERY,context),null);});
test('instrument actual capture helper only at exact capture boundary and refuse duplicate/unknown source',async()=>{const source=await readFile(process.env.OVERTE_CREATE_SOURCE_CLIENT?process.env.OVERTE_CREATE_SOURCE_CLIENT+'/gateway/tablet-capture.qml':new URL('../../gateway/tablet-capture.qml',import.meta.url),'utf8');const result=instrumentCreateReadiness(source);assert(result.includes('createAudit(item,message);'));assert.equal(result.split('function createAudit(').length,2);assert.equal(result.split('runJavaScript(').length-source.split('runJavaScript(').length,1);assert.throws(()=>instrumentCreateReadiness(result));assert.throws(()=>instrumentCreateReadiness('unknown QML'));});
test('execute generated QML function; only exact visible native route runs fixed query and pending callbacks are bounded',async()=>{const source=await readFile(process.env.OVERTE_CREATE_SOURCE_CLIENT?process.env.OVERTE_CREATE_SOURCE_CLIENT+'/gateway/tablet-capture.qml':new URL('../../gateway/tablet-capture.qml',import.meta.url),'utf8');const qml=instrumentCreateReadiness(source),script=qml.slice(qml.indexOf('    function createAudit('),qml.indexOf('    function fromScript('));const callbacks=[],logs=[],context={createAuditPending:{},console:{log:value=>logs.push(value)}};vm.runInNewContext(script,context);const node={url:'file:///approved/scripts/system/create/entityProperties/html/entityProperties.html',visible:true,width:480,height:666,mapToItem:()=>({x:0,y:40}),children:[],runJavaScript:(query,callback)=>{assert.equal(query,CREATE_READINESS_QUERY);callbacks.push(callback);}};const item={visible:true,children:[node]};context.createAudit(item,{sequence:3,revision:1});context.createAudit(item,{sequence:4,revision:1});assert.equal(callbacks.length,1);callbacks.shift()(entry().dom);assert.equal(parseCreateReadiness(logs.join('\n'))[0].sequence,3);node.url='https://unapproved.example/page.html';context.createAudit(item,{sequence:4,revision:1});assert.equal(callbacks.length,0);node.url='file:///approved/scripts/system/create/entityProperties/html/entityProperties.html';context.createAudit(item,{sequence:5,revision:1});node.visible=false;callbacks.shift()(entry().dom);assert.equal(logs.length,1);});
test('parse bounded private records and constrain control paint crop to exact frame',()=>{const e=entry();assert.deepEqual(parseCreateReadiness('ordinary log\n'+PREFIX+JSON.stringify(e)),[e]);assert.deepEqual(controlPaintBox(e,'property-id',frame),{x:36,y:98,width:350,height:25});e.web.x=480;assert.throws(()=>controlPaintBox(e,'property-id',frame));assert.throws(()=>parseCreateReadiness(PREFIX+'{bad'));assert.throws(()=>parseCreateReadiness('x'.repeat(4*1024*1024+1)));});
test('exact selected native Properties section gates calibration rather than preceding base/Shape capture',()=>{const e=entry();e.dom.section='base';assert.equal(readyCreateView([e],frame,'properties',own,'shape'),null);e.dom.section='shape';e.dom.controls['section-title']={...rect};e.dom.controls['property-name'].visible=false;e.dom.controls['property-id'].visible=false;e.dom.controls['property-color']={...rect};assert(readyCreateView([e],frame,'properties',own,'shape'));assert.equal(readyCreateView([e],frame,'properties',own,'spatial'),null);e.dom.section='spatial';for(const axis of ['x','y','z'])e.dom.controls['property-localDimensions-'+axis]={...rect};assert(readyCreateView([e],frame,'properties',own,'spatial'));e.dom.controls['property-localDimensions-x'].enabled=false;assert.equal(readyCreateView([e],frame,'properties',own,'spatial'),null);});
test('genuine color picker requires active own swatch and exactly three visible editable RGB controls',()=>{const e=entry();e.dom.section='shape';e.dom.controls['section-title']={...rect};e.dom.colorPickerActive=false;for(const channel of ['red','green','blue'])e.dom.controls['picker-'+channel]={...rect};assert.equal(readyCreateView([e],frame,'properties',own,'colorPicker'),null);e.dom.colorPickerActive=true;assert(readyCreateView([e],frame,'properties',own,'colorPicker'));e.dom.controls['picker-green']=null;assert.equal(readyCreateView([e],frame,'properties',own,'colorPicker'),null);});
test('fixed native query emits section and rejects multiple visible color pickers without exposing values',()=>{const element={value:own,getAttribute:name=>name==='active'?'true':null,getBoundingClientRect:()=>rect};const context={currentTab:'shape',location:{pathname:'/approved/scripts/system/create/entityProperties/html/entityProperties.html'},window:{EventBridge:{emitWebEvent(){throw Error('No writes');}}},EventBridge:{emitWebEvent(){throw Error('No writes');}},document:{readyState:'complete',fonts:{status:'loaded',forEach(){},check:()=>true},getElementById:()=>element,querySelectorAll:selector=>selector.startsWith('.colpick')?[element]:[]},getComputedStyle:()=>({display:'block',visibility:'visible'}),innerWidth:480,innerHeight:666};let result=vm.runInNewContext(CREATE_READINESS_QUERY,context);assert.equal(result.section,'shape');assert.equal(result.colorPickerActive,true);assert.equal(result.controls['picker-red'].visible,true);context.document.querySelectorAll=selector=>selector.startsWith('.colpick')?[element,element]:[];result=vm.runInNewContext(CREATE_READINESS_QUERY,context);assert.equal(result.controls['picker-red'],null);context.document.querySelectorAll=selector=>selector.startsWith('.colpick')?Array.from({length:65},()=>element):[];result=vm.runInNewContext(CREATE_READINESS_QUERY,context);assert.equal(result.controls['picker-red'],null);context.currentTab='scripts';assert.equal(vm.runInNewContext(CREATE_READINESS_QUERY,context).section,null);});

test('non-base sections keep the hidden owned UUID but require a painted native heading',()=>{const e=entry();e.dom.section='shape';e.dom.controls['property-color']={...rect};e.dom.controls['property-name'].visible=false;e.dom.controls['property-id'].visible=false;assert.equal(readyCreateView([e],frame,'properties',own,'shape'),null);e.dom.controls['section-title']={...rect};assert(readyCreateView([e],frame,'properties',own,'shape'));e.dom.selectedUUID=own.replace(/1}/,'2}');assert.equal(readyCreateView([e],frame,'properties',own,'shape'),null);});

test('actual narrow native heading paint intersects only its visible WebEngine viewport; editable boxes remain strict',()=>{const e=entry();e.dom.controls['section-title']={...rect,x:51,y:98,width:524,height:40};assert.deepEqual(headingPaintBox(e,frame),{x:51,y:138,width:429,height:40});assert.throws(()=>controlPaintBox(e,'section-title',frame));e.dom.controls['property-name']={...e.dom.controls['section-title']};assert.throws(()=>controlPaintBox(e,'property-name',frame));});
test('offscreen, absent, malformed or uncaptured native headings cannot supply pixel readiness',()=>{for(const mutate of [e=>e.dom.controls['section-title'].x=481,e=>e.dom.controls['section-title'].y=667,e=>e.dom.controls['section-title'].width=NaN,e=>e.dom.controls['section-title'].visible=false,e=>e.web.x=1,e=>e.web.height=667]){const e=entry();e.dom.controls['section-title']={...rect};mutate(e);assert.throws(()=>headingPaintBox(e,frame));}});
test('native editable control centers use current actual web and tablet geometry, not prior calibration',()=>{
 const e=entry(),f={...frame,tabletRect:{x:0,y:0,width:480,height:706}};
 assert.deepEqual(controlTabletPoint(e,'property-name',f),[211,110.5]);
 e.dom.controls['property-name']={...rect,x:80,y:200,width:140,height:28};assert.deepEqual(controlTabletPoint(e,'property-name',f),[150,254]);
 e.sequence++;assert.throws(()=>controlTabletPoint(e,'property-name',f));e.sequence--;
 for(const patch of [{x:526},{visible:false},{enabled:false},{width:Infinity}]){e.dom.controls['property-name']={...rect,...patch};assert.throws(()=>controlTabletPoint(e,'property-name',f));}
});
test('List selection waits for the actual one filtered own UUID and visible row rather than recycled row count',()=>{
 const e=entry('list'),f={...frame,tabletRect:{x:0,y:0,width:480,height:706}};
 e.dom.rowCount=23;e.dom.visibleEntityCount=1;e.dom.visibleRows=[{id:own,rect:{...rect}}];assert.deepEqual(readyFilteredOwnList([e],f,own).ownRowPoint,[211,110.5]);
 for(const mutate of [x=>x.dom.visibleEntityCount=2,x=>x.dom.visibleEntityCount=null,x=>x.dom.visibleRows[0].id=own.replace(/1}/,'2}'),x=>x.dom.visibleRows.push({...x.dom.visibleRows[0]}),x=>x.sequence++,x=>x.dom.visibleRows[0].rect.visible=false]){
  const changed=structuredClone(e);mutate(changed);assert.equal(readyFilteredOwnList([changed],f,own),null);
 }
 e.dom.visibleRows[0].rect.x=526;assert.throws(()=>readyFilteredOwnList([e],f,own));
});
test('fixed List query exports only bounded row UUID geometry and numeric footer counts, never field text or row values',()=>{
 const row={dataset:{entityID:own},getBoundingClientRect:()=>rect},empty={dataset:{entityID:'-1'},getBoundingClientRect:()=>rect};
 const elements={'visible-entities-count':{textContent:'1'},'selected-entities-count':{textContent:'0'},'filter-search':{value:'private filter',getBoundingClientRect:()=>rect}};
 const context={location:{pathname:'/approved/scripts/system/create/entityList/html/entityList.html'},window:{EventBridge:{emitWebEvent(){throw Error('No writes');}}},EventBridge:{emitWebEvent(){throw Error('No writes');}},document:{readyState:'complete',fonts:{status:'loaded',forEach(){},check:()=>true},getElementById:id=>elements[id],querySelectorAll:selector=>selector==='#entity-table-body tr'?[row,empty]:[]},getComputedStyle:()=>({display:'block',visibility:'visible'}),innerWidth:480,innerHeight:666};
 let actual=vm.runInNewContext(CREATE_READINESS_QUERY,context);assert.equal(actual.visibleEntityCount,1);assert.equal(actual.selectedEntityCount,0);assert.equal(actual.visibleRows.length,1);assert.equal(actual.visibleRows[0].id,own);assert(!JSON.stringify(actual).includes('private filter'));
 elements['visible-entities-count'].textContent='99999';context.document.querySelectorAll=selector=>selector==='#entity-table-body tr'?Array(65).fill(row):[];actual=vm.runInNewContext(CREATE_READINESS_QUERY,context);assert.equal(actual.visibleEntityCount,null);assert.equal(actual.visibleRows.length,0);
});

test('actual Create input method commits List text with genuine Enter before moving focus; Properties keeps its native blur handler',async()=>{
 const harness=await readFile(new URL('./tablet-create.mjs',import.meta.url),'utf8');
 const start=harness.indexOf(' async function inputControl('),end=harness.indexOf(' async function filteredOwnRow()',start);assert(start>=0&&end>start);
 const calls=[],context={tapControl:async(...args)=>calls.push(['tap',...args]),delay:async ms=>calls.push(['delay',ms]),String,
  page:{keyboard:{press:async key=>calls.push(['key',key])},getByLabel:label=>({evaluate:async(fn,text)=>{const field={dispatchEvent:event=>calls.push(['commit',label,event.data])};vm.runInNewContext('('+fn.toString()+')(field,text)',{field,text,CompositionEvent:class{constructor(type,options){this.type=type;Object.assign(this,options);}}});}})}};
 vm.runInNewContext(harness.slice(start,end),context);
 await context.inputControl('filter-search','own UUID fixture','list');assert.deepEqual(calls.map(x=>x[0]),['tap','key','commit','key','key','delay']);assert.deepEqual(calls.filter(x=>x[0]==='key').map(x=>x[1]),['Control+a','Enter','Tab']);
 calls.length=0;await context.inputControl('property-name','own UUID fixture','properties','base');assert.deepEqual(calls.filter(x=>x[0]==='key').map(x=>x[1]),['Control+a','Tab']);
});
