// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';
import {readdirSync,readlinkSync} from 'node:fs';

// Count only descriptors naming this test's own canonical fixture, not unrelated
// Node/child descriptors which can retire between two asynchronous snapshots.
function ownedFixtureDescriptors(root){
 const names=readdirSync('/proc/self/fd');assert(names.length<=4096,'Descriptor snapshot bound exceeded');
 const owned=[];for(const name of names){assert(/^\d+$/.test(name),'Unexpected descriptor entry');let target;
  try{target=readlinkSync('/proc/self/fd/'+name);}catch(error){if(error.code==='ENOENT'||error.code==='ESRCH')continue;throw error;}
  assert(Buffer.byteLength(target)<=4096,'Descriptor target bound exceeded');
  if(target===root||target===root+' (deleted)'||target.startsWith(root+'/'))owned.push({fd:Number(name),target});
 }return owned;
}
function assertOwnedFixtureClosed(root){assert.deepEqual(ownedFixtureDescriptors(root),[],'Every operation-owned descriptor must close');}
import {authorIdentity,processStat,projectAuthorAudio,nextAuthorSequence,createAuthorConsent} from './tablet-ptt-native-peer.mjs';
const root='/fixed-owned-lab',args=['--url','hifi://127.0.0.2:45102/3,1.8,3/0,0,0,1','--defaultScriptsOverride','http://127.0.0.1:45110/native-participant.js'],entry={pid:123,startTicks:'800',arguments:[root+'/build/browser-lab/appimage/squashfs-root/AppRun',...args]},actual={group:123,startTicks:'800',cwd:root,executable:root+'/interface',arguments:[root+'/interface',...args]},context={cwd:root,kind:'native',executable:root+'/interface'};
const log=(kind,at,data)=>'private prefix BROWSER_LAB '+JSON.stringify({kind,at,data})+'\n';
test('actual process stat excludes zombie and preserves numeric PGID/start ticks even with parentheses in comm',()=>{const tail=['S','1','123','123',...Array(15).fill('0'),'800'];assert.deepEqual(processStat('123 (own (test)) '+tail.join(' ')),{group:123,startTicks:'800'});assert.throws(()=>processStat('123 (test) '+['Z',...tail.slice(1)].join(' ')));});
test('native owner validation requires exact recorded PID/start group/cwd/executable and served author endpoint',()=>{assert(authorIdentity(entry,actual,context));for(const delta of [{startTicks:'801'},{group:999},{cwd:'/copy'},{executable:'/foreign'},{arguments:['/native',...args.slice(0,-1),'http://public.invalid/author.js']}])assert.throws(()=>authorIdentity(entry,{...actual,...delta},context));assert.throws(()=>authorIdentity({...entry,pid:true},actual,context));assert.throws(()=>authorIdentity({...entry,arguments:['/other/AppRun',...args]},actual,context));});
test('existing HTTP owner can serve only the exact fixed loopback port and canonical lab HTTP directory',()=>{const options=['-m','http.server','45110','--bind','127.0.0.1','--directory',root+'/build/browser-lab/http'],record={...entry,arguments:['/python',...options]},process={...actual,arguments:['/python',...options]};assert(authorIdentity(record,process,{...context,kind:'http',httpDirectory:root+'/build/browser-lab/http'}));assert.throws(()=>authorIdentity(record,process,{...context,kind:'http',httpDirectory:'/copy/http'}));});
test('actual native log projection requires exact applied bool plus independent fresh later mute observation; leaks no raw fields',()=>{const text=log('observation',900,{muted:true,privateUrl:'credential'})+log('command-applied',1000,{sequence:5,muted:false})+log('observation',1001,{muted:false,entities:[{name:'private',id:'private'}]});const p=projectAuthorAudio(text,{sequence:5,muted:false,now:1002,since:950});assert(p.commandApplied&&p.observationAfterCommand&&p.observationFresh);assert.equal(p.observationMuted,false);assert(!JSON.stringify(p).includes('private'));assert.equal(projectAuthorAudio(text,{sequence:4,muted:false,now:1002}).commandApplied,false);assert.equal(projectAuthorAudio(text,{sequence:5,muted:true,now:1002}).commandApplied,false);assert.equal(projectAuthorAudio(text,{sequence:5,muted:false,now:1002,since:1001}).commandApplied,false);assert.equal(projectAuthorAudio(text,{sequence:5,muted:false,now:9000}).observationFresh,false);});
test('native source command position/orientation/extra-field injection cannot qualify an audio acknowledgement',()=>{const t=log('command-applied',1000,{sequence:5,muted:false,position:{x:1,y:2,z:3}})+log('observation',1001,{muted:false});assert.equal(projectAuthorAudio(t,{sequence:5,muted:false,now:1002}).commandApplied,false);assert.throws(()=>projectAuthorAudio('x'.repeat(1024*1024+1)));});
test('command sequence exceeds future existing command and native applied sequence rather than just Date.now',()=>{assert.equal(nextAuthorSequence(10000,20000,1000),20001);assert.throws(()=>nextAuthorSequence(-1,0,0));assert.throws(()=>nextAuthorSequence(Number.MAX_SAFE_INTEGER,0,0));});
function fixture({readback=true}={}){let now=1000,live=true,old={sequence:2000,position:{x:100}},last=3000,applied=null,observed=null;const writes=[],delays=[];const actor=createAuthorConsent({now:()=>now,wait:async ms=>{delays.push(ms);now+=ms;},identity:async()=>{if(!live)throw Error('owned identity refused');},readCommand:async()=>old,projection:async()=>({lastSequence:last,commandApplied:!!applied,observationAfterCommand:!!observed,observationFresh:true,observationMuted:observed?.muted??true}),writeCommand:async v=>{writes.push(v);old=v;if(readback){applied=v;observed={muted:v.muted};}}});return{actor,writes,delays,kill(){live=false;},get now(){return now;}};}
test('actual production transaction writes only two mute fields, observes false, then restores true once',async()=>{const f=fixture();const r=await f.actor.setMuted(false);assert.equal(r.actualMuted,false);assert.deepEqual(f.writes,[{sequence:3001,muted:false}]);await f.actor.restore();await f.actor.restore();assert.deepEqual(f.writes,[{sequence:3001,muted:false},{sequence:3002,muted:true}]);await f.actor.close();await assert.rejects(f.actor.setMuted(false));});
test('wrong/stale observation cannot qualify; original fifteen-second command deadline unchanged',async()=>{const f=fixture({readback:false});await assert.rejects(f.actor.setMuted(false),/fifteen seconds/);assert.equal(f.now,16000);assert(f.delays.every(ms=>ms===100));assert.equal(f.writes.length,1);await assert.rejects(f.actor.restore(),/fifteen seconds/);assert.equal(f.writes.length,2);await assert.rejects(f.actor.restore());assert.equal(f.writes.length,2,'A failed restoration is not silently retried');await assert.rejects(f.actor.close());});
test('revoked owned process refuses before any native command is written',async()=>{const f=fixture();f.kill();await assert.rejects(f.actor.setMuted(false));assert.equal(f.writes.length,0);await f.actor.close();});
test('actual one-pending transaction blocks concurrent mute authority writes',async()=>{let unlock;const hold=new Promise(r=>unlock=r);let writes=0;const actor=createAuthorConsent({now:()=>1000,wait:async()=>{},identity:async()=>hold,readCommand:async()=>({sequence:0}),projection:async()=>({lastSequence:0,commandApplied:true,observationAfterCommand:true,observationFresh:true,observationMuted:true}),writeCommand:async()=>writes++});const pending=actor.setMuted(true);await assert.rejects(actor.setMuted(false));unlock();await pending;assert.equal(writes,1);await actor.close();});
test('authored peer source actually starts muted and applies only an explicit bool command; negative control has no reverse signal',async()=>{const source=await readFile(new URL('../../lab/native-participant.js',import.meta.url),'utf8');const timers=[],requests=[],Audio={};vm.runInNewContext(source,{Audio,Render:{},MyAvatar:{},Script:{setInterval:fn=>timers.push(fn)},XMLHttpRequest:function(){this.open=()=>{};this.send=()=>requests.push(this);},print(){},About:{version:'pinned'},Entities:{canRez:()=>false}});assert.equal(Audio.muted,true);timers[1]();const xhr=requests[0];xhr.readyState=4;xhr.status=200;xhr.responseText=JSON.stringify({sequence:5,muted:false});xhr.onreadystatechange();assert.equal(Audio.muted,false);timers[1]();const mute=requests[1];mute.readyState=4;mute.status=200;mute.responseText=JSON.stringify({sequence:6,muted:true});mute.onreadystatechange();assert.equal(Audio.muted,true);});
test('actual runner finally restores author mute before other resource cleanup while preserving original 997Hz oracle',async()=>{const source=await readFile(new URL('./tablet-push-to-talk.mjs',import.meta.url),'utf8');assert(source.includes("assert(reverse.rms>.001&&reverse.tone997Amplitude>.001,'Browser actual output must contain the native peer 997Hz synthetic input')"));const cleanup=source.slice(source.lastIndexOf('}finally{\n'));assert(cleanup.indexOf('nativeAuthor.restore()')<cleanup.indexOf('for(const child of children)'));assert(source.indexOf('nativeAuthor.setMuted(false)')<source.indexOf('const nativeTone='));assert(source.includes('process.env.OVERTE_PTT_AUTHOR_ROOT'));});
test('opening requires explicit canonical actual author root and matching private Pulse, not the copied runner root',async()=>{const {openOwnedNativeAudioAuthor}=await import('./tablet-ptt-native-peer.mjs');await assert.rejects(openOwnedNativeAudioAuthor(undefined,{pulseServer:'unix:/copy/native-pulse.sock'}));await assert.rejects(openOwnedNativeAudioAuthor('/tmp',{pulseServer:'unix:/copy/native-pulse.sock'}));});
test('held regular-file admission rejects a FIFO registry promptly and closes every opened descriptor',async()=>{const {mkdtemp,mkdir,rm}=await import('node:fs/promises'),{execFile}=await import('node:child_process'),{promisify}=await import('node:util'),{tmpdir}=await import('node:os'),{openOwnedNativeAudioAuthor}=await import('./tablet-ptt-native-peer.mjs');const root=await mkdtemp(tmpdir()+'/ptt-owned-refusal-');try{await mkdir(root+'/build/browser-lab/runtime',{recursive:true});await promisify(execFile)('mkfifo',['-m','600',root+'/build/browser-lab/runtime/processes.json']);assertOwnedFixtureClosed(root);const start=performance.now();await assert.rejects(openOwnedNativeAudioAuthor(root,{pulseServer:`unix:${root}/build/browser-lab/runtime/native-pulse.sock`}));assert(performance.now()-start<1000);assertOwnedFixtureClosed(root);}finally{await rm(root,{recursive:true,force:true});}});

test('operation-owned descriptor oracle detects an actual production catch-close mutant',async()=>{
 const {mkdtemp,mkdir,rm}=await import('node:fs/promises'),{execFile}=await import('node:child_process'),{promisify}=await import('node:util'),{tmpdir}=await import('node:os');
 const source=await readFile(new URL('./tablet-ptt-native-peer.mjs',import.meta.url),'utf8');
 const close="for(const f of handles.reverse())await f.close().catch(()=>{});throw error;";
 assert.equal(source.split(close).length-1,1,'Exactly the original refusal cleanup is mutated');
 const mutant="let testRetainedHandles=[];\n"+source.replace(close,"testRetainedHandles.push(...handles);throw error;")+"\nexport async function releaseTestRetainedHandles(){for(const f of testRetainedHandles.splice(0))await f.close();}\n";
 const actual=await import('data:text/javascript;base64,'+Buffer.from(mutant).toString('base64'));
 const root=await mkdtemp(tmpdir()+'/ptt-owned-close-mutant-');
 try{await mkdir(root+'/build/browser-lab/runtime',{recursive:true});await promisify(execFile)('mkfifo',['-m','600',root+'/build/browser-lab/runtime/processes.json']);
  assertOwnedFixtureClosed(root);const start=performance.now();
  await assert.rejects(actual.openOwnedNativeAudioAuthor(root,{pulseServer:`unix:${root}/build/browser-lab/runtime/native-pulse.sock`}));assert(performance.now()-start<1000);
  assert.equal(ownedFixtureDescriptors(root).length,5,'The genuine refusal opened its root, three child directories and FIFO');
  assert.throws(()=>assertOwnedFixtureClosed(root),/Every operation-owned descriptor must close/);
 }finally{await actual.releaseTestRetainedHandles();assertOwnedFixtureClosed(root);await rm(root,{recursive:true,force:true});}
});

test('unrelated descriptor retirement cannot impersonate operation-owned cleanup failure',async()=>{
 const {mkdtemp,open,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os');
 const root=await mkdtemp(tmpdir()+'/ptt-owned-fd-control-'),foreign=await mkdtemp(tmpdir()+'/ptt-foreign-fd-control-');let handle;
 try{handle=await open(foreign,'r');assertOwnedFixtureClosed(root);
  const held=ownedFixtureDescriptors(foreign);assert.equal(held.length,1);
  await handle.close();handle=undefined;assertOwnedFixtureClosed(root);assertOwnedFixtureClosed(foreign);
 }finally{if(handle)await handle.close();await rm(root,{recursive:true,force:true});await rm(foreign,{recursive:true,force:true});}
});
