// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {mkdtemp,mkdir,readFile,writeFile,rm,lstat,symlink,cp} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {parseEmoteAudit,parseEmoteHomeAudit,EMOTE_PREFIX,VIEW_PREFIX,HOME_PREFIX} from './tablet-sit-audit.mjs';import {sitCopiedSourceHashes,SIT_COPIED_HELPERS} from './tablet-sit-source.mjs';
const canonical='[authored time] [DEBUG] [overte.scriptengine.script] [authored thread] ';const decorate=(prefix,body)=>(prefix===EMOTE_PREFIX?canonical:'')+prefix+body;
const run=promisify(execFile),event={kind:'override-returned',name:'Sit1',frames:340,fps:60},home={version:1,sequence:8,revision:2,navigationSequence:5,nodes:2,truncated:false,buttonCount:1,control:{enabled:true,rect:{x:260,y:450,width:129,height:129}}};
test('source dump marker literals never become native Emote action/view/Home records; genuine decorated JSON remains',()=>{const dumps=["print('BROWSER_EMOTE_ACTION '+JSON.stringify({kind:'override-returned',name:emoteName,frames:frameCount,fps:FPS}));","console.log('BROWSER_EMOTE_VIEW '+body);","console.log('BROWSER_EMOTE_HOME '+body);","export const EMOTE_PREFIX='BROWSER_EMOTE_ACTION ';","export const HOME_PREFIX='BROWSER_EMOTE_HOME ';"].join('\n');assert.deepEqual(parseEmoteAudit(dumps,EMOTE_PREFIX),[]);assert.deepEqual(parseEmoteAudit(dumps,VIEW_PREFIX),[]);assert.deepEqual(parseEmoteHomeAudit(dumps),[]);const actual=dumps+'\n'+canonical+EMOTE_PREFIX+JSON.stringify(event)+'\n[script: authored] '+HOME_PREFIX+JSON.stringify(home);assert.deepEqual(parseEmoteAudit(actual,EMOTE_PREFIX),[event]);assert.deepEqual(parseEmoteHomeAudit(actual),[home]);});
test('legacy exact parser negative control reproduces source-literal JSON refusal; object-bearing payloads keep original bounds',()=>{const legacy=vm.runInNewContext('('+parseEmoteAudit.toString().replace("if(!body.startsWith('{'))continue;",'')+')',{assert,EMOTE_PREFIX,VIEW_PREFIX});const dump="console.log('BROWSER_EMOTE_VIEW '+JSON.stringify(...));";assert.throws(()=>legacy(dump,VIEW_PREFIX),/JSON|Unexpected/);for(const prefix of [EMOTE_PREFIX,VIEW_PREFIX]){assert.throws(()=>parseEmoteAudit(decorate(prefix,'{invalid'),prefix));assert.throws(()=>parseEmoteAudit(decorate(prefix,'{'+ 'x'.repeat(16384)),prefix));assert.throws(()=>parseEmoteAudit('x'.repeat(4*1024*1024+1),prefix));const records=Array.from({length:50},(_,i)=>decorate(prefix,JSON.stringify({ordinal:i}))).join('\n');assert.equal(parseEmoteAudit(records,prefix).length,32);assert.equal(parseEmoteAudit(records,prefix)[0].ordinal,18);}assert.throws(()=>parseEmoteHomeAudit(HOME_PREFIX+'{invalid'));assert.throws(()=>parseEmoteHomeAudit(HOME_PREFIX+'{'+ 'x'.repeat(4096)));assert.throws(()=>parseEmoteHomeAudit(HOME_PREFIX+JSON.stringify({...home,privateValue:'not permitted'})));});
async function authoredSource(){const root=await mkdtemp(path.join(tmpdir(),'sit-real-cache-copy-'));for(const d of ['gateway/fixtures','shared','tests/integration','dist','public'])await mkdir(path.join(root,d),{recursive:true});for(const f of ['gateway/tablet-emote.mjs','gateway/tablet-capture.qml','gateway/fixtures/native-emote-f91d15a.js.gz',...SIT_COPIED_HELPERS.map(n=>'tests/integration/'+n)])await writeFile(path.join(root,f),await readFile(new URL('../../'+f,import.meta.url)));await writeFile(path.join(root,'gateway/server.mjs'),'// authored entry; never launched\n');await writeFile(path.join(root,'shared/authority.mjs'),'// authored public source\n');await writeFile(path.join(root,'gateway/trusted_fixture.py'),'VALUE = 42\n');return root;}
const compile=String.raw`import sys,os,py_compile,importlib.util,json,pathlib,struct
p=pathlib.Path(sys.argv[1]);os.utime(p,ns=(1700000000123456000,1700000000123456000));py_compile.compile(str(p),doraise=True);cache=pathlib.Path(importlib.util.cache_from_source(str(p)));data=cache.read_bytes();print(json.dumps({'cacheName':cache.name,'flags':struct.unpack('<I',data[4:8])[0],'headerMtime':struct.unpack('<I',data[8:12])[0],'headerSize':struct.unpack('<I',data[12:16])[0],'sourceMtime':int(p.stat().st_mtime),'sourceSize':p.stat().st_size}))`;
const inspect=String.raw`import sys,importlib.util,pathlib,json,struct
p=pathlib.Path(sys.argv[1]);cache=pathlib.Path(importlib.util.cache_from_source(str(p)));data=cache.read_bytes();print(json.dumps({'flags':struct.unpack('<I',data[4:8])[0],'headerMtime':struct.unpack('<I',data[8:12])[0],'headerSize':struct.unpack('<I',data[12:16])[0],'sourceMtime':int(p.stat().st_mtime),'sourceSize':p.stat().st_size}))`;
const execute=String.raw`import sys,importlib.util
p=sys.argv[1];s=importlib.util.spec_from_file_location('authored_sit_fixture',p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);assert m.VALUE==42`;
test('real authored PEP552 cache header and ALL source/cache hashes remain unchanged after actual preserved-timestamp copy/import',async()=>{const source=await authoredSource();let prepared;try{const c=JSON.parse((await run('/usr/bin/python3',['-I','-c',compile,path.join(source,'gateway/trusted_fixture.py')],{timeout:5000,maxBuffer:4096})).stdout);assert.equal(c.flags,0);assert.equal(c.headerMtime,c.sourceMtime);assert.equal(c.headerSize,c.sourceSize);const before=await sitCopiedSourceHashes(source);prepared=JSON.parse((await run(process.execPath,[new URL('./prepare-tablet-sit-audit.mjs',import.meta.url).pathname,source],{timeout:5000,maxBuffer:4096})).stdout);const file=path.join(prepared.client,'gateway/trusted_fixture.py'),metadata=JSON.parse((await run('/usr/bin/python3',['-I','-c',inspect,file],{timeout:5000,maxBuffer:4096})).stdout);assert.deepEqual(metadata,{flags:0,headerMtime:c.headerMtime,headerSize:c.headerSize,sourceMtime:c.sourceMtime,sourceSize:c.sourceSize});const initial=await sitCopiedSourceHashes(prepared.client);assert.equal(initial['gateway/__pycache__/'+c.cacheName],before['gateway/__pycache__/'+c.cacheName]);await run('/usr/bin/python3',['-I','-c',execute,file],{timeout:5000,maxBuffer:4096});assert.deepEqual(await sitCopiedSourceHashes(prepared.client),initial);assert.deepEqual(await sitCopiedSourceHashes(source),before);}finally{await rm(source,{recursive:true,force:true});if(prepared)await rm(prepared.directory,{recursive:true,force:true});}});
test('counterexample timestamp-reset copy regenerates actual Python bytecode and original ALL-byte attestation refuses',async()=>{const source=await authoredSource(),copy=await mkdtemp(path.join(tmpdir(),'sit-reset-cache-negative-'));try{const c=JSON.parse((await run('/usr/bin/python3',['-I','-c',compile,path.join(source,'gateway/trusted_fixture.py')],{timeout:5000,maxBuffer:4096})).stdout);await cp(source,copy,{recursive:true,preserveTimestamps:false});const file=path.join(copy,'gateway/trusted_fixture.py'),metadata=JSON.parse((await run('/usr/bin/python3',['-I','-c',inspect,file],{timeout:5000,maxBuffer:4096})).stdout);assert.notEqual(metadata.headerMtime,metadata.sourceMtime);const before=await sitCopiedSourceHashes(copy);await run('/usr/bin/python3',['-I','-c',execute,file],{timeout:5000,maxBuffer:4096});const after=await sitCopiedSourceHashes(copy);assert.equal(after['gateway/trusted_fixture.py'],before['gateway/trusted_fixture.py']);assert.notEqual(after['gateway/__pycache__/'+c.cacheName],before['gateway/__pycache__/'+c.cacheName]);assert.throws(()=>assert.deepEqual(after,before));}finally{await rm(source,{recursive:true,force:true});await rm(copy,{recursive:true,force:true});}});
test('unknown generated cache bytes are still attested and source/cache symlinks still refuse',async()=>{const source=await authoredSource();try{await mkdir(path.join(source,'gateway/__pycache__'));const before=await sitCopiedSourceHashes(source);await writeFile(path.join(source,'gateway/__pycache__/unknown.cpython-999.pyc'),'unknown bytes must not be ignored');const after=await sitCopiedSourceHashes(source);assert.notDeepEqual(after,before);assert(after['gateway/__pycache__/unknown.cpython-999.pyc']);await symlink('../trusted_fixture.py',path.join(source,'gateway/__pycache__/network_udp.cpython-314.pyc'));await assert.rejects(sitCopiedSourceHashes(source),/regular/);}finally{await rm(source,{recursive:true,force:true});}});
