// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';
import {currentPttFrameMetadata,samplePttDisplayedControl,freshPttClickCoordinates,incrementPttRefusal} from './tablet-ptt-frame-sample.mjs';
import {assertPaintedPttControl,pttClickControl} from './tablet-ptt-audit.mjs';
const frame=()=>({sequence:8,revision:2,navigationSequence:5,width:480,height:706,data:'bounded-native-PNG'}),point=()=>({sequence:8,revision:2,navigationSequence:5,x:164.5,y:214.5,rect:{x:100,y:150,width:129,height:129}});
test('bounded frame metadata preserves the actual native Tablet rectangle required by the original control contract',()=>{
 const source={...frame(),tabletRect:{x:0,y:0,width:480,height:706}},ctx={window:{__pttAudit:{frame:source}}};
 const read=vm.runInNewContext('('+currentPttFrameMetadata.toString()+')',ctx),metadata=read();
 const record={sequence:8,revision:2,navigationSequence:5,truncated:false,audioButtonCount:1,audioRootCount:0,audioButton:{enabled:true,rect:point().rect}};
 assert(pttClickControl([record],metadata,'audio-app'));assert(!('data' in metadata));
 delete metadata.tabletRect;assert.equal(pttClickControl([record],metadata,'audio-app'),null);
 ctx.window.__pttAudit.frame=null;assert.equal(read(),null);
});
function fixture(){let reads=0;const ctx={window:{__pttAudit:{frame:frame()}}},el={width:480,height:706,getBoundingClientRect:()=>({x:10,y:20,width:240,height:353}),getContext(kind){assert.equal(kind,'2d');return {getImageData(x,y,w,h){reads++;assert.equal(x,100);assert.equal(y,150);const data=new Uint8ClampedArray(w*h*4);for(let i=0;i<data.length;i+=4){data[i]=data[i+1]=data[i+2]=i<1000?20:230;data[i+3]=255;}return {data};}};}};const run=fn=>vm.runInNewContext('('+fn.toString()+')',ctx);return {ctx,el,reads:()=>reads,sample:run(samplePttDisplayedControl),click:run(freshPttClickCoordinates)};}
test('one synchronous browser task captures the exact committed frame, dimensions and native control pixels',()=>{const f=fixture(),r=f.sample(f.el,point());assert.equal(r.refusal,null);assert.equal(r.image.width,129);assert.equal(r.image.height,129);assert.equal(r.frame.sequence,8);assert.equal(r.nativePNG,'bounded-native-PNG');assert.equal(f.reads(),1);assertPaintedPttControl(r.image.rgba,r.image.width,r.image.height);});
test('all three original source ownership mismatches refuse before canvas pixel reads',()=>{for(const [key,reason]of [['sequence','frame-sequence-changed'],['revision','frame-revision-changed'],['navigationSequence','frame-navigation-changed']]){const f=fixture();f.ctx.window.__pttAudit.frame[key]++;assert.equal(f.sample(f.el,point()).refusal,reason);assert.equal(f.reads(),0);assert.equal(f.click(f.el,point()).refusal,reason);}});
test('actual one-task counterexample to split sampling: queued ACK only runs after atomic pixel/owner capture',async()=>{const f=fixture();const change=()=>{f.ctx.window.__pttAudit.frame={...frame(),sequence:9};};queueMicrotask(change);const atomic=f.sample(f.el,point());assert.equal(atomic.refusal,null);assert.equal(atomic.frame.sequence,8);await Promise.resolve();assert.equal(f.ctx.window.__pttAudit.frame.sequence,9);assert.equal(f.click(f.el,point()).refusal,'frame-sequence-changed');const g=fixture(),old=g.ctx.window.__pttAudit.frame;await Promise.resolve().then(()=>{g.ctx.window.__pttAudit.frame={...frame(),sequence:9};});assert.notEqual(g.ctx.window.__pttAudit.frame.sequence,old.sequence,'The old separate owner recheck rejects the preceding legitimate pixel sample after an interstitial ACK');});
test('mapped width/height/total area and edge clipping retain exact old limits',()=>{for(const change of [p=>p.rect.width=257,p=>p.rect.height=7,p=>p.rect.x=-1,p=>p.rect.x=479,p=>p.rect.y=706]){const f=fixture(),p=point();change(p);assert.equal(f.sample(f.el,p).refusal,'mapped-control-out-of-bounds');assert.equal(f.reads(),0);}});
test('blank and transparent pixels still fail the unchanged original painted contrast gate',()=>{const f=fixture();f.el.getContext=()=>({getImageData:(x,y,w,h)=>({data:new Uint8ClampedArray(w*h*4).fill(255)})});const r=f.sample(f.el,point());assert.throws(()=>assertPaintedPttControl(r.image.rgba,r.image.width,r.image.height));});
test('fresh genuine mouse coordinates preserve current exact frame and real canvas scale',()=>{const f=fixture(),r=f.click(f.el,point());assert.equal(r.refusal,null);assert.equal(r.x,92.25);assert.equal(r.y,127.25);f.el.getBoundingClientRect=()=>({x:0,y:0,width:0,height:100});assert.equal(f.click(f.el,point()).refusal,'canvas-bounds-refused');});
test('reentrant authored changes during reads never publish a mixed-owner sample',()=>{const f=fixture(),original=f.el.getContext;f.el.getContext=kind=>{const context=original(kind),read=context.getImageData;return {getImageData(...args){const image=read(...args);f.ctx.window.__pttAudit.frame={...frame(),sequence:9};return image;}};};assert.equal(f.sample(f.el,point()).refusal,'frame-changed-during-sample');});
test('pixel read exceptions propagate unchanged instead of being hidden or weakening calibration',()=>{const f=fixture(),error=new Error('owned pixel read');f.el.getContext=()=>({getImageData(){throw error;}});assert.throws(()=>f.sample(f.el,point()),e=>e===error);});
test('fixed refusal histogram cannot retain arbitrary private strings or grow beyond bounded categories/counts',()=>{const counts={};incrementPttRefusal(counts,'frame-sequence-changed');incrementPttRefusal(counts,'frame-sequence-changed');assert.deepEqual(counts,{'frame-sequence-changed':2});assert.throws(()=>incrementPttRefusal(counts,'private text'));counts['frame-sequence-changed']=1000000;assert.throws(()=>incrementPttRefusal(counts,'frame-sequence-changed'));});
