// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
import {assertIsolatedCreateTarget,baselineIdentity,discoverOwnedShape,assertBaseline,assertExpectedShape,validateCreateCoordinates} from './tablet-create-contract.mjs';
const baseline=Array.from({length:7},(_,i)=>({id:`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,name:`Browser Lab ${i}`,type:'Box',entityHostType:'domain'}));
const shape={id:'10000000-0000-4000-8000-000000000001',type:'Shape',shape:'Cube',entityHostType:'domain',name:'',children:[],color:{red:30,green:170,blue:220},dimensions:{x:.7,y:.9,z:1.1}};
test('public gateways/domains and credentials are rejected before any GUI input',()=>{assertIsolatedCreateTarget('http://127.0.0.1:8090','overte://127.0.0.2:45102');for(const domain of ['overte://overte_hub','overte://127.0.0.2:40102'])assert.throws(()=>assertIsolatedCreateTarget('http://127.0.0.1:8090',domain));assert.throws(()=>assertIsolatedCreateTarget('http://u:p@127.0.0.1:8090','overte://127.0.0.2:45102'));});
test('exact single native domain Cube is discovered, local handles are excluded',()=>{assert.equal(discoverOwnedShape(baseline,[...baseline,shape,{...shape,id:'local',entityHostType:'local'}]).id,shape.id);assert.equal(baselineIdentity(baseline).length,7);});
test('ambiguous additions, changed baseline or child-owning shape refuse ownership',()=>{assert.throws(()=>discoverOwnedShape(baseline,[...baseline,shape,{...shape,id:baseline[0].id.replace('00000000','20000000')}]));assert.throws(()=>discoverOwnedShape(baseline,[...baseline.slice(1),shape]));assert.throws(()=>discoverOwnedShape(baseline,[...baseline,{...shape,children:['other']} ]));assert.throws(()=>assertBaseline([{...baseline[0],name:'Changed'},...baseline.slice(1)],baselineIdentity(baseline)));});
test('native and delivered property assertions demand actual color/dimensions',()=>{const expected={...shape,name:'Native Create Fixture proof'};assertExpectedShape(expected,expected);assert.throws(()=>assertExpectedShape({...expected,color:{...expected.color,red:29}},expected));assert.throws(()=>assertExpectedShape({...expected,dimensions:{...expected.dimensions,x:.71}},expected));});
test('uncalibrated action maps cannot run functional editing',()=>{assert.throws(()=>validateCreateCoordinates({version:1}));const fields=['name','shapeTab','colorRed','colorGreen','colorBlue','transformTab','dimensionX','dimensionY','dimensionZ','listSearch','listRow','listDelete'];const value={version:1,propertiesPNG_SHA256:'a'.repeat(64),listPNG_SHA256:'b'.repeat(64)};for(const name of fields)value[name]=[100,100];const copy=validateCreateCoordinates(value);value.name[0]=1;assert.equal(copy.name[0],100);assert.throws(()=>validateCreateCoordinates({...value,listDelete:[100,-1]}));});
test('actual native observer admits only one armed own Shape and never edits properties',async()=>{
 const source=await readFile(new URL('./native-create-observer.js',import.meta.url),'utf8'),context=vm.createContext({});vm.runInContext(source,context);let entities=structuredClone(baseline),domain='hifi://127.0.0.2:45102/',children=[],removed=[],emitted=[];
 const observer=context.createNativeCreateObserver({name:'Native Create Fixture proof'},{href:()=>domain,loaded:()=>true,ids:()=>entities.map(e=>e.id),properties:id=>entities.find(e=>e.id===id),children:()=>children,canRez:()=>true,version:()=> '2026.04.1',remove:id=>removed.push(id),emit:(kind,data)=>emitted.push({kind,data})});
 observer.receive({sequence:1,action:'arm'});entities.push({...shape});observer.tick();assert.equal(emitted.filter(e=>e.kind==='owned').length,1);assert.deepEqual(removed,[]);
 children=['baseline-child'];assert.throws(()=>observer.receive({sequence:2,action:'cleanup'}));assert.deepEqual(removed,[]);children=[];entities.at(-1).name='Unrelated renamed entity';assert.throws(()=>observer.receive({sequence:3,action:'cleanup'}));assert.deepEqual(removed,[]);
 entities.at(-1).name='Native Create Fixture proof';observer.receive({sequence:4,action:'cleanup'});assert.deepEqual(removed,[shape.id]);observer.receive({sequence:4,action:'cleanup'});assert.equal(removed.length,1);
 domain='hifi://public.example/';assert.throws(()=>observer.receive({sequence:5,action:'cleanup'}));assert.equal(removed.length,1);assert.throws(()=>observer.receive({sequence:6,action:'edit'}));
});

test('fresh profile and actual native selection refuse concurrent or foreign delete targets',async()=>{
 const {freshWorkerProfile,nativeSelectionTrace,assertOwnNativeSelection}=await import('./tablet-create-selection.mjs');
 assert.equal(freshWorkerProfile(['/tmp/old'],['/tmp/old','/tmp/new']),'/tmp/new');assert.throws(()=>freshWorkerProfile([],['/tmp/a','/tmp/b']));
 const log='[DEBUG] setSelections: '+JSON.stringify([shape.id])+'\n',trace=nativeSelectionTrace(log);assertOwnNativeSelection(trace,0,shape.id);assert.throws(()=>assertOwnNativeSelection(trace,1,shape.id));assert.throws(()=>assertOwnNativeSelection(nativeSelectionTrace(log+'[DEBUG] setSelections: '+JSON.stringify([baseline[0].id])+'\n'),0,shape.id));assert.throws(()=>assertOwnNativeSelection(nativeSelectionTrace(log+'[DEBUG] setSelections: '+JSON.stringify([shape.id,baseline[0].id])+'\n'),0,shape.id));assert.throws(()=>nativeSelectionTrace('[DEBUG] setSelections: invalid'));
});
test('finally cleanup also seals a newly created Shape when a UI frame timeout precedes observer tick',async()=>{
 const source=await readFile(new URL('./native-create-observer.js',import.meta.url),'utf8'),context=vm.createContext({});vm.runInContext(source,context);let entities=structuredClone(baseline),removed=[];
 const observer=context.createNativeCreateObserver({name:'Fixture'},{href:()=> 'hifi://127.0.0.2:45102/',loaded:()=>true,ids:()=>entities.map(e=>e.id),properties:id=>entities.find(e=>e.id===id),children:()=>[],canRez:()=>true,version:()=> '2026.04.1',remove:id=>removed.push(id),emit:()=>{}});observer.receive({sequence:1,action:'arm'});entities.push({...shape});observer.receive({sequence:2,action:'cleanup'});assert.deepEqual(removed,[shape.id]);
});
test('actual native selection reader refuses intermediate/final symlinks and FIFOs',async()=>{
 const {readNativeSelection}=await import('./tablet-create-selection.mjs');const {mkdtemp,mkdir,writeFile,symlink,rm,rename}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const path=await import('node:path');const root=await mkdtemp(path.join(tmpdir(),'create-selection-contract-'));
 try{const logs=path.join(root,'data/Overte/Interface/Logs');await mkdir(logs,{recursive:true});await writeFile(path.join(logs,'overte-log.txt'),'[DEBUG] setSelections: '+JSON.stringify([shape.id])+'\n');assert.deepEqual((await readNativeSelection(root)).ids,[shape.id]);await rename(path.join(root,'data/Overte'),path.join(root,'held'));await symlink(path.join(root,'held'),path.join(root,'data/Overte'));await assert.rejects(()=>readNativeSelection(root));await rm(path.join(root,'data/Overte'));await rename(path.join(root,'held'),path.join(root,'data/Overte'));await rename(path.join(logs,'overte-log.txt'),path.join(logs,'outside.txt'));await symlink(path.join(logs,'outside.txt'),path.join(logs,'overte-log.txt'));await assert.rejects(()=>readNativeSelection(root));await rm(path.join(logs,'overte-log.txt'));const {execFile}=await import('node:child_process');await new Promise((resolve,reject)=>execFile('mkfifo',[path.join(logs,'overte-log.txt')],error=>error?reject(error):resolve()));await assert.rejects(()=>readNativeSelection(root),/regular/);}finally{await rm(root,{recursive:true,force:true});}
});

test('native Cube canonicalizes to Box; only Cube shape is eligible under either supported alias',()=>{for(const type of ['Shape','Box']){const entity={...shape,type};assert.equal(discoverOwnedShape(baseline,[...baseline,entity]).id,shape.id);assertExpectedShape(entity,entity);}for(const type of ['Sphere','Model','Text'])assert.throws(()=>discoverOwnedShape(baseline,[...baseline,{...shape,type}]));for(const type of ['Shape','Box'])assert.throws(()=>discoverOwnedShape(baseline,[...baseline,{...shape,type,shape:'Sphere'}]));});

function calibrated(){const value={version:1,propertiesPNG_SHA256:'a'.repeat(64),listPNG_SHA256:'b'.repeat(64)};for(const key of ['name','shapeTab','colorRed','colorGreen','colorBlue','transformTab','dimensionX','dimensionY','dimensionZ','listSearch','listRow','listDelete'])value[key]=[100,100];return value;}
test('native color popup calibration needs its own captured PNG and clones coordinates',()=>{const value={...calibrated(),colorSwatch:[234,231],colorPickerPNG_SHA256:'c'.repeat(64)};const copy=validateCreateCoordinates(value);value.colorSwatch[0]=0;assert.deepEqual(copy.colorSwatch,[234,231]);assert.equal(copy.colorPickerPNG_SHA256,'c'.repeat(64));assert.equal(validateCreateCoordinates(calibrated()).colorSwatch,undefined);});
test('uncaptured picker or out-of-surface swatch cannot authorize genuine RGB editing',()=>{for(const change of [{colorSwatch:[234,231]},{colorSwatch:[234,231],colorPickerPNG_SHA256:'bad'},{colorSwatch:[480,231],colorPickerPNG_SHA256:'c'.repeat(64)},{colorSwatch:[234,39],colorPickerPNG_SHA256:'c'.repeat(64)},{colorSwatch:[234,Infinity],colorPickerPNG_SHA256:'c'.repeat(64)}])assert.throws(()=>validateCreateCoordinates({...calibrated(),...change}));});
