// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
import {readPttVisibilitySnapshot,observePttVisibilityEvents,validatePttVisibilitySnapshot,recordPttVisibilityCheckpoint} from './tablet-ptt-visibility.mjs';
import {readPttKeyDownSnapshot} from './tablet-ptt-keydown-snapshot.mjs';
const a=()=>({events:{keyDown:2,keyUp:1,blur:0,hidden:0},state:{enabled:true,held:true,muted:false},commands:[{held:true,sequence:9}]});
function fixture(){const wl=new Map(),dl=new Map(),ctx={window:{__pttAudit:a(),addEventListener(type,fn){wl.set(type,fn);}},document:{hidden:false,visibilityState:'visible',hasFocus:()=>true,addEventListener(type,fn){dl.set(type,fn);}}};vm.runInNewContext('('+observePttVisibilityEvents.toString()+')();this.read=('+readPttVisibilitySnapshot.toString()+');',ctx);return{ctx,wl,dl,read:()=>JSON.parse(JSON.stringify(ctx.read()))};}
test('fixed document/event/authority scalars preserve actual hidden/focus disagreement instead of inferring topology',()=>{const f=fixture();f.ctx.document.hidden=true;f.ctx.document.visibilityState='hidden';const s=f.read();assert.equal(s.document.hidden,true);assert.equal(s.document.hasFocus,true);assert.deepEqual(s.state,{enabled:true,held:true,muted:false});assert.equal(s.command.sequence,9);assert.equal(validatePttVisibilitySnapshot(s),s);});
test('trusted observation distinguishes synthetic events without changing original4 event counters or wire',()=>{const f=fixture(),before=structuredClone(f.ctx.window.__pttAudit.events);for(const type of ['focus','blur'])f.wl.get(type)({isTrusted:false});f.ctx.document.hidden=true;f.dl.get('visibilitychange')({isTrusted:false});let s=f.read();assert.equal(s.events.focus,1);assert.equal(s.events.trustedFocus,0);assert.equal(s.events.trustedBlur,0);assert.equal(s.events.trustedHidden,0);for(const type of ['focus','blur'])f.wl.get(type)({isTrusted:true});f.dl.get('visibilitychange')({isTrusted:true});s=f.read();assert.equal(s.events.focus,2);assert.equal(s.events.trustedFocus,1);assert.equal(s.events.trustedBlur,1);assert.equal(s.events.trustedHidden,1);assert.deepEqual(f.ctx.window.__pttAudit.events,before);assert.deepEqual(f.ctx.window.__pttAudit.commands,[{held:true,sequence:9}]);});
test('counter saturation, missing state, malformed commands and unexpected visibility preserve bounded uncertainty',()=>{const f=fixture(),data=f.ctx.window.__pttAudit;data.visibilityObservation.focus=65535;f.wl.get('focus')({isTrusted:true});data.events.keyDown=65536;data.state=null;data.commands=Array(129).fill({held:true,sequence:9});f.ctx.document.visibilityState='private URL never retained';const s=f.read();assert.equal(s.events.focus,65535);assert.equal(s.events.keyDown,null);assert.deepEqual(s.state,{enabled:null,held:null,muted:null});assert.deepEqual(s.command,{held:null,sequence:null});assert.equal(s.document.visibilityState,'unknown');assert(!JSON.stringify(s).includes('private URL'));});
test('schema rejects arbitrary strings/fields/negative counts/nonfinite sequence without retaining private payload',()=>{for(const modify of [s=>s.url='private',s=>s.document.hasFocus='private',s=>s.state.held='private',s=>s.events.blur=-1,s=>s.command.sequence=Infinity,s=>s.command.name='private']){const s=fixture().read();modify(s);assert.throws(()=>validatePttVisibilitySnapshot(s));}});
test('checkpoint persists actual snapshot on original failure phase; read/persistence exceptions cannot replace primary refusal',async()=>{for(const mode of ['ok','read','bad','persist']){const report={failure:{category:'original-refusal'}},calls=[],s=fixture().read();await recordPttVisibilityCheckpoint(report,{evaluate:async fn=>{assert.equal(fn,readPttVisibilitySnapshot);calls.push('read');if(mode==='read')throw Error('private');if(mode==='bad')return {...s,url:'private'};return s;}},'original-hidden-wait-refused',async()=>{calls.push('persist');if(mode==='persist')throw Error('private');});assert.deepEqual(calls,['read','persist']);assert.equal(report.failure.category,'original-refusal');assert.equal(report.windowVisibility.records.length,1);assert.equal(report.windowVisibility.readRefused,['read','bad'].includes(mode)?1:0);assert.equal(report.windowVisibility.persistRefused,mode==='persist'?1:0);assert(!JSON.stringify(report).includes('private'));}});
test('checkpoint phases/count remain bounded and stalled reads cannot retain late stale snapshot',async()=>{const report={},s=fixture().read();let resolve;await recordPttVisibilityCheckpoint(report,{evaluate:()=>new Promise(r=>{resolve=r;})},'after-other-front',async()=>{});assert.equal(report.windowVisibility.readRefused,1);assert.equal(report.windowVisibility.records[0].snapshot,null);resolve(s);await Promise.resolve();assert.equal(report.windowVisibility.records[0].snapshot,null);for(let i=1;i<8;i++)await recordPttVisibilityCheckpoint(report,{evaluate:async()=>s},'before-second-tab',async()=>{});await assert.rejects(recordPttVisibilityCheckpoint(report,{evaluate:async()=>s},'before-second-tab',async()=>{}),/bound/);await assert.rejects(recordPttVisibilityCheckpoint({},null,'untrusted-phase',async()=>{}),/Unknown/);});
const source=()=>readFile(new URL('./tablet-push-to-talk.mjs',import.meta.url),'utf8');
test('actual harness serializes original bootstrap plus observer in one ordered init script',async()=>{const s=await source(),start=s.indexOf(" await page.addInitScript('window.__pttKeyDownSnapshot="),end=s.indexOf('\n await page.goto(base);',start),calls=[];assert(start>=0&&end>start);const run=new Function('page','observePttVisibilityEvents','readPttKeyDownSnapshot','return (async()=>{'+s.slice(start,end)+'})();');await run({addInitScript:async script=>calls.push(script)},observePttVisibilityEvents,readPttKeyDownSnapshot);assert.equal(calls.length,1);const f=fixture();f.ctx.navigator={mediaDevices:{getUserMedia:async()=>({getAudioTracks:()=>[]})}};f.ctx.window.WebSocket=class{};vm.runInNewContext(calls[0],f.ctx);assert.deepEqual(JSON.parse(JSON.stringify(f.ctx.window.__pttAudit.events)),{keyDown:0,keyUp:0,blur:0,hidden:0});assert.deepEqual(JSON.parse(JSON.stringify(f.ctx.window.__pttAudit.visibilityObservation)),{focus:0,trustedFocus:0,trustedBlur:0,trustedHidden:0});});
test('actual original10s hidden+both-event gate starts before diagnostic read and cannot be relaxed by focus alone',async()=>{const s=await source(),start=s.indexOf(" await visibilityCheckpoint('before-second-tab');"),end=s.indexOf(" await hold();await page.locator('#tablet').click();await released();",start),body=s.slice(start,end),timeline=[],failure=Error('original10s refusal');let gate;
 const page={bringToFront:async()=>timeline.push('page-front'),evaluate:async()=>({blur:2,hidden:3}),waitForFunction(fn,before,options){timeline.push('original-gate');assert.deepEqual(options,{timeout:10000,polling:100});assert.deepEqual(before,{blur:2,hidden:3});gate=fn;return Promise.reject(failure);},keyboard:{up:async()=>timeline.push('key-up')}};
 const other={goto:async route=>{assert.equal(route,'about:blank');timeline.push('blank');},bringToFront:async()=>timeline.push('other-front')},ctx={report:{actualFocusPages:[]},firefox:false,useActualPttPageFocus:async(context,target,engine)=>{assert.equal(target,other);assert.equal(engine,'system-chromium');timeline.push('real-focus');return {focusEmulationDisabled:true};},context:{newPage:async()=>{timeline.push('new-page');return other;}},page,hold:async()=>timeline.push('hold'),visibilityCheckpoint:async phase=>timeline.push(phase),released:async()=>timeline.push('released'),checkpoint:async()=>timeline.push('passed-checkpoint')};
 const run=new Function(...Object.keys(ctx),'return (async()=>{'+body+'})();');await assert.rejects(run(...Object.values(ctx)),error=>error===failure);assert(timeline.indexOf('new-page')<timeline.indexOf('real-focus'));assert(timeline.indexOf('real-focus')<timeline.indexOf('blank'));assert(timeline.indexOf('original-gate')<timeline.indexOf('after-other-front'));assert.equal(timeline.at(-1),'original-hidden-wait-refused');assert(!timeline.includes('released'));const check=vm.runInNewContext('('+gate.toString()+')',{document:{hidden:true},window:{__pttAudit:{events:{blur:3,hidden:4}}}});assert.equal(check({blur:2,hidden:3}),true);for(const events of [{blur:2,hidden:4},{blur:3,hidden:3}]){const f=vm.runInNewContext('('+gate.toString()+')',{document:{hidden:true},window:{__pttAudit:{events}}});assert.equal(f({blur:2,hidden:3}),false);}const shown=vm.runInNewContext('('+gate.toString()+')',{document:{hidden:false},window:{__pttAudit:{events:{blur:3,hidden:4}}}});assert.equal(shown({blur:2,hidden:3}),false);});
test('genuine Home→AUDIO helper preserves expected PTT boolean and original30s frame/control guards',async()=>{const s=await source(),a=s.indexOf(' async function visitAudioHome(expected)'),b=s.indexOf('\n await audioApp(false);',a),declarations=s.slice(a,b);for(const expected of [false,true]){const calls=[],page={locator(selector){assert.equal(selector,'#tablet');return{click:async()=>calls.push('open')};},waitForFunction:async(fn,arg,options)=>{assert.deepEqual(options,{timeout:30000});calls.push('frame');},getByRole(role,opts){assert.equal(role,'button');assert.deepEqual(opts,{name:'Home',exact:true});return{click:async()=>calls.push('Home')};}},point=async(kind,readback)=>{calls.push([kind,readback]);return {kind,readback};},click=async p=>calls.push(['real-click',p.kind]),factory=new Function('page','point','click',declarations+';return {visitAudioHome,audioApp};'),helpers=factory(page,point,click);await helpers.audioApp(expected);assert.deepEqual(calls,['open','frame','Home',['audio-app',undefined],['real-click','audio-app'],['desktop-ptt',expected]]);calls.length=0;await helpers.visitAudioHome(expected);assert.equal(calls[0],'frame');assert(!calls.includes('open'));assert.deepEqual(calls.at(-1),['desktop-ptt',expected]);}});
test('all later Audio visits use original native Home route, preserving held-release and true/false toggles',async()=>{const s=await source();assert(s.includes("await page.locator('#tablet').click();await released();await page.keyboard.up('t');await visitAudioHome(true);"));assert(s.includes("await audioApp(true);await click(await point('desktop-ptt',true));await point('desktop-ptt',false)"));assert(s.includes("await audioApp(false);await click(await point('desktop-ptt',false));await point('desktop-ptt',true)"));assert(s.includes('sine=frequency=997:sample_rate=48000'));assert(s.includes('tone997Amplitude>.001'));assert(s.includes("'tests/integration/tablet-ptt-visibility.mjs'"));});
