// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile,mkdtemp,mkdir,writeFile,symlink,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
import {EMOTE_HOME_AUDIT_QML,HOME_PREFIX,parseEmoteHomeAudit,emoteHomeControl,assertPaintedEmoteControl} from './tablet-sit-audit.mjs';
import {currentSitFrameMetadata,sampleSitDisplayedControl,freshSitClickCoordinates,createSitControlProofQueue,sitProofQueueInstallerSource} from './tablet-sit-proof-queue.mjs';
import {finishSitLifecycle} from './tablet-sit-lifecycle.mjs';import {sitCopiedSourceHashes,SIT_COPIED_HELPERS} from './tablet-sit-source.mjs';
const frame=()=>({sequence:8,revision:2,navigationSequence:5,width:800,height:800,tabletRect:{x:50,y:40,width:480,height:706},surface:'native',data:Buffer.from('owned PNG bytes').toString('base64')});
const button=root=>({parent:root,text:'EMOTE',sortOrder:12,isActive:false,buttonIndex:6,visible:true,enabled:true,width:129,height:129,children:[],mapToItem:()=>({x:260,y:450})});
function home(root){const output=[],context={console:{log:line=>output.push(line)}};vm.runInNewContext(EMOTE_HOME_AUDIT_QML.replaceAll(/    property int (\w+): ([^\n]+)/g,'    var $1=$2;')+';this.run=emoteHomeAudit',context);context.run(root,frame());return {context,output,records:parseEmoteHomeAudit(output.join('\n'))};}
function tree(){const root={visible:true,children:[]};root.children=[button(root)];return root;}
function pixels(width,height){return Array.from({length:width*height*4},(_,i)=>i%4===3?255:i<width*height*2?20:220);}
function canvas(width=800,height=800){return {width,height,getBoundingClientRect:()=>({x:10,y:20,width:800,height:800}),getContext:()=>({getImageData:(x,y,w,h)=>({data:Uint8ClampedArray.from(pixels(w,h))})})};}
function point(w=129,h=129){return {sequence:8,revision:2,navigationSequence:5,rect:{x:10,y:10,width:w,height:h},x:10+w/2,y:10+h/2};}
function installed(){const context={window:{__sitAudit:{frame:frame()}},atob:text=>Buffer.from(text,'base64').toString('binary'),Map,Uint8Array};vm.runInNewContext(sitProofQueueInstallerSource(sampleSitDisplayedControl,assertPaintedEmoteControl),context);return {context,queue:context.window.__sitProofFactory()};}
test('Home observer uniquely identifies the published native EMOTE/12 button and real tablet-relative mapping',()=>{const r=home(tree());assert.equal(r.records.length,1);assert.equal(r.records[0].nodes,2);const p=emoteHomeControl(r.records,frame());assert.deepEqual(p.rect,{x:260,y:450,width:129,height:129});assert.equal(p.x,324.5);assert.equal(p.y,514.5);assert(!r.output.join('').includes('EMOTE"'));});
test('wrong signature, hidden ancestry, ambiguous buttons, disabled, bad owner and cyclic graph cannot qualify',()=>{for(const change of [r=>r.children[0].sortOrder=100,r=>r.children[0].visible=false,r=>r.visible=false,r=>r.children.push(button(r)),r=>r.children[0].enabled=false,r=>r.children[0].parent={},r=>r.children[0].children=[r]]){const r=tree();change(r);assert.equal(emoteHomeControl(home(r).records,frame()),null);}});
test('Home clipping and stale sequence/revision/navigation or absent tabletRect refuse',()=>{const rows=home(tree()).records;for(const key of ['sequence','revision','navigationSequence']){const f=frame();f[key]++;assert.equal(emoteHomeControl(rows,f),null);}const f=frame();delete f.tabletRect;assert.equal(emoteHomeControl(rows,f),null);const copy=structuredClone(rows);copy[0].control.rect.x=20;assert.equal(emoteHomeControl(copy,frame()),null);assert.equal(emoteHomeControl([...rows,...rows],frame()),null);});
test('native Home graph limits remain 24 depth/4096 nodes/256 children, and visibility exceptions refuse',()=>{for(const mode of ['depth','children','throw']){const r=tree();if(mode==='depth'){let node=r;for(let i=0;i<26;i++){const next={parent:node,children:[],visible:true};node.children.push(next);node=next;}}if(mode==='children')r.children.push(...Array.from({length:256},()=>({parent:r,children:[]})));if(mode==='throw')Object.defineProperty(r.children[0],'opacity',{get(){throw Error('private');}});const rows=home(r).records;assert.equal(emoteHomeControl(rows,frame()),null);}});
test('Home fixed schema excludes foreign fields and retains only bounded records/bytes',()=>{const r=home(tree()).records[0];const text=HOME_PREFIX+JSON.stringify(r);assert.equal(parseEmoteHomeAudit(Array(40).fill(text).join('\n')).length,32);assert.throws(()=>parseEmoteHomeAudit(HOME_PREFIX+JSON.stringify({...r,privateText:'never admitted'})));assert.throws(()=>parseEmoteHomeAudit(HOME_PREFIX+'x'.repeat(4097)));assert.throws(()=>parseEmoteHomeAudit('x'.repeat(4*1024*1024+1)));});
test('serialized exact Sit painted assertion retains original 512 dimension and 65536-area bounds',()=>{const {queue}=installed();for(const [w,h]of [[400,100],[512,128]]){const result=queue.sample(canvas(),point(w,h));assert.equal(result.refusal,null);assert.equal(result.image.width,w);assert(result.proofOrdinal>0);const proof=queue.read(result.proofOrdinal);assertPaintedEmoteControl(proof.image);queue.release(result.proofOrdinal);}for(const [w,h]of [[513,8],[8,7],[512,129]])assert.equal(queue.sample(canvas(),point(w,h)).refusal,'mapped-control-out-of-bounds');});
test('blank/transparent native images cannot become proofs; no raw PNG/RGBA crosses calibration return',()=>{const {queue}=installed(),el=canvas();el.getContext=()=>({getImageData:(x,y,w,h)=>({data:new Uint8ClampedArray(w*h*4)})});assert.throws(()=>queue.sample(el,point()),/painted/);const small=queue.sample(canvas(),point());assert(JSON.stringify(small).length<1024);assert.equal(small.nativePNG,undefined);assert.equal(small.image.rgba,undefined);});
test('bulk transfer before click produces actual stale CAS while same-task proof leaves sequence unchanged',()=>{const {context,queue}=installed();const el=canvas(),p=point();queue.sample(el,p);context.window.__sitAudit.frame.sequence++;const fresh=vm.runInNewContext('('+freshSitClickCoordinates.toString()+')',context);assert.equal(fresh(el,p).refusal,'frame-sequence-changed');context.window.__sitAudit.frame=frame();const sampled=queue.sample(el,p);assert.equal(sampled.frame.sequence,8);assert.equal(fresh(el,p).refusal,null);});
test('native frame changes during canvas read or painted validation never publish a proof',()=>{const {context,queue}=installed(),el=canvas();el.getContext=()=>({getImageData:(x,y,w,h)=>{context.window.__sitAudit.frame=frame();return {data:Uint8ClampedArray.from(pixels(w,h))};}});assert.equal(queue.sample(el,point()).refusal,'frame-changed-during-sample');assert.equal(queue.metadata().count,0);globalThis.window={__sitAudit:{frame:frame()}};try{const q=createSitControlProofQueue(sampleSitDisplayedControl,image=>{assertPaintedEmoteControl(image);window.__sitAudit.frame=frame();});assert.equal(q.sample(canvas(),point()).refusal,'frame-changed-during-sample');}finally{delete globalThis.window;}});
test('missing/oversize PNG and 16-row/32MiB owned queue bounds fail closed; release and retirement free ownership',()=>{const {context,queue}=installed();context.window.__sitAudit.frame.data='';assert.throws(()=>queue.sample(canvas(),point()),/PNG/);context.window.__sitAudit.frame.data=Buffer.alloc(2*1024*1024+1).toString('base64');assert.throws(()=>queue.sample(canvas(),point()),/PNG/);context.window.__sitAudit.frame=frame();for(let i=0;i<16;i++)queue.sample(canvas(),point());assert.throws(()=>queue.sample(canvas(),point()),/count/);assert.throws(()=>queue.read(999),/missing/);for(const id of queue.metadata().ordinals)queue.release(id);assert.equal(queue.metadata().bytes,0);queue.retire();assert.throws(()=>queue.sample(canvas(),point()),/retired/);const second=installed();second.context.window.__sitAudit.frame.data=Buffer.alloc(2*1024*1024).toString('base64');for(let i=0;i<5;i++)second.queue.sample(canvas(),point(512,128));assert.throws(()=>second.queue.sample(canvas(),point(512,128)),/byte/);});
test('copied proof metadata and RGBA cannot mutate retained evidence; actual native PNG survives exact post-check',()=>{const {queue}=installed();const small=queue.sample(canvas(),point());small.frame.tabletRect.x=999;const read=queue.read(small.proofOrdinal);assert.equal(read.frame.tabletRect.x,50);read.image.rgba[0]=999;read.frame.revision=99;assert.equal(queue.read(small.proofOrdinal).image.rgba[0],20);assert.equal(queue.read(small.proofOrdinal).frame.revision,2);assert.equal(queue.read(small.proofOrdinal).nativePNG,frame().data);});
test('browser close failure never skips exact profile removal, attestation or original primary-error evidence',async()=>{const calls=[],report={completed:false,failure:'original genuine gate',baselineUnchanged:true};const accepted=await finishSitLifecycle(report,{closeBrowser:async()=>{calls.push('close');throw Error('close');},removeOwnedProfile:async()=>{calls.push('remove');return true;},attest:async()=>{calls.push('attest');return true;},persist:async()=>calls.push('persist')});assert.deepEqual(calls,['close','remove','attest','persist']);assert.equal(report.failure,'original genuine gate');assert.equal(report.browserCloseFailed,true);assert.equal(accepted,false);assert.equal(report.cleanupVerified,false);});
test('successful lifecycle requires actual close, baseline, exact profile removal and all source attestations',async()=>{for(const mode of ['ok','removed','attest','baseline']){const report={completed:true,baselineUnchanged:mode!=='baseline'},calls=[];const accepted=await finishSitLifecycle(report,{closeBrowser:async()=>calls.push('close'),removeOwnedProfile:async()=>mode!=='removed',attest:async()=>{if(mode==='attest')throw Error('changed');return true;},persist:async()=>calls.push('persist')});assert.equal(accepted,mode==='ok');assert.equal(calls.at(-1),'persist');}});
test('source census binds copied entry/all gateway+shared/helper/fixture bytes and refuses symlinks',async()=>{const client=await mkdtemp(path.join(tmpdir(),'sit-source-contract-'));try{for(const dir of ['gateway/fixtures','shared','tests/integration'])await mkdir(path.join(client,dir),{recursive:true});for(const file of ['gateway/server.mjs','gateway/fixtures/native-emote-f91d15a.js.gz','shared/authority.mjs',...SIT_COPIED_HELPERS.map(n=>'tests/integration/'+n)])await writeFile(path.join(client,file),'authored '+file);const before=await sitCopiedSourceHashes(client);assert.equal(Object.keys(before).length,7);await writeFile(path.join(client,'shared/authority.mjs'),'actual changed dependency');assert.notDeepEqual(await sitCopiedSourceHashes(client),before);await symlink('server.mjs',path.join(client,'gateway/foreign.mjs'));await assert.rejects(sitCopiedSourceHashes(client),/regular/);}finally{await rm(client,{recursive:true,force:true});}});
test('harness preserves genuine controller key Stop and 90/30/20/10/12 deadlines without guessed Home positions',async()=>{const source=await readFile(new URL('./tablet-sit-session.mjs',import.meta.url),'utf8');assert(!source.includes('380,460'));assert(source.includes("page.keyboard.press('x')"));assert(!source.includes('page.keyboard.press(\'Sit'));for(const fragment of ['timeout:90000','timeout:30000','timeout:20000',"'Exact owned profile removal',12000",'d.hipsDrop<=20','d.maximumThighChange<=.5','Math.abs(d.hipsDrop)<10','d.maximumThighChange<.35'])assert(source.includes(fragment),fragment);assert(source.includes('sitProofQueueInstallerSource(sampleSitDisplayedControl,assertPaintedEmoteControl)'));assert(source.indexOf("const count=parseEmoteAudit")<source.indexOf("report.step='calibrate-genuine-painted-Sit'"));assert(source.includes('expectedSnapshot'));});
test('actual flush implementation reruns exact Node assertion before writes, preserves missing/changed proofs and write failures',async()=>{const source=await readFile(new URL('./tablet-sit-session.mjs',import.meta.url),'utf8'),start=source.indexOf('async function flushProofs(){'),end=source.indexOf('\nasync function waitFor',start),body=source.slice(start,end);for(const mode of ['ok','missing','changed','blank','io']){const {queue}=installed(),small=queue.sample(canvas(),point()),saved={file:'own-fixed-proof',frame:structuredClone(small.frame),canvas:structuredClone(small.canvas),image:structuredClone(small.image)},privateProofs=new Map([[small.proofOrdinal,saved]]),writes=[];const page={async evaluate(fn,arg){const command=fn.toString();if(command.includes('metadata()'))return mode==='missing'?{ordinals:[],count:0,bytes:0}:JSON.parse(JSON.stringify(queue.metadata()));if(command.includes('.read(')){const r=JSON.parse(JSON.stringify(queue.read(arg)));if(mode==='changed')r.frame.revision++;if(mode==='blank')r.image.rgba.fill(255);return r;}if(command.includes('.release('))return queue.release(arg);throw Error('Unexpected browser call');}};const ctx={page,privateProofs,assert,assertPaintedEmoteControl,Buffer,writeFile:async(name,data,options)=>{assert.equal(options.mode,0o600);assert.equal(options.flag,'wx');if(mode==='io')throw Error('owned write');writes.push(name);}};ctx.flush=new Function('page','privateProofs','assert','assertPaintedEmoteControl','Buffer','writeFile',body+';return flushProofs;')(...Object.values(ctx));if(mode==='ok'){await ctx.flush();assert.equal(writes.length,3);assert.equal(privateProofs.size,0);assert.equal(queue.metadata().bytes,0);}else{await assert.rejects(ctx.flush());assert.equal(privateProofs.size,1);assert.equal(queue.metadata().count,1);assert.equal(writes.length,0);}}});
test('actual offline preparer copies only reviewed source changes and pins generated Emote/runtime/helper bytes',async()=>{const {execFile}=await import('node:child_process'),{promisify}=await import('node:util');const source=await mkdtemp(path.join(tmpdir(),'sit-prepare-source-'));let owned;try{for(const name of ['gateway/fixtures','shared','tests/integration','dist','public'])await mkdir(path.join(source,name),{recursive:true});for(const name of ['gateway/tablet-emote.mjs','gateway/tablet-capture.qml','gateway/fixtures/native-emote-f91d15a.js.gz',...SIT_COPIED_HELPERS.map(n=>'tests/integration/'+n)])await writeFile(path.join(source,name),await readFile(new URL('../../'+name,import.meta.url)));await writeFile(path.join(source,'gateway/server.mjs'),'// authored entry; never launched\n');await writeFile(path.join(source,'shared/authority.mjs'),'// authored source dependency\n');const before=await sitCopiedSourceHashes(source),result=await promisify(execFile)(process.execPath,[new URL('./prepare-tablet-sit-audit.mjs',import.meta.url).pathname,source],{timeout:5000,maxBuffer:4096});owned=JSON.parse(result.stdout);const prepared=JSON.parse(await readFile(path.join(owned.directory,'audit-manifest.private.json'),'utf8'));assert.deepEqual(prepared.shippingSourceSHA256,before);assert.deepEqual(await sitCopiedSourceHashes(source),before);assert.deepEqual(prepared.copiedSourceSHA256,await sitCopiedSourceHashes(owned.client));for(const [name,hash]of Object.entries(before))if(!['gateway/tablet-emote.mjs','gateway/tablet-capture.qml'].includes(name))assert.equal(prepared.copiedSourceSHA256[name],hash);assert.equal(prepared.copiedCaptureSHA256,prepared.copiedSourceSHA256['gateway/tablet-capture.qml']);assert.equal(prepared.copiedAdapterSHA256,prepared.copiedSourceSHA256['gateway/tablet-emote.mjs']);assert.match(prepared.copiedEmoteGeneratedSHA256,/^[a-f0-9]{64}$/);assert.equal(prepared.version,2);}finally{await rm(source,{recursive:true,force:true});if(owned)await rm(owned.directory,{recursive:true,force:true});}});
