// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';
import {instrumentEmoteView,instrumentEmoteEvents,EMOTE_QUERY,VIEW_PREFIX,EMOTE_PREFIX,parseEmoteAudit,emoteControl,assertPaintedEmoteControl,sitPose,sitDifference,actualRigMatches,SIT_JOINTS} from './tablet-sit-audit.mjs';
const frame={sequence:8,revision:2,navigationSequence:5,width:480,height:706},names=['Crying','Surprised','Dancing','Cheering','Waving','Fall','Pointing','Clapping','Sit','Love'];
const record=()=>({sequence:8,revision:2,navigationSequence:5,web:{x:0,y:40,width:480,height:666},dom:{route:'emote',readyState:'complete',eventBridge:true,viewport:{width:480,height:666},controls:names.map(name=>({name,enabled:true,visible:true,rect:{x:30,y:500,width:190,height:90}}))}});
const avatar=()=>({jointNames:[...SIT_JOINTS],jointRotations:SIT_JOINTS.map(()=>({x:0,y:0,z:0,w:1})),jointTranslations:SIT_JOINTS.map(()=>({x:0,y:100,z:0}))});
test('control uses the genuine fixed HTML button geometry paired to displayed sequence/revision/navigation',()=>{const p=emoteControl([record()],frame);assert.deepEqual(p.rect,{x:30,y:540,width:190,height:90});assert.equal(p.y,585);for(const key of ['sequence','revision','navigationSequence']){const r=record();r[key]++;assert.equal(emoteControl([r],frame),null);}assert.equal(emoteControl([record(),record()],frame),null);});
test('clipped Sit, skeleton/loading HTML, wrong route, duplicate button or missing EventBridge refuses clicking',()=>{for(const modify of [r=>r.dom.readyState='loading',r=>r.dom.eventBridge=false,r=>r.dom.route='other',r=>r.dom.controls[0].name='Sit',r=>r.dom.controls[8].enabled=false,r=>r.dom.controls[8].rect.y=650,r=>r.web.x=500]){const r=record();modify(r);assert.equal(emoteControl([r],frame),null);}});
test('original authored HTML query only reads controls and refuses alternative title/route',()=>{let writes=0;const e={value:'Sit',disabled:false,getBoundingClientRect:()=>({x:30,y:500,width:190,height:90})};Object.defineProperty(e,'value',{get:()=> 'Sit',set(){writes++;throw Error('setter');}});const ctx={location:{pathname:'/scripts/system/html/EmoteApp.html'},document:{title:'Emote App',readyState:'complete',querySelectorAll(selector){assert.equal(selector,'input.emote-button');return Array.from({length:10},()=>e);}},getComputedStyle:()=>({display:'block',visibility:'visible'}),window:{EventBridge:{emitWebEvent(){throw Error('Cannot emit a native command');}}},innerWidth:480,innerHeight:666};ctx.EventBridge=ctx.window.EventBridge;const output=vm.runInNewContext(EMOTE_QUERY,ctx);assert.equal(output.controls.length,10);assert.equal(writes,0);ctx.location.pathname='/other.html';assert.equal(vm.runInNewContext(EMOTE_QUERY,ctx),null);});
test('fixed capture observer is bounded and destroyed/reparented views cannot publish late calibration',async()=>{const shipping=await readFile(new URL('../../gateway/tablet-capture.qml',import.meta.url),'utf8');const modified=instrumentEmoteView(shipping);assert(modified.includes('emoteAudit(item,message)'));const start=modified.indexOf('    property int emoteAuditCount'),end=modified.indexOf('    function fromScript(message)');let body=modified.slice(start,end).replaceAll(/    property (?:int|bool) (\w+): ([^\n]+)/g,'    var $1=$2;');const output=[],ctx={console:{log:l=>output.push(l)}};vm.runInNewContext(body+';this.run=emoteAudit;',ctx);let done;const root={visible:true,children:[]},view={visible:true,parent:root,children:[],url:'file:///scripts/system/html/EmoteApp.html',width:480,height:666,mapToItem:()=>({x:0,y:40}),runJavaScript(query,callback){assert.equal(query,EMOTE_QUERY);done=callback;}};root.children=[view];ctx.run(root,frame);const result=record().dom;view.parent={};done(result);assert.equal(output.length,0);view.parent=root;ctx.run(root,frame);done(result);const r=parseEmoteAudit(output[0],VIEW_PREFIX)[0];assert.equal(r.navigationSequence,5);for(let i=0;i<300;i++){ctx.run(root,frame);done(result);}assert.equal(output.length,256);});
test('painted-control gate retains opaque nonflat pixels and refuses white skeleton/empty/oversized buffers',()=>{const width=10,height=10,rgba=Array.from({length:400},(_,i)=>i%4===3?255:i<200?30:220);assertPaintedEmoteControl({width,height,rgba});assert.throws(()=>assertPaintedEmoteControl({width,height,rgba:Array(400).fill(255)}));assert.throws(()=>assertPaintedEmoteControl({width:1000,height:1000,rgba:[]}));});
test('Sit requires source-backed hip descent and real thigh movement; a notification or arm-only change cannot satisfy it',()=>{const before=sitPose(avatar()),input=avatar();input.jointTranslations[0].y=10;input.jointRotations[1]={x:Math.sin(.5),y:0,z:0,w:Math.cos(.5)};const after=sitPose(input),d=sitDifference(before,after);assert.equal(d.hipsDrop,90);assert(Math.abs(d.maximumThighChange-1)<1e-9);assert.equal(sitDifference(before,before).maximumThighChange,0);assert(actualRigMatches({joints:after},after));const bad=structuredClone(after);bad.LeftLeg.orientation.x=.2;assert(!actualRigMatches({joints:bad},after));});
test('missing/duplicate leg names and invalid native transforms refuse skeletal acceptance',()=>{for(const change of [a=>a.jointNames[1]='Hips',a=>a.jointRotations[2].w=0,a=>a.jointTranslations[3].y=Infinity]){const a=avatar();change(a);assert.throws(()=>sitPose(a));}});
test('private log projection retains only last 32 bounded records and refuses a foreign prefix',()=>{const text=Array.from({length:50},(_,i)=>'[authored time] [DEBUG] [overte.scriptengine.script] [authored thread] '+EMOTE_PREFIX+JSON.stringify({kind:'override-returned',frames:i})).join('\n');assert.equal(parseEmoteAudit(text,EMOTE_PREFIX).length,32);assert.throws(()=>parseEmoteAudit(text,'foreign'));assert.throws(()=>parseEmoteAudit(EMOTE_PREFIX+'x'.repeat(16385),EMOTE_PREFIX));});
test('passive event instrumentation preserves every original animation/control call and rejects unknown bytes',async()=>{const {buildBrowserEmoteOverride}=await import('../../gateway/tablet-emote.mjs');const raw=gunzipSync(await readFile(new URL('../../gateway/fixtures/native-emote-f91d15a.js.gz',import.meta.url))).toString(),fixed=buildBrowserEmoteOverride(raw),audited=instrumentEmoteEvents(fixed);assert.equal(audited.split('MyAvatar.overrideAnimation(').length,fixed.split('MyAvatar.overrideAnimation(').length);assert.equal(audited.split('MyAvatar.restoreAnimation(').length,fixed.split('MyAvatar.restoreAnimation(').length);assert.equal(audited.split('Controller.disableMapping(').length,fixed.split('Controller.disableMapping(').length);const stripped=audited.replace(/\n                    print\('BROWSER_EMOTE_ACTION '\+JSON\.stringify\(\{kind:'override-returned',name:emoteName,frames:frameCount,fps:FPS\}\)\);/g,'').replace(/\n    print\('BROWSER_EMOTE_ACTION '\+JSON\.stringify\(\{kind:'restore-control-returned'\}\)\);/g,'');assert.equal(stripped,fixed);assert.throws(()=>instrumentEmoteEvents(raw));assert.throws(()=>instrumentEmoteEvents(fixed+'\n'));assert.equal(createHash('sha256').update(raw).digest('hex'),'968b5af22e88242fcbc8f09eb0a85161baa70a9cfd3dd5af0edec957fa0e5762');});
