// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import {test,type TestContext} from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {ModelResources} from '../src/model-resources';
import {WorldBitmapUpload} from '../src/world-bitmap-upload';
class Bitmap{width=2;height=2;closes=0;close(){this.closes++;this.width=this.height=0;}}
function fixture(t:TestContext){const previous=globalThis.ImageBitmap;Object.assign(globalThis,{ImageBitmap:Bitmap});t.after(()=>{if(previous)globalThis.ImageBitmap=previous;else delete(globalThis as {ImageBitmap?:typeof ImageBitmap}).ImageBitmap;});const abort=new AbortController(),bitmap=new Bitmap(),source=new THREE.Texture({naturalWidth:2,naturalHeight:2} as unknown as HTMLImageElement),owner=new WorldBitmapUpload({signal:abort.signal,isImage:()=>true,createBitmap:async()=>bitmap as unknown as ImageBitmap});return{abort,bitmap,source,owner};}
function model(texture:THREE.Texture){const root=new THREE.Group();root.add(new THREE.Mesh(new THREE.PlaneGeometry(),new THREE.MeshBasicMaterial({map:texture})));return root;}
test('removing one model never directly closes the private bitmap retained by an independent sampler lease',async t=>{const f=fixture(t),first=await f.owner.prepare(f.source,f.abort.signal),second=first.clone(),a=model(first),b=model(second),cleanup=new ModelResources();f.owner.close();cleanup.capture(a);cleanup.releaseKeeping();assert.equal(f.bitmap.closes,0);assert.equal(f.owner.stats().leases,1);assert.equal((second.image as ImageBitmap).width,2);const later=new ModelResources();later.capture(b);later.releaseKeeping();assert.equal(f.bitmap.closes,1);assert.equal(f.owner.stats().bytes,0);assert.equal(f.owner.stats().leases,0);cleanup.releaseKeeping();later.releaseKeeping();assert.equal(f.bitmap.closes,1);});
test('unmatched retained material slots keep their sampler lease, while replaced slots release exactly once',async t=>{const f=fixture(t),first=await f.owner.prepare(f.source,f.abort.signal),second=first.clone(),root=new THREE.Group(),left=new THREE.MeshBasicMaterial({map:first}),right=new THREE.MeshBasicMaterial({map:second}),mesh=new THREE.Mesh(new THREE.BoxGeometry(),[left,right]);root.add(mesh);const cleanup=new ModelResources();cleanup.capture(root);mesh.material=[new THREE.MeshBasicMaterial(),right];cleanup.capture(root);f.owner.close();cleanup.releaseKeeping(root);assert.equal(f.bitmap.closes,0);assert.equal(f.owner.stats().leases,1);cleanup.releaseKeeping();assert.equal(f.bitmap.closes,1);assert.equal(f.owner.stats().bytes,0);});
test('whole owner abort preserves borrowed live leased pixels until the final model releases them',async t=>{const f=fixture(t),sampler=await f.owner.prepare(f.source,f.abort.signal),root=model(sampler),cleanup=new ModelResources();cleanup.capture(root);f.abort.abort();assert.equal(f.bitmap.closes,0);assert.equal(f.owner.stats().leases,1);cleanup.releaseKeeping();assert.equal(f.bitmap.closes,1);assert.equal(f.owner.stats().bytes,0);});
test('ordinary unleased ImageBitmaps still close once and cube arrays remain deduplicated',t=>{fixture(t);const bitmap=new Bitmap(),texture=new THREE.Texture([bitmap,bitmap] as unknown as TexImageSource),root=model(texture),cleanup=new ModelResources();cleanup.capture(root);cleanup.releaseKeeping();cleanup.releaseKeeping();assert.equal(bitmap.closes,1);});
test('throwing dispose listeners cannot bypass sampler lease release or trigger a second bitmap close',async t=>{const f=fixture(t),sampler=await f.owner.prepare(f.source,f.abort.signal),root=model(sampler),cleanup=new ModelResources();cleanup.capture(root);f.owner.close();sampler.addEventListener('dispose',()=>{throw Error('Actual Three fixture listener failure');});cleanup.releaseKeeping();assert.equal(f.bitmap.closes,1);assert.equal(f.owner.stats().leases,0);assert.equal(f.owner.stats().bytes,0);cleanup.releaseKeeping();assert.equal(f.bitmap.closes,1);});
