// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile,mkdtemp,writeFile,chmod,symlink,rm} from 'node:fs/promises';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';import vm from 'node:vm';import path from 'node:path';
import {selectGoogleChromeJourney} from './integration/chrome-journey-selection.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
const fixture=await readFile(new URL('./fixtures/chrome-journey-original.json.gz',import.meta.url));assert(fixture.length<=65536);assert.equal(sha(fixture),'91ac3fc064514701d04076829950212daa54009670c05629b5a04dc19400ff6e');const gold=JSON.parse(gunzipSync(fixture,{maxOutputLength:262144}));assert.equal(gold.version,1);assert.equal(gold.changes.length,7);
const expected=['browser-client/tests/integration/tablet-sit-session.mjs','browser-client/tests/integration/tablet-sit-home-stop-session.mjs','browser-client/tests/integration/tablet-sit-world-stop-session.mjs','browser-client/tests/integration/public-hub.mjs','browser-client/lab/README.md','docs/browser-client/TABLET_SIT_ACCEPTANCE.md','browser-client/tests/integration/assets-and-avatars.mjs'];assert.deepEqual(gold.changes.map(x=>x.path),expected);
function recover(source,row){assert.equal(sha(source),row.afterSHA256);for(const [before,after]of [...row.anchors].reverse()){assert.equal(source.split(after).length,2);source=source.replace(after,before);}assert.equal(source,row.beforeSource);assert.equal(sha(source),row.beforeSHA256);return source;}
// CPU-only exact reviewed metadata recovery; product sources are never rewritten.
const metadataReadmeBefore="screenshots without starving the browser compositor. It protects administration with a random password held only in the ignored,\nmode-0600 `build/browser-lab/runtime/admin.json` file. It never prints that password.",metadataReadmeAfter="screenshots without starving the browser compositor. It protects administration\nwith a random token held only in the launcher process while provisioning the\nfresh domain. Neither the launcher nor the atomic diagnostic writes that token\nto disk or prints it. The domain configuration stores only its native verifier.";
function recoverReviewedReadme(source){assert.equal(sha(source),'86e5620f014c69879722a90609fb1808a7e55f5592a51fb9ec6d5c7b1070a4cb','Exact reviewed current lab README required');assert.equal(source.split(metadataReadmeAfter).length,2);source=source.replace(metadataReadmeAfter,metadataReadmeBefore);assert.equal(sha(source),'3538e7e9184b585d5ecf4ec9b494d89a68578ac2d27b6b8de4eada5d627b10ce');return source;}
// tests are below: relative source path is resolved from tests/ to its client parent.
async function source(rel){const current=await readFile(new URL(rel.startsWith('browser-client/')?'../'+rel.slice(15):'../../'+rel,import.meta.url),'utf8');return rel==='browser-client/lab/README.md'?recoverReviewedReadme(current):current;}
test('default and named current journeys choose branded Chrome channel, not bundled Chromium',()=>{for(const env of [{},{OVERTE_LAB_BROWSER:'chrome'},{OVERTE_LAB_BROWSER:'google-chrome'}])assert.deepEqual(selectGoogleChromeJourney(env),{channel:'chrome'});});
test('unknown Firefox, bundled Chromium, empty kind and incomplete legacy alias refuse',()=>{for(const kind of ['firefox','system-firefox','chromium','','unknown',null])assert.throws(()=>selectGoogleChromeJourney({OVERTE_LAB_BROWSER:kind}));assert.throws(()=>selectGoogleChromeJourney({OVERTE_LAB_BROWSER:'system-chromium'}));});
test('explicit regular owned executable uses approved selector; symlink/nonexecutable/relative refuse',async()=>{const dir=await mkdtemp('/tmp/chrome-journey-cpu-');try{const file=path.join(dir,'chrome');await writeFile(file,'not executed',{mode:0o700});for(const kind of ['chrome','google-chrome','system-chromium'])assert.deepEqual(selectGoogleChromeJourney({OVERTE_LAB_BROWSER:kind,OVERTE_LAB_CHROMIUM:file}),{executablePath:file});assert.deepEqual(selectGoogleChromeJourney({OVERTE_BROWSER_CHROME_EXECUTABLE:file}),{executablePath:file});const alias=path.join(dir,'link');await symlink(file,alias);assert.throws(()=>selectGoogleChromeJourney({OVERTE_LAB_CHROMIUM:alias}));await chmod(file,0o600);assert.throws(()=>selectGoogleChromeJourney({OVERTE_LAB_CHROMIUM:file}));assert.throws(()=>selectGoogleChromeJourney({OVERTE_LAB_CHROMIUM:'relative'}));}finally{await rm(dir,{recursive:true,force:true});}});
test('all seven exact full before sources recover; unchanged actions/assertions/deadlines and history remain',async()=>{for(const row of gold.changes){const s=await source(row.path);recover(s,row);assert.throws(()=>recover(s+'\n',row));}});
test('five actual current launch statements delegate channel to existing launcher without executing browser',async()=>{for(const row of gold.changes.filter(x=>x.path.endsWith('.mjs'))){const s=await source(row.path);let statement;
 if(row.path.endsWith('public-hub.mjs'))statement=s.slice(s.indexOf('  browser=await chromium.launch('),s.indexOf('  report.browserVersion=',s.indexOf('  browser=await chromium.launch(')));
 else if(row.path.endsWith('assets-and-avatars.mjs'))statement=s.slice(s.indexOf('    browser=await chromium.launch('),s.indexOf('    report.browserVersion=',s.indexOf('    browser=await chromium.launch(')));
 else statement=s.split('\n').find(x=>x.startsWith(' browser=await chromium.launch('));assert(statement);let calls=0;const context={browser:null,chromium:{launch:async options=>{calls++;return options;}},process:{env:{}},selectGoogleChromeJourney,env:{},display:undefined,args:['original-args'],repo:'/authored'};
 const result=await vm.runInNewContext('(async()=>{'+statement+'return browser;})()',context);assert.equal(calls,1);assert.equal(result.channel,'chrome');assert.equal(result.executablePath,undefined);assert.equal(result.headless,true);assert(s.includes('chrome-journey-selection.mjs'));assert(s.includes('google-chrome-selection.mjs'));}
});
test('original five bare launch controls had no branded channel; current docs have no Firefox launch recipe',async()=>{for(const row of gold.changes.filter(x=>x.path.endsWith('.mjs'))){const old=row.beforeSource;assert(!old.includes('selectGoogleChromeJourney'));const prefix=row.path.endsWith('public-hub.mjs')?'  browser=firefox?':row.path.endsWith('assets-and-avatars.mjs')?'    browser=await chromium.launch(':' browser=process.env.OVERTE_LAB_BROWSER';const start=old.indexOf(prefix);assert(start>=0);const end=old.indexOf('report.browserVersion',start);assert(end>start);const statement=old.slice(start,end).replace(/\s+$/,'');const options=await vm.runInNewContext('(async()=>{'+statement+'return browser;})()',{browser:null,chromium:{launch:async o=>o},launchSystemFirefox:()=>{throw Error('No Firefox call');},firefox:false,process:{env:{}},display:undefined,env:{},args:['original-args'],repo:'/authored'});assert.equal(options.channel,undefined);assert.equal(options.executablePath,undefined);const current=await source(row.path);assert(current.includes('selectGoogleChromeJourney(process.env)'));}const readme=await source('browser-client/lab/README.md');assert(readme.includes('playwright install chrome'));assert(!readme.includes('OVERTE_LAB_BROWSER=system-firefox'));assert(!readme.includes('OVERTE_LAB_BROWSER=firefox'));assert(!readme.includes('install chromium firefox'));assert(readme.includes('offline-browser-alpha.mjs'));assert(readme.includes('historical'));});

test('reviewed metadata recovery proves exact current README then exact historical Chrome source',async()=>{const current=await readFile(new URL('../lab/README.md',import.meta.url),'utf8'),row=gold.changes.find(x=>x.path==='browser-client/lab/README.md');assert.throws(()=>recover(current,row));const restored=recoverReviewedReadme(current);assert.equal(sha(restored),row.afterSHA256);recover(restored,row);assert.throws(()=>recoverReviewedReadme(restored));});
test('unknown missing duplicate metadata edits and current hash drift refuse before history',async()=>{const current=await readFile(new URL('../lab/README.md',import.meta.url),'utf8');for(const wrong of [current+'\n',current.replace(metadataReadmeAfter,''),current.replace(metadataReadmeAfter,metadataReadmeAfter+'\n'+metadataReadmeAfter),current.replace('random token','unknown token')])assert.throws(()=>recoverReviewedReadme(wrong));});
test('only the lab README receives exact metadata recovery; other source files retain original bytes',async()=>{for(const row of gold.changes.filter(x=>x.path!=='browser-client/lab/README.md')){const raw=await readFile(new URL(row.path.startsWith('browser-client/')?'../'+row.path.slice(15):'../../'+row.path,import.meta.url),'utf8');assert.equal(await source(row.path),raw);recover(raw,row);}});
