// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Current software-fixture policy; genuine extracted launch path, no browser.
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {createHash}from'node:crypto';
import {readCaptureV26Source}from'./integration/capture-software-managed-source-fixture.mjs';
const workflow=await readFile(new URL('../../.github/workflows/browser-client.yml',import.meta.url),'utf8'),before=await readCaptureV26Source('.github/workflows/browser-client.yml'),runner=await readFile(new URL('./integration/embedded-world.mjs',import.meta.url),'utf8');
const sha=s=>createHash('sha256').update(s).digest('hex'),plain=x=>JSON.parse(JSON.stringify(x));
const changes=[['embedded_swangle_diagnostic:','embedded_default_angle_control:'],["description: 'Request the single SwiftShader ANGLE launch flag during the unchanged embedded GPU proof'","description: 'Run the unchanged embedded GPU proof with the original default ANGLE selection instead of the software-fixture driver request'"],["OVERTE_EMBEDDED_USE_SWANGLE: ${{ github.event_name == 'workflow_dispatch' && inputs.embedded_swangle_diagnostic && '1' || '' }}","OVERTE_EMBEDDED_USE_SWANGLE: ${{ github.event_name == 'workflow_dispatch' && inputs.embedded_default_angle_control && '0' || '1' }}"]];
function expression(w){const m=w.match(/OVERTE_EMBEDDED_USE_SWANGLE: \$\{\{ ([^\n]+) \}\}/g);assert.equal(m.length,1);return m[0].split('${{ ')[1].slice(0,-3);}
const value=(w,event,control)=>vm.runInNewContext(expression(w),{github:{event_name:event},inputs:{embedded_swangle_diagnostic:control,embedded_default_angle_control:control}});
const begin='// BEGIN explicit embedded ANGLE request.',end='// END explicit embedded ANGLE request.';assert.equal(runner.split(begin).length,2);assert.equal(runner.split(end).length,2);const options=vm.runInNewContext(runner.slice(runner.indexOf(begin),runner.indexOf(end))+';embeddedGraphicsLaunchOptions',{assert});
const a=runner.indexOf(" if(engine==='system-firefox')"),z=runner.indexOf(' report.browserVersion=',a);assert(a>0&&z>a);
async function actual(w,event,control){const graphicsLaunch=options(value(w,event,control),'chrome'),calls=[],expected={owned:true};const result=await vm.runInNewContext('(async()=>{let browser;'+runner.slice(a,z)+';return browser;})()', {engine:'chrome',display:':owned',env:{OWNED_FIXTURE:'1'},graphicsLaunch,process:{env:{}},googleChromeLaunchOptions:()=>({channel:'chrome'}),chromium:{launch:async config=>{calls.push(plain(config));return expected;}},firefox:{launch:()=>assert.fail('wrong engine')},launchSystemFirefox:()=>assert.fail('wrong engine')});assert.equal(result,expected);assert.equal(calls.length,1);return{config:calls[0],request:graphicsLaunch.requestedAngleMode};}
test('normal automatic software fixture changes only the single known requested Chrome flag',async()=>{const b=await actual(before,'pull_request',false),c=await actual(workflow,'pull_request',false);assert.deepEqual(c.config,{...b.config,args:['--mute-audio','--use-angle=swiftshader']});assert.equal(c.request,'swiftshader-requested');});
test('manual false or omitted default control selects the normal software driver',async()=>{for(const control of [false,undefined])assert.deepEqual((await actual(workflow,'workflow_dispatch',control)).config.args,['--mute-audio','--use-angle=swiftshader']);});
test('manual true control reproduces the exact original default Chrome launch',async()=>{const b=await actual(before,'pull_request',false),c=await actual(workflow,'workflow_dispatch',true);assert.deepEqual(c.config,b.config);assert.equal(c.request,'default');assert.equal(value(workflow,'workflow_dispatch',true),'0');});
test('non-dispatch events cannot opt into the default control',()=>{for(const event of ['pull_request','push','schedule'])assert.equal(value(workflow,event,true),'1');});
test('unknown environment requests remain refusals and never become launch arguments',()=>{for(const v of ['true','false',' 1','2',null,{},'--no-sandbox'])assert.throws(()=>options(v,'chrome'),/Embedded ANGLE request refused/);});
test('explicit software driver remains branded Chrome only',()=>{for(const engine of ['chromium','firefox','system-chromium','system-firefox'])assert.throws(()=>options('1',engine),/requires Google Chrome/);});
test('new default-control input is the exact single boolean default-off YAML declaration',()=>{const block="      embedded_default_angle_control:\n        description: 'Run the unchanged embedded GPU proof with the original default ANGLE selection instead of the software-fixture driver request'\n        type: boolean\n        default: false\n";assert.equal(workflow.split(block).length,2);assert(!workflow.includes('embedded_swangle_diagnostic'));});
test('three named metadata changes recover the whole exact original workflow',()=>{let old=workflow;for(const[b,c]of [...changes].reverse()){assert.equal(old.split(c).length,2);old=old.replace(c,b);}assert.equal(old,before);assert.equal(sha(before),'d608f4173399093959bda9362953a46589d02b08893cc5468c0c09c0de358202');});
test('software request is confined to the original embedded step with unchanged startup condition',()=>{const label='      - name: Prove embedded FBX decoding, shared GPU upload and actual World cancellation\n',start=workflow.indexOf(label),finish=workflow.indexOf('      - name:',start+label.length),step=workflow.slice(start,finish);assert(start>0&&finish>start);assert.equal(workflow.split('OVERTE_EMBEDDED_USE_SWANGLE').length,2);assert(step.includes('if: ${{ !inputs.startup_diagnostics }}'));assert(step.includes('bash ../browser-client/lab/run-embedded-journey.sh'));assert(step.includes("LIBGL_ALWAYS_SOFTWARE: 'true'"));assert(step.includes('GALLIUM_DRIVER: llvmpipe'));});
test('all original steps actions permissions and job deadlines stay exact after the declared inverse',()=>{let old=workflow;for(const[b,c]of [...changes].reverse())old=old.replace(c,b);assert.equal(old,before);assert(old.includes('timeout-minutes: 15'));assert(old.includes('contents: read'));assert(!workflow.includes('continue-on-error:'));});
test('actual runner and existing pixel deadlines retain their whole reviewed source identity',()=>{assert.equal(sha(runner),'dd7325199f929f82143252d0444e9860a2c3728d4a330501e2ba36fcbe443044');assert(runner.includes("reject(Error('Embedded World fixture exceeded 30 seconds')),30000"));assert(runner.includes("reject(Error('bounded-diagnostic-unavailable')),500"));assert.equal(runner.split('--use-angle=swiftshader').length,2);});
test('the recovered original input remains a treatment and is not reinterpreted as the new control',()=>{assert.equal(value(before,'workflow_dispatch',true),'1');assert.equal(value(before,'workflow_dispatch',false),'');assert.equal(value(workflow,'workflow_dispatch',true),'0');});
