// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Source-exact authored observation controls; no browser/GPU/native is imported.
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {stripTypeScriptTypes} from 'node:module';import vm from 'node:vm';import {EventEmitter} from 'node:events';
const fixture=await readFile(new URL('./fixtures/embedded-world.ts',import.meta.url),'utf8'),runner=await readFile(new URL('./integration/embedded-world.mjs',import.meta.url),'utf8');
function marked(s,label){const a='// BEGIN '+label,z='// END '+label;assert.equal(s.split(a).length,2);assert.equal(s.split(z).length,2);return s.slice(s.indexOf(a),s.indexOf(z));}
const producer=vm.runInNewContext(stripTypeScriptTypes(marked(fixture,'bounded embedded diagnostic'),{mode:'strip'})+';({createEmbeddedDiagnostic,observeEmbeddedWorld,embeddedBackendCategory})');
function consumers(timers={setTimeout,clearTimeout}){return vm.runInNewContext(marked(runner,'strict fixed-field diagnostic consumer.')+';({validateEmbeddedDiagnostic,validateEmbeddedLifecycle,createEmbeddedBrowserObserver,projectEmbeddedGpuProcess,collectEmbeddedFailureDiagnostic})',{assert,...timers});}
const consumer=consumers(),input=()=>JSON.parse(JSON.stringify(producer.createEmbeddedDiagnostic()));
function owner(prototype,options={}){const canvas=new EventEmitter();canvas.addEventListener=canvas.on.bind(canvas);canvas.removeEventListener=canvas.off.bind(canvas);let lost=false;const gl={RENDERER:1,isContextLost:()=>lost,getError(){throw Error('No diagnostic error consumption');},getExtension:()=>({UNMASKED_RENDERER_WEBGL:2}),getParameter:()=>options.backend??'ANGLE (SwiftShader Device)'};const result=Object.create(prototype);result.renderer={domElement:canvas,info:{render:{frame:0}},getContext:()=>gl};return{result,canvas,gl,setLost(value){lost=value;}};}
function frame(d){d.phase='gpu-loop';d.decodedRGBA=[255,0,0,255];d.frames=[[0,0,0,0,0,0,1,1,1,1,0]];d.contextStates=[[0,0,0,1,1]];return d;}

test('actual method wrappers preserve receiver arguments exact value and Promise without observing then',()=>{
 const args=[{},()=>true],value={},promise={get then(){throw Error('No observer continuation');}},proto={resize(...got){assert.equal(this,f.result);assert.deepEqual(got,args);return value;},prepareGraphics(...got){assert.equal(this,f.result);assert.deepEqual(got,args);return promise;}},before={resize:Object.getOwnPropertyDescriptor(proto,'resize'),prepareGraphics:Object.getOwnPropertyDescriptor(proto,'prepareGraphics')},f=owner(proto),d=input(),observation=producer.observeEmbeddedWorld(proto,d);
 assert.equal(f.result.resize(...args),value);assert.equal(f.result.prepareGraphics(...args),promise);assert.equal(d.lifecycle.resizeCalls,1);assert.equal(d.lifecycle.prepareCalls,1);assert.deepEqual(d.lifecycle.events.map(r=>r[0]),[1,2,3,4]);assert.equal(d.lifecycle.backend,1);assert.equal(d.lifecycle.backendSource,1);observation.close();assert.deepEqual(Object.getOwnPropertyDescriptor(proto,'resize'),before.resize);assert.deepEqual(Object.getOwnPropertyDescriptor(proto,'prepareGraphics'),before.prepareGraphics);
});
test('synchronous original exceptions remain primary even when diagnostic GL reads refuse',()=>{
 const original=Error('Original method'),proto={resize(){throw original;},prepareGraphics(){throw original;}},f=owner(proto),d=input(),observation=producer.observeEmbeddedWorld(proto,d);f.result.renderer.getContext=()=>{throw Error('Observation unavailable');};assert.throws(()=>f.result.resize(),e=>e===original);assert.throws(()=>f.result.prepareGraphics(),e=>e===original);assert.equal(d.lifecycle.observerRefused,1);observation.close();
});
test('owned loss events record exact synchronous submission phase without preventing default or changing readiness',()=>{
 let prevented=0;const proto={resize(){},prepareGraphics(){f.setLost(true);f.canvas.emit('webglcontextlost',{isTrusted:true,preventDefault(){prevented++;}});return 23;}},f=owner(proto),d=input(),observation=producer.observeEmbeddedWorld(proto,d);assert.equal(f.result.prepareGraphics(),23);const loss=d.lifecycle.events.find(r=>r[0]===5);assert.deepEqual(Array.from(loss),[5,3,0,1,1,1]);assert.equal(prevented,0);assert.equal(d.lifecycle.phase,1);consumer.validateEmbeddedLifecycle(d.lifecycle);observation.close();assert.equal(f.canvas.listenerCount('webglcontextlost'),0);assert.equal(f.canvas.listenerCount('webglcontextrestored'),0);
});
test('late loss/restoration after retirement is ignored and close never overwrites an external descriptor replacement',()=>{
 const proto={resize(){},prepareGraphics(){}},f=owner(proto),d=input(),observation=producer.observeEmbeddedWorld(proto,d);f.result.prepareGraphics();const replacement=()=>99;proto.resize=replacement;observation.close();const count=d.lifecycle.events.length;f.canvas.emit('webglcontextlost',{isTrusted:true});f.canvas.emit('webglcontextrestored',{isTrusted:true});assert.equal(d.lifecycle.events.length,count);assert.equal(proto.resize,replacement);assert.equal(d.lifecycle.observerRefused,1);observation.close();
});
test('closed observers and foreign World receivers still call originals without acquiring foreign canvas state',()=>{
 let calls=0;const proto={resize(){calls++;return this;},prepareGraphics(){calls++;return this;}},f=owner(proto),foreign=owner(proto),d=input(),observation=producer.observeEmbeddedWorld(proto,d);assert.equal(f.result.prepareGraphics(),f.result);assert.equal(foreign.result.resize(),foreign.result);assert.equal(foreign.canvas.listenerCount('webglcontextlost'),0);assert.equal(d.lifecycle.observerRefused,1);observation.close();assert.equal(f.result.resize(),f.result);assert.equal(calls,3);
});
test('producer bounds lifecycle rows16 and exports fixed backend enums without renderer strings',()=>{
 const proto={resize(){},prepareGraphics(){}},f=owner(proto,{backend:'ANGLE (llvmpipe private host text)'}),d=input(),observation=producer.observeEmbeddedWorld(proto,d);for(let i=0;i<20;i++)f.result.resize();assert.equal(d.lifecycle.events.length,16);assert(d.lifecycle.dropped>0);assert.equal(d.lifecycle.backend,2);assert(!JSON.stringify(d).includes('private'));observation.close();for(const[value,expected]of [['SwiftShader',1],['llvmpipe',2],['ANGLE(other)',3],['WebKit WebGL',4],['',0],[null,0],['x'.repeat(1025),0]])assert.equal(producer.embeddedBackendCategory(value),expected);
});
test('current consumer retains failed11tuple20bound pixels and rejects all unknown lifecycle data',()=>{
 const d=frame(input());consumer.validateEmbeddedDiagnostic(d);assert.deepEqual(d.frames[0],[0,0,0,0,0,0,1,1,1,1,0]);assert.deepEqual(d.contextStates[0],[0,0,0,1,1]);
 for(const mutate of [x=>delete x.lifecycle,x=>x.lifecycle.raw='private',x=>x.lifecycle.backend=5,x=>x.lifecycle.backend='SwiftShader',x=>x.lifecycle.phase=0,x=>x.lifecycle.observerRefused=true,x=>x.lifecycle.prepareCalls=NaN,x=>x.lifecycle.events=Array(17).fill([0,1,0,0,0,0]),x=>x.lifecycle.events=[[11,1,0,0,0,0]],x=>x.lifecycle.events=[[0,1,0,0,2,0]],x=>x.lifecycle.events=[[0,1,0,0,0,0,'private']]]){const v=structuredClone(d);mutate(v);assert.throws(()=>consumer.validateEmbeddedDiagnostic(v));}
});
test('passive browser console crash and disconnect projection uses only finite counters and retires before intended cleanup',()=>{
 const browser=new EventEmitter(),page=new EventEmitter(),observation=consumer.createEmbeddedBrowserObserver();observation.attach(browser,page);for(const text of ['THREE.WebGLRenderer: Context Lost.','THREE.WebGLRenderer: Context Restored.','THREE.WebGLRenderer: Error creating WebGL context.','THREE.WebGLProgram: Shader Error private-source','WebGL: CONTEXT_LOST_WEBGL private-message'])page.emit('console',{text:()=>text});page.emit('console',{text:()=> 'private credential'});page.emit('console',{text:()=> 'x'.repeat(4097)});page.emit('crash');browser.emit('disconnected');const snap=observation.snapshot();assert.deepEqual(Array.from(snap.consoleCounts),[1,1,1,1,1]);assert.equal(snap.consoleDropped,1);assert.equal(snap.pageCrashed,1);assert.equal(snap.browserDisconnectedBeforeCleanup,1);assert(!JSON.stringify(snap).includes('private'));snap.consoleCounts[0]=800;assert.equal(observation.snapshot().consoleCounts[0],1);observation.retire();page.emit('close');assert.equal(observation.snapshot().pageClosedBeforeCleanup,0);assert.equal(page.listenerCount('console'),0);assert.equal(browser.listenerCount('disconnected'),0);
});
test('observer own callback or listener cleanup refusal never escapes into original browser finally',()=>{
 const browser=new EventEmitter(),page=new EventEmitter(),observation=consumer.createEmbeddedBrowserObserver();observation.attach(browser,page);page.emit('console',{text(){throw Error('Private console inaccessible');}});page.off=()=>{throw Error('Cleanup observer refusal');};assert.doesNotThrow(()=>observation.retire());assert.equal(observation.snapshot().observerRefused,1);
});
test('GPU auxiliary producer accepts only bounded actual integer crash count and never exports private auxiliary keys',()=>{
 for(const count of [0,1,1000000])assert.equal(consumer.projectEmbeddedGpuProcess({gpu:{auxAttributes:{processCrashCount:count,private:'secret'}}}).processCrashCount,count);
 for(const count of [undefined,null,-1,1.5,NaN,Infinity,1000001,'2'])assert.equal(consumer.projectEmbeddedGpuProcess({gpu:{auxAttributes:{processCrashCount:count}}}).processCrashCount,null);assert.deepEqual(JSON.parse(JSON.stringify(consumer.projectEmbeddedGpuProcess({gpu:{devices:['private'],auxAttributes:{private:'secret'}}}))),{processCrashCount:null});
});
test('expired original30s deadline skips both original pixel RPC and GPU/CDP query',async()=>{
 let queries=0;const result=await consumer.collectEmbeddedFailureDiagnostic({evaluate(){queries++;throw Error('No read after deadline');}},'Embedded World fixture exceeded 30 seconds',{newBrowserCDPSession(){queries++;throw Error('No pre-init');}});assert.equal(queries,0);assert.equal(result.pixelDiagnosticRefusal,'original-fixture-deadline');
});
test('after-failure actual CDP call is optional bounded and detaches while retaining the original pixel data',async()=>{
 const calls=[],d=frame(input()),session={async send(method){calls.push(method);return{gpu:{auxAttributes:{processCrashCount:2,private:'secret'}}};},async detach(){calls.push('detach');}},browser={async newBrowserCDPSession(){calls.push('session');return session;}};const result=await consumer.collectEmbeddedFailureDiagnostic({evaluate:()=>d},'Actual GPU embedded pixels changed',browser);assert.equal(result.pixelDiagnostic,d);assert.equal(result.gpuProcessDiagnostic.processCrashCount,2);assert.deepEqual(calls,['session','SystemInfo.getInfo','detach']);
});
test('never-settling GPU diagnostics consume only same500ms budget and keep settled pixel evidence with unknown GPU result',async()=>{
 let expire,cleared=0,budget,queryCalls=0;const c=consumers({setTimeout(fn,ms){expire=fn;budget=ms;return 47;},clearTimeout(value){assert.equal(value,47);cleared++;}}),d=frame(input()),resultPromise=c.collectEmbeddedFailureDiagnostic({evaluate:()=>d},'Original pixel failure',{newBrowserCDPSession(){queryCalls++;return new Promise(()=>{});}});await new Promise(done=>setImmediate(done));assert.equal(budget,500);expire();const result=await resultPromise;assert.equal(result.pixelDiagnostic,d);assert.equal(result.gpuProcessDiagnostic.processCrashCount,null);assert.equal(queryCalls,1);assert.equal(cleared,1);
});
test('late pixel or GPU rejection is consumed and cannot mutate the returned bounded unknown projection',async()=>{
 let expire,rejectPage,rejectGpu;const c=consumers({setTimeout(fn){expire=fn;return 31;},clearTimeout(){}}),unhandled=[],listener=e=>unhandled.push(e);process.on('unhandledRejection',listener);
 try{const pending=c.collectEmbeddedFailureDiagnostic({evaluate:()=>new Promise((_,reject)=>rejectPage=reject)},'Original failure',{newBrowserCDPSession:()=>new Promise((_,reject)=>rejectGpu=reject)});await new Promise(done=>setImmediate(done));expire();const result=await pending;assert.equal(result.pixelDiagnosticRefusal,'unavailable-or-invalid');assert.equal(result.gpuProcessDiagnostic.processCrashCount,null);rejectPage(Error('Late private page'));rejectGpu(Error('Late private GPU'));await new Promise(done=>setImmediate(done));assert.equal(unhandled.length,0);assert.equal(result.gpuProcessDiagnostic.processCrashCount,null);}finally{process.off('unhandledRejection',listener);}
});
