// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Actual diagnostic producer/consumer and World preparation counter; no browser.
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {stripTypeScriptTypes} from 'node:module';import vm from 'node:vm';import {EventEmitter} from 'node:events';
const fixture=await readFile(new URL('./fixtures/embedded-world.ts',import.meta.url),'utf8'),runner=await readFile(new URL('./integration/embedded-world.mjs',import.meta.url),'utf8'),world=await readFile(new URL('../src/world.ts',import.meta.url),'utf8');
function marked(s,label){const a='// BEGIN '+label,z='// END '+label;assert.equal(s.split(a).length,2);assert.equal(s.split(z).length,2);return s.slice(s.indexOf(a),s.indexOf(z));}
function producer(clock=()=>100){return vm.runInNewContext(stripTypeScriptTypes(marked(fixture,'bounded embedded diagnostic'),{mode:'strip'})+';({createEmbeddedDiagnostic,observeEmbeddedWorld})',{performance:{now:clock}});}
const consumer=vm.runInNewContext(marked(runner,'strict fixed-field diagnostic consumer.')+';({validateEmbeddedDiagnostic,validateEmbeddedLifecycle,collectEmbeddedFailureDiagnostic})',{assert,setTimeout,clearTimeout});
function owner(proto,pending=0){const canvas=new EventEmitter();canvas.addEventListener=canvas.on.bind(canvas);canvas.removeEventListener=canvas.off.bind(canvas);let lost=false;const value=Object.create(proto);value.compilingGraphics=pending;value.renderer={domElement:canvas,info:{render:{frame:0}},getContext:()=>({isContextLost:()=>lost,RENDERER:1,getExtension:()=>null,getParameter:()=> 'SwiftShader'})};return{value,canvas,setLost(v){lost=v;}};}
function setup(clock,pending=0){const p=producer(clock),proto={resize(){return 19;},prepareGraphics(){return 23;}},f=owner(proto,pending),d=p.createEmbeddedDiagnostic(),observer=p.observeEmbeddedWorld(proto,d);return{p,proto,f,d,observer};}
const plain=x=>JSON.parse(JSON.stringify(x));
test('actual event producer aligns bounded relative clock and existing preparation counter with untouched event6',()=>{const values=[1000.1,1000.6,1008.8],x=setup(()=>values.shift(),1);assert.equal(x.f.value.prepareGraphics(),23);x.f.setLost(true);x.f.canvas.emit('webglcontextlost',{isTrusted:true});assert.deepEqual(plain(x.d.lifecycle.events),[[3,3,0,0,0,1],[4,3,0,0,0,1],[5,1,0,1,1,1]]);assert.deepEqual(plain(x.d.lifecycle.eventTimings),[[0,0,1],[1,1,1],[2,9,1]]);consumer.validateEmbeddedDiagnostic(x.d);x.observer.close();});
test('clock failures and undefined sparse old World counter remain null/refused without changing return or event6',()=>{const x=setup(()=>{throw Error('private clock');},undefined);delete x.f.value.compilingGraphics;assert.equal(x.f.value.resize(),19);assert.deepEqual(plain(x.d.lifecycle.events),[[1,2,0,0,0,0],[2,2,0,0,0,0]]);assert.deepEqual(plain(x.d.lifecycle.eventTimings),[[0,null,null],[1,null,null]]);assert.equal(x.d.lifecycle.timingRefused,1);assert(!JSON.stringify(x.d).includes('private'));consumer.validateEmbeddedLifecycle(x.d.lifecycle);x.observer.close();});
test('negative nonfinite backwards and overbound clock values never become invented elapsed zero',()=>{for(const values of [[-1,-1],[NaN,Infinity],[100,90],[100,60101]]){const x=setup(()=>values.shift());x.f.value.resize();assert.equal(x.d.lifecycle.timingRefused,1);assert.equal(x.d.lifecycle.eventTimings[1][1],null);consumer.validateEmbeddedLifecycle(x.d.lifecycle);x.observer.close();}});
test('pending counter rejects every invalid shape while allowing exact finite0 and1',()=>{for(const bad of [undefined,null,-1,NaN,Infinity,0.5,1000001,'1',true]){const x=setup(()=>100,bad);if(bad===undefined)delete x.f.value.compilingGraphics;x.f.value.resize();assert.equal(x.d.lifecycle.eventTimings[0][2],null);assert.equal(x.d.lifecycle.timingRefused,1);consumer.validateEmbeddedLifecycle(x.d.lifecycle);x.observer.close();}});
test('cap16 does not add clock reads or timing rows after original event bound or retirement',()=>{let reads=0;const x=setup(()=>100+reads++);for(let i=0;i<20;i++)x.f.value.resize();assert.equal(x.d.lifecycle.events.length,16);assert.equal(x.d.lifecycle.eventTimings.length,16);assert.equal(reads,16);assert.equal(x.d.lifecycle.dropped,24);x.observer.close();x.f.value.resize();assert.equal(reads,16);assert.equal(x.d.lifecycle.eventTimings.length,16);consumer.validateEmbeddedLifecycle(x.d.lifecycle);});
test('current shared validator rejects unknown legacy malformed timeline and unsafe private fields',()=>{const x=setup(()=>100);x.f.value.resize();const valid=plain(x.d);consumer.validateEmbeddedDiagnostic(valid);for(const mutate of [v=>v.version=3,v=>delete v.lifecycle.eventTimings,v=>v.lifecycle.eventTimings=[[0,0,0]],v=>v.lifecycle.eventTimings.push([2,0,0]),v=>v.lifecycle.eventTimings[0]=[0,0,0,'private'],v=>v.lifecycle.eventTimings[0][0]=1,v=>v.lifecycle.eventTimings[0][1]='private',v=>v.lifecycle.eventTimings[0][1]=60001,v=>v.lifecycle.eventTimings[0][1]=1.5,v=>v.lifecycle.eventTimings[1][1]=-1,v=>v.lifecycle.eventTimings[0][2]=1000001,v=>v.lifecycle.eventTimings[0][2]=NaN,v=>v.lifecycle.eventTimings[0][1]=null,v=>v.lifecycle.timingRefused=true,v=>v.lifecycle.raw='private']){const v=structuredClone(valid);mutate(v);assert.throws(()=>consumer.validateEmbeddedDiagnostic(v));}x.observer.close();});
test('exact Promise remains unobserved and original exception primary even when timing reads refuse',()=>{const p=producer(()=>{throw Error('clock');}),promise={get then(){throw Error('no extra continuation');}},error=Error('original'),proto={resize(){throw error;},prepareGraphics(){return promise;}},f=owner(proto),d=p.createEmbeddedDiagnostic(),observation=p.observeEmbeddedWorld(proto,d);assert.equal(f.value.prepareGraphics(),promise);assert.throws(()=>f.value.resize(),e=>e===error);assert.equal(d.lifecycle.timingRefused,1);observation.close();});
test('actual World preparation field remains pending until its genuine original finally and records loss before versus after',async()=>{
 const start=world.indexOf('  private async prepareGraphics('),end=world.indexOf('  private willPublishPreparedRoot(',start),recordStart=world.indexOf('  private recordLoadPhase(');assert(start>0&&end>start&&recordStart>0);assert(world.includes('private compilingGraphics = 0;'));
 const methods=world.slice(recordStart,start)+world.slice(start,end),Actual=vm.runInNewContext(stripTypeScriptTypes('class Actual { private compilingGraphics = 0;\n'+methods+'}\nActual',{mode:'strip'}),{performance:{now:()=>100},DOMException});
 let finish;const readiness=new Promise(resolve=>finish=resolve),proto=Actual.prototype;Object.defineProperty(proto,'resize',{configurable:true,value(){return 17;}});
 const p=producer(()=>100),d=p.createEmbeddedDiagnostic(),observer=p.observeEmbeddedWorld(proto,d),f=owner(proto);f.value=Object.assign(new Actual(),f.value);assert.equal(Object.getOwnPropertyDescriptor(f.value,'compilingGraphics').value,0);Object.assign(f.value,{disposed:false,objects:new Map(),prepareZeroLightShaders(){},loadPhases:new Map()});f.value.renderer.compileAsync=()=>readiness;
 const root={userData:{},visible:true},pending=f.value.prepareGraphics(root);assert.equal(f.value.compilingGraphics,1);f.setLost(true);f.canvas.emit('webglcontextlost',{isTrusted:true});assert.equal(d.lifecycle.eventTimings.at(-1)[2],1);finish();await pending;assert.equal(f.value.compilingGraphics,0);f.canvas.emit('webglcontextlost',{isTrusted:true});assert.equal(d.lifecycle.eventTimings.at(-1)[2],0);assert.equal(f.value.loadPhases.get('shaderPrepare').count,1);observer.close();consumer.validateEmbeddedDiagnostic(d);
});
test('runner failure curation returns the validated same v4 producer object under the unchanged bounded read',async()=>{const x=setup(()=>100,1);x.f.value.resize();const result=await consumer.collectEmbeddedFailureDiagnostic({evaluate:()=>x.d},'Actual GPU embedded pixels changed');assert.equal(result.pixelDiagnostic,x.d);assert.equal(result.pixelDiagnostic.version,4);assert.equal(result.pixelDiagnostic.lifecycle.eventTimings.length,2);assert.equal(result.gpuProcessDiagnostic.processCrashCount,null);x.observer.close();});
