// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Source-extracted actual launch configuration; no browser or server.
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const runner=await readFile(new URL('./integration/embedded-world.mjs',import.meta.url),'utf8');
import {recoverCaptureV26Input} from './integration/capture-software-managed-source-fixture.mjs';
const workflow=(await recoverCaptureV26Input('.github/workflows/browser-client.yml',await readFile(new URL('../../.github/workflows/browser-client.yml',import.meta.url)))).toString('utf8');
const begin='// BEGIN explicit embedded ANGLE request.',end='// END explicit embedded ANGLE request.';
assert.equal(runner.split(begin).length,2);assert.equal(runner.split(end).length,2);
const producer=runner.slice(runner.indexOf(begin),runner.indexOf(end));
const options=vm.runInNewContext(producer+';embeddedGraphicsLaunchOptions',{assert});
const plain=x=>JSON.parse(JSON.stringify(x));
const launchStart=runner.indexOf(" if(engine==='system-firefox')"),launchEnd=runner.indexOf(' report.browserVersion=',launchStart);
assert(launchStart>0&&launchEnd>launchStart);const launch=runner.slice(launchStart,launchEnd);
async function actualChrome(value){const calls=[],chromeOptions={channel:'chrome'},env={OWNED_FIXTURE:'1'},expected={version:1},graphicsLaunch=options(value,'chrome');
 const returned=await vm.runInNewContext('(async()=>{let browser;'+launch+';return browser;})()',{
  assert,engine:'chrome',display:':owned',env,graphicsLaunch,process:{env:{}},googleChromeLaunchOptions:()=>chromeOptions,
  chromium:{launch:async config=>{calls.push(config);return expected;}},firefox:{launch:()=>{throw Error('wrong browser');}},launchSystemFirefox:()=>{throw Error('wrong browser');}
 });assert.equal(returned,expected);assert.equal(calls.length,1);return{config:plain(calls[0]),graphicsLaunch:plain(graphicsLaunch)};
}
test('default empty and explicit false preserve the exact original mute-only launch options',async()=>{for(const value of [undefined,'','0']){const actual=await actualChrome(value);assert.deepEqual(actual.config,{channel:'chrome',headless:false,env:{OWNED_FIXTURE:'1'},args:['--mute-audio']});assert.equal(actual.graphicsLaunch.requestedAngleMode,'default');}});
test('selected Chrome request adds exactly the one safe ANGLE argument to actual launch',async()=>{const before=await actualChrome(undefined),after=await actualChrome('1');assert.deepEqual(after.config,{...before.config,args:[...before.config.args,'--use-angle=swiftshader']});assert.equal(after.graphicsLaunch.requestedAngleMode,'swiftshader-requested');});
test('unknown option values refuse rather than becoming launch arguments',()=>{for(const value of ['true','false','yes','2',' 1','1\n','--no-sandbox',null,true,false,0,1,{},[]])assert.throws(()=>options(value,'chrome'),/Embedded ANGLE request refused/);});
test('selected mode is restricted to branded Chrome while every default engine keeps mute only',()=>{for(const engine of ['chrome','chromium','firefox','system-chromium','system-firefox']){assert.deepEqual(plain(options('',engine).args),['--mute-audio']);if(engine!=='chrome')assert.throws(()=>options('1',engine),/requires Google Chrome/);}});
test('report records only the actual selected request enum before any resource setup',()=>{const start=runner.indexOf('const report={'),finish=runner.indexOf('\nlet server',start);assert(start>0&&finish>start);for(const value of [undefined,'1']){const graphicsLaunch=options(value,'chrome');const report=vm.runInNewContext(runner.slice(start,finish)+';report',{Date,engine:'chrome',graphicsLaunch});assert.equal(report.requestedAngleMode,graphicsLaunch.requestedAngleMode);assert(!('actualAngleMode'in report));assert.equal(report.completed,false);assert.equal(report.requests,0);}assert(runner.indexOf('const graphicsLaunch=')<start);});
test('workflow input is boolean default off and confines selected env to the original embedded step',()=>{const input="      embedded_swangle_diagnostic:\n        description: 'Request the single SwiftShader ANGLE launch flag during the unchanged embedded GPU proof'\n        type: boolean\n        default: false\n";assert.equal(workflow.split(input).length,2);const name='      - name: Prove embedded FBX decoding, shared GPU upload and actual World cancellation\n',start=workflow.indexOf(name),finish=workflow.indexOf('      - name:',start+name.length);const step=workflow.slice(start,finish);assert(step.includes("OVERTE_EMBEDDED_USE_SWANGLE: ${{ github.event_name == 'workflow_dispatch' && inputs.embedded_swangle_diagnostic && '1' || '' }}"));assert(step.includes("if: ${{ !inputs.startup_diagnostics }}"));assert.equal(workflow.split('OVERTE_EMBEDDED_USE_SWANGLE').length,2);assert.equal(workflow.split('inputs.embedded_swangle_diagnostic').length,2);assert(step.includes('bash ../browser-client/lab/run-embedded-journey.sh'));});
test('only the Chrome command arguments change; existing GPU deadlines and failure read remain exact',()=>{assert(runner.includes('args:graphicsLaunch.args'));assert.equal(runner.split('--use-angle=swiftshader').length,2);assert.equal(runner.split('newBrowserCDPSession()').length,2);assert(runner.includes("reject(Error('Embedded World fixture exceeded 30 seconds')),30000"));assert(runner.includes("reject(Error('bounded-diagnostic-unavailable')),500"));assert(runner.includes("if(primaryMessage==='Embedded World fixture exceeded 30 seconds')return {pixelDiagnosticRefusal:'original-fixture-deadline'}"));});
