// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import vm from 'node:vm';import {transformSync} from 'esbuild';
import {assertFullscreenViewportGeometry,type FullscreenViewportGeometry} from './fullscreen-geometry';
const source=(name:string)=>readFileSync(new URL(name,import.meta.url),'utf8'),sha=(value:string)=>createHash('sha256').update(value).digest('hex');
const old=source('./fixtures/tablet-fullscreen-original-20261002.ts.txt'),spec=source('./tablet-fullscreen.browser.spec.ts'),geometry=source('./fullscreen-geometry.ts'),denial=source('./fullscreen-embedding-denial.ts');
function witness(width=1280.4000244140625):FullscreenViewportGeometry{return {owner:true,targetConnected:true,referenceConnected:true,referenceOwned:true,topLevel:true,visible:true,nativeDPR:1.25,inner:{width:1280,height:900},target:{left:0,top:0,right:width,bottom:900,width,height:900},reference:{left:0,top:0,right:width,bottom:900,width,height:900},viewport:{width,height:900,offsetLeft:0,offsetTop:0,scale:1}};}
test('retained fractional target cannot satisfy old integer equality; independent exact DOMRect reference can',()=>{const w=witness();assert.throws(()=>assert.equal(w.target!.width,w.inner.width));assertFullscreenViewportGeometry(w);});
test('source-correct float division versus reciprocal multiplication disproves universal direct VisualViewport equality',()=>{const internal=303,zoom=Math.fround(1.25),viewport=Math.fround(internal/zoom),rect=Math.fround(internal*Math.fround(1/zoom));assert.equal(viewport,242.39999389648438);assert.equal(rect,242.40000915527344);assert.notEqual(rect,viewport);const w=witness(rect);w.viewport!.width=viewport;assertFullscreenViewportGeometry(w);});
test('integer default viewport passes the same exact oracle',()=>{const w=witness(1280);assertFullscreenViewportGeometry(w);});
test('every subpixel wrong edge or size is rejected, including defects lost by integer rounding',()=>{for(const field of ['left','top','right','bottom','width','height'] as const){const w=witness();w.target![field]+=1/64;assert.throws(()=>assertFullscreenViewportGeometry(w),field);assert.equal(Math.round(w.target!.width),w.inner.width);}});
test('missing reference, wrong ownership, hidden/disconnected or non-top-level scope never qualifies',()=>{for(const field of ['owner','targetConnected','referenceConnected','referenceOwned','topLevel','visible'] as const){const w=witness();w[field]=false;assert.throws(()=>assertFullscreenViewportGeometry(w));}const w=witness();w.reference=null;assert.throws(()=>assertFullscreenViewportGeometry(w));});
test('independent viewport pinch or offset refuses, rather than assuming geometry equality',()=>{for(const field of ['scale','offsetLeft','offsetTop'] as const){const w=witness();w.viewport![field]+=.25;assert.throws(()=>assertFullscreenViewportGeometry(w));}const w=witness();w.viewport=null;assert.throws(()=>assertFullscreenViewportGeometry(w));});
test('invalid resource dimensions/density refuse before comparisons',()=>{for(const value of [NaN,Infinity,0,-1,16385]){const w=witness();w.viewport!.width=value;assert.throws(()=>assertFullscreenViewportGeometry(w));}for(const value of [NaN,Infinity,0,-1,9]){const w=witness();w.nativeDPR=value;assert.throws(()=>assertFullscreenViewportGeometry(w));}const w=witness();w.inner.width=1280.4;assert.throws(()=>assertFullscreenViewportGeometry(w));});
test('actual reference setup derives only viewport CSS; no measured-target inputs or pointer/pixel/focus mutation',()=>{
 const code=transformSync(geometry,{loader:'ts',format:'cjs',target:'es2022'}).code;let appended=0;const node:any={id:'',style:{},attributes:{},setAttribute(k:string,v:string){this.attributes[k]=v;}};
 const context:any={exports:{},module:{exports:{}},require:()=>assert,document:{getElementById:()=>null,createElement:(tag:string)=>{assert.equal(tag,'div');return node;},body:{append:(n:any)=>{assert.equal(n,node);appended++;}}}};vm.runInNewContext(code,context);context.module.exports.createFullscreenViewportReference();assert.equal(appended,1);assert.deepEqual(node.style,{position:'fixed',inset:'0',width:'auto',height:'auto',margin:'0',padding:'0',border:'0',boxSizing:'border-box',transform:'none',visibility:'hidden',pointerEvents:'none'});assert.deepEqual(node.attributes,{'aria-hidden':'true'});assert(!geometry.includes('requestFullscreen('));assert(!geometry.includes('.focus('));
});
test('all prior authored source bytes recover exactly after only documented test-oracle amendments',()=>{
 assert.equal(sha(old),'53ae639c6ec16a6f57aba3ee60bf997e87589a20ec6ce50735fd3bccfb393c37');let restored=spec;
 restored=restored.replace("\nimport {createFullscreenViewportReference,readFullscreenViewportGeometry,assertFullscreenViewportGeometry,removeFullscreenViewportReference} from './fullscreen-geometry';\nimport {runEmbeddedFullscreenDenial} from './fullscreen-embedding-denial';",'');
 restored=restored.replace('\n    await page.evaluate(removeFullscreenViewportReference);','').replace('\n    await page.evaluate(createFullscreenViewportReference);','');
 restored=restored.replace("const fullscreenGeometry=await page.evaluate(readFullscreenViewportGeometry);await test.info().attach('fullscreen-geometry',{body:Buffer.from(JSON.stringify(fullscreenGeometry)),contentType:'application/json'});assertFullscreenViewportGeometry(fullscreenGeometry);",'expect(during.width).toBe(during.innerWidth);expect(during.height).toBe(during.innerHeight);');
 const originalHeader=old.slice(old.indexOf("test('actual fullscreen Permissions Policy"),old.indexOf("\n\ntest('same-container"));const replacement="test('actual nondelegated cross-origin iframe denies fullscreen while preserving painted native input',async({page})=>{\n    await runEmbeddedFullscreenDenial(page);\n});";
 assert.equal(restored.split(replacement).length,2);restored=restored.replace(replacement,originalHeader);assert.equal(restored,old);
});
test('embedding installs exact original BrowserTablet authored callback, never substitutes API or canvas state',()=>{
 const body=old.split('    await page.evaluate(async()=>{')[1].split('\n    });\n    await expect.poll')[0];assert.equal(denial.split(body).length,2);
 for(const gate of ["expect(child.origin).not.toBe(parent.origin)","expect(parentResponses).toBe(1)","expect(childResponses).toBe(1)","noDelegation:!e.hasAttribute('allowfullscreen')&&!e.hasAttribute('allow')","enabled:false,visible:true,connected:true,none:true","{type:'pointerdown',trusted:true,button:0}","{type:'pointerup',trusted:true,button:0}","input).toMatchObject({revision:1,frameSequence:1,button:0})","trusted:true,calls:1,visible:true,connected:true,enabled:false,rejected:true,name:'TypeError',none:true","await frame.getByRole('button',{name:'Probe actual embedded fullscreen permission',exact:true}).click()","await page.unroute(parent.href)","await page.unroute(child.href)"])assert(denial.includes(gate),gate);
 assert(!denial.includes('allowfullscreen '));assert(!denial.includes('Object.defineProperty'));assert(!denial.includes('dispatchEvent'));assert(!denial.includes('setTimeout'));assert(!denial.includes('.focus('));
});
