// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import vm from 'node:vm';import {transformSync} from 'esbuild';
import test from 'node:test';import assert from 'node:assert/strict';import {BrowserFullscreen,type FullscreenDocument,type FullscreenTarget,type FullscreenState} from '../src/fullscreen';
const click={type:'click',isTrusted:true};
/** Source/controller guard fixture. Authored trusted data is not a browser-trust proof. */
function fixture(deadline=8000,Controller=BrowserFullscreen){
    let enter=0,exit=0;const states:FullscreenState[]=[];
    class Document extends EventTarget implements FullscreenDocument{
        fullscreenEnabled=true;fullscreenElement:Element|null=null;keys=new Set<EventListenerOrEventListenerObject>();
        override addEventListener(type:string,callback:EventListenerOrEventListenerObject|null,options?:AddEventListenerOptions|boolean){if(type==='keydown'){assert.equal(options,true);if(callback)this.keys.add(callback);}super.addEventListener(type,callback,options);}
        override removeEventListener(type:string,callback:EventListenerOrEventListenerObject|null,options?:EventListenerOptions|boolean){if(type==='keydown'){assert.equal(options,true);if(callback)this.keys.delete(callback);}super.removeEventListener(type,callback,options);}
        async exitFullscreen(){exit++;this.fullscreenElement=null;this.dispatchEvent(new Event('fullscreenchange'));}
        authoredKey(overrides:Record<string,unknown>={}){let prevented=0;const event={type:'keydown',isTrusted:true,key:'Escape',repeat:false,isComposing:false,defaultPrevented:false,altKey:false,ctrlKey:false,metaKey:false,shiftKey:false,preventDefault(){prevented++;this.defaultPrevented=true;},...overrides};for(const callback of this.keys){if(typeof callback==='function')callback.call(this,event as unknown as Event);else callback.handleEvent(event as unknown as Event);}return {prevented,event};}
    }
    const document=new Document();const target:FullscreenTarget={ownerDocument:document,isConnected:true,async requestFullscreen(){enter++;document.fullscreenElement=target as unknown as Element;document.dispatchEvent(new Event('fullscreenchange'));}};
    const control=new Controller(target,state=>states.push(state),deadline);return {control,document,target,states,get enter(){return enter;},get exit(){return exit;}};
}
const settle=async()=>{await Promise.resolve();await Promise.resolve();};
test('plain established owned Escape calls real exit synchronously and uses the same pending/state path',async()=>{const f=fixture();f.control.setConnected(true);assert.equal(await f.control.invoke(click),true);assert.equal(f.document.keys.size,1);const result=f.document.authoredKey();assert.equal(result.prevented,1);assert.equal(f.exit,1);assert.equal(f.control.snapshot().pending,true);await settle();assert.equal(f.control.snapshot().pending,false);assert.equal(f.control.snapshot().active,false);assert.equal(f.states.at(-1)?.message,'');f.control.dispose();assert.equal(f.document.keys.size,0);});
test('synthetic, repeat, composing, modified, already handled, wrong key and wrong event refuse before exit or consumption',async()=>{const f=fixture();f.control.setConnected(true);await f.control.invoke(click);for(const bad of [{isTrusted:false},{repeat:true},{isComposing:true},{altKey:true},{ctrlKey:true},{metaKey:true},{shiftKey:true},{defaultPrevented:true},{key:'Enter'},{type:'keyup'},{repeat:undefined},{isComposing:undefined}]){const r=f.document.authoredKey(bad);assert.equal(r.prevented,0);assert.equal(f.exit,0);}const synthetic=new Event('keydown',{cancelable:true});Object.assign(synthetic,{key:'Escape',repeat:false,isComposing:false,altKey:false,ctrlKey:false,metaKey:false,shiftKey:false});f.document.dispatchEvent(synthetic);assert.equal(synthetic.defaultPrevented,false);assert.equal(f.exit,0);f.control.dispose();});
test('unowned same-target and foreign fullscreen, detached/adopted targets and disconnected controllers remain untouched',async()=>{const f=fixture();f.control.setConnected(true);f.document.fullscreenElement=f.target as unknown as Element;assert.equal(f.document.authoredKey().prevented,0);assert.equal(f.exit,0);f.document.fullscreenElement=null;await f.control.invoke(click);const foreign={} as Element;f.document.fullscreenElement=foreign;assert.equal(f.document.authoredKey().prevented,0);assert.equal(f.exit,0);f.document.fullscreenElement=f.target as unknown as Element;Object.assign(f.target,{isConnected:false});assert.equal(f.document.authoredKey().prevented,0);Object.assign(f.target,{isConnected:true,ownerDocument:new EventTarget()});assert.equal(f.document.authoredKey().prevented,0);assert.equal(f.exit,0);Object.assign(f.target,{ownerDocument:f.document});f.control.setConnected(false);await settle();const exits=f.exit;assert.equal(f.document.authoredKey().prevented,0);assert.equal(f.exit,exits);f.control.dispose();});
test('same-target replacement inherits established ownership; stale registered handler cannot double-exit',async()=>{const f=fixture();f.control.setConnected(true);await f.control.invoke(click);const replacement=new BrowserFullscreen(f.target,()=>{});replacement.setConnected(true);assert.equal(f.document.keys.size,2);assert.equal(f.document.authoredKey().prevented,1);assert.equal(f.exit,1);await settle();f.control.dispose();replacement.dispose();assert.equal(f.document.keys.size,0);});
test('a not-yet-connected replacement revokes the obsolete keyboard owner without inventing exit rights',async()=>{const f=fixture();f.control.setConnected(true);await f.control.invoke(click);const replacement=new BrowserFullscreen(f.target,()=>{});assert.equal(f.document.authoredKey().prevented,0);assert.equal(f.exit,0);f.control.dispose();replacement.dispose();await settle();assert.equal(f.exit,1);});
test('busy enter and exit reject duplicate Escape; original promise and cleanup lifetime remain owned',async()=>{const f=fixture();f.control.setConnected(true);let release!:()=>void;f.target.requestFullscreen=()=>new Promise<void>(yes=>release=()=>{f.document.fullscreenElement=f.target as unknown as Element;yes();});const pending=f.control.invoke(click);assert.equal(f.document.authoredKey().prevented,0);assert.equal(f.exit,0);release();assert.equal(await pending,true);let finish!:()=>void,calls=0;f.document.exitFullscreen=()=>{calls++;return new Promise<void>(yes=>finish=()=>{f.document.fullscreenElement=null;yes();});};assert.equal(f.document.authoredKey().prevented,1);assert.equal(calls,1);assert.equal(f.document.authoredKey().prevented,0);assert.equal(calls,1);f.control.dispose();assert.equal(f.document.keys.size,0);finish();await settle();assert.equal(f.control.snapshot().pending,false);assert.equal(f.document.fullscreenElement,null);});
test('real exit rejection uses fixed existing message, consumes late errors and permits no post-dispose callbacks',async()=>{const f=fixture();f.control.setConnected(true);await f.control.invoke(click);let reject!:(error:Error)=>void;f.document.exitFullscreen=()=>new Promise<void>((_,no)=>reject=no);f.document.authoredKey();reject(Error('private native browser detail'));await settle();assert.equal(f.control.snapshot().pending,false);assert.match(f.control.snapshot().message,/could not enter or leave/);assert(!JSON.stringify(f.states).includes('private'));f.control.dispose();const count=f.states.length;f.document.authoredKey();f.document.dispatchEvent(new Event('fullscreenchange'));assert.equal(f.states.length,count);});
test('owned Escape deadline stays bounded with one pending operation and no retry',async()=>{const f=fixture(10);f.control.setConnected(true);await f.control.invoke(click);let finish!:()=>void,calls=0;f.document.exitFullscreen=()=>{calls++;return new Promise<void>(yes=>finish=()=>{f.document.fullscreenElement=null;yes();});};f.document.authoredKey();await new Promise(resolve=>setTimeout(resolve,20));assert.equal(f.control.snapshot().pending,true);assert.match(f.control.snapshot().message,/within 8 seconds/);assert.equal(f.document.authoredKey().prevented,0);assert.equal(calls,1);f.control.dispose();finish();await settle();assert.equal(f.control.snapshot().pending,false);});

test('exact original controller counterfactual has no application Escape action; all four production hunks recover the original source',async()=>{
    let source=await readFile(new URL('../src/fullscreen.ts',import.meta.url),'utf8');
    const start=source.indexOf('    private readonly escape='),end=source.indexOf('    constructor(',start);assert(start>=0&&end>start);
    source=source.slice(0,start)+source.slice(end);
    source=source.replace("        this.document.addEventListener('keydown',this.escape,true);\n",'').replace("        this.document.removeEventListener('keydown',this.escape,true);\n",'');
    source=source.replace('        return this.change(before===null);\n    }\n    private change(entering:boolean):Promise<boolean> {\n        const epoch=this.epoch;','        const entering=before===null,epoch=this.epoch;');
    assert.equal(createHash('sha256').update(source).digest('hex'),'c6cc3b470ff6c6f5763a56227c1ec19693507e5abdbb2580c9407ab00ce16720');
    const module={exports:{} as {BrowserFullscreen:typeof BrowserFullscreen}};
    vm.runInNewContext(transformSync(source,{loader:'ts',format:'cjs',target:'es2022'}).code,{module,exports:module.exports,setTimeout,clearTimeout});
    const f=fixture(8000,module.exports.BrowserFullscreen);f.control.setConnected(true);assert.equal(await f.control.invoke(click),true);
    assert.equal(f.document.keys.size,0);assert.equal(f.document.authoredKey().prevented,0);assert.equal(f.exit,0);assert.equal(f.document.fullscreenElement,f.target);f.control.dispose();await settle();assert.equal(f.exit,1);
});
