// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
import {projectWorldEntityMembership,collectHubEntityMembership} from '../shared/hub-entity-membership.mjs';
const id=i=>i.toString(16).padStart(8,'0')+'-1234-1234-1234-123456789012';
function run(native,world){const box={window:{__hubEntitySummary:native,__overte:{entityModelMembership:world}},Map,TextEncoder};return vm.runInNewContext('('+collectHubEntityMembership.toString()+')()',box);}
test('same-task native input and real owned slot projection captures one extra Model without URLs/name/pose',()=>{const entities=new Map([[id(1),{type:'Model',modelURL:'PRIVATE',name:'PRIVATE',position:'PRIVATE'}],[id(2),{type:'Shape'}]]),objects=new Map([[id(1),{userData:{modelLoaded:true,shadersReady:true,modelGeometryReady:true}}]]);const world=projectWorldEntityMembership(entities,objects),proof=run(entities,world);assert.equal(proof.status,'complete');assert.equal(proof.nativeRows.length,2);assert.equal(proof.world.entityRows.length,2);assert.deepEqual(Array.from(proof.world.slotRows[0]),[id(1),'Model',true,false,true,true]);assert(!JSON.stringify(proof).includes('PRIVATE'));});
test('same entity input with stale orphan or failed slot remains distinct metadata rather than loading success',()=>{const entities=new Map([[id(1),{type:'Model'}]]),objects=new Map([[id(1),{userData:{modelFailed:true}}],[id(2),{userData:{modelLoaded:true}}]]);const result=projectWorldEntityMembership(entities,objects);assert.deepEqual(result.slotRows,[[id(1),'Model',false,true,false,false],[id(2),'missing',true,false,false,false]]);});
test('sensitive unknown properties are never read or serialized',()=>{const entity={type:'Model'},root={userData:{modelLoaded:true}};for(const key of ['modelURL','imageURL','position','name','token'])Object.defineProperty(entity,key,{get(){throw Error('Do not read sensitive unrelated field');}});const result=run(new Map([[id(1),entity]]),projectWorldEntityMembership(new Map([[id(1),entity]]),new Map([[id(1),root]])));assert.equal(result.status,'complete');assert(!JSON.stringify(result).includes('modelURL'));});
test('URL-like identity and unbounded type are refused without original payload escape',()=>{for(const rows of [new Map([['https://private.invalid/token',{type:'Model'}]]),new Map([[id(1),{type:'x'.repeat(65)}]])]){const result=run(rows,{schema:1,status:'complete',entityRows:[],slotRows:[]});assert.equal(result.status,'refused');assert.equal(result.reason,'source-shape');assert(!JSON.stringify(result).includes('private'));}});
test('record and byte limits refuse instead of partial successful membership',()=>{const big=new Map(Array.from({length:4097},(_,i)=>[id(i),{type:'Model'}]));assert.equal(projectWorldEntityMembership(big,new Map()).reason,'record-budget');const entities=new Map(Array.from({length:4096},(_,i)=>[id(i),{type:'A'.repeat(64)}])),slots=new Map([...entities.keys()].map(key=>[key,{userData:{}}]));assert.equal(projectWorldEntityMembership(entities,slots).reason,'byte-budget');});
test('missing/disposed owned world is explicitly refused',()=>{assert.equal(run(new Map(),undefined).reason,'world-unavailable');const result=run(new Map(),{schema:1,status:'refused',reason:'record-budget'});assert.equal(result.status,'refused');});
test('original same-boundary gates/deadlines and default-off control remain in exact source',()=>{const source=readFileSync(new URL('../tests/integration/public-hub.mjs',import.meta.url),'utf8');assert(source.includes("report.entityMembershipRequested=process.env.OVERTE_LAB_ENTITY_MEMBERSHIP==='1'"));assert(source.includes('if(requested&&sample.queuedModels===0&&sample.loadingModels===0&&sample.compilingGraphics===0)'));assert(source.includes('report.entityMembershipRequested&&index===0'));assert(source.includes('requireWorldLoadingReady(report.performance.at(-1))'));assert(source.includes('report.steadyFluidPerformance=assessFluidPerformance(report.performance.slice(-2))'));assert(source.includes('report.reconnectedSteadyFluidPerformance=assessFluidPerformance(report.reconnectedSteadySamples.slice(-2))'));});

test('collector rebuilds exact fixed projection and never returns unrelated source payloads',()=>{const world={schema:1,status:'complete',entityRows:[[id(1),'Model']],slotRows:[[id(1),'Model',true,false,true,true]],privateURL:'https://private.invalid/token',privatePayload:{secret:'PRIVATE'}};const result=run(new Map([[id(1),{type:'Model'}]]),world);assert.equal(result.status,'complete');assert.deepEqual(Object.keys(result.world).sort(),['entityRows','schema','slotRows','status']);assert(!JSON.stringify(result).includes('PRIVATE'));assert(!JSON.stringify(result).includes('private.invalid'));});
