// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync}from'node:fs';
import {configureHubDispatchAttribution,collectHubDispatchAttribution,hubDispatchSourceCoherence}from'./integration/hub-render-dispatch-attribution.mjs';
const limits={maximumSamples:512,maximumDrawsPerSample:4096,maximumOwnersPerSample:512,maximumMaterialsPerSample:512,maximumGeometriesPerSample:512,maximumSourcesPerSample:1024,maximumSamplerTuplesPerSample:2048,maximumProgramsPerSample:128,maximumProgramCallsPerSample:4096,maximumSamplerKeyBytesPerSample:262144,maximumCpuMsPerSample:2,maximumAggregateCpuMs:500,maximumElapsedMsPerSample:5000};
const totals=()=>({drawsObserved:2,owners:2,materials:2,geometries:2,materialTransitions:1,geometryTransitions:1,geometryVariantTransitions:0,geometryVariants:1,programCalls:1,programTransitions:0,drawsWithObservedProgram:2,drawsWithoutObservedProgram:0,programs:1,textureBindings:0,sources:0,sourceSamplerTuples:0,samplerKeyBytes:0,cpuMs:.1,elapsedMs:1});
const empty=()=>({samples:0,completeSamples:0,censoredSamples:0,reasons:{},completeTotals:{},partialTotals:{},totals:{}});
function snapshot(){const t=totals();return {enabled:true,status:'sampling',active:false,sampleEveryFrames:8,maximumSamples:2048,maximumObservedFrames:16384,maximumBoundaryCallsPerSample:4096,maximumFrameMs:5000,observedFrames:8,scheduledFrames:1,completedFrames:1,failedRenders:0,invalidFrames:0,capacitySkippedFrames:0,reentrantFrames:0,installationRefusals:0,foreignHookChanges:0,dispatchAttribution:{enabled:true,samples:1,capacitySkippedSamples:0,cpuMs:.1,limits:{...limits},scope:'sampled-renderBufferDirect-call-entries',entryEvidence:'call-entries-not-confirmed-GL-draws',programEvidence:'actual-useProgram-calls',materialEvidence:'identity-only-not-value-equivalence',populations:{emptyScene:empty(),loading:empty(),modelJobsIdle:{samples:1,completeSamples:1,censoredSamples:0,reasons:{},completeTotals:{...t},partialTotals:{},totals:{...t}}}}};}
function fixture(raw=snapshot()){
 let reads=0;const api={connected:true};Object.defineProperty(api,'performance',{configurable:true,get(){reads++;return {renderCpuTiming:raw};}});const context={window:{__overte:api}};return {raw,api,context,reads:()=>reads,collect:vm.runInNewContext('('+collectHubDispatchAttribution.toString()+')',context)};
}
test('default-off config preserves exact existing density/quality/asset and unrelated flags',()=>{
 for(const value of [undefined,'0','true',1]){const url=new URL('http://127.0.0.1:8095/?density=100&texturePreparation=1&private=fixture');const before=url.href;assert.equal(configureHubDispatchAttribution(url,value),false);assert.equal(url.href,before);}
 const url=new URL('http://127.0.0.1:8095/?density=100&texturePreparation=1');assert.equal(configureHubDispatchAttribution(url,'1'),true);assert.equal(url.searchParams.get('renderCpuTiming'),'1');assert.equal(url.searchParams.get('renderDispatchAttribution'),'1');assert.equal(url.searchParams.get('density'),'100');assert.equal(url.searchParams.get('texturePreparation'),'1');
});
test('exact serialized collector reads one existing snapshot and projects numeric/censor semantics without private text',()=>{
 const raw=snapshot();raw.extra='PRIVATE';raw.dispatchAttribution.extra='PRIVATE';raw.dispatchAttribution.populations.modelJobsIdle.name='PRIVATE';const f=fixture(raw),out=f.collect(1);assert.equal(f.reads(),1);assert.equal(out.samples,1);assert.equal(out.partial,false);assert.equal(out.entryEvidence,'call-entries-not-confirmed-GL-draws');assert.equal(out.programEvidence,'actual-useProgram-calls');assert.equal(out.measurementIncludesObserverOverhead,true);assert.equal(out.causalLagAttribution,false);assert.equal(out.wholeWorldCoverage,false);assert.equal(out.limits.maximumProgramsPerSample,128);assert(!JSON.stringify(out).includes('PRIVATE'));
});
test('each successful or failed admission snapshot is one-shot; rejoin has its own ordinal and no retry',()=>{
 const f=fixture();f.collect(1);assert.throws(()=>f.collect(1));f.collect(2);assert.equal(f.reads(),2);assert.throws(()=>f.collect(3));assert.equal(f.reads(),2);const bad=fixture();bad.raw.active=true;assert.throws(()=>bad.collect(1));bad.raw.active=false;assert.throws(()=>bad.collect(1));assert.equal(bad.reads(),1);
});
test('disconnected/current-owner replacement and disabled/stale/active observer fail without raw errors',()=>{
 const f=fixture();f.api.connected=false;assert.throws(()=>f.collect(1));assert.equal(f.reads(),0);
 for(const change of [r=>r.enabled=false,r=>r.active=true,r=>r.status='disposed',r=>r.dispatchAttribution.enabled=false,r=>r.sampleEveryFrames=1,r=>r.dispatchAttribution.entryEvidence='GPU-draws']){const r=snapshot();change(r);assert.throws(()=>fixture(r).collect(1),/valid bounded scalar/);}
 const g=fixture();Object.defineProperty(g.api,'performance',{configurable:true,get(){g.context.window.__overte={connected:true};return{renderCpuTiming:snapshot()};}});assert.throws(()=>g.collect(1),/valid bounded scalar/);
});
test('128-program protocol is exact, limits are never enlarged or inferred from draw counts',()=>{
 for(const change of [r=>r.dispatchAttribution.limits.maximumProgramsPerSample=129,r=>r.dispatchAttribution.samples=513,r=>r.observedFrames=16385,r=>r.scheduledFrames=2049,r=>r.dispatchAttribution.populations.modelJobsIdle.completeTotals.programs=129]){const r=snapshot();change(r);assert.throws(()=>fixture(r).collect(1));}
 const r=snapshot(),p=r.dispatchAttribution.populations.modelJobsIdle;for(const t of [p.totals,p.completeTotals]){t.programCalls=0;t.programs=0;t.drawsWithObservedProgram=0;t.drawsWithoutObservedProgram=2;}const out=fixture(r).collect(1);assert.equal(out.populations.modelJobsIdle.completeTotals.drawsWithoutObservedProgram,2);assert.equal(out.populations.modelJobsIdle.completeTotals.programs,0,'A cached state produces no useProgram call in this sample; it does not mean no GPU draw occurred');
});
test('actual censored totals/reasons and measured overhead overruns remain explicit without clipping or fake completeness',()=>{
 const r=snapshot(),p=r.dispatchAttribution.populations.modelJobsIdle;p.completeSamples=0;p.censoredSamples=1;p.reasons={'cpu-limit':1};p.completeTotals={};p.partialTotals={...p.totals,cpuMs:750,drawsWithObservedProgram:0,drawsWithoutObservedProgram:0};p.totals={...p.partialTotals};r.dispatchAttribution.cpuMs=750;r.dispatchAttribution.capacitySkippedSamples=3;const out=fixture(r).collect(1);assert.equal(out.partial,true);assert.equal(out.censoredSamples,1);assert.equal(out.observerCpuMs,750);assert.equal(out.limits.maximumAggregateCpuMs,500);assert.equal(out.populations.modelJobsIdle.partialTotals.drawsObserved,2);assert.equal(out.populations.modelJobsIdle.completeTotals.drawsObserved,0);
});
test('unknown censor reasons, mixed partitions, malformed integers and missing totals cannot leak or become positive',()=>{
 const changes=[r=>r.dispatchAttribution.populations.modelJobsIdle.reasons={PRIVATE:1},r=>r.dispatchAttribution.populations.modelJobsIdle.completeSamples=0,r=>r.dispatchAttribution.populations.modelJobsIdle.totals.drawsObserved=3,r=>delete r.dispatchAttribution.populations.modelJobsIdle.completeTotals.programs,r=>r.dispatchAttribution.populations.modelJobsIdle.totals.cpuMs=Infinity,r=>r.dispatchAttribution.populations.modelJobsIdle.completeTotals.materials=-1,r=>r.dispatchAttribution.populations.modelJobsIdle.completeTotals.extra='PRIVATE',r=>r.dispatchAttribution.cpuMs=.2];
 for(const change of changes){const r=snapshot();change(r);assert.throws(()=>fixture(r).collect(1),error=>error.message==='Connected dispatch observer did not produce a valid bounded scalar diagnostic');}
});
test('full opt-in source and distribution coherence refuses missing/changed sources and artifact manifests',()=>{
 const files=['browser-client/src/world.ts','browser-client/src/render-dispatch-attribution.ts'],source=Object.fromEntries(files.map(file=>[file,'a'.repeat(64)])),dist={'assets/main.js':{sha256:'b'.repeat(64),bytes:10}};assert.deepEqual(hubDispatchSourceCoherence(files,source,{...source},dist,{...dist}),{sourceCoherent:true,distributionCoherent:true,sourceFileCount:2});assert.equal(hubDispatchSourceCoherence(files,source,{...source,[files[1]]:'c'.repeat(64)},dist,dist).sourceCoherent,false);assert.equal(hubDispatchSourceCoherence(files,{},source,dist,dist).sourceCoherent,false);assert.equal(hubDispatchSourceCoherence(files,source,source,dist,{'assets/main.js':{sha256:'c'.repeat(64),bytes:10}}).distributionCoherent,false);assert.equal(hubDispatchSourceCoherence(files,source,source,{},{}).distributionCoherent,false);
});
test('actual production RenderCpuBreakdown snapshot conforms and restores every wrapped method in CPU simulation',async()=>{
 const {RenderCpuBreakdown}=await import('../src/render-cpu-breakdown.ts');const {Scene,PerspectiveCamera,BoxGeometry,MeshBasicMaterial,Mesh}=await import('three');const abort=new AbortController();let time=0,programCalls=0;const program={},gl={useProgram(){programCalls++;}},scene=new Scene(),camera=new PerspectiveCamera(),geometry=new BoxGeometry(),material=new MeshBasicMaterial(),owner=new Mesh(geometry,material);scene.add(owner);const renderer={getContext:()=>gl,info:{render:{calls:2,triangles:24}},renderBufferDirect(){gl.useProgram(program);}};const before=[scene.updateMatrixWorld,camera.updateMatrixWorld,scene.onBeforeRender,renderer.renderBufferDirect,gl.useProgram];const diagnostic=new RenderCpuBreakdown(abort.signal,{now:()=>time+=.001,dispatchAttribution:true});diagnostic.measure(renderer,scene,camera,'modelJobsIdle',()=>{scene.updateMatrixWorld();camera.updateMatrixWorld();scene.onBeforeRender();renderer.renderBufferDirect(camera,scene,geometry,material,owner);renderer.renderBufferDirect(camera,scene,geometry,material,owner);return 7;});assert.equal(programCalls,2);assert.deepEqual([scene.updateMatrixWorld,camera.updateMatrixWorld,scene.onBeforeRender,renderer.renderBufferDirect,gl.useProgram],before);const out=fixture(diagnostic.snapshot()).collect(1);assert.equal(out.completeSamples,1);assert.equal(out.populations.modelJobsIdle.completeTotals.drawsObserved,2);assert.equal(out.populations.modelJobsIdle.completeTotals.programCalls,2);assert.equal(out.populations.modelJobsIdle.completeTotals.programs,1);abort.abort();assert.equal(diagnostic.snapshot().status,'disposed');geometry.dispose();material.dispose();
});
test('Hub integration preserves original four fluid/native/movement checks, source order/deadlines and post-measure snapshots',()=>{
 const source=readFileSync(new URL('./integration/public-hub.mjs',import.meta.url),'utf8');const first=source.indexOf('page.evaluate(collectHubDispatchAttribution,1)'),second=source.indexOf('page.evaluate(collectHubDispatchAttribution,2)');assert(first>source.indexOf('report.walkFluidPerformance=assessFluidPerformance'));assert(first>source.indexOf('assert(report.nativePoseDifferenceMeters<0.5'));assert(first>source.indexOf("await screenshot('public-hub.png')"));assert(first<source.indexOf("await page.locator('#leave').click()"));assert(second>source.indexOf('report.reconnectedWalkFluidPerformance=assessFluidPerformance'));assert(second>source.indexOf('assert(report.reconnectedNativeDifferenceMeters<0.5'));assert(second<source.lastIndexOf("await page.locator('#leave').click()"));assert(source.includes('process.env.OVERTE_LAB_RENDER_DISPATCH_ATTRIBUTION'));assert(source.includes('if(report.renderDispatchAttributionRequested)'));assert(source.includes('hubDispatchSourceCoherence(sourceFiles'));assert(source.includes('30FPS, p95<=66.7ms and no steady stall>250ms'));assert.equal(source.match(/timeout:60000/g)?.length,2);assert.equal(source.match(/timeout:90000/g)?.length,1);assert(source.includes('assert(report.movementMeters>0.5'));assert(source.includes('assert(report.reconnectedMovementMeters>0.5'));assert(source.includes("'browser-client/src/render-dispatch-attribution.ts'"));assert(source.includes("'browser-client/tests/integration/render-dispatch-pixels.mjs'"));
 const collector=collectHubDispatchAttribution.toString();for(const operation of ['setTimeout','readPixels','getContext','getParameter','requestAnimationFrame','fetch(','useProgram(','renderBufferDirect(','drawCensus','updateMatrixWorld'])assert(!collector.includes(operation),'Collector must only project the existing observer: '+operation);
});
