// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,chmod,writeFile,symlink,link,rm,lstat} from 'node:fs/promises';import {readFileSync} from 'node:fs';import os from 'node:os';import path from 'node:path';
const source=readFileSync(new URL('./integration/public-hub.mjs',import.meta.url),'utf8'),start=source.indexOf('async function requirePrivateMembershipOutput(output) {'),end=source.indexOf('async function distributionManifest()',start);assert(start>=0&&end>start);const exact=source.slice(start,end);
function guard(umask=0o077){return Function('process','lstat','path','report','return ('+exact+')')({getuid:()=>process.getuid(),umask:()=>umask},lstat,path,{startedAt:'2026-10-02T00:00:00.000Z'});}
async function owned(run){const dir=await mkdtemp(path.join(os.tmpdir(),'hub-membership-output-'));await chmod(dir,0o700);try{await run(dir);}finally{await rm(dir,{recursive:true,force:true});}}
test('exact opt-in preflight requires private owned directory, original private existing files and restrictive inherited umask',()=>owned(async dir=>{await guard()(dir);await writeFile(path.join(dir,'public-hub.json'),'{}',{mode:0o600});await guard()(dir);await assert.rejects(guard(0o022)(dir),/Private membership output refused/);await chmod(dir,0o755);await assert.rejects(guard()(dir),/Private membership output refused/);}));
test('actual existing readable files, symlinks and hardlinks refuse without changing metadata or source bytes',()=>owned(async dir=>{const target=path.join(dir,'target'),report=path.join(dir,'public-hub-progress.json');await writeFile(target,'authored untouched',{mode:0o600});await writeFile(report,'public',{mode:0o644});await chmod(report,0o644);await assert.rejects(guard()(dir),/Private membership output refused/);assert.equal((await lstat(report)).mode&0o777,0o644);await rm(report);await symlink(target,report);await assert.rejects(guard()(dir),/Private membership output refused/);await rm(report);await link(target,report);await assert.rejects(guard()(dir),/Private membership output refused/);assert.equal(readFileSync(target,'utf8'),'authored untouched');}));
test('private preflight runs only requested and before any membership collection; exact original four fluid oracles remain',()=>{assert(source.includes('if(report.entityMembershipRequested)await requirePrivateMembershipOutput(output);'));assert(source.indexOf('await requirePrivateMembershipOutput(output)')<source.indexOf('await page.addInitScript'));for(const gate of ['report.walkFluidPerformance=assessFluidPerformance([report.performance.at(-1),report.after.performance])','report.steadyFluidPerformance=assessFluidPerformance(report.performance.slice(-2))','report.reconnectedWalkFluidPerformance=assessFluidPerformance([report.reconnected.performance,report.reconnectedAfterMovement.performance])','report.reconnectedSteadyFluidPerformance=assessFluidPerformance(report.reconnectedSteadySamples.slice(-2))'])assert(source.includes(gate),gate);});

test('explicit private membership output preserves default and requires requested absolute operator path',()=>{
 const first=source.indexOf('function selectPrivateMembershipOutput('),last=source.indexOf('const output=',first);assert(first>=0&&last>first);const choose=Function('path','return ('+source.slice(first,last)+')')(path);
 assert.equal(choose(undefined,false,'original'),'original');assert.equal(choose(undefined,true,'original'),'original');assert.equal(choose('/owned/private',true,'original'),'/owned/private');for(const value of ['relative','',null,42])assert.throws(()=>choose(value,true,'original'),/Private membership output refused/);assert.throws(()=>choose('/owned/private',false,'original'),/Private membership output refused/);
 assert(source.includes("const output=selectPrivateMembershipOutput(process.env.OVERTE_LAB_ENTITY_MEMBERSHIP_OUTPUT,"));assert(source.includes('if(report.entityMembershipRequested)await requirePrivateMembershipOutput(output);'));
});
