// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {planNativeImageEffects,applyNativeImageEffects,updateNativeImagePulse,nativeImageCropCoordinate} from '../src/native-image-effects';
import {makeNativeImageMaterial} from '../src/native-image-material';
import {NativeCompressedColorCache,nativeCompressedImageOriginalSize} from '../src/native-compressed-color';
import {inspectNativeKtx} from '../shared/native-ktx.mjs';
const image=(width=8,height=4)=>new THREE.Texture({width,height} as TexImageSource);
const entity={id:'owned',type:'Image',dimensions:{x:4,y:4,z:.1}};
function ktx(version:number,originalWidth=16,originalHeight=8){const metadata=version===2?60:52,bytes=new Uint8Array(64+metadata+4+8),v=new DataView(bytes.buffer);bytes.set([0xab,0x4b,0x54,0x58,0x20,0x31,0x31,0xbb,13,10,26,10]);[0x04030201,0,1,0,0x8c4c,0x1907,4,4,0,0,1,1,metadata].forEach((n,i)=>v.setUint32(12+4*i,n,true));v.setUint32(64,9+(version===2?44:36),true);bytes.set(new TextEncoder().encode('hifi.gpu\0'),68);bytes[77]=version;v.setUint32(106,1,true);if(version===2){v.setInt32(111,originalWidth,true);v.setInt32(115,originalHeight,true);}v.setUint32(64+metadata,8,true);return bytes;}
function cache(bytes:Uint8Array){return new NativeCompressedColorCache({origin:'https://owned.example',sessionId:'owned',authority:()=> 'permission1',resolveAsset:url=> 'https://owned.example/api/assets/owned?url='+encodeURIComponent(url),capabilities:{s3tc:true,s3tcSRGB:true,maximumTextureSize:32768},fetch:async()=>new Response(bytes as BodyInit)});}
test('native default aspect fits original image inside dimensions without stretching or changing registration bounds',()=>{const map=image();const plan=planNativeImageEffects(entity,map,16);assert.deepEqual(plan.size,{x:4,y:2,z:.1});assert.deepEqual(plan.uv,[.0625,.125,.9375,.875]);assert.deepEqual(plan.warnings,[]);const fit=planNativeImageEffects({...entity,keepAspectRatio:false},map,16);assert.deepEqual(fit.size,entity.dimensions);map.dispose();});
test('native crop is original pixel coordinates with QRect truncation and half texel inset; aspect remains whole-image aspect',()=>{const map=image(8,4),plan=planNativeImageEffects({...entity,subImage:{x:2,y:1,width:4,height:2}},map,16);assert.deepEqual(plan.uv,[2.5/8,1-2.5/4,5.5/8,1-1.5/4]);assert.deepEqual(plan.size,{x:4,y:2,z:.1});const negative=planNativeImageEffects({...entity,subImage:{x:7,y:2,width:-1,height:0}},map,16);assert.deepEqual(negative.uv,[.0625,.125,.9375,.875]);map.dispose();});
test('native filter names map exactly, point/linear aliases and repeat/mirror/clamp retain full mip quality',()=>{const map=image();for(const [native,three]of Object.entries({point:THREE.NearestFilter,linear:THREE.LinearFilter,mipmapPoint:THREE.NearestMipmapNearestFilter,mipmapLinear:THREE.NearestMipmapLinearFilter,linearMipmapPoint:THREE.LinearMipmapNearestFilter,linearMipmapLinear:THREE.LinearMipmapLinearFilter})){const plan=planNativeImageEffects({...entity,sampler:{minFilter:native,magFilter:'point',wrapModeU:'mirror',wrapModeV:'clamp'}},map,8);assert.equal(plan.sampler.min,three);assert.equal(plan.sampler.mag,THREE.NearestFilter);assert.equal(plan.sampler.u,THREE.MirroredRepeatWrapping);assert.equal(plan.sampler.v,THREE.ClampToEdgeWrapping);assert.equal(plan.sampler.anisotropy,8);assert.deepEqual(plan.warnings,[]);}const defaults=planNativeImageEffects(entity,map,32);assert.equal(defaults.sampler.min,THREE.LinearMipmapLinearFilter);assert.equal(defaults.sampler.u,THREE.RepeatWrapping);assert.equal(defaults.sampler.anisotropy,16);assert.equal(planNativeImageEffects({...entity,sampler:{filter:'linear',wrap:'clamp'}},map,16).sampler.min,THREE.LinearFilter);map.dispose();});
test('unknown wrap/filter/effect records warn instead of claiming unsupported behavior',()=>{const map=image();const plan=planNativeImageEffects({...entity,sampler:{wrapModeU:'border',minFilter:'unknown',extra:true},subImage:{x:0,y:0,width:0,height:0,extra:true},pulse:{colorMode:'in',period:1}},map,16);assert.equal(plan.warnings.length,5);assert.equal(plan.pulse,undefined);assert.equal(plan.sampler.u,THREE.RepeatWrapping);assert.equal(plan.sampler.min,THREE.LinearMipmapLinearFilter);map.dispose();});
test('owned Plane UVs and samplers change independently without shared Source/image/version mutation',()=>{const first=image(),second=first.clone(),version=first.source.version,textureVersion=first.version,geometry=new THREE.PlaneGeometry(),other=new THREE.PlaneGeometry(),material=makeNativeImageMaterial({},first,'opaque');const baseline=Array.from(other.getAttribute('uv').array),plan=planNativeImageEffects({...entity,subImage:{x:2,y:1,width:4,height:2},sampler:{wrapModeU:'mirror'}},first,16);applyNativeImageEffects(plan,first,geometry,material);assert.equal(first.source,second.source);assert.equal(first.source.version,version);assert.equal(first.version,textureVersion);assert.equal(second.wrapS,THREE.ClampToEdgeWrapping);assert.equal(first.wrapS,THREE.MirroredRepeatWrapping);assert.deepEqual(Array.from(other.getAttribute('uv').array),baseline);assert.deepEqual(Array.from(geometry.getAttribute('uv').array),[.3125,.625,.6875,.625,.3125,.375,.6875,.375]);geometry.dispose();other.dispose();material.dispose();first.dispose();second.dispose();});
test('native pulse starts at max, uses creation-relative cosine and color sRGB multiplication before decode',()=>{const map=image(),authored={color:{red:128,green:64,blue:32},alpha:.5},material=makeNativeImageMaterial(authored,map,'opaque'),pulse={min:0,max:1,period:4,colorMode:'in' as const,alphaMode:'out' as const,created:1000000};updateNativeImagePulse(pulse,authored,material,1000000);assert.equal(material.color.getHex(THREE.SRGBColorSpace),0x804020);assert.equal(material.opacity,0);updateNativeImagePulse(pulse,authored,material,2000000);const expected=new THREE.Color().setRGB(64/255,32/255,16/255,THREE.SRGBColorSpace);assert.ok(Math.abs(material.color.r-expected.r)<1e-7);assert.ok(Math.abs(material.opacity-.25)<1e-7);updateNativeImagePulse(pulse,authored,material,3000000);assert.ok(material.color.r<1e-10);assert.equal(material.opacity,.5);material.dispose();map.dispose();});
test('pulse period zero returns authored color and alpha while alpha mode retains native blend pipeline',()=>{const map=image(),e={...entity,created:1000000,pulse:{min:.3,max:.6,period:0,colorMode:'out',alphaMode:'in'},color:{red:128,green:128,blue:128}},plan=planNativeImageEffects(e,map,16),material=makeNativeImageMaterial(e,map,'opaque'),geometry=new THREE.PlaneGeometry();applyNativeImageEffects(plan,map,geometry,material);assert.equal(material.transparent,true);assert.equal(material.depthWrite,false);updateNativeImagePulse(plan.pulse!,e,material,2000000);assert.equal(material.color.getHex(THREE.SRGBColorSpace),0x808080);assert.equal(material.opacity,1);assert.throws(()=>updateNativeImagePulse(plan.pulse!,e,material,0),/creation clock/);geometry.dispose();material.dispose();map.dispose();});
test('default inactive pulse needs no timestamp or dynamic owner; unsupported factors warn without fabricating time',()=>{const map=image();assert.equal(planNativeImageEffects({...entity,pulse:{colorMode:'none',alphaMode:'none'}},map,16).pulse,undefined);for(const e of [{created:NaN,pulse:{colorMode:'in'}},{created:0,pulse:{colorMode:'in',min:-1,max:2}},{created:0,pulse:{alphaMode:'in',min:2,max:.5}}]){const plan=planNativeImageEffects({...entity,...e},map,16);assert.equal(plan.pulse,undefined);assert.equal(plan.warnings.length,1);}map.dispose();});
test('malformed native crop/aspect/dimensions or unavailable decoded image refuse before altering owned resources',()=>{const map=image();for(const extra of [{subImage:{x:.5,width:3}},{subImage:{width:Infinity}},{keepAspectRatio:'true'},{dimensions:{x:0,y:2,z:1}},{sampler:null}])assert.throws(()=>planNativeImageEffects({...entity,...extra} as never,map,16));assert.throws(()=>planNativeImageEffects(entity,new THREE.Texture(),16),/loaded texture dimensions/);map.dispose();});
test('strict KTX v2 reads original pixel dimensions at native packed offsets without extending metadata authority',async()=>{const bytes=ktx(2),parsed=inspectNativeKtx(bytes);assert.deepEqual(parsed.nativeUsage.originalSize,{width:16,height:8});const owned=cache(bytes),map=await owned.load('https://asset.example/original.ktx');try{assert.deepEqual(nativeCompressedImageOriginalSize(map),{width:16,height:8});const plan=planNativeImageEffects({...entity,subImage:{x:8,y:4,width:8,height:4}},map,16);assert.deepEqual(plan.size,{x:4,y:2,z:.1});assert.deepEqual(plan.uv,[.625,.125,.875,.375]);const clone=map.clone();assert.equal(nativeCompressedImageOriginalSize(clone),undefined);clone.dispose();const source=map.source;map.source=new THREE.TextureSource({width:4,height:4});assert.equal(nativeCompressedImageOriginalSize(map),undefined);map.source=source;const copied=nativeCompressedImageOriginalSize(map)!;copied.width=1;assert.equal(nativeCompressedImageOriginalSize(map)!.width,16);}finally{map.dispose();owned.dispose();}});
test('version1/invalid original size cannot invent native crop/aspect; exact owned bytes still remain usable',async()=>{for(const bytes of [ktx(1),ktx(2,0,0),ktx(2,-1,8)]){const owned=cache(bytes),map=await owned.load('https://asset.example/legacy.ktx');try{assert.equal(nativeCompressedImageOriginalSize(map),undefined);const plan=planNativeImageEffects({...entity,subImage:{x:1,y:1,width:2,height:2}},map,16);assert.deepEqual(plan.size,entity.dimensions);assert.equal(plan.warnings.length,2);assert.deepEqual(plan.uv,[.125,.125,.875,.875]);}finally{map.dispose();owned.dispose();}}});

test('native inverted ranges and negative periods preserve the unrestricted cosine equation',()=>{const map=image(),entity={id:'invert',type:'Image',created:1000000,pulse:{min:1,max:0,period:-4,colorMode:'in'}},plan=planNativeImageEffects(entity,map,16),material=makeNativeImageMaterial({emissive:true},map,'opaque');assert.deepEqual(plan.warnings,[]);assert.ok(plan.pulse);updateNativeImagePulse(plan.pulse,{},material,1000000);assert.equal(material.color.r,0);updateNativeImagePulse(plan.pulse,{},material,3000000);assert.equal(material.color.r,1);material.dispose();map.dispose();});

test('native QRect float arithmetic truncates the rounded scaled result, including non-power-of-two exact mathematical boundaries',()=>{assert.equal(nativeImageCropCoordinate(41,4,41),3);assert.equal(nativeImageCropCoordinate(-41,4,41),-3);assert.equal(nativeImageCropCoordinate(8,4,16),2);assert.equal(nativeImageCropCoordinate(2,4,16),0);});

// QRect coordinates are signed int32, including the asymmetric negative endpoint.
test('native crop admits both signed-int32 endpoints and rejects only values outside that exact range',()=>{
 const map=image();
 try {
  for(const field of ['x','y','width','height'])for(const value of [-2147483648,2147483647]){
   const plan=planNativeImageEffects({...entity,subImage:{x:0,y:0,width:1,height:1,[field]:value}},map,16);
   assert.deepEqual(plan.warnings,[]);
  }
  for(const field of ['x','y','width','height'])for(const value of [-2147483649,2147483648,.5,NaN,Infinity,'-2147483648']){
   assert.throws(()=>planNativeImageEffects({...entity,subImage:{x:0,y:0,width:1,height:1,[field]:value}} as never,map,16),/finite|signed integer/);
  }
 }finally{map.dispose();}
});
test('native minimum crop coordinates retain exact float32 UV endpoints and negative extents retain the native full-axis fallback',()=>{
 const map=image(),geometry=new THREE.PlaneGeometry(),material=makeNativeImageMaterial({},map,'opaque');
 try{
  assert.equal(nativeImageCropCoordinate(-2147483648,8,8),-2147483648);
  const plan=planNativeImageEffects({...entity,subImage:{x:-2147483648,y:-2147483648,width:1,height:1}},map,16);
  applyNativeImageEffects(plan,map,geometry,material);
  // Independent reference: QRect INT_MIN, 8x4 texture, half-texel endpoints
  // round to these exactly representable float32 powers of two.
  assert.deepEqual(Array.from(geometry.getAttribute('uv').array),[-268435456,536870912,-268435456,536870912,-268435456,536870912,-268435456,536870912]);
  const full=planNativeImageEffects({...entity,subImage:{x:-2147483648,y:-2147483648,width:-2147483648,height:-2147483648}},map,16);
  assert.deepEqual(full.uv,[.0625,.125,.9375,.875]);
 }finally{geometry.dispose();material.dispose();map.dispose();}
});
