// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync as readCurrentFileSync} from 'node:fs';
import {prepareStartupV30HistoryReaders} from './integration/capture-startup-runtime-source-fixture.mjs';
const {readFileSync}=await prepareStartupV30HistoryReaders(import.meta.url,readCurrentFileSync);
import vm from 'node:vm';
const fixture=readFileSync(new URL('./fixtures/native-ignored-fbx-pixels.ts',import.meta.url),'utf8');
const runner=readFileSync(new URL('./integration/native-ignored-fbx-pixels.mjs',import.meta.url),'utf8');
const between=(source,start,end)=>{const a=source.indexOf(start),b=source.indexOf(end,a+start.length);assert(a>=0&&b>a);assert.equal(source.indexOf(start,a+1),-1);return source.slice(a+start.length,b);};
const producer=between(fixture,'// BEGIN fixed native-ignored GPU read observation.','// END fixed native-ignored GPU read observation.')
 .replace('[] as (number|null)[][]','[]').replace('diagnostic:ReturnType<typeof createNativeIgnoredGpuDiagnostic>,code:unknown','diagnostic,code');
const consumer=between(runner,'// BEGIN fixed native-ignored GPU read consumer.','// END fixed native-ignored GPU read consumer.');
function realm(extra={}){const context=vm.createContext({assert,performance,setTimeout,clearTimeout,...extra});vm.runInContext(producer+consumer+'\n globalThis.api={createNativeIgnoredGpuDiagnostic,recordNativeIgnoredGpuRead,validateNativeIgnoredGpuDiagnostic,collectNativeIgnoredGpuDiagnostic};',context);return context;}
const json=value=>JSON.parse(JSON.stringify(value));
test('actual producer to consumer preserves background, baseline and twenty candidate codes',()=>{const {api}=realm();const d=api.createNativeIgnoredGpuDiagnostic();for(let i=0;i<22;i++)api.recordNativeIgnoredGpuRead(d,i===21?1282:0);assert.equal(api.validateNativeIgnoredGpuDiagnostic(d),d);assert.deepEqual(json(d.records),Array.from({length:22},(_,i)=>[i,i===0?0:i===1?1:2,i===21?1282:0]));api.recordNativeIgnoredGpuRead(d,0);assert.equal(d.records.length,22);assert.equal(d.refused,true);});
test('invalid codes become unknown; raw private strings cannot survive projection',()=>{const {api}=realm();for(const code of ['private-shader/path',-1,65536,NaN,Infinity,1.5,{},undefined]){const d=api.createNativeIgnoredGpuDiagnostic();api.recordNativeIgnoredGpuRead(d,code);assert.deepEqual(json(api.validateNativeIgnoredGpuDiagnostic(d)),{version:1,records:[[0,0,null]],refused:true});}for(const code of [0,1280,1281,1282,1285,1286,37442,65535]){const d=api.createNativeIgnoredGpuDiagnostic();api.recordNativeIgnoredGpuRead(d,code);assert.equal(api.validateNativeIgnoredGpuDiagnostic(d).records[0][2],code);}});
test('consumer rejects unknown shape, ordinal, phase, oversized and unrefused null',()=>{const {api}=realm();for(const d of [{version:1,records:[],refused:false,raw:'private'},{version:2,records:[],refused:false},{version:1,records:[[1,0,0]],refused:false},{version:1,records:[[0,2,0]],refused:false},{version:1,records:[[0,0,null]],refused:false},{version:1,records:[[0,0,'1282']],refused:false},{version:1,records:Array(23).fill([0,0,0]),refused:false}])assert.throws(()=>api.validateNativeIgnoredGpuDiagnostic(d));});
test('actual read body captures same getError return before same assertion without changing GL effects',()=>{const readBody=between(fixture,'const read=','\n try{').trim();assert.equal((readBody.match(/\.getError\(/g)||[]).length,1);let code=0,queries=0;const effects=[];const context=realm({scene:{add(){effects.push('add');},remove(){effects.push('remove');}},target:{},camera:{},renderer:{setRenderTarget(){effects.push('target');},setClearColor(){effects.push('clear');},render(){effects.push('render');},readRenderTargetPixels(){effects.push('read');},getContext(){return {getError(){queries++;effects.push('error');return code;}};}}});vm.runInContext('const gpuReadDiagnostic=createNativeIgnoredGpuDiagnostic(); const read='+readBody.replace('(root?:THREE.Object3D)','(root)')+'\n globalThis.read=read;globalThis.d=gpuReadDiagnostic;',context);context.read();context.read({});code=1282;assert.throws(()=>context.read({}),/Actual GPU render produced a GL error/);assert.equal(queries,3);assert.deepEqual(json(context.d.records),[[0,0,0],[1,1,0],[2,2,1282]]);assert.deepEqual(effects,['target','clear','render','read','error','add','target','clear','render','read','remove','error','add','target','clear','render','read','remove','error']);});
test('original deadline, missing deadline and elapsed deadline skip RPC',async()=>{let calls=0;const {api}=realm({performance:{now:()=>100}});for(const [message,deadline] of [['Native ignored FBX pixel fixture exceeded 30 seconds',200],['GPU error',undefined],['GPU error',100],['GPU error',99]])assert.deepEqual(json(await api.collectNativeIgnoredGpuDiagnostic({evaluate(){calls++;}},message,deadline)),{gpuReadDiagnosticRefusal:'original-fixture-deadline'});assert.equal(calls,0);});
test('never settling RPC uses smaller remaining original budget and reaches cleanup',async()=>{let callback,budget,cleared=0,finallyReached=false;const {api}=realm({performance:{now:()=>100},setTimeout(fn,ms){callback=fn;budget=ms;return 7;},clearTimeout(id){assert.equal(id,7);cleared++;}});const pending=(async()=>{try{return await api.collectNativeIgnoredGpuDiagnostic({evaluate:()=>new Promise(()=>{})},'GPU error',123);}finally{finallyReached=true;}})();await Promise.resolve();assert.equal(budget,23);callback();assert.deepEqual(json(await pending),{gpuReadDiagnosticRefusal:'unavailable-or-invalid'});assert.equal(finallyReached,true);assert.equal(cleared,1);});
test('settled RPC clears capped timer and preserves exact safe payload',async()=>{let budget,cleared=0;const {api}=realm({performance:{now:()=>100},setTimeout(fn,ms){budget=ms;return 8;},clearTimeout(id){assert.equal(id,8);cleared++;}});const d=api.createNativeIgnoredGpuDiagnostic();api.recordNativeIgnoredGpuRead(d,37442);assert.deepEqual(json(await api.collectNativeIgnoredGpuDiagnostic({evaluate:async()=>d},'GPU error',10000)),{gpuReadDiagnostic:{version:1,records:[[0,0,37442]],refused:false}});assert.equal(budget,500);assert.equal(cleared,1);});
test('late resolve and reject are consumed after timeout, without unhandled rejection',async()=>{let unhandled=0;const listener=()=>unhandled++;process.on('unhandledRejection',listener);try{for(const rejectLate of [false,true]){let callback,resolve,reject;const {api}=realm({performance:{now:()=>100},setTimeout(fn){callback=fn;return 9;},clearTimeout(){}});const pending=api.collectNativeIgnoredGpuDiagnostic({evaluate:()=>new Promise((a,b)=>{resolve=a;reject=b;})},'GPU error',200);await Promise.resolve();callback();const result=await pending;if(rejectLate)reject(Error('private late error'));else resolve({version:1,records:[],refused:false});await new Promise(setImmediate);assert.deepEqual(json(result),{gpuReadDiagnosticRefusal:'unavailable-or-invalid'});}assert.equal(unhandled,0);}finally{process.off('unhandledRejection',listener);}});
test('deadline recheck refuses RPC if microtask begins after original deadline',async()=>{let calls=0,n=0;const {api}=realm({performance:{now:()=>++n===1?100:201}});const result=await api.collectNativeIgnoredGpuDiagnostic({evaluate(){calls++;}},'GPU error',200);assert.equal(calls,0);assert.equal(result.gpuReadDiagnosticRefusal,'unavailable-or-invalid');});
test('actual launcher catch preserves original failure and exit while finally executes',async()=>{const catchBody=between(runner,'}catch(error){report.error=','\nfinally{');const context=realm({process:{exitCode:0}});vm.runInContext('globalThis.exercise=async function(diagnosticPage,fixtureDeadline){const report={};let finalized=false;try{throw Error("Actual GPU render produced a GL error");}catch(error){report.error='+catchBody+'finally{finalized=true;}return {report,finalized,exitCode:process.exitCode};};',context);const result=await context.exercise({evaluate:async()=>({version:1,records:[[0,0,1282]],refused:false})},performance.now()+500);assert.equal(result.report.error,'Actual GPU render produced a GL error');assert.equal(result.exitCode,1);assert.equal(result.finalized,true);assert.deepEqual(json(result.report.gpuReadDiagnostic.records),[[0,0,1282]]);});
