// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import vm from 'node:vm';
const fixture=readFileSync(new URL('./fixtures/native-ignored-fbx-pixels.ts',import.meta.url),'utf8');
const runner=readFileSync(new URL('./integration/native-ignored-fbx-pixels.mjs',import.meta.url),'utf8');
const between=(source,start,end)=>{const a=source.indexOf(start),b=source.indexOf(end,a+start.length);assert(a>=0&&b>a);assert.equal(source.indexOf(start,a+1),-1);return source.slice(a+start.length,b);};
const producer=stripTypeScriptTypes(between(fixture,'// BEGIN fixed native-ignored GPU read observation.','// END fixed native-ignored GPU read observation.'));
const consumer=between(runner,'// BEGIN fixed native-ignored GPU read consumer.','// END fixed native-ignored GPU read consumer.');
const json=value=>JSON.parse(JSON.stringify(value));
function realm(extra={}){const context=vm.createContext({assert,performance,setTimeout,clearTimeout,...extra});vm.runInContext(producer+consumer+'\n globalThis.api={createNativeIgnoredGpuDiagnostic,recordNativeIgnoredGpuRead,observeNativeIgnoredGpuContext:typeof observeNativeIgnoredGpuContext==="function"?observeNativeIgnoredGpuContext:undefined,validateNativeIgnoredGpuDiagnostic,collectNativeIgnoredGpuDiagnostic};',context);return context;}
function canvas(){const listeners=new Map();return {listeners,addEventListener(type,fn){listeners.set(type,fn);},removeEventListener(type,fn){if(listeners.get(type)===fn)listeners.delete(type);},emit(type,extra={}){listeners.get(type)?.({isTrusted:true,target:this,currentTarget:this,...extra});}};}
test('actual v2 producer and strict consumer preserve all 22 legacy read tuples',()=>{const {api}=realm(),d=api.createNativeIgnoredGpuDiagnostic(),c=canvas(),o=api.observeNativeIgnoredGpuContext(d,c);o.sample(()=>false);o.phase(5);o.sample(()=>true);for(let i=0;i<22;i++)api.recordNativeIgnoredGpuRead(d,i===0?37442:0);assert.equal(api.validateNativeIgnoredGpuDiagnostic(d),d);assert.deepEqual(json(d.records),Array.from({length:22},(_,i)=>[i,i===0?0:i===1?1:2,i===0?37442:0]));assert.deepEqual(json(d.contextStates),[[0,0,0],[1,5,1]]);o.retire();assert.equal(c.listeners.size,0);});
test('trusted own canvas events retain only ordinal, loss/restored kind and active operation phase',()=>{const {api}=realm(),d=api.createNativeIgnoredGpuDiagnostic(),c=canvas(),o=api.observeNativeIgnoredGpuContext(d,c);o.phase(3);c.emit('webglcontextlost',{statusMessage:'private driver/path'});o.phase(4);c.emit('webglcontextrestored');c.emit('webglcontextlost',{isTrusted:false});c.emit('webglcontextlost',{target:{}});c.emit('webglcontextlost',{currentTarget:{}});assert.deepEqual(json(api.validateNativeIgnoredGpuDiagnostic(d).contextEvents),[[0,0,3],[1,1,4]]);assert.equal(JSON.stringify(d).includes('private'),false);});
test('event cap censors without adding rows or invoking prevention/restoration',()=>{const {api}=realm(),d=api.createNativeIgnoredGpuDiagnostic(),c=canvas(),o=api.observeNativeIgnoredGpuContext(d,c);let prevented=0;for(let i=0;i<10;i++)c.emit('webglcontextlost',{preventDefault(){prevented++;}});assert.equal(d.contextEvents.length,8);assert.equal(d.refused,true);assert.equal(prevented,0);assert.equal(api.validateNativeIgnoredGpuDiagnostic(d),d);o.retire();});
test('unknown query values and thrown private errors remain null/refused',()=>{const {api}=realm();for(const read of [()=>undefined,()=>1,()=>null,()=> 'private',()=>{throw Error('private driver/path');}]){const d=api.createNativeIgnoredGpuDiagnostic(),o=api.observeNativeIgnoredGpuContext(d,canvas());o.sample(read);assert.deepEqual(json(api.validateNativeIgnoredGpuDiagnostic(d)),{version:2,records:[],refused:true,contextStates:[[0,0,null]],contextEvents:[]});o.retire();}});
test('two-read cap and retired observer never invoke a new GL operation',()=>{const {api}=realm(),d=api.createNativeIgnoredGpuDiagnostic(),c=canvas(),o=api.observeNativeIgnoredGpuContext(d,c);let calls=0;const read=()=>{calls++;return false;};o.sample(read);o.phase(5);o.sample(read);o.sample(read);assert.equal(calls,2);assert.equal(d.refused,true);o.retire();o.retire();o.sample(read);o.phase(2);c.emit('webglcontextlost');assert.equal(calls,2);assert.equal(d.contextEvents.length,0);assert.equal(c.listeners.size,0);});
test('listener attachment/removal refusal is bounded and cannot reflect exception text',()=>{const {api}=realm(),d=api.createNativeIgnoredGpuDiagnostic(),c={addEventListener(){throw Error('private');},removeEventListener(){throw Error('private');}};const o=api.observeNativeIgnoredGpuContext(d,c);o.retire();assert.equal(d.refused,true);assert.equal(JSON.stringify(d).includes('private'),false);});
test('strict current consumer rejects old v1, unknown fields, caps, wrong phases and unrefused unknowns',()=>{const {api}=realm();const valid=json(api.createNativeIgnoredGpuDiagnostic());for(const d of [{version:1,records:[],refused:false},{...valid,raw:'private'},{...valid,contextStates:[[0,1,0]]},{...valid,contextStates:[[0,0,null]]},{...valid,contextStates:[[0,0,2]]},{...valid,contextStates:[[0,0,0],[1,5,0],[2,5,0]]},{...valid,contextEvents:[[0,2,0]]},{...valid,contextEvents:[[0,0,9]]},{...valid,contextEvents:[[1,0,0]]},{...valid,contextEvents:Array.from({length:9},(_,i)=>[i,0,0])}])assert.throws(()=>api.validateNativeIgnoredGpuDiagnostic(d));});
test('invalid phase refuses while preserving previous finite event phase',()=>{const {api}=realm(),d=api.createNativeIgnoredGpuDiagnostic(),c=canvas(),o=api.observeNativeIgnoredGpuContext(d,c);o.phase(4);for(const phase of [-1,9,NaN,'private',{}])o.phase(phase);c.emit('webglcontextlost');assert.equal(d.refused,true);assert.deepEqual(json(api.validateNativeIgnoredGpuDiagnostic(d).contextEvents),[[0,0,4]]);o.retire();});
test('actual read retains one original getError, GL effects and original failure after context annotation',()=>{const readBody=stripTypeScriptTypes('const read='+between(fixture,'const read=','\n try{').trim());assert.equal((readBody.match(/\.getError\(/g)||[]).length,1);let errorCode=37442,errorCalls=0;const effects=[],phases=[];const context=realm({scene:{add(){effects.push('add');},remove(){effects.push('remove');}},target:{},camera:{},contextObservation:{phase(value){phases.push(value);}},renderer:{setRenderTarget(){effects.push('target');},setClearColor(){effects.push('clear');},render(){effects.push('render');},readRenderTargetPixels(){effects.push('read');},getContext(){return {getError(){errorCalls++;effects.push('error');return errorCode;}};}}});vm.runInContext('const gpuReadDiagnostic=createNativeIgnoredGpuDiagnostic();'+readBody+'\n globalThis.read=read;globalThis.d=gpuReadDiagnostic;',context);assert.throws(()=>context.read(),/Actual GPU render produced a GL error/);errorCode=0;context.read({});context.read({});assert.equal(errorCalls,3);assert.deepEqual(phases,[6,7,8]);assert.deepEqual(effects,['target','clear','render','read','error','add','target','clear','render','read','remove','error','add','target','clear','render','read','remove','error']);assert.deepEqual(json(context.d.records),[[0,0,37442],[1,1,0],[2,2,0]]);});
function fixtureRealm(lossAt){
 const transportURL={createObjectURL(){return 'blob:owned';},revokeObjectURL(){}};
 const c=canvas(),window={},effects=[],state={lost:false,queries:0,errorQueries:0,root:false,disposed:false};
 class LoadingManager{constructor(done,progress,error){this.done=done;this.error=error;}setURLModifier(resolve){this.resolve=resolve;}}
 class FBXLoader{constructor(manager){this.manager=manager;}parse(){const kind=effects.includes('parse')?'candidate':'baseline';effects.push('parse');this.manager.resolve(transportURL.createObjectURL({}));this.manager.resolve(transportURL.createObjectURL({}));if(kind==='baseline'){this.manager.resolve('http://fixture/__native_ignored/unused-a.dds');this.manager.error('http://fixture/__native_ignored/unused-a.dds');}this.manager.done();return {traverse(){}};}}
 class Pool{constructor(){this.counters={workers:0,outstanding:0,inputBytes:0};}prepare(bytes,signal){if(signal)return new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')),{once:true}));if(lossAt==='prepare'&&!effects.includes('prepare')){state.lost=true;c.emit('webglcontextlost');}effects.push('prepare');return Promise.resolve({buffer:bytes,embeddedImages:[]});}}
 class Registry{constructor(){this.statistics={entries:0,scopes:0};}register(){return {resolveURL:url=>url,close(){}};}}
 class Renderer{constructor(){this.domElement=c;}setSize(){}setPixelRatio(){}setRenderTarget(){effects.push('target');}setClearColor(){}render(){effects.push('render');if(lossAt==='background'&&!effects.includes('read')){state.lost=true;c.emit('webglcontextlost');}}readRenderTargetPixels(target,x,y,w,h,out){effects.push('read');out.fill(state.root?255:0);}getContext(){return {isContextLost(){state.queries++;return state.lost;},getError(){state.errorQueries++;return state.lost?37442:0;},getExtension(){return null;},getParameter(){return 'mock';}};}dispose(){state.disposed=true;}}
 class Scene{add(root){if(!(root instanceof AmbientLight))state.root=true;}remove(){state.root=false;}}
 class AmbientLight{};class Camera{constructor(){this.position={};}}class Target{dispose(){}}
 const THREE={WebGLRenderer:Renderer,LoadingManager,Scene,AmbientLight,OrthographicCamera:Camera,WebGLRenderTarget:Target,Mesh:class {},NoToneMapping:0,LinearSRGBColorSpace:0};
 const context=realm({window,THREE,FBXLoader,BakedFbxPreparePool:Pool,EmbeddedFbxImages:Registry,normalizeNativeFbxTransparency:b=>b,ModelResources:class {capture(){}releaseKeeping(){}},AbortController,DOMException,URL:transportURL,location:{origin:'http://fixture'},document:{body:{appendChild(){}}},fetch:async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(4)}),assert:(v,m)=>{if(!v)throw Error(m);}});
 c.remove=()=>{};
 const body=fixture.slice(fixture.indexOf('export async function runNativeIgnoredFbxPixels()')).replace('export async function','async function');vm.runInContext(stripTypeScriptTypes(body),context);
 return {context,state,effects,c,window};
}
test('actual full fixture distinguishes loss during original preparation await from first background GL operation',async()=>{for(const lossAt of ['prepare','background']){const {context,state,c,window}=fixtureRealm(lossAt);await assert.rejects(context.window.runNativeIgnoredFbxPixels(),/Actual GPU render produced a GL error/);const d=json(window.__nativeIgnoredGpuReadDiagnostic);assert.deepEqual(d.records,[[0,0,37442]]);assert.deepEqual(d.contextStates,[[0,0,0],[1,5,lossAt==='prepare'?1:0]]);assert.deepEqual(d.contextEvents,[[0,0,lossAt==='prepare'?3:6]]);assert.equal(state.queries,2);assert.equal(state.errorQueries,1);assert.equal(state.disposed,true);assert.equal(c.listeners.size,0);}});
test('actual full fixture success keeps original 22 reads, cancellation and listener retirement',async()=>{const {context,state,c,window}=fixtureRealm('none');const result=await context.window.runNativeIgnoredFbxPixels();assert.equal(result.completed,true);assert.equal(result.cancelledAdmission,true);assert.equal(result.frames,20);assert.equal(state.queries,2);assert.equal(state.errorQueries,22);assert.equal(state.disposed,true);assert.equal(c.listeners.size,0);assert.equal(window.__nativeIgnoredGpuReadDiagnostic.records.length,22);assert.deepEqual(json(window.__nativeIgnoredGpuReadDiagnostic.contextStates),[[0,0,0],[1,5,0]]);});
test('new payload keeps existing failed-only deadline skip and bounded response path',async()=>{let calls=0,budget,cleared=0;const {api}=realm({performance:{now:()=>100},setTimeout(fn,ms){budget=ms;return 1;},clearTimeout(){cleared++;}});assert.deepEqual(json(await api.collectNativeIgnoredGpuDiagnostic({evaluate(){calls++;}},'Native ignored FBX pixel fixture exceeded 30 seconds',1000)),{gpuReadDiagnosticRefusal:'original-fixture-deadline'});const d=api.createNativeIgnoredGpuDiagnostic();api.recordNativeIgnoredGpuRead(d,37442);assert.deepEqual(json(await api.collectNativeIgnoredGpuDiagnostic({evaluate(){calls++;return Promise.resolve(d);}},'GPU error',123)),{gpuReadDiagnostic:json(d)});assert.equal(calls,1);assert.equal(budget,23);assert.equal(cleared,1);});
