// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import {weightedAreaImagePixels,imagePixelComparison,assertLoadedImagePixels} from './integration/native-image-pixels.mjs';
function image(width,height,make){const rgba=new Uint8ClampedArray(width*height*4);for(let y=0;y<height;y++)for(let x=0;x<width;x++)rgba.set(make(x,y),(y*width+x)*4);return{rgba,width,height};}
const close=(a,b)=>assert(Math.abs(a-b)<1e-8,`${a} != ${b}`);
test('area checkerboard minification integrates all source pixels, without four-tap alias',()=>{const source=image(12,12,(x,y)=>{const v=(x+y)%2?192:64;return[v,v,v,255];}),out=weightedAreaImagePixels({...source,grid:2});assert.deepEqual(out.rgb,Array(12).fill(128));assert.equal(out.variance,0);});
test('fractional crop and boundary footprints use exact pixel overlap weights',()=>{const source=image(2,2,(x,y)=>[x*40+y*80,0,0,255]);close(weightedAreaImagePixels({...source,grid:1,crop:{x:.5,y:.5,width:1,height:1}}).rgb[0],60);close(weightedAreaImagePixels({...source,grid:1,crop:{x:.25,y:0,width:1,height:1}}).rgb[0],10);assert.deepEqual(weightedAreaImagePixels({...source,grid:1,crop:{x:1,y:1,width:1,height:1}}).rgb,[120,0,0]);});
test('hidden RGBA composes authored magenta per pixel before reduction; source input is untouched',()=>{const source=image(2,1,x=>x?[1,250,30,0]:[0,0,0,128]),before=source.rgba.slice();const out=weightedAreaImagePixels({...source,grid:2,composeNativeAlpha:true});assert.deepEqual(out.rgb,[187,0,187,255,0,255,187,0,187,255,0,255]);assert.deepEqual(out.mask,[1,1,1,1]);assert.deepEqual(source.rgba,before);const reduced=weightedAreaImagePixels({...source,grid:1,composeNativeAlpha:true});assert.deepEqual(reduced.rgb,[221,0,221]);assert.notDeepEqual(reduced.rgb,[128,0,128]);});
test('actual screenshot bytes are not alpha-composited or brightness-normalized by default',()=>{const source=image(1,1,()=>[20,35,60,0]);assert.deepEqual(weightedAreaImagePixels({...source,grid:1}).rgb,[20,35,60]);assert.deepEqual(weightedAreaImagePixels({...source,grid:1,composeNativeAlpha:true}).rgb,[255,0,255]);});
test('source detail and UV reversal controls retain exact existing .9 correlation and ten-level RGB bounds',()=>{const source=image(32,32,(x,y)=>[x*7,y*6,(x+y)%3*50,255]),reference=weightedAreaImagePixels({...source,grid:16});assertLoadedImagePixels(reference,reference);for(const [h,v]of [[true,false],[false,true],[true,true]]){const reversed=image(32,32,(x,y)=>{const n=((v?31-y:y)*32+(h?31-x:x))*4;return Array.from(source.rgba.slice(n,n+4));});assert.throws(()=>assertLoadedImagePixels(weightedAreaImagePixels({...reversed,grid:16}),reference));}const shifted={...reference,rgb:reference.rgb.map(x=>x+11)};assert(imagePixelComparison(shifted,reference).correlation>.99);assert.throws(()=>assertLoadedImagePixels(shifted,reference),/colors/);const flat={...reference,rgb:reference.rgb.map((_,i)=>[108.5,93,50][i%3])};assert.throws(()=>assertLoadedImagePixels(flat,reference));});
test('unmixed authored holes stay classified, while genuine textured pixels remain visible',()=>{const source=image(4,4,x=>x<2?[255,0,255,255]:[20,90,10,255]),sample=weightedAreaImagePixels({...source,grid:2});assert.deepEqual(sample.mask,[1,0,1,0]);assert.equal(sample.backgroundCoverage,.5);});
test('bounded dimensions, exact RGBA views, grid sizes, and options reject before sampler allocation',()=>{for(const options of [{width:2049,height:2048},{width:4194304,height:1},{width:0,height:1},{width:1.1,height:1}])assert.throws(()=>weightedAreaImagePixels({rgba:new Uint8Array(0),...options}),/bounded/);const source=image(1,1,()=>[0,0,0,255]);for(const extra of [{rgba:[0,0,0,255]},{rgba:new Uint16Array(4)},{rgba:new Uint8Array(5)},{grid:0},{grid:65},{grid:1.1},{composeNativeAlpha:1}])assert.throws(()=>weightedAreaImagePixels({...source,...extra}));});
test('out-of-bounds, nonfinite and numerically unresolvable crop cells fail explicitly',()=>{const source=image(2,2,()=>[0,0,0,255]);for(const crop of [null,{x:-.1,y:0,width:1,height:1},{x:0,y:0,width:3,height:1},{x:0,y:0,width:1,height:0},{x:NaN,y:0,width:1,height:1},{x:0,y:Infinity,width:1,height:1}])assert.throws(()=>weightedAreaImagePixels({...source,crop}));assert.throws(()=>weightedAreaImagePixels({...source,crop:{x:0,y:0,width:Number.MIN_VALUE,height:1}}),/too small/);});
test('fractional opaque white has physically bounded channels despite floating-point overlap sums',()=>{const source=image(101,103,()=>[255,255,255,255]),sample=weightedAreaImagePixels({...source,crop:{x:.01,y:.03,width:99.921,height:101.773}});assert(sample.rgb.every(v=>v<=255&&v>254.99999));assert.doesNotThrow(()=>imagePixelComparison(sample,sample));});
