// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Actual WebGL/World publication, authored original source pixels and owned RAF.
// This is not a matched-native ambient/BRDF/transparent-RGB parity claim.
import {expect,test} from '@playwright/test';
test('actual World native aspect/crop/sampler use owned UVs and independent source clones',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');
 const report=await page.evaluate(async()=>{
  const module='/tests/native-image-effects-fixture.ts';const{THREE,BrowserWorld}=await import(/* @vite-ignore */module);
  const source=document.createElement('canvas');source.width=16;source.height=8;const ctx=source.getContext('2d')!;
  ctx.fillStyle='red';ctx.fillRect(0,0,8,8);ctx.fillStyle='lime';ctx.fillRect(8,0,8,8);const url=source.toDataURL();
  const host=document.createElement('div');host.style.cssText='position:fixed;inset:0;width:320px;height:240px';document.body.append(host);
  const warnings:string[]=[],authority={generation:'owned-effects',assertCurrent(){}};
  const world:any=new BrowserWorld(host,{captureAssetAuthority:()=>authority,resolveAsset:(address:string)=>{if(address!=='https://owned-image-effects.invalid/source.png')throw Error('Unapproved fixture source');return url;},onPose(){},onInteract(){},onStatus:(message:string,kind:string)=>{if(kind==='warning'||kind==='error')warnings.push(message);}});
  cancelAnimationFrame(world.frame);world.setPresentationEnabled(false);world.setInputEnabled(false);const renderer=world.renderer,gl=renderer.getContext();if(!(gl instanceof WebGL2RenderingContext))throw Error('Actual WebGL2 required');renderer.setPixelRatio(1);renderer.setSize(320,240);renderer.setClearColor(0,1);world.scene.background=new THREE.Color(0);
  const camera=()=>{world.camera.position.set(0,0,5);world.camera.quaternion.identity();world.camera.aspect=320/240;world.camera.updateProjectionMatrix();};
  const ready=async()=>{const deadline=performance.now()+15000;while([...world.objects.values()].some((root:any)=>!root.userData.shadersReady)){if(performance.now()>deadline)throw Error(`Actual Image effects did not prepare: ${warnings.join('; ')}`);await new Promise(resolve=>setTimeout(resolve,10));}};
  const find=(id:string)=>{let mesh:any;world.objects.get(id).traverse((node:any)=>{if(node instanceof THREE.Mesh)mesh=node;});return mesh;};
  const pixel=(x:number,y:number)=>{const p=new THREE.Vector3(x,y,0).project(world.camera),v=new Uint8Array(4);gl.readPixels(Math.floor((p.x*.5+.5)*320),Math.floor((p.y*.5+.5)*240),1,1,gl.RGBA,gl.UNSIGNED_BYTE,v);return [...v];};
  const render=()=>{camera();renderer.render(world.scene,world.camera);if(gl.getError()!==gl.NO_ERROR)throw Error('Actual Image effects GL error');};
  const base={type:'Image',imageURL:'https://owned-image-effects.invalid/source.png',dimensions:{x:2,y:2,z:.01},emissive:true,sampler:{filter:'point'}};
  try{
   world.upsertEntities([{...base,id:'fit',position:{x:-1.2,y:0,z:0}},{...base,id:'stretch',position:{x:1.2,y:0,z:0},keepAspectRatio:false}]);await ready();render();
   const aspect={fitScale:find('fit').scale.toArray(),stretchScale:find('stretch').scale.toArray(),outsideFit:pixel(-1.2,.75),insideStretch:pixel(1.5,.75)};
   const old=find('fit').material.map,oldSource=old.source,sourceVersion=oldSource.version;
   world.upsertEntities([{...base,id:'fit',position:{x:-1.2,y:0,z:0},subImage:{x:8,y:0,width:8,height:8}},{...base,id:'stretch',position:{x:1.2,y:0,z:0},subImage:{x:16,y:0,width:16,height:8},sampler:{filter:'point',wrapModeU:'repeat'},keepAspectRatio:false}]);await ready();render();
   const crop={actual:pixel(-1.2,0),repeat:pixel(.6,0),cropScale:find('fit').scale.toArray()},repeat=find('stretch').material.map;
   world.upsertEntities([{...base,id:'stretch',position:{x:1.2,y:0,z:0},subImage:{x:16,y:0,width:16,height:8},sampler:{filter:'point',wrapModeU:'clamp'},keepAspectRatio:false}]);await ready();render();
   const clamp= pixel(.6,0),after=find('stretch').material.map;
   const ownership={sameSource:oldSource===repeat.source&&oldSource===after.source,distinctTextures:repeat!==after,sourceVersionUnchanged:oldSource.version===sourceVersion,repeatSampler:repeat.wrapS,clampSampler:after.wrapS};
   world.removeEntities(['fit','stretch']);return{aspect,crop,clamp,ownership,rootsRemaining:world.objects.size,pulseOwners:world.imagePulseOwners.size,warnings};
  }finally{world.dispose();host.remove();}
 });
 await info.attach('native-image-effects',{contentType:'application/json',body:JSON.stringify({browser:page.context().browser()?.version(),report,errors})});
 expect(errors).toEqual([]);expect(report.warnings).toEqual([]);expect(report.aspect.fitScale).toEqual([2,1,.01]);expect(report.aspect.stretchScale).toEqual([2,2,.01]);expect(report.aspect.outsideFit).toEqual([0,0,0,255]);expect(report.aspect.insideStretch).toEqual([0,255,0,255]);expect(report.crop.cropScale).toEqual([2,1,.01]);expect(report.crop.actual).toEqual([0,255,0,255]);expect(report.crop.repeat).toEqual([255,0,0,255]);expect(report.clamp).toEqual([0,255,0,255]);expect(report.ownership).toEqual({sameSource:true,distinctTextures:true,sourceVersionUnchanged:true,repeatSampler:1000,clampSampler:1001});expect(report.rootsRemaining).toBe(0);expect(report.pulseOwners).toBe(0);
});
test('actual World pulse samples native creation clock, pauses presentation and releases ownership after removal',async({page},info)=>{
 await page.goto('/');const report=await page.evaluate(async()=>{
  const module='/tests/native-image-effects-fixture.ts';const{THREE,BrowserWorld}=await import(/* @vite-ignore */module);const source=document.createElement('canvas');source.width=source.height=8;const ctx=source.getContext('2d')!;ctx.fillStyle='white';ctx.fillRect(0,0,8,8);const url=source.toDataURL();
  const host=document.createElement('div');host.style.cssText='position:fixed;inset:0;width:160px;height:120px';document.body.append(host);let approved=true;const warnings:string[]=[];
  const world:any=new BrowserWorld(host,{captureAssetAuthority:()=>({generation:'pulse-effects',assertCurrent(){if(!approved)throw new DOMException('Revoked pulse owner','AbortError');}}),resolveAsset:(address:string)=>{if(address!=='https://owned-image-effects.invalid/pulse.png')throw Error('Unapproved pulse source');return url;},onPose(){},onInteract(){},onStatus:(message:string,kind:string)=>{if(kind==='warning'||kind==='error')warnings.push(message);}});
  cancelAnimationFrame(world.frame);world.setInputEnabled(false);world.setPresentationEnabled(false);const renderer=world.renderer,gl=renderer.getContext();if(!(gl instanceof WebGL2RenderingContext))throw Error('Actual WebGL2 required');renderer.setPixelRatio(1);renderer.setSize(160,120);renderer.setClearColor(0,1);world.scene.background=new THREE.Color(0);
  const realNow=Date.now;let now=1000;Date.now=()=>now;let material:any;
  const draw=(milliseconds:number)=>{now=milliseconds;world.animate(performance.now());cancelAnimationFrame(world.frame);world.camera.position.set(0,0,3);world.camera.quaternion.identity();world.camera.aspect=160/120;world.camera.updateProjectionMatrix();renderer.render(world.scene,world.camera);if(gl.getError()!==gl.NO_ERROR)throw Error('Actual pulse rendering failed');const rgba=new Uint8Array(4);gl.readPixels(80,60,1,1,gl.RGBA,gl.UNSIGNED_BYTE,rgba);return[...rgba];};
  try{
   world.upsertEntities([{id:'pulse',type:'Image',imageURL:'https://owned-image-effects.invalid/pulse.png',emissive:true,dimensions:{x:1,y:1,z:.01},color:{red:128,green:128,blue:128},created:1000000,pulse:{period:4,colorMode:'in',alphaMode:'none'}}]);const deadline=performance.now()+15000;while(!world.objects.get('pulse')?.userData.shadersReady){if(performance.now()>deadline)throw Error('Actual pulse Image preparation failed');await new Promise(resolve=>setTimeout(resolve,10));}
   world.objects.get('pulse').traverse((node:any)=>{if(node instanceof THREE.Mesh)material=node.material;});const versions=[material.version,material.map.version,material.map.source.version];world.setPresentationEnabled(true);const peak=draw(1000),half=draw(2000),trough=draw(3000);world.setPresentationEnabled(false);const paused=draw(1000);world.setPresentationEnabled(true);const resumed=draw(1000);const stableVersions=versions.every((value,index)=>value===[material.version,material.map.version,material.map.source.version][index]);
   let disposed=0;material.map.addEventListener('dispose',()=>disposed++);world.removeEntities(['pulse']);approved=false;world.animate(performance.now());cancelAnimationFrame(world.frame);return{peak,half,trough,paused,resumed,stableVersions,disposed,ownersRemaining:world.imagePulseOwners.size,rootsRemaining:world.objects.size,warnings};
  }finally{Date.now=realNow;world.dispose();host.remove();}
 });await info.attach('native-image-pulse',{contentType:'application/json',body:JSON.stringify({browser:page.context().browser()?.version(),report})});
 expect(report.warnings).toEqual([]);expect(report.peak).toEqual([128,128,128,255]);expect(report.half).toEqual([64,64,64,255]);expect(report.trough).toEqual([0,0,0,255]);expect(report.paused).toEqual(report.trough);expect(report.resumed).toEqual(report.peak);expect(report.stableVersions).toBe(true);expect(report.disposed).toBe(1);expect(report.ownersRemaining).toBe(0);expect(report.rootsRemaining).toBe(0);
});
test('actual approved native KTX v2 original dimensions control crop/aspect without mutating orientation or Source',async({page},info)=>{
 // Exact bounded GPUKTX payload, 8x4 decoded pixels, original16x4. Two DXT1
 // blocks independently author solid red/green; no framebuffer/native oracle reuse.
 const data=new Uint8Array(64+60+4+16),view=new DataView(data.buffer);data.set([0xab,0x4b,0x54,0x58,0x20,0x31,0x31,0xbb,13,10,26,10]);[0x04030201,0,1,0,0x8c4c,0x1907,8,4,0,0,1,1,60].forEach((n,i)=>view.setUint32(12+4*i,n,true));view.setUint32(64,53,true);data.set(new TextEncoder().encode('hifi.gpu\0'),68);data[77]=2;view.setUint32(106,1,true);view.setInt32(111,16,true);view.setInt32(115,4,true);view.setUint32(124,16,true);for(const[at,value]of [[128,0xf800],[130,0xf800],[136,0x07e0],[138,0x07e0]])view.setUint16(at,value,true);
 await page.route('**/api/assets/owned-image-ktx?*',route=>{const address=new URL(route.request().url()).searchParams.get('url');if(address==='https://owned-image-effects.invalid/native.texmeta.json')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({version:1,compressed:{COMPRESSED_SRGB_S3TC_DXT1_EXT:'native.ktx'},original:'unsupported-original.png'})});if(address==='https://owned-image-effects.invalid/native.ktx')return route.fulfill({status:200,contentType:'application/octet-stream',body:Buffer.from(data)});return route.fulfill({status:403,body:'Unapproved fixture asset'});});
 await page.goto('/');const report=await page.evaluate(async()=>{
  const module='/tests/native-image-effects-fixture.ts';const{THREE,BrowserWorld,NativeCompressedColorCache}=await import(/* @vite-ignore */module);const host=document.createElement('div');host.style.cssText='position:fixed;inset:0;width:160px;height:120px';document.body.append(host);
  let approved=true,cache:any;const warnings:string[]=[],asset=(address:string)=>`${location.origin}/api/assets/owned-image-ktx?url=${encodeURIComponent(address)}`;
  const world:any=new BrowserWorld(host,{captureAssetAuthority:()=>({generation:'ktx-effects',assertCurrent(){if(!approved)throw new DOMException('Revoked fixture authority','AbortError');}}),resolveAsset:asset,compressedColors:(capabilities:any)=>cache??=new NativeCompressedColorCache({origin:location.origin,sessionId:'owned-image-ktx',authority:()=>approved?'permission1':null,resolveAsset:asset,capabilities}),onPose(){},onInteract(){},onStatus:(message:string,kind:string)=>{if(kind==='warning'||kind==='error')warnings.push(message);}});
  cancelAnimationFrame(world.frame);world.setPresentationEnabled(false);world.setInputEnabled(false);const renderer=world.renderer,gl=renderer.getContext();if(!(gl instanceof WebGL2RenderingContext))throw Error('Actual WebGL2 required');if(!renderer.extensions.has('WEBGL_compressed_texture_s3tc')||!renderer.extensions.has('WEBGL_compressed_texture_s3tc_srgb'))throw Error('Actual validated native S3TC color capability required');renderer.setPixelRatio(1);renderer.setSize(160,120);world.scene.background=new THREE.Color(0);
  try{
   world.upsertEntities([{id:'compressed-crop',type:'Image',imageURL:'https://owned-image-effects.invalid/native.texmeta.json',emissive:true,dimensions:{x:2,y:2,z:.01},subImage:{x:8,y:0,width:8,height:4},sampler:{filter:'point'}}]);const deadline=performance.now()+15000;while(!world.objects.get('compressed-crop')?.userData.shadersReady){if(performance.now()>deadline)throw Error(`Actual native KTX Image did not prepare: ${warnings.join('; ')}`);await new Promise(resolve=>setTimeout(resolve,10));}
   let mesh:any;world.objects.get('compressed-crop').traverse((node:any)=>{if(node instanceof THREE.Mesh)mesh=node;});const map=mesh.material.map,matrix=map.matrix.elements.slice(),source=map.source,versions=[map.version,map.source.version];if(!(map instanceof THREE.CompressedTexture))throw Error('Fixture must use actual approved native KTX rather than original fallback');world.camera.position.set(0,0,3);world.camera.quaternion.identity();world.camera.aspect=160/120;world.camera.updateProjectionMatrix();renderer.render(world.scene,world.camera);if(gl.getError()!==gl.NO_ERROR)throw Error('Actual native KTX Image rendering failed');const pixel=new Uint8Array(4);gl.readPixels(80,60,1,1,gl.RGBA,gl.UNSIGNED_BYTE,pixel);let disposed=0;map.addEventListener('dispose',()=>disposed++);const scale=mesh.scale.toArray(),uv=Array.from(mesh.geometry.getAttribute('uv').array);world.removeEntities(['compressed-crop']);return{pixel:[...pixel],scale,uv,compressed:true,orientationMatrix:matrix,sourceUnchanged:map.source===source,versionsUnchanged:map.version===versions[0]&&map.source.version===versions[1],disposed,rootsRemaining:world.objects.size,warnings};
  }finally{approved=false;world.dispose();cache?.dispose();host.remove();}
 });await info.attach('native-ktx-image-effects',{contentType:'application/json',body:JSON.stringify({browser:page.context().browser()?.version(),report})});
 expect(report.warnings).toEqual([]);expect(report.pixel).toEqual([0,255,0,255]);expect(report.scale).toEqual([2,.5,.01]);expect(report.uv).toEqual([.5625,.875,.9375,.875,.5625,.125,.9375,.125]);expect(report.orientationMatrix).toEqual([1,0,0,0,-1,0,0,1,1]);expect(report.sourceUnchanged).toBe(true);expect(report.versionsUnchanged).toBe(true);expect(report.disposed).toBe(1);expect(report.rootsRemaining).toBe(0);
});
