// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import {imageLightingCohort,assertLitImagePixels} from './integration/native-image-lit.mjs';
import {weightedAreaImagePixels} from './integration/native-image-pixels.mjs';
function source(){const rgba=new Uint8Array(32*32*4);for(let y=0;y<32;y++)for(let x=0;x<32;x++){const n=(y*32+x)*4;rgba.set([20+x*5,30+y*4,40+(x+y)%5*10,255],n);}return weightedAreaImagePixels({rgba,width:32,height:32,grid:32});}
function illuminate(sample,factor){return {...sample,rgb:sample.rgb.map(value=>value*factor),mask:sample.mask.slice()};}
test('the explicit lit cohort cannot silently fall back to an emissive or arbitrary option',()=>{assert.equal(imageLightingCohort().emissive,true);assert.equal(imageLightingCohort('unlit').emissive,true);assert.equal(imageLightingCohort('lit').emissive,false);assert(Object.isFrozen(imageLightingCohort('lit')));for(const value of ['',true,'false','LIT',{},null])assert.throws(()=>imageLightingCohort(value));});
test('real incident light may alter source colors but matched actual-engine lit pixels retain source detail',()=>{const original=source(),native=illuminate(original,.4),browser=illuminate(original,.41),result=assertLitImagePixels(native,browser,original,original);assert(result.nativeDetail.rgbMAE>10);assert(result.crossEngine.rgbMAE<10);assert(result.nativeDetail.correlation>=.9);});
test('unlit browser output cannot pass against a genuinely lit darker native Image',()=>{const original=source();assert.throws(()=>assertLitImagePixels(illuminate(original,.4),original,original,original),/lighting colors/);});
test('flat, UV-reversed and mismatched masks remain strict failures rather than oracle calibration',()=>{const original=source(),native=illuminate(original,.4),flat={...native,rgb:native.rgb.map((_,i)=>[30,40,25][i%3])};assert.throws(()=>assertLitImagePixels(flat,flat,original,original),/detail/);const reversed={...native,rgb:[]};for(let y=0;y<32;y++)for(let x=0;x<32;x++)reversed.rgb.push(...native.rgb.slice((y*32+31-x)*3,(y*32+32-x)*3));assert.throws(()=>assertLitImagePixels(reversed,reversed,original,original),/detail/);const holes={...native,mask:native.mask.map((v,i)=>i<64?1-v:v)};assert.throws(()=>assertLitImagePixels(native,holes,original,original),/holes/);});
