// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import * as THREE from 'three';
import {FBXLoader} from 'three/addons/loaders/FBXLoader.js';
import {clone} from 'three/addons/utils/SkeletonUtils.js';
import {ownedGraphSkeletons,disposeOwnedSkeleton} from '../src/owned-skeletons';
import {ModelResources} from '../src/model-resources';
import {replacementMaterialFbx} from './fixtures/replacement-material-fbx';
const world=readFileSync(new URL('../src/world.ts',import.meta.url),'utf8');
const body=world.slice(world.indexOf('function disposeObject('),world.indexOf('\n}\n',world.indexOf('function disposeObject('))+3);
// Execute the actual candidate cleanup binding, not a mirrored cleanup algorithm.
const dispose=new Function('THREE','ownedGraphSkeletons','disposeOwnedSkeleton','isOwnedUploadBitmap',stripTypeScriptTypes(body)+'; return disposeObject;')(THREE,ownedGraphSkeletons,disposeOwnedSkeleton,()=>false) as(root:THREE.Object3D)=>void;
function parsed(){const root=new FBXLoader().parse(replacementMaterialFbx({skin:true,withoutOriginalTextures:true}),'');let mesh:THREE.SkinnedMesh|undefined;root.traverse(node=>{if(node instanceof THREE.SkinnedMesh)mesh=node;});assert(mesh);mesh.skeleton.computeBoneTexture();return{root,mesh,skeleton:mesh.skeleton};}
function watch(skeleton:THREE.Skeleton){let calls=0;assert(skeleton.boneTexture);skeleton.boneTexture.addEventListener('dispose',()=>calls++);return()=>calls;}
test('actual fresh FBX binding owns its private bone texture; candidate whole graph teardown releases it once',()=>{const {root,skeleton}=parsed(),calls=watch(skeleton);assert.equal(ownedGraphSkeletons(root).size,1);dispose(root);assert.equal(calls(),1);assert.equal(skeleton.boneTexture,null);dispose(root);assert.equal(calls(),1);});
test('SkeletonUtils cloned graph has fresh skeleton and bone texture; disposing clone preserves private canonical template',()=>{const original=parsed(),copied=clone(original.root);let mesh:THREE.SkinnedMesh|undefined;copied.traverse(node=>{if(node instanceof THREE.SkinnedMesh)mesh=node;});assert(mesh);assert.notEqual(mesh.skeleton,original.skeleton);assert.equal(mesh.skeleton.boneTexture,null);mesh.skeleton.computeBoneTexture();const own=watch(mesh.skeleton),other=watch(original.skeleton);dispose(copied);assert.equal(own(),1);assert.equal(other(),0);assert(original.skeleton.boneTexture);dispose(original.root);assert.equal(other(),1);});
test('one parse graph with two meshes sharing the same skeleton disposes exactly one bone texture',()=>{const{root,mesh,skeleton}=parsed(),copy=new THREE.SkinnedMesh(mesh.geometry,mesh.material);copy.bind(skeleton,mesh.bindMatrix);root.add(copy);const calls=watch(skeleton);assert.equal(ownedGraphSkeletons(root).size,1);dispose(root);assert.equal(calls(),1);});
test('ModelResources keeps retained skeleton while replacing material then releases detached captured skeleton once',()=>{const{root,mesh,skeleton}=parsed(),calls=watch(skeleton),resources=new ModelResources();resources.capture(root);const old=mesh.material;mesh.material=new THREE.MeshPhongMaterial();resources.capture(root);resources.releaseKeeping(root);assert.equal(calls(),0);assert(skeleton.boneTexture);root.remove(mesh);resources.releaseKeeping(root);assert.equal(calls(),1);resources.releaseKeeping();assert.equal(calls(),1);assert(old);});
test('borrowed skeleton whose bones belong to another prefab root is refused and remains alive',()=>{const original=parsed(),borrowed=new THREE.Group(),mesh=new THREE.SkinnedMesh(new THREE.BufferGeometry(),new THREE.MeshPhongMaterial());mesh.bind(original.skeleton);borrowed.add(mesh);const calls=watch(original.skeleton);assert.equal(ownedGraphSkeletons(borrowed).size,0);dispose(borrowed);assert.equal(calls(),0);dispose(original.root);assert.equal(calls(),1);});
test('foreign skeleton disposal callback and accessor are not executed or treated as ownership',()=>{const{root,mesh,skeleton}=parsed();let called=0;Object.defineProperty(skeleton,'dispose',{get(){called++;throw Error('foreign getter');}});assert.equal(ownedGraphSkeletons(root).size,0);assert.equal(called,0);Object.defineProperty(mesh,'skeleton',{get(){called++;throw Error('foreign mesh getter');},configurable:true});assert.equal(ownedGraphSkeletons(root).size,0);assert.equal(called,0);});
test('bone texture with externally borrowed matrix data is excluded without disposing that texture',()=>{const{root,skeleton}=parsed();const borrowed=new THREE.DataTexture(new Float32Array(16),1,1);let calls=0;borrowed.addEventListener('dispose',()=>calls++);skeleton.boneTexture!.dispose();skeleton.boneTexture=borrowed;assert.equal(ownedGraphSkeletons(root).size,0);dispose(root);assert.equal(calls,0);borrowed.dispose();assert.equal(calls,1);});
test('whole graph cleanup preserves original dispose listener error rather than hiding it',()=>{const{root,skeleton}=parsed(),failure=Error('original listener');skeleton.boneTexture!.addEventListener('dispose',()=>{throw failure;});assert.throws(()=>dispose(root),error=>error===failure);});

test('a delayed ModelResources claim refuses newly substituted borrowed texture data',()=>{const{root,skeleton}=parsed(),resources=new ModelResources();resources.capture(root);const original=skeleton.boneTexture!,borrowed=new THREE.DataTexture(new Float32Array(16),1,1);let calls=0;borrowed.addEventListener('dispose',()=>calls++);skeleton.boneTexture=borrowed;resources.releaseKeeping();assert.equal(calls,0);original.dispose();borrowed.dispose();});
test('delayed cleanup refuses replaced bone ownership and does not execute a newly installed foreign dispose getter',()=>{const{root,skeleton}=parsed(),resources=new ModelResources(),calls=watch(skeleton);resources.capture(root);skeleton.bones=[new THREE.Bone()];resources.releaseKeeping();assert.equal(calls(),0);const other=parsed(),owner=new ModelResources();owner.capture(other.root);let getters=0;Object.defineProperty(other.skeleton,'dispose',{get(){getters++;throw Error('foreign');}});owner.releaseKeeping();assert.equal(getters,0);});
