// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Genuine binary FBX/Three structural ownership proof; no browser image claim.
import test from 'node:test';import assert from 'node:assert/strict';
import {DirectionalLight,Group,Mesh,Object3D,PointLight,WebGLRenderTarget} from 'three';
import {FBXLoader} from 'three/addons/loaders/FBXLoader.js';
import {replacementMaterialFbx} from './fixtures/parsed-template-fbx';
import {cloneParsedFbxTemplate,disposeParsedFbxGraph,inspectParsedFbxTemplate,ParsedFbxTemplateRefusal,ParsedFbxTemplates} from '../src/parsed-fbx-template';
const bytes=(options:Parameters<typeof replacementMaterialFbx>[0]={})=>replacementMaterialFbx({directionalLight:'detached',withoutOriginalTextures:true,vertexColors:true,...options});
const parse=(buffer=bytes())=>new FBXLoader().parse(buffer,'');
function light(root:Object3D){let result:DirectionalLight|undefined;root.traverse(n=>{if(n instanceof DirectionalLight)result??=n;});assert(result);return result;}
function mesh(root:Object3D){let result:Mesh|undefined;root.traverse(n=>{if(n instanceof Mesh)result??=n;});assert(result);return result;}
const tick=()=>new Promise<void>(resolve=>setImmediate(resolve));
test('authentic binary32/64 DirectionalLight is admitted with unchanged authored geometry, color, intensity and transform',()=>{
 for(const wide of [false,true]){const input=bytes({wide}),original=Uint8Array.from(new Uint8Array(input)),root=parse(input),without=parse(replacementMaterialFbx({wide,withoutOriginalTextures:true,vertexColors:true}));try{const l=light(root);assert.equal(Object.getPrototypeOf(l),DirectionalLight.prototype);assert.equal(l.intensity,.5);assert.deepEqual(l.position.toArray(),[-2,4,4]);assert.equal(l.castShadow,false);assert.equal(l.target.parent,null);assert.equal(l.shadow.map,null);assert.equal(l.shadow.mapPass,null);assert(inspectParsedFbxTemplate(root).bytes>inspectParsedFbxTemplate(without).bytes);for(const key of ['position','normal','uv','color'])assert.deepEqual(mesh(root).geometry.attributes[key].array,mesh(without).geometry.attributes[key].array);assert.deepEqual(mesh(root).geometry.groups,mesh(without).geometry.groups);assert.deepEqual(new Uint8Array(input),original);}finally{disposeParsedFbxGraph(root);disposeParsedFbxGraph(without);}}
});
test('each clone preserves exact light and shadow state with private target/camera/color and independent mesh resources',()=>{
 const root=parse(),a=cloneParsedFbxTemplate(root),b=cloneParsedFbxTemplate(root);try{const source=light(root),x=light(a),y=light(b);for(const item of [x,y]){assert.deepEqual(item.color,source.color);assert.equal(item.intensity,source.intensity);assert.deepEqual(item.matrix.elements,source.matrix.elements);assert.deepEqual(item.target.position.toArray(),source.target.position.toArray());assert.deepEqual(item.shadow.camera.projectionMatrix.elements,source.shadow.camera.projectionMatrix.elements);assert.equal(item.target.parent,null);assert.equal(item.shadow.map,null);}assert.notEqual(x.target,y.target);assert.notEqual(x.color,y.color);assert.notEqual(x.shadow,y.shadow);assert.notEqual(x.shadow.camera,y.shadow.camera);assert.notEqual(mesh(a).geometry,mesh(b).geometry);assert.notEqual(mesh(a).material,mesh(b).material);x.target.position.y=9;x.color.g=.25;x.shadow.camera.position.y=7;assert.notEqual(y.target.position.y,9);assert.notEqual(y.color.g,.25);assert.notEqual(y.shadow.camera.position.y,7);assert.notEqual(source.target.position.y,9);}finally{[a,b,root].forEach(disposeParsedFbxGraph);}
});
test('actual FBX LookAt graph linkage, enabled shadows and PointLight still refuse rather than changing their semantics',()=>{
 for(const mode of ['look-at','shadow','point']as const){const root=parse(bytes({directionalLight:mode}));try{if(mode==='look-at')assert.notEqual(light(root).target.parent,null);if(mode==='shadow')assert.equal(light(root).castShadow,true);if(mode==='point')assert(root.children.some(n=>n instanceof PointLight));assert.throws(()=>inspectParsedFbxTemplate(root),ParsedFbxTemplateRefusal);}finally{disposeParsedFbxGraph(root);}}
});
test('negative and zero finite intensity and authored color are copied exactly; nonfinite values refuse',()=>{
 for(const intensity of [-2,0,.5]){const root=parse();light(root).intensity=intensity;const copy=cloneParsedFbxTemplate(root);try{assert.equal(light(copy).intensity,intensity);assert.deepEqual(light(copy).color,light(root).color);}finally{disposeParsedFbxGraph(copy);disposeParsedFbxGraph(root);}}
 for(const field of ['intensity','color']as const){const root=parse();try{if(field==='intensity')light(root).intensity=NaN;else light(root).color.r=Infinity;assert.throws(()=>inspectParsedFbxTemplate(root),ParsedFbxTemplateRefusal);}finally{disposeParsedFbxGraph(root);}}
});
test('target/shadow/camera foreign callbacks and prototypes refuse without calling their methods',()=>{
 let calls=0;const changes:((n:DirectionalLight)=>void)[]=[n=>n.copy=()=>{calls++;return n;},n=>n.target.clone=()=>{calls++;return n.target;},n=>n.target.copy=()=>{calls++;return n.target;},n=>n.shadow.clone=()=>{calls++;return n.shadow;},n=>n.shadow.camera.clone=()=>{calls++;return n.shadow.camera;},n=>n.shadow.camera.copy=()=>{calls++;return n.shadow.camera;},n=>Object.setPrototypeOf(n.target,Group.prototype),n=>n.target.onBeforeRender=()=>calls++];for(const change of changes){const root=parse();try{change(light(root));assert.throws(()=>inspectParsedFbxTemplate(root),ParsedFbxTemplateRefusal);assert.equal(calls,0);}finally{disposeParsedFbxGraph(root);}}assert.equal(calls,0);
});
test('nested target/shadow/camera accessors refuse without reading getters or invoking setters',()=>{
 let calls=0;for(const place of ['target-position','shadow-camera','camera-near','target']as const){const root=parse(),n=light(root);let object:object,key:string;if(place==='target-position'){object=n.target.position;key='x';}else if(place==='shadow-camera'){object=n.shadow;key='camera';}else if(place==='camera-near'){object=n.shadow.camera;key='near';}else{object=n;key='target';}const before=Object.getOwnPropertyDescriptor(object,key)!;try{Object.defineProperty(object,key,{enumerable:before.enumerable,configurable:true,get(){calls++;throw Error('Forbidden getter');},set(){calls++;}});assert.throws(()=>inspectParsedFbxTemplate(root),ParsedFbxTemplateRefusal);assert.equal(calls,0);}finally{Object.defineProperty(object,key,before);disposeParsedFbxGraph(root);}}assert.equal(calls,0);
});
test('unexpected detached target state, target children, attached targets and shared private descriptors refuse',()=>{
 const changes:((n:DirectionalLight,root:Object3D)=>void)[]=[n=>n.target.position.x=1,n=>n.target.userData.custom=true,n=>n.target.add(new Object3D()),(n,root)=>root.add(n.target),n=>n.shadow.camera.near=1,n=>n.shadow.radius=2,(n,root)=>{const other=new DirectionalLight();other.target=n.target;root.add(other);},(n,root)=>{const other=new DirectionalLight();other.shadow=n.shadow;root.add(other);}];for(const change of changes){const root=parse();try{change(light(root),root);assert.throws(()=>inspectParsedFbxTemplate(root),ParsedFbxTemplateRefusal);}finally{disposeParsedFbxGraph(root);}}
});
test('allocated shadow resources are refused, while each independently published clone disposes only its own later allocations once',()=>{
 const root=parse(),a=cloneParsedFbxTemplate(root),b=cloneParsedFbxTemplate(root),x=light(a),y=light(b),source=light(root),map=new WebGLRenderTarget(2,2),pass=new WebGLRenderTarget(2,2);let disposed=0,passDisposed=0,xd=0,yd=0,sd=0;map.addEventListener('dispose',()=>disposed++);pass.addEventListener('dispose',()=>passDisposed++);x.addEventListener('dispose',()=>xd++);y.addEventListener('dispose',()=>yd++);source.addEventListener('dispose',()=>sd++);try{x.shadow.map=map;x.shadow.mapPass=pass;assert.throws(()=>inspectParsedFbxTemplate(a),ParsedFbxTemplateRefusal);disposeParsedFbxGraph(a);disposeParsedFbxGraph(a);assert.equal(disposed,1);assert.equal(passDisposed,1);assert.equal(xd,1);assert.equal(yd,0);assert.equal(sd,0);disposeParsedFbxGraph(b);assert.equal(yd,1);assert.equal(sd,0);disposeParsedFbxGraph(root);assert.equal(sd,1);}finally{[a,b,root].forEach(disposeParsedFbxGraph);}
});
test('throwing private dispose listener does not prevent the independently owned shadow maps from being released',()=>{
 const root=parse(),n=light(root),map=new WebGLRenderTarget(2,2);let released=0;map.addEventListener('dispose',()=>released++);n.shadow.map=map;n.addEventListener('dispose',()=>{throw Error('Owned listener failed');});disposeParsedFbxGraph(root);assert.equal(released,1);disposeParsedFbxGraph(root);assert.equal(released,1);
});
test('source math synchronization closures are not copied or executed by private target/camera cloning',()=>{
 const root=parse(),n=light(root);let invoked=0;(n.target.quaternion as unknown as {_onChangeCallback:()=>void})._onChangeCallback=()=>invoked++;(n.shadow.camera.rotation as unknown as {_onChangeCallback:()=>void})._onChangeCallback=()=>invoked++;const copy=cloneParsedFbxTemplate(root);try{assert.equal(invoked,0);light(copy).target.quaternion.x=.1;light(copy).shadow.camera.rotation.x=.1;assert.equal(invoked,0);}finally{disposeParsedFbxGraph(copy);disposeParsedFbxGraph(root);}
});
test('joined current consumers and a cache hit use one actual binary parse and private descriptors with unchanged bytes',async()=>{
 const world=new AbortController(),cache=new ParsedFbxTemplates(world.signal),input=bytes(),original=Uint8Array.from(new Uint8Array(input)),roots:Object3D[]=[];let parses=0;const producer=async(_signal:AbortSignal,onParsed:(n:Object3D)=>void)=>{parses++;const root=parse(input);onParsed(root);return root;};try{roots.push(...await Promise.all([cache.get(input,'approved/base',()=>world.signal.throwIfAborted(),producer),cache.get(input,'approved/base',()=>world.signal.throwIfAborted(),producer)]));roots.push(await cache.get(input,'approved/base',()=>world.signal.throwIfAborted(),producer));assert.equal(parses,1);assert.equal(cache.statistics.cloned,3);assert.equal(cache.statistics.admissionEvidence.producerFailures,0);assert.notEqual(light(roots[0]).target,light(roots[1]).target);assert.notEqual(light(roots[1]).shadow.camera,light(roots[2]).shadow.camera);assert.deepEqual(new Uint8Array(input),original);}finally{roots.forEach(disposeParsedFbxGraph);cache.dispose();assert.equal(cache.statistics.bytes,0);assert.equal(cache.statistics.readers,0);}
});
test('revocation before staged-light publication preserves original authority guard and disposes the producer without a late clone',async()=>{
 const world=new AbortController(),cache=new ParsedFbxTemplates(world.signal),input=bytes();let publish!:(n:Object3D)=>void,finish!:(n:Object3D)=>void,current=true,staged=0;const request=cache.get(input,'approved/base',()=>{if(!current)throw new DOMException('Ended','AbortError');},async(_signal,onParsed)=>{publish=onParsed;return new Promise(resolve=>finish=resolve);},undefined,()=>staged++),rejected=assert.rejects(request,{name:'AbortError'});await tick();const root=parse(input);current=false;assert.throws(()=>publish(root),{name:'AbortError'});world.abort();await rejected;finish(root);await tick();assert.equal(staged,0);assert.equal(cache.statistics.ready,0);assert.equal(cache.statistics.readers,0);
});
test('cancelling one staged-light reader disposes its private light while a joined reader retains the producer and its own clone',async()=>{
 const cache=new ParsedFbxTemplates(new AbortController().signal),reader=new AbortController(),input=bytes();let publish!:(n:Object3D)=>void,finish!:(n:Object3D)=>void,disposed=0,sourceDisposed=0;const first=cache.get(input,'approved/base',()=>{},async(_signal,onParsed)=>{publish=onParsed;return new Promise(resolve=>finish=resolve);},reader.signal,n=>light(n).addEventListener('dispose',()=>disposed++)),rejected=assert.rejects(first,{name:'AbortError'}),second=cache.get(input,'approved/base',()=>{},async()=>{throw Error('Joined producer must not run');});await tick();const original=parse(input);light(original).addEventListener('dispose',()=>sourceDisposed++);publish(original);reader.abort();await rejected;assert.equal(disposed,1);assert.equal(sourceDisposed,0);finish(original);const survivor=await second;assert.equal(sourceDisposed,0);disposeParsedFbxGraph(survivor);cache.dispose();assert.equal(sourceDisposed,1);assert.equal(disposed,1);
});
test('cached private light descriptors are rechecked before cloning without executing post-inspection foreign methods',()=>{
 let called=0;const changes:((n:DirectionalLight)=>void)[]=[n=>n.target.clone=()=>{called++;return n.target;},n=>n.shadow.camera.clone=()=>{called++;return n.shadow.camera;},n=>n.shadow.clone=()=>{called++;return n.shadow;},n=>n.clone=()=>{called++;return n;},n=>n.userData.toJSON=()=>{called++;return {};},n=>n.target.position.x=1];for(const change of changes){const root=parse();try{const token=inspectParsedFbxTemplate(root);change(light(root));assert.throws(()=>cloneParsedFbxTemplate(root,token),ParsedFbxTemplateRefusal);assert.equal(called,0);}finally{disposeParsedFbxGraph(root);}}assert.equal(called,0);
});
test('detached target, shadow and camera descriptors are charged per private light in the existing inspection/cache byte budget',async()=>{
 const root=parse(),n=light(root),one=inspectParsedFbxTemplate(root).bytes;root.remove(n);const base=inspectParsedFbxTemplate(root).bytes;root.add(n);const secondRoot=parse(),other=light(secondRoot);other.removeFromParent();root.add(other);try{const two=inspectParsedFbxTemplate(root).bytes;assert(one-base>8192,'Private target/shadow/camera descriptor storage must be charged');assert.equal(two-one,one-base);const cache=new ParsedFbxTemplates(new AbortController().signal),input=bytes(),key='approved/base';try{const owner=await cache.get(input,key,()=>{},async()=>parse(input));assert.equal(cache.statistics.bytes,inspectParsedFbxTemplate(owner).bytes+input.byteLength+key.length*2);disposeParsedFbxGraph(owner);}finally{cache.dispose();assert.equal(cache.statistics.bytes,0);}}finally{disposeParsedFbxGraph(root);disposeParsedFbxGraph(secondRoot);}
});
test('existing 32-ready eviction limit releases only the evicted canonical light and dispose retires all other canonical lights once',async()=>{
 const cache=new ParsedFbxTemplates(new AbortController().signal),owners:Object3D[]=[];let canonicalDisposed=0;try{for(let i=0;i<33;i++){const input=bytes();owners.push(await cache.get(input,'approved/base',()=>{},async()=>{const root=parse(input);light(root).addEventListener('dispose',()=>canonicalDisposed++);return root;}));}assert.equal(cache.statistics.ready,32);assert.equal(cache.statistics.evicted,1);assert.equal(canonicalDisposed,1);for(const owner of owners)assert.equal(light(owner).shadow.map,null);owners.forEach(disposeParsedFbxGraph);assert.equal(canonicalDisposed,1);cache.dispose();assert.equal(canonicalDisposed,33);cache.dispose();assert.equal(canonicalDisposed,33);assert.equal(cache.statistics.bytes,0);}finally{owners.forEach(disposeParsedFbxGraph);cache.dispose();}
});
test('late new or replacement light membership is refused before invoking an uninspected clone hook, including an originally light-free graph',()=>{
 let called=0;for(const mode of ['added','replacement','originally-none']as const){const root=mode==='originally-none'?parse(replacementMaterialFbx({withoutOriginalTextures:true})):parse(),token=inspectParsedFbxTemplate(root);const added=new DirectionalLight();added.clone=()=>{called++;throw Error('Uninspected clone must not execute');};if(mode==='replacement')root.remove(light(root));root.add(added);try{assert.throws(()=>cloneParsedFbxTemplate(root,token),ParsedFbxTemplateRefusal);assert.equal(called,0);}finally{disposeParsedFbxGraph(root);}}assert.equal(called,0);
});
test('late child-array accessor/iterator and ancestor constructor changes refuse without invoking foreign code',()=>{
 let called=0;for(const mode of ['children-accessor','children-iterator','constructor']as const){const root=parse(),token=inspectParsedFbxTemplate(root),before=Object.getOwnPropertyDescriptor(root,'children')!;try{if(mode==='children-accessor')Object.defineProperty(root,'children',{configurable:true,enumerable:true,get(){called++;throw Error('No child getter');}});else if(mode==='children-iterator')Object.defineProperty(root.children,Symbol.iterator,{configurable:true,get(){called++;throw Error('No foreign iterator');}});else Object.defineProperty(root,'constructor',{configurable:true,value:function(){called++;}});assert.throws(()=>cloneParsedFbxTemplate(root,token),ParsedFbxTemplateRefusal);assert.equal(called,0);}finally{Object.defineProperty(root,'children',before);delete (root.children as unknown as Record<symbol,unknown>)[Symbol.iterator];delete (root as unknown as {constructor?:unknown}).constructor;disposeParsedFbxGraph(root);}}assert.equal(called,0);
});
test('throwing map listener cannot skip mapPass retirement and repeated cleanup does not redispatch either owned resource',()=>{
 const root=parse(),n=light(root),map=new WebGLRenderTarget(2,2),pass=new WebGLRenderTarget(2,2);let md=0,pd=0;n.shadow.map=map;n.shadow.mapPass=pass;map.addEventListener('dispose',()=>{md++;throw Error('Owned map listener failed');});pass.addEventListener('dispose',()=>pd++);disposeParsedFbxGraph(root);assert.equal(md,1);assert.equal(pd,1);assert.equal(n.shadow.map,null);assert.equal(n.shadow.mapPass,null);disposeParsedFbxGraph(root);assert.equal(md,1);assert.equal(pd,1);
});
test('foreign target dispose method is not invoked; known target retirement still dispatches the ordinary dispose event',()=>{
 const root=parse(),n=light(root),map=new WebGLRenderTarget(2,2);let foreign=0,ordinary=0;map.dispose=()=>foreign++;map.addEventListener('dispose',()=>ordinary++);n.shadow.map=map;disposeParsedFbxGraph(root);assert.equal(foreign,0);assert.equal(ordinary,1);
});
test('unreadable private map descriptors do not execute getters or prevent the independent mapPass retirement',()=>{
 const root=parse(),n=light(root),map=new WebGLRenderTarget(2,2),pass=new WebGLRenderTarget(2,2);let getter=0,passDisposed=0;Object.defineProperty(map,'constructor',{configurable:true,get(){getter++;throw Error('No private map getter');}});pass.addEventListener('dispose',()=>passDisposed++);n.shadow.map=map;n.shadow.mapPass=pass;disposeParsedFbxGraph(root);assert.equal(getter,0);assert.equal(passDisposed,1);delete (map as unknown as {constructor?:unknown}).constructor;map.dispose();
});
