// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Actual BrowserWorld/FBXLoader; I/O and readiness faults are explicit boundaries.
import test from 'node:test';import assert from 'node:assert/strict';
import * as THREE from 'three';
import {BrowserWorld} from '../src/world';
import {WorldImageCache} from '../src/world-image-cache';
import {EmbeddedFbxImages} from '../src/embedded-fbx-images';
import {FstGraphCache} from '../src/fst-graph-cache';
import {replacementMaterialFbx} from './fixtures/parsed-template-fbx';
import {disposeParsedFbxGraph} from '../src/parsed-fbx-template';
const tick=()=>new Promise<void>(resolve=>setImmediate(resolve));
function fixture(buffer=replacementMaterialFbx({withoutOriginalTextures:true,skin:true,vertexColors:true}),enabled=true){
 const world:any=Object.create(BrowserWorld.prototype),abort=new AbortController(),calls:string[]=[],warnings:string[]=[];let generation='first',valid=true;
 Object.assign(world,{abort,disposed:false,options:{resolveAsset:(source:string)=>{calls.push(source);if(!valid)throw new DOMException('revoked','AbortError');return source;},captureAssetAuthority:()=>{const captured=generation;return{generation:captured,assertCurrent(){if(!valid||generation!==captured)throw new DOMException('revoked','AbortError');}};},onStatus:(_message:string,kind:string)=>warnings.push(kind)},parsedTemplatesEnabled:enabled,parsedTemplateCounts:{fallbacks:0},loadManagers:new Set(),embeddedFbxImages:new EmbeddedFbxImages(abort.signal),imageCache:new WorldImageCache({signal:abort.signal}),fstGraphCache:new FstGraphCache(abort.signal),recordLoadPhase(){},zeroLightGuard:false,loadPreparedFbx:async()=>({buffer,phases:{materialBindingsMs:0,decodeMs:0},cacheHit:false})});
 return{world,abort,calls,warnings,revoke:()=>{valid=false;},next:()=>generation='second',close(){abort.abort();world.invalidateModelParses();}};
}
function mesh(root:THREE.Object3D){let value:THREE.Mesh|undefined;root.traverse(node=>{if(node instanceof THREE.Mesh)value=node;});assert(value);return value;}
test('actual World opt-in returns per-reader staged geometry and distinct skeleton/material/buffer state with one canonical parse',async()=>{
 const f=fixture(),staged:THREE.Object3D[]=[];try{const roots=await Promise.all([f.world.loadModel('https://assets.invalid/body.fbx',new Set(),undefined,undefined,(root:THREE.Object3D)=>{root.userData.ownerMapping={scale:2};staged.push(root);}),f.world.loadModel('https://assets.invalid/body.fbx',new Set(),undefined,undefined,(root:THREE.Object3D)=>staged.push(root))]);
 assert.equal(staged.length,2);assert.equal(roots[0],staged[0]);assert.equal(roots[1],staged[1]);assert.notEqual(mesh(roots[0]).geometry,mesh(roots[1]).geometry);assert.notEqual((mesh(roots[0])as THREE.SkinnedMesh).skeleton,(mesh(roots[1])as THREE.SkinnedMesh).skeleton);assert.equal(roots[1].userData.ownerMapping,undefined);assert.equal(f.world.getParsedFbxTemplateStatistics().cache.producers,1);assert.equal(f.world.loadManagers.size,0);roots.forEach(disposeParsedFbxGraph);
 }finally{f.close();}
});
test('actual default-off and AvatarRig/no-geometry-callback branches retain original parser without template admission',async()=>{for(const enabled of [false,true]){const f=fixture(undefined,enabled);try{const root=await f.world.loadModel('https://assets.invalid/body.fbx');assert.equal(f.world.getParsedFbxTemplateStatistics().cache,null);assert(mesh(root)instanceof THREE.SkinnedMesh);disposeParsedFbxGraph(root);}finally{f.close();}}});
test('actual mapped consumers retain different ordered native material/FST metadata with no cross-owner template mutation',async t=>{
 const f=fixture(),seen:THREE.Object3D[]=[];t.mock.method(globalThis,'fetch',async (input:unknown)=>new Response(String(input).endsWith('left.fst')?'filename = body.fbx\nscale = 2\nmaterialMap = [{"all":"red.json"}]':String(input).endsWith('right.fst')?'filename = body.fbx\nscale = 3\nmaterialMap = [{"all":"green.json"}]':JSON.stringify({materials:{name:'mapped',unlit:true,albedo:String(input).endsWith('red.json')?[1,0,0]:[0,1,0]}})));
 try{const [a,b]=await Promise.all(['left','right'].map(name=>f.world.loadModel('https://assets.invalid/'+name+'.fst',new Set(),undefined,undefined,(root:THREE.Object3D)=>seen.push(root))));assert.equal(a.userData.avatarMapping.scale,2);assert.equal(b.userData.avatarMapping.scale,3);assert.equal((mesh(a).material as THREE.MeshBasicMaterial[])[0].color.getHex(),0xff0000);assert.equal((mesh(b).material as THREE.MeshBasicMaterial[])[0].color.getHex(),0x00ff00);assert.equal(f.world.getParsedFbxTemplateStatistics().cache.producers,1);assert.equal(seen.length,2);[a,b].forEach(disposeParsedFbxGraph);}finally{f.close();}
});
test('actual ready consumer reauthorizes route and world permission; fresh generation invalidates old canonical template',async()=>{const f=fixture();try{const load=()=>f.world.loadModel('https://assets.invalid/body.fbx',new Set(),undefined,undefined,()=>{});const a=await load(),b=await load();assert.equal(f.world.getParsedFbxTemplateStatistics().cache.hits,1);f.next();const c=await load();assert.equal(f.world.getParsedFbxTemplateStatistics().cache.producers,1);f.revoke();await assert.rejects(load(),{name:'AbortError'});[a,b,c].forEach(disposeParsedFbxGraph);}finally{f.close();}});
test('actual World failed original dependency retains same staged root, original warning and no ready-template retention',async()=>{
 const f=fixture(replacementMaterialFbx()),staged:THREE.Object3D[]=[];const failures:(()=>void)[]=[];
 f.world.imageCache={loader(manager:THREE.LoadingManager){return new class extends THREE.TextureLoader{override load(url:string){const resolved=manager.resolveURL((this.path||'')+url);manager.itemStart(resolved);const texture=new THREE.Texture<HTMLImageElement>();failures.push(()=>{manager.itemError(resolved);manager.itemEnd(resolved);});return texture;}}(manager);}};
 try{const pending=f.world.loadModel('https://assets.invalid/body.fbx',new Set(),undefined,undefined,(root:THREE.Object3D)=>staged.push(root));await tick();assert.equal(staged.length,1);assert(failures.length>0);failures.forEach(fail=>fail());const root=await pending;assert.equal(root,staged[0]);assert(f.warnings.includes('warning'));assert.equal(f.world.getParsedFbxTemplateStatistics().cache.ready,0);assert.equal(f.world.getParsedFbxTemplateStatistics().cache.transient,1);disposeParsedFbxGraph(root);}finally{f.close();}
});
test('producer manager survives first reader cancellation while second reader awaits original image completion',async()=>{
 const f=fixture(replacementMaterialFbx()),first=new AbortController(),second=new AbortController(),staged:THREE.Object3D[]=[];const finish:(()=>void)[]=[];let manager:THREE.LoadingManager|undefined;
 f.world.imageCache={loader(owner:THREE.LoadingManager){return new class extends THREE.TextureLoader{override load(url:string){manager=owner;const key=owner.resolveURL((this.path||'')+url);owner.itemStart(key);const texture=new THREE.Texture<HTMLImageElement>();finish.push(()=>{owner.itemError(key);owner.itemEnd(key);});return texture;}}(owner);}};
 try{const a=f.world.loadModel('https://assets.invalid/body.fbx',new Set(),undefined,first.signal,(root:THREE.Object3D)=>staged.push(root)),b=f.world.loadModel('https://assets.invalid/body.fbx',new Set(),undefined,second.signal,(root:THREE.Object3D)=>staged.push(root));const rejected=assert.rejects(a,{name:'AbortError'});await tick();assert.equal(staged.length,2);assert(manager);first.abort();await rejected;assert.equal(manager.abortController.signal.aborted,false);finish.forEach(fn=>fn());const root=await b;assert.equal(root,staged[1]);assert.equal(f.world.loadManagers.size,0);disposeParsedFbxGraph(root);}finally{f.close();}
});
test('World invalidation aborts all pending producers without publishing late geometry or falling back',async()=>{
 const f=fixture(replacementMaterialFbx()),staged:THREE.Object3D[]=[];f.world.imageCache={loader(manager:THREE.LoadingManager){return new class extends THREE.TextureLoader{override load(url:string){const key=manager.resolveURL((this.path||'')+url);manager.itemStart(key);manager.abortController.signal.addEventListener('abort',()=>manager.itemEnd(key),{once:true});return new THREE.Texture<HTMLImageElement>();}}(manager);}};
 try{const pending=f.world.loadModel('https://assets.invalid/body.fbx',new Set(),undefined,undefined,(root:THREE.Object3D)=>staged.push(root));const rejected=assert.rejects(pending,{name:'AbortError'});await tick();assert.equal(staged.length,1);f.world.invalidateModelParses();await rejected;await tick();assert.equal(f.world.getParsedFbxTemplateStatistics().fallbacks,0);assert.equal(f.world.loadManagers.size,0);}finally{f.close();}
});
test('optional key budget refuses before staging and invokes the unchanged original parser, not a generic error fallback',async()=>{
 const f=fixture();let staged=0;f.world.options.resolveAsset=()=> 'https://assets.invalid/'+ 'a'.repeat(8192);
 try{const root=await f.world.loadModel('https://assets.invalid/body.fbx',new Set(),undefined,undefined,()=>staged++);assert.equal(staged,1);assert.equal(f.world.getParsedFbxTemplateStatistics().fallbacks,1);assert.equal(f.world.getParsedFbxTemplateStatistics().cache.producers,0);disposeParsedFbxGraph(root);}finally{f.close();}
});
test('actual malformed FBX parse failure remains original failure and creates no fallback parser or staged graph',async()=>{
 const f=fixture(new ArrayBuffer(64));let staged=0;try{await assert.rejects(f.world.loadModel('https://assets.invalid/body.fbx',new Set(),undefined,undefined,()=>staged++),error=>error instanceof Error&&error.name!=='AbortError');assert.equal(staged,0);assert.equal(f.world.getParsedFbxTemplateStatistics().fallbacks,0);assert.equal(f.world.loadManagers.size,0);}finally{f.close();}
});
test('actual approved embedded descriptor scope belongs to producer after first reader cancels and all scopes end after readiness',async()=>{
 const {extractEmbeddedFbxImages}=await import('../src/baked-fbx'),prepared=await extractEmbeddedFbxImages(replacementMaterialFbx({embedded:true}));assert(prepared.images.length>0);
 const f=fixture(prepared.buffer),first=new AbortController(),finish:(()=>void)[]=[];f.world.loadPreparedFbx=async()=>({buffer:prepared.buffer,embeddedImages:prepared.images,phases:{materialBindingsMs:0,decodeMs:0},cacheHit:false});
 f.world.imageCache={loader(manager:THREE.LoadingManager){return new class extends THREE.TextureLoader{override load(url:string){const key=manager.resolveURL((this.path||'')+url);assert(key.startsWith('blob:'));manager.itemStart(key);finish.push(()=>{manager.itemError(key);manager.itemEnd(key);});return new THREE.Texture<HTMLImageElement>();}}(manager);}};
 try{const a=f.world.loadModel('https://assets.invalid/body.fbx',new Set(),undefined,first.signal,()=>{}),b=f.world.loadModel('https://assets.invalid/body.fbx',new Set(),undefined,undefined,()=>{}),rejected=assert.rejects(a,{name:'AbortError'});await tick();assert.equal(f.world.embeddedFbxImages.statistics.scopes,3);first.abort();await rejected;assert.equal(f.world.embeddedFbxImages.statistics.scopes,2);finish.forEach(fn=>fn());const root=await b;assert.equal(f.world.embeddedFbxImages.statistics.scopes,0);assert.equal(f.world.loadManagers.size,0);disposeParsedFbxGraph(root);}finally{f.close();}
});
test('fully authoritative admission-rewritten FST remains original parse path rather than reuse a canonical raw mapping variant',async t=>{
 const f=fixture(replacementMaterialFbx());t.mock.method(globalThis,'fetch',async(input:unknown)=>new Response(String(input).endsWith('.fst')?'filename = body.fbx\nmaterialMap = [{"all":"material.json"}]':JSON.stringify({materials:{name:'Replacement',unlit:true,albedo:[1,0,0]}})));
 try{const root=await f.world.loadModel('https://assets.invalid/body.fst',new Set(),undefined,undefined,()=>{});assert.equal(f.world.getParsedFbxTemplateStatistics().cache,null);assert.equal((mesh(root).material as THREE.MeshBasicMaterial[])[0].color.getHex(),0xff0000);assert.equal(f.warnings.length,0);disposeParsedFbxGraph(root);}finally{f.close();}
});
