// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Authentic binary FBXLoader admission/ownership controls; no image/world success claim.
import test from 'node:test';import assert from 'node:assert/strict';
import {Mesh,MeshPhongMaterial,Object3D,SkinnedMesh} from 'three';
import {FBXLoader} from 'three/addons/loaders/FBXLoader.js';
import {replacementMaterialFbx} from './fixtures/parsed-template-fbx';
import {cloneParsedFbxTemplate,disposeParsedFbxGraph,inspectParsedFbxTemplate,ParsedFbxTemplates,ParsedFbxTemplateRefusal} from '../src/parsed-fbx-template';
const bytes=(skin=false,wide=false)=>replacementMaterialFbx({unnamedModel:true,skin,wide,vertexColors:true,withoutOriginalTextures:true});
const parse=(input=bytes())=>new FBXLoader().parse(input,'');
function mesh(root:Object3D){let result:Mesh|undefined;root.traverse(node=>{if(node instanceof Mesh)result??=node;});assert(result);return result;}
function missingName(root:Object3D){const node=mesh(root);assert.equal(node.name,'');assert.equal(Object.getPrototypeOf(node.userData),Object.prototype);assert.equal(Object.hasOwn(node.userData,'originalName'),true);assert.deepEqual(Object.getOwnPropertyDescriptor(node.userData,'originalName'),{value:undefined,writable:true,enumerable:true,configurable:true});}
const tick=()=>new Promise<void>(resolve=>setImmediate(resolve));
test('authentic unnamed binary32/64 FBX metadata is admitted and retained as an own absent-name value in every independent clone',()=>{
 for(const wide of [false,true]){const root=parse(bytes(false,wide));let a:Object3D|undefined,b:Object3D|undefined;try{missingName(root);const originalData=mesh(root).userData,inspection=inspectParsedFbxTemplate(root);a=cloneParsedFbxTemplate(root,inspection);b=cloneParsedFbxTemplate(root,inspection);for(const node of [root,a,b])missingName(node);assert.equal(mesh(root).userData,originalData);assert.notEqual(mesh(a).userData,originalData);assert.notEqual(mesh(a).userData,mesh(b).userData);mesh(a).userData.originalName='owner-local';assert.equal(mesh(b).userData.originalName,undefined);assert.equal(mesh(root).userData.originalName,undefined);}finally{for(const node of [a,b,root])if(node)disposeParsedFbxGraph(node);}}
});
test('named and unnamed genuine FBX keep exactly the same positions/normals/colors/UVs/groups/materials and skin data',()=>{
 for(const skin of [false,true]){const named=parse(replacementMaterialFbx({skin,vertexColors:true,withoutOriginalTextures:true})),unnamed=parse(bytes(skin));try{const a=mesh(named),b=mesh(unnamed);for(const key of ['position','normal','color','uv',...(skin?['skinIndex','skinWeight']:[])])assert.deepEqual(a.geometry.attributes[key].array,b.geometry.attributes[key].array,key);assert.deepEqual(a.geometry.groups,b.geometry.groups);for(let i=0;i<2;i++){const x=(a.material as MeshPhongMaterial[])[i],y=(b.material as MeshPhongMaterial[])[i];assert.equal(x.name,y.name);assert.deepEqual(x.color,y.color);assert.equal(x.opacity,y.opacity);assert.equal(x.side,y.side);}if(skin){assert(a instanceof SkinnedMesh&&b instanceof SkinnedMesh);assert.deepEqual(a.skeleton.boneInverses.map(x=>x.elements),b.skeleton.boneInverses.map(x=>x.elements));}}finally{disposeParsedFbxGraph(named);disposeParsedFbxGraph(unnamed);}}
});
test('joined and repeated same immutable unnamed input uses one authentic parse with independent staged owners and unchanged bytes',async()=>{
 const world=new AbortController(),cache=new ParsedFbxTemplates(world.signal),input=bytes(),before=Uint8Array.from(new Uint8Array(input));let parses=0,checks=0;const staged:Object3D[]=[];const producer=async(_signal:AbortSignal,onParsed:(root:Object3D)=>void)=>{parses++;const graph=parse(input);onParsed(graph);return graph;};const roots:Object3D[]=[];try{const one=cache.get(input,'approved-base',()=>checks++,producer,undefined,root=>staged.push(root)),two=cache.get(input,'approved-base',()=>checks++,producer,undefined,root=>staged.push(root));roots.push(...await Promise.all([one,two]));roots.push(await cache.get(input,'approved-base',()=>checks++,producer));assert.equal(parses,1);assert.equal(cache.statistics.producers,1);assert.equal(cache.statistics.joined,1);assert.equal(cache.statistics.hits,1);assert.equal(cache.statistics.cloned,3);assert.equal(cache.statistics.admissionEvidence.producerFailures,0);assert.deepEqual(staged,roots.slice(0,2));assert(checks>=6);for(const root of roots)missingName(root);assert.notEqual(mesh(roots[0]).geometry,mesh(roots[1]).geometry);assert.notEqual(mesh(roots[0]).material,mesh(roots[2]).material);assert.deepEqual(new Uint8Array(input),before);}finally{roots.forEach(disposeParsedFbxGraph);cache.dispose();}
});
test('prepared identity and approved base remain separate; no URL/source authority key collapsing',async()=>{
 const cache=new ParsedFbxTemplates(new AbortController().signal),a=bytes(),b=a.slice(0);let parses=0;const roots:Object3D[]=[];try{for(const [input,key]of [[a,'first'],[a,'second'],[b,'first']]as const)roots.push(await cache.get(input,key,()=>{},async()=>{parses++;return parse(input);}));assert.equal(parses,3);assert.equal(cache.statistics.ready,3);}finally{roots.forEach(disposeParsedFbxGraph);cache.dispose();}
});
test('one reader cancellation after geometry disposes only its clone while joined current owner finishes the original producer',async()=>{
 const cache=new ParsedFbxTemplates(new AbortController().signal),input=bytes(),reader=new AbortController();let publish!:(root:Object3D)=>void,finish!:(root:Object3D)=>void,firstDisposed=0,originalDisposed=0;const one=cache.get(input,'base',()=>{},async(_signal,onParsed)=>{publish=onParsed;return new Promise(resolve=>finish=resolve);},reader.signal,root=>mesh(root).geometry.addEventListener('dispose',()=>firstDisposed++));const rejected=assert.rejects(one,{name:'AbortError'});const two=cache.get(input,'base',()=>{},async()=>{throw Error('joined producer must not run');},undefined,()=>{});await tick();const original=parse(input);mesh(original).geometry.addEventListener('dispose',()=>originalDisposed++);publish(original);reader.abort();await rejected;assert.equal(firstDisposed,1);assert.equal(originalDisposed,0);finish(original);const survivor=await two;missingName(survivor);assert.equal(originalDisposed,0);disposeParsedFbxGraph(survivor);cache.dispose();assert.equal(originalDisposed,1);assert.equal(firstDisposed,1);
});
test('revoked current-owner check and whole-cache abort still suppress geometry publication and settle readers',async()=>{
 const world=new AbortController(),cache=new ParsedFbxTemplates(world.signal),input=bytes();let current=true,publish!:(root:Object3D)=>void,finish!:(root:Object3D)=>void,staged=0;const one=cache.get(input,'base',()=>{if(!current)throw new DOMException('Current owner ended','AbortError');},async(_signal,onParsed)=>{publish=onParsed;return new Promise(resolve=>finish=resolve);},undefined,()=>staged++);const rejected=assert.rejects(one,{name:'AbortError'});await tick();current=false;const original=parse(input);assert.throws(()=>publish(original),{name:'AbortError'});world.abort();await rejected;finish(original);await tick();assert.equal(staged,0);assert.equal(cache.statistics.ready,0);assert.equal(cache.statistics.readers,0);assert.equal(cache.statistics.bytes,0);
});
test('every other undefined site, nested originalName, named-node undefined and nonordinary descriptors still refuse',()=>{
 const mutations:((root:Object3D)=>void)[]=[root=>mesh(root).userData.other=undefined,root=>mesh(root).userData.nested={originalName:undefined},root=>mesh(root).name='named',root=>root.userData.other=undefined,root=>mesh(root).geometry.userData.originalName=undefined,root=>(mesh(root).material as MeshPhongMaterial[])[0].userData.originalName=undefined];for(const mutate of mutations){const root=parse();try{mutate(root);assert.throws(()=>inspectParsedFbxTemplate(root),ParsedFbxTemplateRefusal);}finally{disposeParsedFbxGraph(root);}}
 for(const flag of ['enumerable','writable','configurable']as const){const root=parse();try{Object.defineProperty(mesh(root).userData,'originalName',{value:undefined,enumerable:true,writable:true,configurable:true,[flag]:false});assert.throws(()=>inspectParsedFbxTemplate(root),ParsedFbxTemplateRefusal);}finally{disposeParsedFbxGraph(root);}}
});
test('originalName accessor, foreign metadata prototype and unsupported render callbacks refuse without executing hooks',()=>{
 let invoked=0;for(const kind of ['accessor','prototype','hook']){const root=parse();try{if(kind==='accessor')Object.defineProperty(mesh(root).userData,'originalName',{enumerable:true,configurable:true,get(){invoked++;throw Error('must not read');},set(){invoked++;}});else if(kind==='prototype')Object.setPrototypeOf(mesh(root).userData,{originalName:undefined});else root.onBeforeRender=()=>invoked++;assert.throws(()=>inspectParsedFbxTemplate(root),ParsedFbxTemplateRefusal);}finally{if(kind==='accessor')delete mesh(root).userData.originalName;disposeParsedFbxGraph(root);}}assert.equal(invoked,0);
});
test('unnamed genuine skins retain private bones/inverses/matrices and dispose only owner-local bone textures',()=>{
 const root=parse(bytes(true));let a:Object3D|undefined,b:Object3D|undefined,rootDisposed=false;try{a=cloneParsedFbxTemplate(root);b=cloneParsedFbxTemplate(root);const x=mesh(a)as SkinnedMesh,y=mesh(b)as SkinnedMesh,z=mesh(root)as SkinnedMesh;for(const node of [x,y,z])node.skeleton.computeBoneTexture();assert.notEqual(x.skeleton,y.skeleton);assert.notEqual(x.skeleton.boneTexture,y.skeleton.boneTexture);assert.notEqual(x.skeleton.bones[0],y.skeleton.bones[0]);assert.notEqual(x.skeleton.boneInverses[0],y.skeleton.boneInverses[0]);x.skeleton.bones[0].position.y=9;assert.notEqual(y.skeleton.bones[0].position.y,9);let xd=0,yd=0,zd=0;x.skeleton.boneTexture!.addEventListener('dispose',()=>xd++);y.skeleton.boneTexture!.addEventListener('dispose',()=>yd++);z.skeleton.boneTexture!.addEventListener('dispose',()=>zd++);disposeParsedFbxGraph(a);a=undefined;assert.equal(xd,1);assert.equal(yd,0);assert.equal(zd,0);disposeParsedFbxGraph(b);b=undefined;assert.equal(yd,1);assert.equal(zd,0);disposeParsedFbxGraph(root);rootDisposed=true;assert.equal(zd,1);}finally{if(a)disposeParsedFbxGraph(a);if(b)disposeParsedFbxGraph(b);if(!rootDisposed)disposeParsedFbxGraph(root);}
});
test('the exact own absent-name key remains charged to the existing bounded graph budget',()=>{
 const root=parse();try{const withName=inspectParsedFbxTemplate(root).bytes;delete mesh(root).userData.originalName;const withoutName=inspectParsedFbxTemplate(root).bytes;assert.equal(withName-withoutName,'originalName'.length*2+8);}finally{disposeParsedFbxGraph(root);}
});
