// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Exact FBXLoader/resource-token tests; no browser image or GPU allocation claim.
import test from 'node:test';import assert from 'node:assert/strict';
import {AnimationClip,BufferGeometry,Float32BufferAttribute,Material,Mesh,MeshPhongMaterial,NumberKeyframeTrack,Object3D,SkinnedMesh,Texture} from 'three';
import {FBXLoader} from 'three/addons/loaders/FBXLoader.js';
import {replacementMaterialFbx} from './fixtures/parsed-template-fbx';
import {cloneParsedFbxTemplate,disposeParsedFbxGraph,inspectParsedFbxTemplate,ParsedFbxTemplateRefusal,ParsedFbxTemplates} from '../src/parsed-fbx-template';
function parse(skin=false){const root=new FBXLoader().parse(replacementMaterialFbx({withoutOriginalTextures:true,skin,vertexColors:true,directionalLight:'detached'}),'');root.animations=[new AnimationClip('Owned animation',1,[new NumberKeyframeTrack('.position[x]',[0,1],[0,1])])];return root;}
function mesh(root:Object3D){let value:Mesh|undefined;root.traverse(node=>{if(node instanceof Mesh)value??=node;});assert(value);return value;}
function material(root:Object3D){const values=mesh(root).material;return (Array.isArray(values)?values[0]:values)as MeshPhongMaterial;}
for(const kind of ['geometry','material','animation']as const)test('post-inspection '+kind+' replacement refuses before an unchecked clone hook (genuine binary counterfactual)',()=>{
 const root=parse(),m=mesh(root),g=m.geometry,mat=m.material,animations=root.animations,token=inspectParsedFbxTemplate(root);let calls=0;const extra:BufferGeometry|Material|undefined=kind==='geometry'?BufferGeometry.prototype.clone.call(g):kind==='material'?new MeshPhongMaterial():undefined;
 try{if(kind==='geometry'){const value=extra as BufferGeometry;value.clone=()=>{calls++;return BufferGeometry.prototype.clone.call(value);};m.geometry=value;}else if(kind==='material'){const value=extra as Material;value.clone=()=>{calls++;return Material.prototype.clone.call(value);};m.material=Array.isArray(mat)?[value,...mat.slice(1)]:value;}else{const value=new AnimationClip('Replacement',1,[new NumberKeyframeTrack('.position[x]',[0,1],[1,0])]);value.clone=()=>{calls++;return AnimationClip.prototype.clone.call(value);};root.animations=[value];}assert.throws(()=>cloneParsedFbxTemplate(root,token),ParsedFbxTemplateRefusal);assert.equal(calls,0);}finally{m.geometry=g;m.material=mat;root.animations=animations;disposeParsedFbxGraph(root);extra?.dispose();}
});
for(const kind of ['geometry','material','clip','track','attribute']as const)test('same admitted '+kind+' late method mutation is refused before cloning',()=>{
 const root=parse(),m=mesh(root),objects={geometry:m.geometry,material:material(root),clip:root.animations[0],track:root.animations[0].tracks[0],attribute:m.geometry.attributes.position},value=objects[kind],token=inspectParsedFbxTemplate(root),before=Object.getOwnPropertyDescriptor(value,'clone');let calls=0;
 try{Object.defineProperty(value,'clone',{configurable:true,writable:true,value:()=>{calls++;throw Error('Forbidden clone');}});assert.throws(()=>cloneParsedFbxTemplate(root,token),ParsedFbxTemplateRefusal);assert.equal(calls,0);}finally{if(before)Object.defineProperty(value,'clone',before);else delete(value as unknown as {clone?:unknown}).clone;disposeParsedFbxGraph(root);}
});
test('material array slot, geometry attribute and clip track replacements cannot enter through unchanged container identity',()=>{
 for(const kind of ['slot','attribute','track']as const){const root=parse(),m=mesh(root),token=inspectParsedFbxTemplate(root);let calls=0;const restore:(()=>void)[]=[];try{if(kind==='slot'){assert(Array.isArray(m.material));const original=m.material[0],replacement=new MeshPhongMaterial();replacement.clone=()=>{calls++;return replacement;};m.material[0]=replacement;restore.push(()=>{(m.material as Material[])[0]=original;replacement.dispose();});}else if(kind==='attribute'){const original=m.geometry.attributes.position,replacement=new Float32BufferAttribute([0,0,0],3);replacement.clone=()=>{calls++;return replacement;};m.geometry.attributes.position=replacement;restore.push(()=>m.geometry.attributes.position=original);}else{const original=root.animations[0].tracks[0],replacement=new NumberKeyframeTrack('.position[x]',[0,1],[1,0]);replacement.clone=()=>{calls++;return replacement;};root.animations[0].tracks[0]=replacement;restore.push(()=>root.animations[0].tracks[0]=original);}assert.throws(()=>cloneParsedFbxTemplate(root,token),ParsedFbxTemplateRefusal);assert.equal(calls,0);}finally{restore.forEach(f=>f());disposeParsedFbxGraph(root);}}
});
test('late resource nested accessors and array iterator hooks refuse without invoking getters or setters',()=>{
 for(const kind of ['attribute','track','material','iterator']as const){const root=parse(),m=mesh(root),token=inspectParsedFbxTemplate(root);let reads=0,writes=0;const object:object=kind==='attribute'?m.geometry.attributes:kind==='track'?root.animations[0].tracks:kind==='material'?material(root).color:root.animations,key:PropertyKey=kind==='attribute'?'position':kind==='track'?'0':kind==='material'?'r':Symbol.iterator,before=Object.getOwnPropertyDescriptor(object,key);try{Object.defineProperty(object,key,{configurable:true,enumerable:true,get(){reads++;throw Error('Forbidden getter');},set(){writes++;}});assert.throws(()=>cloneParsedFbxTemplate(root,token),ParsedFbxTemplateRefusal);assert.equal(reads,0);assert.equal(writes,0);}finally{if(before)Object.defineProperty(object,key,before);else Reflect.deleteProperty(object,key);disposeParsedFbxGraph(root);}}
});
test('typed storage replacements, detach and own slice hooks refuse without element enumeration or foreign execution',()=>{
 for(const kind of ['replacement','detached','slice']as const){const root=parse(),track=root.animations[0].tracks[0],original=track.values,token=inspectParsedFbxTemplate(root);let calls=0;try{if(kind==='replacement')track.values=new Float32Array([1,0]);else if(kind==='detached')structuredClone(track.values.buffer,{transfer:[track.values.buffer as ArrayBuffer]});else Object.defineProperty(track.values,'slice',{configurable:true,value:()=>{calls++;return new Float32Array([1,0]);}});assert.throws(()=>cloneParsedFbxTemplate(root,token),ParsedFbxTemplateRefusal);assert.equal(calls,0);}finally{if(kind==='slice')Reflect.deleteProperty(original,'slice');disposeParsedFbxGraph(root);}}
});
test('late typed-array extent getters are refused without invoking untrusted getter or setter',()=>{
 for(const key of ['buffer','byteLength','byteOffset']as const){const root=parse(),array=root.animations[0].tracks[0].values,token=inspectParsedFbxTemplate(root);let reads=0,writes=0;try{Object.defineProperty(array,key,{configurable:true,get(){reads++;throw Error('No extent getter');},set(){writes++;}});assert.throws(()=>cloneParsedFbxTemplate(root,token),ParsedFbxTemplateRefusal);assert.equal(reads,0);assert.equal(writes,0);}finally{Reflect.deleteProperty(array,key);disposeParsedFbxGraph(root);}}
});
test('texture and Source replacement under unchanged material refuses before Texture.copy or new image reads',()=>{
 for(const kind of ['texture','source','getter']as const){const root=parse(),mat=material(root),texture=new Texture(),tokenBefore=mat.map;mat.map=texture;const token=inspectParsedFbxTemplate(root,true);let reads=0;try{if(kind==='texture')mat.map=new Texture();else if(kind==='source')texture.source=new Texture().source;else Object.defineProperty(texture,'source',{configurable:true,get(){reads++;throw Error('Forbidden Source getter');}});assert.throws(()=>cloneParsedFbxTemplate(root,token),ParsedFbxTemplateRefusal);assert.equal(reads,0);}finally{if(kind==='getter')Object.defineProperty(texture,'source',{configurable:true,writable:true,enumerable:true,value:new Texture().source});if(mat.map!==texture)mat.map?.dispose();mat.map=tokenBefore;texture.dispose();disposeParsedFbxGraph(root);}}
});
test('post-inspection skeleton/inverse replacement refuses before a new clone hook',()=>{
 for(const kind of ['skeleton','inverse']as const){const root=parse(true),m=mesh(root)as SkinnedMesh,original=m.skeleton,token=inspectParsedFbxTemplate(root);let calls=0;const inverse=original.boneInverses[0];try{if(kind==='skeleton'){const replacement=original.clone();replacement.clone=()=>{calls++;return replacement;};m.skeleton=replacement;}else{const replacement=inverse.clone();replacement.clone=()=>{calls++;return replacement;};original.boneInverses[0]=replacement;}assert.throws(()=>cloneParsedFbxTemplate(root,token),ParsedFbxTemplateRefusal);assert.equal(calls,0);}finally{m.skeleton=original;original.boneInverses[0]=inverse;disposeParsedFbxGraph(root);}}
});
test('valid repeated clones preserve every genuine geometry/animation and private material/skeleton; original disposal listeners remain permitted',()=>{
 const root=parse(true),token=inspectParsedFbxTemplate(root),m=mesh(root);let disposals=0;m.geometry.addEventListener('dispose',()=>disposals++);const a=cloneParsedFbxTemplate(root,token),b=cloneParsedFbxTemplate(root,token);try{assert.deepEqual(mesh(a).geometry.attributes.position.array,m.geometry.attributes.position.array);assert.notEqual(mesh(a).geometry,mesh(b).geometry);assert.notEqual(mesh(a).material,mesh(b).material);assert.notEqual(a.animations[0].tracks[0].values,b.animations[0].tracks[0].values);assert.notEqual((mesh(a)as SkinnedMesh).skeleton,(mesh(b)as SkinnedMesh).skeleton);disposeParsedFbxGraph(a);assert.equal(disposals,0);disposeParsedFbxGraph(b);assert.equal(disposals,0);}finally{disposeParsedFbxGraph(root);}assert.equal(disposals,1);
});
test('ready-hit resource mutation has typed refusal, drops canonical entry and preserves already published owner',async()=>{
 const cache=new ParsedFbxTemplates(new AbortController().signal),input=new ArrayBuffer(1);let original:Object3D|undefined;const owner=await cache.get(input,'approved/base',()=>{},async()=>{original=parse();return original;});assert(original);const g=mesh(original).geometry;let calls=0;g.clone=()=>{calls++;return g;};try{await assert.rejects(cache.get(input,'approved/base',()=>{},async()=>{assert.fail('No producer before refused hit');return parse();}),ParsedFbxTemplateRefusal);assert.equal(calls,0);assert.equal(cache.statistics.ready,0);assert.equal(cache.statistics.readers,0);assert.notEqual(mesh(owner).geometry,g);assert(mesh(owner).geometry.attributes.position.count>0);}finally{delete(g as unknown as {clone?:unknown}).clone;disposeParsedFbxGraph(owner);cache.dispose();}
});
test('bounded snapshots refuse oversized descriptor containers without widening the original byte budget',()=>{
 const root=parse(),mat=material(root);mat.userData.small=Array.from({length:3000},()=>({a:1,b:2}));const before=inspectParsedFbxTemplate(root).bytes;assert(before>3000*2*48);mat.userData.large=Array.from({length:65537},()=>({}));assert.throws(()=>inspectParsedFbxTemplate(root),ParsedFbxTemplateRefusal);disposeParsedFbxGraph(root);
});
