// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import * as THREE from 'three';
import {FBXLoader} from 'three/addons/loaders/FBXLoader.js';
import {ParsedFbxTemplates,disposeParsedFbxGraph} from '../src/parsed-fbx-template';
import {replacementMaterialFbx} from './fixtures/parsed-template-fbx';
/** Actual renderer and actual browser ImageLoader: no fake image/texture readiness. */
export async function auditParsedFbxTemplate(variant:'plain'|'skin'|'morph',options:{unnamedModel?:boolean;directionalLight?:boolean}={}){
 const owner=new AbortController(),cache=new ParsedFbxTemplates(owner.signal),canvas=document.createElement('canvas');canvas.width=640;canvas.height=480;document.body.append(canvas);
 const renderer=new THREE.WebGLRenderer({canvas,antialias:false,preserveDrawingBuffer:true});renderer.setPixelRatio(1);renderer.setSize(640,480,false);renderer.setClearColor(0x263544,1);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(50,640/480,.1,100);camera.position.set(0,0,3);scene.add(new THREE.AmbientLight(0xffffff,1.5));const light=new THREE.PointLight(0xffeeee,8,20);light.position.set(2,3,4);scene.add(light);
 const buffer=replacementMaterialFbx({skin:variant==='skin',vertexColors:true,unnamedModel:options.unnamedModel===true,...(options.directionalLight===true?{directionalLight:'detached' as const}:{})}),roots:THREE.Object3D[]=[],rows:{label:string;different:number;maximumDelta:number;visible:number;center:number[];surfaceCenters:number[][];background:number[]}[]=[],staged:{ready:boolean;vertices:number}[]=[],sourceVersions=new Map<THREE.TextureSource<unknown>,number>();let parseCalls=0;let outcome;const lightDisposal={created:0,disposed:0},observedLights=new Set<THREE.DirectionalLight>();const watchLights=(root:THREE.Object3D)=>{if(!options.directionalLight)return;root.traverse(node=>{if(node instanceof THREE.DirectionalLight&&!observedLights.has(node)){observedLights.add(node);lightDisposal.created++;node.addEventListener('dispose',()=>lightDisposal.disposed++);}});};
 const producer=async(signal:AbortSignal,onParsed?:(root:THREE.Object3D)=>void)=>{
  parseCalls++;const manager=new THREE.LoadingManager(),sentinel='owned-parse',loader=new FBXLoader(manager);let resolve!:()=>void,reject!:(error:unknown)=>void;const ready=new Promise<void>((yes,no)=>{resolve=yes;reject=no;});ready.catch(()=>{});manager.onLoad=resolve;manager.onError=()=>reject(Error('An actual fixture texture failed'));manager.setURLModifier(url=>new URL(url,new URL('./fixtures/',location.href)).href);
  const abort=()=>{reject(new DOMException('Fixture ended','AbortError'));manager.abort();};signal.addEventListener('abort',abort,{once:true});manager.itemStart(sentinel);let root:THREE.Object3D|undefined;
  try{root=loader.parse(buffer,new URL('./fixtures/',location.href).href);if(variant==='morph')root.traverse(node=>{if(node instanceof THREE.Mesh){node.geometry.morphAttributes.position=[new THREE.Float32BufferAttribute(Array.from(node.geometry.attributes.position.array,v=>Number(v)*.95),3)];node.updateMorphTargets();}});watchLights(root);onParsed?.(root);manager.itemEnd(sentinel);await ready;signal.throwIfAborted();return root;}catch(error){if(root)disposeParsedFbxGraph(root);throw error;}finally{signal.removeEventListener('abort',abort);}
 };
 const actualMeshes=(root:THREE.Object3D)=>{const meshes:THREE.Mesh[]=[];root.traverse(node=>{if(node instanceof THREE.Mesh)meshes.push(node);});return meshes;};
 function pixels(root:THREE.Object3D){scene.add(root);root.updateMatrixWorld(true);for(let i=0;i<20;i++)renderer.render(scene,camera);const data=new Uint8Array(640*480*4);renderer.getContext().readPixels(0,0,640,480,renderer.getContext().RGBA,renderer.getContext().UNSIGNED_BYTE,data);scene.remove(root);return data;}
 function centers(root:THREE.Object3D,data:Uint8Array){const points:number[][]=[];root.updateMatrixWorld(true);for(const mesh of actualMeshes(root)){const position=mesh.geometry.attributes.position,index=mesh.geometry.index;for(let start=0;start+2<(index?.count??position.count)&&points.length<2;start+=3){const point=new THREE.Vector3();for(let k=0;k<3;k++)point.add(new THREE.Vector3().fromBufferAttribute(position,index?index.getX(start+k):start+k));point.multiplyScalar(1/3);mesh.localToWorld(point);point.project(camera);const x=Math.floor((point.x+1)*320),y=Math.floor((point.y+1)*240);if(x<0||x>=640||y<0||y>=480)throw Error('Actual authored surface center outside viewport');points.push([...data.slice((y*640+x)*4,(y*640+x)*4+4)]);}}return points;}
 function compare(label:string,a:Uint8Array,b:Uint8Array){let different=0,maximumDelta=0,visible=0;for(let i=0;i<a.length;i++){if(a[i]!==b[i])different++;maximumDelta=Math.max(maximumDelta,Math.abs(a[i]-b[i]));}for(let i=0;i<a.length;i+=4)if(a[i]>80||a[i+1]>100||a[i+2]>140)visible++;rows.push({label,different,maximumDelta,visible,center:[...a.slice((240*640+320)*4,(240*640+320)*4+4)],surfaceCenters:centers(roots[0],a),background:[...a.slice(0,4)]});}
 try{
  const baseline=await producer(owner.signal);roots.push(baseline);const first=await cache.get(buffer,'owned-authorized-source/base-one',()=>owner.signal.throwIfAborted(),producer,owner.signal,root=>{const mesh=actualMeshes(root)[0];staged.push({ready:Boolean(((mesh.material as THREE.MeshPhongMaterial[])[0].map?.image as HTMLImageElement|null)?.complete),vertices:mesh.geometry.attributes.position.count});});roots.push(first);for(const mesh of actualMeshes(first))for(const material of Array.isArray(mesh.material)?mesh.material:[mesh.material])for(const value of Object.values(material))if(value instanceof THREE.Texture)sourceVersions.set(value.source,value.source.version);
  const second=await cache.get(buffer,'owned-authorized-source/base-one',()=>owner.signal.throwIfAborted(),producer,owner.signal);roots.push(second);watchLights(first);watchLights(second);const baseMeshes=actualMeshes(baseline),firstMeshes=actualMeshes(first),secondMeshes=actualMeshes(second);
  if(!baseMeshes.length||!firstMeshes.length||!secondMeshes.length)throw Error('Actual imported meshes required');if(variant==='skin'&&!firstMeshes.some(mesh=>mesh instanceof THREE.SkinnedMesh))throw Error('Actual imported skin required');
  for(const mesh of firstMeshes)for(const material of Array.isArray(mesh.material)?mesh.material:[mesh.material])for(const value of Object.values(material))if(value instanceof THREE.Texture){if(!value.image?.complete)throw Error('Actual loaded browser HTML image required');if(!sourceVersions.has(value.source))sourceVersions.set(value.source,value.source.version);}
  compare('loaded',pixels(baseline),pixels(first));compare('cached',pixels(baseline),pixels(second));baseline.position.x=first.position.x=second.position.x=.125;compare('moved',pixels(baseline),pixels(second));
  const b=(baseMeshes[0].material as THREE.MeshPhongMaterial[])[0],s=(secondMeshes[0].material as THREE.MeshPhongMaterial[])[0];b.map!.offset.x=s.map!.offset.x=.25;b.color.setRGB(.35,.8,.6);s.color.setRGB(.35,.8,.6);compare('owner-map-and-color',pixels(baseline),pixels(second));
  const independent=firstMeshes[0].geometry!==secondMeshes[0].geometry&&firstMeshes[0].geometry.attributes.position.array!==secondMeshes[0].geometry.attributes.position.array&&(firstMeshes[0].material as THREE.Material[])[0]!==s&&(firstMeshes[0].material as THREE.MeshPhongMaterial[])[0].map!==s.map;
  // Observe authentic FBXLoader metadata and each independent cache clone; never mutate it.
  const unnamedMetadata=options.unnamedModel===true?{
   ownUndefined:[baseMeshes,firstMeshes,secondMeshes].every(meshes=>meshes.length>0&&meshes.every(mesh=>mesh.name===''&&Object.getOwnPropertyDescriptor(mesh.userData,'originalName')?.value===undefined&&Object.hasOwn(mesh.userData,'originalName'))),
   ordinaryDescriptor:[baseMeshes,firstMeshes,secondMeshes].every(meshes=>meshes.every(mesh=>{const descriptor=Object.getOwnPropertyDescriptor(mesh.userData,'originalName');return descriptor?.enumerable===true&&descriptor.writable===true&&descriptor.configurable===true&&Object.getPrototypeOf(mesh.userData)===Object.prototype;})),
   independent:baseMeshes[0].userData!==firstMeshes[0].userData&&baseMeshes[0].userData!==secondMeshes[0].userData&&firstMeshes[0].userData!==secondMeshes[0].userData,
   meshCounts:[baseMeshes.length,firstMeshes.length,secondMeshes.length]
  }:undefined;
  const directionalMetadata=options.directionalLight===true?(()=>{const lists=[baseline,first,second].map(root=>{const lights:THREE.DirectionalLight[]=[];root.traverse(node=>{if(node instanceof THREE.DirectionalLight)lights.push(node);});return lights;});const source=lists[0][0];if(!source)throw Error('Actual binary DirectionalLight required');return{counts:lists.map(lights=>lights.length),exactClass:lists.every(lights=>lights.every(light=>Object.getPrototypeOf(light)===THREE.DirectionalLight.prototype)),statePreserved:lists.every(lights=>lights.every(light=>light.intensity===source.intensity&&light.color.equals(source.color)&&light.matrix.equals(source.matrix)&&light.target.position.equals(source.target.position)&&light.shadow.camera.projectionMatrix.equals(source.shadow.camera.projectionMatrix))),privateDescriptors:new Set(lists.map(lights=>lights[0].target)).size===3&&new Set(lists.map(lights=>lights[0].shadow)).size===3&&new Set(lists.map(lights=>lights[0].shadow.camera)).size===3,unallocated:lists.every(lights=>lights.every(light=>!light.castShadow&&light.target.parent===null&&light.shadow.map===null&&light.shadow.mapPass===null)),disposal:lightDisposal};})():undefined;
  outcome={directionalMetadata,unnamedMetadata,backend:renderer.getContext()instanceof WebGL2RenderingContext?'WebGL2':'other',variant,rows,staged,independent,sourceVersionsStable:[...sourceVersions].every(([source,version])=>source.version===version),parseCalls,cache:cache.statistics,cleanup:false};
 }finally{owner.abort();cache.dispose();for(const root of roots)disposeParsedFbxGraph(root);renderer.dispose();renderer.forceContextLoss();canvas.remove();}
 outcome.cleanup=cache.statistics.ready===0&&cache.statistics.readers===0&&cache.statistics.bytes===0;return outcome;
}
