// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,symlink,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {compareParsedFbxHub,readComparisonReport} from './integration/parsed-fbx-hub-comparison.mjs';
import {configureParsedFbxTemplateCohort} from './integration/hub-parsed-fbx-cohort.mjs';
const h='a'.repeat(64),k='b'.repeat(64),epoch=1759400000000;
const pins=['src/world.ts','src/main.ts','src/parsed-fbx-template.ts','src/owned-skeletons.ts','tests/integration/public-hub.mjs','tests/integration/hub-parsed-fbx-cohort.mjs'];
const gate={passed:true,validMeasurements:true,minimumFPS:30,maximumP95FrameMs:1000/15,maximumStallMs:250};
function performance(mode){return {loadedModels:295,loadedAvatars:1,meshColliders:75,entities:517,loadingModels:0,queuedModels:0,compilingGraphics:0,graphicsActive:true,drawingBufferWidth:1280,drawingBufferHeight:800,preparedFbxCache:{active:0,readers:0,hits:173,misses:124,ready:122,evictions:0,bytes:40000000,keyBytes:20000},loadPhases:{fbxParse:{count:mode==='templates'?122:295,totalMs:mode==='templates'?1000:4000,maxMs:100}},parsedFbxTemplates:mode==='templates'?{enabled:true,fallbacks:0,cache:{producers:122,hits:173,joined:0,cloned:295,evicted:90,refused:0,transient:0,ready:32,pending:0,readers:0,bytes:20000000}}:{enabled:false,fallbacks:0,cache:null}};}
function report(mode){const p=performance(mode),source=Object.fromEntries(pins.map(n=>['browser-client/'+n,h])),native={'bridge.js':h,'native-tablet.js':h,'tablet-capture.qml':h};const entry={urlSHA256:h,category:'FBX',requests:1,knownBytes:1000,unknownByteResponses:0,totalMs:25,maximumMs:25,sources:{download:1,shared:0,memory:0,unknown:0}};return {completed:true,fluidMovementAcceptancePassed:true,place:'overte_hub',microphoneRequested:false,worldInteractionsSent:0,pageErrors:[],movementMeters:4,reconnectedMovementMeters:4,nativePoseDifferenceMeters:0.001,reconnectedNativeDifferenceMeters:0.001,parsedFbxTemplateCohort:{schema:1,mode},startSourceSHA256:source,sourceSHA256:{...source},startDistributionManifest:{'assets/app.js':{sha256:h,bytes:5000}},distributionManifest:{'assets/app.js':{sha256:h,bytes:5000}},runtimeHelperSHA256:native,reconnectedRuntimeHelperSHA256:{...native,'bridge.js':k},browserVersion:'154.0.8072.0',webGL:{vendor:'fixture',renderer:'fixture',parallelShaderCompile:true},viewport:{width:1280,height:800,devicePixelRatio:1,visibility:'visible'},...Object.fromEntries(['gpuTimingRequested','cpuFrameTimingRequested','renderCpuTimingRequested','staticModelMatricesRequested','bitmapUploadRequested','modelParseTurnRequested','modelSlotResidenceRequested','shaderWarmupRequested','texturePreparationRequested','renderDispatchAttributionRequested','asyncDrawCensusRequested','loadedModelCohortCensusRequested','uploadProfileRequested'].map(n=>[n,false])),connectedAt:new Date(epoch).toISOString(),performance:[{...structuredClone(p),at:epoch+10000},{...structuredClone(p),at:epoch+13000}],after:{performance:structuredClone(p)},reconnectedAfterMovement:{performance:structuredClone(p)},reconnectedSteadySamples:Array.from({length:4},()=>structuredClone(p)),assetTransfers:{sessions:[1,2].map(ordinal=>({ordinal,uniqueURLs:1,requests:1,entries:[structuredClone(entry)]}))},originalImageErrors:{schema:1,scope:'existing-owned-gateway-original-image-502-responses',extensionIsNotDecodedFormat:true,accepted:0,completed:0,dropped:0,unsettled:0,aggregates:{},entries:[]},failedResources:[],...Object.fromEntries(['steadyFluidPerformance','walkFluidPerformance','reconnectedSteadyFluidPerformance','reconnectedWalkFluidPerformance'].map(n=>[n,{...gate}]))};}
const compare=(edit)=>{const a=report('baseline'),b=report('templates');edit?.(a,b);return compareParsedFbxHub(a,b);};
test('source-coherent counterfactual separates synchronous parse-span reduction from unchanged ready time',()=>{const r=compare();assert.equal(r.status,'compared');assert.equal(r.generations[0].parseCountDifference,-173);assert.equal(r.generations[0].parseSpanSumDifferenceMs,-3000);assert.equal(r.firstReadyPolling.differenceMs,0);assert.equal(r.equivalence.wholeHubPixels,false);assert.equal(r.equivalence.equalNetworkLatency,false);assert.equal(r.equivalence.assetBodyBytes,false);});
test('slower ready poll remains a valid negative result despite less parser work',()=>{const r=compare((a,b)=>b.performance.forEach(s=>s.at+=3000));assert.equal(r.status,'compared');assert.equal(r.firstReadyPolling.differenceMs,3000);assert.equal(r.generations[0].parseCountDifference,-173);});
test('producer actual count is not multiplied by cloned consumers or owner trace sums',()=>{const r=compare((a,b)=>{b.performance.forEach(s=>s.modelSlotResidence={enabled:true,reportCensored:false,clockInvalid:0,active:0,exclusiveLeafWallMs:{'loader-other':100000,'fbx-parse':0}});});assert.equal(r.status,'compared');assert.equal(r.generations[0].templates.fbxParse.count,122);assert.equal(r.generations[0].templates.parsedTemplates.cache.cloned,295);});
const negatives=[
 ['source mutation',(a,b)=>b.sourceSHA256['browser-client/src/world.ts']=k,'source-changed'],
 ['missing template source pin',(a,b)=>{delete b.startSourceSHA256['browser-client/src/parsed-fbx-template.ts'];delete b.sourceSHA256['browser-client/src/parsed-fbx-template.ts'];},'source-attestation-limit'],
 ['different coherent source cohort',(a,b)=>{b.startSourceSHA256['browser-client/src/world.ts']=k;b.sourceSHA256['browser-client/src/world.ts']=k;},'cohort-source-or-distribution-mismatch'],
 ['distribution mutation',(a,b)=>b.distributionManifest['assets/app.js'].sha256=k,'distribution-changed'],
 ['different viewport DPR',(a,b)=>b.viewport.devicePixelRatio=2,'viewport-or-dpr-mismatch'],
 ['different buffers',(a,b)=>{b.performance.forEach(s=>s.drawingBufferWidth=2560);b.after.performance.drawingBufferWidth=2560;},'drawing-buffer-mismatch'],
 ['different browser',(a,b)=>b.browserVersion='156.0','browser-mismatch'],
 ['different WebGL metadata',(a,b)=>b.webGL.renderer='other','webgl-metadata-mismatch'],
 ['different options',(a,b)=>b.shaderWarmupRequested=true,'other-option-mismatch'],
 ['different scene counts',(a,b)=>{b.performance.forEach(s=>s.loadedModels++);b.after.performance.loadedModels++;},'scene-count-mismatch'],
 ['still active model',(a,b)=>b.after.performance.loadingModels=1,'world-not-ready'],
 ['censored owner record',(a,b)=>b.performance[0].modelSlotResidence={enabled:true,reportCensored:true,clockInvalid:0,active:0},'censored-owner-evidence'],
 ['missing phase',(a,b)=>delete b.performance[0].loadPhases.fbxParse,'missing-parse-evidence'],
 ['pending template reader',(a,b)=>b.performance[0].parsedFbxTemplates.cache.readers=1,'cache-not-settled'],
 ['wrong cache mode',(a,b)=>b.performance[0].parsedFbxTemplates.enabled=false,'cache-mode-mismatch'],
 ['different asset sources',(a,b)=>{b.assetTransfers.sessions[0].entries[0].sources.download=0;b.assetTransfers.sessions[0].entries[0].sources.memory=1;},'asset-metadata-mismatch'],
 ['different source set',(a,b)=>b.assetTransfers.sessions[0].entries[0].urlSHA256=k,'asset-metadata-mismatch'],
 ['missing asset bytes',(a,b)=>delete b.assetTransfers.sessions[0].entries[0].knownBytes,'numeric-evidence-refused'],
 ['censored image error',(a,b)=>b.originalImageErrors.dropped=1,'censored-image-errors'],
 ['changed original image error',(a,b)=>{b.originalImageErrors.entries=[{urlSHA256:k,format:'jpg',category:'origin-refused'}];b.originalImageErrors.accepted=1;b.originalImageErrors.completed=1;b.originalImageErrors.aggregates={'jpg:origin-refused':1};},'original-image-errors-mismatch'],
 ['fluid gate false',(a,b)=>b.reconnectedWalkFluidPerformance.passed=false,'original-fluid-gate-failed'],
 ['weakened gate',(a,b)=>b.walkFluidPerformance.minimumFPS=20,'original-fluid-gate-failed'],
 ['missing native pose evidence',(a,b)=>delete b.nativePoseDifferenceMeters,'numeric-evidence-refused'],
 ['different native helper',(a,b)=>{b.runtimeHelperSHA256['native-tablet.js']=k;b.reconnectedRuntimeHelperSHA256['native-tablet.js']=k;},'native-helper-mismatch'],
 ['unknown explicit mode',(a,b)=>b.parsedFbxTemplateCohort.mode='auto','missing-explicit-cohort'],
 ['missing rejoin',(a,b)=>delete b.reconnectedAfterMovement,'missing-performance-evidence'],
];
for(const [name,edit,reason]of negatives)test('refuses '+name,()=>assert.deepEqual(compare(edit),{schema:1,status:'refused',reason}));
test('ignored private identity data never enters output; accessors are not invoked',()=>{const a=report('baseline'),b=report('templates');a.privateAddress=b.privateAddress='PRIVATE_SENTINEL';const out=JSON.stringify(compareParsedFbxHub(a,b));assert(!out.includes('PRIVATE_SENTINEL'));let reads=0;Object.defineProperty(b,'privateAccessor',{get(){reads++;throw Error('PRIVATE_SENTINEL');},enumerable:true});assert.deepEqual(compareParsedFbxHub(a,b),{schema:1,status:'refused',reason:'report-accessor-refused'});assert.equal(reads,0);});
test('bound file descriptor refuses symlinks, malformed JSON and oversize without reflecting paths',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'parsed-hub-contract-'));try{const file=path.join(dir,'report.json');await writeFile(file,JSON.stringify(report('baseline')));const read=await readComparisonReport(file);assert.equal(read.value.completed,true);assert.match(read.sha256,/^[0-9a-f]{64}$/);await symlink(file,path.join(dir,'alias'));await assert.rejects(readComparisonReport(path.join(dir,'alias')),e=>e.message==='input-read-refused');await writeFile(file,'{PRIVATE_SENTINEL');await assert.rejects(readComparisonReport(file),e=>e.message==='input-json-refused');await writeFile(file,Buffer.alloc(32*1024*1024+1));await assert.rejects(readComparisonReport(file),e=>e.message==='input-file-refused');}finally{await rm(dir,{recursive:true,force:true});}});
test('cohort option has no effect when unset and changes only the intended existing query',()=>{const url=new URL('http://127.0.0.1:8090/?other=1&parsedFbxTemplates=1');assert.equal(configureParsedFbxTemplateCohort(undefined,url),undefined);assert.equal(url.searchParams.get('parsedFbxTemplates'),'1');assert.deepEqual(configureParsedFbxTemplateCohort('baseline',url),{schema:1,mode:'baseline'});assert.equal(url.searchParams.get('other'),'1');assert.equal(url.searchParams.has('parsedFbxTemplates'),false);assert.deepEqual(configureParsedFbxTemplateCohort('templates',url),{schema:1,mode:'templates'});assert.equal(url.searchParams.get('parsedFbxTemplates'),'1');assert.throws(()=>configureParsedFbxTemplateCohort('auto',url),/refused/);});

test('equal asset metadata never implies equal network latency',()=>{const r=compare((a,b)=>{for(const session of b.assetTransfers.sessions){session.entries[0].totalMs=2500;session.entries[0].maximumMs=2500;}});assert.equal(r.status,'compared');assert.equal(r.equivalence.equalNetworkLatency,false);});
test('missing image aggregate refuses instead of assuming no errors',()=>assert.deepEqual(compare((a,b)=>delete b.originalImageErrors.aggregates),{schema:1,status:'refused',reason:'missing-image-error-aggregates'}));

// Preserve raw engine/version identity; admit only the observed lowercase BiDi prefix.
test('matching actual Firefox syntax compares without version normalization',()=>{const r=compare((a,b)=>{a.browserVersion=b.browserVersion='firefox/156.0';});assert.equal(r.status,'compared');assert.equal(r.browserVersion,'firefox/156.0');});
for(const version of ['Firefox/156.0','chrome/154.0.8037.57','unknown/156.0','firefox/156','firefox/156.0-beta','firefox/156.0extra',' firefox/156.0','firefox/156.0 ','firefox/156.0\n','firefox/156.0\r','firefox/156.0.1.2.3'])test('refuses unknown or malformed browser evidence '+JSON.stringify(version),()=>assert.deepEqual(compare((a,b)=>{a.browserVersion=b.browserVersion=version;}),{schema:1,status:'refused',reason:'browser-evidence-refused'}));
for(const version of ['firefox/156.1','firefox/157.0','156.0'])test('retains exact Firefox version and engine mismatch refusal '+version,()=>assert.deepEqual(compare((a,b)=>{a.browserVersion='firefox/156.0';b.browserVersion=version;}),{schema:1,status:'refused',reason:'browser-mismatch'}));
test('Firefox syntax does not waive the complete scene/assets/source/fluidness restrictions',()=>{for(const [name,edit,reason]of negatives){const a=report('baseline'),b=report('templates');a.browserVersion=b.browserVersion='firefox/156.0';edit(a,b);assert.deepEqual(compareParsedFbxHub(a,b),{schema:1,status:'refused',reason},name);}});
