// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import {test} from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {RenderDispatchAttributionFrame} from '../src/render-dispatch-attribution';import {RenderCpuBreakdown} from '../src/render-cpu-breakdown';
function graph(){const geometry=new T.BufferGeometry(),material=new T.MeshStandardMaterial(),mesh=new T.Mesh(geometry,material);return {geometry,material,mesh};}
test('actual ordered identities count material and geometry transitions independently',()=>{const f=new RenderDispatchAttributionFrame(()=>0),a=graph(),b=graph();for(const [g,m,o]of [[a.geometry,a.material,a.mesh],[a.geometry,a.material,b.mesh],[b.geometry,b.material,b.mesh],[a.geometry,a.material,a.mesh]] as const)f.observeDraw(g,m,o);const r=f.finish();assert.equal(r.complete,true);assert.equal(r.drawsObserved,4);assert.equal(r.materials,2);assert.equal(r.geometries,2);assert.equal(r.owners,2);assert.equal(r.materialTransitions,2);assert.equal(r.geometryTransitions,2);assert.equal(r.geometryVariants,1);});
test('actual program calls count transitions without fabricating an initial binding or GPU query',()=>{const f=new RenderDispatchAttributionFrame(()=>0),a={},b={};f.finishDraw();f.observeProgram(a);f.finishDraw();f.observeProgram(a);f.observeProgram(b);f.finishDraw();const r=f.finish();assert.equal(r.programCalls,3);assert.equal(r.programs,2);assert.equal(r.programTransitions,1);assert.equal(r.drawsWithObservedProgram,2);assert.equal(r.drawsWithoutObservedProgram,1);});
test('shared Source and identical sampler deduplicate identity tuples; sampler differences and distinct Sources do not',()=>{const f=new RenderDispatchAttributionFrame(()=>0),a=graph(),b=graph(),c=graph(),image={privateURL:'must-not-read'};a.material.map=new T.Texture(image as any);b.material.map=a.material.map.clone();c.material.map=new T.Texture(image as any);for(const g of [a,b,c])f.observeDraw(g.geometry,g.material,g.mesh);b.material.map.wrapS=T.RepeatWrapping;f.observeDraw(b.geometry,b.material,b.mesh);const r=f.finish();assert.equal(r.complete,true);assert.equal(r.sources,2);assert.equal(r.sourceSamplerTuples,3);assert.equal(r.textureBindings,4);assert.equal(JSON.stringify(r).includes('must-not-read'),false);});
test('Source replacement and sampler mutation are observed each draw rather than cached by material identity',()=>{const f=new RenderDispatchAttributionFrame(()=>0),a=graph();a.material.map=new T.Texture();f.observeDraw(a.geometry,a.material,a.mesh);a.material.map.source=new T.TextureSource(null);f.observeDraw(a.geometry,a.material,a.mesh);a.material.map.minFilter=T.NearestFilter;f.observeDraw(a.geometry,a.material,a.mesh);const r=f.finish();assert.equal(r.sources,2);assert.equal(r.sourceSamplerTuples,3);assert.equal(r.materials,1);});
test('geometry feature flags distinguish skin, instance, morph and vertex alpha without shader equivalence claims',()=>{const f=new RenderDispatchAttributionFrame(()=>0),a=graph();f.observeDraw(a.geometry,a.material,a.mesh);a.geometry.setAttribute('color',new T.BufferAttribute(new Float32Array(4),4));a.material.vertexColors=true;f.observeDraw(a.geometry,a.material,a.mesh);a.geometry.morphAttributes.position=[];f.observeDraw(a.geometry,a.material,a.mesh);const skin=new T.SkinnedMesh(a.geometry,a.material);f.observeDraw(a.geometry,a.material,skin);const r=f.finish();assert.equal(r.geometryVariants,4);assert.equal(r.geometryVariantTransitions,3);});
test('asset-controlled texture getters are never invoked or mistaken for absent maps',()=>{const f=new RenderDispatchAttributionFrame(()=>0),a=graph();let called=0;Object.defineProperty(a.material,'map',{get(){called++;throw Error('private-value');}});f.observeDraw(a.geometry,a.material,a.mesh);const r=f.finish();assert.equal(called,0);assert.equal(r.censored,true);assert.equal(r.reason,'unsupported-input');assert.equal(JSON.stringify(r).includes('private-value'),false);});
test('draw, owner, material, geometry and program bounds censor evidence while original objects remain untouched',()=>{
 for(const [kind,make,count,reason]of [
  ['draw',()=>graph(),4097,'draw-limit'],['owner',()=>graph(),513,'owner-limit'],['material',()=>graph(),513,'material-limit'],['geometry',()=>graph(),513,'geometry-limit']
 ] as const){const f=new RenderDispatchAttributionFrame(()=>0),a=graph();for(let i=0;i<count;i++){const b=kind==='draw'?a:make();f.observeDraw(kind==='geometry'?b.geometry:a.geometry,kind==='material'?b.material:a.material,kind==='owner'?b.mesh:a.mesh);}const r=f.finish();assert.equal(r.reason,reason);assert.equal(r.complete,false);assert.equal(a.mesh.visible,true);}
 const f=new RenderDispatchAttributionFrame(()=>0);for(let i=0;i<129;i++)f.observeProgram({});assert.equal(f.finish().reason,'program-limit');
});
test('CPU and elapsed bounds are explicit partial evidence; diagnostic errors never escape',()=>{let time=0;const f=new RenderDispatchAttributionFrame(()=>time++),a=graph();for(let i=0;i<9;i++)f.observeDraw(a.geometry,a.material,a.mesh);const r=f.finish();assert.equal(r.reason,'cpu-limit');assert.equal(r.complete,false);let wall=0;const g=new RenderDispatchAttributionFrame(()=>wall);wall=5001;g.observeDraw(a.geometry,a.material,a.mesh);assert.equal(g.finish().reason,'wall-limit');const h=new RenderDispatchAttributionFrame(()=>{throw Error('secret-clock');});assert.equal(h.finish().reason,'invalid-clock');});
test('closed records release source/graph identities and cannot be modified by returned projections',()=>{const f=new RenderDispatchAttributionFrame(()=>0),a=graph();a.mesh.name='private-native-avatar';f.observeDraw(a.geometry,a.material,a.mesh);const before=f.finish();before.owners=900;f.observeDraw(a.geometry,a.material,a.mesh);const after=f.finish();assert.equal(after.owners,1);for(const key of ['owners','materials','geometries','programs','sources','variants'])assert.equal((f as any)[key].size,0);assert.equal(JSON.stringify(after).includes('private-native-avatar'),false);});
function observer(options:{throwOriginal?:boolean;nonWritable?:boolean}={}){let time=0;const abort=new AbortController(),timing=new RenderCpuBreakdown(abort.signal,{sampleEveryFrames:1,now:()=>time,dispatchAttribution:true});const a=graph(),program={},events:unknown[]=[];
 const gl={useProgram(value:unknown){assert.equal(this,gl);events.push(value);time+=.25;return 'driver-result';}};if(options.nonWritable)Object.defineProperty(gl,'useProgram',{writable:false});
 const scene:any={updateMatrixWorld(){},onBeforeRender(){}},camera:any={updateMatrixWorld(){}},renderer:any={getContext(){return gl;},info:{render:{calls:2,triangles:6}},renderBufferDirect(...args:unknown[]){assert.equal(this,renderer);assert.equal(args[2],a.geometry);assert.equal(gl.useProgram(program),'driver-result');if(options.throwOriginal)throw Error('actual-driver-failure');return 'draw-result';}};
 const render=()=>{scene.updateMatrixWorld();camera.updateMatrixWorld();scene.onBeforeRender();assert.equal(renderer.renderBufferDirect(camera,scene,a.geometry,a.material,a.mesh),'draw-result');assert.equal(renderer.renderBufferDirect(camera,scene,a.geometry,a.material,a.mesh),'draw-result');return 'actual-render';};return {abort,timing,a,gl,scene,camera,renderer,render,events};}
const stats=(f:ReturnType<typeof observer>)=>f.timing.snapshot().dispatchAttribution.populations.modelJobsIdle;
test('program boundary wrapper forwards exact arguments/this/return and restores original descriptor with actual draw attribution',()=>{const f=observer(),before=Object.getOwnPropertyDescriptor(f.gl,'useProgram');assert.equal(f.timing.measure(f.renderer,f.scene,f.camera,'modelJobsIdle',f.render),'actual-render');assert.deepEqual(Object.getOwnPropertyDescriptor(f.gl,'useProgram'),before);const p=stats(f);assert.equal(p.completeSamples,1);assert.equal(p.totals.drawsObserved,2);assert.equal(p.totals.programCalls,2);assert.equal(p.totals.programTransitions,0);assert.equal(p.totals.drawsWithObservedProgram,2);f.timing.dispose();});
test('original driver failure propagates unchanged and restores every wrapper with censored attribution',()=>{const f=observer({throwOriginal:true}),original=f.gl.useProgram;assert.throws(()=>f.timing.measure(f.renderer,f.scene,f.camera,'modelJobsIdle',f.render),/actual-driver-failure/);assert.equal(f.gl.useProgram,original);assert.equal(stats(f).reasons['render-failed'],1);f.timing.dispose();});
test('nonwritable program boundary preserves actual renders and refuses attribution only',()=>{const f=observer({nonWritable:true});assert.equal(f.timing.measure(f.renderer,f.scene,f.camera,'modelJobsIdle',f.render),'actual-render');assert.equal(f.events.length,2);assert.equal(stats(f).reasons['installation-refused'],1);assert.equal(f.timing.snapshot().completedFrames,1);f.timing.dispose();});
for(const cause of ['abort','context','foreign'] as const)test(`${cause} invalidates sampled attribution and never clobbers a foreign program hook`,()=>{const f=observer(),original=f.gl.useProgram,foreign=()=> 'foreign';f.timing.measure(f.renderer,f.scene,f.camera,'modelJobsIdle',()=>{f.render();if(cause==='abort')f.abort.abort();else if(cause==='context')f.timing.loseContext();else f.gl.useProgram=foreign as any;});const r=stats(f);assert.equal(r.completeSamples,0);assert.equal(r.censoredSamples,1);assert.equal(f.gl.useProgram,cause==='foreign'?foreign:original);f.timing.dispose();});
test('disabled default never requests a context or installs a program wrapper',()=>{const f=observer();let contexts=0;f.renderer.getContext=()=>{contexts++;throw Error('not-called');};const plain=new RenderCpuBreakdown(f.abort.signal,{sampleEveryFrames:1,now:()=>0});assert.equal(plain.measure(f.renderer,f.scene,f.camera,'modelJobsIdle',f.render),'actual-render');assert.equal(contexts,0);assert.equal(plain.snapshot().dispatchAttribution.enabled,false);plain.dispose();f.timing.dispose();});
test('sample cap and detached aggregate snapshots cannot retain or leak source/graph identities',()=>{const f=observer();for(let i=0;i<514;i++)f.timing.measure(f.renderer,f.scene,f.camera,'modelJobsIdle',f.render);const s=f.timing.snapshot();assert.equal(s.dispatchAttribution.samples,512);assert.equal(s.dispatchAttribution.capacitySkippedSamples,2);(s.dispatchAttribution.populations.modelJobsIdle.totals as any).drawsObserved=99999;assert.equal(f.timing.snapshot().dispatchAttribution.populations.modelJobsIdle.totals.drawsObserved,1024);assert.equal(JSON.stringify(f.timing.snapshot()).includes('uuid'),false);f.timing.dispose();});

test('finished frame actually releases graph/material/texture/source/program owners in an isolated GC subprocess',async()=>{const {spawn}=await import('node:child_process');const child=spawn(process.execPath,['--expose-gc','--import','tsx',new URL('./fixtures/render-dispatch-gc.mjs',import.meta.url).pathname],{stdio:['ignore','pipe','pipe']});let out='',err='';child.stdout.on('data',data=>{out+=data;if(out.length>1024)child.kill();});child.stderr.on('data',data=>{err+=data;if(err.length>4096)child.kill();});const timer=setTimeout(()=>child.kill(),10000);try{const code=await new Promise<number|null>((resolve,reject)=>{child.on('error',reject);child.on('close',resolve);});assert.equal(code,0);assert.equal(err,'');assert.deepEqual(JSON.parse(out),{released:true,observedReferences:6});}finally{clearTimeout(timer);}});


test('source count and charged sampler-key budgets refuse growth without reading image bytes or URLs',()=>{
 const a=graph(),sources=new RenderDispatchAttributionFrame(()=>0);for(let i=0;i<1025;i++){a.material.map=new T.Texture();sources.observeDraw(a.geometry,a.material,a.mesh);}assert.equal(sources.finish().reason,'source-limit');
 const samplers=new RenderDispatchAttributionFrame(()=>0);a.material.map=new T.Texture();for(let i=0;i<2049;i++){Object.defineProperty(a.material.map,'internalFormat',{value:'F'.repeat(64),writable:true,configurable:true});a.material.map.colorSpace='C'.repeat(64);a.material.map.anisotropy=i;samplers.observeDraw(a.geometry,a.material,a.mesh);}const record=samplers.finish();assert.equal(record.reason,'sampler-key-limit');assert.ok(record.samplerKeyBytes<=256*1024);assert.ok(record.sourceSamplerTuples<2048);
});

test('repeated program calls have a hard count bound even with a nonadvancing valid test clock',()=>{const frame=new RenderDispatchAttributionFrame(()=>0),program={};for(let i=0;i<4100;i++)frame.observeProgram(program);const record=frame.finish();assert.equal(record.reason,'program-call-limit');assert.equal(record.programCalls,4096);assert.equal(record.programs,1);});
