// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Authored error/event/filesystem controls only; no browser or server.
import test from'node:test';import assert from'node:assert/strict';import{EventEmitter}from'node:events';import{mkdtemp,readdir,readFile,stat,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{cloneFailureDiagnostic,privateCloneException,observeCloneDriver,evaluateCloneFixture,persistCloneAttempt}from'./integration/replacement-material-clones-diagnostics.mjs';
test('Errors project only fixed classes/reasons and never raw messages, URLs or getters',()=>{
 const secret='https://private.invalid/participant?token=secret';for(const error of [Error(secret),TypeError(secret),RangeError(secret),ReferenceError(secret),SyntaxError(secret),new AggregateError([Error(secret)],secret)]){const out=cloneFailureDiagnostic(error);assert.equal(out.reason,'unclassified');assert(!JSON.stringify(out).includes('private'));assert.deepEqual(Object.keys(out),['errorClass','reason']);}
 const getter={get name(){throw Error('No getter permitted');},get message(){throw Error('No getter permitted');},get matcherResult(){throw Error('No getter permitted');}};assert.deepEqual(cloneFailureDiagnostic(getter),{errorClass:'unclassified',reason:'unclassified'});assert.deepEqual(cloneFailureDiagnostic(new Proxy({}, {getPrototypeOf(){throw Error(secret);},getOwnPropertyDescriptor(){throw Error(secret);}})),{errorClass:'unclassified',reason:'unclassified'});
});
test('Recognized context-loss/target/timeout/assertion distinguish without raw exception',()=>{for(const[error,reason]of [[Error('page.evaluate: Execution context was destroyed '+ 'private-value'),'evaluation-context-destroyed'],[Error('Target page, context or browser has been closed private-value'),'target-closed'],[Object.assign(Error('private-value'),{name:'TimeoutError'}),'deadline'],[Object.assign(Error('private-value'),{matcherResult:{pass:false,actual:'private-value'}}),'registered-assertion-refused']]){assert.equal(cloneFailureDiagnostic(error).reason,reason);assert(!JSON.stringify(cloneFailureDiagnostic(error)).includes('private-value'));}assert.equal(cloneFailureDiagnostic(Error('Execution context was destroyed'+'X'.repeat(8193))).reason,'unclassified');assert.deepEqual(cloneFailureDiagnostic({name:'ReferenceError',message:'private'}),{errorClass:'reference-error',reason:'unclassified'});assert.equal(cloneFailureDiagnostic({name:'private-credential'}).errorClass,'unclassified');});
test('Real EventEmitter event counters are fixed/bounded and detach exact owned listeners',()=>{const page=new EventEmitter(),observer=observeCloneDriver(page);page.emit('framenavigated',{parentFrame:()=>null,url:()=>{throw Error('No URL read');}});page.emit('framenavigated',{parentFrame:()=>({})});page.emit('console',{type:()=> 'error',text:()=>{throw Error('No console text read');}});page.emit('console',{type:()=> 'warning'});page.emit('console',{type:()=> 'debug'});for(let i=0;i<300;i++){page.emit('requestfailed',{});page.emit('pageerror',Error('private-path'));}const out=observer.read();assert.equal(out.mainFrameNavigations,1);assert.equal(out.consoleErrors,1);assert.equal(out.consoleWarnings,1);assert.equal(out.requestFailures,256);assert.equal(out.pageErrorCount,256);assert.equal(out.pageErrorClasses.length,16);assert.equal(out.censored,true);assert(!JSON.stringify(out).includes('private-path'));observer.close();observer.close();for(const name of ['framenavigated','console','requestfailed','pageerror'])assert.equal(page.listenerCount(name),0);out.pageErrorClasses.push('bad');assert.equal(observer.read().pageErrorClasses.length,16);});
test('Observation failures stay fixed and detach failure cannot abort later cleanup',()=>{const page=new EventEmitter(),original=page.off.bind(page),observer=observeCloneDriver(page);page.emit('framenavigated',{parentFrame:()=>{throw Error('private');}});page.emit('console',{type:()=>{throw Error('private');}});page.off=(...args)=>{original(...args);throw Error('private');};observer.close();assert.equal(observer.read().observationRefusals,6);assert.equal(page.listenerCount('pageerror'),0);});
test('Original evaluation succeeds exactly once without changing arguments or outputs',async()=>{const args=[()=>{}, {enabled:false}],record={},value={actual:'owned-report'},page={evaluate:async(...given)=>{assert.equal(given[0],args[0]);assert.equal(given[1],args[1]);return value;}};assert.equal(await evaluateCloneFixture(page,args,record),value);assert.equal(record.lastEvaluation,'evaluate-baseline');assert.equal(record.failureOperation,undefined);});
test('Original failure identity is retained and no retry/replacement occurs',async()=>{for(const enabled of [false,true]){const error=Error('Execution context was destroyed private-url'),record={};let calls=0;const page={evaluate:async()=>{calls++;throw error;}};await assert.rejects(evaluateCloneFixture(page,[()=>{}, {enabled}],record),e=>e===error);assert.equal(calls,1);assert.equal(record.failureOperation,enabled?'evaluate-candidate':'evaluate-baseline');assert.equal(record.failureDiagnostic.reason,'evaluation-context-destroyed');assert(!JSON.stringify(record.failureDiagnostic).includes('private-url'));assert.equal(record.privateException.stackAvailable,true);assert(record.privateException.stack.includes('private-url'));}});
test('Unknown/getter argument classification never invokes its getters or mutates it',async()=>{const arg={get enabled(){throw Error('No classification getter');}},record={},page={evaluate:async(_fn,value)=>{assert.equal(value,arg);return 1;}};assert.equal(await evaluateCloneFixture(page,[()=>{},arg],record),1);assert.equal(record.lastEvaluation,'evaluate-other');});
test('Exclusive UUID attempts preserve first actual report and private permissions',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'owned-clone-report-'));try{const first={completed:false,failurePhase:'registered-test'},second={completed:false,failurePhase:'owned-server'},a=await persistCloneAttempt(directory,'system-chromium',first),b=await persistCloneAttempt(directory,'system-chromium',second),entries=await readdir(directory);assert.equal(entries.length,2);const bytes=[];for(const name of entries){assert(/^[a-f0-9-]{36}$/.test(name));const owned=path.join(directory,name),file=path.join(owned,'system-chromium.private.json');assert.equal((await stat(owned)).mode&0o777,0o700);assert.equal((await stat(file)).mode&0o777,0o600);bytes.push(await readFile(file,'utf8'));}assert(bytes.includes(a)&&bytes.includes(b));await assert.rejects(persistCloneAttempt(directory,'foreign',{}),/Unsupported/);assert.equal((await readdir(directory)).length,2);}finally{await rm(directory,{recursive:true,force:true});}});

test('Exact current fixture refusals produce fixed enums without leaking private stack or messages',()=>{
 const cases=[['Required imported World graph is not ready','fixture-graph-ready-deadline'],['A fixed view changed pixels over actual twenty rendered frames','fixture-unstable-pixels'],['Fixed material/program state changed across genuine rendered frames','fixture-material-program-change'],['Duplicate material disposal','fixture-duplicate-material-disposal'],['Authored triangle center must remain on screen','fixture-projected-triangle-center-offscreen'],['Two genuine imported FBX triangle centers required','fixture-triangle-centers-missing']];
 for(const[message,reason]of cases){const error=Error('page.evaluate: '+message+' private-secret');assert.equal(cloneFailureDiagnostic(error).reason,reason);assert(!JSON.stringify(cloneFailureDiagnostic(error)).includes('private-secret'));}
 assert.equal(cloneFailureDiagnostic(Error('Unrecognized fixture failure')).reason,'unclassified');
});
test('Original native Error/TypeError stack is captured only in explicit private projection',()=>{
 for(const error of [Error('private-url'),TypeError('private-path')]){const stack=error.stack;const result=privateCloneException(error);assert.equal(result.stack,stack);assert.equal(result.stackTruncated,false);assert.equal(result.stackAvailable,true);assert.deepEqual(Object.keys(result),['stackAvailable','stack','stackTruncated']);}
 const error=Error('owned');Object.defineProperty(error,'stack',{value:'x'.repeat(9000)});const result=privateCloneException(error);assert.equal(result.stack.length,8192);assert.equal(result.stackTruncated,true);
 const unicode=privateCloneException({stack:'👋'.repeat(4000)});assert.equal(Buffer.byteLength(unicode.stack),8192);assert.equal(unicode.stackTruncated,true);assert.equal(unicode.stack,'👋'.repeat(2048));
});
test('Private capture refuses hostile getters/custom prototype/changed formatter without evaluating them',()=>{
 let calls=0;const hostile={get stack(){calls++;throw Error('private');}};assert.equal(privateCloneException(hostile).stackAvailable,false);
 const named=Error('private');Object.defineProperty(named,'name',{get(){calls++;throw Error('private');}});assert.equal(privateCloneException(named).stackAvailable,false);
 class Foreign extends Error{}assert.equal(privateCloneException(new Foreign('private')).stackAvailable,false);
 const original=Object.getOwnPropertyDescriptor(Error,'prepareStackTrace');try{Object.defineProperty(Error,'prepareStackTrace',{configurable:true,value:()=>{calls++;return 'private';}});assert.equal(privateCloneException(Error('private')).stackAvailable,false);}finally{if(original)Object.defineProperty(Error,'prepareStackTrace',original);else delete Error.prepareStackTrace;}
 const priorName=Object.getOwnPropertyDescriptor(Error.prototype,'name');try{Object.defineProperty(Error.prototype,'name',{configurable:true,get(){calls++;return 'private';}});assert.equal(privateCloneException(Error('private')).stackAvailable,false);}finally{Object.defineProperty(Error.prototype,'name',priorName);}
 assert.equal(calls,0);assert.equal(privateCloneException(new Proxy({}, {getOwnPropertyDescriptor(){throw Error('private');}})).stackAvailable,false);
});
test('Driver raw-stack plumbing is private-report only and leaves original registered oracles unchanged',async()=>{
 const source=await readFile(new URL('./integration/replacement-material-clones.mjs',import.meta.url),'utf8');
 assert(source.includes('report.privateException=privateCloneException(error)'));const output=source.slice(source.lastIndexOf('if(bytes)console.log'));
 assert(!output.includes('privateException'));assert(!output.includes('stack'));assert(!output.includes('failureDiagnostic'));
});

test('The exact formatter restoration handles supported Node without initial descriptor',async()=>{
 const source=await readFile(new URL('./replacement-material-clones-diagnostics.test.mjs',import.meta.url),'utf8');
 const match=/finally\{(if\(original\)Object\.defineProperty\(Error,'prepareStackTrace',original\);else delete Error\.prepareStackTrace;)\}/.exec(source);assert(match);
 const authoredError={};const restore=new Function('Error','original',match[1]);Object.defineProperty(authoredError,'prepareStackTrace',{configurable:true,value:()=>{}});restore(authoredError,undefined);assert(!Object.hasOwn(authoredError,'prepareStackTrace'));
 const original={configurable:true,value:()=> 'original'};restore(authoredError,original);assert.equal(Object.getOwnPropertyDescriptor(authoredError,'prepareStackTrace').value,original.value);
});
