// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import {BoxGeometry,BufferGeometry,Float32BufferAttribute,Group,Material,Mesh,MeshBasicMaterial,MeshStandardMaterial,Object3D,SkinnedMesh,Texture} from 'three';
import {FBXLoader} from 'three/examples/jsm/loaders/FBXLoader.js';
import {ReplacementMaterialClones} from '../src/replacement-material-clones';
import {ModelResources} from '../src/model-resources';
import {applyNativeMaterialAlpha,hasNativeAlphaShader} from '../src/native-alpha-material';
import {installNativeZeroLightShader,hasNativeZeroLightShader} from '../src/native-zero-lights';
import {fstTextureAdmissionFbx} from './fixtures/fst-texture-admission';
const setup=()=>{const template=new MeshStandardMaterial(),resources=new ModelResources(),bank=new ReplacementMaterialClones(template,resources),geometry=new BoxGeometry();resources.captureMaterial(template);return {template,resources,bank,geometry,mesh:new Mesh(geometry)};};
test('one exact template application reuses at most two vertex-color variants without sharing geometry',()=>{const f=setup(),plain=f.bank.forMesh(f.mesh)!,other=new Mesh(new BoxGeometry());assert.equal(f.bank.forMesh(other),plain);const colored=new Mesh(new BoxGeometry());colored.geometry.setAttribute('color',new Float32BufferAttribute(new Float32Array(24*3),3));const rgb=f.bank.forMesh(colored);assert.notEqual(rgb,plain);assert.equal(rgb?.vertexColors,true);assert.equal(plain.vertexColors,false);colored.geometry.setAttribute('color',new Float32BufferAttribute(new Float32Array(24*4),4));assert.equal(f.bank.forMesh(colored),rgb);assert.deepEqual(f.bank.snapshot(),{created:2,reused:2,refused:0});f.bank.close();f.resources.releaseKeeping();});
test('two models and two ordered applications never share a clone even for the same template',()=>{const f=setup(),second=new ReplacementMaterialClones(f.template,f.resources),a=f.bank.forMesh(f.mesh),b=second.forMesh(f.mesh);assert.notEqual(a,b);f.bank.close();second.close();f.resources.releaseKeeping();});
test('mutating scalar, color and nested metadata invalidates this application instead of using stale clone',()=>{for(const mutate of [(m:MeshStandardMaterial)=>{m.opacity=.3;},(m:MeshStandardMaterial)=>{m.color.r=.3;},(m:MeshStandardMaterial)=>{m.userData.value=2;}]){const f=setup();f.template.userData.value=1;f.bank.close();const bank=new ReplacementMaterialClones(f.template,f.resources);assert.ok(bank.forMesh(f.mesh));mutate(f.template);assert.equal(bank.forMesh(f.mesh),undefined);bank.close();f.resources.releaseKeeping();}});
test('foreign own/inherited mesh callbacks refuse reuse; accessors never execute',()=>{for(const hook of ['onBeforeRender','onAfterRender','onBeforeShadow','onAfterShadow'])for(const inherited of [false,true]){const f=setup();let getters=0;if(inherited){const parent=Object.create(Mesh.prototype);Object.defineProperty(parent,hook,{get(){getters++;return ()=>{};}});Object.setPrototypeOf(f.mesh,parent);}else Object.defineProperty(f.mesh,hook,{get(){getters++;return ()=>{};}});assert.equal(f.bank.forMesh(f.mesh),undefined);assert.equal(getters,0);f.bank.close();f.resources.releaseKeeping();}});
test('foreign own/inherited template hooks and clone methods never execute',()=>{for(const key of ['onBeforeCompile','customProgramCacheKey','onBeforeRender','clone','copy','constructor'])for(const inherited of [false,true]){const f=setup();let calls=0;if(inherited){const parent=Object.create(MeshStandardMaterial.prototype);Object.defineProperty(parent,key,{get(){calls++;return ()=>{calls++;};}});Object.setPrototypeOf(f.template,parent);}else Object.defineProperty(f.template,key,{get(){calls++;return ()=>{calls++;};}});const bank=new ReplacementMaterialClones(f.template,f.resources);assert.equal(bank.forMesh(f.mesh),undefined);assert.equal(calls,0);bank.close();/* Do not feed hostile accessor fixture into baseline ModelResources scanning. */}});
test('foreign data callbacks and subclasses remain separate from trusted built-ins',()=>{const f=setup();f.mesh.onBeforeRender=()=>{};assert.equal(f.bank.forMesh(f.mesh),undefined);f.template.onBeforeCompile=()=>{};assert.equal(new ReplacementMaterialClones(f.template,f.resources).forMesh(new Mesh(f.geometry)),undefined);class Custom extends MeshStandardMaterial{}assert.equal(new ReplacementMaterialClones(new Custom(),f.resources).forMesh(new Mesh(f.geometry)),undefined);f.bank.close();});
test('color/geometry/userData accessors, cyclic or oversized metadata refuse without invoking getters',()=>{for(const mode of ['color','geometry','attribute','userData','cycle','large']as const){const f=setup();let calls=0;if(mode==='color')Object.defineProperty(f.template.color,'r',{get(){calls++;return .4;}});if(mode==='geometry')Object.defineProperty(f.mesh,'geometry',{get(){calls++;return f.geometry;}});if(mode==='attribute')Object.defineProperty(f.geometry.attributes,'color',{get(){calls++;return {};}});if(mode==='userData')Object.defineProperty(f.template.userData,'secret',{enumerable:true,get(){calls++;return true;}});if(mode==='cycle')f.template.userData.cycle=f.template.userData;if(mode==='large')for(let i=0;i<300;i++)f.template.userData['field'+i]=i;const bank=new ReplacementMaterialClones(f.template,f.resources);assert.equal(bank.forMesh(f.mesh),undefined);assert.equal(calls,0);bank.close();}});
test('skinned and morph consumers reuse only material data; actual object shader variants remain independent',()=>{const f=setup(),plain=f.bank.forMesh(f.mesh),skinned=new SkinnedMesh(f.geometry);assert.equal(f.bank.forMesh(skinned),plain);const morphGeometry=f.geometry.clone();morphGeometry.morphAttributes.position=[morphGeometry.attributes.position.clone()];const morph=new Mesh(morphGeometry);assert.equal(f.bank.forMesh(morph),plain);assert.ok(skinned.isSkinnedMesh);assert.equal(morph.geometry.morphAttributes.position!.length,1);f.bank.close();f.resources.releaseKeeping();});
test('actual native mask and zero-light shader registries remain privately owned by the shared clone',async()=>{const f=setup();f.template.map=new Texture();await applyNativeMaterialAlpha(f.template,{useAlpha:true,mode:'OPACITY_MAP_MASK',cutoff:.7});installNativeZeroLightShader(f.template);const bank=new ReplacementMaterialClones(f.template,f.resources),clone=bank.forMesh(f.mesh)!;assert.ok(clone);assert.equal(hasNativeZeroLightShader(clone),true);assert.equal(bank.forMesh(f.mesh),clone);assert.equal(hasNativeZeroLightShader(f.template),true);assert.equal(hasNativeAlphaShader(clone),false);assert.equal(clone.alphaTest,.7);bank.close();f.bank.close();f.resources.releaseKeeping();});
test('one foreign hook replacement after creation refuses later reuse without clobbering the callback',()=>{const f=setup();assert.ok(f.bank.forMesh(f.mesh));const foreign=()=>{};f.template.onBeforeCompile=foreign;assert.equal(f.bank.forMesh(f.mesh),undefined);assert.equal(f.template.onBeforeCompile,foreign);f.bank.close();});
test('cancel and revoked owner assertions propagate and no later clone is published',()=>{const f=setup(),abort=new AbortController(),bank=new ReplacementMaterialClones(f.template,f.resources,abort.signal);const first=bank.forMesh(f.mesh);assert.ok(first);abort.abort();assert.throws(()=>bank.forMesh(f.mesh),{name:'AbortError'});const refusal=new Error('controlled owner revocation'),other=new ReplacementMaterialClones(f.template,f.resources,undefined,()=>{throw refusal;});assert.throws(()=>other.forMesh(f.mesh),e=>e===refusal);assert.equal(other.snapshot().created,0);bank.close();other.close();f.bank.close();f.resources.releaseKeeping();});
test('closed bank owns no disposal authority; retained texture/clone survive until ModelResources release',()=>{const f=setup(),texture=new Texture();f.template.map=texture;const bank=new ReplacementMaterialClones(f.template,f.resources),clone=bank.forMesh(f.mesh)!;let materialDisposals=0,textureDisposals=0;clone.addEventListener('dispose',()=>materialDisposals++);texture.addEventListener('dispose',()=>textureDisposals++);f.mesh.material=clone;const root=new Group();root.add(f.mesh);f.resources.capture(root);bank.close();bank.close();assert.equal(materialDisposals,0);assert.equal(textureDisposals,0);f.resources.releaseKeeping(root);assert.equal(materialDisposals,0);assert.equal(textureDisposals,0);f.resources.releaseKeeping();f.resources.releaseKeeping();assert.equal(materialDisposals,1);assert.equal(textureDisposals,1);});
test('unmatched slot keeps shared maps alive while obsolete templates/clones dispose only once',()=>{const f=setup(),texture=new Texture(),untouched=new MeshBasicMaterial({map:texture});f.template.map=texture;f.resources.captureMaterial(untouched);const bank=new ReplacementMaterialClones(f.template,f.resources),clone=bank.forMesh(f.mesh)!;const root=new Group();f.mesh.material=[clone,untouched];root.add(f.mesh);let disposal=0;texture.addEventListener('dispose',()=>disposal++);f.resources.capture(root);bank.close();f.resources.releaseKeeping(root);assert.equal(disposal,0);f.resources.releaseKeeping();assert.equal(disposal,1);});
test('a genuine production FBXLoader six-vertex/two-material graph gets one exact replacement clone',()=>{const parsed=new FBXLoader().parse(fstTextureAdmissionFbx({withoutOriginalTextures:true}),'');const template=new MeshBasicMaterial({color:0xffffff,toneMapped:false}),resources=new ModelResources(),bank=new ReplacementMaterialClones(template,resources);resources.capture(parsed);resources.captureMaterial(template);let meshCount=0,slotCount=0;parsed.traverse(object=>{if(!(object instanceof Mesh))return;meshCount++;const old=Array.isArray(object.material)?object.material:[object.material];slotCount+=old.length;object.material=old.map(()=>bank.forMesh(object)!);assert.equal(object.geometry.attributes.position.count,6);});assert.equal(meshCount,1);assert.equal(slotCount,2);assert.deepEqual(bank.snapshot(),{created:1,reused:1,refused:0});bank.close();resources.capture(parsed);resources.releaseKeeping(parsed);resources.releaseKeeping();});
