// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import vm from'node:vm';import{readFileSync}from'node:fs';import{stripTypeScriptTypes}from'node:module';
const source=readFileSync(new URL('../src/session.ts',import.meta.url),'utf8');
function load(message=()=>true,wrapper=false){const sockets=[],errors=[];class WS{static OPEN=1;readyState=1;sent=[];closeCalls=[];constructor(){sockets.push(this);}send(text){this.sent.push(JSON.parse(text));}close(...args){this.closeCalls.push(args);}receive(value){this.onmessage({data:JSON.stringify(value)});}}const c={WebSocket:WS,window:{location:{href:'http://owned.invalid'}},URL,TextEncoder,ArrayBuffer,performance:{now:()=>0},setTimeout:()=>1,clearTimeout:()=>{},DOMException};vm.createContext(c);let code=source.replace(/^import .*;\n/gm,'').replace(/^export /gm,'');if(wrapper)code+='\n'+readFileSync(new URL('../src/compressed-color-session.ts',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'');vm.runInContext(stripTypeScriptTypes(code,{mode:'transform'})+'\nglobalThis.Session='+ (wrapper?'CompressedColorSession':'BrowserSession')+';',c);const session=new c.Session({message,audio:()=>{},closed:()=>{},error:e=>errors.push(e)});session.join('overte://owned','visitor');const socket=sockets[0];socket.onopen();return{session,socket,sockets,errors};}
const state=(extra={})=>({type:'state',state:'connecting',sessionId:'owned',avatarConsumption:'ack-v1',...extra,toJSON(){const value={...this};delete value.toJSON;if(value.avatarConsumption==='ack-v1'){value.avatarEpoch=extra.avatarEpoch??(extra.permissionRevision===2?1:0);value.permissionRevision=extra.permissionRevision??1;}return value;}});
const frame=(extra={})=>({type:'avatars',avatars:[{id:'self',position:{x:4,y:1.8,z:2}}],delivery:{version:1,sessionId:'owned',permissionRevision:1,epoch:0,sequence:1,...extra}});
test('actual BrowserSession requests exact capability and ACKs approved-before-connected only after explicit callback success',()=>{let called=0;const x=load(m=>{if(m.type==='avatars')called++;return true;});assert.equal(x.socket.sent[0].avatarConsumption,'ack-v1');x.socket.receive(state());x.socket.receive(frame());assert.equal(called,1);assert.equal(x.session.connected,false);assert.equal(x.socket.sent.at(-1).type,'avatarConsumed');assert.equal(x.socket.sent.at(-1).delivery.sequence,1);assert.equal(x.errors.length,0);});
test('compressed session preserves explicit application callback return',()=>{for(const result of [true,false,undefined,Promise.resolve(true)]){const x=load(()=>result,true);x.socket.receive(state());x.socket.receive(frame());const acks=x.socket.sent.filter(v=>v.type==='avatarConsumed');assert.equal(acks.length,result===true?1:0);assert.equal(x.socket.closeCalls.length,result===true?0:1);}});
test('missing World/false/void/promise and thrown application callback cannot ACK',()=>{for(const result of [false,undefined,Promise.resolve(true),'true']){const x=load(()=>result);x.socket.receive(state());x.socket.receive(frame());assert.equal(x.socket.sent.filter(v=>v.type==='avatarConsumed').length,0);assert.equal(x.socket.closeCalls.length,1);}const x=load(m=>{if(m.type==='avatars')throw Error('fixed');return true;});x.socket.receive(state());x.socket.receive(frame());assert.equal(x.socket.sent.filter(v=>v.type==='avatarConsumed').length,0);assert.equal(x.socket.closeCalls.length,1);});
test('reentrant leave/join cannot ACK through replacement socket',()=>{let x; x=load(m=>{if(m.type==='avatars'){x.session.join('overte://next','visitor');}return true;});x.socket.receive(state());x.socket.receive(frame());assert.equal(x.socket.sent.filter(v=>v.type==='avatarConsumed').length,0);assert.equal(x.sockets[1].sent.filter(v=>v.type==='avatarConsumed').length,0);});
test('same generation reentrant connecting/revision transition revokes ACK eligibility',()=>{let x;x=load(m=>{if(m.type==='avatars')x.socket.receive(state({state:'connected',permissionRevision:2}));return true;});x.socket.receive(state());x.socket.receive(frame());assert.equal(x.socket.sent.filter(v=>v.type==='avatarConsumed').length,0);});
test('callback mutation cannot change captured ACK metadata',()=>{const x=load(m=>{if(m.type==='avatars')m.delivery.sequence=99;return true;});x.socket.receive(state());x.socket.receive(frame());assert.equal(x.socket.sent.at(-1).delivery.sequence,1);});
test('negotiated missing/unknown/duplicate/future-authority metadata refuses without fallback',()=>{for(const mutate of [m=>delete m.delivery,m=>m.delivery.private='no',m=>m.delivery.version=2,m=>m.delivery.sequence=0,m=>m.delivery.sessionId='foreign',m=>m.delivery.epoch=-1]){const x=load();x.socket.receive(state());const m=frame();mutate(m);x.socket.receive(m);assert.equal(x.socket.sent.filter(v=>v.type==='avatarConsumed').length,0);assert.equal(x.socket.closeCalls.length,1);}const x=load();x.socket.receive(state({state:'connected',permissionRevision:1}));x.socket.receive(frame());x.socket.receive(frame());assert.equal(x.socket.sent.filter(v=>v.type==='avatarConsumed').length,1);assert.equal(x.socket.closeCalls.length,1);});
test('explicit old-server legacy state consumes ordinary snapshots without emitting ACK',()=>{const x=load();const m=state();delete m.avatarConsumption;x.socket.receive(m);x.socket.receive({type:'avatars',avatars:frame().avatars});assert.equal(x.errors.length,0);assert.equal(x.socket.sent.filter(v=>v.type==='avatarConsumed').length,0);x.socket.receive(frame());assert.equal(x.socket.closeCalls.length,1);});
test('real main avatar branch only returns success when World consumption completes',()=>{const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8'),start=main.indexOf('function onMessage('),end=main.indexOf('\nconst session =',start+1);assert(start>=0&&end>start);for(const present of [false,true]){let count=0;const c={world:present?{setLocalAvatar:()=>{},setAvatars:()=>{count++;}}:undefined,updateStats:()=>{},avatarCount:0};vm.createContext(c);vm.runInContext(stripTypeScriptTypes(main.slice(start,end),{mode:'transform'})+'\nglobalThis.apply=onMessage;',c);assert.equal(c.apply(frame()),present);assert.equal(count,present?1:0);}});

// These controls preserve the original independent negative records; nested
// failure now deliberately closes current protocol generation with zero ACK.
test('reserved descriptor prevents reentrant duplicate and latches outer failure',()=>{let x,calls=0;x=load(m=>{if(m.type==='avatars'){calls++;if(calls===1)x.socket.receive(frame());}return true;});x.socket.receive(state());x.socket.receive(frame());assert.equal(calls,1);assert.equal(x.socket.sent.filter(v=>v.type==='avatarConsumed').length,0);assert.equal(x.errors.length,1);assert.equal(x.socket.closeCalls.length,1);});
test('retired callback join then throw cannot emit fresh generation error',()=>{let x;x=load(m=>{if(m.type==='avatars'){x.session.join('overte://next','visitor');throw Error('controlled-retired-callback');}return true;});x.socket.receive(state());x.socket.receive(frame());assert.equal(x.errors.length,0);assert.equal(x.sockets[1].closeCalls.length,0);});
test('retired compressed callback throw preserves fresh connected asset approval',()=>{let x,approvalBefore;x=load(m=>{if(m.type==='avatars'){x.session.join('overte://next','visitor');x.sockets[1].receive(state({sessionId:'next',state:'connected',permissionRevision:2,avatarEpoch:1}));approvalBefore=x.session.compressedAssetApproval;throw Error('controlled-retired-callback');}return true;},true);x.socket.receive(state());x.socket.receive(frame());assert.equal(!!approvalBefore,true);assert.equal(!!x.session.compressedAssetApproval,true);assert.equal(x.errors.length,0);});
test('connecting cannot reuse consumed epoch with a newer sequence',()=>{let calls=0;const x=load(m=>{if(m.type==='avatars')calls++;return true;});x.socket.receive(state());x.socket.receive(frame());x.socket.receive(state());x.socket.receive(frame({sequence:2}));assert.equal(calls,1);assert.equal(x.socket.sent.filter(v=>v.type==='avatarConsumed').length,1);assert.equal(x.socket.closeCalls.length,1);});
test('new bound connecting epoch excludes old descriptors and grants approved-before-connected only with exact revision',()=>{const stale=load();stale.socket.receive(state());stale.socket.receive(frame());stale.socket.receive(state({avatarEpoch:1}));stale.socket.receive(frame({sequence:2}));assert.equal(stale.socket.sent.filter(v=>v.type==='avatarConsumed').length,1);assert.equal(stale.socket.closeCalls.length,1);const fresh=load();fresh.socket.receive(state({avatarEpoch:0,toJSON:undefined,permissionRevision:undefined}));assert.equal(fresh.errors.length,0);fresh.socket.receive(state({avatarEpoch:1,permissionRevision:1}));fresh.socket.receive(frame({epoch:1}));assert.equal(fresh.session.connected,false);assert.equal(fresh.socket.sent.filter(v=>v.type==='avatarConsumed').length,1);});
test('missing/lower/fractional/reused revision epochs refuse negotiated state without fallback',()=>{for(const extra of [{avatarEpoch:-1},{avatarEpoch:0.5},{avatarEpoch:undefined,toJSON:undefined,permissionRevision:1}]){const x=load();const value=state();delete value.toJSON;Object.assign(value,extra);x.socket.receive(value);assert.equal(x.socket.closeCalls.length,1);}const x=load();x.socket.receive(state());x.socket.receive(frame());x.socket.receive(state({state:'connected',permissionRevision:2,avatarEpoch:0}));assert.equal(x.socket.closeCalls.length,1);});
