// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {StaticModelMatrices} from '../src/static-model-matrices';
function graph(){const scene=new THREE.Scene(),root=new THREE.Group(),child=new THREE.Group(),mesh=new THREE.Mesh<THREE.BufferGeometry,THREE.MeshStandardMaterial>(new THREE.BoxGeometry(),new THREE.MeshStandardMaterial());scene.add(root);root.add(child);child.add(mesh);root.position.set(2,3,-4);child.rotation.set(.2,.4,-.1);child.scale.set(2,1,-3);mesh.position.set(1,2,3);return{scene,root,child,mesh};}
function state(scene:THREE.Object3D){const result:number[][]=[];scene.traverse(o=>result.push([...o.matrix.elements,...o.matrixWorld.elements]));return result;}
function mutationProof(change:(g:ReturnType<typeof graph>)=>void){const a=graph(),b=graph(),abort=new AbortController(),owner=new StaticModelMatrices(abort.signal);assert.equal(owner.attach(a.root,()=>true),true);a.scene.updateMatrixWorld(true);b.scene.updateMatrixWorld(true);assert.deepEqual(state(a.scene),state(b.scene));change(a);change(b);a.scene.updateMatrixWorld(true);b.scene.updateMatrixWorld(true);assert.deepEqual(state(a.scene),state(b.scene));assert.equal(owner.statistics.updatedTraversals,2);owner.dispose();assert.equal(a.root.updateMatrixWorld,THREE.Object3D.prototype.updateMatrixWorld);assert.deepEqual(owner.statistics.activeRoots,0);assert.equal(owner.statistics.retainedNodes,0);}
test('unchanged owned static subtree skips repeated native-equivalent compose/multiply even under Scene force; snapshots are private copies',()=>{const g=graph(),abort=new AbortController(),owner=new StaticModelMatrices(abort.signal);assert.equal(owner.attach(g.root,()=>true),true);for(let i=0;i<20;i++)g.scene.updateMatrixWorld(true);assert.equal(owner.statistics.updatedTraversals,1);assert.equal(owner.statistics.skippedTraversals,20);assert.equal(g.root.matrixAutoUpdate,true);assert.equal(g.child.matrixWorldAutoUpdate,true);const stats=owner.statistics;stats.retainedNodes=99;assert.equal(owner.statistics.retainedNodes,3);owner.dispose();});
test('root position/quaternion/negative nonuniform scale changes update exact child world matrices',()=>{mutationProof(g=>{g.root.position.x+=1;g.root.rotation.set(.3,-.7,.8);g.root.scale.set(-2,3,.5);});});
test('parent matrix changes cannot reuse obsolete subtree world transforms',()=>{mutationProof(g=>{g.scene.position.x=12;g.scene.rotation.y=.3;g.scene.scale.set(3,-2,.5);});});
test('direct child position/quaternion/scale writes invalidate without requiring browser-owned setters',()=>{mutationProof(g=>{g.child.position.y=7;g.child.rotation.x=.7;g.mesh.scale.z=-4;});});
test('manual matrices and auto flags preserve exact original Three semantics',()=>{mutationProof(g=>{g.child.matrixAutoUpdate=false;g.child.matrix.makeTranslation(9,8,7);g.child.matrixWorldNeedsUpdate=true;});});
test('manual world matrix mutation refreshes automatic matrices instead of presenting unauthorized stale pixels',()=>{mutationProof(g=>{g.mesh.matrixWorld.elements[12]=99;});});
test('new/removed/reparented children and hidden static-batch originals refresh without changing visibility or graph',()=>{mutationProof(g=>{g.mesh.visible=false;g.root.remove(g.child);g.root.add(g.mesh);g.root.add(new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshStandardMaterial()));});});
test('bone/skinned/morph/animation graphs retain ordinary updating path',()=>{for(const change of [(g:ReturnType<typeof graph>)=>g.root.add(new THREE.Bone()),(g:ReturnType<typeof graph>)=>g.root.add(new THREE.SkinnedMesh()),(g:ReturnType<typeof graph>)=>g.mesh.morphTargetInfluences=[0],(g:ReturnType<typeof graph>)=>g.mesh.geometry.morphAttributes.position=[new THREE.Float32BufferAttribute([0,0,0],3)],(g:ReturnType<typeof graph>)=>g.root.animations.push(new THREE.AnimationClip('private',1,[]))]){const g=graph(),owner=new StaticModelMatrices(new AbortController().signal);change(g);assert.equal(owner.attach(g.root,()=>true),false);assert.equal(g.root.updateMatrixWorld,THREE.Object3D.prototype.updateMatrixWorld);assert.equal(owner.statistics.retainedNodes,0);owner.dispose();}});
test('foreign render/update/shader hooks and object subclasses never enter skipped traversal',()=>{for(const change of [(g:ReturnType<typeof graph>)=>g.mesh.onBeforeRender=()=>{},(g:ReturnType<typeof graph>)=>g.child.updateWorldMatrix=()=>{},(g:ReturnType<typeof graph>)=>(g.mesh.material as THREE.Material).onBeforeCompile=()=>{},(g:ReturnType<typeof graph>)=>g.root.add(new THREE.PointLight())]){const g=graph(),owner=new StaticModelMatrices(new AbortController().signal);change(g);assert.equal(owner.attach(g.root,()=>true),false);owner.dispose();}});
test('a newly installed foreign method retires cache and remains owned by its author',()=>{const g=graph(),owner=new StaticModelMatrices(new AbortController().signal);owner.attach(g.root,()=>true);let calls=0;const foreign=function(this:THREE.Object3D,force?:boolean){calls++;THREE.Object3D.prototype.updateMatrixWorld.call(this,force);};g.child.updateMatrixWorld=foreign;g.scene.updateMatrixWorld(true);assert.equal(calls,1);assert.equal(owner.statistics.activeRoots,0);assert.equal(g.child.updateMatrixWorld,foreign);owner.dispose();});
test('actual authority revocation and whole-owner cancellation restore only exact owned root descriptor',()=>{const g=graph(),abort=new AbortController(),owner=new StaticModelMatrices(abort.signal);let current=true;owner.attach(g.root,()=>current);current=false;g.scene.updateMatrixWorld(true);assert.equal(owner.statistics.activeRoots,0);current=true;owner.attach(g.root,()=>current);abort.abort();assert.equal(owner.statistics.retainedNodes,0);assert.equal(g.root.updateMatrixWorld,THREE.Object3D.prototype.updateMatrixWorld);assert.equal(owner.attach(g.root,()=>true),false);});
test('late foreign replacement is never clobbered by cleanup; repeated release/dispose is idempotent',()=>{const g=graph(),owner=new StaticModelMatrices(new AbortController().signal);owner.attach(g.root,()=>true);const foreign=()=>{};g.root.updateMatrixWorld=foreign;owner.release(g.root);owner.release(g.root);owner.dispose();owner.dispose();assert.equal(g.root.updateMatrixWorld,foreign);assert.equal(owner.statistics.retainedNodes,0);});
test('capacity and nonfinite graph refusals preserve complete ordinary graph',()=>{const g=graph(),owner=new StaticModelMatrices(new AbortController().signal);g.child.position.x=Infinity;assert.equal(owner.attach(g.root,()=>true),false);assert.equal(owner.statistics.retainedNodes,0);assert.equal(g.root.children[0],g.child);owner.dispose();const root=new THREE.Group();for(let i=0;i<8192;i++)root.add(new THREE.Group());const bounded=new StaticModelMatrices(new AbortController().signal);assert.equal(bounded.attach(root,()=>true),false);assert.equal(root.children.length,8192);bounded.dispose();});

test('exact owned native alpha hooks remain eligible; mutable foreign shader hooks retire the optional path',async()=>{
 const {applyNativeMaterialAlpha}=await import('../src/native-alpha-material');
 const g=graph(),owner=new StaticModelMatrices(new AbortController().signal);
 (g.mesh.material as THREE.MeshStandardMaterial).map=new THREE.Texture();
 await applyNativeMaterialAlpha(g.mesh.material as THREE.MeshStandardMaterial,{useAlpha:true,mode:'OPACITY_MAP_MASK'});
 assert.equal(owner.attach(g.root,()=>true),true);g.scene.updateMatrixWorld(true);assert(owner.statistics.skippedTraversals>0);
 (g.mesh.material as THREE.Material).onBeforeCompile=()=>{};g.scene.updateMatrixWorld(true);assert.equal(owner.statistics.activeRoots,0);owner.dispose();
});

test('real BVH/capsule contacts and Three picking match ordinary transforms after negative/nonuniform movement',async()=>{
 const {MeshCollision}=await import('../src/mesh-collision');const baseline=graph(),optimized=graph(),owner=new StaticModelMatrices(new AbortController().signal);owner.attach(optimized.root,()=>true);
 for(const g of [baseline,optimized]){g.root.position.set(2,1,-4);g.root.scale.set(-2,3,.5);g.child.rotation.set(0,0,0);g.mesh.position.set(0,0,0);g.mesh.geometry=new THREE.PlaneGeometry(10,10);g.mesh.rotation.x=-Math.PI/2;g.mesh.material.side=THREE.DoubleSide;g.scene.updateMatrixWorld(true);}
 const a=new MeshCollision(baseline.root),b=new MeshCollision(optimized.root);
 try{let contacts=0;for(const position of [new THREE.Vector3(2,1.8,-4),new THREE.Vector3(0,1.8,-3),new THREE.Vector3(2,2,-4)]){
  const first=position.clone(),second=position.clone(),ca=a.resolve(first),cb=b.resolve(second);assert.deepEqual(second.toArray(),first.toArray());assert.deepEqual(cb?.toArray(),ca?.toArray());if(ca)contacts++;
 }
 assert(contacts>0,'Independent real walkable triangle capsule contacts are required');
 const mesh=baseline.mesh.getWorldPosition(new THREE.Vector3()),ray=new THREE.Raycaster(mesh.clone().add(new THREE.Vector3(0,20,0)),new THREE.Vector3(0,-1,0));
 assert(ray.intersectObject(baseline.root,true).length>0,'The independent real floor picking oracle must have hits');
 assert.deepEqual(ray.intersectObject(optimized.root,true).map(hit=>hit.point.toArray()),ray.intersectObject(baseline.root,true).map(hit=>hit.point.toArray()));
 }finally{a.dispose();b.dispose();owner.dispose();}
});
