// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
import {copyCaptureFixtureRow,readCaptureHistoricalPreparer,readCaptureV6History,decodeCaptureV6History,readCaptureV7Source} from './integration/capture-readback-source-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),manifestBytes=await readFile(new URL('./fixtures/capture-fst-escape-v7-complete-source-manifest.json',import.meta.url)),v7=JSON.parse(manifestBytes),oldBytes=await readFile(new URL('./fixtures/capture-world-key-v6-complete-source-manifest.json',import.meta.url)),v6=JSON.parse(oldBytes),prep=await readCaptureHistoricalPreparer(7);
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,preflight=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-fst-escape-guard-'));try{const source=path.join(dir,'browser-client');for(const row of v7.files){if(!row.path.startsWith('browser-client/'))continue;const relative=row.path.slice(15),dest=path.join(source,relative);await mkdir(path.dirname(dest),{recursive:true});await copyCaptureFixtureRow({client,relative,dest,expectedSHA256:row.afterSHA256,version:7});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,manifestBytes);return await fn(source,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(source,proposal)=>preflight(assert,readFile,realpath,lstat,path,sha,source,proposal);
test('v7 validates actual current source and retains every original84 row with only declared migrations',async()=>{const migrations=v7.fstEscapeDerivation.migrations;assert.equal(v6.files.length,84);assert.equal(v7.version,7);assert.equal(sha(oldBytes),v7.fstEscapeDerivation.originalManifestSHA256);for(const r of v6.files){const n=v7.files.filter(x=>x.path===r.path);assert.equal(n.length,1);if(Object.hasOwn(migrations,r.path)){assert.equal(migrations[r.path].beforeSHA256,r.afterSHA256);assert.equal(n[0].afterSHA256,migrations[r.path].afterSHA256);}else assert.deepEqual(n[0],r);}assert.deepEqual(v7.limits,v6.limits);assert.deepEqual(v7.verification,v6.verification);assert.equal(v7.files.length,new Set(v7.files.map(r=>r.path)).size);await fixture(async(s,p)=>assert.equal((await check(s,p)).version,7));});
test('v7 production preparer recovers exact current v6 preparer after one manifest literal',async()=>{const original=await readCaptureHistoricalPreparer(6);assert.equal(prep.split(sha(manifestBytes)).length,2);assert.equal(prep.replace(sha(manifestBytes),sha(oldBytes)),original);});
test('stale v6 manifest refuses before source inspection',async()=>{await fixture(async(s,p)=>{await writeFile(p,oldBytes);let reads=0;const read=async f=>{if(f!==p)reads++;return readFile(f);};await assert.rejects(()=>preflight(assert,read,realpath,lstat,path,sha,s,p));assert.equal(reads,0);});});
for(const relative of ['src/world.ts','src/main.ts','src/fst-definition-lookahead.ts','src/world-source-text-cache.ts','tests/integration/capture-source-fixture.mjs','tests/integration/capture-lookahead-source-fixture.mjs'])test('actual source drift refuses: '+relative,async()=>{await fixture(async(s,p)=>{const f=path.join(s,relative);await writeFile(f,Buffer.concat([await readFile(f),Buffer.from('\n// drift\n')]));await assert.rejects(()=>check(s,p));});});
test('symlink actual compound source refuses',async()=>{await fixture(async(s,p,dir)=>{const f=path.join(s,'src/world.ts'),outside=path.join(dir,'world.ts');await writeFile(outside,await readFile(f));await unlink(f);await symlink(outside,f);await assert.rejects(()=>check(s,p));});});
test('fixed historical input recovery preserves complete World/Main/core/test bytes and preparer',async()=>{const h=await readCaptureV6History();await fixture(async(s,p,dir)=>{for(const relative of Object.keys(h.files).filter(k=>k!=='tests/integration/prepare-tablet-capture-acceptance.mjs')){const dest=path.join(dir,'old-'+relative.replaceAll('/','-'));await copyCaptureFixtureRow({client:s,relative,dest,expectedSHA256:h.files[relative].sha256,version:6});assert.equal(await readFile(dest,'utf8'),h.files[relative].source);await assert.rejects(()=>copyCaptureFixtureRow({client:s,relative,dest,expectedSHA256:h.files[relative].sha256,version:6}));}assert.equal(await readCaptureHistoricalPreparer(6),h.files['tests/integration/prepare-tablet-capture-acceptance.mjs'].source);});});
test('unknown current source cannot use historical recovery',async()=>{const h=await readCaptureV6History();await fixture(async(s,p,dir)=>{await writeFile(path.join(s,'src/world.ts'),'unknown');await assert.rejects(()=>copyCaptureFixtureRow({client:s,relative:'src/world.ts',dest:path.join(dir,'old.ts'),expectedSHA256:h.files['src/world.ts'].sha256,version:6}));});});
test('historical archive is strictly bounded and exact; corrupt or expanded inputs refuse',async()=>{const b=await readFile(new URL('./fixtures/capture-v6-fst-escape-before.json.gz',import.meta.url));assert.equal(Object.keys(decodeCaptureV6History(b).files).length,5);const c=Buffer.from(b);c[c.length-1]^=1;assert.throws(()=>decodeCaptureV6History(c));assert.throws(()=>decodeCaptureV6History(Buffer.alloc(65537)));assert.throws(()=>decodeCaptureV6History(new Uint8Array(b)));});
test('portable Escape control and original v6 assertion bodies remain complete',async()=>{const h=await readCaptureV6History(),current=await readCaptureV7Source('tests/tablet-capture-world-key-manifest.test.mjs');assert.equal(current.replace('./integration/capture-lookahead-source-fixture.mjs','./integration/capture-source-fixture.mjs').replace('await readCaptureHistoricalPreparer(6)',"await readFile(new URL('./integration/prepare-tablet-capture-acceptance.mjs',import.meta.url),'utf8')"),h.files['tests/tablet-capture-world-key-manifest.test.mjs'].source);const oldCore=h.files['tests/integration/capture-source-fixture.mjs'].source,newCore=await readCaptureV7Source('tests/integration/capture-source-fixture.mjs'),oldMainSHA=sha(Buffer.from(h.files['src/main.ts'].source)),newMainSHA=sha(await readFile(new URL('../src/main.ts',import.meta.url)));assert.equal(newCore.split(newMainSHA).length,2);assert.equal(newCore.replace(newMainSHA,oldMainSHA),oldCore);});
test('actual Main constructor enables lookahead only through the explicit reviewed query; full original source recovers',async()=>{const h=await readCaptureV6History(),main=await readFile(new URL('../src/main.ts',import.meta.url),'utf8'),line="            fstDefinitionLookahead: new URLSearchParams(location.search).get('fstDefinitionLookahead') === '1',\n";assert.equal(main.split(line).length,2);assert.equal(main.replace(line,''),h.files['src/main.ts'].source);const expression=line.trim().slice('fstDefinitionLookahead: '.length,-1),resolve=new Function('URLSearchParams','location','return '+expression);for(const search of ['', '?fstDefinitionLookahead=0','?fstDefinitionLookahead=true','?fstDefinitionLookahead=1'])assert.equal(resolve(URLSearchParams,{search}),search.endsWith('=1'));});
