// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';import {createHash} from 'node:crypto';
import {composeCaptureRunner,recoverPttRunner,PTT_RUNNER_SHA256,ADDITIONS} from './integration/tablet-capture-compose.mjs';
import {QUERY,PREFIX,instrumentCaptureAudit,parseCaptureAudit,captureControl,encodeCaptureRecords,gainPoint} from './integration/tablet-capture-audit.mjs';
import {realTrackReadback,captureInstallerSource} from './integration/tablet-capture-browser.mjs';
import {createPeopleFrameAcknowledgement} from './integration/tablet-people-audit.mjs';
import {createPttControlProofQueue} from './integration/tablet-ptt-proof-queue.mjs';
import {createPttTrustedBinding} from './integration/tablet-ptt-trusted-binding.mjs';
import {createPeopleTrustedEventOracle} from './integration/tablet-people-trusted-event-oracle.mjs';
import {assertPaintedPttControl} from './integration/tablet-ptt-audit.mjs';
import {retainCaptureProof,persistCaptureProofs,finishCaptureEvidence} from './integration/tablet-capture-phase.mjs';
import {inactiveCapture} from '../shared/browser-capture.mjs';
const source=await readFile(new URL('./fixtures/capture-original-ptt-20261002.mjs.txt',import.meta.url),'utf8');
const state=()=>({...inactiveCapture(),active:true,controls:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,inputGainPercent:true},settings:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,inputGainPercent:100,inputGain:1}});
const frame={sequence:8,revision:2,navigationSequence:4,width:480,height:706,tabletRect:{x:0,y:0,width:480,height:706}};
const row=()=>({version:1,sequence:8,revision:2,navigationSequence:4,scope:'visitor-capture-controls',nodes:20,truncated:false,rootCount:1,uiEpoch:3,ready:true,awaiting:false,state:state(),controls:[{kind:'echoCancellation',enabled:true,checked:true,rect:{x:20,y:120,width:40,height:18}}]});
const text=r=>PREFIX+JSON.stringify(r);
test('complete original12 PTT source is byte-identical after removing only six reviewed extension anchors',()=>{const combined=composeCaptureRunner(source);assert.equal(recoverPttRunner(combined),source);assert.equal(createHash('sha256').update(source).digest('hex'),PTT_RUNNER_SHA256);assert.throws(()=>composeCaptureRunner(source+'\n'));assert.throws(()=>recoverPttRunner(combined.replace('await runCapturePhase','await inventedPhase')));for(const phrase of ['timeout:90000','timeout:15000','native-to-browser-audio','leave-releases-held-microphone','fresh-session-authority-requires-new-explicit-grant'])assert(combined.includes(phrase));});
test('capture parser clones only exact effective schema and refuses device fields/numeric bounds',()=>{assert.equal(parseCaptureAudit(text(row()))[0].state.settings.inputGain,1);for(const r of [{...row(),privateDevice:'secret'},{...row(),revision:0},{...row(),controls:[{...row().controls[0],privateLabel:'secret'}]},{...row(),state:{...state(),settings:{...state().settings,deviceId:'secret'}}}])assert.throws(()=>parseCaptureAudit(text(r)));assert.throws(()=>parseCaptureAudit('x'.repeat(4*1024*1024+1)));});
test('current control qualification rejects stale navigation, unready, hidden/busy and ambiguous geometry',()=>{assert(captureControl([row()],frame,'echoCancellation',true));for(const r of [{...row(),revision:3},{...row(),navigationSequence:5},{...row(),truncated:true},{...row(),rootCount:2},{...row(),ready:false},{...row(),awaiting:true},{...row(),controls:[row().controls[0],row().controls[0]]},{...row(),controls:[{...row().controls[0],enabled:false}]}])assert.equal(captureControl([r],frame,'echoCancellation',true),null);assert.equal(captureControl([row()],frame,'echoCancellation',false),null);});
test('gain hit derives from the actual native slider rectangle and rejects wrong readback/clipped edge',()=>{const r=row();r.controls=[{kind:'inputGainPercent',enabled:true,checked:null,value:100,rect:{x:20,y:180,width:400,height:2},slider:{rect:{x:20,y:160,width:400,height:40},availableWidth:360,leftPadding:20,rightPadding:20,handleWidth:40,mirrored:false,horizontal:true}}];const p=captureControl([r],frame,'inputGainPercent',100,50);assert.deepEqual(p.rect,{x:132,y:173,width:16,height:16});assert.equal(p.x,140);assert.equal(captureControl([r],frame,'inputGainPercent',50,100),null);r.controls[0].slider.rect.x=-200;assert.equal(captureControl([r],frame,'inputGainPercent',100,50),null);});
test('validated transport retains at most32 native records and rejects unsupported targets',()=>{const records=Array.from({length:33},(_,i)=>({...row(),sequence:i+1}));const parsed=parseCaptureAudit(records.map(text).join('\n'));assert.equal(parsed.length,32);assert.equal(parsed[0].sequence,2);assert.throws(()=>encodeCaptureRecords(records));assert.throws(()=>captureControl([row()],frame,'arbitrary-command',true));});
test('fixed capture QML observer never sets controls or runs arbitrary scripts and supports one bounded query',()=>{for(const bad of ['.checked =','.value =','runJavaScript','sendToQml','Qt.callLater','Settings.setValue'])assert(!QUERY.includes(bad));const qml='    function fromScript(message) {\n                var item=target();activeCapture=message;\n';const observed=instrumentCaptureAudit(qml);assert(observed.includes(PREFIX));assert.throws(()=>instrumentCaptureAudit(observed));assert.throws(()=>instrumentCaptureAudit(qml+qml));});
test('actual query emits only the known wrapper state and visible native switch background',()=>{const item={visible:true,opacity:1,children:[]};const root={parent:item,visible:true,opacity:1,browserUiEpoch:3,browserReady:true,awaiting:false,browserState:state(),children:[]};item.children=[root];const wrapper={parent:root,visible:true,opacity:1,labelTextOn:'Echo Cancellation',checked:true,enabled:true,children:[]};root.children=[wrapper];const background={mapToItem:()=>({x:20,y:120}),width:40,height:18};const control={parent:wrapper,visible:true,opacity:1,checked:true,visualPosition:1,enabled:true,background,indicator:{},children:[]};wrapper.children=[control];const logs=[],ctx={captureAuditCount:0,captureAuditBytes:0,Set,console:{log:s=>logs.push(s)}};vm.createContext(ctx);vm.runInContext(QUERY.slice(QUERY.indexOf('    function captureAudit')),ctx);ctx.captureAudit(item,frame);const r=parseCaptureAudit(logs[0])[0];assert.equal(r.rootCount,1);assert.equal(r.controls.length,1);assert.equal(r.controls[0].kind,'echoCancellation');control.visible=false;ctx.captureAudit(item,frame);assert.equal(parseCaptureAudit(logs[1])[0].controls.length,0);});
test('serialized observer/actual-event binding is syntactically executable without microphone/input calls',async()=>{const installer=await captureInstallerSource();assert(installer.includes('createPeopleTrustedEventOracle'));assert(!installer.includes('getUserMedia('));assert(!installer.includes('applyConstraints('));const ctx={window:{},TextEncoder};vm.createContext(ctx);vm.runInContext(installer,ctx);assert.equal(typeof ctx.window.__captureFactory,'function');});
test('real track readback exports only actual bool processing and never device names/labels',()=>{const old=globalThis.window;try{let calls=0;globalThis.window={__pttAudit:{tracks:[{readyState:'live',getSettings(){calls++;return{echoCancellation:false,noiseSuppression:true,autoGainControl:false,deviceId:'secret',groupId:'secret'};}}],getUserMediaCalls:1}};const r=realTrackReadback();assert.equal(calls,1);assert.deepEqual(r,{active:true,liveTrackCount:1,getUserMediaCalls:1,echoCancellation:false,noiseSuppression:true,autoGainControl:false});assert(!JSON.stringify(r).includes('secret'));window.__pttAudit.tracks[0].readyState='ended';assert.equal(realTrackReadback().active,false);assert.equal(calls,1);}finally{if(old===undefined)delete globalThis.window;else globalThis.window=old;}});
test('new phase has real grant, current correlated ACK, native source attestation and signedPCM gates without setters',async()=>{const phase=await readFile(new URL('./integration/tablet-capture-phase.mjs',import.meta.url),'utf8');for(const s of ["page.locator('#microphone').click()",'getUserMediaCalls===c+1','getSettings()','q.navigationSequence','attestCaptureWorker(profile)','ratio>=.45&&ratio<=.55','getByRole(\'button\',{name:\'Close tablet\'','retire()'])assert(phase.includes(s),s);for(const s of ['applyConstraints(','.gain.value=','sendToQml(','Users.ignore('])assert(!phase.includes(s));});
test('gain physical hit is inverse of pinned Qt positionAt with padding, handle and mirroring, not naive background fraction',()=>{
 const slider={rect:{x:20,y:160,width:400,height:40},availableWidth:360,leftPadding:20,rightPadding:20,handleWidth:40,mirrored:false,horizontal:true};
 const q=50,x=gainPoint(slider,q);assert.equal(x,140);const qt=((x-slider.rect.x-slider.leftPadding-slider.handleWidth/2)/(slider.availableWidth-slider.handleWidth))*200;assert.equal(qt,50);const oldX=20+400*q/200;const oldQt=((oldX-slider.rect.x-slider.leftPadding-slider.handleWidth/2)/(slider.availableWidth-slider.handleWidth))*200;assert.equal(oldQt,37.5);assert.notEqual(Math.round(oldQt),q);
 const mirrored={...slider,mirrored:true},mx=gainPoint(mirrored,q);assert.equal(mx,300);assert.equal((mirrored.rect.width-(mx-mirrored.rect.x)-mirrored.rightPadding-mirrored.handleWidth/2)/(mirrored.availableWidth-mirrored.handleWidth)*200,50);
 for(const s of [{...slider,availableWidth:40},{...slider,horizontal:false},{...slider,handleWidth:Infinity},{...slider,leftPadding:-1},{...slider,privateDevice:'secret'}])assert.throws(()=>gainPoint(s,50));
});
test('originating QML epoch is bounded and zero cannot qualify an active control',()=>{const r=row();r.uiEpoch=0;assert.equal(captureControl([r],frame,'echoCancellation',true),null);r.uiEpoch=2147483648;assert.throws(()=>parseCaptureAudit(text(r)));});
test('actual installed passive factory selects the exact existing native canvas without a DOM write or input',async()=>{const installer=await captureInstallerSource();let selector;const ctx={window:{__pttAudit:{},__captureAudit:{},__pttProofFactory:()=>({})},TextEncoder,document:{querySelector(s){selector=s;return{};},addEventListener(){}},AbortController};vm.runInNewContext(installer,ctx);ctx.window.__captureFactory();assert.equal(selector,'canvas[aria-label="Native tablet apps and dialogs"]');});
test('real worker source attest uses exact v2 generated script/QML/helper and refuses changed bytes or symlinks',async()=>{
 const {mkdtemp,writeFile,rm,symlink}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),path=await import('node:path'),{pathToFileURL}=await import('node:url'),{gunzipSync}=await import('node:zlib');const {buildBrowserCaptureUI}=await import('../gateway/browser-capture-overrides.mjs'),{attestCaptureWorker,captureChannel}=await import('./integration/tablet-capture-worker.mjs');const dir=await mkdtemp(path.join(tmpdir(),'capture-owned-contract-'));
 try{const original=gunzipSync(await readFile(new URL('../gateway/fixtures/native-audio-f91d15a.js.gz',import.meta.url))).toString(),channel='overte.browser.capture.'+'1'.repeat(32),g=buildBrowserCaptureUI(original,channel,pathToFileURL(path.join(dir,'browser-audio.qml')).href),helper=await readFile(new URL('../gateway/native-browser-capture.js',import.meta.url));await writeFile(path.join(dir,'browser-audio.js'),g.script,{mode:0o600});await writeFile(path.join(dir,'browser-audio.qml'),g.qml,{mode:0o600});await writeFile(path.join(dir,'native-browser-capture.js'),helper,{mode:0o600});assert.equal(captureChannel(g.script),channel);assert((await attestCaptureWorker(dir)).exactGeneratedSource);assert.throws(()=>captureChannel(g.script+'\nvar browserCaptureChannel='+JSON.stringify(channel)+',browserCaptureSequence=0,browserCaptureEpoch=0,browserCaptureActive=false;'));await writeFile(path.join(dir,'browser-audio.qml'),g.qml+'\n');await assert.rejects(attestCaptureWorker(dir));await rm(path.join(dir,'browser-audio.qml'));await symlink(path.join(dir,'browser-audio.js'),path.join(dir,'browser-audio.qml'));await assert.rejects(attestCaptureWorker(dir));}finally{await rm(dir,{recursive:true,force:true});}
});

test('exact new-phase observer reset acknowledges a fresh second session and retains stale/undrawn/ambiguous refusal',()=>{
 const originalObserver=createPeopleFrameAcknowledgement(),oldFrame={type:'tablet',kind:'frame',sequence:30,revision:1,navigationSequence:54};
 originalObserver({type:'tablet',action:'open',sequence:54},[]);assert.equal(originalObserver({type:'tablet',action:'frameAck',sequence:55,revision:1,frameSequence:30,navigationSequence:54,displayed:true},[oldFrame]),oldFrame);
 const fresh={type:'tablet',kind:'frame',sequence:1,revision:1,navigationSequence:1};const open={type:'tablet',action:'open',sequence:1},ack={type:'tablet',action:'frameAck',sequence:2,revision:1,frameSequence:1,navigationSequence:1,displayed:true};
 originalObserver(open,[]);assert.equal(originalObserver(ack,[fresh]),null,'counterfactual persistent first-session navigation refuses real new-session frames');for(let sequence=1;sequence<=34;sequence++)assert.equal(originalObserver({...ack,sequence:sequence+1,frameSequence:sequence},[{...fresh,sequence}]),null,'all34 actual second-session capture ordinals remain below the retained old navigation');
 const reset=ADDITIONS[3].after.split('\n')[1];assert.equal(reset," await page.evaluate('window.__pttFrameAck=('+createPeopleFrameAcknowledgement.toString()+')();');");
 let evaluateCalls=0;const window={__pttFrameAck:originalObserver},c={window,createPeopleFrameAcknowledgement,page:{evaluate(code){evaluateCalls++;return vm.runInNewContext(code,{window});}}};vm.runInNewContext(reset.trim().replace(/^await /,''),c);assert.equal(evaluateCalls,1);const observe=window.__pttFrameAck;observe(open,[]);assert.equal(observe(ack,[fresh]),fresh);
 for(const change of [{displayed:false},{revision:2},{navigationSequence:54},{frameSequence:30},{sequence:1}])assert.equal(observe({...ack,...change},[fresh]),null);assert.equal(observe(ack,[fresh,{...fresh}]),null);
 const combined=composeCaptureRunner(source);const originalGate=combined.indexOf("await checkpoint('fresh-session-authority-requires-new-explicit-grant'");assert(originalGate>=0&&combined.indexOf(reset,originalGate)>originalGate);assert.equal(recoverPttRunner(combined),source);
});

function queueFixture(){const previous=globalThis.window,frame={sequence:8,revision:2,navigationSequence:4,width:480,height:706},point={sequence:8,revision:2,navigationSequence:4};const rgba=Array.from({length:8*8*4},(_,i)=>i%4===3?255:i%8<4?0:255);globalThis.window={__pttAudit:{frame},__captureAudit:{}};const sample=()=>({refusal:null,frame:{...frame},canvas:{width:480,height:706},image:{width:8,height:8,rgba},nativePNG:'AQ=='}),queue=createPttControlProofQueue(sample,assertPaintedPttControl),events=[];window.__captureAudit.proofs=queue;window.__captureAudit.trusted={readProofMetadata:()=>events,forgetProof:()=>{},retire:()=>{}};const page={evaluate:async(fn,arg)=>fn(arg)};return{queue,point,events,page,close(){queue.retire();if(previous===undefined)delete globalThis.window;else globalThis.window=previous;}};}
async function proofDirectory(run){const {mkdtemp,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),path=await import('node:path');const d=await mkdtemp(path.join(tmpdir(),'capture-proof-ownership-'));try{return await run(d);}finally{await rm(d,{recursive:true,force:true});}}
test('actual trusted prepare allocates an otherwise unexported queue proof; new persistence owns and releases it',()=>proofDirectory(async directory=>{const f=queueFixture();try{const binding=createPttTrustedBinding({canvas:{},audit:{proofs:f.queue,frame:window.__pttAudit.frame,navigation:4},parseAudit:()=>[{sequence:8,revision:2,navigationSequence:4,nativeBuildVersion:'f91'}],pttControl:()=>({...f.point,rect:{x:20,y:20,width:8,height:8}}),createOracle:createPeopleTrustedEventOracle,isActive:()=>true,document:{addEventListener(){}},AbortController,TextEncoder});const preparation=binding.prepare({kind:'audio-app'},'[]');assert.equal(preparation.refusal,null);assert.equal(f.queue.metadata().count,1);assert.deepEqual(binding.readProofMetadata(),[],'legacy physical metadata omits the allocated preparation');window.__captureAudit.trusted=binding;const owned=new Map();retainCaptureProof(owned,preparation.sample);await persistCaptureProofs({page:f.page,directory,proofs:owned});assert.deepEqual(f.queue.metadata(),{ordinals:[],count:0,bytes:0});assert.equal(owned.size,0);binding.retire();const {stat}=await import('node:fs/promises');assert.equal((await stat(directory+'/capture-control-1.png')).mode&0o777,0o600);}finally{f.close();}}));
test('preparation and physical-event proofs both persist exact pixels before individual release',()=>proofDirectory(async directory=>{const f=queueFixture();try{const prep=f.queue.sample({},f.point),event=f.queue.sample({},f.point);f.events.push(event);const owned=new Map();retainCaptureProof(owned,prep);assert.equal(f.events.length,1);assert.equal(f.queue.metadata().count,2,'legacy event-only ownership leaves one real allocation');await persistCaptureProofs({page:f.page,directory,proofs:owned});assert.equal(f.queue.metadata().bytes,0);assert.equal(owned.size,0);const {readFile}=await import('node:fs/promises');assert.deepEqual(await readFile(directory+'/capture-control-1.png'),Buffer.from([1]));assert.deepEqual(await readFile(directory+'/capture-control-2.png'),Buffer.from([1]));}finally{f.close();}}));
test('unknown queue allocation remains a strict failure rather than silently exported or discarded',()=>proofDirectory(async directory=>{const f=queueFixture();try{f.queue.sample({},f.point);await assert.rejects(persistCaptureProofs({page:f.page,directory,proofs:new Map()}),/Every allocated/);assert.equal(f.queue.metadata().count,1);}finally{f.close();}}));
test('node evidence repeats the original painted assertion and cannot release an unpainted proof',()=>proofDirectory(async directory=>{const f=queueFixture();try{const sample=f.queue.sample({},f.point),owned=new Map();retainCaptureProof(owned,sample);const page={evaluate:async(fn,arg)=>{const r=await f.page.evaluate(fn,arg);if(fn.toString().includes('proofs.read(id)'))r.image.rgba.fill(0);return r;}};await assert.rejects(persistCaptureProofs({page,directory,proofs:owned}),/painted visible contrast/);assert.equal(f.queue.metadata().count,1);}finally{f.close();}}));
test('duplicate event metadata at the16-proof boundary retains bounds without a false overflow',()=>{const f=queueFixture();try{const owned=new Map();let last;for(let i=0;i<16;i++){last=f.queue.sample({},f.point);retainCaptureProof(owned,last);}retainCaptureProof(owned,last);assert.equal(owned.size,16);assert.throws(()=>f.queue.sample({},f.point),/count bound/);assert.throws(()=>retainCaptureProof(owned,{...last,proofOrdinal:17}));}finally{f.close();}});
test('cleanup preserves the original error while separately retaining both cleanup errors privately',()=>proofDirectory(async directory=>{const primary=new Error('AUTHORED_PRIMARY'),save=new Error('AUTHORED_SAVE'),retire=new Error('AUTHORED_RETIRE'),report={};let retirement=0;async function actualFlow(){try{throw primary;}finally{await finishCaptureEvidence({report,directory,primaryFailed:true,saveProofs:async()=>{throw save;},retire:async()=>{retirement++;throw retire;}});}}await assert.rejects(actualFlow(),e=>e===primary);assert.equal(retirement,1);assert.equal(report.captureCleanupFailureCount,2);assert.equal(report.captureObserverRetired,false);assert.equal(report.capturePrimaryFailurePreserved,true);const {readFile,stat}=await import('node:fs/promises');const text=await readFile(directory+'/capture-cleanup-failure.private.txt','utf8');assert(text.includes('AUTHORED_SAVE')&&text.includes('AUTHORED_RETIRE'));assert(text.length<65536);assert.equal((await stat(directory+'/capture-cleanup-failure.private.txt')).mode&0o777,0o600);}));
test('without a primary failure cleanup still fails closed and retirement follows a save failure',()=>proofDirectory(async directory=>{const save=new Error('AUTHORED_SAVE'),report={};let retired=0;await assert.rejects(finishCaptureEvidence({report,directory,primaryFailed:false,saveProofs:async()=>{throw save;},retire:async()=>{retired++;}}),e=>e===save);assert.equal(retired,1);assert.equal(report.captureObserverRetired,true);assert.equal(report.capturePrimaryFailurePreserved,false);}));

test('fifth exact extension retains original filenames until the post12 capture phase',()=>{assert.equal(ADDITIONS.length,6);const anchor=ADDITIONS[4];assert.equal(anchor.before,"file:path.join(directory,'native-trusted-'+sample.kind+'-'+sample.proofOrdinal+'.png')");const combined=composeCaptureRunner(source),gate=combined.indexOf("await checkpoint('fresh-session-authority-requires-new-explicit-grant'");const phase=combined.indexOf(' report.captureProofPhase=true;',gate);assert(gate>=0&&phase>gate&&phase<combined.indexOf(' await audioApp(false);',phase));assert.equal(combined.slice(0,gate).includes('report.captureProofPhase=true'),false);assert.equal(recoverPttRunner(combined),source);});
test('two real queues repeating ordinal2 use distinct exclusive private filenames without overwrite or retry',()=>proofDirectory(async directory=>{const {writeFile,readFile,stat}=await import('node:fs/promises'),path=await import('node:path');const f=queueFixture();try{const filename=(report,sample,after=true)=>vm.runInNewContext((after?ADDITIONS[4].after:ADDITIONS[4].before).slice('file:'.length),{directory,path,report,sample});const firstQueue=f.queue;firstQueue.sample({},f.point);const first=firstQueue.sample({},f.point);assert.equal(first.proofOrdinal,2);const firstName=filename({}, {...first,kind:'audio-app'});assert.equal(firstName,filename({}, {...first,kind:'audio-app'},false));assert.equal(path.basename(firstName),'native-trusted-audio-app-2.png');await writeFile(firstName,Buffer.from([1]),{flag:'wx',mode:0o600});firstQueue.retire();const second=createPttControlProofQueue(()=>({refusal:null,frame:{...window.__pttAudit.frame},canvas:{width:480,height:706},image:{width:8,height:8,rgba:Array.from({length:256},(_,i)=>i%4===3?255:i%8<4?0:255)},nativePNG:'Ag=='}),assertPaintedPttControl);try{second.sample({},f.point);const next=second.sample({},f.point);assert.equal(next.proofOrdinal,2);const sample={...next,kind:'audio-app'};await assert.rejects(writeFile(filename({},sample),Buffer.from([2]),{flag:'wx',mode:0o600}),e=>e.code==='EEXIST','counterfactual old phase overwrites are refused');const secondName=filename({captureProofPhase:true},sample);assert.notEqual(secondName,firstName);assert.equal(path.basename(secondName),'capture-native-trusted-audio-app-2.png');await writeFile(secondName,Buffer.from([2]),{flag:'wx',mode:0o600});for(const file of [firstName,secondName]){await assert.rejects(writeFile(file,Buffer.from([3]),{flag:'wx',mode:0o600}),e=>e.code==='EEXIST');assert.equal((await stat(file)).mode&0o777,0o600);}assert.deepEqual(await readFile(firstName),Buffer.from([1]));assert.deepEqual(await readFile(secondName),Buffer.from([2]));assert.equal(filename({captureProofPhase:1},sample),firstName);}finally{second.retire();}}finally{f.close();}}));
