// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import {copyCaptureFixtureRow,readCaptureHistoricalPreparer} from './integration/capture-source-fixture.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,rm,cp,mkdir,unlink,symlink,lstat,realpath} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {recoverCaptureV10Input} from './integration/capture-environment-source-fixture.mjs';
// CPU history only: actual canonical metadata remains checked before exact byte recovery.
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV10Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
const sha=b=>createHash('sha256').update(b).digest('hex');
const client=fileURLToPath(new URL('../',import.meta.url)),current=await readFile(new URL('./fixtures/capture-reacquisition-v5-complete-source-manifest.json',import.meta.url)),prior=await readFile(new URL('./fixtures/layout-v4-gzip-complete-source-manifest.json',import.meta.url)),v4=JSON.parse(prior),v5=JSON.parse(current),candidate=await readCaptureHistoricalPreparer(5),historical=await readFile(new URL('./fixtures/capture-reacquisition-v4-prepare.mjs.txt',import.meta.url),'utf8');
const a=candidate.indexOf('const manifestBytes=await readFile(proposal);'),z=candidate.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,preflight=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',candidate.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-v5-guard-'));try{const source=path.join(dir,'browser-client');for(const row of v5.files){if(!row.path.startsWith('browser-client/'))continue;const relative=row.path.slice(15),dest=path.join(source,relative);await mkdir(path.dirname(dest),{recursive:true});await copyCaptureFixtureRow({client,relative,dest,expectedSHA256:row.afterSHA256,version:5});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,current);return await fn(source,proposal);}finally{await rm(dir,{recursive:true,force:true});}}
test('v5 changes only the pinned preparer literal and recovers the complete historical gzip preparer',()=>{assert.equal(candidate.replace(sha(current),sha(prior)),historical);assert.equal(candidate.split(sha(current)).length,2);assert.equal(v5.version,5);assert.equal(v5.reacquisitionDerivation.previousCompleteManifestSHA256,sha(prior));});
test('v5 preserves every historical gate and row except the four explicitly declared current-source migrations',()=>{const expected=structuredClone(v4);expected.version=5;expected.scope=v5.scope;expected.reacquisitionDerivation=v5.reacquisitionDerivation;for(const key of ['browser-client/src/audio.ts','browser-client/src/browser-capture-target.ts','browser-client/src/browser-capture-audio.test.ts','browser-client/tests/tablet-capture-layout-manifest.test.mjs']){const old=expected.files.find(v=>v.path===key),next=v5.files.find(v=>v.path===key);assert(old&&next);old.afterSHA256=next.afterSHA256;old.bytes=next.bytes;}expected.files.push(...v5.files.slice(v4.files.length));assert.deepEqual(v5,expected);assert.equal(v4.files.length,38);assert.equal(v5.files.length,56);for(const key of ['dependencyPins','packagePins','limits','verification','followupManifestSHA256','historicalManifestSHA256','historicalPatchSHA256','layoutDerivation','styleDerivation','gzipGoldDerivation'])assert.deepEqual(v5[key],v4[key]);assert.equal(v5.reacquisitionDerivation.actualCaptureReacquisitionQualified,false);assert.equal(v5.reacquisitionDerivation.original12BodySHA256,'6dec42866e6818b1595840e4ccf517f1a56888d8752a3cfe197c0625f6996e3f');});
test('v5 actual pre-copy guard accepts only the exact source image without side effects',()=>fixture(async(source,p)=>{assert.deepEqual(await preflight(assert,readFile,realpath,lstat,path,sha,source,p),v5);}));
test('historical, invented and altered manifests refuse before any client source read',()=>fixture(async(source,p)=>{for(const bytes of [prior,await readFile(new URL('./fixtures/layout-v4-complete-source-manifest.json',import.meta.url)),Buffer.from(JSON.stringify({...v5,version:4})),Buffer.from(JSON.stringify({...v5,files:[]}))]){await writeFile(p,bytes);let reads=0;await assert.rejects(preflight(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,source,p));assert.equal(reads,0);}}));
test('old Audio, old Target, modified observer and symlink aliases refuse the unchanged current source guard',()=>fixture(async(source,p)=>{for(const [relative,old] of [['src/audio.ts','capture-reacquisition-v4-audio.ts.txt'],['src/browser-capture-target.ts','capture-reacquisition-v4-target.ts.txt']]){const f=path.join(source,relative),saved=await readFile(f);await writeFile(f,await readFile(new URL('./fixtures/'+old,import.meta.url)));await assert.rejects(preflight(assert,readFile,realpath,lstat,path,sha,source,p),/Exact reviewed capture composition required/);await writeFile(f,saved);}const f=path.join(source,'tests/integration/tablet-capture-reacquisition-observer.mjs'),saved=await readFile(f);await writeFile(f,Buffer.concat([saved,Buffer.from('\n')]));await assert.rejects(preflight(assert,readFile,realpath,lstat,path,sha,source,p),/Exact reviewed capture composition required/);await unlink(f);const alias=path.join(source,'observer-copy.mjs');await writeFile(alias,saved);await symlink(alias,f);await assert.rejects(preflight(assert,readFile,realpath,lstat,path,sha,source,p));}));

test('the current twenty Google Chrome environment files match the separately reviewed complete composition',async()=>{const pins=v5.reacquisitionDerivation.chromeEnvironmentSourcePins;assert.equal(Object.keys(pins).length,20);assert.equal(v5.reacquisitionDerivation.chromeEnvironmentReviewManifestSHA256,'018b85156521d62be8bf9c7c58be469c38cfe89b17fff837ebe2e014c76ccf89');for(const [relative,hash] of Object.entries(pins)){assert(relative.startsWith('browser-client/')||relative==='.github/workflows/browser-client.yml');assert(!relative.split('/').includes('..'));const file=path.join(client,'..',relative);assert((await lstat(file)).isFile());assert.equal(await realpath(file),file);assert.equal(sha(await readFile(file)),hash);}});
