// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
import {readCaptureV11Source,recoverCaptureV11Input} from './integration/capture-loading-source-fixture.mjs';
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV11Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
import {readCaptureV10History,readCaptureV10Source,decodeCaptureV10History,recoverCaptureV10Input} from './integration/capture-environment-source-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.join(client,'..'),bytes=await readFile(new URL('./fixtures/capture-environment-v11-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-reconnect-v10-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readCaptureV11Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,sourceCheck=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-environment-guard-'));try{const source=path.join(dir,'browser-client');for(const r of m.files){if(!r.path.startsWith('browser-client/'))continue;const relative=r.path.slice(15),dest=path.join(source,relative);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(client,relative)),{mode:0o600,flag:'wx'});}for(const name of Object.keys(m.environmentReconciliationDerivation.externalMigrations)){const dest=path.join(dir,name);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,name)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(source,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>sourceCheck(assert,readFile,realpath,lstat,path,sha,s,p);
test('v11 preserves all126 rows and declares only three CPU migrations plus four added rows',()=>{
 assert.equal(sha(oldBytes),'fc6e6b881054ebb5f010e885ad43a2a05490ae03a06d411e3f9a9c82c8bcc602');assert.equal(old.files.length,126);assert.equal(m.version,11);const d=m.environmentReconciliationDerivation;assert.equal(d.previousManifestSHA256,sha(oldBytes));assert.equal(m.files.length,130);assert.equal(m.files.length,new Set(m.files.map(r=>r.path)).size);
 for(const row of old.files){const n=m.files.filter(r=>r.path===row.path);assert.equal(n.length,1);if(d.fixtureMigrations[row.path]){const v=d.fixtureMigrations[row.path];assert.equal(v.beforeSHA256,row.afterSHA256);assert.equal(n[0].beforeSHA256,row.afterSHA256);assert.equal(n[0].afterSHA256,v.afterSHA256);}else assert.deepEqual(n[0],row);}
 for(const k of ['limits','verification','packagePins','dependencyPins','reconnectDerivation'])assert.deepEqual(m[k],old[k]);assert.equal(Object.keys(d.externalMigrations).length,2);assert.equal(Object.keys(d.fixtureMigrations).length,3);assert.equal(d.addedRows.length,4);
 const expected=structuredClone(old);expected.version=m.version;expected.scope=m.scope;expected.files=m.files;expected.reacquisitionDerivation.chromeEnvironmentSourcePins['.github/workflows/browser-client.yml']=d.externalMigrations['.github/workflows/browser-client.yml'].afterSHA256;expected.statusChromeDerivation.documentationPins['browser-client/lab/README.md']={beforeSHA256:d.externalMigrations['browser-client/lab/README.md'].beforeSHA256,afterSHA256:d.externalMigrations['browser-client/lab/README.md'].afterSHA256};expected.environmentReconciliationDerivation=d;assert.deepEqual(m,expected);
});
test('production preparer whole-before recovers two exact insertions and imports no history',async()=>{const oldPrep=await readCaptureV10Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs'),block=m.environmentReconciliationDerivation.productionEnvironmentGuard;assert.equal(prep.split(sha(bytes)).length,2);assert.equal(prep.split(block).length,2);assert.equal(prep.replace(sha(bytes),sha(oldBytes)).replace(block,''),oldPrep);assert.equal(sha(Buffer.from(oldPrep)),'d04b297ab5051de714bca86556c66a2fc0527da1612027127894f08300c34ae7');assert(!prep.includes('capture-environment-source-fixture'));});
test('actual extracted production gate accepts current130 and both reviewed external inputs',()=>fixture(async(s,p)=>assert.equal((await check(s,p)).version,11)));
test('historical or invented manifests refuse before current client or external source reads',()=>fixture(async(s,p)=>{for(const data of [oldBytes,Buffer.from(JSON.stringify({...m,version:10})),Buffer.from(JSON.stringify({...m,files:[]}))]){await writeFile(p,data);let reads=0;await assert.rejects(()=>sourceCheck(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}}));
test('every fixture migration and appended row still refuses unknown byte changes',()=>fixture(async(s,p)=>{const d=m.environmentReconciliationDerivation;for(const name of [...Object.keys(d.fixtureMigrations),...d.addedRows]){const file=path.join(s,name.slice(15)),b=await readFile(file);await writeFile(file,Buffer.concat([b,Buffer.from('\n')]));await assert.rejects(()=>check(s,p),/Exact reviewed capture composition required/);await writeFile(file,b);}}));
test('whole previous workflow and README and unknown drift refuse current external source gates',()=>fixture(async(s,p,dir)=>{for(const name of Object.keys(m.environmentReconciliationDerivation.externalMigrations)){const file=path.join(dir,name),b=await readFile(file);for(const wrong of [Buffer.from(await readCaptureV10Source(name)),Buffer.concat([b,Buffer.from('\n')])]){await writeFile(file,wrong);await assert.rejects(()=>check(s,p),/Exact reviewed capture environment required/);}await writeFile(file,b);}}));
test('outside metadata symlink aliases remain refused despite exact bytes',async()=>{for(const name of Object.keys(m.environmentReconciliationDerivation.externalMigrations))await fixture(async(s,p,dir)=>{const file=path.join(dir,name),b=await readFile(file),other=path.join(dir,'alias');await writeFile(other,b);await unlink(file);await symlink(other,file);await assert.rejects(()=>check(s,p));});});
test('all seven whole-before inputs immutable and exact; unknown mutants and archive bounds refuse',async()=>{const h=await readCaptureV10History();assert.equal(Object.keys(h.files).length,7);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const [name,row]of Object.entries(h.files)){assert(Object.isFrozen(row));assert.equal(sha(Buffer.from(row.source)),row.sha256);assert.equal(await readCaptureV10Source(name),row.source);}for(const name of [...Object.keys(m.environmentReconciliationDerivation.externalMigrations),...Object.keys(m.environmentReconciliationDerivation.fixtureMigrations)]){const b=await readFile(path.join(root,name));assert.equal((await recoverCaptureV10Input(name,b)).toString(),h.files[name].source);await assert.rejects(()=>recoverCaptureV10Input(name,Buffer.concat([b,Buffer.from('\n')])));}const b=await readFile(new URL('./fixtures/capture-v10-environment-before.json.gz',import.meta.url)),wrong=Buffer.from(b);wrong[wrong.length-1]^=1;assert.throws(()=>decodeCaptureV10History(wrong));assert.throws(()=>decodeCaptureV10History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV10History(new Uint8Array(b)));await assert.rejects(()=>readCaptureV10Source('unknown'));});
test('historical v10 and v5 assertion bodies remain byte-identical after fixture-only plumbing',async()=>{for(const name of ['browser-client/tests/tablet-capture-reconnect-manifest.test.mjs','browser-client/tests/tablet-capture-reacquisition-manifest.test.mjs']){const before=await readCaptureV10Source(name),after=await readFile(path.join(root,name),'utf8');assert.equal(after.slice(after.indexOf("test('")),before.slice(before.indexOf("test('")));}});
test('old20ce production receipt and outside Micdoc row remain honest historical inputs',()=>{const d=m.environmentReconciliationDerivation;assert.equal(d.oldProductionReceiptSHA256,'20cedb53d46a8b8b123b82bb385b6b380458c08cdaaa98256d506e97f0fc0212');assert.equal(d.actualProductionBuildQualified,false);assert.equal(d.actualNativeOrBrowserQualified,false);assert.equal(d.productionHistoricalFallback,false);assert.deepEqual(m.files.find(r=>r.path==='docs/browser-client/BROWSER_MICROPHONE_CONTROLS.md'),old.files.find(r=>r.path==='docs/browser-client/BROWSER_MICROPHONE_CONTROLS.md'));assert.equal(m.reconnectDerivation.preexistingOutsideClientDocumentationSHA256,'a01bc236eef5b602b695b0f0aa52d38004a0ba43e17519375b1eec4e49ae58d5');});
