// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Current production admission and exact CPU history are tested separately.
import test from 'node:test';import assert from 'node:assert/strict';import {readFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink,link,chmod}from'node:fs/promises';import path from'node:path';import{fileURLToPath}from'node:url';import{tmpdir}from'node:os';import{createHash}from'node:crypto';
import{readCaptureV27History,readCaptureV27Source,recoverCaptureV27Input,decodeCaptureV27History,readCurrentAvatarFlowSource}from'./integration/capture-avatar-flow-source-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.dirname(client),bytes=await readFile(new URL('./fixtures/capture-avatar-flow-v28-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-software-managed-v27-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readFile(new URL('./integration/prepare-tablet-capture-acceptance.mjs',import.meta.url),'utf8'),d=m.avatarFlowDerivation;
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,gate=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-software-managed-'));try{const s=path.join(dir,'browser-client');for(const row of m.files){const dest=path.join(dir,row.path);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,row.path)),{mode:0o600,flag:'wx'});}for(const relative of ['.github/workflows/browser-client.yml','browser-client/lab/README.md']){const dest=path.join(dir,relative);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,relative)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(s,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>gate(assert,readFile,realpath,lstat,path,sha,s,p);
test('V28 retains every V27 row with honest finite source migrations and new admissions',()=>{assert.equal(m.version,28);assert.equal(old.version,27);assert.equal(old.files.length,241);assert.equal(m.files.length,241+d.addedRows.length);assert.equal(d.previousManifestSHA256,sha(oldBytes));assert.equal(new Set(m.files.map(r=>r.path)).size,m.files.length);for(const row of old.files){const change=d.sourceMigrations[row.path];assert.deepEqual(m.files.find(r=>r.path===row.path),change?{...row,beforeSHA256:row.afterSHA256,afterSHA256:change.afterSHA256,bytes:change.bytes}:row);}for(const n of d.addedRows){assert(!old.files.some(r=>r.path===n));assert.equal(m.files.find(r=>r.path===n).beforeSHA256,null);}const expected=structuredClone(old);expected.version=28;expected.scope=m.scope;expected.files=m.files;expected.avatarFlowDerivation=d;Object.assign(expected.reacquisitionDerivation.chromeEnvironmentSourcePins,d.chromeEnvironmentMigrations);assert.deepEqual(m,expected);assert.equal(d.actualRuntimeAcceptance,false);assert.equal(d.productionHistoryFallback,false);});
test('actual current production gate validates current rows and external workflow without expanding lab admission',()=>fixture(async(s,p)=>{assert.equal((await check(s,p)).version,28);assert(prep.includes('(?:src|shared|gateway|tests|native-input|tools)'));assert(!prep.includes('recoverCapture'));assert(!prep.includes('source-fixture'));assert(!m.files.some(r=>r.path.startsWith('browser-client/lab/')));}));
test('entire V27 old version and unknown newline manifest refuse before any source reads',()=>fixture(async(s,p)=>{for(const input of [oldBytes,Buffer.from(JSON.stringify({...m,version:27})),Buffer.concat([bytes,Buffer.from('\n')])]){await writeFile(p,input);let reads=0;await assert.rejects(()=>gate(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}}));
test('all changed or added current rows and workflow refuse drift old missing and symlink files',()=>fixture(async(s,p,dir)=>{const h=await readCaptureV27History();for(const n of [...Object.keys(d.sourceMigrations),...d.addedRows,'.github/workflows/browser-client.yml']){const f=path.join(dir,n),current=await readFile(f);await writeFile(f,Buffer.concat([current,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));if(Object.hasOwn(h.files,n)&&h.files[n].sha256!==sha(current)){await writeFile(f,await readCaptureV27Source(n));await assert.rejects(()=>check(s,p));}await unlink(f);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'alias');await writeFile(alias,current);await symlink(alias,f);await assert.rejects(()=>check(s,p));await unlink(f);await unlink(alias);await writeFile(f,current);}}));
test('production preparer changes exactly one manifest literal and imports no history',async()=>{const before=await readCaptureV27Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.split(sha(bytes)).length,2);assert.equal(prep.replace(sha(bytes),sha(oldBytes)),before);});
test('bounded full V27 history preserves all original assertion bodies and rejects changed archives',async()=>{const h=await readCaptureV27History();assert.equal(Object.keys(h.files).length,d.historyInputCount);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const[n,r]of Object.entries(h.files))assert.equal(sha(Buffer.from(await readCaptureV27Source(n))),r.sha256);for(const[n,hash]of Object.entries(d.originalAssertionBodiesSHA256)){const current=await readFile(path.join(root,n),'utf8'),before=await readCaptureV27Source(n);assert.equal(current.slice(current.indexOf("test('")),before.slice(before.indexOf("test('")));assert.equal(sha(Buffer.from(before.slice(before.indexOf("test('")))),hash);}const archive=await readFile(new URL('./fixtures/capture-v27-avatar-flow-before.json.gz',import.meta.url)),bad=Buffer.from(archive);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV27History(bad));assert.throws(()=>decodeCaptureV27History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV27History(new Uint8Array(archive)));});
test('CPU normalization accepts only entire named current and before sources not altered or unknown bytes',async()=>{for(const n of Object.keys(d.historicalInputSHA256).filter(n=>!['browser-client/tests/fixtures/capture-software-managed-v27-complete-source-manifest.json','browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs'].includes(n))){const before=Buffer.from(await readCaptureV27Source(n)),current=await readFile(path.join(root,n));assert.deepEqual(await recoverCaptureV27Input(n,before),before);assert.deepEqual(await recoverCaptureV27Input(n,current),before);for(const input of [Buffer.concat([before,Buffer.from('\n')]),Buffer.concat([current,Buffer.from('\n')]),Buffer.from('unknown')])await assert.rejects(()=>recoverCaptureV27Input(n,input));}await assert.rejects(()=>readCaptureV27Source('unknown'));});
test('current Chrome20 stays exact and only one current49 spec pin migrates with whole original assertion recovery',async()=>{
 assert.deepEqual(m.reacquisitionDerivation.chromeEnvironmentSourcePins,old.reacquisitionDerivation.chromeEnvironmentSourcePins);assert.deepEqual(d.chromeEnvironmentMigrations,{});
 assert.equal(Object.keys(d.currentBrowserSpecSHA256).length,49);assert.deepEqual(d.originalBrowserSpecSHA256,old.softwareManagedDerivation.originalBrowserSpecSHA256);
 const changed=Object.keys(d.currentBrowserSpecSHA256).filter(n=>d.currentBrowserSpecSHA256[n]!==d.originalBrowserSpecSHA256[n]);assert.deepEqual(changed,['browser-client/tests/render-dispatch-attribution.browser.spec.ts']);assert.deepEqual(changed,Object.keys(d.currentBrowserSpecMigrations));
 for(const[n,h]of Object.entries(d.currentBrowserSpecSHA256))assert.equal(sha(await readFile(path.join(root,n))),h);
 const spec=changed[0],before=await readCaptureV27Source(spec),current=await readFile(path.join(root,spec),'utf8');assert.equal(current.split(' await testInfo.attach',2)[1],before.split(' await testInfo.attach',2)[1]);assert.equal(sha(Buffer.from(before)),d.originalBrowserSpecSHA256[spec]);assert.equal(d.clockScope,'synthetic-fixture-not-host-CPU');
 for(const[n,h]of Object.entries(m.reacquisitionDerivation.chromeEnvironmentSourcePins))assert.equal(sha(await readFile(path.join(root,n))),h);
 for(const[n,h]of Object.entries(d.unchangedNativeCoreSourcePins))assert.equal(sha(await readFile(path.join(root,n))),h);
 for(const[n,h]of [['browser-client/src/world.ts',d.unchangedWorldSHA256],['browser-client/tests/fixtures/embedded-world.ts',d.unchangedEmbeddedFixtureSHA256],['browser-client/tests/integration/embedded-world.mjs',d.unchangedEmbeddedRunnerSHA256]])assert.equal(sha(await readFile(path.join(root,n))),h);
});
test('current strict source reader and schema scopes stay distinct from CPU history and private viewer',async()=>{
 assert.equal(d.nativeChildSampleVersion,1);assert.equal(d.gatewaySampleVersion,2);assert.equal(d.nativeAuthorVersion,1);assert.equal(d.currentRuntimeSourceMeaningCount,15);assert.equal(d.gitOnlyRuntimeFalseMeaningCount,3);assert.equal(d.newThirdGitOnlyMeaning,'browser-client/tools/curate-avatar-samples.mjs');assert.equal(d.privateViewerIsNotRepositoryInput,true);assert(!m.files.some(r=>/viewer\.mjs$/.test(r.path)));
 for(const n of ['browser-client/gateway/server.mjs','browser-client/gateway/avatar-snapshot-sender.mjs','browser-client/gateway/native-avatar-stdout-projection.mjs','browser-client/tools/curate-avatar-samples.mjs']){const current=await readFile(path.join(root,n));assert.deepEqual(await readCurrentAvatarFlowSource(n,path.join(root,n)),current);assert.notEqual(sha(current),d.historicalInputSHA256[n]);}
});
test('strict current production reader refuses old altered missing oversize unknown and invalid key bytes',async()=>{const n='browser-client/gateway/server.mjs',current=await readFile(path.join(root,n)),before=Buffer.from(await readCaptureV27Source(n));assert.notEqual(sha(current),sha(before));const dir=await mkdtemp(path.join(tmpdir(),'v27-current-'));try{const f=path.join(dir,'input');for(const b of [before,Buffer.concat([current,Buffer.from('\n')]),Buffer.from('unknown'),Buffer.alloc(262145)]){await writeFile(f,b,{mode:0o600});await assert.rejects(()=>readCurrentAvatarFlowSource(n,f));}await unlink(f);await assert.rejects(()=>readCurrentAvatarFlowSource(n,f));await assert.rejects(()=>readCurrentAvatarFlowSource('unknown',path.join(root,n)));await assert.rejects(()=>readCurrentAvatarFlowSource(n,new URL('https://example.invalid/')));}finally{await rm(dir,{recursive:true,force:true});}});
test('strict current held file requires sole own safe regular source and rejects alias link writable and directory',async()=>{const n='browser-client/gateway/server.mjs',b=await readFile(path.join(root,n)),dir=await mkdtemp(path.join(tmpdir(),'v27-held-'));try{const target=path.join(dir,'target'),f=path.join(dir,'input');await writeFile(target,b,{mode:0o600});await symlink(target,f);await assert.rejects(()=>readCurrentAvatarFlowSource(n,f));await unlink(f);await link(target,f);await assert.rejects(()=>readCurrentAvatarFlowSource(n,f));await unlink(f);await writeFile(f,b,{mode:0o600});await chmod(f,0o622);await assert.rejects(()=>readCurrentAvatarFlowSource(n,f));await chmod(f,0o600);assert.deepEqual(await readCurrentAvatarFlowSource(n,f),b);await assert.rejects(()=>readCurrentAvatarFlowSource(n,dir));}finally{await rm(dir,{recursive:true,force:true});}});
