// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {pathToFileURL,fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import {gunzipSync} from 'node:zlib';
import {recoverCaptureV13Input} from './integration/capture-image-transport-source-fixture.mjs';
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV13Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
import {readCaptureV8History,readCaptureV8Source,decodeCaptureV8History,recoverCaptureV8Input} from './integration/capture-status-source-fixture.mjs';
import {readCaptureV9Source,recoverCaptureV9Input} from './integration/capture-reconnect-source-fixture.mjs';
import {attestCaptureWorker} from './integration/tablet-capture-worker.mjs';import {buildBrowserCaptureUI} from '../gateway/browser-capture-overrides.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),manifestBytes=await readFile(new URL('./fixtures/capture-status-v9-complete-source-manifest.json',import.meta.url)),v9=JSON.parse(manifestBytes),oldBytes=await readFile(new URL('./fixtures/capture-readback-v8-complete-source-manifest.json',import.meta.url)),v8=JSON.parse(oldBytes),prep=await readCaptureV9Source('tests/integration/prepare-tablet-capture-acceptance.mjs');
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,preflight=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-status-guard-'));try{const source=path.join(dir,'browser-client');for(const row of v9.files){if(!row.path.startsWith('browser-client/'))continue;const relative=row.path.slice(15),dest=path.join(source,relative);await mkdir(path.dirname(dest),{recursive:true});await writeFile(dest,await recoverCaptureV9Input(relative,await readFile(path.join(client,relative))),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,manifestBytes);return await fn(source,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(source,proposal)=>preflight(assert,readFile,realpath,lstat,path,sha,source,proposal);
test('v9 actual current rows preserve complete v8 104 with exact declared migrations and original policy/limits',async()=>{assert.equal(v8.files.length,104);assert.equal(sha(oldBytes),'66c7ce8e7723cfff9ba1c88a0d59730214c896def3fe9597db98d777d790db31');assert.equal(v9.version,9);const d=v9.statusChromeDerivation;assert.equal(d.previousCompleteManifestSHA256,sha(oldBytes));for(const r of v8.files){const rows=v9.files.filter(n=>n.path===r.path);assert.equal(rows.length,1);const n=rows[0],m=d.migrations[r.path];if(m){assert.equal(m.beforeSHA256,r.afterSHA256);assert.equal(n.beforeSHA256,r.afterSHA256);assert.equal(n.afterSHA256,m.afterSHA256);}else assert.deepEqual(n,r);}for(const key of['limits','verification','packagePins','dependencyPins'])assert.deepEqual(v9[key],v8[key]);assert.equal(v9.files.length,104+d.addedRows.length);assert.equal(v9.files.length,new Set(v9.files.map(r=>r.path)).size);await fixture(async(s,p)=>assert.equal((await check(s,p)).version,9));});
test('current production preparer reverses exactly one manifest literal to complete v8; no historical imports or fallback',async()=>{const prior=await readCaptureV8Source('tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.split(sha(manifestBytes)).length,2);assert.equal(prep.replace(sha(manifestBytes),sha(oldBytes)),prior);assert(!prep.includes('capture-status-source-fixture'));assert(!prep.includes('capture-readback-source-fixture'));});
test('old v8/current-looking/invented manifests refuse before source reads',async()=>{await fixture(async(s,p)=>{for(const b of[oldBytes,Buffer.from(JSON.stringify({...v9,version:8})),Buffer.from(JSON.stringify({...v9,files:[]}))]){await writeFile(p,b);let reads=0;const read=async f=>{if(f!==p)reads++;return readFile(f);};await assert.rejects(()=>preflight(assert,read,realpath,lstat,path,sha,s,p));assert.equal(reads,0);}});});
test('each changed factory/operator/history/test and appended row refuses actual byte drift',async()=>{await fixture(async(s,p)=>{for(const key of[...Object.keys(v9.statusChromeDerivation.migrations),...v9.statusChromeDerivation.addedRows]){const file=path.join(s,key.slice(15)),b=await readFile(file);await writeFile(file,Buffer.concat([b,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));await writeFile(file,b);}});});
test('current recovery history/factory symlink alias refuses exact admission',async()=>{for(const relative of['gateway/browser-capture-overrides.mjs','tests/fixtures/capture-v8-status-before.json.gz','tests/integration/capture-status-source-fixture.mjs'])await fixture(async(s,p,dir)=>{const file=path.join(s,relative),outside=path.join(dir,'alias');await writeFile(outside,await readFile(file));await unlink(file);await symlink(outside,file);await assert.rejects(()=>check(s,p));});});
test('ten whole v8 inputs immutable/exact; corrupted oversized and nonbuffer archives refuse',async()=>{const h=await readCaptureV8History();assert.equal(Object.keys(h.files).length,10);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const r of Object.values(h.files)){assert(Object.isFrozen(r));assert.equal(sha(Buffer.from(r.source)),r.sha256);}const b=await readFile(new URL('./fixtures/capture-v8-status-before.json.gz',import.meta.url)),bad=Buffer.from(b);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV8History(bad));assert.throws(()=>decodeCaptureV8History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV8History(new Uint8Array(b)));await assert.rejects(()=>readCaptureV8Source('unknown'));});
test('entire historical v8 helper/test/operator bodies recover only exact substitutions; arbitrary modern input refuses',async()=>{const h=await readCaptureV8History(),recovery=JSON.parse(await readFile(new URL('./fixtures/capture-v9-status-input-recovery.json',import.meta.url)));assert.equal(Object.keys(recovery).length,8);for(const[relative,anchors]of Object.entries(recovery)){const bytes=await readFile(path.join(client,relative));let s=bytes.toString();for(const[before,after]of anchors.toReversed()){assert.equal(s.split(after).length,2);s=s.replace(after,before);}assert.equal(s,h.files[relative].source);assert.equal((await recoverCaptureV8Input(relative,bytes)).toString(),s);await assert.rejects(()=>recoverCaptureV8Input(relative,Buffer.concat([bytes,Buffer.from('\n')])));}assert.equal(await readCaptureV8Source('tests/fixtures/capture-readback-v8-complete-source-manifest.json'),oldBytes.toString());});
test('genuine worker attestation regenerates qualified current QML while exact old QML/helper drift refuse',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'capture-status-worker-'));try{const original=gunzipSync(await readFile(new URL('../gateway/fixtures/native-audio-f91d15a.js.gz',import.meta.url))).toString(),channel='overte.browser.capture.'+'0'.repeat(32),generated=buildBrowserCaptureUI(original,channel,pathToFileURL(path.join(dir,'browser-audio.qml')).href),helper=await readFile(new URL('../gateway/native-browser-capture.js',import.meta.url));for(const[name,b]of[['browser-audio.js',generated.script],['browser-audio.qml',generated.qml],['native-browser-capture.js',helper]])await writeFile(path.join(dir,name),b,{mode:0o600,flag:'wx'});assert.equal((await attestCaptureWorker(dir)).exactGeneratedSource,true);const anchors=JSON.parse(await readFile(new URL('./fixtures/capture-status-layout-source-anchors.json',import.meta.url)));let old=generated.qml;for(const[a,b]of anchors.toReversed()){assert.equal(old.split(b).length,2);old=old.replace(b,a);}await writeFile(path.join(dir,'browser-audio.qml'),old);await assert.rejects(()=>attestCaptureWorker(dir));await writeFile(path.join(dir,'browser-audio.qml'),generated.qml);await writeFile(path.join(dir,'native-browser-capture.js'),Buffer.concat([helper,Buffer.from('\n')]));await assert.rejects(()=>attestCaptureWorker(dir));}finally{await rm(dir,{recursive:true,force:true});}});
test('retained copied actual Chrome PASS is source-bound synthetic evidence, not a new current-build or hardware claim',async()=>{const b=await readFile(new URL('./fixtures/capture-status-layout-qualified.json',import.meta.url)),p=JSON.parse(b);assert.equal(sha(b),'a90ccae90910c24822074f26d8190da6123c0a431d10d7d2251b601f35138e43');assert.equal(p.outcome,'PASS');assert.equal(p.bindings.factoryCopySHA256,v9.statusChromeDerivation.migrations['browser-client/gateway/browser-capture-overrides.mjs'].afterSHA256);assert.equal(p.bindings.workerAttestationSourceSHA256,sha(await readFile(new URL('./integration/tablet-capture-worker.mjs',import.meta.url))));assert.equal(p.source.productionStatusFixIntegrated,false);assert.equal(v9.statusChromeDerivation.currentCanonicalV9ChromeQualified,false);});
