// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {recoverCaptureV17Input,readCaptureV17Source} from './integration/capture-embedded-diagnostic-source-fixture.mjs';
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV17Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
import {readCaptureV16History,readCaptureV16Source,recoverCaptureV16Input,decodeCaptureV16History} from './integration/capture-avatar-diagnostic-source-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.dirname(client),bytes=await readFile(new URL('./fixtures/capture-avatar-diagnostic-v17-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-chrome-readme-v16-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readCaptureV17Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs'),d=m.avatarDiagnosticDerivation;
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,gate=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-avatar-'));try{const s=path.join(dir,'browser-client');for(const row of m.files){if(!row.path.startsWith('browser-client/'))continue;const dest=path.join(dir,row.path);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,row.path)),{mode:0o600,flag:'wx'});}for(const relative of ['.github/workflows/browser-client.yml','browser-client/lab/README.md']){const dest=path.join(dir,relative);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,relative)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(s,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>gate(assert,readFile,realpath,lstat,path,sha,s,p);
test('v17 retains all157 V16 rows and declares two CPU migrations six additions and one external workflow',()=>{assert.equal(m.version,17);assert.equal(old.files.length,157);assert.equal(m.files.length,163);assert.equal(new Set(m.files.map(r=>r.path)).size,163);assert.equal(d.previousManifestSHA256,sha(oldBytes));assert.equal(Object.keys(d.fixtureMigrations).length,2);assert.equal(d.addedRows.length,6);assert.deepEqual(Object.keys(d.externalMigrations),['.github/workflows/browser-client.yml']);for(const row of old.files){const next=m.files.find(r=>r.path===row.path);assert(next);const change=d.fixtureMigrations[row.path];assert.deepEqual(next,change?{...row,beforeSHA256:row.afterSHA256,afterSHA256:change.afterSHA256,bytes:change.bytes}:row);}const expected=structuredClone(old);expected.version=17;expected.scope=m.scope;expected.files=m.files;expected.reacquisitionDerivation.chromeEnvironmentSourcePins['.github/workflows/browser-client.yml']=d.externalMigrations['.github/workflows/browser-client.yml'].afterSHA256;expected.avatarDiagnosticDerivation=d;assert.deepEqual(m,expected);assert.equal(d.frontendProductionChanged,false);});
test('actual current pre-copy gate admits all163 rows and explicitly binds tools collector and its tests',()=>fixture(async(s,p)=>{assert.equal((await check(s,p)).version,17);for(const n of ['browser-client/tools/curate-avatar-samples.mjs','browser-client/tests/native-avatar-curation.test.mjs'])assert(m.files.some(r=>r.path===n));}));
test('whole V16 and invented manifests refuse before any current source or environment read',()=>fixture(async(s,p)=>{for(const data of [oldBytes,Buffer.from(JSON.stringify({...m,version:16})),Buffer.concat([bytes,Buffer.from('\n')])]){await writeFile(p,data);let reads=0;await assert.rejects(()=>gate(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}}));
test('each changed and appended current row refuses unknown missing symlink and exact old source',()=>fixture(async(s,p,dir)=>{for(const name of [...Object.keys(d.fixtureMigrations),...d.addedRows]){const f=path.join(dir,name),b=await readFile(f);await writeFile(f,Buffer.concat([b,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));if(d.fixtureMigrations[name]){await writeFile(f,await readCaptureV16Source(name));await assert.rejects(()=>check(s,p));}await unlink(f);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'alias');await writeFile(alias,b);await symlink(alias,f);await assert.rejects(()=>check(s,p));await unlink(f);await unlink(alias);await writeFile(f,b);}}));
test('changed external workflow refuses whole old bytes unknown newline missing and symlink',()=>fixture(async(s,p,dir)=>{const f=path.join(dir,'.github/workflows/browser-client.yml'),b=await readFile(f);for(const data of [Buffer.from(await readCaptureV16Source('.github/workflows/browser-client.yml')),Buffer.concat([b,Buffer.from('\n')])]){await writeFile(f,data);await assert.rejects(()=>check(s,p));}await unlink(f);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'workflow-alias');await writeFile(alias,b);await symlink(alias,f);await assert.rejects(()=>check(s,p));}));
test('production preparer changes exactly one digest literal and never imports source history',async()=>{const before=await readCaptureV16Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.split(sha(bytes)).length,2);assert.equal(prep.replace(sha(bytes),sha(oldBytes)),before);assert(!prep.includes('source-fixture'));assert(!prep.includes('recoverCapture'));assert(prep.includes('(?:src|shared|gateway|tests|native-input|tools)'));});
test('bounded whole V16 recovery authenticates five original inputs and rejects unknown or malformed archive',async()=>{const h=await readCaptureV16History();assert.equal(Object.keys(h.files).length,5);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const[name,row]of Object.entries(h.files))assert.equal(sha(Buffer.from(await readCaptureV16Source(name))),row.sha256);for(const name of [...Object.keys(d.fixtureMigrations),'.github/workflows/browser-client.yml']){const b=await readFile(path.join(root,name));assert.equal((await recoverCaptureV16Input(name,b)).toString(),h.files[name].source);await assert.rejects(()=>recoverCaptureV16Input(name,Buffer.concat([b,Buffer.from('\n')])));assert.equal((await recoverCaptureV16Input(name,Buffer.from(h.files[name].source))).toString(),h.files[name].source);}const b=await readFile(new URL('./fixtures/capture-v16-avatar-diagnostic-before.json.gz',import.meta.url)),bad=Buffer.from(b);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV16History(bad));assert.throws(()=>decodeCaptureV16History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV16History(new Uint8Array(b)));});
test('all original seven V16 assertion bodies and49 authored Chrome spec sources remain unchanged',async()=>{const oldTest=await readCaptureV16Source('browser-client/tests/tablet-capture-chrome-readme-manifest.test.mjs'),current=await readFile(new URL('./tablet-capture-chrome-readme-manifest.test.mjs',import.meta.url),'utf8');assert.equal(current.slice(current.indexOf("test('")),oldTest.slice(oldTest.indexOf("test('")));assert.equal(Object.keys(d.chromeSpecSourcePins).length,49);for(const[relative,hash]of Object.entries(d.chromeSpecSourcePins))assert.equal(sha(await readFile(path.join(root,relative))),hash);});
test('three exact inverse workflow anchors preserve whole old actions jobs permissions and default-off behavior',async()=>{let workflow=await readFile(path.join(root,'.github/workflows/browser-client.yml'),'utf8');assert.equal(sha(Buffer.from(workflow)),d.externalMigrations['.github/workflows/browser-client.yml'].afterSHA256);assert.equal(d.workflowAnchors.length,3);for(const{before,after}of [...d.workflowAnchors].reverse()){assert.equal(workflow.split(after).length,2);workflow=workflow.replace(after,before);}assert.equal(workflow,await readCaptureV16Source('.github/workflows/browser-client.yml'));assert.equal(sha(Buffer.from(workflow)),d.externalMigrations['.github/workflows/browser-client.yml'].beforeSHA256);});
