// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {readCaptureV23History,readCaptureV23Source,recoverCaptureV23Input,decodeCaptureV23History,readCurrentCommandClockCurator} from './integration/capture-command-clock-source-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.dirname(client),bytes=await readFile(new URL('./fixtures/capture-command-clock-v24-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-live-context-v23-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readFile(new URL('./integration/prepare-tablet-capture-acceptance.mjs',import.meta.url),'utf8'),d=m.commandClockDerivation;
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,gate=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-command-clock-'));try{const s=path.join(dir,'browser-client');for(const row of m.files){if(!row.path.startsWith('browser-client/'))continue;const dest=path.join(dir,row.path);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,row.path)),{mode:0o600,flag:'wx'});}for(const relative of ['.github/workflows/browser-client.yml','browser-client/lab/README.md']){const dest=path.join(dir,relative);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,relative)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(s,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>gate(assert,readFile,realpath,lstat,path,sha,s,p);
test('V24 preserves all209 V23 rows with two CPU migrations and six honest admissions',()=>{
 assert.equal(m.version,24);assert.equal(old.version,23);assert.equal(old.files.length,209);assert.equal(m.files.length,215);assert.equal(d.addedRows.length,6);assert.equal(Object.keys(d.sourceMigrations).length,2);assert.equal(d.previousManifestSHA256,sha(oldBytes));assert.equal(new Set(m.files.map(r=>r.path)).size,m.files.length);
 for(const row of old.files){const next=m.files.find(r=>r.path===row.path),change=d.sourceMigrations[row.path];assert.deepEqual(next,change?{...row,beforeSHA256:row.afterSHA256,afterSHA256:change.afterSHA256,bytes:change.bytes}:row);}
 for(const name of d.addedRows){assert(!old.files.some(r=>r.path===name));assert.equal(m.files.find(r=>r.path===name).beforeSHA256,null);}
 const expected=structuredClone(old);expected.version=24;expected.scope=m.scope;expected.files=m.files;expected.commandClockDerivation=d;expected.reacquisitionDerivation.chromeEnvironmentSourcePins['browser-client/lab/curate-core-journey.py']=d.currentCuratorSHA256;assert.deepEqual(m,expected);assert.equal(d.currentCoreUnchanged,true);assert.equal(d.actualRuntimeAcceptance,false);
});
test('actual production gate checks exact V24 rows with unchanged finite exclusions',()=>fixture(async(s,p)=>{
 assert.equal((await check(s,p)).version,24);for(const name of [...Object.keys(d.sourceMigrations),...d.addedRows])assert(m.files.some(r=>r.path===name));assert(!m.files.some(r=>r.path.startsWith('browser-client/lab/')));assert(prep.includes('(?:src|shared|gateway|tests|native-input|tools)'));assert(!prep.includes('recoverCapture'));assert.equal(d.curatorProductionRowAdmission,false);
}));
test('old V23 invented version and newline refuse before source reads',()=>fixture(async(s,p)=>{
 for(const input of [oldBytes,Buffer.from(JSON.stringify({...m,version:23})),Buffer.concat([bytes,Buffer.from('\n')])]){await writeFile(p,input);let reads=0;await assert.rejects(()=>gate(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}
}));
test('all declared V24 rows refuse missing symlink drift and prior reviewed source',()=>fixture(async(s,p,dir)=>{
 const h=await readCaptureV23History();for(const name of [...Object.keys(d.sourceMigrations),...d.addedRows]){const f=path.join(dir,name),current=await readFile(f);await writeFile(f,Buffer.concat([current,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));if(Object.hasOwn(h.files,name)&&h.files[name].sha256!==sha(current)){await writeFile(f,await readCaptureV23Source(name));await assert.rejects(()=>check(s,p));}await unlink(f);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'alias');await writeFile(alias,current);await symlink(alias,f);await assert.rejects(()=>check(s,p));await unlink(f);await unlink(alias);await writeFile(f,current);}
}));
test('production preparer is whole V23 plus one exact manifest literal only',async()=>{
 const before=await readCaptureV23Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.split(sha(bytes)).length,2);assert.equal(prep.replace(sha(bytes),sha(oldBytes)),before);assert(!prep.includes('source-fixture'));assert(!prep.includes('recoverCapture'));
});
test('bounded V23 archive keeps five whole inputs and all nine original V23 assertion bodies',async()=>{
 const h=await readCaptureV23History();assert.equal(Object.keys(h.files).length,5);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const[name,row]of Object.entries(h.files))assert.equal(sha(Buffer.from(await readCaptureV23Source(name))),row.sha256);
 const name='browser-client/tests/tablet-capture-live-context-manifest.test.mjs',current=await readFile(path.join(root,name),'utf8'),before=await readCaptureV23Source(name);assert.equal(current.slice(current.indexOf("test('")),before.slice(before.indexOf("test('")));assert.equal(sha(Buffer.from(before.slice(before.indexOf("test('")))),d.originalV23BodiesSHA256);
 const archive=await readFile(new URL('./fixtures/capture-v23-command-clock-before.json.gz',import.meta.url)),bad=Buffer.from(archive);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV23History(bad));assert.throws(()=>decodeCaptureV23History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV23History(new Uint8Array(archive)));
});
test('named curator CPU recovery accepts only exact whole3980 or reviewed d879, never backfills clocks',async()=>{
 const name='browser-client/lab/curate-core-journey.py',before=Buffer.from(await readCaptureV23Source(name)),current=await readFile(path.join(root,name));assert.equal(sha(before),d.priorCuratorSHA256);assert.equal(sha(current),d.currentCuratorSHA256);assert.deepEqual(await recoverCaptureV23Input(name,before),before);assert.deepEqual(await recoverCaptureV23Input(name,current),before);
 for(const value of [Buffer.concat([before,Buffer.from('\n')]),Buffer.concat([current,Buffer.from('\n')]),Buffer.from('unknown')])await assert.rejects(()=>recoverCaptureV23Input(name,value));assert(!before.toString().includes("'commandIssuedAtMs'"));assert(current.toString().includes("'commandIssuedAtMs'"));
});
test('current external curator is checked separately and refuses old missing symlink and changed bytes',async()=>{
 const dir=await mkdtemp(path.join(tmpdir(),'capture-current-curator-'));try{const file=path.join(dir,'curator.py'),current=await readFile(path.join(root,'browser-client/lab/curate-core-journey.py')),before=await readCaptureV23Source('browser-client/lab/curate-core-journey.py');await writeFile(file,current,{mode:0o600,flag:'wx'});assert.deepEqual(await readCurrentCommandClockCurator(file),current);for(const data of [before,Buffer.concat([current,Buffer.from('\n')])]){await writeFile(file,data);await assert.rejects(()=>readCurrentCommandClockCurator(file));}await unlink(file);await assert.rejects(()=>readCurrentCommandClockCurator(file));const target=path.join(dir,'target');await writeFile(target,current);await symlink(target,file);await assert.rejects(()=>readCurrentCommandClockCurator(file));}finally{await rm(dir,{recursive:true,force:true});}
});
test('current Chrome20 metadata changes only curator and exact current sources all match',async()=>{
 const prior=old.reacquisitionDerivation.chromeEnvironmentSourcePins,next=m.reacquisitionDerivation.chromeEnvironmentSourcePins;assert.equal(Object.keys(next).length,20);assert.deepEqual(Object.keys(next).filter(name=>next[name]!==prior[name]),['browser-client/lab/curate-core-journey.py']);for(const[name,hash]of Object.entries(next)){const file=path.join(root,name);const data=name==='browser-client/lab/curate-core-journey.py'?await readCurrentCommandClockCurator(file):await readFile(file);assert.equal(sha(data),hash);}assert.equal(sha(await readFile(path.join(root,'browser-client/tests/integration/real-session.mjs'))),d.currentCoreSHA256);assert.equal(d.original2800msChanged,false);
});

test('current curator reader rejects a hard-link alias without changing source bytes',async()=>{
 const dir=await mkdtemp(path.join(tmpdir(),'capture-curator-alias-'));try{const file=path.join(dir,'curator.py'),alias=path.join(dir,'alias.py');await writeFile(file,await readFile(path.join(root,'browser-client/lab/curate-core-journey.py')));const {link}=await import('node:fs/promises');await link(file,alias);await assert.rejects(()=>readCurrentCommandClockCurator(file));await assert.rejects(()=>readCurrentCommandClockCurator(alias));}finally{await rm(dir,{recursive:true,force:true});}
});
