// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';import {copyCaptureFixtureRow,readCaptureHistoricalPreparer,decodeCaptureSourceHistory} from './integration/capture-readback-source-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),current=await readFile(new URL('./fixtures/capture-world-key-v6-complete-source-manifest.json',import.meta.url)),prior=await readFile(new URL('./fixtures/capture-reacquisition-v5-complete-source-manifest.json',import.meta.url)),v5=JSON.parse(prior),v6=JSON.parse(current),candidate=await readCaptureHistoricalPreparer(6),original=await readCaptureHistoricalPreparer(5);
const a=candidate.indexOf('const manifestBytes=await readFile(proposal);'),z=candidate.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,preflight=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',candidate.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-world-key-guard-'));try{const source=path.join(dir,'browser-client');for(const row of v6.files){if(!row.path.startsWith('browser-client/'))continue;const relative=row.path.slice(15),dest=path.join(source,relative);await mkdir(path.dirname(dest),{recursive:true});await copyCaptureFixtureRow({client,relative,dest,expectedSHA256:row.afterSHA256,version:6});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,current);return await fn(source,proposal);}finally{await rm(dir,{recursive:true,force:true});}}
test('v6 recovers the entire exact v5 preparer after only pinned manifest, explicit source kinds and native source copy additions',()=>{let recovered=candidate;for(const [after,before]of [[sha(current),sha(prior)],['(?:src|shared|gateway|tests|native-input|tools)','(?:src|shared|gateway|tests)'],["['gateway','shared','src','tests','tools','public','dist','native-input']","['gateway','shared','src','tests','tools','public','dist']"]]){assert.equal(recovered.split(after).length,2);recovered=recovered.replace(after,before);}assert.equal(recovered,original);});
test('successor preserves all56 paths and original gates with only declared exact World-X/palette/collector/source dependency migrations',()=>{assert.equal(v5.files.length,56);assert.equal(v6.files.length,84);const expected=structuredClone(v5);expected.version=6;expected.scope=v6.scope;expected.historicalCompositionDerivation=v6.historicalCompositionDerivation;expected.worldKeyDerivation=v6.worldKeyDerivation;expected.paletteDerivation=v6.paletteDerivation;expected.fstObservationDerivation=v6.fstObservationDerivation;expected.dependencyPins['browser-client/src/world.ts']=v6.dependencyPins['browser-client/src/world.ts'];for(const key of v6.worldKeyDerivation.changedOriginalRowPaths){const row=expected.files.find(v=>v.path===key),next=v6.files.find(v=>v.path===key);assert(row&&next);row.afterSHA256=next.afterSHA256;row.bytes=next.bytes;}expected.files.push(...v6.files.slice(56));assert.deepEqual(v6,expected);assert.equal(v6.worldKeyDerivation.previousCompleteManifestSHA256,sha(prior));assert.equal(v6.worldKeyDerivation.worldKeyCompositionManifestSHA256,'4c5937b6a18ac5b8f72c36a11001da3f9214f6b884a3d61180555b3cdad4f97d');assert.equal(v6.worldKeyDerivation.actualAudioAfterWorldKeyQualified,false);assert.equal(v6.worldKeyDerivation.runtimeQualityOrPermissionChanges,false);assert.deepEqual(v6.reacquisitionDerivation,v5.reacquisitionDerivation);assert.equal(v6.reacquisitionDerivation.original12BodySHA256,'6dec42866e6818b1595840e4ccf517f1a56888d8752a3cfe197c0625f6996e3f');});
test('current exact84-row guard reads admitted native source and tool kinds with no preparer setup side effects',()=>fixture(async(source,p)=>{assert.deepEqual(await preflight(assert,readFile,realpath,lstat,path,sha,source,p),v6);}));
test('old v5, invented versions and missing source rows refuse before any source read',()=>fixture(async(source,p)=>{for(const bytes of [prior,Buffer.from(JSON.stringify({...v6,version:5})),Buffer.from(JSON.stringify({...v6,files:[]}))]){await writeFile(p,bytes);let reads=0;await assert.rejects(preflight(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,source,p));assert.equal(reads,0);}}));
test('modified World-X source, native header and builder symlink cannot satisfy current admission',()=>fixture(async(source,p)=>{for(const key of v6.worldKeyDerivation.changedWorldKeyRows){const row=v6.files.find(v=>v.path===key);assert(row);const file=path.join(source,key.slice(15)),before=await readFile(file);await writeFile(file,Buffer.concat([before,Buffer.from('\n')]));await assert.rejects(preflight(assert,readFile,realpath,lstat,path,sha,source,p),/Exact reviewed capture composition required/);await writeFile(file,before);}const file=path.join(source,'tools/build-native-input.py'),bytes=await readFile(file);await unlink(file);const alias=path.join(source,'builder.py');await writeFile(alias,bytes);await symlink(alias,file);await assert.rejects(preflight(assert,readFile,realpath,lstat,path,sha,source,p));}));

test('every actual five-row v5 before image refuses the current v6 guard without changing its rejection gate',()=>fixture(async(source,p)=>{const history=decodeCaptureSourceHistory(await readFile(new URL('./fixtures/capture-source-history-v5-world-key.json.gz',import.meta.url)));for(const relative of ['gateway/native-tablet.js','gateway/tablet.mjs','src/main.ts','src/tablet-protocol.ts','src/tablet.ts']){const row=history.files[relative],v5row=v5.files.find(v=>v.path==='browser-client/'+relative);assert.equal(row.sha256,v5row.afterSHA256);const file=path.join(source,relative),current=await readFile(file);assert.notEqual(sha(current),row.sha256);await writeFile(file,row.source);await assert.rejects(preflight(assert,readFile,realpath,lstat,path,sha,source,p),/Exact reviewed capture composition required/);await writeFile(file,current);}}));


test('palette and optional collector preserve exact old source guards; all current rows and World dependency require the composed source',()=>fixture(async(source,p)=>{
 const history=decodeCaptureSourceHistory(await readFile(new URL('./fixtures/capture-source-history-v5-world-key.json.gz',import.meta.url)));
 assert.equal(v6.paletteDerivation.gainPaletteManifestSHA256,'36531116e3a6ebf56ac04527511a10de8ad1042f5716fbec0c6049eaa94d390f');
 assert.equal(v6.paletteDerivation.originalPaintedContrastThreshold,20);assert.equal(v6.paletteDerivation.widgetGeometryOrActionChanged,false);
 assert.equal(v6.fstObservationDerivation.defaultEnabled,false);assert.equal(v6.fstObservationDerivation.loadOrderOrConcurrencyChanged,false);
 assert.equal(v6.fstObservationDerivation.maximumPerFieldCount,256);assert.equal(v6.fstObservationDerivation.worldBeforeSHA256,'2091ddde38ece3bb5ed1dbfe4efdaf9f6979a9d99a9dc094de3f315f71961407');
 assert.equal(v6.dependencyPins['browser-client/src/world.ts'],v6.fstObservationDerivation.worldAfterSHA256);
 const worldrow=v6.files.find(r=>r.path==='browser-client/src/world.ts');assert.equal(worldrow.afterSHA256,v6.dependencyPins['browser-client/src/world.ts']);
 for(const relative of ['gateway/browser-capture-overrides.mjs','tests/tablet-capture-style.test.mjs']){const file=path.join(source,relative),bytes=await readFile(file);await writeFile(file,history.files[relative].source);await assert.rejects(preflight(assert,readFile,realpath,lstat,path,sha,source,p),/Exact reviewed capture composition required/);await writeFile(file,bytes);}
 for(const row of v6.fstObservationDerivation.admittedRows){const file=path.join(source,row.path.slice(15)),bytes=await readFile(file);assert.equal(sha(bytes),row.afterSHA256);await writeFile(file,Buffer.concat([bytes,Buffer.from('\n')]));await assert.rejects(preflight(assert,readFile,realpath,lstat,path,sha,source,p),/Exact reviewed capture composition required/);await writeFile(file,bytes);}
}));

test('historical composition successor preserves all old Application/width assertions and adds only fixed source controls',()=>{
 assert.equal(v6.historicalCompositionDerivation.previousCompleteManifestSHA256,'e8798d41b6a35268d70f52d14375ac96a7cdbdf56ecad92910bfbd439708ce87');
 assert.equal(v6.historicalCompositionDerivation.historicalArchiveInputs,10);
 assert.equal(v6.historicalCompositionDerivation.runtimeChanges,false);assert.equal(v6.historicalCompositionDerivation.assertionsRemoved,false);
 for(const relative of v6.historicalCompositionDerivation.addedSourceRows)assert(v6.files.some(r=>r.path===relative));
 assert.deepEqual(v6.historicalCompositionDerivation.oldApplicationExpectedSHA256,['c4edbad2ea9697cc969b0ab965ad5c834119a553465ae5ef7d95205d73f2d3ca','f990c2ed3f5b0d68e50b959774214f4b7637e332b1c9613567c8ea9252f5f1bc','09d1aa93dc612d6a9229ca58ae214b3d4e51bd9bf62009f7ea4d921db51741e4']);
});
