// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';import vm from 'node:vm';
import {readCaptureV15History,readCaptureV15Source,recoverCaptureV15Input,decodeCaptureV15History} from './integration/capture-chrome-readme-source-fixture.mjs';
import {recoverCaptureV14Input} from './integration/capture-reviewed-environment-source-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.dirname(client),bytes=await readFile(new URL('./fixtures/capture-chrome-readme-v16-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-reviewed-environment-v15-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readFile(new URL('./integration/prepare-tablet-capture-acceptance.mjs',import.meta.url),'utf8'),d=m.chromeReadmeRecoveryDerivation;
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,gate=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-chrome-readme-'));try{const s=path.join(dir,'browser-client');for(const row of m.files){if(!row.path.startsWith('browser-client/'))continue;const dest=path.join(dir,row.path);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,row.path)),{mode:0o600,flag:'wx'});}for(const relative of ['.github/workflows/browser-client.yml','browser-client/lab/README.md']){const dest=path.join(dir,relative);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,relative)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(s,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>gate(assert,readFile,realpath,lstat,path,sha,s,p);
test('v16 retains all153 reviewed V15 rows and changes only three CPU plumbing rows plus four explicit historical controls',()=>{assert.equal(m.version,16);assert.equal(old.files.length,153);assert.equal(m.files.length,157);assert.equal(d.previousManifestSHA256,sha(oldBytes));assert.equal(Object.keys(d.fixtureMigrations).length,3);assert.equal(d.addedRows.length,4);for(const row of old.files){const next=m.files.find(r=>r.path===row.path);assert(next);const change=d.fixtureMigrations[row.path];assert.deepEqual(next,change?{...row,beforeSHA256:row.afterSHA256,afterSHA256:change.afterSHA256,bytes:change.bytes}:row);}const expected=structuredClone(old);expected.version=16;expected.scope=m.scope;expected.files=m.files;expected.chromeReadmeRecoveryDerivation=d;assert.deepEqual(m,expected);assert.equal(d.productionSourceChanged,false);});
test('real current pre-copy gate admits157 rows and rejects whole V15 before any source read',()=>fixture(async(s,p)=>{assert.equal((await check(s,p)).version,16);await writeFile(p,oldBytes);let reads=0;await assert.rejects(()=>gate(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}));
test('all three repaired and four appended current rows retain oldsource unknownbyte missing and symlink refusal',()=>fixture(async(s,p,dir)=>{for(const name of [...Object.keys(d.fixtureMigrations),...d.addedRows]){const f=path.join(dir,name),b=await readFile(f);await writeFile(f,Buffer.concat([b,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));if(d.fixtureMigrations[name]){await writeFile(f,await readCaptureV15Source(name));await assert.rejects(()=>check(s,p));}await unlink(f);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'alias');await writeFile(alias,b);await symlink(alias,f);await assert.rejects(()=>check(s,p));await unlink(f);await unlink(alias);await writeFile(f,b);}}));
test('actual final README still requires exact current bytes and canonical regular file',()=>fixture(async(s,p,dir)=>{const f=path.join(dir,'browser-client/lab/README.md'),b=await readFile(f);assert.equal(sha(b),'4d3b41b34f70c1158e135b3bbce98b911136e54d376078144020516fab49ec86');await writeFile(f,await recoverCaptureV14Input('browser-client/lab/README.md',b));await assert.rejects(()=>check(s,p));await writeFile(f,Buffer.concat([b,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));await unlink(f);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'readme-alias');await writeFile(alias,b);await symlink(alias,f);await assert.rejects(()=>check(s,p));}));
test('all original nine Chrome and eleven V15 assertion bodies remain byte-exact and current preparer recovers wholly',async()=>{for(const relative of ['browser-client/tests/chrome-journey-defaults.test.mjs','browser-client/tests/tablet-capture-reviewed-environment-manifest.test.mjs']){const before=await readCaptureV15Source(relative),after=await readFile(path.join(root,relative),'utf8');assert.equal(after.slice(after.indexOf("test('")),before.slice(before.indexOf("test('")));}const before=await readCaptureV15Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.replace(sha(bytes),sha(oldBytes)),before);assert(!prep.includes('source-fixture'));assert(!prep.includes('recoverCapture'));});
test('exact old metadata recovery fails final README until existing V14 whole-source normalization is composed',async()=>{const before=await readCaptureV15Source('browser-client/tests/chrome-journey-defaults.test.mjs'),start=before.indexOf('const metadataReadmeBefore='),end=before.indexOf('// tests are below:',start);assert(start>=0&&end>start);const recover=vm.runInNewContext(before.slice(start,end)+'recoverReviewedReadme',{assert,sha});const current=await readFile(path.join(root,'browser-client/lab/README.md'),'utf8');assert.throws(()=>recover(current));const restored=await recoverCaptureV14Input('browser-client/lab/README.md',Buffer.from(current));assert.equal(sha(restored),'86e5620f014c69879722a90609fb1808a7e55f5592a51fb9ec6d5c7b1070a4cb');assert.equal(sha(recover(restored.toString())),'3538e7e9184b585d5ecf4ec9b494d89a68578ac2d27b6b8de4eada5d627b10ce');await assert.rejects(()=>recoverCaptureV14Input('browser-client/lab/README.md',Buffer.from(current+'\n')));});
test('bounded five whole V15 inputs preserve strict current recovery and malformed/archive refusal',async()=>{const h=await readCaptureV15History();assert.equal(Object.keys(h.files).length,5);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const[name,row]of Object.entries(h.files))assert.equal(sha(Buffer.from(await readCaptureV15Source(name))),row.sha256);for(const name of Object.keys(d.fixtureMigrations)){const b=await readFile(path.join(root,name));assert.equal((await recoverCaptureV15Input(name,b)).toString(),h.files[name].source);await assert.rejects(()=>recoverCaptureV15Input(name,Buffer.concat([b,Buffer.from('\n')])));}const b=await readFile(new URL('./fixtures/capture-v15-chrome-readme-before.json.gz',import.meta.url)),bad=Buffer.from(b);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV15History(bad));assert.throws(()=>decodeCaptureV15History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV15History(new Uint8Array(b)));});
