// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
import {readCaptureV12Source,recoverCaptureV12Input} from './integration/capture-source-test-fixture.mjs';
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV12Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
import {readCaptureV11History,readCaptureV11Source,decodeCaptureV11History,recoverCaptureV11Input} from './integration/capture-loading-source-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.join(client,'..'),bytes=await readFile(new URL('./fixtures/capture-loading-v12-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-environment-v11-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readCaptureV12Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,gate=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-loading-guard-'));try{const source=path.join(dir,'browser-client');for(const row of m.files){if(!row.path.startsWith('browser-client/'))continue;const name=row.path.slice(15),dest=path.join(source,name);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(client,name)),{mode:0o600,flag:'wx'});}for(const name of Object.keys(m.environmentReconciliationDerivation.externalMigrations)){const dest=path.join(dir,name);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,name)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(source,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>gate(assert,readFile,realpath,lstat,path,sha,s,p);
test('v12 preserves all130 V11 rows with one runtime migration, one explicit runtime admission, two CPU migrations and eight additions',()=>{assert.equal(sha(oldBytes),'19aa0b6eb4d57ebcdba875b03d9cfebb17d4e17e5c34b4e22efbe3071b5bdf1c');assert.equal(old.files.length,130);assert.equal(m.version,12);assert.equal(m.files.length,138);assert.equal(new Set(m.files.map(r=>r.path)).size,138);const d=m.imageFstLoadingDerivation,changed={...d.runtimeMigrations,...d.fixtureMigrations};assert.equal(d.previousManifestSHA256,sha(oldBytes));assert.equal(Object.keys(d.runtimeMigrations).length,1);assert.equal(Object.keys(d.fixtureMigrations).length,2);assert.equal(Object.keys(d.runtimeAdmissions).length,1);assert.equal(old.files.some(r=>r.path==='browser-client/src/world-image-cache.ts'),false);assert.equal(d.runtimeAdmissions['browser-client/src/world-image-cache.ts'].previousManifestListed,false);assert.equal(d.runtimeAdmissions['browser-client/src/world-image-cache.ts'].beforeSHA256,'ba45a6125087f8b275c939a5e9e36dadac6879a37cb0fbe50d8c19dd9f1c6af9');assert.equal(d.addedRows.length,8);for(const row of old.files){const next=m.files.filter(r=>r.path===row.path);assert.equal(next.length,1);if(changed[row.path]){assert.equal(changed[row.path].beforeSHA256,row.afterSHA256);assert.deepEqual(next[0],{...row,beforeSHA256:row.afterSHA256,afterSHA256:changed[row.path].afterSHA256,bytes:changed[row.path].bytes});}else assert.deepEqual(next[0],row);}const expected=structuredClone(old);expected.version=m.version;expected.scope=m.scope;expected.files=m.files;expected.dependencyPins['browser-client/src/world.ts']=d.runtimeMigrations['browser-client/src/world.ts'].afterSHA256;expected.imageFstLoadingDerivation=d;assert.deepEqual(m,expected);});
test('new preparer recovers complete exact V11 after only one literal and imports no history',async()=>{const oldPrep=await readCaptureV11Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.split(sha(bytes)).length,2);assert.equal(prep.replace(sha(bytes),sha(oldBytes)),oldPrep);assert(!prep.includes('capture-loading-source-fixture'));assert(!prep.includes('recoverCapture'));});
test('actual extracted production gate accepts all138 current rows and unchanged two external inputs',()=>fixture(async(s,p)=>assert.equal((await check(s,p)).version,12)));
test('historical and invented manifests refuse before any source or environment read',()=>fixture(async(s,p)=>{for(const data of [oldBytes,Buffer.from(JSON.stringify({...m,version:11})),Buffer.from(JSON.stringify({...m,files:[]}))]){await writeFile(p,data);let reads=0;await assert.rejects(()=>gate(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}}));
test('every migration and added row refuses unknown current source drift',()=>fixture(async(s,p)=>{const d=m.imageFstLoadingDerivation;for(const name of [...Object.keys(d.runtimeMigrations),...Object.keys(d.fixtureMigrations),...d.addedRows]){const file=path.join(s,name.slice(15)),data=await readFile(file);await writeFile(file,Buffer.concat([data,Buffer.from('\n')]));await assert.rejects(()=>check(s,p),/Exact reviewed capture composition required/);await writeFile(file,data);}}));
test('both original runtime before sources and missing new helper/tests refuse current gate',()=>fixture(async(s,p)=>{for(const name of [...Object.keys(m.imageFstLoadingDerivation.runtimeMigrations),...Object.keys(m.imageFstLoadingDerivation.runtimeAdmissions)]){const file=path.join(s,name.slice(15)),data=await readFile(file);await writeFile(file,await readCaptureV11Source(name));await assert.rejects(()=>check(s,p));await writeFile(file,data);}for(const name of m.imageFstLoadingDerivation.newInstalledRuntimePaths.filter(n=>!m.imageFstLoadingDerivation.runtimeMigrations[n])){const file=path.join(s,name.slice(15)),data=await readFile(file);await unlink(file);await assert.rejects(()=>check(s,p));await writeFile(file,data);}}));
test('new five runtime/test paths retain canonical source and symlink refusals',async()=>{for(const name of m.imageFstLoadingDerivation.newInstalledRuntimePaths)await fixture(async(s,p,dir)=>{const file=path.join(s,name.slice(15)),alias=path.join(dir,'alias');await writeFile(alias,await readFile(file));await unlink(file);await symlink(alias,file);await assert.rejects(()=>check(s,p));});});
test('six bounded exact whole-before inputs reject corrupt, oversized and unknown history',async()=>{const h=await readCaptureV11History();assert.equal(Object.keys(h.files).length,6);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const [name,row]of Object.entries(h.files)){assert(Object.isFrozen(row));assert.equal(sha(Buffer.from(row.source)),row.sha256);assert.equal(await readCaptureV11Source(name),row.source);}const data=await readFile(new URL('./fixtures/capture-v11-loading-before.json.gz',import.meta.url)),bad=Buffer.from(data);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV11History(bad));assert.throws(()=>decodeCaptureV11History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV11History(new Uint8Array(data)));await assert.rejects(()=>readCaptureV11Source('unknown'));});
test('historical normalizer accepts only exact before or reviewed current and refuses unknown mutants',async()=>{const d=m.imageFstLoadingDerivation,h=await readCaptureV11History();for(const name of [...Object.keys(d.runtimeMigrations),...Object.keys(d.runtimeAdmissions),...Object.keys(d.fixtureMigrations)]){const data=await readFile(path.join(root,name));assert.equal((await recoverCaptureV11Input(name,data)).toString(),h.files[name].source);assert.equal((await recoverCaptureV11Input(name,Buffer.from(h.files[name].source))).toString(),h.files[name].source);await assert.rejects(()=>recoverCaptureV11Input(name,Buffer.concat([data,Buffer.from('\n')])));}});
test('all historical V11 assertions are byte-identical behind fixture-only input normalization',async()=>{const before=await readCaptureV11Source('browser-client/tests/tablet-capture-environment-manifest.test.mjs'),after=await readFile(new URL('./tablet-capture-environment-manifest.test.mjs',import.meta.url),'utf8');assert.equal(after.slice(after.indexOf("test('")),before.slice(before.indexOf("test('")));});
test('unchanged environment, limits and old20ce stay historical with no runtime or gain qualification',()=>{const d=m.imageFstLoadingDerivation;assert.equal(d.externalEnvironmentChanged,false);assert.equal(d.productionHistoricalFallback,false);assert.equal(d.actualProductionBuildQualified,false);assert.equal(d.actualNativeOrBrowserQualified,false);assert.equal(d.performanceGainClaim,false);assert.equal(d.oldProductionReceiptSHA256,'20cedb53d46a8b8b123b82bb385b6b380458c08cdaaa98256d506e97f0fc0212');for(const key of ['limits','verification','packagePins','reacquisitionDerivation','environmentReconciliationDerivation'])assert.deepEqual(m[key],old[key]);assert.deepEqual(m.files.find(r=>r.path==='docs/browser-client/BROWSER_MICROPHONE_CONTROLS.md'),old.files.find(r=>r.path==='docs/browser-client/BROWSER_MICROPHONE_CONTROLS.md'));assert.equal(d.newInstalledRuntimePaths.length,5);});
