// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink}from'node:fs/promises';import path from'node:path';import{fileURLToPath}from'node:url';import{tmpdir}from'node:os';import{createHash}from'node:crypto';
import{readCaptureV24History,readCaptureV24Source,recoverCaptureV24Input,decodeCaptureV24History}from'./integration/capture-event-timing-source-fixture.mjs';
import {readCaptureV25Source,recoverCaptureV25Input} from './integration/capture-delivery-angle-source-fixture.mjs';
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV25Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.dirname(client),bytes=await readFile(new URL('./fixtures/capture-event-timing-v25-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-command-clock-v24-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readCaptureV25Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs'),d=m.eventTimingDerivation;
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,gate=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-event-timing-'));try{const s=path.join(dir,'browser-client');for(const row of m.files){if(!row.path.startsWith('browser-client/'))continue;const dest=path.join(dir,row.path);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,row.path)),{mode:0o600,flag:'wx'});}for(const relative of ['.github/workflows/browser-client.yml','browser-client/lab/README.md']){const dest=path.join(dir,relative);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,relative)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(s,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>gate(assert,readFile,realpath,lstat,path,sha,s,p);
test('V25 preserves all215 published V24 rows with four finite migrations and five honest admissions',()=>{assert.equal(m.version,25);assert.equal(old.version,24);assert.equal(old.files.length,215);assert.equal(m.files.length,220);assert.equal(d.addedRows.length,5);assert.equal(Object.keys(d.sourceMigrations).length,4);assert.equal(d.previousManifestSHA256,sha(oldBytes));assert.equal(new Set(m.files.map(r=>r.path)).size,m.files.length);for(const row of old.files){const next=m.files.find(r=>r.path===row.path),change=d.sourceMigrations[row.path];assert.deepEqual(next,change?{...row,beforeSHA256:row.afterSHA256,afterSHA256:change.afterSHA256,bytes:change.bytes}:row);}for(const n of d.addedRows){assert(!old.files.some(r=>r.path===n));assert.equal(m.files.find(r=>r.path===n).beforeSHA256,null);}const expected=structuredClone(old);expected.version=25;expected.scope=m.scope;expected.files=m.files;expected.eventTimingDerivation=d;expected.reacquisitionDerivation.chromeEnvironmentSourcePins['browser-client/tests/integration/embedded-world.mjs']=d.currentRunnerSHA256;assert.deepEqual(m,expected);assert.equal(d.baselineGitCommit,'3329dfc45ec31244fdc15463c3eee1e17e6d869a');assert.equal(d.actualRuntimeAcceptance,false);});
test('actual current production gate checks all220 rows without history imports or changed exclusions',()=>fixture(async(s,p)=>{assert.equal((await check(s,p)).version,25);assert(prep.includes('(?:src|shared|gateway|tests|native-input|tools)'));assert(!prep.includes('recoverCapture'));assert(!prep.includes('source-fixture'));assert(!m.files.some(r=>r.path.startsWith('browser-client/lab/')));}));
test('old V24 invented version and unknown manifest newline refuse before source reads',()=>fixture(async(s,p)=>{for(const input of [oldBytes,Buffer.from(JSON.stringify({...m,version:24})),Buffer.concat([bytes,Buffer.from('\n')])]){await writeFile(p,input);let reads=0;await assert.rejects(()=>gate(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}}));
test('each migrated/admitted row refuses old missing symlink and changed bytes',()=>fixture(async(s,p,dir)=>{const h=await readCaptureV24History();for(const n of [...Object.keys(d.sourceMigrations),...d.addedRows]){const f=path.join(dir,n),current=await readFile(f);await writeFile(f,Buffer.concat([current,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));if(Object.hasOwn(h.files,n)&&h.files[n].sha256!==sha(current)){await writeFile(f,await readCaptureV24Source(n));await assert.rejects(()=>check(s,p));}await unlink(f);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'alias');await writeFile(alias,current);await symlink(alias,f);await assert.rejects(()=>check(s,p));await unlink(f);await unlink(alias);await writeFile(f,current);}}));
test('whole current preparer differs from V24 only by exact manifest literal',async()=>{const before=await readCaptureV24Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.split(sha(bytes)).length,2);assert.equal(prep.replace(sha(bytes),sha(oldBytes)),before);});
test('bounded six whole V24 inputs preserve all ten original V24 bodies and full source hashes',async()=>{const h=await readCaptureV24History();assert.equal(Object.keys(h.files).length,6);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const[n,r]of Object.entries(h.files))assert.equal(sha(Buffer.from(await readCaptureV24Source(n))),r.sha256);const n='browser-client/tests/tablet-capture-command-clock-manifest.test.mjs',current=await readFile(path.join(root,n),'utf8'),before=await readCaptureV24Source(n);assert.equal(current.slice(current.indexOf("test('")),before.slice(before.indexOf("test('")));assert.equal(sha(Buffer.from(before.slice(before.indexOf("test('")))),d.originalV24BodiesSHA256);const archive=await readFile(new URL('./fixtures/capture-v24-event-timing-before.json.gz',import.meta.url)),bad=Buffer.from(archive);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV24History(bad));assert.throws(()=>decodeCaptureV24History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV24History(new Uint8Array(archive)));});
test('CPU normalization accepts only each exact reviewed current or whole before source',async()=>{for(const n of Object.keys(d.sourceMigrations)){const before=Buffer.from(await readCaptureV24Source(n)),current=await readFile(path.join(root,n));assert.deepEqual(await recoverCaptureV24Input(n,before),before);assert.deepEqual(await recoverCaptureV24Input(n,current),before);for(const input of [Buffer.concat([before,Buffer.from('\n')]),Buffer.concat([current,Buffer.from('\n')]),Buffer.from('unknown')])await assert.rejects(()=>recoverCaptureV24Input(n,input));}await assert.rejects(()=>recoverCaptureV24Input('unknown',new Uint8Array()));await assert.rejects(()=>readCaptureV24Source('unknown'));});
test('Chrome20 metadata changes only embedded runner; all exact current dependencies match',async()=>{const prior=old.reacquisitionDerivation.chromeEnvironmentSourcePins,next=m.reacquisitionDerivation.chromeEnvironmentSourcePins;assert.equal(Object.keys(next).length,20);assert.deepEqual(Object.keys(next).filter(n=>next[n]!==prior[n]),['browser-client/tests/integration/embedded-world.mjs']);for(const[n,h]of Object.entries(next))assert.equal(sha(await readFile(path.join(root,n))),h);assert.equal(sha(await readFile(path.join(root,'browser-client/src/world.ts'))),d.unchangedWorldSHA256);assert.equal(d.debugWorkflowChanged,false);assert.equal(d.productionBackendChanged,false);});
test('GPU body and all original14 lifecycle assertions remain whole unchanged; v4 new semantics stay current',async()=>{const n='browser-client/tests/fixtures/embedded-world.ts',current=await readFile(path.join(root,n),'utf8'),before=await readCaptureV24Source(n),marker='export async function runEmbeddedWorldFixture()';assert.equal(current.slice(current.indexOf(marker)),before.slice(before.indexOf(marker)));assert(current.includes('version:4'));assert(current.includes('eventTimings'));assert(current.includes('performance.now()'));assert.equal(sha(await readFile(path.join(root,'browser-client/tests/embedded-world-lifecycle-diagnostics.test.mjs'))),d.original14LifecycleTestSHA256);assert.equal(d.legacyTupleWidths.join(','),'6,11,5');assert.equal(d.eventTimingRowsMaximum,16);});
test('all49 historical browser specs remain exact and private viewer is excluded',async()=>{for(const[n,h]of Object.entries(d.originalBrowserSpecSHA256))assert.equal(sha(await readFile(path.join(root,n))),h);assert.equal(Object.keys(d.originalBrowserSpecSHA256).length,49);assert(!m.files.some(r=>/viewer\.mjs$|viewer\.test\.mjs$/.test(r.path)));});
