// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {readCaptureV21History,readCaptureV21Source,recoverCaptureV21Input,decodeCaptureV21History} from './integration/capture-context-lifecycle-source-fixture.mjs';
import {recoverCaptureV22Input,readCaptureV22Source} from './integration/capture-live-context-source-fixture.mjs';
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV22Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.dirname(client),bytes=await readFile(new URL('./fixtures/capture-context-lifecycle-v22-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-context-type-v21-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readCaptureV22Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs'),d=m.contextLifecycleDerivation;
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,gate=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-lifecycle-'));try{const s=path.join(dir,'browser-client');for(const row of m.files){if(!row.path.startsWith('browser-client/'))continue;const dest=path.join(dir,row.path);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,row.path)),{mode:0o600,flag:'wx'});}for(const relative of ['.github/workflows/browser-client.yml','browser-client/lab/README.md']){const dest=path.join(dir,relative);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,relative)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(s,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>gate(assert,readFile,realpath,lstat,path,sha,s,p);
test('V22 preserves all190 V21 rows with finite reviewed migrations and honest new admissions',()=>{
 assert.equal(m.version,22);assert.equal(old.files.length,190);assert.equal(m.files.length,190+d.addedRows.length);assert.equal(new Set(m.files.map(r=>r.path)).size,m.files.length);assert.equal(d.previousManifestSHA256,sha(oldBytes));
 for(const row of old.files){const next=m.files.find(r=>r.path===row.path),change=d.sourceMigrations[row.path];assert.deepEqual(next,change?{...row,beforeSHA256:row.afterSHA256,afterSHA256:change.afterSHA256,bytes:change.bytes}:row);}
 for(const name of d.addedRows){assert(!old.files.some(r=>r.path===name));assert.equal(m.files.find(r=>r.path===name).beforeSHA256,null);}
 const expected=structuredClone(old);expected.version=22;expected.scope=m.scope;expected.files=m.files;expected.contextLifecycleDerivation=d;expected.reacquisitionDerivation.chromeEnvironmentSourcePins=m.reacquisitionDerivation.chromeEnvironmentSourcePins;assert.deepEqual(m,expected);assert.deepEqual(Object.keys(d.chromeEnvironmentSourceMigrations),['browser-client/tests/integration/embedded-world.mjs']);const currentEnvironment={...old.reacquisitionDerivation.chromeEnvironmentSourcePins};for(const[name,change]of Object.entries(d.chromeEnvironmentSourceMigrations)){assert.equal(change.beforeSHA256,currentEnvironment[name]);assert.equal(change.afterSHA256,m.files.find(row=>row.path===name).afterSHA256);currentEnvironment[name]=change.afterSHA256;}assert.deepEqual(m.reacquisitionDerivation.chromeEnvironmentSourcePins,currentEnvironment);
});
test('actual current production gate admits reviewed observations recovery and author boundary with unchanged finite exclusions',()=>fixture(async(s,p)=>{
 assert.equal((await check(s,p)).version,22);for(const name of [...Object.keys(d.sourceMigrations),...d.addedRows])assert(m.files.some(r=>r.path===name));assert(!m.files.some(r=>r.path==='browser-client/lab/native-participant.js'));assert(prep.includes('(?:src|shared|gateway|tests|native-input|tools)'));assert(!prep.includes('recoverCapture'));
}));
test('whole prior V21 altered version and unknown manifest bytes refuse before source reads',()=>fixture(async(s,p)=>{
 for(const input of [oldBytes,Buffer.from(JSON.stringify({...m,version:21})),Buffer.concat([bytes,Buffer.from('\n')])]){await writeFile(p,input);let reads=0;await assert.rejects(()=>gate(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}
}));
test('every new migrated row refuses missing symlink unknown newline and prior whole reviewed source',()=>fixture(async(s,p,dir)=>{
 const h=await readCaptureV21History();for(const name of [...Object.keys(d.sourceMigrations),...d.addedRows]){const f=path.join(dir,name),current=await readFile(f);await writeFile(f,Buffer.concat([current,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));if(Object.hasOwn(h.files,name)&&h.files[name].sha256!==sha(current)){await writeFile(f,await readCaptureV21Source(name));await assert.rejects(()=>check(s,p));}await unlink(f);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'alias');await writeFile(alias,current);await symlink(alias,f);await assert.rejects(()=>check(s,p));await unlink(f);await unlink(alias);await writeFile(f,current);}
}));
test('production preparer changes only exact current V22 digest without history imports or fallback',async()=>{
 const before=await readCaptureV21Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.split(sha(bytes)).length,2);assert.equal(prep.replace(sha(bytes),sha(oldBytes)),before);assert(!prep.includes('source-fixture'));assert(!prep.includes('recoverCapture'));
});
test('bounded complete V21 history and current CPU normalization preserve nine original V21 bodies',async()=>{
 const h=await readCaptureV21History();assert.equal(Object.keys(h.files).length,Object.keys(d.historyInputSHA256).length);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const[name,row]of Object.entries(h.files))assert.equal(sha(Buffer.from(await readCaptureV21Source(name))),row.sha256);
 for(const name of d.historyRecoveredCurrentPaths){const current=await readFile(path.join(root,name)),before=await readCaptureV21Source(name);assert.equal((await recoverCaptureV21Input(name,current)).toString(),before);assert.equal((await recoverCaptureV21Input(name,Buffer.from(before))).toString(),before);await assert.rejects(()=>recoverCaptureV21Input(name,Buffer.concat([current,Buffer.from('\n')])));if(name.endsWith('tablet-capture-context-type-manifest.test.mjs')){assert.equal(current.toString().slice(current.toString().indexOf("test('")),before.slice(before.indexOf("test('")));assert.equal(sha(Buffer.from(before.slice(before.indexOf("test('")+6))),d.originalV21NineBodySHA256);}}
 const b=await readFile(new URL('./fixtures/capture-v21-context-lifecycle-before.json.gz',import.meta.url)),bad=Buffer.from(b);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV21History(bad));assert.throws(()=>decodeCaptureV21History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV21History(new Uint8Array(b)));
});
function named(source,start,end){assert.equal(source.split(start).length,2);assert.equal(source.split(end).length,2);return source.slice(source.indexOf(start),source.indexOf(end));}
test('original direct render context sampler eleven tuple and all pixel upload statements remain unchanged',async()=>{
 const p='browser-client/tests/fixtures/embedded-world.ts',current=await readFile(path.join(root,p),'utf8'),before=await readCaptureV21Source(p);
 for(const[start,end]of [['function recordEmbeddedFrame(','function sampleEmbeddedRender('],['function sampleEmbeddedRender(','function recordEmbeddedContext('],['function recordEmbeddedContext(','function createEmbeddedLifecycle(']]){const oldEnd=end==='function createEmbeddedLifecycle('? '// END bounded embedded diagnostic.':end;assert.equal(named(current,start,end),named(before,start,oldEnd));}
 for(const statement of ["assert(gpuPixel.join(',')==='255,0,0,255','Actual GPU embedded pixels changed');","assert(uploads===1,'Independent samplers reuploaded their shared HTML Source');"]){assert.equal(before.split(statement).length,2);assert.equal(current.split(statement).length,2);}
 assert(!current.includes('forceContextLoss'));assert.equal(current.split('gl.getError()').length,before.split('gl.getError()').length);assert.equal(d.contextLossTriggerEstablished,false);
});
test('all original Chrome20 and49 ordinary browser specs remain exact without asserting new runtime success',async()=>{
 assert.equal(sha(await readFile(path.join(root,'browser-client/tests/tablet-capture-reacquisition-manifest.test.mjs'))),d.originalChrome20TestSHA256);assert.equal(Object.keys(d.chromeSpecSourcePins).length,49);for(const[name,hash]of Object.entries(d.chromeSpecSourcePins))assert.equal(sha(await readFile(path.join(root,name))),hash);for(const[name,hash]of Object.entries(m.reacquisitionDerivation.chromeEnvironmentSourcePins))assert.equal(sha(await readFile(path.join(root,name))),hash);for(const[name,hash]of Object.entries(d.newChromeSpecSourcePins)){assert(!Object.hasOwn(d.chromeSpecSourcePins,name));assert(d.addedRows.includes(name));assert.equal(sha(await readFile(path.join(root,name))),hash);}assert.equal(d.originalOrdinaryChromeBodiesUnchanged,true);assert.equal(d.newRestorationSpecIsSeparateDeliberateLossLane,true);assert.equal(d.actualChromeAcceptance,false);assert.equal(d.unchangedOriginalThirtySecondFixtureBound,true);assert.equal(d.unchangedSingleFiveHundredMillisecondSecondaryBound,true);
});
test('all reviewed central-helper old inputs survive normalization and unknown bytes still refuse',async()=>{
 const h=await readCaptureV21History();for(const name of d.historyRecoveredCurrentPaths){const before=Buffer.from(h.files[name].source),current=await readFile(path.join(root,name));assert.deepEqual(await recoverCaptureV21Input(name,before),before);assert.deepEqual(await recoverCaptureV21Input(name,current),before);await assert.rejects(()=>recoverCaptureV21Input(name,Buffer.concat([before,Buffer.from('\n')])));}
});
