// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {recoverCaptureV20Input,readCaptureV20Source} from './integration/capture-embedded-context-type-source-fixture.mjs';
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV20Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
import {readCaptureV19History,readCaptureV19Source,recoverCaptureV19Input,decodeCaptureV19History} from './integration/capture-native-author-source-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.dirname(client),bytes=await readFile(new URL('./fixtures/capture-native-author-v20-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-context-diagnostic-v19-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readCaptureV20Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs'),d=m.nativeAuthorRegistrationDerivation;
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,gate=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-author-'));try{const s=path.join(dir,'browser-client');for(const row of m.files){if(!row.path.startsWith('browser-client/'))continue;const dest=path.join(dir,row.path);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,row.path)),{mode:0o600,flag:'wx'});}for(const relative of ['.github/workflows/browser-client.yml','browser-client/lab/README.md']){const dest=path.join(dir,relative);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,relative)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(s,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>gate(assert,readFile,realpath,lstat,path,sha,s,p);
test('V20 preserves all179 V19 rows with one CPU plumbing migration and seven honest admissions',()=>{
 assert.equal(m.version,20);assert.equal(old.files.length,179);assert.equal(m.files.length,186);assert.equal(new Set(m.files.map(r=>r.path)).size,186);assert.equal(d.previousManifestSHA256,sha(oldBytes));assert.equal(Object.keys(d.sourceMigrations).length,1);assert.equal(d.addedRows.length,7);
 for(const row of old.files){const next=m.files.find(r=>r.path===row.path),change=d.sourceMigrations[row.path];assert.deepEqual(next,change?{...row,beforeSHA256:row.afterSHA256,afterSHA256:change.afterSHA256,bytes:change.bytes}:row);}
 for(const name of d.addedRows){assert(!old.files.some(r=>r.path===name));assert.equal(m.files.find(r=>r.path===name).beforeSHA256,null);}
 const expected=structuredClone(old);expected.version=20;expected.scope=m.scope;expected.files=m.files;expected.nativeAuthorRegistrationDerivation=d;assert.deepEqual(m,expected);assert.equal(d.frontendProductionChanged,false);assert.deepEqual(m.reacquisitionDerivation.chromeEnvironmentSourcePins,old.reacquisitionDerivation.chromeEnvironmentSourcePins);
});
test('actual current production gate admits exact reviewed registration files with unchanged finite path exclusions',()=>fixture(async(s,p)=>{
 assert.equal((await check(s,p)).version,20);for(const row of d.transportRepositoryChanges)assert(m.files.some(r=>r.path===row.path));assert(!m.files.some(r=>r.path==='browser-client/lab/native-participant.js'));assert(prep.includes('(?:src|shared|gateway|tests|native-input|tools)'));assert(!prep.includes('recoverCapture'));
}));
test('whole prior V19 altered version and unknown manifest bytes refuse before source reads',()=>fixture(async(s,p)=>{
 for(const input of [oldBytes,Buffer.from(JSON.stringify({...m,version:19})),Buffer.concat([bytes,Buffer.from('\n')])]){await writeFile(p,input);let reads=0;await assert.rejects(()=>gate(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}
}));
test('all new and migrated rows refuse missing symlink unknown newline and prior reviewed source bytes',()=>fixture(async(s,p,dir)=>{
 const h=await readCaptureV19History();for(const name of [...Object.keys(d.sourceMigrations),...d.addedRows]){const f=path.join(dir,name),current=await readFile(f);await writeFile(f,Buffer.concat([current,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));if(Object.hasOwn(h.files,name)&&h.files[name].sha256!==sha(current)){await writeFile(f,await readCaptureV19Source(name));await assert.rejects(()=>check(s,p));}await unlink(f);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'alias');await writeFile(alias,current);await symlink(alias,f);await assert.rejects(()=>check(s,p));await unlink(f);await unlink(alias);await writeFile(f,current);}
}));
test('production preparer changes only exact V20 digest with no historical import fallback',async()=>{
 const before=await readCaptureV19Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.split(sha(bytes)).length,2);assert.equal(prep.replace(sha(bytes),sha(oldBytes)),before);assert(!prep.includes('source-fixture'));assert(!prep.includes('recoverCapture'));
});
test('five complete prior sources and exact current CPU normalization retain all original V19 assertions',async()=>{
 const h=await readCaptureV19History();assert.equal(Object.keys(h.files).length,5);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const[name,row]of Object.entries(h.files))assert.equal(sha(Buffer.from(await readCaptureV19Source(name))),row.sha256);
 for(const name of d.historyRecoveredCurrentPaths){const current=await readFile(path.join(root,name)),before=await readCaptureV19Source(name);assert.equal((await recoverCaptureV19Input(name,current)).toString(),before);assert.equal((await recoverCaptureV19Input(name,Buffer.from(before))).toString(),before);await assert.rejects(()=>recoverCaptureV19Input(name,Buffer.concat([current,Buffer.from('\n')])));assert.equal(current.toString().slice(current.toString().indexOf("test('")),before.slice(before.indexOf("test('")));assert.equal(sha(Buffer.from(before.slice(before.indexOf("test('")+6))),d.originalV19TenBodySHA256);}
 const b=await readFile(new URL('./fixtures/capture-v19-native-author-before.json.gz',import.meta.url)),bad=Buffer.from(b);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV19History(bad));assert.throws(()=>decodeCaptureV19History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV19History(new Uint8Array(b)));
});
test('native registration changes recover whole old modules and preserve historical served pin and consent scope',async()=>{
 for(const row of d.transportRepositoryChanges){assert.equal(sha(await readFile(path.join(root,row.path))),row.afterSHA256);if(row.beforeSHA256){const before=await readCaptureV19Source(row.path);assert.equal(sha(Buffer.from(before)),row.beforeSHA256);}}
 const name='browser-client/tests/integration/tablet-ptt-native-peer.mjs',source=await readFile(path.join(root,name),'utf8'),before=await readCaptureV19Source(name);let recovered=source;
 for(const[oldPin,newPin]of [['c0648ce3fb6f4924cee122445ef6132e0770d15568b36bcc71aefe8204e0f17f','735a5ee9b4327963ea7fb2ebec5e2159c1196aa99d8b6e7fd996809f521b7ede'],['ac3bb49a0ab81913044e1c3c1cde78280098a6b0ff0c59d07f72ede7faba0ca8','1c386213ac2ddb89ae313db55a6df4df2ecd0a38a1d6be93ef545384bc4299fd']]){assert.equal(recovered.split(newPin).length,2);recovered=recovered.replace(newPin,oldPin);}assert.equal(recovered,before);assert(source.includes(d.historicalServedSourceSHA256));assert.equal(source.slice(source.indexOf('export function admitServedAuthor(')),before.slice(before.indexOf('export function admitServedAuthor(')));
});
test('whole original Chrome20 current source map and49 browser specs stay exact and primary negative remains negative',async()=>{
 assert.equal(sha(await readFile(path.join(root,'browser-client/tests/tablet-capture-reacquisition-manifest.test.mjs'))),d.originalChrome20TestSHA256);assert.equal(Object.keys(d.chromeSpecSourcePins).length,49);for(const[name,hash]of Object.entries(d.chromeSpecSourcePins))assert.equal(sha(await readFile(path.join(root,name))),hash);for(const[name,hash]of Object.entries(m.reacquisitionDerivation.chromeEnvironmentSourcePins))assert.equal(sha(await readFile(path.join(root,name))),hash);assert.deepEqual(d.originalFullSuiteFailure,{...d.originalFullSuiteFailure,tests:2709,pass:2706,fail:3,skipped:0});
});
