// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {readCaptureV22History,readCaptureV22Source,recoverCaptureV22Input,decodeCaptureV22History} from './integration/capture-live-context-source-fixture.mjs';
import {recoverCaptureV23Input,readCaptureV23Source} from './integration/capture-command-clock-source-fixture.mjs';
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV23Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.dirname(client),bytes=await readFile(new URL('./fixtures/capture-live-context-v23-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-context-lifecycle-v22-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readCaptureV23Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs'),d=m.liveContextFixtureDerivation;
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,gate=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-live-context-'));try{const s=path.join(dir,'browser-client');for(const row of m.files){if(!row.path.startsWith('browser-client/'))continue;const dest=path.join(dir,row.path);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,row.path)),{mode:0o600,flag:'wx'});}for(const relative of ['.github/workflows/browser-client.yml','browser-client/lab/README.md']){const dest=path.join(dir,relative);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,relative)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(s,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>gate(assert,readFile,realpath,lstat,path,sha,s,p);
test('V23 preserves all203 installed unpublished V22 rows with three finite migrations and six honest admissions',()=>{
 assert.equal(m.version,23);assert.equal(old.version,22);assert.equal(old.files.length,203);assert.equal(m.files.length,209);assert.equal(d.addedRows.length,6);assert.equal(Object.keys(d.sourceMigrations).length,3);assert.equal(d.previousManifestSHA256,sha(oldBytes));assert.equal(new Set(m.files.map(r=>r.path)).size,m.files.length);
 for(const row of old.files){const next=m.files.find(r=>r.path===row.path),change=d.sourceMigrations[row.path];assert.deepEqual(next,change?{...row,beforeSHA256:row.afterSHA256,afterSHA256:change.afterSHA256,bytes:change.bytes}:row);}
 for(const name of d.addedRows){assert(!old.files.some(r=>r.path===name));assert.equal(m.files.find(r=>r.path===name).beforeSHA256,null);}
 const expected=structuredClone(old);expected.version=23;expected.scope=m.scope;expected.files=m.files;expected.liveContextFixtureDerivation=d;assert.deepEqual(m,expected);assert.equal(d.productionBehaviourChanged,false);assert.equal(d.originalSixFullSuiteFailuresRetained,true);
});
test('actual production gate admits exact fixture repair rows with unchanged finite source exclusions',()=>fixture(async(s,p)=>{
 assert.equal((await check(s,p)).version,23);for(const name of [...Object.keys(d.sourceMigrations),...d.addedRows])assert(m.files.some(r=>r.path===name));assert(!m.files.some(r=>r.path==='browser-client/lab/native-participant.js'));assert(prep.includes('(?:src|shared|gateway|tests|native-input|tools)'));assert(!prep.includes('recoverCapture'));
}));
test('old V22 altered version and extra manifest newline refuse before source reads',()=>fixture(async(s,p)=>{
 for(const input of [oldBytes,Buffer.from(JSON.stringify({...m,version:22})),Buffer.concat([bytes,Buffer.from('\n')])]){await writeFile(p,input);let reads=0;await assert.rejects(()=>gate(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}
}));
test('all declared fixture rows refuse missing symlink unknown newline and exact prior source bytes',()=>fixture(async(s,p,dir)=>{
 const h=await readCaptureV22History();for(const name of [...Object.keys(d.sourceMigrations),...d.addedRows]){const f=path.join(dir,name),current=await readFile(f);await writeFile(f,Buffer.concat([current,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));if(Object.hasOwn(h.files,name)&&h.files[name].sha256!==sha(current)){await writeFile(f,await readCaptureV22Source(name));await assert.rejects(()=>check(s,p));}await unlink(f);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'alias');await writeFile(alias,current);await symlink(alias,f);await assert.rejects(()=>check(s,p));await unlink(f);await unlink(alias);await writeFile(f,current);}
}));
test('production preparer changes one exact manifest literal with no historical runtime fallback',async()=>{
 const before=await readCaptureV22Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.split(sha(bytes)).length,2);assert.equal(prep.replace(sha(bytes),sha(oldBytes)),before);assert(!prep.includes('source-fixture'));assert(!prep.includes('recoverCapture'));
});
test('bounded entire V22 archive preserves whole nine original current assertion bodies',async()=>{
 const h=await readCaptureV22History();assert.equal(Object.keys(h.files).length,7);assert.equal(Object.keys(h.files).length,Object.keys(d.historyInputSHA256).length);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const[name,row]of Object.entries(h.files))assert.equal(sha(Buffer.from(await readCaptureV22Source(name))),row.sha256);
 const name='browser-client/tests/tablet-capture-context-lifecycle-manifest.test.mjs',current=await readFile(path.join(root,name),'utf8'),before=await readCaptureV22Source(name);assert.equal(current.slice(current.indexOf("test('")),before.slice(before.indexOf("test('")));assert.equal(sha(Buffer.from(before.slice(before.indexOf("test('")+6))),d.originalV22NineBodySHA256);
 const bytes=await readFile(new URL('./fixtures/capture-v22-live-context-before.json.gz',import.meta.url)),bad=Buffer.from(bytes);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV22History(bad));assert.throws(()=>decodeCaptureV22History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV22History(new Uint8Array(bytes)));
});
test('three repair files preserve entire original assertions and exact current full-source recoveries',async()=>{
 for(const[name,hash]of Object.entries(d.originalFixtureBodySHA256)){const before=await readCaptureV22Source(name),current=await readFile(path.join(root,name),'utf8');assert.equal(current.slice(current.indexOf('test(')),before.slice(before.indexOf('test(')));assert.equal(sha(Buffer.from(before.slice(before.indexOf('test(')+5))),hash);assert.equal((await recoverCaptureV22Input(name,Buffer.from(current))).toString(),before);}
 const timing=await readFile(path.join(root,'browser-client/src/world-cpu-segments.test.ts'),'utf8'),image=await readFile(path.join(root,'browser-client/tests/world-native-image-effects.test.ts'),'utf8'),escape=await readFile(path.join(root,'browser-client/tests/world-owned-escape.test.mjs'),'utf8');assert(timing.includes('abort:owner,graphicsContextAvailable:true'));assert(timing.includes('getContext:()=>({isContextLost:()=>false})'));assert(image.includes('abort,disposed:false,graphicsContextAvailable:true'));assert(image.includes('getContext:()=>({isContextLost:()=>false})'));assert(escape.includes("recoverCaptureV21Input('browser-client/src/world.ts',readFileSync("));assert(escape.includes("assert.equal(controls(current),controls(after),'Actual current installControls must equal the qualified one-hunk method');"));
});
test('all production source and old20 plus49 and separate restore browser bodies remain exact',async()=>{
 for(const[name,hash]of Object.entries(d.unchangedProductionSourcePins))assert.equal(sha(await readFile(path.join(root,name))),hash);assert.equal(sha(await readFile(path.join(root,'browser-client/tests/tablet-capture-reacquisition-manifest.test.mjs'))),d.originalChrome20TestSHA256);assert.equal(Object.keys(d.chromeSpecSourcePins).length,49);for(const[name,hash]of Object.entries({...d.chromeSpecSourcePins,...d.separateRestorationSpecSourcePins}))assert.equal(sha(await readFile(path.join(root,name))),hash);assert.equal(d.actualRuntimeAcceptance,false);assert.deepEqual(m.reacquisitionDerivation,old.reacquisitionDerivation);
});
test('exact old current fixture inputs recover while unknown source drift remains refused',async()=>{
 const h=await readCaptureV22History();for(const name of d.historyRecoveredCurrentPaths){const before=Buffer.from(h.files[name].source),current=await readFile(path.join(root,name));assert.deepEqual(await recoverCaptureV22Input(name,before),before);assert.deepEqual(await recoverCaptureV22Input(name,current),before);await assert.rejects(()=>recoverCaptureV22Input(name,Buffer.concat([before,Buffer.from('\n')])));await assert.rejects(()=>recoverCaptureV22Input(name,Buffer.concat([current,Buffer.from('\n')])));}
});
