// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,mkdir,rm,symlink} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';import {decodeCaptureSourceHistory,copyCaptureFixtureRow,readCaptureHistoricalPreparer} from './integration/capture-source-fixture.mjs';
import {recoverCaptureV21Input} from './integration/capture-context-lifecycle-source-fixture.mjs';
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV21Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),archive=await readFile(new URL('./fixtures/capture-source-history-v5-world-key.json.gz',import.meta.url)),history=decodeCaptureSourceHistory(archive);
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-source-fixture-'));try{return await fn(dir);}finally{await rm(dir,{recursive:true,force:true});}}
test('one fixed bounded archive preserves all ten exact original source inputs and the v5 preparer',()=>{assert(archive.length<=65536);assert.equal(Object.keys(history.files).length,10);assert(Object.isFrozen(history)&&Object.isFrozen(history.files));for(const row of Object.values(history.files)){assert(Object.isFrozen(row));assert.equal(sha(Buffer.from(row.source)),row.sha256);}assert.equal(history.preparer.sha256,'ff1430f16e58a837d969e2d2e860ff902f4c8bf7f6b1f4cd61416fbcb8fe2d30');});
test('every known changed v5 input recovers exact before bytes; original verification never copies mutable current bytes as history',()=>fixture(async dir=>{for(const [relative,row] of Object.entries(history.files)){const dest=path.join(dir,path.basename(relative));await copyCaptureFixtureRow({client,relative,dest,expectedSHA256:row.sha256,version:5});assert.equal(sha(await readFile(dest)),row.sha256);}}));
test('historical v4 Audio and Target retain separately verified old snapshots without relaxing new runtime inputs',()=>fixture(async dir=>{for(const relative of ['src/audio.ts','src/browser-capture-target.ts']){const manifest=JSON.parse(await readFile(new URL('./fixtures/layout-v4-gzip-complete-source-manifest.json',import.meta.url))),row=manifest.files.find(v=>v.path==='browser-client/'+relative),dest=path.join(dir,path.basename(relative));await copyCaptureFixtureRow({client,relative,dest,expectedSHA256:row.afterSHA256,version:4});assert.equal(sha(await readFile(dest)),row.afterSHA256);}}));
test('current v6 refuses historical expectations and accepts only its actual exact current bytes',()=>fixture(async dir=>{const relative='src/main.ts',old=history.files[relative].sha256,dest=path.join(dir,'main.ts');await assert.rejects(copyCaptureFixtureRow({client,relative,dest,expectedSHA256:old,version:6}),/refused/);const current=sha(await readFile(path.join(client,relative)));await copyCaptureFixtureRow({client,relative,dest,expectedSHA256:current,version:6});assert.equal(sha(await readFile(dest)),current);}));
test('unknown live source drift and symlink aliases refuse before a historical output is written',()=>fixture(async dir=>{const source=path.join(dir,'client'),relative='src/main.ts';await mkdir(path.join(source,'src'),{recursive:true});const file=path.join(source,relative),bytes=await readFile(path.join(client,relative));await writeFile(file,Buffer.concat([bytes,Buffer.from('\n')]));await assert.rejects(copyCaptureFixtureRow({client:source,relative,dest:path.join(dir,'drift.ts'),expectedSHA256:history.files[relative].sha256,version:5}),/refused/);const alias=path.join(source,'src/alias.ts');await writeFile(alias,bytes);const link='src/link.ts';await symlink(alias,path.join(source,link));await assert.rejects(copyCaptureFixtureRow({client:source,relative:link,dest:path.join(dir,'link.ts'),expectedSHA256:sha(bytes),version:6}),/refused/);}));
test('corrupt oversized and substituted archives cannot create historical fixture authority',()=>{for(const bytes of [Buffer.from('untrusted'),Buffer.alloc(65537),Buffer.concat([archive,Buffer.from('x')]),Buffer.from(archive).fill(0,30,31)])assert.throws(()=>decodeCaptureSourceHistory(bytes),/refused/);});
test('foreign versions traversal and wrong expected prior hashes refuse; destinations remain exclusively owned',()=>fixture(async dir=>{const relative='src/main.ts';for(const version of [0,7,'5'])await assert.rejects(copyCaptureFixtureRow({client,relative,dest:path.join(dir,'wrong.ts'),expectedSHA256:history.files[relative].sha256,version}),/refused/);await assert.rejects(copyCaptureFixtureRow({client,relative:'src/../main.ts',dest:path.join(dir,'path.ts'),expectedSHA256:'0'.repeat(64),version:5}),/refused/);await assert.rejects(copyCaptureFixtureRow({client,relative,dest:path.join(dir,'hash.ts'),expectedSHA256:'0'.repeat(64),version:5}),/refused/);const dest=path.join(dir,'existing.ts');await writeFile(dest,'retained');await assert.rejects(copyCaptureFixtureRow({client,relative,dest,expectedSHA256:sha(await readFile(path.join(client,relative))),version:6}));assert.equal(await readFile(dest,'utf8'),'retained');}));
test('fixed historical preparer reader refuses arbitrary versions and returns exact v4/v5 source strings',async()=>{assert.equal(sha(Buffer.from(await readCaptureHistoricalPreparer(5))),'ff1430f16e58a837d969e2d2e860ff902f4c8bf7f6b1f4cd61416fbcb8fe2d30');assert.equal(sha(Buffer.from(await readCaptureHistoricalPreparer(4))),'80c2ce58e464ae7f91755d6493fccd8046105bfd0dd80ea9c86af4d33dce02bd');await assert.rejects(readCaptureHistoricalPreparer(6),/refused/);});


test('exact pre-palette generator and style control recover for both historical versions; current version refuses them',()=>fixture(async dir=>{
 for(const version of [4,5])for(const relative of ['gateway/browser-capture-overrides.mjs','tests/tablet-capture-style.test.mjs']){const row=history.files[relative],dest=path.join(dir,version+'-'+path.basename(relative));await copyCaptureFixtureRow({client,relative,dest,expectedSHA256:row.sha256,version});assert.equal(sha(await readFile(dest)),row.sha256);}
 for(const relative of ['gateway/browser-capture-overrides.mjs','tests/tablet-capture-style.test.mjs'])await assert.rejects(copyCaptureFixtureRow({client,relative,dest:path.join(dir,'current-'+path.basename(relative)),expectedSHA256:history.files[relative].sha256,version:6}),/refused/);
}));

test('width history recovers exact original gates for v4 and v5 while v6 refuses old width source',()=>fixture(async dir=>{
 const relative='tests/tablet-capture-switch-width.test.mjs',row=history.files[relative];
 for(const version of [4,5]){const dest=path.join(dir,'width-'+version+'.mjs');await copyCaptureFixtureRow({client,relative,dest,expectedSHA256:row.sha256,version});assert.equal(sha(await readFile(dest)),row.sha256);}
 await assert.rejects(copyCaptureFixtureRow({client,relative,dest:path.join(dir,'width-current.mjs'),expectedSHA256:row.sha256,version:6}),/refused/);
}));
