// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {gunzipSync} from 'node:zlib';import vm from 'node:vm';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {buildBrowserCaptureUI,AUDIO_SCRIPT_SHA256} from '../gateway/browser-capture-overrides.mjs';
import {readCaptureV8Source} from './integration/capture-status-source-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),before=await readCaptureV8Source('gateway/browser-capture-overrides.mjs'),after=await readFile(new URL('../gateway/browser-capture-overrides.mjs',import.meta.url),'utf8'),anchors=JSON.parse(await readFile(new URL('./fixtures/capture-status-layout-source-anchors.json',import.meta.url))),proofBytes=await readFile(new URL('./fixtures/capture-status-layout-measured.json',import.meta.url)),proof=JSON.parse(proofBytes);
function recover(s){for(const[a,b]of anchors.toReversed()){assert.equal(s.split(b).length,2);s=s.replace(b,a);}return s;}
const audio=gunzipSync(await readFile(new URL('../gateway/fixtures/native-audio-f91d15a.js.gz',import.meta.url))).toString(),channel='overte.browser.capture.'+'0'.repeat(32),url='file:///tmp/authored/browser-audio.qml';
const start=before.indexOf('export function buildBrowserCaptureUI('),end=before.indexOf('\nexport async function loadBrowserCapturePackage',start),context={createHash,AUDIO_SCRIPT_SHA256,URL,path,fileURLToPath,once:(s,a,b)=>{assert.equal(s.split(a).length,2);return s.replace(a,b);}};assert(start>=0&&end>start);vm.runInNewContext(before.slice(start,end).replace(/^export /,'')+';this.generate=buildBrowserCaptureUI;',context);const old=context.generate(audio,channel,url),fresh=buildBrowserCaptureUI(audio,channel,url);
test('current qualified factory and generated QML recover complete v8 before; native script/control behavior unchanged',()=>{assert.equal(sha(before),proof.beforeFactorySHA256);assert.equal(sha(after),proof.afterFactorySHA256);assert.equal(recover(after),before);assert.equal(recover(fresh.qml),old.qml);assert.equal(fresh.script,old.script);assert.throws(()=>recover(old.qml));assert.throws(()=>recover(fresh.qml.replace(anchors[0][1],anchors[0][1]+anchors[0][1])));});
test('actual current height expression fits retained real Qt52 measurements across every state and four widths',()=>{
 const expression=fresh.qml.match(/height:(Math\.max\(captureStatusSize0\.implicitHeight,[^;]+\));/);assert(expression);
 const reasons=['notReady','inactiveState','awaiting','busy','ok','inactive','unsupported','apply-refused','readback-mismatch','rollback-refused','deadline','cancelled'];
 assert.equal(proof.softwareQtVersion,'5.15.3');assert.equal(proof.candidateRows.length,52);assert.equal(proof.notNewActualExecution,true);
 for(const width of[240,320,480,640]){const rows=proof.candidateRows.filter(r=>r.width===width);assert.equal(rows.length,13);const values=Object.fromEntries(reasons.map((reason,i)=>{const r=rows.find(r=>r.reason===reason);assert(r);return['captureStatusSize'+i,{implicitHeight:r.statusContentHeight}];}));const height=vm.runInNewContext(expression[1],values);for(const row of rows){assert(row.passed&&row.stable&&row.fits);assert.equal(height,row.statusHeight);assert(row.statusContentHeight<=height);}assert.equal(new Set(rows.map(r=>r.gainCenterY)).size,1);assert(rows.filter(r=>['notReady','inactiveState','awaiting'].includes(r.reason)).every(r=>!r.gainEnabled));}
 const [normal,busy]=proof.originalRows;assert.equal(normal.gainCenterY-busy.gainCenterY,18);assert(normal.gainEnabled&&busy.gainEnabled);assert.equal(proof.candidateRows.find(r=>r.width===480&&r.reason==='ok').gainCenterY,normal.gainCenterY);
 // A fixed two-line region fails the independently measured three-line narrow states.
 assert(proof.candidateRows.some(r=>r.width===240&&r.statusContentHeight>36));
});
test('every full existing message is independently measured at identical font/width/wrap, including longest wrapped narrow state',()=>{const reasons=['inactive','unsupported','apply-refused','readback-mismatch','rollback-refused','deadline','cancelled'];const messages=['Waiting for browser readback…','Enable your microphone in the browser to inspect and change capture settings.','Applying capture settings…','Inspecting current capture settings…','These controls affect your local browser microphone. Native mixer gains and device choices are separate.',...reasons.map(r=>'The browser did not apply this change ('+r+').')];assert.equal(messages.length,12);for(const[i,m]of messages.entries())assert(fresh.qml.includes('Text{id:captureStatusSize'+i+';width:parent.width;font:captureStatus.font;wrapMode:Text.Wrap;text:'+JSON.stringify(m)+'}'));assert(fresh.qml.includes('Item{id:captureStatusReserve;visible:false;width:captureStatus.width;'));assert(!anchors.map(v=>v[1]).join('').match(/maximumLineCount|elide:|clip:/));});
test('ordinary callbacks, native Loader, timer, gain geometry/settings and no-implicit permission remain complete unchanged',()=>{for(const marker of ['function fromScript(','function change(','HifiControlsUit.Switch {id:echoControl;','Timer{interval:500;']){const a=old.qml.indexOf(marker),b=fresh.qml.indexOf(marker);assert(a>=0&&b>=0);const z=marker==='HifiControlsUit.Switch {id:echoControl;'?old.qml.length:old.qml.indexOf('\n',a),t=marker==='HifiControlsUit.Switch {id:echoControl;'?fresh.qml.length:fresh.qml.indexOf('\n',b);assert.equal(fresh.qml.slice(b,t),old.qml.slice(a,z));}assert.equal(fresh.script,old.script);assert.throws(()=>buildBrowserCaptureUI(audio+'\n',channel,url));assert.throws(()=>buildBrowserCaptureUI(audio,'unapproved.channel',url));assert.throws(()=>buildBrowserCaptureUI(audio,channel,'https://example.invalid/browser-audio.qml'));});
