// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {recoverCaptureV19Input,readCaptureV19Source} from './integration/capture-native-author-source-fixture.mjs';
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV19Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
import {readCaptureV18History,readCaptureV18Source,recoverCaptureV18Input,decodeCaptureV18History} from './integration/capture-embedded-context-source-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.dirname(client),bytes=await readFile(new URL('./fixtures/capture-context-diagnostic-v19-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-embedded-diagnostic-v18-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readCaptureV19Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs'),d=m.contextDiagnosticDerivation;
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,gate=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-context-'));try{const s=path.join(dir,'browser-client');for(const row of m.files){if(!row.path.startsWith('browser-client/'))continue;const dest=path.join(dir,row.path);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,row.path)),{mode:0o600,flag:'wx'});}for(const relative of ['.github/workflows/browser-client.yml','browser-client/lab/README.md']){const dest=path.join(dir,relative);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,relative)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(s,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>gate(assert,readFile,realpath,lstat,path,sha,s,p);

test('V19 preserves all170 V18 rows with six exact migrations nine admissions and one Chrome20 migration',()=>{
 assert.equal(m.version,19);assert.equal(old.files.length,170);assert.equal(m.files.length,179);assert.equal(new Set(m.files.map(r=>r.path)).size,179);assert.equal(d.previousManifestSHA256,sha(oldBytes));assert.equal(Object.keys(d.sourceMigrations).length,6);assert.equal(d.addedRows.length,9);
 for(const row of old.files){const next=m.files.find(r=>r.path===row.path),change=d.sourceMigrations[row.path];assert(next);assert.deepEqual(next,change?{...row,beforeSHA256:row.afterSHA256,afterSHA256:change.afterSHA256,bytes:change.bytes}:row);}
 const expected=structuredClone(old);expected.version=19;expected.scope=m.scope;expected.files=m.files;expected.reacquisitionDerivation.chromeEnvironmentSourcePins['browser-client/tests/integration/embedded-world.mjs']=d.chromeEnvironmentMigrations['browser-client/tests/integration/embedded-world.mjs'].afterSHA256;expected.contextDiagnosticDerivation=d;assert.deepEqual(m,expected);assert.equal(d.frontendProductionChanged,false);
});
test('actual current pre-copy production gate admits exact context and avatar source rows without a lab allow-rule',()=>fixture(async(s,p)=>{
 assert.equal((await check(s,p)).version,19);for(const name of [...Object.keys(d.sourceMigrations),...d.addedRows])assert(m.files.some(r=>r.path===name));assert(!m.files.some(r=>r.path==='browser-client/lab/native-participant.js'));assert(prep.includes('(?:src|shared|gateway|tests|native-input|tools)'));assert(!prep.includes('recoverCapture'));
}));
test('old whole V18 and invented manifests refuse before current source read',()=>fixture(async(s,p)=>{
 for(const input of [oldBytes,Buffer.from(JSON.stringify({...m,version:18})),Buffer.concat([bytes,Buffer.from('\n')])]){await writeFile(p,input);let reads=0;await assert.rejects(()=>gate(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}
}));
test('every current migration and admission rejects unknown missing symlink and authenticated prior sources',()=>fixture(async(s,p,dir)=>{
 const history=await readCaptureV18History();for(const name of [...Object.keys(d.sourceMigrations),...d.addedRows]){const f=path.join(dir,name),current=await readFile(f);await writeFile(f,Buffer.concat([current,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));if(Object.hasOwn(history.files,name)&&history.files[name].sha256!==sha(current)){await writeFile(f,await readCaptureV18Source(name));await assert.rejects(()=>check(s,p));}await unlink(f);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'alias');await writeFile(alias,current);await symlink(alias,f);await assert.rejects(()=>check(s,p));await unlink(f);await unlink(alias);await writeFile(f,current);}
}));
test('production preparer is exactly one manifest literal migration and never imports historical recovery',async()=>{
 const before=await readCaptureV18Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.split(sha(bytes)).length,2);assert.equal(prep.replace(sha(bytes),sha(oldBytes)),before);assert(!prep.includes('source-fixture'));assert(!prep.includes('recoverCapture'));assert(!prep.includes('native-participant.js'));
});
test('bounded CPU history authenticates twelve whole V18 inputs and rejects unknown or malformed recovery',async()=>{
 const h=await readCaptureV18History();assert.equal(Object.keys(h.files).length,12);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const[name,row]of Object.entries(h.files))assert.equal(sha(Buffer.from(await readCaptureV18Source(name))),row.sha256);
 for(const name of d.historyRecoveredCurrentPaths){const current=await readFile(path.join(root,name));assert.equal((await recoverCaptureV18Input(name,current)).toString(),h.files[name].source);assert.equal((await recoverCaptureV18Input(name,Buffer.from(h.files[name].source))).toString(),h.files[name].source);await assert.rejects(()=>recoverCaptureV18Input(name,Buffer.concat([current,Buffer.from('\n')])));}
 const b=await readFile(new URL('./fixtures/capture-v18-embedded-context-before.json.gz',import.meta.url)),bad=Buffer.from(b);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV18History(bad));assert.throws(()=>decodeCaptureV18History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV18History(new Uint8Array(b)));
});
test('whole context source inverses preserve original11tuple20frames pixels upload cancellation and500ms read',async()=>{
 for(const[name,anchors]of Object.entries(d.contextSourceInverseAnchors)){let source=await readFile(path.join(root,name),'utf8');for(const{before,after}of [...anchors].reverse()){assert.equal(source.split(after).length,2);source=source.replace(after,before);}assert.equal(source,await readCaptureV18Source(name));}
 const producer=await readFile(path.join(root,'browser-client/tests/fixtures/embedded-world.ts'),'utf8');assert(producer.includes('if(diagnostic.contextStates.length<20)'));assert(producer.includes('isContextLostBefore=gl.isContextLost()?1:0'));assert(producer.includes('renderer.info.render.frame,isContextLostBefore,gl.isContextLost()?1:0'));assert(!producer.includes('COMPLETION_STATUS_KHR'));assert(!producer.includes('isReady()'));
});
test('original eleven V18 and seven diagnostic bodies plus entire Chrome20 and49 browser spec sources stay exact',async()=>{
 for(const name of ['browser-client/tests/tablet-capture-embedded-diagnostic-manifest.test.mjs','browser-client/tests/embedded-world-diagnostics.test.mjs']){const before=await readCaptureV18Source(name),current=await readFile(path.join(root,name),'utf8');assert.equal(current.slice(current.indexOf("test('")),before.slice(before.indexOf("test('")));}
 assert.equal(sha(await readFile(path.join(root,'browser-client/tests/tablet-capture-reacquisition-manifest.test.mjs'))),d.originalChrome20TestSHA256);assert.equal(Object.keys(d.chromeSpecSourcePins).length,49);for(const[name,hash]of Object.entries(d.chromeSpecSourcePins))assert.equal(sha(await readFile(path.join(root,name))),hash);
});
test('current20 Chrome metadata migrates only exact new embedded runner and rejects original or unknown current bytes',async()=>{
 const before=old.reacquisitionDerivation.chromeEnvironmentSourcePins,current=m.reacquisitionDerivation.chromeEnvironmentSourcePins;assert.equal(Object.keys(current).length,20);assert.deepEqual(Object.keys(current).filter(k=>current[k]!==before[k]),['browser-client/tests/integration/embedded-world.mjs']);for(const[name,hash]of Object.entries(current))assert.equal(sha(await readFile(path.join(root,name))),hash);
 const name='browser-client/tests/integration/embedded-world.mjs',expected=current[name];assert.notEqual(sha(Buffer.from(await readCaptureV18Source(name))),expected);assert.notEqual(sha(Buffer.concat([await readFile(path.join(root,name)),Buffer.from('\n')])),expected);
});
test('avatar source inverses and proper author dependency preserve original sampler projection and curation contracts',async()=>{
 for(const[name,anchors]of Object.entries(d.avatarRateDerivation.inverseAnchors)){let source=await readFile(path.join(root,name),'utf8');for(const{before,after}of [...anchors].reverse()){assert.equal(source.split(after).length,2);source=source.replace(after,before);}assert.equal(source,await readCaptureV18Source(name));}
 const participant=d.avatarRateDerivation.authorDependencyMigration;assert.equal(participant.path,'browser-client/lab/native-participant.js');const f=path.join(root,participant.path);assert((await lstat(f)).isFile());assert.equal(await realpath(f),f);assert.equal(sha(await readFile(f)),participant.afterSHA256);assert.notEqual(participant.afterSHA256,participant.beforeSHA256);
 for(const[name,hash]of Object.entries(d.avatarRateDerivation.unchangedSourcePins))assert.equal(sha(await readFile(path.join(root,name))),hash);
});
