// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {BrowserTablet} from '../src/tablet';
function fixture(){const sent:Record<string,unknown>[]=[];const tablet=Object.create(BrowserTablet.prototype) as BrowserTablet;Object.assign(tablet,{connected:true,disposed:false,visible:false,revision:2,sequence:8,navigationSequence:8,generation:0,worldKeyRequest:0,worldKeyReady:false,worldKeyAwaiting:false,worldCanvasFocused:false,clearPointer(){},options:{send:(value:Record<string,unknown>)=>sent.push(value)}});const canvas={};const descriptor=Object.getOwnPropertyDescriptor(globalThis,'document');const doc={hidden:false,hasFocus:()=>true,activeElement:canvas};Object.defineProperty(globalThis,'document',{configurable:true,value:doc});return {tablet,sent,canvas,doc,close(){if(descriptor)Object.defineProperty(globalThis,'document',descriptor);else Reflect.deleteProperty(globalThis,'document');},event:(extra={})=>({target:canvas,isTrusted:true,key:'x',code:'KeyX',repeat:false,isComposing:false,defaultPrevented:false,ctrlKey:false,metaKey:false,altKey:false,shiftKey:false,...extra} as unknown as KeyboardEvent),ack:(extra={})=>tablet.receive({type:'tablet',kind:'worldKeyReady',revision:2,navigationSequence:8,requestId:9,ready:true,...extra} as Parameters<BrowserTablet['receive']>[0])};}
test('actual BrowserTablet methods wait for exact native ready and emit only one world X',()=>{const f=fixture();try{f.tablet.worldInputFocus(true);assert.equal(f.sent[0].action,'worldKeyArm');assert.equal(f.tablet.worldKey(f.event(),f.canvas as HTMLCanvasElement),false);f.ack();assert.equal(f.tablet.worldInputReady,true);assert.equal(f.tablet.worldKey(f.event(),f.canvas as HTMLCanvasElement),true);assert.equal(f.sent.at(-1)?.action,'worldKey');assert.equal(f.sent.at(-1)?.navigationSequence,8);}finally{f.close();}});
test('actual browser method refuses stale native ACK, foreign canvas, synthetic/repeat/modifier/hidden/unfocused input',()=>{const f=fixture();try{f.tablet.worldInputFocus(true);f.ack({requestId:8});assert.equal(f.tablet.worldInputReady,false);f.ack({navigationSequence:7});assert.equal(f.tablet.worldInputReady,false);f.ack();for(const change of [{isTrusted:false},{isComposing:true},{defaultPrevented:true},{repeat:true},{key:'X'},{code:'KeyW'},{ctrlKey:true},{altKey:true},{metaKey:true},{shiftKey:true},{target:{}}])assert.equal(f.tablet.worldKey(f.event(change),f.canvas as HTMLCanvasElement),false);f.doc.hidden=true;assert.equal(f.tablet.worldKey(f.event(),f.canvas as HTMLCanvasElement),false);f.doc.hidden=false;f.doc.hasFocus=()=>false;assert.equal(f.tablet.worldKey(f.event(),f.canvas as HTMLCanvasElement),false);f.doc.hasFocus=()=>true;f.doc.activeElement={};assert.equal(f.tablet.worldKey(f.event(),f.canvas as HTMLCanvasElement),false);}finally{f.close();}});
test('actual blur cancellation invalidates old ACK and a new focus gets new request',()=>{const f=fixture();try{f.tablet.worldInputFocus(true);f.ack();f.tablet.worldInputFocus(false);assert.equal(f.sent.at(-1)?.action,'worldKeyCancel');f.ack();assert.equal(f.tablet.worldKey(f.event(),f.canvas as HTMLCanvasElement),false);f.tablet.worldInputFocus(true);assert.equal(f.sent.at(-1)?.sequence,11);f.ack();assert.equal(f.tablet.worldInputReady,false);f.ack({requestId:11});assert.equal(f.tablet.worldInputReady,true);}finally{f.close();}});

test('repeated ordinary canvas activation does not replace a pending/current grant, but blur permits genuine rearm',()=>{const f=fixture();try{f.tablet.worldInputFocus(true);f.tablet.worldInputFocus(true);assert.equal(f.sent.length,1);f.ack();f.tablet.worldInputFocus(true);assert.equal(f.sent.length,1);assert.equal(f.tablet.worldInputReady,true);f.tablet.worldInputFocus(false);f.tablet.worldInputFocus(true);assert.equal(f.sent.at(-1)?.action,'worldKeyArm');}finally{f.close();}});

test('only a new genuine activation can rearm a replied-false grant; pending and ready duplicate suppression remains',()=>{const f=fixture();try{f.tablet.worldInputFocus(true);f.tablet.worldInputFocus(true,true);assert.equal(f.sent.length,1);f.ack({ready:false});f.tablet.worldInputFocus(true);assert.equal(f.sent.length,1);f.tablet.worldInputFocus(true,true);assert.equal(f.sent.length,2);assert.equal(f.sent.at(-1)?.action,'worldKeyArm');assert.equal(f.sent.at(-1)?.sequence,10);f.ack({requestId:9,ready:true});assert.equal(f.tablet.worldInputReady,false);f.ack({requestId:10,ready:true});f.tablet.worldInputFocus(true,true);assert.equal(f.sent.length,2);assert.equal(f.tablet.worldInputReady,true);}finally{f.close();}});

test('actual QML missing-root refusal unlocks only a new genuine browser activation after the root appears',()=>{const f=fixture();try{const qml=readFileSync(new URL('../gateway/tablet-capture.qml',import.meta.url),'utf8');const root:{objectName:string;visible:boolean;children:unknown[]}={objectName:'root',visible:true,children:[]};let nativeQueries=0,nativeKeys=0;const c:Record<string,any>={pendingText:null,pointerSurface:null,inputSurface:null,savedSurface:null,activeCapture:null,privateGrab:null,worldKeyRoot:null,worldKeyRequest:0,worldKeyRevision:0,worldKeyNavigation:0,worldKeyWasReady:false,topRoot:()=>root,sendToScript:(row:Record<string,unknown>)=>f.tablet.receive({type:'tablet',...row} as Parameters<BrowserTablet['receive']>[0]),nativeInput:{worldKeyReady:()=>{nativeQueries++;return true;},clickWorldKey:()=>{nativeKeys++;return true;}}};c.helper=c;vm.createContext(c);for(const name of ['cancelWorldKeys','findWorldKeyRoot','worldKeyInputIdle','updateWorldKeyReadiness','fromScript']){const start=qml.indexOf('    function '+name+'('),end=qml.indexOf('\n    function ',start+10);assert(start>=0);vm.runInContext(qml.slice(start,end<0?qml.lastIndexOf('\n}'):end),c);}const deliver=()=>{const command=f.sent.at(-1)!;c.fromScript({kind:'armWorldKey',revision:command.revision,navigationSequence:command.navigationSequence,requestId:command.sequence});};f.tablet.worldInputFocus(true);deliver();assert.equal(nativeQueries,0);assert.equal(f.tablet.worldInputReady,false);assert.equal(f.tablet.worldKey(f.event(),f.canvas as HTMLCanvasElement),false);root.children.push({objectName:'tabletRoot',visible:false,children:[]});f.tablet.worldInputFocus(true);assert.equal(f.sent.length,1);f.tablet.worldInputFocus(true,true);assert.equal(f.sent.length,2);deliver();assert.equal(f.tablet.worldInputReady,true);assert.equal(f.tablet.worldKey(f.event(),f.canvas as HTMLCanvasElement),true);const key=f.sent.at(-1)!;c.fromScript({kind:'worldKey',revision:key.revision,navigationSequence:key.navigationSequence,requestId:10,key:'x'});assert.equal(nativeKeys,1);}finally{f.close();}});
