// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Current strict gate and exact historical CPU sources remain separate.
import test from 'node:test';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink,chmod,link}from'node:fs/promises';import path from'node:path';import{fileURLToPath}from'node:url';import{tmpdir}from'node:os';import{createHash}from'node:crypto';
import {readCaptureV28History,readCaptureV28Source,recoverCaptureV28Input,decodeCaptureV28History,readCurrentPruningFlightSource} from './integration/capture-pruning-flight-source-fixture.mjs';
import {recoverCaptureV29Input,readCaptureV29Source} from './integration/capture-avatar-consumption-source-fixture.mjs';
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV29Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.dirname(client),bytes=await readFile(new URL('./fixtures/capture-pruning-flight-v29-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-avatar-flow-v28-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readCaptureV29Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs'),d=m.pruningFlightDerivation;
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,gate=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-pruning-flight-'));try{const s=path.join(dir,'browser-client');for(const row of m.files){const dest=path.join(dir,row.path);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,row.path)),{mode:0o600,flag:'wx'});}for(const relative of ['.github/workflows/browser-client.yml','browser-client/lab/README.md']){const dest=path.join(dir,relative);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,relative)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(s,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>gate(assert,readFile,realpath,lstat,path,sha,s,p);
test('V29 keeps every249 row with honest finite migrations and admissions',()=>{assert.equal(m.version,29);assert.equal(old.version,28);assert.equal(old.files.length,249);assert.equal(m.files.length,249+d.addedRows.length);assert.equal(d.previousManifestSHA256,sha(oldBytes));assert.equal(new Set(m.files.map(r=>r.path)).size,m.files.length);for(const row of old.files){const change=d.sourceMigrations[row.path];assert.deepEqual(m.files.find(r=>r.path===row.path),change?{...row,beforeSHA256:row.afterSHA256,afterSHA256:change.afterSHA256,bytes:change.bytes}:row);}for(const n of d.addedRows){assert(!old.files.some(r=>r.path===n));assert.equal(m.files.find(r=>r.path===n).beforeSHA256,null);}const expected=structuredClone(old);expected.version=29;expected.scope=m.scope;expected.files=m.files;expected.pruningFlightDerivation=d;Object.assign(expected.reacquisitionDerivation.chromeEnvironmentSourcePins,d.chromeEnvironmentMigrations);assert.deepEqual(m,expected);assert.equal(d.actualRuntimeAcceptance,false);assert.equal(d.productionHistoryFallback,false);});
test('actual current production gate validates all current sources and unchanged finite admission',()=>fixture(async(s,p)=>{assert.equal((await check(s,p)).version,29);assert(prep.includes('(?:src|shared|gateway|tests|native-input|tools)'));assert(!prep.includes('recoverCapture'));assert(!prep.includes('source-fixture'));assert(!m.files.some(r=>r.path.startsWith('browser-client/lab/')));}));
test('entire oldV28 and unknown newline manifest refuse before source reads',()=>fixture(async(s,p)=>{for(const input of [oldBytes,Buffer.from(JSON.stringify({...m,version:28})),Buffer.concat([bytes,Buffer.from('\n')])]){await writeFile(p,input);let reads=0;await assert.rejects(()=>gate(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}}));
test('changed and admitted rows refuse drift old missing and symlink',()=>fixture(async(s,p,dir)=>{const h=await readCaptureV28History();for(const n of [...Object.keys(d.sourceMigrations),...d.addedRows]){const f=path.join(dir,n),current=await readFile(f);await writeFile(f,Buffer.concat([current,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));if(Object.hasOwn(h.files,n)&&h.files[n].sha256!==sha(current)){await writeFile(f,await readCaptureV28Source(n));await assert.rejects(()=>check(s,p));}await unlink(f);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'alias');await writeFile(alias,current);await symlink(alias,f);await assert.rejects(()=>check(s,p));await unlink(f);await unlink(alias);await writeFile(f,current);}}));
test('production preparer is exactly one digest literal change without history imports',async()=>{const before=await readCaptureV28Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.split(sha(bytes)).length,2);assert.equal(prep.replace(sha(bytes),sha(oldBytes)),before);});
test('bounded whole14 history and original assertion bodies remain exact',async()=>{const h=await readCaptureV28History();assert.equal(Object.keys(h.files).length,d.historyInputCount);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const[n,r]of Object.entries(h.files))assert.equal(sha(Buffer.from(await readCaptureV28Source(n))),r.sha256);for(const[n,hash]of Object.entries(d.originalAssertionBodiesSHA256)){const current=await readFile(path.join(root,n),'utf8'),before=await readCaptureV28Source(n);assert.equal(current.slice(current.indexOf("test('")),before.slice(before.indexOf("test('")));assert.equal(sha(Buffer.from(before.slice(before.indexOf("test('")))),hash);}const archive=await readFile(new URL('./fixtures/capture-v28-pruning-flight-before.json.gz',import.meta.url)),bad=Buffer.from(archive);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV28History(bad));assert.throws(()=>decodeCaptureV28History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV28History(new Uint8Array(archive)));});
test('CPU normalization is whole-source finite and refuses changed known inputs',async()=>{for(const n of Object.keys(d.currentNormalizedSourceSHA256)){const before=Buffer.from(await readCaptureV28Source(n)),current=await readFile(path.join(root,n));assert.deepEqual(await recoverCaptureV28Input(n,before),before);assert.deepEqual(await recoverCaptureV28Input(n,current),before);for(const input of [Buffer.concat([before,Buffer.from('\n')]),Buffer.concat([current,Buffer.from('\n')]),Buffer.from('unknown')])await assert.rejects(()=>recoverCaptureV28Input(n,input));}await assert.rejects(()=>readCaptureV28Source('unknown'));});
test('all49 specs and currentChrome20 source bindings remain exact with only pruning runner pin migrated',async()=>{assert.equal(Object.keys(d.currentBrowserSpecSHA256).length,49);assert.deepEqual(d.currentBrowserSpecSHA256,old.avatarFlowDerivation.currentBrowserSpecSHA256);assert.deepEqual(Object.keys(d.chromeEnvironmentMigrations),['browser-client/tests/integration/native-ignored-fbx-pixels.mjs']);for(const[n,h]of Object.entries(d.currentBrowserSpecSHA256))assert.equal(sha(await readFile(path.join(root,n))),h);for(const[n,h]of Object.entries(m.reacquisitionDerivation.chromeEnvironmentSourcePins))assert.equal(sha(await readFile(path.join(root,n))),h);for(const[n,h]of Object.entries(d.unchangedSourcePins))assert.equal(sha(await readFile(path.join(root,n))),h);assert.equal(d.nativeChildSampleVersion,1);assert.equal(d.gatewaySampleVersion,2);assert.equal(d.innerFlowVersion,2);assert.equal(d.privateViewerIsNotRepositoryInput,true);});
test('strict current physical-source reader refuses before altered absent unsafe alias and unknown keys',async()=>{const n='browser-client/gateway/server.mjs',current=await readFile(path.join(root,n)),before=Buffer.from(await readCaptureV28Source(n));assert.deepEqual(await readCurrentPruningFlightSource(n,path.join(root,n)),current);const dir=await mkdtemp(path.join(tmpdir(),'v29-held-'));try{const f=path.join(dir,'input');for(const b of [before,Buffer.concat([current,Buffer.from('\n')]),Buffer.from('unknown'),Buffer.alloc(262145)]){await writeFile(f,b,{mode:0o600});await assert.rejects(()=>readCurrentPruningFlightSource(n,f));}await unlink(f);await assert.rejects(()=>readCurrentPruningFlightSource(n,f));const target=path.join(dir,'target');await writeFile(target,current,{mode:0o600});await symlink(target,f);await assert.rejects(()=>readCurrentPruningFlightSource(n,f));await unlink(f);await link(target,f);await assert.rejects(()=>readCurrentPruningFlightSource(n,f));await unlink(f);await writeFile(f,current,{mode:0o600});await chmod(f,0o622);await assert.rejects(()=>readCurrentPruningFlightSource(n,f));await assert.rejects(()=>readCurrentPruningFlightSource('unknown',target));}finally{await rm(dir,{recursive:true,force:true});}});
