// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import {stripTypeScriptTypes} from 'node:module';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {recoverCaptureV21Input,readCaptureV21Source} from './integration/capture-context-lifecycle-source-fixture.mjs';
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV21Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
import {readCaptureV20History,readCaptureV20Source,recoverCaptureV20Input,decodeCaptureV20History} from './integration/capture-embedded-context-type-source-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.dirname(client),bytes=await readFile(new URL('./fixtures/capture-context-type-v21-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-native-author-v20-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readCaptureV21Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs'),d=m.contextTypeDerivation;
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,gate=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-author-'));try{const s=path.join(dir,'browser-client');for(const row of m.files){if(!row.path.startsWith('browser-client/'))continue;const dest=path.join(dir,row.path);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,row.path)),{mode:0o600,flag:'wx'});}for(const relative of ['.github/workflows/browser-client.yml','browser-client/lab/README.md']){const dest=path.join(dir,relative);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,relative)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(s,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>gate(assert,readFile,realpath,lstat,path,sha,s,p);
test('V21 preserves all186 V20 rows with one type and three CPU plumbing migrations and four admissions',()=>{
 assert.equal(m.version,21);assert.equal(old.files.length,186);assert.equal(m.files.length,190);assert.equal(new Set(m.files.map(r=>r.path)).size,190);assert.equal(d.previousManifestSHA256,sha(oldBytes));assert.equal(Object.keys(d.sourceMigrations).length,4);assert.equal(d.addedRows.length,4);
 for(const row of old.files){const next=m.files.find(r=>r.path===row.path),change=d.sourceMigrations[row.path];assert.deepEqual(next,change?{...row,beforeSHA256:row.afterSHA256,afterSHA256:change.afterSHA256,bytes:change.bytes}:row);}
 for(const name of d.addedRows){assert(!old.files.some(r=>r.path===name));assert.equal(m.files.find(r=>r.path===name).beforeSHA256,null);}
 const expected=structuredClone(old);expected.version=21;expected.scope=m.scope;expected.files=m.files;expected.contextTypeDerivation=d;assert.deepEqual(m,expected);assert.equal(d.frontendProductionChanged,false);assert.deepEqual(m.reacquisitionDerivation.chromeEnvironmentSourcePins,old.reacquisitionDerivation.chromeEnvironmentSourcePins);
});
test('actual current production gate admits exact type annotation and history files with unchanged finite path exclusions',()=>fixture(async(s,p)=>{
 assert.equal((await check(s,p)).version,21);for(const name of [...Object.keys(d.sourceMigrations),...d.addedRows])assert(m.files.some(r=>r.path===name));assert(!m.files.some(r=>r.path==='browser-client/lab/native-participant.js'));assert(prep.includes('(?:src|shared|gateway|tests|native-input|tools)'));assert(!prep.includes('recoverCapture'));
}));
test('whole prior V20 altered version and unknown manifest bytes refuse before source reads',()=>fixture(async(s,p)=>{
 for(const input of [oldBytes,Buffer.from(JSON.stringify({...m,version:20})),Buffer.concat([bytes,Buffer.from('\n')])]){await writeFile(p,input);let reads=0;await assert.rejects(()=>gate(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}
}));
test('all new and migrated rows refuse missing symlink unknown newline and prior reviewed source bytes',()=>fixture(async(s,p,dir)=>{
 const h=await readCaptureV20History();for(const name of [...Object.keys(d.sourceMigrations),...d.addedRows]){const f=path.join(dir,name),current=await readFile(f);await writeFile(f,Buffer.concat([current,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));if(Object.hasOwn(h.files,name)&&h.files[name].sha256!==sha(current)){await writeFile(f,await readCaptureV20Source(name));await assert.rejects(()=>check(s,p));}await unlink(f);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'alias');await writeFile(alias,current);await symlink(alias,f);await assert.rejects(()=>check(s,p));await unlink(f);await unlink(alias);await writeFile(f,current);}
}));
test('production preparer changes only exact V21 digest with no historical import fallback',async()=>{
 const before=await readCaptureV20Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.split(sha(bytes)).length,2);assert.equal(prep.replace(sha(bytes),sha(oldBytes)),before);assert(!prep.includes('source-fixture'));assert(!prep.includes('recoverCapture'));
});
test('six complete prior sources and exact current CPU normalization retain all original V20 assertions',async()=>{
 const h=await readCaptureV20History();assert.equal(Object.keys(h.files).length,6);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const[name,row]of Object.entries(h.files))assert.equal(sha(Buffer.from(await readCaptureV20Source(name))),row.sha256);
 for(const name of d.historyRecoveredCurrentPaths){const current=await readFile(path.join(root,name)),before=await readCaptureV20Source(name);assert.equal((await recoverCaptureV20Input(name,current)).toString(),before);assert.equal((await recoverCaptureV20Input(name,Buffer.from(before))).toString(),before);await assert.rejects(()=>recoverCaptureV20Input(name,Buffer.concat([current,Buffer.from('\n')])));if(name.endsWith("tablet-capture-native-author-manifest.test.mjs")){assert.equal(current.toString().slice(current.toString().indexOf("test('")),before.slice(before.indexOf("test('")));assert.equal(sha(Buffer.from(before.slice(before.indexOf("test('")+6))),d.originalV20EightBodySHA256);}}
 const b=await readFile(new URL('./fixtures/capture-v20-context-type-before.json.gz',import.meta.url)),bad=Buffer.from(b);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV20History(bad));assert.throws(()=>decodeCaptureV20History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV20History(new Uint8Array(b)));
});
test('type annotation change preserves the entire original fixture and normalized actual emitted JavaScript',async()=>{
 const name='browser-client/tests/fixtures/embedded-world.ts',current=await readFile(path.join(root,name),'utf8'),before=await readCaptureV20Source(name),a='gl:WebGL2RenderingContext,scene:THREE.Scene',b='gl:WebGLRenderingContext|WebGL2RenderingContext,scene:THREE.Scene';
 assert.equal(before.split(a).length,2);assert.equal(current.split(b).length,2);assert.equal(current.replace(b,a),before);assert.equal(stripTypeScriptTypes(current,{mode:'transform'}),stripTypeScriptTypes(before,{mode:'transform'}));
 const fn=current.slice(current.indexOf('function sampleEmbeddedRender('),current.indexOf('function recordEmbeddedContext('));assert.equal(fn.split('renderer.render(scene,camera);').length,2);assert.equal(fn.split('gl.isContextLost()').length,3);assert(!fn.includes('getError'));assert(!fn.includes(' as '));
});
test('whole original Chrome20 current source map and49 browser specs stay exact and original TS2345 negative remains negative',async()=>{
 assert.equal(sha(await readFile(path.join(root,'browser-client/tests/tablet-capture-reacquisition-manifest.test.mjs'))),d.originalChrome20TestSHA256);assert.equal(Object.keys(d.chromeSpecSourcePins).length,49);for(const[name,hash]of Object.entries(d.chromeSpecSourcePins))assert.equal(sha(await readFile(path.join(root,name))),hash);for(const[name,hash]of Object.entries(m.reacquisitionDerivation.chromeEnvironmentSourcePins))assert.equal(sha(await readFile(path.join(root,name))),hash);assert.equal(d.originalBuildFailure.category,'TS2345');assert.equal(d.originalBuildFailure.parameter,'sampleEmbeddedRender.gl');assert.match(d.originalBuildFailure.logSHA256,/^[0-9a-f]{64}$/);
});
test('all reviewed helper-chain inputs preserve exact authenticated old bytes and refuse unknown drift',async()=>{
 const h=await readCaptureV20History();for(const name of d.historyRecoveredCurrentPaths){const old=Buffer.from(h.files[name].source),current=await readFile(path.join(root,name));assert.deepEqual(await recoverCaptureV20Input(name,old),old);assert.deepEqual(await recoverCaptureV20Input(name,current),old);await assert.rejects(()=>recoverCaptureV20Input(name,Buffer.concat([old,Buffer.from('\n')])));}
});
