// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile as readCurrentFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
import {readCaptureV13Source,recoverCaptureV13Input} from './integration/capture-image-transport-source-fixture.mjs';
const readFile=async(input,options)=>{const bytes=await readCurrentFile(input),file=input instanceof URL?fileURLToPath(input):path.resolve(input),relative=path.relative(fileURLToPath(new URL('../../',import.meta.url)),file),recovered=await recoverCaptureV13Input(relative,bytes);return typeof options==='string'?recovered.toString(options):recovered;};
import {readCaptureV12History,readCaptureV12Source,decodeCaptureV12History,recoverCaptureV12Input} from './integration/capture-source-test-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),root=path.join(client,'..'),bytes=await readFile(new URL('./fixtures/capture-source-test-v13-complete-source-manifest.json',import.meta.url)),m=JSON.parse(bytes),oldBytes=await readFile(new URL('./fixtures/capture-loading-v12-complete-source-manifest.json',import.meta.url)),old=JSON.parse(oldBytes),prep=await readCaptureV13Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,gate=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-source-test-guard-'));try{const source=path.join(dir,'browser-client');for(const row of m.files){if(!row.path.startsWith('browser-client/'))continue;const name=row.path.slice(15),dest=path.join(source,name);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(client,name)),{mode:0o600,flag:'wx'});}for(const name of Object.keys(m.environmentReconciliationDerivation.externalMigrations)){const dest=path.join(dir,name);await mkdir(path.dirname(dest),{recursive:true,mode:0o700});await writeFile(dest,await readFile(path.join(root,name)),{mode:0o600,flag:'wx'});}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,bytes,{mode:0o600,flag:'wx'});return await fn(source,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(s,p)=>gate(assert,readFile,realpath,lstat,path,sha,s,p);
test('v13 preserves all138 rows with two source-test repairs and two CPU plumbing migrations only',()=>{assert.equal(sha(oldBytes),'f67b57ecc9294410fe8dc73ae56b704d1481e8a3ad4c63fb3ce1ada2f6134b37');assert.equal(old.files.length,138);assert.equal(m.version,13);assert.equal(m.files.length,142);assert.equal(new Set(m.files.map(r=>r.path)).size,142);const d=m.sourceTestRepairDerivation,changed={...d.testMigrations,...d.fixtureMigrations};assert.equal(d.previousManifestSHA256,sha(oldBytes));assert.equal(Object.keys(d.testMigrations).length,2);assert.equal(Object.keys(d.fixtureMigrations).length,2);assert.equal(d.addedRows.length,4);for(const row of old.files){const next=m.files.filter(r=>r.path===row.path);assert.equal(next.length,1);if(changed[row.path]){assert.equal(changed[row.path].beforeSHA256,row.afterSHA256);assert.deepEqual(next[0],{...row,beforeSHA256:row.afterSHA256,afterSHA256:changed[row.path].afterSHA256,bytes:changed[row.path].bytes});}else assert.deepEqual(next[0],row);}const expected=structuredClone(old);expected.version=m.version;expected.scope=m.scope;expected.files=m.files;expected.sourceTestRepairDerivation=d;assert.deepEqual(m,expected);});
test('current preparer recovers complete exact V12 by one literal and imports no CPU history',async()=>{const before=await readCaptureV12Source('browser-client/tests/integration/prepare-tablet-capture-acceptance.mjs');assert.equal(prep.split(sha(bytes)).length,2);assert.equal(prep.replace(sha(bytes),sha(oldBytes)),before);assert(!prep.includes('capture-source-test-fixture'));assert(!prep.includes('recoverCapture'));});
test('actual extracted production gate admits all142 current rows and unchanged two external sources',()=>fixture(async(s,p)=>assert.equal((await check(s,p)).version,13)));
test('old and invented manifests refuse before any source or external environment read',()=>fixture(async(s,p)=>{for(const data of [oldBytes,Buffer.from(JSON.stringify({...m,version:12})),Buffer.from(JSON.stringify({...m,files:[]}))]){await writeFile(p,data);let reads=0;await assert.rejects(()=>gate(assert,async f=>{if(f!==p)reads++;return readFile(f);},realpath,lstat,path,sha,s,p));assert.equal(reads,0);}}));
test('all four migrations and four additions refuse unknown source drift and exact old migration bytes',()=>fixture(async(s,p)=>{const d=m.sourceTestRepairDerivation;for(const name of [...Object.keys(d.testMigrations),...Object.keys(d.fixtureMigrations),...d.addedRows]){const file=path.join(s,name.slice(15)),data=await readFile(file);await writeFile(file,Buffer.concat([data,Buffer.from('\n')]));await assert.rejects(()=>check(s,p),/Exact reviewed capture composition required/);if(d.testMigrations[name]||d.fixtureMigrations[name]){await writeFile(file,await readCaptureV12Source(name));await assert.rejects(()=>check(s,p),/Exact reviewed capture composition required/);}await writeFile(file,data);}}));
test('new admitted CPU source and repaired tests preserve missing-source and alias refusals',async()=>{for(const name of [...Object.keys(m.sourceTestRepairDerivation.testMigrations),...m.sourceTestRepairDerivation.addedRows])await fixture(async(s,p,dir)=>{const file=path.join(s,name.slice(15)),data=await readFile(file);await unlink(file);await assert.rejects(()=>check(s,p));const alias=path.join(dir,'alias');await writeFile(alias,data);await symlink(alias,file);await assert.rejects(()=>check(s,p));});});
test('six bounded whole-before inputs and all four migration normalizers refuse malformed or unknown bytes',async()=>{const h=await readCaptureV12History();assert.equal(Object.keys(h.files).length,6);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const[name,row]of Object.entries(h.files)){assert(Object.isFrozen(row));assert.equal(sha(Buffer.from(row.source)),row.sha256);assert.equal(await readCaptureV12Source(name),row.source);}const data=await readFile(new URL('./fixtures/capture-v12-source-test-before.json.gz',import.meta.url)),bad=Buffer.from(data);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV12History(bad));assert.throws(()=>decodeCaptureV12History(Buffer.alloc(131073)));assert.throws(()=>decodeCaptureV12History(new Uint8Array(data)));await assert.rejects(()=>readCaptureV12Source('unknown'));for(const name of [...Object.keys(m.sourceTestRepairDerivation.testMigrations),...Object.keys(m.sourceTestRepairDerivation.fixtureMigrations)]){const b=await readFile(path.join(root,name));assert.equal((await recoverCaptureV12Input(name,b)).toString(),h.files[name].source);assert.equal((await recoverCaptureV12Input(name,Buffer.from(h.files[name].source))).toString(),h.files[name].source);await assert.rejects(()=>recoverCaptureV12Input(name,Buffer.concat([b,Buffer.from('\n')])));}});
test('all81 historical assertions and original Chrome bodies/gold remain unchanged with no runtime or build claim',async()=>{const name='browser-client/tests/tablet-capture-loading-manifest.test.mjs',before=await readCaptureV12Source(name),after=await readFile(path.join(root,name),'utf8');assert.equal(after.slice(after.indexOf("test('")),before.slice(before.indexOf("test('")));const chrome='browser-client/tests/chrome-journey-defaults.test.mjs',oldChrome=await readCaptureV12Source(chrome),newChrome=await readFile(path.join(root,chrome),'utf8');assert(newChrome.endsWith(oldChrome.slice(oldChrome.indexOf("test('")))===false);assert(newChrome.includes(oldChrome.slice(oldChrome.indexOf("test('"))));const gold=await readFile(new URL('./fixtures/chrome-journey-original.json.gz',import.meta.url));assert.equal(sha(gold),'91ac3fc064514701d04076829950212daa54009670c05629b5a04dc19400ff6e');for(const key of ['limits','verification','packagePins','dependencyPins','reacquisitionDerivation','environmentReconciliationDerivation'])assert.deepEqual(m[key],old[key]);assert.deepEqual(m.files.find(r=>r.path==='docs/browser-client/BROWSER_MICROPHONE_CONTROLS.md'),old.files.find(r=>r.path==='docs/browser-client/BROWSER_MICROPHONE_CONTROLS.md'));const d=m.sourceTestRepairDerivation;assert.equal(d.runtimeChanged,false);assert.equal(d.externalEnvironmentChanged,false);assert.equal(d.productionHistoricalFallback,false);assert.equal(d.actualProductionBuildQualified,false);assert.equal(d.actualNativeOrBrowserQualified,false);assert.equal(d.oldProductionReceiptSHA256,'20cedb53d46a8b8b123b82bb385b6b380458c08cdaaa98256d506e97f0fc0212');});
