// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Authored observer/navigation contracts, not native or browser qualification.
import test from 'node:test';import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {qualifiedSitHomeStopAck,navigateSitHomeByTab} from './integration/tablet-sit-home-stop.mjs';
const input=()=>({previous:{sequence:10,revision:2,navigationSequence:3},command:{action:'home',revision:2,sequence:9},frame:{sequence:11,revision:2,navigationSequence:9,surface:'tablet',width:480,height:706,tabletRect:{x:0,y:0,width:480,height:706}},state:{revision:2,screen:'Home',visible:true,loading:false},connected:true,tabletVisible:true,entityChanged:false,currentCanvas:true});
test('fresh current displayed Home ACK with original authority/canvas qualifies',()=>assert.equal(qualifiedSitHomeStopAck(input()),true));
test('stale frame/navigation/authority or non-Home/canvas never qualifies',()=>{for(const change of [v=>v.frame.sequence=10,v=>v.frame.navigationSequence=3,v=>v.frame.revision=3,v=>v.command.sequence=3,v=>v.command.revision=3,v=>v.command.action='back',v=>v.state.screen='Web',v=>v.state.loading=true,v=>v.state.visible=false,v=>v.state.revision=3,v=>v.connected=false,v=>v.tabletVisible=false,v=>v.entityChanged=true,v=>v.currentCanvas=false,v=>v.frame.surface='dialogs',v=>v.frame.width=4097,v=>v.frame.tabletRect.x=1]){const v=input();change(v);assert.equal(qualifiedSitHomeStopAck(v),false);}});
test('missing, primitive, foreign or accessor field refuses without invoking getter/setter',()=>{let calls=0;for(const target of ['command','frame','state','previous']){const v=input();Object.defineProperty(v,target,{get(){calls++;throw Error('must not read');},set(){calls++;}});assert.equal(qualifiedSitHomeStopAck(v),false);}const v=input();Object.defineProperty(v.frame,'revision',{get(){calls++;return 2;}});assert.equal(qualifiedSitHomeStopAck(v),false);assert.equal(qualifiedSitHomeStopAck({}),false);assert.equal(qualifiedSitHomeStopAck(null),false);const q=input();q.frame=Object.create(q.frame);assert.equal(qualifiedSitHomeStopAck(q),false);assert.equal(calls,0);});
test('already focused genuine owned canvas sends NO Tab',async()=>{let tabs=0,inspections=0;const result=await navigateSitHomeByTab({inspect:()=>{inspections++;return {current:true,focused:true};},tab:()=>tabs++});assert.equal(tabs,0);assert.equal(inspections,1);assert.deepEqual(result,{completedTabs:0,maximumTabs:32,deadlineMs:15000});});
test('navigation stops before pressing Tab on canvas and counts completed actions only',async()=>{let tabs=0;const observations=[];const result=await navigateSitHomeByTab({inspect:()=>{observations.push(tabs);return {current:true,focused:tabs===3};},tab:()=>{assert(tabs<3);tabs++;}});assert.equal(tabs,3);assert.equal(result.completedTabs,3);assert.deepEqual(observations,[0,1,2,3]);});
test('revoked Home/canvas refuses immediately without sending another key',async()=>{let tabs=0;await assert.rejects(navigateSitHomeByTab({inspect:()=>({current:tabs===0,focused:false}),tab:()=>tabs++}),/Fresh owned Home/);assert.equal(tabs,1);});
test('32 action cap and original15s bound preserved',async()=>{let tabs=0;await assert.rejects(navigateSitHomeByTab({inspect:()=>({current:true,focused:false}),tab:()=>tabs++}),/count bound/);assert.equal(tabs,32);let n=0;await assert.rejects(navigateSitHomeByTab({now:()=>n++===0?0:15000,inspect:()=>{throw Error('must not inspect after deadline');},tab:()=>{throw Error('must not key');}}),/navigation deadline/);});
test('hung observer promptly hits owned deadline and late rejection is consumed',async()=>{let reject,clockCalls=0;const promise=navigateSitHomeByTab({now:()=>clockCalls++===0?0:14999,inspect:()=>new Promise((_,no)=>reject=no),tab:()=>{throw Error('must not send');}});await assert.rejects(promise,/navigation deadline/);reject(Error('late private failure'));await new Promise(resolve=>setImmediate(resolve));});
test('source transformation preserves unchanged seven-joint/handler/standing/deadline/cleanup gates and never emits restore or focus',async()=>{const source=await readFile(new URL('./integration/tablet-sit-home-stop-session.mjs',import.meta.url),'utf8');for(const literal of ["await page.keyboard.press('x');","'Native authored restore control returned',10000", "'Actual standing native/default browser pose restored after key',10000", 'report.appliedJointCount=SIT_JOINTS.length','d.hipsDrop<=20||d.maximumThighChange<=.5','Date.now()-held.at<500','maximumThighChange<.35','Math.abs(d.hipsDrop)<10','assert.deepEqual(baselineIdentity','microphoneEnabled:false','finishSitLifecycle(report','report.startCopiedSourceSHA256','report.endCopiedSourceSHA256'])assert(source.includes(literal),literal);assert(source.includes("tab:()=>page.keyboard.press('Tab')"));assert(source.includes("name:'Home',exact:true"));assert(source.includes('document.activeElement===el'));assert(!/\.focus\(|dispatchEvent\(|Controller\.|MyAvatar\.|restoreAnimation\(/.test(source));assert.equal((source.match(/await page.keyboard.press\('x'\)/g)||[]).length,1);assert(source.includes("'tests/integration/tablet-sit-session.mjs'"));assert(source.includes("'tests/integration/tablet-sit-home-stop-session.mjs'"));});
