// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import {readFile,writeFile,mkdtemp,mkdir,rm,lstat,realpath,unlink,symlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
import {readCaptureV8Source,recoverCaptureV8Input} from './integration/capture-status-source-fixture.mjs';
import {readCaptureV7History,decodeCaptureV7History,readCaptureHistoricalPreparer,copyCaptureFixtureRow} from './integration/capture-readback-source-fixture.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),client=fileURLToPath(new URL('../',import.meta.url)),manifestBytes=await readFile(new URL('./fixtures/capture-readback-v8-complete-source-manifest.json',import.meta.url)),v8=JSON.parse(manifestBytes),oldBytes=await readFile(new URL('./fixtures/capture-fst-escape-v7-complete-source-manifest.json',import.meta.url)),v7=JSON.parse(oldBytes),prep=await readCaptureV8Source('tests/integration/prepare-tablet-capture-acceptance.mjs');
const a=prep.indexOf('const manifestBytes=await readFile(proposal);'),z=prep.indexOf('const directory=await mkdtemp(',a);assert(a>=0&&z>a);const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,preflight=new AsyncFunction('assert','readFile','realpath','lstat','path','sha','source','proposal',prep.slice(a,z)+'return m;');
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'capture-readback-guard-'));try{const source=path.join(dir,'browser-client');for(const row of v8.files){if(!row.path.startsWith('browser-client/'))continue;const relative=row.path.slice(15),dest=path.join(source,relative);await mkdir(path.dirname(dest),{recursive:true});await writeFile(dest,await recoverCaptureV8Input(relative,await readFile(path.join(client,relative))));}const proposal=path.join(dir,'manifest.json');await writeFile(proposal,manifestBytes);return await fn(source,proposal,dir);}finally{await rm(dir,{recursive:true,force:true});}}
const check=(source,proposal)=>preflight(assert,readFile,realpath,lstat,path,sha,source,proposal);
test('v8 validates actual current rows and retains all97 original rows with only declared exact migrations',async()=>{assert.equal(v7.files.length,97);assert.equal(v8.version,8);const d=v8.readbackDerivation;assert.equal(d.previousCompleteManifestSHA256,sha(oldBytes));for(const r of v7.files){const n=v8.files.filter(x=>x.path===r.path);assert.equal(n.length,1);const change=d.migrations[r.path];if(change){assert.equal(change.beforeSHA256,r.afterSHA256);assert.equal(n[0].afterSHA256,change.afterSHA256);}else assert.deepEqual(n[0],r);}assert.deepEqual(v8.limits,v7.limits);assert.deepEqual(v8.verification,v7.verification);assert.deepEqual(v8.packagePins,v7.packagePins);assert.equal(v8.files.length,new Set(v8.files.map(r=>r.path)).size);await fixture(async(s,p)=>assert.equal((await check(s,p)).version,8));});
test('production v8 preparer recovers the entire v7 preparer after only one reviewed manifest literal',async()=>{const prior=await readCaptureHistoricalPreparer(7);assert.equal(prep.split(sha(manifestBytes)).length,2);assert.equal(prep.replace(sha(manifestBytes),sha(oldBytes)),prior);assert(!prep.includes('capture-readback-source-fixture'));});
test('old97 manifest and invented row sets refuse before any source inspection',async()=>{await fixture(async(s,p)=>{for(const bytes of [oldBytes,Buffer.from(JSON.stringify({...v8,version:7})),Buffer.from(JSON.stringify({...v8,files:[]}))]){await writeFile(p,bytes);let reads=0;const read=async f=>{if(f!==p)reads++;return readFile(f);};await assert.rejects(()=>preflight(assert,read,realpath,lstat,path,sha,s,p));assert.equal(reads,0);}});});
test('every declared migration and appended current guard/resource refuses actual byte drift',async()=>{await fixture(async(s,p)=>{for(const key of [...Object.keys(v8.readbackDerivation.migrations),...v8.readbackDerivation.addedRows]){const f=path.join(s,key.slice(15)),bytes=await readFile(f);await writeFile(f,Buffer.concat([bytes,Buffer.from('\n')]));await assert.rejects(()=>check(s,p));await writeFile(f,bytes);}});});
test('current resource and CPU recovery aliases refuse rather than following symlinks',async()=>{for(const relative of ['gateway/fixtures/native-browser-capture-readback-before.qml.gz','tests/integration/capture-readback-source-fixture.mjs'])await fixture(async(s,p,dir)=>{const f=path.join(s,relative),outside=path.join(dir,'alias');await writeFile(outside,await readFile(f));await unlink(f);await symlink(outside,f);await assert.rejects(()=>check(s,p));});});
test('all ten full before inputs are exact frozen bytes; unknown versions and corrupt oversized archives refuse',async()=>{const h=await readCaptureV7History();assert.equal(Object.keys(h.files).length,10);assert(Object.isFrozen(h)&&Object.isFrozen(h.files));for(const r of Object.values(h.files)){assert(Object.isFrozen(r));assert.equal(sha(Buffer.from(r.source)),r.sha256);}const b=await readFile(new URL('./fixtures/capture-v7-readback-before.json.gz',import.meta.url)),bad=Buffer.from(b);bad[bad.length-1]^=1;assert.throws(()=>decodeCaptureV7History(bad));assert.throws(()=>decodeCaptureV7History(Buffer.alloc(65537)));assert.throws(()=>decodeCaptureV7History(new Uint8Array(b)));await assert.rejects(()=>readCaptureHistoricalPreparer(8));});
test('historical assertion bodies and full core/adapter bytes recover only by the declared input substitutions',async()=>{const h=await readCaptureV7History(),recovery=JSON.parse(await readFile(new URL('./fixtures/capture-v8-readback-input-recovery.json',import.meta.url)));assert.deepEqual(Object.keys(recovery).sort(),['tests/integration/capture-lookahead-source-fixture.mjs','tests/integration/capture-source-fixture.mjs','tests/tablet-capture-fst-escape-manifest.test.mjs','tests/tablet-capture-style.test.mjs','tests/tablet-capture-switch-width.test.mjs','tests/tablet-capture-world-key-manifest.test.mjs'].sort());for(const [relative,substitutions]of Object.entries(recovery)){let s=(await recoverCaptureV8Input(relative,await readFile(path.join(client,relative)))).toString('utf8');for(const[before,after]of substitutions.toReversed()){assert.equal(s.split(after).length,2);s=s.replace(after,before);}assert.equal(s,h.files[relative].source);}assert.equal(sha(await readFile(new URL('./fixtures/capture-world-key-v6-complete-source-manifest.json',import.meta.url))),'a823a0e90c8a6cc3f25601982527fdfe194f9a1484ca9a6867c58596a67db901');});
test('historical factory recovery refuses arbitrary live edits and preserves exclusive outputs',async()=>{const h=await readCaptureV7History(),relative='gateway/browser-capture-overrides.mjs';await fixture(async(s,p,dir)=>{const options={client:s,relative,dest:path.join(dir,'old.mjs'),expectedSHA256:h.files[relative].sha256,version:7};await copyCaptureFixtureRow(options);assert.equal(await readFile(options.dest,'utf8'),h.files[relative].source);await assert.rejects(()=>copyCaptureFixtureRow(options));await writeFile(path.join(s,relative),'unknown');await assert.rejects(()=>copyCaptureFixtureRow({...options,dest:path.join(dir,'unknown.mjs')}));});});
