// SPDX-License-Identifier: Apache-2.0
// Actual copied observer and exact original full12 media wrapper, authored API controls only.
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {installCaptureReacquisitionObserver} from './integration/tablet-capture-reacquisition-observer.mjs';
const original=await readFile(new URL('./integration/tablet-push-to-talk.mjs',import.meta.url),'utf8');assert.equal(createHash('sha256').update(original).digest('hex'),'6dec42866e6818b1595840e4ccf517f1a56888d8752a3cfe197c0625f6996e3f');
const wrapper=original.slice(original.indexOf('media.getUserMedia=function(...args)'),original.indexOf('\n  window.addEventListener',original.indexOf('media.getUserMedia=function(...args)')));
assert(wrapper.includes("if(a.tracks.length>4)throw Error('Synthetic input track bound')"));
const defaults={echoCancellation:true,noiseSuppression:true,autoGainControl:true},device='private-authored-device';
const stream=(...tracks)=>({getAudioTracks:()=>[...tracks]});
const track=(values={},id=device)=>({readyState:'live',stops:0,getSettings(){return {deviceId:id,...defaults,...values};},stop(){this.stops++;this.readyState='ended';}});
function fixture(factory){const old=track(),ended=Array.from({length:3},()=>{const t=track();t.readyState='ended';return t;}),a={getUserMediaCalls:4,tracks:[...ended,old],revision:1,navigation:3},window={__pttAudit:a,__overte:{connected:true}},media={},ctx={window,navigator:{mediaDevices:media},a,media,originalMedia:factory|| (args=>Promise.resolve(stream(track(Object.fromEntries(Object.entries(args.audio).filter(([k])=>k!=='deviceId').map(([k,v])=>[k,v.exact]))))))};
 vm.runInNewContext(wrapper,ctx);const base=media.getUserMedia;const result=vm.runInNewContext('('+installCaptureReacquisitionObserver.toString()+')()',ctx);assert.equal(result.installed,true);return {a,old,ended,window,media,api:window.__captureReacquisition,base};}
function options(old,field,value){const s=old.getSettings();return {audio:{deviceId:{exact:s.deviceId},...Object.fromEntries(Object.keys(defaults).map(key=>[key,{exact:key===field?value:s[key]}]))},video:false};}
async function replace(f,field,value,{stop=true,opts}={}){const old=f.a.tracks.find(t=>t.readyState==='live'),id=f.api.arm(field,value);if(stop)old.stop();await f.media.getUserMedia(opts||options(old,field,value));await Promise.resolve();return {id,old};}

test('six genuine observation operations prune only ended refs while retaining original cap and every restored setting',async()=>{const f=fixture();for(const field of Object.keys(defaults)){for(const value of [false,true]){const {id,old}=await replace(f,field,value);const record=f.api.complete(id);assert.equal(record.oldEndedBeforeAcquisition,true);assert.equal(record.sameDevice,true);assert.equal(record.allThreeEffectiveSettings,true);assert.equal(f.a.tracks.filter(t=>t.readyState==='live').length,1);assert(old.readyState==='ended');assert(f.a.tracks.length<=4);}}assert.equal(f.a.getUserMediaCalls,10);assert.equal(f.api.summary().operations.length,6);assert.deepEqual(f.a.tracks.find(t=>t.readyState==='live').getSettings(),{deviceId:device,...defaults});const encoded=JSON.stringify(f.api.summary());assert(!encoded.includes(device));f.a.tracks.filter(t=>t.readyState==='live').forEach(t=>t.stop());assert(f.a.tracks.every(t=>t.readyState==='ended'));f.api.retire();assert.equal(f.media.getUserMedia,f.base);});
test('baseline four-track original observer without ended pruning genuinely refuses the first fifth track',async()=>{const f=fixture();f.api.retire();f.old.stop();await assert.rejects(f.media.getUserMedia(options(f.old,'echoCancellation',false)),/Synthetic input track bound/);assert.equal(f.a.tracks.length,5);});
test('observer returns the exact existing media method Promise and unchanged args without setting or stopping tracks',async()=>{let returned,received;const f=fixture(args=>{received=args;return Promise.resolve(stream(track({echoCancellation:false}))); });const original=f.media.getUserMedia;f.api.retire();const wrappedOriginal=f.media.getUserMedia;Object.defineProperty(f.media,'getUserMedia',{value:function(...args){returned=wrappedOriginal.apply(this,args);return returned;},writable:true,configurable:true});delete f.window.__captureReacquisition;const ctx={window:f.window,navigator:{mediaDevices:f.media}};vm.runInNewContext('('+installCaptureReacquisitionObserver.toString()+')()',ctx);const api=f.window.__captureReacquisition,id=api.arm('echoCancellation',false);f.old.stop();const opts=options(f.old,'echoCancellation',false),promise=f.media.getUserMedia(opts);assert.equal(promise,returned);assert.equal(received,opts);await promise;await new Promise(resolve=>setImmediate(resolve));assert.equal(api.complete(id).sameDevice,true);assert.equal(f.old.stops,1);});
test('acquire-before-retire counterfactual is delegated normally but never qualifies',async()=>{const f=fixture();const {id,old}=await replace(f,'echoCancellation',false,{stop:false});old.stop();assert.throws(()=>f.api.complete(id),/proof refused/);assert.equal(f.a.getUserMediaCalls,5);});
test('wrong private device, wrong untouched setting and two live returned tracks cannot qualify',async()=>{for(const factory of [()=>Promise.resolve({getAudioTracks:()=>[track({echoCancellation:false},'different')] }),()=>Promise.resolve({getAudioTracks:()=>[track({echoCancellation:false,noiseSuppression:false})]}),()=>Promise.resolve({getAudioTracks:()=>[track(),track()]})]){const f=fixture(factory),{id}=await replace(f,'echoCancellation',false);assert.throws(()=>f.api.complete(id),/proof refused/);}});
test('constraints that omit a required exact setting are preserved but fail the observation',async()=>{const f=fixture();const opts=options(f.old,'echoCancellation',false);opts.audio.noiseSuppression=true;const {id}=await replace(f,'echoCancellation',false,{opts});assert.throws(()=>f.api.complete(id),/proof refused/);});
test('rollback second call does not produce a successful operation or get hidden by pruning',async()=>{const f=fixture();const id=f.api.arm('echoCancellation',false);f.old.stop();await f.media.getUserMedia(options(f.old,'echoCancellation',false));f.a.tracks.find(t=>t.readyState==='live').stop();await f.media.getUserMedia(options(f.old,'echoCancellation',true));assert.equal(f.a.getUserMediaCalls,6);assert.throws(()=>f.api.complete(id),/proof refused/);});
test('unarmed unexpected call preserves the original cap refusal and is not injected-refused',async()=>{const f=fixture();f.old.stop();await assert.rejects(f.media.getUserMedia(options(f.old,'echoCancellation',true)),/Synthetic input track bound/);assert.equal(f.a.getUserMediaCalls,5);assert.equal(f.api.summary().unexpectedCalls,1);assert.throws(()=>f.api.arm('echoCancellation',false),/proof refused/);});
test('revision/navigation/disconnect changes cannot qualify fresh accepted replacement',async()=>{for(const change of [f=>f.a.revision++,f=>f.a.navigation++,f=>f.window.__overte.connected=false]){const f=fixture(),{id}=await replace(f,'echoCancellation',false);change(f);assert.throws(()=>f.api.complete(id),/proof refused/);}});
test('never-settling original Promise refuses completion and retiring observer does not settle or stop it',async()=>{let resolve;const f=fixture(()=>new Promise(r=>{resolve=r;}));const id=f.api.arm('echoCancellation',false);f.old.stop();const promise=f.media.getUserMedia(options(f.old,'echoCancellation',false));assert.throws(()=>f.api.complete(id),/proof refused/);f.api.retire();assert.equal(f.media.getUserMedia,f.base);const late=track({echoCancellation:false});resolve({getAudioTracks:()=>[late]});await promise;await Promise.resolve();assert.equal(late.stops,0,'Observer must not own production cleanup');assert.equal(f.api.summary().operations.length,0);assert.equal(f.api.summary().pending,false);});
test('throwing diagnostic callback is consumed and cannot replace original media Promise result',async()=>{let reads=0;const t=track({echoCancellation:false});const f=fixture(()=>Promise.resolve({getAudioTracks(){if(++reads>1)throw Error('authored observer-only throw');return[t];}}));const id=f.api.arm('echoCancellation',false);f.old.stop();const result=await f.media.getUserMedia(options(f.old,'echoCancellation',false));assert.equal(typeof result.getAudioTracks,'function');await new Promise(resolve=>setImmediate(resolve));assert.equal(f.api.summary().observationFailures,1);assert.throws(()=>f.api.complete(id),/proof refused/);});
test('retirement does not clobber a foreign media method and refuses accessor method admission without invoking getter',()=>{const f=fixture(),foreign=()=>Promise.resolve();f.media.getUserMedia=foreign;f.api.retire();assert.equal(f.media.getUserMedia,foreign);let getters=0;const media={};Object.defineProperty(media,'getUserMedia',{get(){getters++;return foreign;}});assert.throws(()=>vm.runInNewContext('('+installCaptureReacquisitionObserver.toString()+')()',{window:{__pttAudit:{tracks:[]}},navigator:{mediaDevices:media}}),/proof refused/);assert.equal(getters,0);});
