// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import {BoxGeometry,Group,Material,Mesh,MeshBasicMaterial,MeshStandardMaterial,Texture} from 'three';
import {BrowserWorld} from '../src/world';
import {ModelResources} from '../src/model-resources';
import type {Entity}from'../src/world-data';
const apply=BrowserWorld.prototype as unknown as {applyEntityMaterial(entity:Entity):Promise<void>};
function setup(enabled:boolean){const context=Object.create(BrowserWorld.prototype),target=new Group(),mesh=new Mesh(new BoxGeometry(),[new MeshBasicMaterial({name:'A'}),new MeshBasicMaterial({name:'B'})]),abort=new AbortController();target.add(mesh);Object.assign(context,{abort,disposed:false,replacementClonesEnabled:enabled,replacementCloneCounts:{applications:0,created:0,reused:0,refused:0},objects:new Map([['model',target]]),entities:new Map([['model',{visible:true}]]),cancelGraphics(){},restoreModelBatch(){},prepareGraphics:async()=>{target.userData.shadersReady=true;},makeMaterial:async()=>new MeshStandardMaterial(),options:{}});return{context,target,mesh,abort};}
const entity=(name:string,selector='all'):Entity=>({id:name,type:'Material',parentID:'model',parentMaterialName:selector,materialURL:'materialData',materialData:'{"materials":{"name":"Replacement","albedo":[0,1,0]}}'});
test('actual World default-off method keeps distinct material identities and creates no bank',async()=>{const f=setup(false);await apply.applyEntityMaterial.call(f.context,entity('first'));const values=f.mesh.material as Material[];assert.notEqual(values[0],values[1]);assert.deepEqual(f.context.replacementCloneCounts,{applications:0,created:0,reused:0,refused:0});const resources=new ModelResources();resources.capture(f.target);resources.releaseKeeping();});
test('actual World trusted application shares exact clone, preserves slot order and separate later replacement',async()=>{const f=setup(true);await apply.applyEntityMaterial.call(f.context,entity('first'));let values=f.mesh.material as Material[];assert.equal(values[0],values[1]);const first=values[0];await apply.applyEntityMaterial.call(f.context,entity('partial','0'));values=f.mesh.material as Material[];assert.notEqual(values[0],first);assert.equal(values[1],first);assert.deepEqual(f.context.replacementCloneCounts,{applications:2,created:2,reused:1,refused:0});await apply.applyEntityMaterial.call(f.context,entity('all-again'));values=f.mesh.material as Material[];assert.equal(values[0],values[1]);assert.notEqual(values[0],first);const resources=new ModelResources();resources.capture(f.target);resources.releaseKeeping();});
test('actual World shared map retains unmatched slot across partial replacement and disposes obsolete clone once',async()=>{const f=setup(true),texture=new Texture();f.context.makeMaterial=async()=>new MeshStandardMaterial({map:texture});await apply.applyEntityMaterial.call(f.context,entity('first'));const original=(f.mesh.material as Material[])[0];let dispose=0,maps=0;original.addEventListener('dispose',()=>dispose++);texture.addEventListener('dispose',()=>maps++);f.context.makeMaterial=async()=>new MeshStandardMaterial();await apply.applyEntityMaterial.call(f.context,entity('partial','0'));assert.equal(dispose,0);assert.equal(maps,0);await apply.applyEntityMaterial.call(f.context,entity('last'));assert.equal(dispose,1);assert.equal(maps,1);const resources=new ModelResources();resources.capture(f.target);resources.releaseKeeping();});
test('actual World removed target after async template creation never publishes or retains a bank',async()=>{const f=setup(true),template=new MeshStandardMaterial();let disposed=0;template.addEventListener('dispose',()=>disposed++);f.context.makeMaterial=async()=>{f.context.objects.delete('model');return template;};const old=f.mesh.material;await apply.applyEntityMaterial.call(f.context,entity('stale'));assert.equal(f.mesh.material,old);assert.equal(disposed,1);assert.deepEqual(f.context.replacementCloneCounts,{applications:0,created:0,reused:0,refused:0});const resources=new ModelResources();resources.capture(f.target);resources.releaseKeeping();});
test('actual World foreign mesh callback uses separate baseline clones without accepting sharing',async()=>{const f=setup(true);let callbacks=0;f.mesh.onBeforeRender=()=>{callbacks++;};await apply.applyEntityMaterial.call(f.context,entity('foreign'));const values=f.mesh.material as Material[];assert.notEqual(values[0],values[1]);assert.equal(callbacks,0);assert.deepEqual(f.context.replacementCloneCounts,{applications:1,created:0,reused:0,refused:2});const resources=new ModelResources();resources.capture(f.target);resources.releaseKeeping();});
