// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {BrowserWorld} from '../src/world';
import {StaticModelMatrices} from '../src/static-model-matrices';
function fixture(){const abort=new AbortController(),reader=new AbortController(),root=new THREE.Group(),scene=new THREE.Scene(),mesh=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshStandardMaterial());root.add(mesh);root.userData.modelLoaded=true;scene.add(root);const world=Object.create(BrowserWorld.prototype);let approved=true;Object.assign(world,{disposed:false,abort,scene,camera:new THREE.PerspectiveCamera(),objects:new Map([['model',root]]),entities:new Map([['model',{id:'model',type:'Model'}]]),modelReaders:new WeakMap([[root,reader]]),staticMatrices:new StaticModelMatrices(abort.signal),modelBatches:new Map(),renderer:{compileAsync:async()=>{}},options:{captureAssetAuthority:()=>({assertCurrent:()=>{if(!approved)throw Error('Stale approval');}})},compilingGraphics:0,recordLoadPhase(){}});return{world,root,scene,reader,abort,revoke(){approved=false;}};}
test('actual World attaches only its completed current Model publisher after exact successful shader readiness',async()=>{const f=fixture();await f.world.prepareGraphics(f.root,()=>true);assert.equal(f.world.staticMatrices.statistics.activeRoots,1);f.scene.updateMatrixWorld(true);assert.equal(f.world.staticMatrices.statistics.skippedTraversals,1);f.world.cancelGraphics(f.root);assert.equal(f.world.staticMatrices.statistics.retainedNodes,0);assert.equal(f.root.updateMatrixWorld,THREE.Object3D.prototype.updateMatrixWorld);f.abort.abort();});
test('actual World preserves default-off compiler behavior and never attaches primitive/avatar/unknown roots',async()=>{for(const variant of ['default','primitive','unloaded','unknown','obsolete']){const f=fixture();if(variant==='default')f.world.staticMatrices=undefined;if(variant==='primitive')f.world.entities.set('model',{id:'model',type:'Box'});if(variant==='unloaded')f.root.userData.modelLoaded=false;if(variant==='unknown')f.world.objects.clear();await f.world.prepareGraphics(f.root,()=>variant!=='obsolete');assert.equal(f.world.staticMatrices?.statistics.activeRoots??0,0);assert.equal(f.root.updateMatrixWorld,THREE.Object3D.prototype.updateMatrixWorld);assert.equal(f.world.compilingGraphics,0);f.abort.abort();}});
test('actual World authority, individual reader, revision and publisher removal immediately refuse cached matrix reuse',async()=>{for(const reason of ['approval','reader','revision','removed']){const f=fixture();await f.world.prepareGraphics(f.root,()=>true);if(reason==='approval')f.revoke();if(reason==='reader')f.reader.abort();if(reason==='revision')f.root.userData.shaderRevision++;if(reason==='removed')f.world.objects.clear();f.root.position.y=3;f.scene.updateMatrixWorld(true);assert.equal(f.root.matrixWorld.elements[13],3);assert.equal(f.world.staticMatrices.statistics.activeRoots,0);f.abort.abort();}});
test('actual World batch restore retires the guard before any immutable geometry hierarchy restoration',async()=>{const f=fixture();await f.world.prepareGraphics(f.root,()=>true);let restored=false;f.world.modelBatches.set(f.root,{value:{restore(){assert.equal(f.root.updateMatrixWorld,THREE.Object3D.prototype.updateMatrixWorld);restored=true;}}});f.world.restoreModelBatch(f.root);assert.equal(restored,true);assert.equal(f.world.staticMatrices.statistics.retainedNodes,0);f.abort.abort();});
