// Copyright 2026 Overte contributors
// SPDX-License-Identifier: Apache-2.0
// Actual World Image publication/replacement/RAF methods; platform readback is
// controlled here. Actual GPU/source-image fixtures are separate and pending.
import {test,type TestContext} from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';
import {BrowserWorld} from '../src/world';import type {Entity} from '../src/world-data';
function context(t:TestContext){
 const originals=['createImageBitmap','Worker','requestAnimationFrame'].map(name=>[name,Object.getOwnPropertyDescriptor(globalThis,name)]as const);
 t.after(()=>{for(const[name,d]of originals){if(d)Object.defineProperty(globalThis,name,d);else Reflect.deleteProperty(globalThis,name);}});
 Object.defineProperty(globalThis,'createImageBitmap',{configurable:true,value:async()=>({width:8,height:4,close(){}})});
 class AlphaWorker{onmessage?:(e:unknown)=>void;postMessage(data:{id:number}){queueMicrotask(()=>this.onmessage?.({data:{id:data.id,total:32,opaque:32,intermediate:0}}));}terminate(){}}
 Object.defineProperty(globalThis,'Worker',{configurable:true,value:AlphaWorker});Object.defineProperty(globalThis,'requestAnimationFrame',{configurable:true,value:()=>0});
 const w:any=Object.create(BrowserWorld.prototype),abort=new AbortController(),warnings:string[]=[],maps:THREE.Texture[]=[];let approved=true,rendered=0;
 Object.assign(w,{abort,disposed:false,imagePulseOwners:new Map(),modelReaders:new WeakMap(),modelGeometry:new WeakMap(),loadManagers:new Set(),loadPhases:new Map(),entities:new Map(),signatures:new Map(),objects:new Map(),meshCollisions:new Map(),localLights:new Set(),modelBatches:new Map(),scene:new THREE.Scene(),colliders:[],pendingModelColliders:[],graphicsWarmups:{cancel(){}},renderer:{capabilities:{getMaxAnisotropy:()=>16},render(){rendered++;}},metrics:{sample(){}},simulationClock:{advance:()=>0},enabled:false,camera:new THREE.PerspectiveCamera(),position:new THREE.Vector3(),self:new THREE.Group(),avatars:new Map(),yaw:0,pitch:0,thirdPerson:false,lastLightSelection:0,presentationEnabled:true,renderedFrames:0,options:{captureAssetAuthority:()=>({generation:'approval1',assertCurrent(){if(!approved)throw new DOMException('Revoked Image permission','AbortError');}}),onStatus:(text:string,kind:string)=>{if(kind==='warning')warnings.push(text);}},imageCache:{loader:()=>({loadAsync:async()=>{const map=new THREE.Texture({width:8,height:4}as TexImageSource);maps.push(map);return map;}})}});
 w.texture=async()=>{const map=new THREE.Texture({width:8,height:4}as TexImageSource);maps.push(map);return map;};w.prepareGraphics=async(root:THREE.Group)=>{root.userData.shadersReady=true;};
 t.after(()=>abort.abort());return{w,maps,warnings,abort,revoke:()=>{approved=false;},get renders(){return rendered;}};
}
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
const base:Entity={id:'owned',type:'Image',imageURL:'https://approved.example/image.png',dimensions:{x:4,y:4,z:.1},emissive:true};
function mesh(w:any){let found!:THREE.Mesh;w.objects.get(base.id).traverse((node:THREE.Object3D)=>{if(node instanceof THREE.Mesh)found=node;});return found;}
test('actual World uses default original aspect/UV/sampler and rebuilds every native effect change',async t=>{const{w,maps}=context(t);w.upsertEntities([base]);await tick();const first=mesh(w);assert.deepEqual(first.scale.toArray(),[4,2,.1]);assert.equal((first.material as THREE.MeshBasicMaterial).map!.wrapS,THREE.RepeatWrapping);
 const changes=[{keepAspectRatio:false},{subImage:{x:2,y:1,width:4,height:2}},{sampler:{wrapModeU:'mirror'}},{created:1000000,pulse:{period:0,colorMode:'in',alphaMode:'none'}}];let previous=w.objects.get(base.id);for(const change of changes){w.upsertEntities([{...base,...change}]);await tick();assert.notEqual(w.objects.get(base.id),previous);assert.equal(w.modelReaders.get(previous).signal.aborted,true);previous=w.objects.get(base.id);}assert.equal(maps.length,5);w.removeEntities([base.id]);assert.equal(w.imagePulseOwners.size,0);});
test('actual World existing RAF updates native pulse without material/source/program version changes',async t=>{const fixture=context(t),{w,maps}=fixture;t.mock.method(Date,'now',()=>2000);w.upsertEntities([{...base,color:{red:128,green:64,blue:32},alpha:.5,created:1000000,pulse:{period:4,colorMode:'in',alphaMode:'out'}}]);await tick();const item=mesh(w),material=item.material as THREE.MeshBasicMaterial,map=maps[0],before=[material.version,map.version,map.source.version];assert.equal(w.imagePulseOwners.size,1);assert.equal(material.transparent,true);w.animate(10);assert.equal(fixture.renders,1);assert.ok(Math.abs(material.opacity-.25)<1e-7);assert.ok(Math.abs(material.color.r-new THREE.Color().setRGB(64/255,32/255,16/255,THREE.SRGBColorSpace).r)<1e-7);assert.deepEqual([material.version,map.version,map.source.version],before);w.setPresentationEnabled(false);t.mock.method(Date,'now',()=>3000);w.animate(11);assert.ok(Math.abs(material.opacity-.25)<1e-7);w.removeEntities([base.id]);assert.equal(w.imagePulseOwners.size,0);assert.equal(fixture.renders,1);});
test('actual World cancellation/removal releases the pulse owner immediately and never updates disposed material',async t=>{const{w}=context(t);w.upsertEntities([{...base,created:0,pulse:{colorMode:'in'}}]);await tick();const material=mesh(w).material as THREE.MeshBasicMaterial;let disposed=0;material.addEventListener('dispose',()=>disposed++);w.removeEntities([base.id]);assert.equal(w.imagePulseOwners.size,0);assert.equal(disposed,1);w.animate(10);assert.equal(disposed,1);assert.equal(w.objects.size,0);});
test('actual World revoked permission drops dynamic ownership and stops material writes',async t=>{const{w,revoke,warnings}=context(t);w.upsertEntities([{...base,created:0,pulse:{colorMode:'in'}}]);await tick();const material=mesh(w).material as THREE.MeshBasicMaterial,before=material.color.clone();revoke();w.animate(10);assert.equal(w.imagePulseOwners.size,0);assert.deepEqual(material.color,before);assert.deepEqual(warnings,[]);w.removeEntities([base.id]);});
test('actual World pulse owner cap is explicit and no additional timers or graph owners are allocated',async t=>{const{w,warnings}=context(t);for(let i=0;i<512;i++)w.imagePulseOwners.set(new THREE.Group(),{stop(){}});w.upsertEntities([{...base,created:0,pulse:{colorMode:'in'}}]);await tick();assert.equal(w.imagePulseOwners.size,512);assert.ok(warnings.some((warning:string)=>warning.includes('capacity')));assert.ok(mesh(w));w.imagePulseOwners.clear();w.removeEntities([base.id]);});
test('actual World catches overriding Material ownership, rather than animating an abandoned material',async t=>{const{w,warnings}=context(t);w.upsertEntities([{...base,created:0,pulse:{colorMode:'in'}}]);await tick();const item=mesh(w),old=item.material as THREE.Material,replacement=new THREE.MeshBasicMaterial();item.material=replacement;old.dispose();w.animate(10);assert.equal(w.imagePulseOwners.size,0);assert.ok(warnings.some((warning:string)=>warning.includes('overriding Material')));w.removeEntities([base.id]);});

test('actual World warning callback revocation refuses late effect publication and frees the returned map',async t=>{const{w,maps,warnings,revoke}=context(t);const entity={...base,sampler:{wrapModeU:'border'}},root=new THREE.Group();w.objects.set(base.id,root);const previous=w.options.onStatus;w.options.onStatus=(message:string,kind:string)=>{previous(message,kind);revoke();};let disposals=0;const texture=w.texture;w.texture=async(...args:unknown[])=>{const map=await texture(...args);map.addEventListener('dispose',()=>disposals++);return map;};await assert.rejects(w.populateEntity(entity,root),{name:'AbortError'});assert.equal(disposals,1);assert.equal(root.children[0].children.length,0);assert.equal(w.imagePulseOwners.size,0);assert.equal(warnings.length,1);assert.equal(maps.length,1);});

test('actual World whole-session abort releases every Image pulse owner synchronously',async t=>{const{w,abort}=context(t);w.upsertEntities([{...base,created:0,pulse:{colorMode:'in'}}]);await tick();assert.equal(w.imagePulseOwners.size,1);abort.abort();assert.equal(w.imagePulseOwners.size,0);assert.equal(w.modelReaders.get(w.objects.get(base.id)).signal.aborted,false,'World cancellation uses the combined signal without mutating a separate reader');w.removeEntities([base.id]);});
