# Optional, hash-bound codec archive for isolated Android Phone builds.
# The default uses the existing Conan package without modification.
set(OVERTE_PHONE_ETC_ARCHIVE "" CACHE FILEPATH "Explicit isolated Phone ETC archive")
set(OVERTE_PHONE_ETC_ARCHIVE_SHA256 "" CACHE STRING "Expected SHA256 for isolated Phone ETC archive")
if(OVERTE_PHONE_ETC_ARCHIVE)
    if(NOT ANDROID OR NOT HIFI_ANDROID_APP STREQUAL "phoneInterface")
        message(FATAL_ERROR "ETC archive override is restricted to Android Phone")
    endif()
    if(NOT CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
        message(FATAL_ERROR "ETC archive override requires RelWithDebInfo")
    endif()
    if(NOT IS_ABSOLUTE "${OVERTE_PHONE_ETC_ARCHIVE}" OR NOT EXISTS "${OVERTE_PHONE_ETC_ARCHIVE}" OR IS_DIRECTORY "${OVERTE_PHONE_ETC_ARCHIVE}")
        message(FATAL_ERROR "ETC archive override must name an existing absolute file")
    endif()
    if(NOT OVERTE_PHONE_ETC_ARCHIVE_SHA256 MATCHES "^[0-9a-f]+$")
        message(FATAL_ERROR "ETC archive expected SHA256 is missing or invalid")
    endif()
    string(LENGTH "${OVERTE_PHONE_ETC_ARCHIVE_SHA256}" _phone_etc_hash_length)
    if(NOT _phone_etc_hash_length EQUAL 64)
        message(FATAL_ERROR "ETC archive expected SHA256 must contain 64 hexadecimal characters")
    endif()
    file(SHA256 "${OVERTE_PHONE_ETC_ARCHIVE}" _phone_etc_actual_hash)
    if(NOT _phone_etc_actual_hash STREQUAL OVERTE_PHONE_ETC_ARCHIVE_SHA256)
        message(FATAL_ERROR "ETC archive SHA256 mismatch")
    endif()
    if(NOT TARGET CONAN_LIB::etc2comp_EtcLib_RELWITHDEBINFO)
        message(FATAL_ERROR "Expected Conan ETC archive target is absent")
    endif()
    set_property(TARGET CONAN_LIB::etc2comp_EtcLib_RELWITHDEBINFO PROPERTY
        IMPORTED_LOCATION_RELWITHDEBINFO "${OVERTE_PHONE_ETC_ARCHIVE}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${OVERTE_PHONE_ETC_ARCHIVE}")
endif()
