# Platform-owned adapter around the unchanged Shared bootstrap.
if(DEFINED ENV{OVERTE_FDROID_CONAN_DIR})
    message(FATAL_ERROR "Pico requires its explicit host/target inputs; unset OVERTE_FDROID_CONAN_DIR")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/../../../common/cmake/overte-android-bootstrap.cmake")
if(ANDROID)
    foreach(_pico_dependency draco::draco glad::glad etc2comp::etc2comp nvidia-texture-tools::nvidia-texture-tools)
        if(NOT TARGET ${_pico_dependency})
            message(FATAL_ERROR "Pico target graph lacks ${_pico_dependency}; legacy precompiled paths are not a fallback")
        endif()
    endforeach()
endif()
foreach(_pico_tool SCRIBE GLSLANG SPIRV_CROSS SPIRV_TOOLS)
    if(NOT EXISTS "${PICO_${_pico_tool}}")
        message(FATAL_ERROR "Missing bound Pico host tool: ${_pico_tool}")
    endif()
    get_filename_component(_pico_tool_dir "${PICO_${_pico_tool}}" DIRECTORY)
    set(ENV{${_pico_tool}_DIR} "${_pico_tool_dir}")
endforeach()
