# Copyright 2013-2019 High Fidelity, Inc.
# Copyright 2020-2022 Vircadia contributors.
# Copyright 2021-2025 Overte e.V.
# SPDX-License-Identifier: Apache-2.0

name: Linux Server CI Build
# Keep in mind that GitHub Actions does not allow reading secrets during PR builds.

on:
  pull_request:
    types: [labeled]
  push:
    tags:
      # Release tags. E.g. 2024.06.1
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - "[0-9][0-9][0-9][0-9].[0-9][0-9].**"

permissions:
  contents: read

env:
  BUILD_TYPE: Release

jobs:
  build:
    # Only run tagged builds, or PRs when labeled as "server".
    if: github.event.label.name == 'server'|| github.event_name != 'pull_request'
    name: "${{matrix.os}}, ${{matrix.arch}}"
    strategy:
      matrix:
        include:
          - os: debian-12
            image: docker.io/overte/overte-server-build:2026-02-09-debian-12-amd64@sha256:deb5e9eeef5ad5df3b44c7bfd456fe73aa5c513aa16456c3983966578d8b0531  # Built from /tools/ci-script/deb_package/Dockerfile_x
            arch: amd64
            qt_source: system  # Which Qt Conan package to use. `system`, `source`, or `aqt`.
            runner: ubuntu-24.04  # Which GitHub Actions Runner to use. When using `image` this just needs to run the build container.

          - os: debian-12
            image: docker.io/overte/overte-server-build:2026-02-09-debian-12-aarch64@sha256:0f07adfb81fbd3c49f5f214641d82af49727fbc5201466ce3d2d6ec53beece34
            arch: aarch64
            qt_source: system
            runner: ubuntu-24.04-arm

          - os: debian-13
            image: docker.io/overte/overte-server-build:2026-02-09-debian-13-amd64@sha256:32e3cc2110915af6f3f20a5d9679a77300101a9c1d2f163b5a31d806125b1240
            arch: amd64
            qt_source: system
            runner: ubuntu-24.04

          - os: debian-13
            image: docker.io/overte/overte-server-build:2026-02-09-debian-13-aarch64@sha256:9efd666a3d4444cab8dac91b2eb991179c75ffc2a48dfac1153756d601085a06
            arch: aarch64
            qt_source: system
            runner: ubuntu-24.04-arm

          - os: debian-14
            image: docker.io/overte/overte-server-build:2026-07-17-debian-14-amd64@sha256:e8c0a1ad1c9cb98d5923d8376dddf5bed0fafec112bbf4e383c37fd5f154d612
            arch: amd64
            qt_source: system
            # GitHub's hosted Runner runs out of disk space.
            runner: depot-ubuntu-24.04

          - os: debian-14
            image: docker.io/overte/overte-server-build:2026-07-17-debian-14-aarch64@sha256:e3ad62338131925b8082c5a9f7290a457fcd9b41dca62af048886c1299c2b692
            arch: aarch64
            qt_source: system
            runner: ubuntu-24.04-arm

          - os: ubuntu-22.04
            image: docker.io/overte/overte-server-build:2026-02-09-ubuntu-22.04-amd64@sha256:74b3bd9c66e955f0fa354686554c9d427bd2761d4f37954388840325525860f5
            arch: amd64
            qt_source: system
            runner: ubuntu-24.04

          - os: ubuntu-22.04
            image: docker.io/overte/overte-server-build:2026-02-09-ubuntu-22.04-aarch64@sha256:7e06f30fbebb548f9dff73a50037863eacb3824987b894e801bb267be93629b1
            arch: aarch64
            qt_source: system
            runner: ubuntu-24.04-arm

          - os: ubuntu-24.04
            image: docker.io/overte/overte-server-build:2026-02-09-ubuntu-24.04-amd64@sha256:babe51f7c369e303aac67f0a9e7620707319b1d017a3ac13c4376b0d9fed056e
            arch: amd64
            qt_source: system
            runner: ubuntu-24.04

          - os: ubuntu-24.04
            image: docker.io/overte/overte-server-build:2026-02-09-ubuntu-24.04-aarch64@sha256:9e6db0532d80e6ccc826cdb340bad7422544bcc28df0f1e001b29cf168a8c1ce
            arch: aarch64
            qt_source: system
            runner: ubuntu-24.04-arm

          - os: fedora-42
            image: docker.io/overte/overte-server-build:2026-02-09-fedora-42-amd64@sha256:efb308f17ab5550178f65ef6e9eed52acfaf01b5a34e1271818a1512565768fb
            arch: amd64
            qt_source: system
            runner: ubuntu-24.04

          - os: fedora-42
            image: docker.io/overte/overte-server-build:2026-02-09-fedora-42-aarch64@sha256:c5492e8ca41d6b49059a05777499d11801473bc868f2d85aece0cab683e7954a
            arch: aarch64
            qt_source: system
            runner: ubuntu-24.04-arm

      fail-fast: false

    runs-on: ${{matrix.runner}}
    container: ${{matrix.image}}
    timeout-minutes: 240

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: false
        fetch-depth: 1
        persist-credentials: false

    - name: Read image environment variables
      # Bring some environment variables out of the Runner (Docker) image's environment into the Job environment.
      if: ${{matrix.image}}
      shell: bash
      run: |
        echo "RPM_SHORTHAND=$RPM_SHORTHAND" >> "$GITHUB_ENV"
        echo "CONAN_PROFILE=$CONAN_PROFILE" >> "$GITHUB_ENV"

    - name: Configure Build Environment 1
      shell: bash
      env:
        EVENT_NAME: ${{ github.event_name }}
        MATRIX_ARCH: ${{ matrix.arch }}
        MATRIX_OS: ${{ matrix.os }}
        PULL_REQUEST_SHA: ${{ github.event.pull_request.head.sha }}
        REF_NAME: ${{ github.ref_name }}
        REF_TYPE: ${{ github.ref_type }}
      run: |

        # Get git commit
        if [ "$EVENT_NAME" = "pull_request" ]; then
          echo "GIT_COMMIT_SHORT=${PULL_REQUEST_SHA:0:7}" >> "$GITHUB_ENV"
        else # tagged
          echo "GIT_COMMIT_SHORT=${GITHUB_SHA:0:7}" >> "$GITHUB_ENV"
        fi

        {
          echo "REFNAME=$REF_NAME"
          echo "JOB_NAME=$MATRIX_OS, $MATRIX_ARCH"
          echo "CONAN_CPPSTD=gnu20"
        } >> "$GITHUB_ENV"

        if [[ "$MATRIX_OS" =~ ubuntu|debian ]]; then
          echo "INSTALLER_EXT=deb" >> "$GITHUB_ENV"
        else  # RPM
          if [ "$MATRIX_ARCH" == "amd64" ]; then
            echo "INSTALLER_EXT=x86_64.rpm" >> "$GITHUB_ENV"
          else
            echo "INSTALLER_EXT=aarch64.rpm" >> "$GITHUB_ENV"
          fi
        fi

        # Tagged builds. E.g. release or release candidate builds.
        if [ "$REF_TYPE" == "tag" ]; then
          echo "OVERTE_RELEASE_TYPE=PRODUCTION" >> "$GITHUB_ENV"
        else
          echo "OVERTE_RELEASE_TYPE=PR" >> "$GITHUB_ENV"
        fi

    # Configuration is broken into multiple steps because you can't set an env var and also reference it in the same step
    - name: Configure Build Environment 2
      shell: bash
      env:
        EVENT_NAME: ${{ github.event_name }}
        MATRIX_OS: ${{ matrix.os }}
        PULL_REQUEST_NUMBER: ${{ github.event.number }}
        REF_NAME: ${{ github.ref_name }}
        REF_TYPE: ${{ github.ref_type }}
      run: |

        # Versioning
        if [ "$EVENT_NAME" = "pull_request" ]; then
          echo "DEBVERSION=${PULL_REQUEST_NUMBER}PR-$GIT_COMMIT_SHORT-$MATRIX_OS" >> "$GITHUB_ENV"
          echo "RPMVERSION=PR${PULL_REQUEST_NUMBER}.$GIT_COMMIT_SHORT" >> "$GITHUB_ENV"
        else # tagged
          echo "DEBVERSION=$REF_NAME-$GIT_COMMIT_SHORT-$MATRIX_OS" >> "$GITHUB_ENV"
          # We remove all dash characters from RPM versions, because rpmbuild doesn't allow dashes in version numbers.
          echo "RPMVERSION=${REFNAME//-}.$GIT_COMMIT_SHORT" >> "$GITHUB_ENV"
        fi

        if [ "$REF_TYPE" == "tag" ]; then
          echo "RELEASE_NUMBER=$REF_NAME" >> "$GITHUB_ENV"
        fi

    - name: Configure Build Environment 3
      shell: bash
      env:
        MATRIX_ARCH: ${{ matrix.arch }}
        MATRIX_OS: ${{ matrix.os }}
      run: |

        if [[ "$MATRIX_OS" =~ ubuntu|debian ]]; then
          if [ "$MATRIX_ARCH" == "aarch64" ]; then
            echo "ARTIFACT_PATTERN=overte-server_${DEBVERSION}-1_arm64.$INSTALLER_EXT" >> "$GITHUB_ENV"
          else # amd64
            echo "ARTIFACT_PATTERN=overte-server_${DEBVERSION}-1_amd64.$INSTALLER_EXT" >> "$GITHUB_ENV"
          fi
        else  # RPM
          echo "ARTIFACT_PATTERN=overte-server-$RPMVERSION-1.$RPM_SHORTHAND.$INSTALLER_EXT" >> "$GITHUB_ENV"
        fi

    - name: Install Conan dependencies
      uses: ./.github/actions/conan-install
      with:
        qt_source: ${{matrix.qt_source}}
        build_type: ${{env.BUILD_TYPE}}
        cppstd: ${{env.CONAN_CPPSTD}}
        conan_profile: ${{env.CONAN_PROFILE}}

    - name: Configure CMake
      shell: bash
      # This syntax requires CMake 3.23.
      run: >-
        cmake --preset "conan-${BUILD_TYPE,,}"
        "-DOVERTE_RELEASE_TYPE=$OVERTE_RELEASE_TYPE"
        "-DOVERTE_RELEASE_NUMBER=$RELEASE_NUMBER"
        "-DOVERTE_GIT_COMMIT_SHORT=$GIT_COMMIT_SHORT"
        -DOVERTE_BUILD_SERVER=true
        -DOVERTE_BUILD_TOOLS=true
        -DOVERTE_BUILD_CLIENT=false

    - name: Build Domain Server
      shell: bash
      run: cmake --build --target domain-server --preset conan-release

    - name: Build Assignment Client
      shell: bash
      run: cmake --build --target assignment-client --preset conan-release

    - name: Build Oven
      shell: bash
      run: cmake --build --target oven --preset conan-release

    - name: Package
      working-directory: pkg-scripts
      shell: bash
      env:
        MATRIX_OS: ${{ matrix.os }}
      run: |
        if [[ "$MATRIX_OS" = ubuntu* || "$MATRIX_OS" = debian* ]]; then # Debian
          ./make-deb-server
        else # RPM
          ./make-rpm-server
        fi

    - name: Upload artifact to GitHub
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        archive: false
        path: pkg-scripts/${{ env.ARTIFACT_PATTERN }}

    - name: Output debug information
      if: always()
      uses: ./.github/actions/debug-info
